docs/architecture/decisions/0010-move-ci-cd-to-github-actions.md, docs/install.rst, docs/pipeline.rst
This changeset updates documentation around the move from CircleCI and Gitlab to GH Actions, which is currently in progress.
~It's not quite the ideal time to land this, but making a draft PR now so that it's ready to go when we cut over~ We're just about to unplug the old CI tests, and the new ones are OK, so it makes sense to update the docs now
Resolves #12950
=> Add documentation for CI refactoring

bedrock/newsletter/templates/newsletter/management.html, l10n/en/mozorg/newsletters.ftl
Adds message underneath the unsubscribe all checkbox.
#13050
First get your token here: https://www.mozilla.org/en-US/newsletter/recovery/
Then open `http://localhost:8000/en-US/newsletter/existing/YOUR_TOKEN_HERE/`
=> Add message to email preference center on timing of unsubscribes (Fixes #13050)

.github/workflows/send_mozorg_fluent_strings_to_l10n_org.yml, .github/workflows/send_pocket_fluent_strings_to_l10n_org.yml
Looks like the env var for the auth vars, while present, needed explicitly passing into the shell script which runs the Docker container. Without that, the automatic attempts to open a PR on mozilla-l10n/www-l10n failed
Workflow not working: https://github.com/mozilla/bedrock/actions/runs/4891935488
Workflow now working: https://github.com/mozilla/bedrock/actions/runs/4892916392/jobs/8735242756, resulting in this PR https://github.com/mozilla-l10n/www-l10n/pull/327/files
Am also updating the equivalent Pocket command
=> Fix failure to open L10N-org PRs, due to missing auth

bedrock/newsletter/tests/test_views.py, bedrock/newsletter/urls.py, bedrock/newsletter/views.py, media/js/newsletter/management.es6.js
Updates newsletter preferences page to pull the list of all available newsletters from bedrock, rather than directly from basket.
#13031
First get your token here: https://www.mozilla.org/en-US/newsletter/recovery/
Then open `http://localhost:8000/en-US/newsletter/existing/YOUR_TOKEN_HERE/`
I also pushed this to demo1 for testing: https://www-demo1.allizom.org/
=> Use local newsletter data for email prefs page instead of basket (Fixes #13031)

bedrock/security/templates/security/bug-bounty/faq-webapp.html, bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html, bedrock/security/templates/security/web-bug-bounty.html
Add notes about migrating web bug bounty to hackerone
Main page
Bounty table
=> add notes about migrating to hackerone

bedrock/mozorg/templates/mozorg/about/index.html
The template was referencing the wrong string ID. Ref: https://github.com/mozilla/bedrock/blob/main/l10n/en/mozorg/about.ftl#L11
http://localhost:8000/about/ and you'll probably have to view source to see the meta description.
=> Fix string ID for about page description [no bug]

media/css/products/vpn/download.scss, media/css/products/vpn/platform-download.scss
VPN team wanted to reduce padding on the download pages so content can appear over-the-fold for whoever opens the page, so they can see the download buttons + instructions on load instead of scrolling
Based off https://github.com/mozilla/bedrock/issues/11875
=> Reduce padding on VPN download pages

.github/workflows/cdn_tests.yml
Reinstates https://github.com/mozilla/bedrock/pull/13105 which was lost in a tragic rebasing moment before coffee 🙈
=> Resintate: Port CDN tests to Github Actions

.github/workflows/download_tests.yml, .github/workflows/integration_tests.yml
These tests were effectively disabled via restrictive configuration in GitLab. We're reinstating them here as a scheduled job rather than part of main integration tests, because we don't need them to run at every step, and they put a reasonably high load on the origin servers.
The tests now run against the CDN, which will still put load on prod for the less common options and also because the tests use HEAD not GET, so we should keep an eye on loading. However, autoscaling should keep things happy
Resolves #12946
As with https://github.com/mozilla/bedrock/pull/13105 this may need some tuning after merge
=> Reinstate download tests, now via GHA

.github/workflows/github_asana_bridge.yaml
The relevant secrets have already been added to the repo secrets and the 'Asana' label has been made
=> Plug in mozmeao/github-asana-bridge so that we can make Asana Tasks from GH Issues

docs/conf.py, docs/install.rst
This changeset fixes search in our ReadTheDocs site 
The workaround comes from https://github.com/readthedocs/sphinx_rtd_theme/issues/1452 which also references a potential longer-term fix 
No ticket
=> Docs search fixup

.github/workflows/send_mozorg_fluent_strings_to_l10n_org.yml, .github/workflows/send_pocket_fluent_strings_to_l10n_org.yml, docs/l10n.rst
Since moving to GHA for opening L10N PRs, we've lost the (two) automatic retries that Gitlab supported, which came in handy when the L10N PR update failed. 
We're seeing more of those failures than expected, which I think is a race condition between the Docker image building vs the L10N automation happening - before it all happened in one place in GL, now it's spread across two places in GHA.
To deal with this, this changeset adds a schedule so that the tasks are run every three hours, just in case. The PR-opening script is idempotent, so can be run multiple times without creating duplicate FTL strings, etc 
I've also improved documentation a bit, including linking to the relevant automation in GH
=> Make L10N PR automation more robust + better documented

.stylelintrc, media/css/careers/_utils.scss
Looks like we were still ignoring careers CSS files in our stylelint config, from when we ported the pages over from the old careers site.
=> Lint careers scss files

docs/firefox-accounts.rst, media/js/base/fxa-attribution.es6.js, media/js/base/fxa-bundle-init.es6.js, media/static-bundles.json, tests/unit/karma.conf.js, tests/unit/spec/base/fxa-attribution.js
Adds support for automated coupon passing to the VPN landing page.
This started out simpler, but I took the opportunity to do a bit of a refactor that should hopefully simplify making more changes like this in the future. I also renamed `fxa-utm.js` to `fxa-attribution.js`, since the file has (for a while now) handled more than just UTM passing.
Also updated our test coverage 
#13043
Open each of the following URLs below, scroll down to the pricing section and inspect the "Get 12-month plan" link `href`. Then verify that the `coupon` parameter and any additional parameters are passed through to the subscription link.
Additional test:
Open https://www-demo1.allizom.org/en-US/firefox/113.0/whatsnew/?geo=gb and click "Get Mozilla VPN".
=> Pass coupon URL parameter to FxA subscription links (Fixes #13043)

.github/workflows/send_mozorg_fluent_strings_to_l10n_org.yml, .github/workflows/send_pocket_fluent_strings_to_l10n_org.yml
Noticed a fair few failure notifications for this over the weekend from my personal fork of bedrock. This should hopefully prevent it from trying to run?
=> Stop trying to open l10n PRs from bedrock forks

bedrock/base/templates/macros.html, bedrock/base/templates/product-all-unified-macros.html, bedrock/firefox/templates/firefox/all-unified.html, bedrock/firefox/templates/firefox/browsers/index.html, bedrock/firefox/templates/firefox/browsers/mobile/compare.html, bedrock/firefox/templates/firefox/browsers/mobile/focus.html, bedrock/firefox/templates/firefox/browsers/mobile/get-ios.html, bedrock/firefox/templates/firefox/browsers/mobile/ios.html, bedrock/firefox/templates/firefox/facebookcontainer/index.html, bedrock/firefox/templates/firefox/mobile/get-app.html, bedrock/firefox/templates/firefox/mobile/index.html, bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/firefox/templates/firefox/releases/release-notes.html, bedrock/firefox/templates/firefox/welcome/page4.html, bedrock/firefox/templates/firefox/welcome/page6.html, bedrock/landing/templates/landing/firefox/fx100.html
Add a class to App and Play Store badges for GA4 tracking.
- adds the class 'ga-product-download' to the Play Store macro
- introduces an App Store macro which includes the class 'ga-product-download' 
n/a
http://localhost:8000/en-US/firefox/browsers/
http://localhost:8000/en-US/firefox/browsers/mobile/?xv=legacy
http://localhost:8000/en-US/firefox/browsers/mobile/
http://localhost:8000/en-US/firefox/ios/109.0/releasenotes/
http://localhost:8000/en-US/firefox/109.0/releasenotes/
http://localhost:8000/en-US/firefox/releases/
http://localhost:8000/en-US/firefox/welcome/4/
http://localhost:8000/en-US/firefox/welcome/6/
http://localhost:8000/en-US/landing/firefox/fx100
http://localhost:8000/en-US/firefox/facebookcontainer/ …
=> Adds a class to App and Play Store badges for GA4 tracking.

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html, bedrock/security/templates/security/web-bug-bounty.html
Remove absearch from scope since it is being deprecated. Also remove low severity issue from examples to prevent confusion about paying it.
=> remove absearch from scope, remove low severity issue from examples

bedrock/pocket/urls.py, docs/contribute.rst, docs/l10n.rst, docs/pipeline.rst
* Add comment to remind us all that github.com/Pocket/dotcom-gateway needs updating when we add routes
* Minor docs tidying
* Update documentation to make it easier to discover the URLs of the various Mozorg and Pocket sites (resolves #12690)
=> Update Pocket Mode docs

bedrock/products/templates/products/relay/base.html, bedrock/products/templates/products/relay/faq.html, bedrock/products/urls.py, l10n/en/products/relay/faq.ftl, l10n/en/products/relay/shared.ftl, media/css/products/relay/faq.scss, media/static-bundles.json
Adds the FAQ page from relay site to bedrock
Relay URL: https://relay.firefox.com/faq/
Talked with Elise about using the protocol details component - so the page is not a 1:1 match
#12932 
=> Add Relay FAQ Page

bedrock/products/forms.py, bedrock/products/templates/products/relay/includes/waitlist-base.html, bedrock/products/templates/products/relay/waitlist/phone.html, bedrock/products/templates/products/relay/waitlist/vpn-relay.html, bedrock/products/templates/products/relay/waitlist/vpn.html, bedrock/products/urls.py, bedrock/products/views.py, l10n/en/products/relay/waitlist.ftl, media/css/products/relay/waitlist.scss, media/js/products/relay/waitlist.es6.js, media/static-bundles.json
Adds relay waitlist pages to bedrock for the VPN + Relay Bundle and Phone Masking
- Phone masking wait list page https://relay.firefox.com/phone/waitlist/
- VPN / Relay bundle wait list page https://relay.firefox.com/vpn-relay/waitlist/
Something to note - the original relay pages use notification bars, but I decided to use the standard newsletter Thank you messaging instead of notification bars
#12933
- http://localhost:8000/products/relay/waitlist/vpn/
- http://localhost:8000/products/relay/waitlist/phone/
=> Relay waitlist

bedrock/base/templates/includes/protocol/footer/footer.html, bedrock/mozorg/templates/mozorg/contribute.html, l10n/en/footer.ftl
This changeset:
* changes the link for "Translate Content" on /contribute/ to point to Pontoon directly
* adds a "Localize Mozilla" link in the Support column of the footer, also pointing to Pontoon
Both sets of links append the same UTM params that other links on the page do
A new Fluent string has been added, so the new footer link will not be localied immediately for non-en locales. Is this a problem, given the widespread (if small) impact of the additional link?
This changeset should land before the end of H2 as it's tied to Q2 goals for the L10N team
Resolves #13045 
* View http://www-demo5.allizom.org/contribute/ where you can see the footer change and the "Translate Content" card change in action
=> Localization-related links update

bedrock/firefox/templates/firefox/flashback/index.html
Adds the convert experiment block to /firefox/flashback/
This is part of my Marketing Manifesto goal. It is just to test the system since it hasn't been used recently and will not be enabled on the production server.
http://localhost:8000/en-US/firefox/flashback
=> Add Convert experiment block to /firefox/flashback

bedrock/mozorg/redirects.py, tests/redirects/map_301.py, tests/redirects/map_globalconf.py
...so that Google indexes the right page. A 302 Found isn't enough - see https://github.com/mozilla/bedrock/issues/13211 for context
Resolves #13211
=> Add permanent redirect for /en/ to /en-US/

bedrock/legal_docs/tests/test_base.py, bedrock/legal_docs/views.py, bedrock/mozorg/views.py, bedrock/privacy/views.py, bedrock/settings/base.py
When used in combination with the production CDN, we ended up with incorrect country code being returned in these pages
For background see https://github.com/mozilla/bedrock/issues/13229
Resolves #13229
=> Drop use of cache_page helper

bedrock/pocket/templates/pocket/firefox/new-tab-learn-more.html
The Pocket New Tab page had a broken image URL in prod because the image tag in the code wasn't using an appropriate image helper that we typically use in Bedrock. So I just wrapped it in a `static()` image helper.
This is what the section currently looks like in prod:
<kbd>![Screenshot 2023-06-06 at 5 32 32 PM](https://github.com/mozilla/bedrock/assets/42309026/698a5c91-c83d-418b-9663-621c7cdb03a7)</kbd>
But it should look like this:
<kbd>![Screenshot 2023-06-06 at 5 33 09 PM](https://github.com/mozilla/bedrock/assets/42309026/0acea8ca-1d32-4fde-b68a-6923856f6b9f)</kbd>
The image URL in prod is shown as: 
```
src="/media/img/pocket/new-tab/hidden-gem.svg"
```
But it should look like the following:
```
src="https://www.mozilla.org/media/img/pocket/new-tab/fortress.41ba0083d924.svg"
``` …
=> added static image helper

bedrock/careers/templates/careers/benefits.html
Requested change to the copy on the careers/benefits page. Request [here](https://mozilla.slack.com/archives/C4XSHENBY/p1684522566570639) and more info in [google doc](https://docs.google.com/document/d/1BFWvIfgB75RTWGJ76tEE40C2W8GMnrBVaf402UM1AVI/edit?usp=sharing)
n/a
=> Update copy on careers/benefits

bedrock/privacy/templates/privacy/convert-opt-out.html, bedrock/settings/__init__.py, media/js/base/convert-snippet.js
Update Convert CDN URL.
n/a
Convert [introduced a new CDN](https://support.convert.com/hc/en-us/articles/11205619183373-What-s-new-Nov-2022) that is faster than the one we are referencing.
1. Pick a page on the site and add the convert bundle in an experiments block. [Docs here](https://bedrock.readthedocs.io/en/latest/abtest.html#convert-experiments).
2. Disable all your ad-blockers and DNT.
3. Open the network panel and reload the page.
4. Watch for the convert URL, make sure it's a 200.
=> Update Convert CDN URL

media/js/base/datalayer-productdownload.es6.js, media/js/firefox/all/all-downloads-unified-init.es6.js, media/static-bundles.json, tests/unit/karma.conf.js, tests/unit/spec/base/datalayer-begincheckout.js, tests/unit/spec/base/datalayer-productdownload.js
Adds GA4 custom event product_download and adds event tracking to downloads on /all.
Adds datalayer-product-download.es6.js and converts all-downloads-unified-ini to es6 to allow importing it.
https://github.com/mozilla/bedrock/issues/13238
https://www-demo4.allizom.org/en-US/firefox/all/ 
Bedrock code:
GTM:
- Switch to the workspace in the www.mozilla.org workspace called "GA4 product_download"
- Click "preview" to open the tag assistant website.
- Add the domain https://www-demo4.allizom.org/en-US/firefox/all/ and click it 
- Disable add-ons and toggle off DNT, etc until tag assistant indicates it has a connection
- Navigate to the /all page and start clicking the download/store buttons
- Return to the tag assistant window and look through the 'product_download' …
=> Adds GA4 custom event product_download to /all

bedrock/firefox/tests/test_views.py, bedrock/firefox/urls.py
Adds a comment and a test to ensure that if this URL goes away developers will get an error with a Github issue reference.
=> Fix #13253: Ensure /firefox/set-as-default/thanks/ exists for Firefox

media/js/base/datalayer-begincheckout.es6.js, media/js/base/datalayer-productdownload.es6.js, tests/unit/spec/base/datalayer-begincheckout.js, tests/unit/spec/base/datalayer-productdownload.js
- add checks that the dataLayer exists to two new tests (this does not actually fix the test failure because the check is executed when the file loads and not when the function calls are activated, but it seems prudent)
- change the test to set the dataLayer array to be empty instead of deleting it, which was what was causing the problem
- fix the test message, which was missing a word
#13259
`npm run karma`
=> Fix dataLayer test failure #13259

bedrock/firefox/tests/test_views.py, bedrock/firefox/views.py
Updates the default value for `dlsource` to equal `mozorg`, instead of `(not set)` like we do for other stub attribution values. This should hopefully ensure the value is always `mozorg` in cases where there's an issue validating other data.
https://bugzilla.mozilla.org/show_bug.cgi?id=1836278
Hopefully the updated tests should be simple enough that this only needs code level review?
=> Set default value for dlsource to 'mozorg' instead of '(not set)' (Bug 1836278)

l10n/en/mozorg/newsletters.ftl
Adds new newsletter strings for translation. These won't be used directly until July 5th, so this PR is only adding them for translation at this time.
#13250
=> Add new translated newsletter strings (Issue #13250)

bedrock/mozorg/templates/mozorg/advertising.html, media/css/mozorg/advertising.scss
- Updates requested headline
- Changes CSS classes to prevent ad-blockers removing the header (tested with UBlock Origin)
#13294
http://localhost:8000/en-US/advertising/
=> Update advertising page heading and class names (Fixes #13294)

bedrock/products/tests/test_helper_misc.py, bedrock/settings/base.py
Changes to Euro for Bulgaria, Romania, and Hungary. Paypal doesn't currently support local currencies in Bulgaria or Romania, and doesn't support decimals in Hungarian Forint (which I think presents complications with discount codes if we can't ensure it always rounds to a whole number).
This also fixes the locale code for Czech, which is `cs` not `cz` (CZ is the country code, I just got them mixed up and glad I had a chance to fix it here before it broke something in production).
#13299 
And a Jira ticket with other details and context (Mozilla-only): https://mozilla-hub.atlassian.net/browse/VPN-5079
http://localhost:8000/hu/products/vpn/?geo=HU
http://localhost:8000/en-US/products/vpn/?geo=BG
http://localhost:8000/en-US/products/vpn/?geo=RO
Note: the VPN pages aren't currently localized …
=> Update VPN pricing for Romania, Bulgaria, and Hungary [fix #13299]

bedrock/base/views.py
Alternatively we can remove `GeoTemplateView` completely, since nothing in the current codebase is using it, based on my searching. It seems like most people just use the underlying `get_country_from_request`. If it's not useful, we can drop the whole class.
=> Set `geo_template_names` default to a dict to avoid an `AttributeError`

bedrock/products/templatetags/misc.py, bedrock/products/tests/test_helper_misc.py, media/js/base/fxa-attribution.es6.js, tests/unit/spec/base/fxa-attribution.js
Change the class name that triggers adding attribution information to FxA links to not mention `vpn`.
(Outline the main things changed, and if there are particular parts that need extra scrutiny.)
Fix #13297 
I think this is simple find/replace. 🤞 Did I miss any spots?
=> Generalize FxA/VPN attribution JS class fix #13297

bedrock/products/forms.py, bedrock/products/templates/products/relay/faq.html, bedrock/products/templates/products/relay/includes/bundle.html, bedrock/products/templates/products/relay/includes/macros.html, bedrock/products/templates/products/relay/includes/matrix.html, bedrock/products/templates/products/relay/includes/waitlist-base.html, bedrock/products/templates/products/relay/invite.html, bedrock/products/templates/products/relay/landing.html, bedrock/products/templates/products/relay/premium.html, bedrock/products/templates/products/relay/waitlist/bundle.html, bedrock/products/templates/products/relay/waitlist/phone.html, bedrock/products/templates/products/relay/waitlist/premium.html, bedrock/products/templatetags/misc.py, bedrock/products/urls.py, bedrock/products/views.py, bedrock/settings/base.py, l10n/en/products/relay/bundle.ftl, l10n/en/products/relay/faq.ftl, l10n/en/products/relay/features.ftl, l10n/en/products/relay/landing.ftl, l10n/en/products/relay/matrix.ftl, l10n/en/products/relay/premium.ftl, l10n/en/products/relay/shared.ftl, l10n/en/products/relay/waitlist.ftl, media/css/products/relay/matrix.scss
Add Relay pricing and display logic.
- Add HTML and CSS for pricing toggle and display
- Add pricing and availability lookup tables for Relay Premium, phone, and VPN bundle
- Only display purple bundle promo in CA and US
- Display pricing according to geolocation and language in bundle promo, and pricing matrix for desktop and mobile
- Add waitlist page for Premium
- Add macros to display pricing and waitlist buttons
- Remove unreferenced Fluent string IDs
#13204
http://localhost:8000/en-US/products/relay/
http://localhost:8000/en-US/products/relay/premium
http://localhost:8000/en-US/products/relay/waitlist
Add the query string `?geo={COUNTRY_CODE}` (e.g. AF, CA, DE) to the URL to help test geolocation setup.
**To test this work:**
This PR builds on several previous PRs that have had …
=> Add Relay pricing and display logic #13204

bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py, bedrock/products/templates/products/relay/includes/matrix.html, bedrock/settings/base.py
Use relay_fxa_button helper for Get free Relay link, so we link to staging on dev server.
- Add setting for the link to the Relay product
- Update helper to use Relay setting
- Update test to check prod settings
=> Use relay_fxa_button helper for Get free Relay link

bedrock/mozorg/templates/mozorg/home/includes/ctd-promo-de.html, media/css/firefox/challenge-the-default/_hero.scss, media/css/firefox/challenge-the-default/index.scss
We just launched the CTD campaign and noticed a few front-end fixes that needed some TLC.
=> Quick CTD fixes

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
(Temporarily) remove Hubs from web-eligible-sites as we've paused their involvement until end of August at the earliest
This removes a stanza of HTML from the web-eligible-sites page
If relevant:
=> Remove Hubs from web-eligible-sites

bedrock/settings/base.py, docs/firefox-accounts.rst, media/js/base/fxa-attribution.es6.js, media/js/base/fxa-product-button.es6.js
The stage URL has changed from `stage-vpn.guardian.nonprod.cloudops.mozgcp.net` to `stage.guardian.nonprod.cloudops.mozgcp.net` (minus the `-vpn` bit) and the previous URL will soon stop working.
#13312 
http://localhost:8000/products/vpn/download/
=> Update VPN stage endpoint [fix #13312]

bedrock/products/templatetags/misc.py, bedrock/products/tests/test_helper_misc.py, bedrock/settings/base.py
Add unit tests for helpers for Relay pages
- added tests
- tweaked comments to improve docs
- removed comments separating relay email and phone plans from bundle
#12876 
In the venv: `py.test lib bedrock/products/tests/test_helper_misc.py`
=> Unit tests for relay helpers

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-na-windows.html, media/js/firefox/whatsnew/whatsnew-115-na-win7.js
`6.1` -> `6.3`
http://localhost:8000/en-US/firefox/115.0/whatsnew/
Firefox on Windows 8.1 or lower should redirect to `?xv=windows`. Windows 10 and higher should get the regular page promoting addons (or Fx mobile for en-GB, or VPN for wave vi countries).
=> Update WNP 115 to target Windows 8.1 and lower [#13277]

media/js/base/site.js, tests/unit/spec/base/site.js
With yesterday's release of [Safari Tech Preview 173](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-173), Safari on macOS now supports Web Apps. This results in `navigator.standalone` existing, which in turn means that [Safari on macOS users will be prompted to install the iOS version of Firefox](https://github.com/mozilla/bedrock/assets/344777/8a7a85e7-018d-44bf-a4d5-e395cf10b904) on https://www.mozilla.org/en-US/firefox/new/
This PR changes that to look for `window.ontouchstart` instead, as Safari on macOS does not support those. Thanks to @nt1m for that suggestion.
n/a
n/a
If relevant:
=> Use window.ontouchstart to detect Safari on iPad.

bedrock/firefox/templates/firefox/challenge-the-default/landing.html, media/css/firefox/challenge-the-default/_hero.scss, media/js/firefox/challenge-the-default/animate-pop-in.es6.js
Animated logo was bugged out on Safari and iOS, this reverts to using the old static image
=> Revert to using old logo

bedrock/products/templates/products/relay/base.html
Remove duplicate page descriptions from Relay pages
Talked to Adria about it and she said no description is better than a duplicate one.
#12876
=> Remove duplicate page descriptions from Relay pages

bedrock/products/templates/products/vpn/platforms/v2/linux.html, bedrock/products/templates/products/vpn/platforms/v2/mobile.html, l10n/en/products/vpn/platforms/linux_v2.ftl, l10n/en/products/vpn/platforms/mobile_v2.ftl
Noticed a few issues while reviewing the Italian translation.
https://www-dev.allizom.org/en-US/products/vpn/desktop/linux/
* The first list item is missing a period.
* [Launchpad](https://help.launchpad.net/Legal) should be spelled uppercase
https://www-dev.allizom.org/en-US/products/vpn/mobile/
* All list items but the first are missing a period.
=> Fix small copy errors in VPN Linux and Mobile pages

bedrock/firefox/templates/firefox/includes/download-button.html, l10n/en/download_button.ftl, media/css/firefox/developer/includes/intro.scss, media/css/protocol/components/_download-button-ie.scss, media/css/protocol/components/_download-button.scss, media/js/base/site.js, tests/unit/spec/base/site.js
Firefox desktop is ending support on OS versions less than or equal to Windows 8.1, and the same on macOS 10.14 and below. Existing users on these systems are being migrated to Firefox ESR.
Because of this, there is also an ask to prevent people downloading Firefox on these systems in the future from the website. They should instead be directed toward Firefox ESR. This needs to happen before Firefox 116 is released (August 1st).
Firefox 116 is soon to hit Beta however (July 4th), so we need to tackle pre-release channels first as a priority.
That's what this PR sets out to do by:
- Hiding Beta/Dev Edition/Nightly download buttons on <= Win 8.1 and <= macOS 10.14.
- Displaying a message in its place directing people to download Firefox ESR instead.
This needs some careful testing. I'd …
=> Direct Beta/Dev/Nightly downloads on old OS versions to ESR (Issue #13317)

bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json
Adds strings that we're exposed for L10n in https://github.com/mozilla/bedrock/pull/13291 to `newsletter-strings.json`
This should **not be merged** until July 5th
#13250
JSON should show:
```
"mozilla-accounts": {
"description": "Get tips from Mozilla on how to get the most out of your account.",
"title": "Firefox Accounts"
},
```
```
"firefox-accounts-journey": {
"description": "Welcome emails",
"title": "Welcome emails that get you started using our products and services."
},
```
http://localhost:8000/en-US/newsletter/newsletter-strings.json
=> [July 5th] Add new strings to newsletter-strings.json (Fixes #13250)

bedrock/firefox/templates/firefox/includes/download-button.html
Same as https://github.com/mozilla/bedrock/pull/13349 but I didn't realize it needed to be `esr-next` :/
=> ESR download link aliases should use esr-next (Issue #13317)

media/js/base/site.js, tests/unit/spec/base/site.js
This updates the horrific logic required to work out the correct Windows version using Client Hints.
#13317
Demo link: https://www-demo2.allizom.org/en-US/firefox/channel/desktop/
Using **Chrome on Windows**:
=> Update Client Hints Windows version detection (Issue #13317)

bedrock/firefox/templates/firefox/nightly/whatsnew.html, l10n/en/firefox/nightly/whatsnew.ftl
This changeset adds a link to our new FirefoxNightly Mastodon account on the Nightly whatsnew.html page.
* Added an updated string to mention and link to our FirefoxNightly Mastodon account
* Previously translated string without the mastodon link is used as a fallback
Bug 1841816 - Add link to mastodon feed before twitter feed in nightly release notes - https://bugzil.la/1841816
=> Bug 1841816 :  Update nightly/whatsnew template to also link to Mastodon

bedrock/firefox/templates/firefox/welcome/page15/base.html
Small update to make sure that we can equally compare the same number of people in both variations.
#13303
You may need to clear cookies between testing each variation
=> Update welcome/15 referral_id if no variation is set (Issue #13303)

bedrock/firefox/views.py
Removes the `ftl_file_is_active` condition allowing the template to be shown to all target countries, defaulting to English if it isn't localized. This disregards the user's preferred language and forces English instead of the localized fallback template. It's not an ideal user experience and isn't how we normally handle l10n on the what's new page, but stakeholders have chosen to take this calculated risk.
http://localhost:8000/firefox/115.0/whatsnew/
Ideally this should be tested in prod mode because of the FTL activation rule (otherwise you'll see mixed content at the locale URL instead of being redirected to `/en-US/`). If you restart in prod mode also be sure you add `SWITCH_VPN_WAVE_VI=on` to your env file.
=> Update WNP 115 view logic to show English to target countries [#13215]

media/js/newsletter/newsletter.es6.js
Send a second dataLayer event when someone subscribes to a newsletter, to be processed by GA4.
Small code change but necessary because GA4 is going to be counting the number of subscriptions not the number of form submissions.
#13238 
Fix #13348
- find a few newsletters and look at the dataLayer in the console after you fill them out (use success@example.com to fill them out if you don't want a subscription 😉 )
=> Send dataLayer event for GA4 for newsletter subscriptions

bedrock/products/templates/products/relay/includes/matrix.html, bedrock/products/templates/products/relay/landing.html, bedrock/products/templates/products/relay/premium.html, bedrock/products/templates/products/relay/pricing.html, bedrock/products/urls.py, bedrock/products/views.py
Create page which is only the pricing matrix, like the [VPN pricing page](https://www.mozilla.org/en-US/products/vpn/pricing/).
- add page, url, and view
- fill in missing variable from some strings
- update entry point info
#12876 
http://localhost:8000/en-US/products/relay/pricing/
=> Give pricing matrix its own page

docs/attribution/0001-analytics.rst, docs/attribution/0006-pocket-analytics.rst, docs/vpn-subscriptions.rst
Add documentation to add GA4 begin_checkout event
- reorganized docs to give Pocket a separate page from moz-org, changing all heading levels
- noted some outdated documentation in the data-attribute section
- added a section on GA4 with the begin_checkout info
- added references to it from the VPN docs.
#13012 
[Compile the docs and run them locally.](https://bedrock.readthedocs.io/en/latest/install.html#documentation)
http://127.0.0.1:8100/attribution/0001-analytics.html
=> Add documentation to add GA4 begin_checkout event

bedrock/privacy/templates/privacy/faq.html, l10n/en/privacy/faq.ftl
Minor copy change on privacy FAQ page to remove mention of Firefox Pioneer, which is now 404.
#13387
http://localhost:8000/en-US/privacy/faq/
=> Remove Firefox Pioneer from privacy FAQ page (Fixes #13387)

bedrock/products/tests/test_views.py, bedrock/products/views.py
Request from VPN team to update the iOS app store URL (removes mention of FPN)
#13384
http://localhost:8000/en-US/products/vpn/download/
=> Update VPN iOS app store URL (Fixes #13384)

media/js/base/datalayer-productdownload.es6.js, media/js/firefox/all/all-downloads-unified-init.es6.js, tests/unit/spec/base/datalayer-productdownload.js
Change name of TrackProductDownload's event handler to be closer to the names of things in TrackBeginCheckout.
#13238 
`npm run karma`
=> Change name of productDownload event handler

bedrock/products/templates/products/vpn/includes/macros.html, bedrock/products/templates/products/vpn/includes/subnav-refresh.html, bedrock/products/templates/products/vpn/landing-refresh.html, media/css/products/vpn/landing-refresh.scss, media/static-bundles.json
- Adds VPN affiliate logic back to refreshed landing page. 
- Also updates pricing links to use relative pricing anchors.
https://github.com/mozilla/bedrock/issues/13159
=> Add affiliate flow back to landing refresh page

docs/browser-support.rst, docs/pipeline.rst
- Updates bedrock's browser support documentation to take into account changes happening in https://github.com/mozilla/bedrock/issues/13317
- Also fixes a few heading warnings I noticed in the terminal in `pipeline.rst`.
#13378
=> Update browser support documentation for Firefox (Fixes #13378)

bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json
FTL strings are here https://github.com/mozilla/bedrock/blob/fd32cdce0a1f15996b33432cfcc7bff7b62484e6/l10n/en/mozorg/newsletters.ftl#L419
=> Fix missmatch FTL string IDs for newsletter welcome emails

bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json, l10n/en/mozorg/newsletters.ftl
Changes "Firefox" to "Mozilla"
#13399
http://localhost:8000/en-US/newsletter/newsletter-strings.json
=> Update new product testing newsletter description (Fixes #13399)

docs/attribution/0001-analytics.rst
Add documentation for GA4 product_download event.
#13238 
http://127.0.0.1:8100/attribution/0001-analytics.html#product-download
=> Add documentation for GA4 product_download event

bedrock/products/templates/products/relay/landing.html, l10n/en/brands.ftl, l10n/en/products/relay/landing.ftl, media/css/products/relay/components/reviews.scss
l10n tweaks to Relay ftls
- Don't treat Addons as a brand name
- Migrate Relay strings instead
- CSS tweak to try to handle longer translations of "Add-ons"
https://github.com/mozilla/bedrock/pull/12964#pullrequestreview-1546515308
localhost:8000/en-US/products/relay/
Use dev tools to change the contents of `.c-review-amo-title` to something longer... like the French "Modules complémentaires" for example
=> l10n tweaks to Relay ftls

bedrock/products/templates/products/vpn/features.html, media/css/products/vpn/features.scss
Adds CTA buttons between page sections. This was part of the original design but overlooked during dev (my fault) and not spotted during any of the multiple visual reviews (not my fault).
#13445 
http://localhost:8000/en-US/products/vpn/features/
=> Add CTA buttons to VPN features page [fix #13445]

bedrock/base/templates/base-protocol.html, bedrock/firefox/templates/firefox/home/index-master.html, bedrock/firefox/templates/firefox/new/basic/base.html, bedrock/firefox/templates/firefox/new/desktop/base.html, bedrock/mozorg/templates/mozorg/home/base.html, bedrock/products/templates/products/vpn/landing.html, bedrock/products/templates/products/vpn/pricing.html, docs/attribution/0001-analytics.rst, glean/metrics.yaml, media/js/base/banners/mozilla-banner.js, media/js/base/protocol/init-lang-switcher.es6.js, media/js/glean/init.es6.js, media/js/glean/page.es6.js, media/js/glean/utils.es6.js, package-lock.json, package.json, requirements/dev.txt, requirements/prod.in, requirements/prod.txt, tests/unit/karma.conf.js, tests/unit/spec/glean/page.js, tests/unit/spec/glean/utils.js
Bumps Glean to v.14.0 and makes some smaller updates / improvements to how we collect metrics.
Note: Glean is currently only enabled when `dev=True` so it's pretty safe to make changes.
- Adds Glean bundle to `base-protocol.html`.
- Removes click measurement (leaving only page views for now, until the next release is out).
- Sets `channel` to either `prod` or `non-prod` for easier query filtering.
- Adds a default value of `""` (an empty string) for known parameters, to make querying easier.
- Adds a `hasValidURLScheme()` helper to filter out a small amount of bad data.
https://github.com/mozmeao/www-config/blob/main/waffle_configs/bedrock-prod.env#L44
N/A
- `make preflight`
- `npm start`
You should see the glean page event ping in the console
=> Bump Glean to v1.4.0

bedrock/products/templates/products/vpn/includes/subnav-refresh.html, bedrock/products/templates/products/vpn/includes/subnav.html, bedrock/products/templates/products/vpn/landing-refresh.html, bedrock/products/views.py
Updates the refreshed subnav to match the old subnav, with the addition of a Features link.
Also fixes the percentage shown in the main CTA button (it was showing the savings for the Relay bundle, but that bundle isn't currently active).
#13453 
http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-landing-refresh&entrypoint_variation=2
=> Use existing subnav on refreshed VPN pages [fix #13453]

bedrock/mozorg/urls.py
The pages below currently 404 when there's a trailing slash at the end
N/A
- http://localhost:8000/en-US/sustainability/emissions-data/
- http://localhost:8000/en-US/sustainability/carbon-neutral/
- http://localhost:8000/en-US/diversity/2022/mozilla-foundation-data/
- http://localhost:8000/en-US/diversity/2022/mozilla-corporation-data/
=> Fix missing trailing slash on sustainability pages

bedrock/firefox/templates/firefox/whatsnew/base.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-na.html, bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py, media/css/firefox/whatsnew/whatsnew-116-na.scss, media/img/firefox/whatsnew/whatsnew116-na/reader-icon.svg, media/js/base/uitour-lib.js, media/js/firefox/whatsnew/whatsnew-116-na.js, media/static-bundles.json, tests/functional/firefox/whatsnew/test_whatsnew_116.py
Adds WNP for Firefox 116 for en-US and en-CA, promoting reader view.
#13421 
http://localhost:8000/en-US/firefox/116.0/whatsnew/
=> WNP for Firefox 116, NA [fix #13421]

media/js/newsletter/form-utils.es6.js, tests/unit/spec/newsletter/form-utils.js, tests/unit/spec/newsletter/management.js
Stores token in local memory so that the form still works even if left open for a long period of time.
Rather than wait for an hour for the cookie to expire, the easiest way to test this is to delete the `nl-token` cookie after the page has loaded, and then hit submit after that.
#13324
First get your token here: https://www.mozilla.org/en-US/newsletter/recovery/
Then open `http://localhost:8000/en-US/newsletter/existing/YOUR_TOKEN_HERE/`
=> Fix newsletter management page form submission when cookie has expired (Fixes #13324)

bedrock/firefox/templates/firefox/browsers/compare/brave.html
Brave now supports an in-browser screenshot feature.
#13471
http://localhost:8000/en-US/firefox/browsers/compare/brave/
=> Update Brave browser comparison page for screenshot feature (Fixes #13471)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-de.html
Hanns (our German copywriter) says we only need to update the headline, the other two items in the bug are intentional.
https://bugzilla.mozilla.org/show_bug.cgi?id=1846578
http://localhost:8000/de/firefox/116.0/whatsnew/
=> Fix typo in WNP 116 for DE

media/js/firefox/whatsnew/whatsnew-116-na.js
Adds a `visibilitychange` listener, to make sure we show the icon again after exit from reader mode
Note: this bug isn't reproducible locally, but shows itself on demo https://www-demo1.allizom.org/en-US/firefox/116.0/whatsnew/
#13484
https://www-demo1.allizom.org/en-US/firefox/116.0/whatsnew/
=> Fix disappearing reader mode icon on WNP (Fixes #13484)

bedrock/products/tests/test_helper_misc.py, bedrock/settings/base.py
This is only a short term fix for the original issue highlighted in #13476. It does not address adding currency formatting to the `ftl()` helper, which will provide a more robust solution.
#13476
http://localhost:8000/en-US/products/vpn/?geo=fi
=> Update euro currency formatting for English locales (Issue #13476)

media/js/glean/init.es6.js
Adds `serverEndpoint` config to initializing Glean, that points to our own origin.
#13481
On page load you should see posts successfully sent to www.mozilla.org
=> Update glean server endpoint (Fixes #13481)

bedrock/mozorg/templates/mozorg/sustainability/carbon-neutral.html, bedrock/mozorg/templates/mozorg/sustainability/emissions-data.html, bedrock/mozorg/templates/mozorg/sustainability/index.html
I updated the Sustainability report title to something more appropriate for each page, and added a meta description that suits the report pages 🍀
https://github.com/mozilla/bedrock/issues/13458
=> Fix meta titles and add meta description for sustainability pages

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-de-reader-view.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-fr-reader-view.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-uk-reader-view.html, bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py, media/css/firefox/whatsnew/whatsnew-117-eu-reader-view.scss, media/img/firefox/whatsnew/whatsnew117-eu/reader-icon.svg, media/js/base/uitour-lib.js, media/js/firefox/whatsnew/whatsnew-117-eu-reader-view.js, media/js/firefox/whatsnew/whatsnew-117-experiment-eu-reader-view.es6.js, media/static-bundles.json, tests/functional/firefox/whatsnew/test_whatsnew_117.py, tests/pages/firefox/whatsnew/whatsnew_117.py
Adds WNP for Firefox 117 for `/de/`, `/fr/`, and `/en-GB/` promoting reader view.
Unlike the NA version that this design is using, clicking the main CTA button now triggers Reader View directly (via [UITour](https://bedrock.readthedocs.io/en/latest/uitour.html)), rather than linking off to SUMO. If JS is disabled, the CTA should still go to SUMO like a normal link.
There's also a 50/50 split A/B test for each locale, where each variation displays slightly different tagline copy.
#13480
Clicking "Try Reader View" should activate reader view. Reader view icon should also be displayed in the Firefox address bar on page load.
URLs should trigger traffic cop redirects (test with DNT disabled):
- http://localhost:8000/en-GB/firefox/117.0/whatsnew/
- …
=> Add WNP 117 for EU (Reader mode) (Fixes #13480)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-na.html, media/js/firefox/whatsnew/whatsnew-116-na.js
This removes the set-to-default alternative CTA and makes the main CTA trigger reader view. Also shortens the `<title>`.
http://localhost:8000/en-US/firefox/116.0/whatsnew/
=> Update NA WNP116 CTA [#13421]

package-lock.json, package.json, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
- Bumps Glean.js to 2.0.0
- Bumps glean_parser to 8.1.1
#13493
- `make preflight`
- `npm start`
=> Update Glean.js to v2.0.0 (Fixes #13493)

.github/workflows/pull_request_tests.yml, Dockerfile
Bumps Node to v18 in both Docker images and in CI for pull requests
#13525
Passing test run: https://github.com/mozilla/bedrock/actions/runs/5809529308
=> Bump Node to v18 (Fixes #13525)

bedrock/newsletter/templates/newsletter/monitor-waitlist.html, bedrock/newsletter/urls.py, media/css/newsletter/newsletter-monitor-waitlist.scss, media/static-bundles.json, tests/functional/newsletter/test_monitor_waitlist.py, tests/pages/newsletter/monitor_waitlist.py, tests/unit/spec/newsletter/data.js
Adds a newsletter subscription page for the Monitor pre-launch waitlist. It's English-only and also US-only. Non-US countries should see an apologetic message in place of the form.
This needs to go live on **Monday, 14 August 2023** 
#13522 
US: http://localhost:8000/en-US/newsletter/monitor-waitlist/?geo=US
Non-US: http://localhost:8000/en-US/newsletter/monitor-waitlist/?geo=DE
=> Add Monitor waitlist subscription page [fix #13522]

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
After bumping APScheduler to 3.10.2, dependabot spotted a newer release, with a bugfix in it:
>    Fixed TypeError related to entry point iteration on Python 3.9
Because we're still on Python 3.9, I thought it made sense to get this included ASAP, just in case
@pmac @robhudson **Please merge after approval, as I'm not around rest of today**
=> Bump APScheduler to 3.10.3 - bugfix

bedrock/base/templates/base-protocol.html, bedrock/products/templates/products/vpn/base.html, bedrock/products/templates/products/vpn/resource-center/base-article.html, bedrock/settings/__init__.py
Adds 3rd party Stripe JS script to all VPN morog pages
This has already passed legal review. They are OK with loading the script given that it helps perform a critical business function (fraud prevention).
#13527
Stripe scripts should load successfully:
Stripe POST requests should fire successfully:
=> Load Stripe JS on VPN lead pages (Fixes #13527)

bedrock/products/templates/products/vpn/download.html, bedrock/products/templates/products/vpn/landing.html, l10n/en/products/vpn/landing.ftl
Updates Ubuntu 18.04 to 20.04
#13442
- http://localhost:8000/en-US/products/vpn/download/
=> Update sys requirements for Mozilla VPN on Linux (Fixes #13442)

package-lock.json, package.json
Fixes a minor issue introduced in 2.0.0 https://github.com/mozilla/glean.js/releases/tag/v2.0.1
https://github.com/mozilla/bedrock/issues/13431
- `npm start`
=> Bump Glean JS to v2.0.1

bedrock/base/templates/404.html, glean/metrics.yaml, media/js/glean/page.es6.js, media/js/glean/utils.es6.js, tests/unit/spec/glean/page.js, tests/unit/spec/glean/utils.js
Adds `httpStatus` metric to Glean page pings to help distinguish 404 pages.
Adding this new metric has been approved in data review here: https://bugzilla.mozilla.org/show_bug.cgi?id=1848981
#13581
The easiest way to test this change is to set `GLEAN_LOG_PINGS=True` in your `.env`, and page pings should be viewable in the browser's web console.
=> Distinguish 404 in Glean page metrics (Fixes #13581)

media/js/glean/utils.es6.js, tests/unit/spec/glean/utils.js
Removes tokens from newsletter page pings
#13583
The tests hopefully speak for themselves, but if you would like to test locally you can first get your token here: https://www.mozilla.org/en-US/newsletter/recovery/
Next, set `GLEAN_LOG_PINGS=True` in your .`env`, and page pings should be viewable in the browser's web console.
Then open `http://localhost:8000/en-US/newsletter/existing/YOUR_TOKEN_HERE/`
=> Filter newsletter token from path name in Glean page pings (Fixes #13583)

docs/attribution/0001-analytics.rst, glean/metrics.yaml, media/js/glean/elements.es6.js, media/js/glean/init.es6.js, media/js/glean/page.es6.js, tests/unit/spec/glean/elements.js, tests/unit/spec/glean/page.js
Updates Glean helpers so that we now have `Mozilla.Glean.pagePing()` and `Mozilla.Glean.clickPing()`.
- Glean is only running when `Dev=True` for now, so making changes is pretty safe. 
- Removes old code that would try to automatically create pings based on data attributes (I want to concentrate on measuring a more targeted set of events for now, such as downloads and subscriptions)
- Both of the above helpers are not yet used, so this PR only defines them and adds tests.
https://github.com/mozilla/bedrock/issues/13431
=> Update Glean ping helpers

media/css/firefox/browsers/best-browser.scss, media/css/firefox/features/safebrowser.scss, media/css/firefox/releasenotes.scss
There were some Firefox pages that were using the Inter font instead of Metropolis because they were hard-coded in.
- Update heading fonts from Inter to Metropolis 
- See if updating some of the header fonts in the release notes page was fine to do?
#13577 
- http://localhost:8000/en-US/firefox/features/safebrowser/
- http://localhost:8000/en-US/firefox/116.0/releasenotes/
- http://localhost:8000/en-US/firefox/browsers/best-browser/
=> Update title fonts in Firefox pages (fixes #13577)

l10n/en/products/vpn/landing.ftl
Fixes: https://github.com/mozilla-l10n/www-l10n/pull/345#discussion_r1296434589
=> Remove brand names from vpn download string (Issue #13551)

bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
Incorrectly placed Suba in Senior Leadership, so we moved her to the Steering Committee section.
=> Move Suba to steering committee section in leadership pages

bedrock/mozorg/tests/test_helper_misc.py
This changeset covers an edge case where, if you have DEV=True in a local .env, the TestRelayFxAButton.test_relay_fxa_button test would fail.
This is because, despite DEV being patched to False, RELAY_PRODUCT_URL was set to something else before the patching. So, adding an additional override was needed to keep the test stably passing
=> Fix test that fails if DEV=True in local env

bedrock/firefox/templates/firefox/nightly/whatsnew.html
Add a call to community participation to users in Spain using the es-ES locale to join the community Matrix room for Spain contributors.
This customization should be live before we ship our first 119 nightly build on Monday 28 of August.
geoIP and locale selection
=> Nightly whatsnew page customization for Spain

bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py, bedrock/products/templates/products/vpn/includes/macros.html, bedrock/products/templates/products/vpn/landing.html, bedrock/products/templates/products/vpn/pricing.html, bedrock/products/views.py, bedrock/settings/base.py
Removed switches and conditionals for the now launched VPN expansion work
Did I miss anything?
#13552
Wave VI countries should still see VPN pricing e.g. 
Wave VI countries should still see the 115 WNP e.g.
Full list of supported countries should be visible:
Supported countries should say 33:
=> VPN wave VI expansion post-launch cleanup (Fixes #13552)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-na-relay.html
Updates to body copy for the Relay WNP for Firefox 117.
http://localhost:8000/en-US/firefox/117.0/whatsnew/?v=3
=> WNP117 Relay, copy updates [#13495]

bedrock/products/templates/products/vpn/landing-refresh.html, bedrock/products/views.py, media/js/products/vpn/experiment-refresh-pricing-layout.es6.js, media/static-bundles.json
Sets up a new traffic cop experiment testing two different pricing section layouts on the refreshed VPN landing page. 50% gets the column layout and 50% gets the row layout. This is limited to only en-US.
#13558 
Columns: http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-refresh-pricing&entrypoint_variation=1#pricing
Rows: http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-refresh-pricing&entrypoint_variation=2#pricing
Ensure the `entrypoint_experiment` and `entrypoint_variation` params are added to the purchase buttons and passed through to FxA for attribution.
=> Add VPN refresh pricing experiment [fix #13558]

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-vpn.html
Sets a different `referral_id` for traffic in North America, to help us track attribution on the refreshed VPN pages.
http://localhost:8000/en-US/firefox/117.0/whatsnew/?geo=US : English in the US should get `whatsnew-117-na-vpn`
http://localhost:8000/en-US/firefox/117.0/whatsnew/?geo=US&v=2 : English in the US should get `whatsnew-117-na-vpn-pricing` for the pricing variation.
http://localhost:8000/en-US/firefox/117.0/whatsnew/?geo=LV : English in other target countries should get `whatsnew-117-eu-vpn`
http://localhost:8000/bg/firefox/117.0/whatsnew/?geo=BG : Other languages in other target countries should get `whatsnew-117-eu-vpn`
=> Distinguish NA from EU in WNP117 WPN attribution [#13496]

docs/attribution/0001-analytics.rst, glean/metrics.yaml, glean/pings.yaml, media/js/base/send-to-device.es6.js, media/js/glean/elements.es6.js, media/js/glean/init.es6.js, media/js/glean/page.es6.js, media/js/newsletter/newsletter.es6.js, media/js/products/relay/waitlist.es6.js, media/js/products/vpn/invite.es6.js, tests/unit/spec/glean/elements.js, tests/unit/spec/glean/page.js
Migrates from using custom pings to standard events for recording page hits, interaction, non-interaction and element clicked events.
Note: I've kept our custom page view ping for now, which I can remove later after I've updated a few queries that use it. The other custom pings I think we're fine to lose now as they are not really used yet.
#13639
=> Migrate to Glean events from custom pings (Fixes #13639)

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2023.html, bedrock/mozorg/urls.py
Adds the transparency report for the period from January to June, 2023.
#13633 
http://localhost:8000/en-US/about/policy/transparency/
http://localhost:8000/en-US/about/policy/transparency/jan-jun-2023/
=> Add H1 2023 transparency report [fix #13633]

media/js/base/core-datalayer-page-id.js, media/js/base/fxa-attribution.es6.js, media/js/base/stub-attribution.js, media/js/glean/utils.es6.js, tests/unit/spec/base/core-datalayer-page-id.js, tests/unit/spec/base/fxa-attribution.js, tests/unit/spec/base/stub-attribution.js, tests/unit/spec/glean/utils.js
This PR fixes some existing holes in attribution data, where referrer was being lost when Traffic Cop performs a redirect.
I added a global `Mozilla.Analytics.getReferrer()` helper that other scripts can use to get referrer more reliably. It touches three places:
- Glean
- Stub Attribution
- FxA Attribution
Hopefully the tests I added can give some confidence that the value is now being passed as expected, but I also added some manual testing instructions below.
#13593
Note: test all the items below using a browser with DNT disabled.
**Glean**
1. Set `GLEAN_LOG_PINGS=True` in your `.env`.
2. Open http://localhost:8000/en-US/firefox/new/
3. Click on the Mozilla logo in the main navigation to go to the home page. You should be entered into a traffic cop experiment with wither `?v=1` or …
=> Pass Traffic Cop custom referrer to attribution scripts (Fixes #13593)

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Publishes the latest version of our CA root store policy.
https://bugzilla.mozilla.org/show_bug.cgi?id=1851326
http://localhost:8000/en-US/about/governance/policies/security-group/certs/policy/
Compare to https://github.com/mozilla/pkipolicy/blob/2.9/rootstore/policy.md
=> Update root store policy to 2.9 [fix bug #1851326]

bedrock/base/templates/includes/banners/mobile/firefox-app-store.html, bedrock/base/templates/includes/banners/mobile/focus-app-store.html, bedrock/firefox/templates/firefox/browsers/chromebook.html, bedrock/firefox/templates/firefox/browsers/compare/includes/download-menu-list.html, bedrock/firefox/templates/firefox/browsers/index.html, bedrock/firefox/templates/firefox/browsers/mobile/index.html, bedrock/firefox/templates/firefox/enterprise/index.html, bedrock/firefox/templates/firefox/home/index-master.html, bedrock/firefox/templates/firefox/includes/download-button.html, bedrock/firefox/templates/firefox/includes/download-unsupported.html, bedrock/firefox/templates/firefox/products/index.html, bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py, docs/attribution/0001-analytics.rst, media/js/base/datalayer-productdownload-init.es6.js, media/js/base/datalayer-productdownload.es6.js, media/js/firefox/all/all-downloads-unified-init.es6.js, media/js/firefox/new/common/thanks-direct.js, media/js/firefox/new/common/thanks-init.js, media/static-bundles.json, tests/unit/spec/base/datalayer-productdownload.js
Add Adjust support to TrackProductDownload and trigger on all remaining desktop downloads (previously this had just been triggered on /all).
- add `method` and `link_url` parameters to product_download event
- update tests
- stop assuming product is firefox and log it if the product is unrecognized
- update tests
- add support for App Store links in addition to iTunes links
- add logic to support Adjust links
- and identify which product and app store adjust links are for
- add TrackProductDownload to all pages on the site and init it
- listen to links with class `ga-product-download` on all pages
- remove what is now duplicate listener from /all
- add class `ga-product-download` to adjust links and download buttons
#13238 
[Successful integration …
=> Trigger TrackProductDownload for all mobile and desktop downloads

media/css/products/relay/components/matrix.scss
CSS tweak to Relay plan toggles
It's been bothering me that the blue outline moves to the selected plan on mouse down and the white background moves on mouse up. 
This moves them together on mouse down.
n/a
Toggles appear in the pricing matrix on large screens:
http://localhost:8000/en-US/products/relay/
=> Fix bug with Relay plan toggle

bedrock/firefox/templates/firefox/all-unified.html, media/css/firefox/all/all-unified.scss, media/js/firefox/all/all-downloads-unified-init.es6.js
Remove Sidebar Menu JS from /all
Fix #13236 
http://localhost:8000/en-US/firefox/all/
=> Remove Sidebar Menu JS from /all Fix #13236

bedrock/mozorg/templates/mozorg/home/home-new.html
The EU team requested we bring back the CTD promo into the German homepage 
Waiting on some confirmation regarding placement
- http://localhost:8000/de/
- https://www-demo8.allizom.org/de
=> Re-adding CTD promo to German homepage

bedrock/base/templates/macros.html, bedrock/firefox/templates/firefox/accounts.html, bedrock/firefox/templates/firefox/browsers/compare/brave.html, bedrock/firefox/templates/firefox/browsers/compare/safari.html, bedrock/firefox/templates/firefox/features/password-manager.html, bedrock/firefox/templates/firefox/features/sync.html, bedrock/firefox/templates/firefox/privacy/products.html, bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json, bedrock/newsletter/templates/newsletter/management.html, bedrock/products/templates/products/relay/faq.html, bedrock/products/templates/products/vpn/includes/download-faq.html, l10n/en/brands.ftl, l10n/en/firefox/accounts.ftl, l10n/en/firefox/browsers/compare/brave.ftl, l10n/en/firefox/browsers/compare/safari.ftl, l10n/en/firefox/features/password-manager-2023.ftl, l10n/en/firefox/features/sync-2023.ftl, l10n/en/firefox/privacy-hub.ftl, l10n/en/fxa_form.ftl, l10n/en/mozorg/newsletters.ftl, l10n/en/products/relay/faq.ftl, l10n/en/products/vpn/platform-post-download.ftl, l10n/en/sub_navigation.ftl, media/css/firefox/accounts-2019.scss
We're rebranding Firefox Accounts to Mozilla accounts (lowercase).
- [Guidelines](https://www.figma.com/file/7nsOBSt3VTeCimDqavQT9J/Mozilla-Accounts-Content-Guidelines?type=design&node-id=1901%3A5540&mode=design&t=YvuKYZyKufJwhOFC-1) 
- [Spreadsheet](https://docs.google.com/spreadsheets/d/1QTxMYZacS5WMGbcC4SaJmnAnQ3nqHw-_GyA_ai-rrF8/edit#gid=1586368493)
- Set `Dev=False` in `.env`
- Set `SWITCH_MOZ_ACCOUNTS_UPDATE=True` in `.env`
This is also running on a dev server: http://www-demo6.allizom.org/
<google-sheets-html-origin>
Name | URL
-- | --
Homepage banner | https://www.mozilla.org/
Firefox accounts page | https://www.mozilla.org/en-US/firefox/accounts/
Email Preference Page | https://www.mozilla.org/en-US/newsletter/existing/?utm_source=pref_footer
Firefox Sync page | …
=> Updating Firefox Accounts strings to Mozilla accounts

bedrock/base/management/commands/update_www_config.py, bedrock/settings/base.py
Adds a check to the `update_www_config` management command to check the monitor stats API and enables or disables the monitor waitlist switch.
To test locally run:
`./manage.py update_www_config`
=> Add monitor waitlist switch checking

bedrock/base/__init__.py, bedrock/base/middleware.py, bedrock/base/tests/test_middleware.py, bedrock/base/tests/urls.py, bedrock/settings/base.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This pull request introduces the "markus" Python package into our codebase, enabling the collection of statsd metrics for backend monitoring and performance analysis via Grafana.
This pull request only implements a single metric, `response.status`, in middleware and wraps all views. This will give us a good idea of the volume of requests actually hitting the server vs what hits cache. More metrics will be added in future commits.
=> Add markus for backend metrics collection

bedrock/firefox/templates/firefox/accounts.html
@reemhamz and @alexgibson noticed a small typo in the strings for mozilla accounts - this should fix
http://localhost:8000/en-US/firefox/accounts/
=> Fix string for mozilla accounts

media/js/base/datalayer-productdownload.es6.js, media/js/base/stub-attribution.js, media/js/firefox/all/all-downloads-unified.js, tests/unit/spec/base/datalayer-productdownload.js, tests/unit/spec/base/stub-attribution.js, tests/unit/spec/firefox/all/all-downloads-unified.js
Should hopefully fix https://github.com/mozilla/bedrock/actions/runs/6250636612
I haven't deployed / tested this, but hopefully the tests should give us enough confidence that things will work ok once on dev.
#13699
To test this locally you'd need to set `BOUNCER_URL=https://dev.bouncer.nonprod.webservices.mozgcp.net/` in your `.env`
=> Add bouncer dev to known domains for front-end code checking (Fixes #13699)

media/js/base/send-to-device.es6.js
Send the event `send_to_device` from bedrock & receive it in GTM.
#13683
- Added GTM Tag: `GA4 Event - send_to_device`
- Added GTM Trigger: `Event - send_to_device`
- Deleted previous Tag: `GA4 Event - Campaign - Send to Device Success`
**Please also test the accompanying GTM changes.**
- [Visit the "ga4 s2d" container in GTM.](https://tagmanager.google.com/#/container/accounts/52671733/containers/1075029/workspaces/1000239) 
- Click the "preview" button to open tag assistant.
- Click "add domain" and enter https://www-demo4.allizom.org/en-US/firefox/mobile/get-app
- Submit the form with "success@example.com" and "failure@example.com"
- In tag assistant check that:
- the failure did not trigger a `send_to_device` event
- the success did trigger a `send_to_device` event
- the event …
=> Add GA4/GTM tracking for send_to_device (#13683)

tests/functional/firefox/test_all.py, tests/pages/firefox/all.py
This is causing integrations tests to fail when checking `settings.BOUNCER_URL`. The front-end code already does link validation when generating the download button href, so I think this check is pretty redundant anyways?
N/A
`pytest --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/firefox/test_all.py`
=> Remove link validation check in firefox/all functional test

bedrock/firefox/templates/firefox/accounts.html
Accidentally removed the Firefox icons (sub-nav icon and favicon) instead of placing them behind a switch ternary with the new Moz accounts changes coming up, so I just re-added them here.
http://localhost:8000/en-US/firefox/accounts/
=> Re-adding Firefox icons to Firefox Accounts page

bedrock/products/templates/products/monitor/includes/sub-footer.html, l10n/en/products/monitor/shared.ftl
Legal / product have requested that we switch to using two separate links for ToS and Pivacy Policy.
N/A
http://localhost:8000/en-US/products/monitor/
=> Update monitor page legal footer links

bedrock/firefox/templates/firefox/accounts.html
Fixes https://github.com/mozilla/bedrock/issues/13707
=> Remove whitespace from favicon URL on /firefox/accounts/ (Fixes #13707)

bedrock/careers/templates/careers/diversity.html
We were still linking to the 2021 report but the 2022 report has been published (some time ago, actually). This updates the link.
#13709 
http://localhost:8000/careers/diversity/
=> Update D&I report link [fix #13709]

bedrock/products/templates/products/relay/includes/bundle.html, bedrock/products/templates/products/relay/includes/macros.html, bedrock/products/templates/products/relay/includes/matrix.html, bedrock/products/templates/products/relay/landing.html, bedrock/products/templates/products/relay/premium.html, bedrock/products/templates/products/relay/pricing.html, bedrock/products/templatetags/misc.py, bedrock/products/tests/test_helper_misc.py, bedrock/products/views.py, bedrock/settings/base.py
Add new supported EU countries to Relay
- import [new data structure](https://github.com/mozilla/fx-private-relay/blob/168105a471a4590e6379d663b59b0d3e7e15cd62/privaterelay/plans.py#L250-L439) from Relay
- update templatetags to account for new data structure
- add function to create ga-data object
- update tests to consider analytics will always be there
- add tests for currency formatting
- change tests which expected a different default region for multi region countries
- add some error messages when product is unrecognized instead of falling back
The tests need to be updated to test all the new locales, but I thought it'd be good to merge with the old ones so we can tell I didn't break anything with the new data structure. So, [PR to follow with updated tests](#13667).
#13656 
Try …
=> Add new supported EU countries to Relay #13656

bedrock/mozorg/templates/mozorg/about/governance/policies/social-content-policies.html
Moz.social team requested an update to this page: https://www.mozilla.org/en-US/about/governance/policies/social-content-policies/ that add the specific moz.social infringement form
http://localhost:8000/en-US/about/governance/policies/social-content-policies/
=> update social-content-policies page

bedrock/settings/base.py
Fixes https://github.com/mozilla/bedrock/issues/13716
http://localhost:8000/en-US/products/monitor/
=> Restore deleted monitor setting (Fixes #13716)

media/css/mozorg/try-picture-in-picture.scss
The 404 images path was in notification-bar.scss, which doesn't seem to be used in the page anyway. I removed that import, but added the correct image and font paths just to be safe.
https://github.com/mozilla/bedrock/issues/13718
http://localhost:8000/en-US/try-picture-in-picture/
=> Fix Protocol static asset paths in try-pictute-in-picture.scss

bedrock/mozorg/templates/mozorg/mpl/license-policy.html
Updates the link from the old Mana URL to the new Confluence URL.
#13720 
http://localhost:8000/MPL/license-policy/
=> Update mana link on MPL license policy page [fix #13720]

package-lock.json, package.json
https://github.com/mozilla/glean.js/releases/tag/v2.0.3
=> Bump Glean.js to v2.0.3

media/css/firefox/new/desktop/download.scss
Fixes focus color contrast bug
https://github.com/mozilla/bedrock/issues/13585
=> Fix color contrast issue on link focus in /new modal (Fixes #13585)

bedrock/products/templates/products/vpn/includes/macros.html, bedrock/products/templates/products/vpn/resource-center/base-article.html, bedrock/products/templates/products/vpn/resource-center/landing.html, bedrock/products/views.py
Replaces the default Firefox button (in non-Firefox browsers) with a VPN button on VPN resource center pages. The button should switch to a "join the waitlist" button in non-VPN countries.
Also updates the CTA button in the resource center footer to use the same macro so it includes the logic to switch to the waitlist button in non-VPN countries.
#13622 
http://localhost:8000/products/vpn/resource-center/ - landing page
http://localhost:8000/products/vpn/resource-center/what-is-a-vpn/ - article page
http://localhost:8000/products/vpn/resource-center/what-is-a-vpn/?geo=CN - non-VPN country
=> Add VPN button to navbar on in resource center [fix #13622]

bedrock/firefox/templates/firefox/includes/download-unsupported.html
Updates alias from `firefox-esr-next-latest-ssl` to `firefox-esr-latest-ssl` now that ESR 115 is the current ESR version.
#13752
Links should still return ESR 115 download
=> Update ESR link alias for unsupported messaging (Fixes #13752)

bedrock/products/templates/products/vpn/landing-refresh.html
Simplifies the hero copy when banner is active to make discount less confusing
#13761
=> Update VPN hero copy when banner is active (Fixes #13761)

bedrock/firefox/templates/firefox/all-unified.html, bedrock/firefox/templates/firefox/browsers/chromebook.html, bedrock/firefox/templates/firefox/browsers/windows-64-bit.html, bedrock/firefox/templates/firefox/includes/macros.html, bedrock/firefox/templates/firefox/new/basic/base_download.html, bedrock/firefox/templates/firefox/new/basic/base_platform.html, bedrock/firefox/templates/firefox/new/basic/download_linux.html, bedrock/firefox/templates/firefox/new/basic/download_mac.html, bedrock/firefox/templates/firefox/new/basic/download_windows.html, l10n/en/firefox/browsers/windows-64-bit.ftl, media/css/firefox/browsers/windows-64-bit.scss, media/css/protocol/components/_download-button.scss, media/js/base/stub-attribution.js, media/static-bundles.json, tests/functional/firefox/browsers/test_windows_64_bit.py, tests/functional/firefox/new/test_platform.py, tests/pages/firefox/browsers/windows_64_bit.py, tests/pages/firefox/new/platform.py
- Updates OS specific download pages so that a single OS build is returned, as opposed to the current behavior where the button will return a link to whichever build matches your current OS.
- I also removed the nav CTA button on these pages to make things less confusing.
- https://github.com/mozilla/bedrock/issues/12192
- https://bugzilla.mozilla.org/show_bug.cgi?id=1574162
Demo: 
https://www-demo1.allizom.org/en-US/firefox/windows/
Local:
- http://localhost:8000/en-US/firefox/windows/
- http://localhost:8000/en-US/firefox/mac/
- http://localhost:8000/en-US/firefox/linux/
- http://localhost:8000/en-US/firefox/browsers/windows-64-bit/
=> OS specific FF download pages should always return the same build (Fixes #12192)

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
See [bug 1857050](https://bugzilla.mozilla.org/show_bug.cgi?id=1857050#c2) and https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#531-technically-constrained
=> Fix bug 1857050: Remove extra h4 opening tag where a closing one was needed

bedrock/products/templates/products/vpn/landing-refresh.html, bedrock/products/templates/products/vpn/pricing-refresh.html, media/css/products/vpn/common-refresh.scss, tests/functional/products/vpn/test_landing_refresh.py, tests/functional/products/vpn/test_pricing_refresh.py, tests/pages/products/vpn/landing_refresh.py, tests/pages/products/vpn/pricing_refresh.py
At request of VPN folks:
- Adds legal footer links back to footer of the page
- Adds test to ensure they are displayed
- http://localhost:8000/en-US/products/vpn/pricing/
=> Add legal links to redsigned VPN page footer (Fixes #13771)

bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
Moved Ian Carmichael's card from senior leadership section to the executive steering committee section
https://github.com/mozilla/bedrock/issues/13773
=> Move Ian Carmichael to Executive Steering Committee section

package-lock.json, package.json
https://github.com/mozilla/glean.js/releases/tag/v2.0.4
https://github.com/mozilla/bedrock/issues/13431
- `npm start`
=> Bump Glean.js to v2.0.4

tests/unit/spec/pocket/updates-signup.js
Fixes a 404 img warning when running JS tests and local dev server is not running:
```
16 10 2023 13:54:23.152:WARN [web-server]: 404: /media/img/pocket/pocket-update-signup.png
16 10 2023 13:54:23.165:WARN [web-server]: 404: /media/img/pocket/pocket-update-signup.png
16 10 2023 13:54:23.168:WARN [web-server]: 404: /media/img/pocket/pocket-update-signup.png
16 10 2023 13:54:23.170:WARN [web-server]: 404: /media/img/pocket/pocket-update-signup.png
```
N/A
- `npm test`
=> Fix img 404 in JS tests

package-lock.json, package.json
https://github.com/mozilla/glean.js/releases/tag/v2.0.5
N/A
- `npm start`
=> Bump Glean.js to v2.0.5

bedrock/firefox/templates/firefox/pocket.html
Updates hard coded string on /firefox/pocket/ page.
#13815
http://localhost:8000/en-US/firefox/pocket/
=> Rename Firefox account to Mozilla account on /firefox/pocket page (Fixes #13815)

l10n/en/firefox/new/desktop.ftl
Got a review comment in the `www-l10n` repo to remove a leftover quotation mark in the Fluent string ID for the yellow notification banner's anchor link
https://github.com/mozilla-l10n/www-l10n/pull/359
http://localhost:8000/en-US/firefox/new/?reason=outdated
=> Remove extra quotation mark from L10N string

bedrock/products/templates/products/monitor/waitlist/base.html, bedrock/products/templates/products/monitor/waitlist/plus.html, bedrock/products/templates/products/monitor/waitlist/scan.html, bedrock/products/tests/test_views.py, bedrock/products/urls.py, bedrock/products/views.py, bedrock/settings/base.py, media/css/products/monitor/waitlist.scss, media/static-bundles.json, tests/functional/products/monitor/test_waitlist.py, tests/pages/products/monitor/waitlist.py
Adds 2 waitlist pages for Monitor. These will be linked to via the monitor.firefox.com
#13823
- http://localhost:8000/en-US/products/monitor/waitlist-plus/
- http://localhost:8000/en-US/products/monitor/waitlist-scan/
=> Add Mozilla Monitor waitlist pages (Fixes #13823)

bedrock/privacy/views.py
The file was renamed to lowercase in https://github.com/mozilla/legal-docs/commit/802a6062457c0285a0266cfdb16d59b3ddda904c
The system should already pick up the file, but it's worth updating the reference to match the GitHub file.
The files is displayed here: https://www.mozilla.org/en-US/privacy/ad-targeting-guidelines/ (or [here on stage](https://www-dev.allizom.org/en-US/privacy/ad-targeting-guidelines/))
=> Update names for "Ad Targeting Guidelines" (legal docs)

requirements/dev.in, requirements/dev.txt
Updates both `selenium` and `pytest-selenium`.
Note: I couldn't update selenium to 4.13.0, which is the latest version, due to https://github.com/pytest-dev/pytest-selenium/issues/315
We should keep an eye on that issue for updates (I'm also a bit wary that perhaps pytest-selenium is struggling a bit for maintainers?)
N/A
Successful test run: https://github.com/mozilla/bedrock/actions/runs/6611467486
=> Update Selenium and pytest-selenium

bedrock/base/tests/urls.py, bedrock/newsletter/templates/newsletter/recovery.html, bedrock/newsletter/views.py, l10n/en/mozorg/newsletters.ftl
Adds FxA error notification so we can redirect to this page upon error, giving the user a path forward to finding their email subscription page.
Please suggest any better wording.
Pass the query string to get this error to show up:
http://localhost:8000/en-US/newsletter/recovery/?fxa_error=1
=> Add fxa error notification to newsletter recovery page

bedrock/privacy/redirects.py, bedrock/privacy/templates/privacy/base-protocol.html, bedrock/privacy/templates/privacy/notices/base-notice.html, bedrock/privacy/templates/privacy/notices/mozilla-accounts.html, bedrock/privacy/urls.py, bedrock/privacy/views.py, l10n/en/privacy/index.ftl, tests/redirects/map_globalconf.py
Adds new privacy notice page for Mozilla accounts
#13802
http://localhost:8000/en-US/privacy/mozilla-accounts/
=> Add privacy notice for Mozilla accounts (Fixes #13802)

.pre-commit-config.yaml, bedrock/base/tests/urls.py, l10n/en-US/firefox/features/bookmarks.ftl
This linter runs during our pull requests, so this can help catch things earlier.
The only thing I'm sure about is what to do with the other l10n linting we do? There's 4 different linting commands being run in `./bin/run-tests.sh`. Can we remove any with this addition?
Run `pre-commit run --all-files`. Make a change to an `.ftl` file that causes an error, like using a capital letter or underscore in a string identifier and run.
=> Add moz-fluent-linter to pre-commit 

bedrock/base/templates/macros.html, media/css/mozorg/mozilla-account-promo.scss
Had a conversation w/ the branding team and they requested a few changes for the upcoming Mozilla accounts banner
Since this design was pretty bespoke to begin with, we're making these unique changes to match what's coming out in sibling websites such as SUMO and Mozilla Blog.
Demo server:
=> Small fixes to Moz accounts promo

bedrock/firefox/templates/firefox/releases/nightly-feed.xml
Fixes parsing error in Nightly RSS feed. There are more improvements we could make to this feed, but this hopefully fixes the parsing error (leaving only a few warnings with a couple of individual entries)
#13830
http://www-demo1.allizom.org/en-US/firefox/nightly/notes/feed/
https://validator.w3.org/feed/#validate_by_uri
=> Escape content in /firefox/nightly/notes/feed/ using CDATA (Fixes #13830)

bedrock/products/templates/products/vpn/resource-center/article.html
Populates values `<meta name="description">` and `<meta property="og:description">` using the `info.seo.description` field in Contentful.
#13836
http://localhost:8000/en-US/products/vpn/resource-center/
=> Add meta desc for VPN resource center articles in Contentful (Fixes #13836)

media/js/base/mozilla-article.js, media/js/base/protocol/protocol-menu.js, media/js/base/protocol/protocol-navigation.js, media/js/base/protocol/protocol-sub-navigation.js, media/js/firefox/family/subnav.js, media/js/mozorg/about-transparency.js, media/js/pocket/mobile-nav.es6.js
Prefer `addEventListener` over `addListener` which is deprecated.
#13129
Mozorg mode
- http://localhost:8000/en-US/about/history/ (side menu)
- http://localhost:8000/en-US/ (navigation, sticky nav)
- http://localhost:8000/en-US/products/vpn/ (sub navigation)
- http://localhost:8000/en-US/about/policy/transparency/jul-dec-2022/ (details sections)
Pocket mode
- http://localhost:8000/en/about/ (nav)
=> Prefer addEventListener over addListener for media queries (Fixes #13129)

l10n/configs/pontoon.toml
https://github.com/mozilla/bedrock/pull/13870 added three new Fluent files but we forgot to add them to the pontoon config (which lists individual files but not the whole folder).
=> Add new VPN Fluent files to pontoon

bedrock/products/templates/products/vpn/landing-refresh.html, l10n/en/products/vpn/features.ftl, l10n/en/products/vpn/landing-2023.ftl, l10n/en/products/vpn/pricing-2023.ftl
Fixes a bunch of strings based on feedback in https://github.com/mozilla-l10n/www-l10n/pull/363
http://localhost:8000/products/vpn/
http://localhost:8000/products/vpn/features/
http://localhost:8000/products/vpn/pricing/
=> String fixes for VPN refresh pages

package-lock.json, package.json, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
No major changes for us. This new version just temporarily removes web extension support, until the major glean.js refactor for the web is complete.
N/A
- `make preflight`
- `npm start`
=> Update glean.js to v3.0.0 and glean_parser to 10.0.3

media/js/base/stub-attribution.js
I've been putting off adding stub attribution in GA4 because we can't use the current method we use for extracting client ID once UA is disabled but we might as well start adding what we have currently.
Supporting GTM changes are in the `stub_session_set` workspace.
#12801 and https://github.com/mozilla/bedrock/issues/13904
[demo4](https://www-demo4.allizom.org/en-US/firefox/)
=> Track stub attribution in GA4

bedrock/products/templates/products/vpn/more/base-article.html
Seems like this bundle no longer exists.
#13905
http://localhost:8000/tr/products/vpn/more/what-is-a-vpn/
=> Remove non existant JS bundle from VPN resource article pages (Fixes #13905)

bedrock/firefox/templates/firefox/challenge-the-default/landing.html, media/js/firefox/challenge-the-default/challenge-the-default.es6.js
Instrument actions on CTD page.
- add data attributes to CTA buttons
- add data attributes to link
- send events for easter egg interactions
- send events for summary elements
I only instrumented opening of things, not closing/dismissal of things because that just felt like tracking the same action twice to me.
#13911
http://localhost:8000/de/firefox/
- open the browser console
- click a bunch of stuff
- print the dataLayer to the console to make the clicks have been recorded
=> Instrument actions on CTD page (Fix #13911)

docs/attribution/0001-analytics.rst, media/js/firefox/set-as-default/thanks.js, media/js/firefox/whatsnew/whatsnew-116-eu.js, media/js/firefox/whatsnew/whatsnew-118.es6.js
Track conversions in GA4 for when Firefox is set to default browser.
- Set the custom user dimensions indicating if Firefox is default.
- Send the conversion event when the default is changed.
- Add docs for `default_browser_set` and `dimension_set`
- Fix bug on WNP 118 where dimension was reported twice
#13238
Local testing can be done to make sure the dataLayer has the expected data:
http://localhost:8000/en-GB/firefox/118.0/whatsnew/
http://localhost:8000/en-GB/firefox/116.0/whatsnew/
http://localhost:8000/en-US/firefox/set-as-default/thanks/
=> Track conversions in GA4 for when Firefox is set to default browser  #13238

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx120-eu-vpn.html
Adding Czech, Danish, Finnish, Portuguese, Swedish, and Hungarian, and making some corrections to German.
http://localhost:8000/firefox/120.0/whatsnew/
http://localhost:8000/cs/firefox/120.0/whatsnew/?geo=CZ
http://localhost:8000/da/firefox/120.0/whatsnew/?geo=FI
http://localhost:8000/fi/firefox/120.0/whatsnew/?geo=FI
http://localhost:8000/pt-PT/firefox/120.0/whatsnew/?geo=PT
http://localhost:8000/sv/firefox/120.0/whatsnew/?geo=SE
http://localhost:8000/hu/firefox/120.0/whatsnew/?geo=HU
=> Add more translations to EU WNP 120 for VPN [#13902]

l10n/en/banners/vpn-holidays.ftl
Adding linebreak to VPN holiday banner string
https://github.com/mozilla-l10n/www-l10n/pull/366#discussion_r1401414623
http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-holidays-na-test&entrypoint_variation=1
=> Add linebreak to VPN banner strings

docs/abtest.rst, docs/attribution/0001-analytics.rst, media/js/base/core-datalayer-init.js, media/js/firefox/set-as-default/landing.js, media/js/firefox/whatsnew/whatsnew-119-experiment-eu.es6.js, media/js/firefox/whatsnew/whatsnew-119-experiment-na.es6.js, media/js/firefox/whatsnew/whatsnew-120-experiment-na.es6.js
Track experiments in GA4
- push experiment_view event to dataLayer
- add GA4 syntax to a/b testing docs
None of the currently running test are going to be analyzed in GA4 and so don't need the GA4 syntax added. But I do need a bit of data to verify that it's been coded correctly and try to set up reports. So, I added the GA4 code to a few experiments I thought might still be collecting data.
Also, since people tend to copy-paste from existing experiments I thought it was important to get it there on the WNP ;) 
#13238
Testing can be done locally to make sure that the dataLayer has the expected information
http://localhost:8000/en-GB/firefox/119.0/whatsnew/?v=1
http://localhost:8000/en-GB/firefox/119.0/whatsnew/?v=2
http://localhost:8000/en-GB/firefox/119.0/whatsnew/?v=3 …
=> Track experiments in GA4 (#13238)

media/css/firefox/challenge-the-default/_hero.scss
Fixes Firefox download button to be left aligned along with the hero copy.
#13920
Test in a non-Firefox browser: http://localhost:8000/de/firefox/
=> Fix download button alignment on CTD campaign page (Fixes #13920)

media/css/mozorg/home/home-new.scss
Makes headings smaller on mobile screen sizes to better accommodate longer l10n strings.
#13608
=> Fix home page title overflow for /de/ (Fixes #13608)

docs/attribution/0001-analytics.rst, media/js/base/banners/mozilla-banner.js, media/js/base/protocol/init-lang-switcher.es6.js, media/js/firefox/all/all-downloads-unified-init.es6.js, media/js/firefox/challenge-the-default/challenge-the-default.es6.js, media/js/firefox/family/banner.es6.js, media/js/firefox/new/common/thanks-direct.js, media/js/firefox/new/desktop/download.js, media/js/firefox/new/desktop/join-modal.js, media/js/firefox/privacy/products.js, media/js/firefox/welcome/welcome6.es6.js, media/js/firefox/welcome/welcome8.js, media/js/landing/landing-shared.js, media/js/products/shared/affiliate-init.es6.js, media/js/products/vpn/resource-center-article.es6.js
Track JS widgets in GA4 with `widget_action`
We currently track JS widgets using a mix of `in-page-interaction`, `non-interaction` and the old UA category/action/label to track user interactions with JS widgets on the page.
This is a generic event meant as a catch-all for existing and future interactions with JS widgets that are not conversions.
- Do the event name, properties, and how to use it make sense?
- Have all the appropriate events been instrumented?
- Is the documentation sufficient?
- Basically, before we're stuck with this forever is there anything that is going to be confusing or annoying?
https://github.com/mozilla/bedrock/issues/13238
Files can be viewed locally to see what is being written to the DataLayer.
=> Track JS widgets in GA4 (#13238)

bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v1.html, bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v2.html, bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v3.html, bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v4.html, bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v5.html, bedrock/firefox/templates/firefox/challenge-the-default/landing.html, bedrock/firefox/views.py, media/css/firefox/challenge-the-default/_hero.scss, media/css/firefox/challenge-the-default/index.scss, media/img/firefox/challenge-the-default/close-black.svg, media/img/firefox/challenge-the-default/minimize-black.svg, media/img/firefox/challenge-the-default/open-black.svg, media/js/firefox/family/fx-is-default.es6.js, tests/unit/spec/firefox/family/fx-is-default.js
Adds 4 new variations to the CTD page hero for ad testing
#13915
- http://localhost:8000/de/firefox/?v=1 (control)
- http://localhost:8000/de/firefox/?v=2 (chrome)
- http://localhost:8000/de/firefox/?v=3 (safari)
- http://localhost:8000/de/firefox/?v=4 (new device)
- http://localhost:8000/de/firefox/?v=5 (standard)
=> Add CTA creative hero variations (Fixes #13915)

bedrock/careers/templates/careers/benefits.html, bedrock/careers/templates/careers/home.html, bedrock/careers/templates/careers/locations.html, bedrock/careers/templates/careers/teams.html, bedrock/firefox/templates/firefox/browsers/compare/brave.html, bedrock/firefox/templates/firefox/browsers/compare/chrome.html, bedrock/firefox/templates/firefox/browsers/compare/edge.html, bedrock/firefox/templates/firefox/browsers/compare/ie.html, bedrock/firefox/templates/firefox/browsers/compare/opera.html, bedrock/firefox/templates/firefox/browsers/compare/safari.html, docs/attribution/0001-analytics.rst
As far as I can tell from GTM and UA, the `data-cta-name` value is not being recorded anywhere. Removing the unused data-attribute does not change how these CTAs are recorded in UA or GA4 and makes our docs less confusing.
#13238
=> Remove obsolete `data-cta-name` usage

bedrock/products/templates/products/vpn/features.html, bedrock/products/templates/products/vpn/includes/macros.html
Looks like there were still some hard coded English strings in the redesigned VPN pages. Thankfully the strings were already exposed, so an easy fix.
https://github.com/mozilla/bedrock/issues/13935
https://github.com/mozilla/bedrock/issues/13934
- http://localhost:8000/it/products/vpn/
- http://localhost:8000/it/products/vpn/features/
=> Fix hard-coded strings in VPN pages (Fixes #13935, #13934)

bedrock/firefox/templates/firefox/releases/notes.html, bedrock/releasenotes/models.py, bedrock/releasenotes/tests/test_base.py, media/css/firefox/releasenotes.scss
This changeset adds to the 'Progressive Rollout' behaviour added in https://github.com/mozilla/bedrock/pull/13894
Now, if the source data also includes a list of related countries, they will be shown beneath the note, too:
**Note: random countries selected for testing - not real data!**
Resolves #13930 
Contributes to https://github.com/mozilla/nucleus/issues/811
* Download and unzip  [bedrock-with-rollout-countries-faked-data.db.zip](https://github.com/mozilla/bedrock/files/13460124/bedrock-with-rollout-countries-faked-data.db.zip), rename it to `bedrock.db` and swap it in for your current `bedrock/data/bedrock.db` file -- I've tweaked some release notes to have the expected/future schema and data
* `npm start`
* Go to http://localhost:8000/en-US/firefox/120.0/releasenotes/ and you'll …
=> Show country list specific to a progressive rollout, if data exists

.github/workflows/pull_request_tests.yml, Dockerfile
Updated bedrock to build using Node v20 in both Docker and CI
#13938
Successful test run: https://github.com/mozilla/bedrock/actions/runs/7016709616
=> Update bedrock to build using Node v20 (Fixes #13938)

docs/attribution/0001-analytics.rst
Document existing and future behaviour of data-cta-* attributes.
- changing data-cta-type to specifically indicate if the CTA is for a product
- data-cta-type is no longer required, any of the data-cta-* attributes listed will trigger the event
#13238 
See also: #3948
=> Add documentation for cta_click in GA4 (#13238)

bedrock/products/templates/products/vpn/landing-refresh.html, bedrock/products/templates/products/vpn/landing.html, bedrock/products/templates/products/vpn/variants/landing-1.html, bedrock/products/templates/products/vpn/variants/landing-2.html, bedrock/products/templates/products/vpn/variants/landing-refresh-1.html, bedrock/products/templates/products/vpn/variants/landing-refresh-2.html, bedrock/products/tests/test_views.py, bedrock/products/views.py, media/css/products/vpn/landing.scss, media/js/products/vpn/landing-experiment-pricing-position.es6.js, media/static-bundles.json
Adds an experiment testing the position of the pricing section of the VPN landing page, on both the refreshed design and the old one (still shown to locales that haven't completed translation of the new page).
https://app.asana.com/0/1204604936721242/1205946965841043/f
This is planned to run concurrently with the NA holiday banner test, so it's shown in only countries *outside* the US and CA to avoid collisions. If you're testing locally in the US or CA you'll need to use the `geo` param to evade the banner experiment.
You can use the `xv=legacy` param to get the old page locally.
http://localhost:8000/en-US/products/vpn/?geo=DE
http://localhost:8000/en-US/products/vpn/?geo=DE&xv=legacy
Should redirect to one of two variants:
http://localhost:8000/en-US/products/vpn/?geo=DE&entrypoint_expe …
=> Test pricing position on VPN landing page

bedrock/foundation/urls.py, tests/redirects/map_globalconf.py
Not to be merged until the launch of the new SOM site.
=> Fix #13924: Redirect /foundation/annualreport/ to new SOM report

bedrock/mozorg/urls.py
Adds trailing slash to `/antiharassment-tool/`
=> Fix footprint scrubber URL

gcp/bedrock-demos/cloudrun/mozorg-demo.env.yaml
@alexgibson Once this is merged, rebase your branch on `main` and push it back up a demo and it'll use the dev bouncer instead
=> Set BOUNCER_URL for demos to be the dev bouncer, for all demos

media/js/glean/init.es6.js, media/js/glean/page.es6.js, media/js/glean/utils.es6.js, package-lock.json, package.json, tests/unit/spec/glean/page.js, tests/unit/spec/glean/utils.js
This PR tests out a pre-release of Glean 4.0.0 with the following changes:
- Uses `sendBeacon()` as an event uploader for improved data accuracy.
- Records the new default `page_load` event, which will be a new standardized format for page load metrics that can be used in automated dashboard creation.
- This is a pre-release version of Glean, but since were only using it right now when `Dev=True`, it should be safe enough for us to use in testing.
- I've left the old page hit event in for now (so you should see two event pings on page load). I'll remove the old event once we're confident that data looks OK.
https://github.com/mozilla/bedrock/issues/13431
1. `npm install`
2. `npm start`
3. Open http://localhost:8000/en-US/ and enter `window.Glean.setLogPings(true)` in the console.
4. …
=> Update to Glean 4.0.0-pre.2

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
Update /truecolors/ vanity redirects to point directly to /firefox/
/truecolors/  redirects directly to /firefox/ 
#12613 
https://truecolors.firefox.com/.
=> Update /truecolors/ vanity redirects to point directly to /firefox/

bedrock/firefox/templates/firefox/releases/notes.html
Update release notes page title for developer edition
This PR modifies the title of the release notes page for the Developer Edition to improve clarity. The updated title now reads "Firefox Beta and Developer Edition Release Notes" to reflect that it is the correct page for both browsers.
#13142
All tests passed
=> Update release notes page title for developer edition - Fixes #13142

bedrock/products/templates/products/vpn/includes/download-faq.html, l10n/en/products/vpn/platform-post-download.ftl
Small follow up fix for https://github.com/mozilla/bedrock/issues/14008 where a new Fluent string ID should have been used.
#14008
http://localhost:8000/en-US/products/vpn/download/mac/thanks/
=> Create new Fluent string for monitor name change (Issue #14008)

glean/metrics.yaml, media/js/glean/init.es6.js, media/js/glean/page.es6.js, media/js/glean/utils.es6.js, package-lock.json, package.json, tests/unit/spec/glean/page.js, tests/unit/spec/glean/utils.js
Now that we've migrated to using the new default `page_load` event, we can remove the old custom event and much of the logic around it. Some of the older metrics such as `metrics.path`, `metrics.referrer` etc are left in for now, as they are still used by click events for the time being.
Also adds a commit to update to v4.0.0-pre.3, which fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1868748
#13431
1. `npm install`
2. `npm start`
3. Open http://localhost:8000/en-US/ and enter `window.Glean.setLogPings(true)` in the console.
4. Refresh the page and you should now only see one event logged.
New event should contain:
```
"events": [
{
"category": "glean",
"name": "page_load",
"timestamp": 0,
"extra": {
"url": "http://localhost:8000/en-US/",
"referrer": "",
"title": "Internet for people, …
```
=> Remove old Glean page hit event (Issue #13431)

docs/attribution/0002-firefox-desktop.rst, media/js/base/stub-attribution.js, media/js/firefox/all/all-downloads-unified.js, tests/unit/spec/base/stub-attribution.js
Enables Firefox desktop attribution for macOS download/installer links (Nightly only for now).
#12761
> [!IMPORTANT]
> Test in a browser with DNT disabled
1. Next, open https://www-demo3.allizom.org/en-US/firefox/channel/desktop/.
2. Verify that the Nightly download link also contains `attribution_code` and `attribution_sig` parameters.
3. Verify that the Beta / Dev download links do not contain attribution params.
=> [Jan 8] Include attribution data with macOS Nightly links (Fixes #12761)

media/js/base/stub-attribution.js, tests/unit/spec/base/stub-attribution.js
Add JS to check that the GTM API has loaded and extract the client and session ID if it has. Then add an event to the dataLayer if the check has succeeded.
Biggest additions are `waitForGTMAPI` and `getGAData`.
Should I actually log the client ID? Or is it enough to know that we got it successfully?
https://github.com/mozilla/bedrock/issues/12801
https://github.com/mozilla/bedrock/issues/13238 
Must be tested with a windows computer.
=> Test getting GA4 client_id from GTAG API 

bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
These links seem pretty old and are of low value because Mozillians.org now redirects to people.m.o which in turn needs a user to be authenticated in order to see profiles.
Mark's link redirected to a valid people.m.o page, but behind auth Angela and Ashley's profiles had moved to a different slug on people.m.o.
Also, the link for Mitchell's profile was wrong and was pointing to one with a similar slug but not her actual people.m.o profile
Resolves #14059
* Check http://localhost:8000/en-US/about/leadership/ for Mitchell
* Check http://localhost:8000/en-US/about/leadership/#foundation for Mark, Angela and Ashley
=> Remove links to Mozillians.org from leadership pages

docs/redirects.rst
Fixes #11525 
Updated the redirect method definition to include the following options:
```
re_flags,
to_args, 
to_kwargs, 
prepend_locale, 
merge_query
```
Ref : https://github.com/mozilla/bedrock/blob/main/bedrock/redirects/util.py
=> docs: Modify the documented redirect method definition

bedrock/careers/templates/careers/benefits.html, bedrock/careers/templates/careers/home.html, bedrock/careers/templates/careers/locations.html, bedrock/careers/templates/careers/teams.html, bedrock/firefox/templates/firefox/browsers/compare/brave.html, bedrock/firefox/templates/firefox/browsers/compare/chrome.html, bedrock/firefox/templates/firefox/browsers/compare/edge.html, bedrock/firefox/templates/firefox/browsers/compare/ie.html, bedrock/firefox/templates/firefox/browsers/compare/opera.html, bedrock/firefox/templates/firefox/browsers/compare/safari.html, bedrock/firefox/templates/firefox/privacy/products.html, bedrock/products/templates/products/vpn/pricing-refresh.html, lib/l10n_utils/templatetags/fluent.py
This PR adds the `data-cta-text` attribute to any elements with a `data-cta-type` attribute defined.
- Add `data-cta-text` values to tags with` data-cta-type` defined
- Fix #13749 where data attributes were not being output by Fluent templates
In #14056 we standardized on requiring a "text" value to trigger link and cta click events. 
Fix #13749
- Here is an example of one of the pages with the bug from 13749: http://localhost:8000/en-US/firefox/browsers/compare/brave/
- Maybe make sure I didn't add a `data-cta-text` if there already was one? 
- No missing quotes or spelling mistakes.
=> Add missing data-cta-text values

.github/workflows/cdn_tests.yml, bin/integration_tests/run_integration_tests.sh
Sometimes the CDN tests fail, even with the default 2 retries. This changeset allows us to pass custom params for the number of retries as well as how long to back off for between retries, in the hope that we get more successes for the CDN tests.
No ticket
Might just have to be eyeballs until it hits main
=> Allow more time before retries of CDN tests, plus one extra retry

bedrock/firefox/templates/firefox/family/includes/modules/privacy.html
Fixes https://mozilla.sentry.io/issues/4876118599/?alert_rule_id=10555963&alert_timestamp=1705421496699&alert_type=email&environment=production&notification_uuid=468fc484-3edb-4ff9-a087-3a58f5af0e10&project=6260211&referrer=alert_email
=> Fix set-as-default URL link

bedrock/firefox/templates/firefox/releases/notes.html, media/css/firefox/releasenotes.scss
This changeset fixes a reflow issue on release notes, which was particularly noticeable on Nightly's notes, because sometimes there is a Bug Id link set to the right side of the note.
High five to @reemhamz for finding a lightweight fix, quickly.
It also fixes a HTML validation bug: `div`s are not allowed in `hX` elements. The fix is visually identical.
*Release notes before*
*Release notes after*
*Also confirming that when the Progressive Rollout and countries list are present, they do not break with this change*
* Invalid HTML in h2 before afterfix*
Resolves #14097 
* On `main`, locally go to http://localhost:8000/en-US/firefox/nightly/notes/ 
* If you can't see the reflow, edit one of the notes in devtools to make it very short (less than 1 line long)
* Switch to this branch and …
=> Fix Nightly release notes rendering

bedrock/firefox/templates/firefox/new/desktop/download.html
Updates Firefox for iOS app store link so that DS can get aggregate data on the number of installs that came from the /new page.
#14099
=> Update Firefox iOS app store link on /firefox/new/ (Fixes #14099)

media/js/base/stub-attribution.js, media/js/firefox/all/all-downloads-unified.js, tests/unit/spec/base/stub-attribution.js, tests/unit/spec/firefox/all/all-downloads-unified.js
Enables Firefox attribution links for all macOS pre-release channels.
> [!Important]
> This needs to go live on Monday 22nd Jan for QA.
#12761
> [!Note]
> Test in a macOS browser with DNT disabled. For the `/firefox/all/` page you'll need to inspect the network request when clicking download to see the attribution params added in the request. For the other pages you should be able to see the `attribution_sig` and `attribution_code` params added to the download link HTML.
=> Add attribution params to Firefox pre-release download links on macOS (Issue #12761)

l10n/en/firefox/developer.ftl
Remove comma as requested in mozilla-l10n/www-l10n#371
Remove the comma before `in addition to features ...`
_Originally posted by @peiying2 in https://github.com/mozilla-l10n/www-l10n/pull/371#discussion_r1446787146_
=> Fix punctuation on developer edition page

.github/ISSUE_TEMPLATE/z_gtm_review.md
Create GTM review "issue" template.
We have been tracking GTM reviews in GitHub through issues and I've kind of settled on a format for them (it's basically the same one we use for code reviews). I'd like to streamline my workflow by adding it to the list of options when creating a new issue. Here's an example of what I am trying to replicate: #13948 
n/a
🤷‍♀️
=> Create GTM review issue template

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-na.html, media/css/firefox/whatsnew/whatsnew-122-na.scss
Updates for better clarity and accuracy.
* Remove DuckDuckGo.
* Change Safari to “yes” for fingerprinting resistance.
* Increase tagline font size.
http://localhost:8000/en-US/firefox/122.0/whatsnew/
=> Updates to NA WNP for Firefox 122 [#14058]

bedrock/settings/__init__.py
https://github.com/mozilla/bedrock/issues/14118 shows some new CSP errors for the One Trust banner on dev (and we'll likely see them on stage and prod when the OT JS is working properly again. This fixes the CSP error.
https://github.com/mozilla/bedrock/issues/14118
=> Add appropriate CDN to CSP for OneTrust banner in Pocket Mode

bedrock/settings/__init__.py
Updates Pocket's `COOKIE_CONSENT_SCRIPT_SRC` to always return the dev URL, removing the deprecated prod URL.
#14122
=> Update Pocket’s OneTrust script [fix #14122]

docs/attribution/0001-analytics.rst, package-lock.json, package.json
Glean 4.0 is out of beta so this just updates us to the main release version. No other changes
N/A
- `npm start`
=> Update to Glean 4.0.0

wsgi/uwsgi.ini
When testing on dev we found that spawning workers took about 4-5 seconds per worker, so 4 workers would take about 20 seconds to spin up, causing a lot of health check flapping and pod churn. Locally testing pre-forking allowed for much faster start-up times, so we'll test this on dev.
=> Test with lazy-apps = false

bin/integration_tests/functional_tests.sh
=> Add missing pass-through of rerun-related env vars

bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py, docs/attribution/0001-analytics.rst, media/js/base/datalayer-productdownload.es6.js, tests/unit/spec/base/datalayer-productdownload.js
Split GA4 event `product_download` into product specific conversion events and keep `product_download` around for a few months to help compare before/after changes.
- Send two events for each "Product Download": `[product name]_download` and `product_download`.
- Update documentation.
- Removed 'mobile' as a platform option. When adjust does not redirect to a specific store, platform is now empty.
Fix #14072
A task to remove the old `product_download` event has been added to https://github.com/mozilla/bedrock/issues/13238 (I'll flesh it out as a real issue once I have an idea of the timeline to remove it.)
- `firefox_download`: http://localhost:8000/en-US/firefox/all/
- `firefox_mobile_download`: http://localhost:8000/en-US/firefox/browsers/mobile/android/
- `focus_download`: …
=> Split GA4 event product_download into product specific events Fix #14072

l10n/en/download_button.ftl
Minor fixes to the Linux button strings, based on feedback in https://github.com/mozilla-l10n/www-l10n/pull/372#discussion_r1474968306
=> String fixes for Linux download buttons

bedrock/firefox/templates/firefox/features/translate.html
Updated the strings in the Firefox Features Translate page for better SEO
[Copy doc](https://docs.google.com/document/d/1i2_6irK_nYdWAjpIX5OSOGipfYFkCedgYC0PLdGlx_M/edit#heading=h.hn4ehg2fnbxz)
https://github.com/mozilla/bedrock/issues/14134
http://localhost:8000/en-US/firefox/features/translate/
=> Update strings for Firefox Features Translate page [fix #14134]

bedrock/firefox/templates/firefox/includes/download-button.html, bedrock/firefox/templates/firefox/includes/macros.html, bedrock/firefox/templates/firefox/new/basic/thanks.html, bedrock/firefox/templates/firefox/new/desktop/thanks.html, l10n/en/download_button.ftl
Oops, I hadn't realized the previous strings had already been exposed to localizers, so the fixed ones need new IDs.
https://github.com/mozilla-l10n/www-l10n/pull/374#pullrequestreview-1858425577
=> More string fixes for Linux download buttons

media/js/base/datalayer-productdownload.es6.js
Fixes an error that is caused when trying to send an event and `getEventFromUrl()` returns a boolean instead of an object.
#14177
1. Open http://localhost:8000/en-US/firefox/122.0/releasenotes/
2. Open the web console and make sure you have "Persist logs" checked.
3. Scroll to the bottom of the page where it says "Get the most recent version" and click "Download Firefox"
4. Verify there is no longer a JS error on click.
=> Fix JS error in GA4 event tracking (Fixes #14177)

bedrock/products/templates/products/vpn/includes/macros.html
Looks like these hard-coded strings were left over from when the redesigned pages were still an en-Us only.
#14179
http://localhost:8000/de/products/vpn/
=> Remove hard-coded English strings from VPN nav CTA (Fixes #14179)

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
There are no functional changes here and tests are passing 100%, so I think the risk is very low.
SUMO is also trying out 3.8rc0 for us.
EDIT: Integration tests are 🟢 https://github.com/mozilla/bedrock/actions/runs/7724065824
=> Update django-csp to 3.8 release candidate version, to test out on Bedrock

bedrock/firefox/templates/firefox/products/index.html, tests/functional/firefox/test_products.py, tests/pages/firefox/products.py
So it turns out simply hiding the second CTA in https://github.com/mozilla/bedrock/pull/14189 wasn't such an easy fix after all. That second CTA has been part of the page for a long time and we had functional tests to verify it was displayed. Removing it for one locale made that test fail. We could have updated the test to skip en-US but it was decided to simply remove the second CTA for all locales (and remove the test as well).
#14188 
http://localhost:8000/firefox/products/
Make sure functional tests pass: `$ py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/firefox/test_products.py`
=> Remove second Monitor CTA from Firefox products page [#14188]

bedrock/firefox/templates/firefox/channel/android.html, bedrock/firefox/templates/firefox/channel/desktop.html, l10n/en/firefox/channel.ftl
Add a warning/notice that Nightly will be updated once/twice a day 
#9832 
http://127.0.0.1:8000/en-GB/firefox/channel/desktop/
http://127.0.0.1:8000/en-GB/firefox/channel/android/
=> Add a warning that Nightly will be updated once/twice a day

tests/functional/firefox/browsers/compare/test_browsers.py
I forgot to remove IE from the comparison pages test file, so doing that here
Sibling PR: https://github.com/mozilla/bedrock/pull/14167
=> Remove IE from `test_browsers.py` test file

bedrock/careers/templates/careers/home.html
This PR addresses the alignment issue in the  "_See yourself on one of our teams?_" section text.
I added a `c-careers-section-title` class to the corresponding heading tag. This ensures that the text behaves consistently with other section titles.
#14078
=> Fix text alignment in a section of careers page (issue #14078)

bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
Malformed link in the CTD footer. The `|safe` bit needs to be at the end.
#14192 
http://localhost:8000/de/firefox/
http://localhost:8000/fr/firefox/challenge-the-default/
=> Fix footer community link formatting on CTD page [fix #14192]

bedrock/mozorg/templates/mozorg/security.txt, bedrock/mozorg/tests/test_views.py, bedrock/mozorg/urls.py, bedrock/mozorg/views.py, bedrock/settings/base.py
Adds a page at `.well-known/security.txt` as requested by the security team. Does not redirect to en-US, the same as robots.txt does
```
Email: security@mozilla.org
Main info: https://www.mozilla.org/en-US/security/
Bounty program: https://www.mozilla.org/en-US/security/bug-bounty/
```
Resolves #14173
* See https://www-demo6.allizom.org/.well-known/security.txt
=> Add a security.txt URI

bedrock/firefox/redirects.py, bedrock/redirects/util.py, tests/redirects/map_globalconf.py
Adds a helper that detects Android/iOS and then redirects to the appropriate mobile app store URL (with optional campaign parameters). Default fallback is to Apple App Store.
Note: the redirect at `firefox/browsers/mobile/app/` isn't used by anything yet, but my hope is to use this URL to embed inside QR Codes, as a replacement for Adjust links in https://github.com/mozilla/bedrock/issues/14172
https://github.com/mozilla/bedrock/issues/14172
=> Add mobile app store redirector (Issue #14172)

bedrock/careers/templates/careers/diversity.html
Adds missing page bundle to fix the JS error on video thumbnail click.
#14211
http://localhost:8000/en-US/careers/diversity/
=> Fix /careers/diversity/ video error (Fixes #14211)

media/js/base/stub-attribution.js, media/js/firefox/all/all-downloads-unified.js, tests/unit/spec/base/stub-attribution.js, tests/unit/spec/firefox/all/all-downloads-unified.js
Enables Firefox desktop attribution for all macOS download links (removing pre-release restrictions).
> [!Important]
> Aim is to merge this and deploy around 9am ET on Tuesday 20th
#12761
> [!Note]
> Test in a macOS browser with DNT disabled. For the `/firefox/all/` page you'll need to inspect the network request when clicking download to see the attribution params added in the request. For the other pages you should be able to see the `attribution_sig` and `attribution_code` params added to the download link HTML.
=> Enable attribution for all macOS Firefox download links (Fixes #12761)

media/js/base/stub-attribution.js, media/js/firefox/all/all-downloads-unified.js, tests/unit/spec/base/stub-attribution.js
Excludes attribution data from macOS ESR links
#14216
=> Omit macOS attribution for ESR links (Fixes #14216)

bedrock/firefox/templates/firefox/releases/aurora-notes.html, bedrock/firefox/templates/firefox/releases/beta-notes.html, bedrock/firefox/templates/firefox/releases/dev-browser-notes.html, bedrock/firefox/templates/firefox/releases/nightly-notes.html, bedrock/firefox/templates/firefox/releases/notes.html, media/css/firefox/releasenotes.scss
Updates templates and styles to display the correct product logo on release notes for each Firefox channel, including older legacy logos. This was a regression we missed when updating to Protocol 19 and the refactored callout that no longer has baked-in logos.
#14214 
https://bugzilla.mozilla.org/show_bug.cgi?id=1880831
Appropriate logos should appear:
http://localhost:8000/en-US/firefox/30.0a2/releasenotes/ - Aurora
http://localhost:8000/en-US/firefox/50.0a2/releasenotes/ - Developer, pre-Quantum
http://localhost:8000/en-US/firefox/55.0beta/releasenotes/ - Beta, pre-Quantum
http://localhost:8000/en-US/firefox/60.0beta/releasenotes/ - Beta, Quantum
http://localhost:8000/en-US/firefox/120.0/releasenotes/ - Beta, current
http://localhost:8000/en-US/firefox/55.0a1/releasenotes/ - Nightly, …
=> Fix release notes header branding [fix #14214]

bedrock/mozorg/templates/mozorg/home/home-new.html, l10n/en/mozorg/home-new.ftl
Mitchell Baker's title has changed from CEO to Executive Chair of the Board for MoFo, so we've updated her quote on the homepage to reflect that change.
- http://localhost:8000/en-US/
=> Update Mitchell Baker's title in homepage

bedrock/base/templates/includes/protocol/footer/footer.html
Adds link to `/de/about/legal/impressum/` in footer for all `/de/` pages.
#14240
=> Add Impressum link to /de/ footer (Fixes #14240)

bedrock/mozorg/redirects.py, bedrock/mozorg/urls.py, media/js/mozorg/rise25/rise25.js, tests/redirects/map_globalconf.py
The /rise25/ URL previously had a permanent redirect to rise25.mozilla.org. That redirect gets cached by the browser and is hard to overcome from our end, so basically anyone who visited that URL in the past months while that redirect was in place will be unable to reach the new page. The simplest fix is to move the new page to another URL.
http://localhost:8000/rise25/nominate/
Make sure I didn't miss any references or links to the previous URL.
=> Update Rise25 nomination page URL [#14200]

bedrock/mozorg/templates/mozorg/rise25/landing.html
The page extends `base-protocol.html` which defaults to `summary` for Twitter cards. This overrides that with `summary_large_image` so the link preview will include the page image on Twitter.
This was discovered because Slack seems to use Twitter card data to determine whether to show an image or just text. Even though the `og:image` was present, Slack was respecting the Twitter card.
http://localhost:8000/rise25/nominate/
=> Rise25, add image to Twitter card metadata [#14200]

bedrock/firefox/tests/test_helpers.py, bedrock/firefox/tests/test_views.py, bedrock/firefox/views.py, docs/attribution/0002-firefox-desktop.rst, media/js/base/stub-attribution.js, media/js/firefox/new/common/thanks-direct.js, tests/unit/spec/base/stub-attribution.js
Send GA4 client ID to stub attribution as `client_id_ga4`.
I'm sorry to say this has a bit of urgency. It cannot be merged until the stub attribution server is updated but we should get a jump start on reviewing it - especially since we want a VERY THROUGH review.
- stub attribution now waits for both UA and GTM API before executing
- GA4 client ID is retrieved from GTM API
- data sent to stub attribution now includes the GA4 client ID as `client_id_ga4`
- updated and added tests
- tried to standardize on UA/GA4 when talking about the old and new versions
- tried to be explicit about when we're interacting with GTM rather than UA/GA4 directly
- changed references to scene2 to download/thanks
- added some steps for code review into the docs
Fix #12801 
I worked on this over a couple weeks …
=> Add GA4 client ID to stub attribution

.github/actions/slack/action.yaml, .github/workflows/cdn_tests.yml, .github/workflows/demo_deploy.yml, .github/workflows/download_tests.yml, .github/workflows/fluent_linter.yml, .github/workflows/integration_tests.yml, .github/workflows/pull_request_tests.yml, .github/workflows/send_mozorg_fluent_strings_to_l10n_org.yml, .github/workflows/send_pocket_fluent_strings_to_l10n_org.yml
Update our GHAs to use the latest node-20-based workflow, as the node-16 ones are deprecated and we don't want to be caught out if they stop working.
Resolves #14147 
Some of these we can run directly from the branch, but really we should just merge and see how they are. The only that looks like it _might_ need a bit of tuning is `upload_artifact` and we'll see that as soon as this PR hits `main`
=> Update Github Actions to use Node 20 runtime

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-static.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-video.html, tests/functional/firefox/whatsnew/test_whatsnew_124.py
Updates UTMs for Monitor CTA on WNP 124.
#14296
- http://localhost:8000/en-US/firefox/124.0/whatsnew/
- http://localhost:8000/en-US/firefox/124.0/whatsnew/?v=1
- http://localhost:8000/en-US/firefox/124.0/whatsnew/?v=2
=> Update WNP24 monitor link utms (Issue #14296)

docs/attribution/0003-firefox-mobile.rst
Adds links in our docs for where to find install referral data for Firefox on mobile
N/A
=> Add mobile install data links to docs

l10n/en/firefox/features/fast-2024.ftl
Change requested in https://github.com/mozilla-l10n/www-l10n/pull/381
"never ending" -> "never-ending"
http://localhost:8000/en-US/firefox/features/fast/
=> String fix for speed feature page [#14298]

bedrock/base/templates/base-protocol.html, bedrock/firefox/templates/firefox/whatsnew/base.html
We're moving a lot of our content and persona to be within a pan-Mozilla umbrella, and that includes making sure we have a consistent theme within our website, as well.
We typically had a light-theme footer placed in Firefox pages, and we're going to be switching it to the typical dark-theme footer we have across the rest of the site.
> [!NOTE]
> We will not be removing the light-theme footer in Whats New pages until WNP125 releases (April 16th).
There wasn't much that needed changing except only allowing the light-theme to be used in the Whats New page, so I removed the `theme_class` from the `base-protocol.html` file and instead added it to the `/whatsnew/base.html` file.
https://github.com/mozilla/bedrock/issues/14251
=> Retire light-theme footer in Firefox pages

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-de-voices-share.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-de-voices-video.html, media/js/firefox/whatsnew/whatsnew-124-eu-compare.js, media/js/firefox/whatsnew/whatsnew-124-eu-events.js, media/static-bundles.json
Adds some additional GA events to WNP 124 for the EU team
#14181)
- http://localhost:8000/de/firefox/124.0/whatsnew/?v=1
- http://localhost:8000/de/firefox/124.0/whatsnew/?v=2
- http://localhost:8000/de/firefox/124.0/whatsnew/?v=3
=> Add extra GA events for WNP 124 EU (Issue #14181)

docs/contentful.rst
Update docs to point out that we're no longer syncing from Contentful, and for a shortish period will just live with the last sync of the data, before moving it to Wagtail.
=> Add warning panel about Contentful use being frozen/retired

.github/workflows/routine_l10n_obsolete.yml, docs/l10n.rst
Schedule task to remove obsolete l10n strings 
Fix #14259
=> Schedule task to remove obsolete l10n strings Fix #14259

media/js/base/core-datalayer-init.js, media/js/base/core-datalayer.js, tests/unit/spec/base/core-datalayer.js
Removes unused property on GA `core-datalayer-loaded` event.
#14331
- Enter `window.dataLayer` in the web console, and confirm the `core-datalayer-loaded` event no longer includes `pageHasVideo`.
=> Remove pageHasVideo GA event property (Fixes #14331)

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
Redirecting vanity URL /research/ to foundation.mozilla.org/research/ (previously went to research.mozilla.org)
Also redirects /research/cc/ to the same URL but that will eventually point somewhere else, but for now it goes to the same place.
#14351
http://localhost:8000/research/
http://localhost:8000/research/cc/
=> Update /research redirect [fix #14351]

bedrock/careers/templates/careers/position.html
Updates the link to the applicant privacy notice on job postings.
#14348 
http://localhost:8000/en-US/careers/listings/
Any single job listing should have the link at the bottom, but what listings you have locally will depend on when you last synced from Greenhouse.
=> Careers: update applicant privacy notice [fix #14348]

bedrock/firefox/templates/firefox/developer/firstrun.html, bedrock/firefox/templates/firefox/developer/includes/for-developers.html, bedrock/firefox/templates/firefox/developer/index.html, bedrock/firefox/templates/firefox/developer/whatsnew-mdnplus.html, bedrock/firefox/templates/firefox/installer-help.html, l10n/en/firefox/developer.ftl, l10n/en/firefox/installer-help.ftl, l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
Some strings got merged that needed new IDs to prevent mismatch errors. This restores (or deletes) the old strings and assigns new IDs to the new ones.
https://github.com/mozilla-l10n/www-l10n/pull/387
http://localhost:8000/en-US/firefox/99.0a2/firstrun/
http://localhost:8000/en-US/firefox/99.0a2/whatsnew/
http://localhost:8000/en-US/firefox/installer-help/
=> String fixes for Developer Edition pages [#14243, #14244]

media/js/glean/init.es6.js, package-lock.json, package.json
This adds support for sessions, plus sendBeacon is now the default uploader. Glean is only enabled when Dev=True currently, so testing out this change should be safe.
N/A
- `npm start`
=> Update to Glean 5.0.0

bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
Fixes the top-level URL for "Innovation" from abandoned https://labs.mozilla.org to currently most relevant https://future.mozilla.org
The site labs.mozilla.org is now empty, generally returning 404 errors and not redirecting elsewhere or showing any sunset information so it feels broken.
While the "Innovation" items now generally link to `future.m.o`, the top level nav item still points to `labs.m.o` — and while not "clickable" with JS handling the submenu instead, it can still be right-clicked e.g. to open in a new tab and acts a top-level item for nonJS UAs and crawlers alike, so this should be updated to be usable even for these edge cases.
The linked issues added menu item references to `future.m.o` so I think it is a safe link target for the top level menu item too.
Followup of …
=> Update main menu "Innovation" item link

media/js/firefox/share-page.es6.js
Adds a custom event to the "Copy and share" button on the /firefox/share/ page.
I'm not sure what actions/labels are appropriate for this particular interaction... if the ones I set aren't correct, I'm open to suggestion.
#14199 
http://localhost:8000/de/firefox/share/
http://localhost:8000/fr/firefox/share/
=> Share page: add event tracking to copy button [#14199]

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
Updates redirection for removed page now leading to dead site / 404s.
The `/technology` URL is still being linked to from external sites for historic reasons as it used to be hard-coded in blog templates for the past couple of years, and now leads to 404 which doesn't look good (see https://github.com/mozilla/One-Mozilla-blog/issues/74 …), so while maintaining old dead links might sound crazy, having this redirect lead people somewhere useful has actual value.
#14364
=> Update old `/technology` redirect (Fixes #14364)

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
Updates the redirect for /research/cc/ to point to the appropriate category page (now that we have the URL).
#14351 
http://localhost:8000/research/cc/ should redirect to `https://foundation.mozilla.org/research/library/?topics=187`
=> Update research redirect [#14351]

bedrock/mozorg/templates/mozorg/rise25/landing.html
Nomination deadline is being extended two more weeks.
#14200 
http://localhost:8000/rise25/
=> Extend Rise25 nomination deadline [#14200]

.github/workflows/cdn_tests.yml, .github/workflows/download_tests.yml, .github/workflows/integration_tests.yml, .github/workflows/pull_request_tests.yml
Even though V4 has [breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes), particuarly around how uploads with non-unique names are no longer automatically combined this won't be a problem here, I think
Resolves #14147
=> Upgrade upload-artifact action to v4, based on Node 20

bedrock/newsletter/templates/newsletter/management.html, l10n/en/mozorg/newsletters.ftl, media/js/newsletter/management.es6.js, tests/unit/spec/newsletter/management.js
Removes the option to set a preference for text/html based emails.
#14362
1. Get your newsletter token from https://www.mozilla.org/newsletter/recovery/
2. Open the newsletter management page locally via `http://localhost:8000/en-US/newsletter/existing/YOUR_TOKEN_HERE/`
3. Verify the page loads OK and does not render the format option.
4. Change a different option (such as country) and click save preferences, to verify that form submission still works OK.
5. Click "Back to email preferences" on the next page, and verify the management page loads again with your updated preference.
=> Remove format option from newsletter management page (Fixes #14362)

bedrock/base/templates/404.html, bedrock/careers/templates/careers/404.html, l10n/en/404.ftl
Adds new "Donate" link to CTAs displayed for 404 error pages.
- also removes "Explore" item as per #14209
- removes now unused Fluent string for "Explore" CTA
- adds a new string to localize the "Donate" CTA with no fallback currently present
- doesn't use `donate_url()` as the requested URL has different `?form` param and no tags as per https://github.com/mozilla/bedrock/issues/14209#issuecomment-1965308185
- references "heart" icon (used in Protocol as "Give" CTA etc.) as `"default-browser"`, so in case the metaphor changes upstream in future this CTA might also change its icon meaning;)
Resolves #14209
`run-prod` with `DEBUG=False`:
http://localhost:8000/en-US/foo/bar/404/
http://localhost:8000/en-US/careers/position/foo/404/
=> Add "Donate" link to 404 pages

media/js/firefox/features/features-article.es6.js
The Firefox download CTA shouldn't show in Firefox mobile apps, but it is on the `/features/` pages, so I patched that up.
https://github.com/mozilla/bedrock/issues/14429
Open using your Firefox mobile browser on your phone and go to any of the features pages:
=> Removed download CTA in `/firefox/features/` pages for Firefox mobile

bedrock/firefox/templates/firefox/testflight.html, bedrock/mozorg/forms.py, bedrock/mozorg/templates/mozorg/antiharassment-tool.html, bedrock/newsletter/forms.py, bedrock/newsletter/templates/newsletter/includes/form.html, bedrock/newsletter/tests/test_forms.py, bedrock/newsletter/tests/test_views.py, bedrock/newsletter/views.py, bedrock/products/templates/products/mozsocial/invite.html, bedrock/products/templates/products/vpn/invite.html, l10n/en/newsletter_form.ftl, package-lock.json, package.json, tests/functional/firefox/test_ios_testflight.py, tests/functional/newsletter/test_monitor_waitlist.py, tests/functional/newsletter/test_newsletter_embed.py, tests/functional/newsletter/test_newsletter_family.py, tests/pages/firefox/ios_testflight.py, tests/pages/regions/newsletter.py, tests/unit/spec/newsletter/data.js, tests/unit/spec/products/vpn/invite.js
The email marketing team requested we remove the `format` option that allows users to choose whether to receive emails as HTML or as Text-based markup since Braze does not support these options.
> [!NOTE]
> Part of getting this to work bedrock-wide was to upgrade the Newsletter component in Protocol, so we published `v19.1.0` with the latest update.
You should now be able to sign-up for a newsletter without seeing a `format` option, and it should submit successfully
https://github.com/mozilla/bedrock/issues/14362
This should work on any page with a newsletter sign-up, but here are some sample pages that have the newsletter component:
=> Protocol v19.1.0 -- Remove `format` option across newsletters in Bedrock

Makefile, bin/custom-git-hooks/README.txt, bin/custom-git-hooks/post-merge
Sometimes it's easy to miss that dependencies (Node and/or Python) need updating after a pull on `main`. This changeset adds a git hook that, when installed, will fire after a merge and print out a reminder message if deps need updating:
(The pull contained more than just the files in the screenshot - it's a cropped screenshot)
It also adds commands to the `Makefile` to, er, make it easy to install and uninstall this custom hook
I've tested this a fair bit locally, but the more testing the better, particularly if you _don't_ use git on the CLI
=> Add a git hook that reminds developers if dependencies have just been updated after a pull/merge 

Dockerfile
Silencing warnings by abandoning 20th century syntax;)
This is now POSIX-friendly to be more futureproof…
[runs/8623777967/job/23637585321?pr=14438#step:4:5445](https://github.com/mozilla/bedrock/actions/runs/8623777967/job/23637585321?pr=14438#step:4:5445) (before)
vs.
[/runs/8623995234/job/23638213885?pr=14439#step:4:5495](https://github.com/mozilla/bedrock/actions/runs/8623995234/job/23638213885?pr=14439#step:4:5495) (after)
=> Update Dockerfile chown separators

bedrock/firefox/tests/test_helpers.py, bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json, bedrock/settings/base.py, docs/send-to-device.rst, l10n/en/mozorg/newsletters.ftl, tests/unit/spec/newsletter/data.js
This drops some old unused newsletter IDs and combines the android/iOS since they use the same email template. This also replaces the "download-firefox-mobile-whatsnew" email to use the "download-firefox-mobile" email which we were already doing in Acoustic but this simplifies the set up for Braze, dropping the need to create extra events and campaigns for these.
=> Update newsletter IDs to match Braze migration

bedrock/mozorg/templates/mozorg/rise25/landing.html, media/css/mozorg/rise25/components/hero.scss
Puts the nomination bits behind the switch `rise25-nominations-open` (which we'll need to pre-flip so we can then flip it OFF late in the day on the 12th). When the switch is OFF the buttons will be hidden and a "nominations closed" message appears in the hero.
#14200
http://localhost:8000/rise25/nominate/
=> Close nominations for Rise25

bedrock/firefox/templates/firefox/features/private.html, media/css/firefox/features/article.scss, media/js/firefox/features/features-article.es6.js
Marketing is testing out a campaign and they'd like to see what adding a Firefox download CTA to `/features/private/` page will result in
Fixes https://github.com/mozilla/bedrock/issues/14428
=> Add download CTA for `fr` and `de` /features/private/ page

bedrock/releasenotes/redirects.py, tests/redirects/map_globalconf.py
Redirects `/firefox/125.0/releasenotes/` to `/firefox/125.0.1/releasenotes/`
#14467 
http://localhost:8000/firefeox/125.0/releasenotes/
=> Redirect Firefox 125.0 release notes [fix #14467]

bedrock/settings/__init__.py
Expands `CSP_FONT_SRC` the same way addt'l hosts are added to e.g. `CSP_STYLE_SRC` to avoid surprises when run from different hosts as moz.works or run.app… (loaded from the same absolute URIs as styles, so to match the hosts…)
The other rules start with defaults and add more values. Fonts are the exception to this, only specifying its values. This change makes it more consistent, also starting out with defaults (thus also covering anything needed for both mozorg & pocket mode straight away), that make the effective rule a bit wider than used to be — but basically matches what's in `style-src` anyways so that should be okay~ish.
This could be further optimised to only add `self` for prod, and the extra defaults only for dev or with extra defaults set only etc., but this is the least …
=> Fix fonts CSP for staging

bedrock/firefox/templates/firefox/developer/includes/features.html
[On the landing page](https://www.mozilla.org/en-US/firefox/developer/) of firefox developer edition, one section is showing wrong header, probably due to copy and paste error in template.
None
None
None
=> Fix copypaste error

bedrock/firefox/firefox_details.py, bedrock/firefox/templates/firefox/all-unified.html, bedrock/firefox/tests/test_base.py, bedrock/firefox/tests/test_helpers.py, l10n/en/firefox/all.ftl, media/css/protocol/components/_download-button.scss
Adds "Linux ARM64/AArch64" as an installer option for Firefox Nightly on the `/firefox/all/` page.
#14414
=> Add Linux/ARM64 Firefox Nightly builds to firefox/all (Fixes #14414)

bedrock/sitemaps/management/commands/update_sitemaps.py, bedrock/sitemaps/utils.py
Since the refactor to use Django's i18n mechanism in #14256, not our original `Prefixer`, resolved URLs are automatically prepended with `settings.LANGUAGE_CODE`, which means the `update_sitemaps` management command (used by www-sitemap-generator) creates a sitemap.json containing paths prefixed with `en-US/`, which downstream use of this data for sitemap generation is not expecting. 
The simplest fix was to drop that part of the path.
Resolves #14480
Tricky to test end-to-end, or to write meaningful tests for, but I have extracted three examples of the sitemap.json file, showing that this changeset generates an identical (except for ordering of array elements) version of the data:
* `main` currently generates this: [broken_sitemap.json](https://github.com/mozilla/bedrock/files/15039955/br …
=> Fix sitemap generation

bedrock/settings/base.py
GreenletExits are currently at ~38k/day and eating quota, but we don't believe they are actually a problem as the traceback suggests it's a switch going on.
This changeset will stop them being sent to Sentry altogether.
Please only approve/merge if you agree that this is wise. We can still do further investigation into GreenletExceptions afterwards, but we won't have any fresh data/examples
=> Add GreenletExit to list of unactionable exceptions that we don't send to Sentry

package-lock.json, package.json
- Bumps @sentry/browser to v7.111.0.
- ~Also updates some deprecated function names in preparation for [migration of v7 -> v8](https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#deprecate-hub) in the near future.~
N/A
Set `SENTRY_FRONTEND_DSN=https://c3ab8514873549d5b3785ebc7fb83c80@o1069899.ingest.sentry.io/6260331` in your .env if you would like to test that Sentry initializes locally. You'll also need a browser with DNT disabled.
The main thing to check for is that no JS errors show in the console when `sentry.js` is executed.
=> Bump @sentry/browser to v7.111.0

.github/workflows/cdn_tests.yml, bedrock/base/middleware.py, bedrock/base/tests/test_middleware.py
Previously, we relied on similar code deep in lib.l10n_utils.render, but BedrockLangFixupMiddleware runs way before then, so we need(ed) to add the Vary header here, too.
The orginal code in l10n_utils.render still has value, because it handles the fallback for a missing/unactive language to en-US
Resolves #14498 
Check the headers when you go to /  and it redirects to /en-US/ (or whatever your browser's local language is)
=> Ensure the lang-fixup redirects set a Vary header for Accept-Language

bedrock/mozorg/templates/mozorg/account.html, bedrock/mozorg/templates/mozorg/home/home-new.html
Adds most prominent missing `utm_params` to products / own external links.
- This is just the low-hanging fruit for #14432 with most impact, will look around some more for less prominent locations eventually, too.
- Also removes some passé branding switches, leaving that to ftl fallbacks now.
- Removes some /account ftl conditional logic that mostly doesn't work, when at it.
#14432
http://localhost:8000/en-GB/
http://localhost:8000/en-GB/account/
=> Add referral tags to home & account product links

docs/abtest.rst, media/js/base/core-datalayer-page-id.js, media/js/base/fxa-attribution.es6.js, media/js/base/stub-attribution.js, media/js/firefox/welcome/welcome15-experiment.es6.js, media/js/firefox/whatsnew/whatsnew-119-experiment-eu.es6.js, media/js/firefox/whatsnew/whatsnew-119-experiment-na.es6.js, media/js/glean/utils.es6.js, media/js/products/vpn/landing-experiment-headlines.es6.js, package-lock.json, package.json, tests/unit/spec/base/core-datalayer-page-id.js, tests/unit/spec/base/fxa-attribution.js, tests/unit/spec/base/stub-attribution.js, tests/unit/spec/glean/utils.js
- Bumps Traffic Cop to v3.0.0 (which removes use of cookies).
- Removes bedrock code that would try to read the TC custom referrer cookie (we can revisit this in the future to add back to bedrock if we find we need it).
- Removes redundant `id` and `cookieExpires` properties from TC experiment configs.
#14086
First run `make preflight`.
The following URLs should still redirect to a variation as normal:
The main difference is that each time you hit one of the original URLs above, you may get redirected to a different version than before (since we no longer set a cookie to remember).
=> Bump Traffic Cop to v3.0.0 (Fixes #14086)

tests/functional/products/test_landing.py, tests/pages/products/landing.py
The products page was updated in #14407 and removed the menu lists, but functional tests were still expecting them. This removes those redundant tests.
`py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/products/test_landing.py`
=> Remove redundant product landing tests [#14220]

bedrock/firefox/templates/firefox/browsers/best-browser.html, bedrock/firefox/templates/firefox/privacy/book.html, bedrock/firefox/templates/firefox/privacy/passwords.html, bedrock/firefox/templates/firefox/privacy/products.html, bedrock/firefox/templates/firefox/welcome/page1.html, bedrock/firefox/templates/firefox/welcome/page7.html, bedrock/firefox/templates/firefox/welcome/page8.html, bedrock/mozorg/templates/mozorg/account.html, bedrock/newsletter/templates/newsletter/updated.html, l10n/en/brands.ftl, l10n/en/firefox/accounts.ftl, l10n/en/firefox/browsers/best-browser.ftl, l10n/en/firefox/new/desktop.ftl, l10n/en/firefox/privacy-hub.ftl, l10n/en/firefox/privacy/book.ftl, l10n/en/firefox/privacy/passwords.ftl, l10n/en/firefox/welcome/page1.ftl, l10n/en/firefox/welcome/page7.ftl, l10n/en/firefox/welcome/page8.ftl, l10n/en/mozorg/newsletters.ftl, l10n/en/navigation.ftl
Removed the conditional since Mozilla Monitor has been out for quite some time now, and it's time to retire any of the old and obsolete Firefox Monitor strings and references.
Sibling PR for switch: https://github.com/mozmeao/www-config/pull/560
Fixes https://github.com/mozilla/bedrock/issues/14492
Supersedes https://github.com/mozilla/bedrock/pull/14493
=> Remove mozilla_monitor conditionals (Fixes #14493)

media/js/base/fxa-attribution.es6.js, media/js/base/fxa-bundle-init.es6.js, media/js/base/fxa-coupon.es6.js, media/js/base/fxa-form.es6.js, media/js/base/fxa-link.es6.js, tests/unit/spec/base/fxa-attribution.js, tests/unit/spec/base/fxa-coupon.js, tests/unit/spec/base/fxa-form.js
This PR makes some changes to our FxA / VPN JavaScript code to separate out functionality from non-essential code.
- The coupon passing code is now split out from `fxa-attribution.es6.js` to it's own file called `fxa-coupon.es6.js`, so that the attribution code can be called separately and only when needed.
- A `skipAttribution` parameter has been added to `fxa-form.es6.js`. I found this was the easiest path as separating out the Firefox Sync and UITour functionality would require a considerable refactor of what's there.
#14488
This PR doesn't actually change any behavior in our code for now (that will come later).  For now, it's probably sufficient to test to make sure things continue to work as they do currently in prod:
URL: http://localhost:8000/en-US/products/vpn/?utm_source=test&utm_ …
=> Enable FxA attribution to be optional (Fixes #14488)

bedrock/products/templates/products/landing.html
Turn down the volume on /products buttons just a little.
N/A
http://localhost:8000/en-US/products/
=> Change CTA buttons on /products to use secondary theme styling

bedrock/firefox/templates/firefox/features/translate.html, bedrock/firefox/views.py, media/css/firefox/features/article.scss
Updates the list of supported languages on /firefox/features/translate/. Also reformats the list into columns since it's getting long, and sorts them alphabetically (in English at least) since I'm not sure what order they even were originally, it seemed pretty random.
#14548 
http://localhost:8000/firefox/features/translate/
=> Update Firefox Translation supported languages [fix #14548]

bedrock/products/templates/products/landing.html, l10n/en/firefox/products.ftl
The original string was changed without a new ID (adding `Made by Mozilla`). This is restoring the previous version of the message, and adding a new one with the updated text.
CC @alexgibson
=> Fix string change without new ID in products.ftl

bedrock/security/templates/security/bug-bounty/faq-webapp.html, bedrock/security/templates/security/bug-bounty/web-eligible-sites.html, bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html, bedrock/security/templates/security/web-bug-bounty.html
HackerOne updated the program to a single program under the name `mozilla`. 
- Identical to existing [PR from Frida](https://github.com/fkiriakos07/bedrock/tree/fix-hackerone-links). The links were invalid at the time, but the program has been updated by HackerOne.
=> Fix HackerOne URLs

bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py
Nimbus tooling is going to ride the beta train for another cycle so we need to extend the WNP for the next version. I kept it simple and didn't duplicate or rename the files, just expanded the view condition and added more tests.
#14435 
http://localhost:8000/en-US/firefox/127.0beta/whatsnew/
http://localhost:8000/en-CA/firefox/127.0beta/whatsnew/
http://localhost:8000/en-GB/firefox/127.0beta/whatsnew/
http://localhost:8000/fr/firefox/127.0beta/whatsnew/
http://localhost:8000/de/firefox/127.0beta/whatsnew/
=> Extend 126beta WNP to 127beta [fix #14435]

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-eu.html
The PDFs for DE, ES and PL needed some corrections but they were already cached by the CDN. So renaming the files will bust the cache, and all of them got renamed for consistency.
#14512 
http://localhost:8000/de/firefox/126.0/whatsnew/
http://localhost:8000/es-ES/firefox/126.0/whatsnew/
http://localhost:8000/pl/firefox/126.0/whatsnew/
http://localhost:8000/fr/firefox/126.0/whatsnew/
http://localhost:8000/it/firefox/126.0/whatsnew/
http://localhost:8000/en-GB/firefox/126.0/whatsnew/
=> Rename PDFs for EU WNP126 [#14512]

bedrock/mozorg/redirects.py, bedrock/mozorg/tests/test_views.py
* Drop duplicated redirect for Paris space
* Fix redirect when /diversity lacks a trailing slash; expand tests for diversity and webvision redirects
=> Hotfix broken redirects

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-eu.html
A friend reported this typo: `di’` is the imperative form, so it needs an apostrophe, not an accent.
=> Fix typo in Italian WNP126 page

bedrock/firefox/templates/firefox/features/private-browsing.html, l10n/en/firefox/features/private-browsing-2023.ftl
Copy fix, as suggested in the issue #14579
Now looks like:
Resolves #14579
* Visit http://localhost:8000/en-US/firefox/features/private-browsing/
=> Copy fix for private browsing

bedrock/releasenotes/migrations/0001_initial.py, bedrock/releasenotes/models.py, bedrock/releasenotes/tests/test_base.py, bedrock/releasenotes/tests/test_models.py, bedrock/releasenotes/views.py
... to a simpler JSONField so we can loaddata into it
This is precursor work to moving to sqlite while retaining an export-to-sqlite route.
Editing the migration seems OK, given NotesField was a subclass of JSONField with no schema-related changes.
Resolves #14574
=> Move ReleaseNotes.notes from being a custom NotesField

docs/install.rst
Removes outdated Puppeteer info and adds note to uncheck Rosetta emulation.
#14588
=> Update install docs with note to uncheck Rosetta emulation on macOS using Docker (Fixes #14588)

package.json
Fixes an error where assets generated by Glean's build process were missing when running `make run` with a fresh install.
#14587
1. Delete untracked files from `./media/js/libs/glean/`
2. Run `make clean pull build run`
=> Fix Glean error when running make run with Docker (Fixes #14587)

docs/index.rst, docs/legal-docs.rst
Add some docs for the privacy notice templates.
- added file
- added link to file
This is to help with #14233
`make livedocs` in your venv
=> Add some docs for the privacy notice templates #14233

bedrock/base/management/commands/check_email_deliverability.py, bedrock/base/tests/test_commands.py, bedrock/legal/views.py, bedrock/mozorg/views.py, bedrock/press/views.py, bedrock/settings/base.py
If we set an env var `EMAIL_DELIVERABILITY_TEST_ADDRESS` to be the address of a dedicated snitch in Dead Man's Snitch (https://deadmanssnitch.com/snitches/2995da2cd9/setup) and then run this management command via a k8s cron job, in production only, we will be able to be alerted if email deliverability is affected.
There will be a corresponding infra PR that uses this management command.
It was kept out of cron.py for simplicity in controlling exactly where it is triggered.
I used Copilot to generate the base of the tests, but then tuned them by hand (to make them appropriate, not just to make them work)
Resolves #14566 
Related PR in infra that needs to be merged **after** this https://github.com/mozilla-it/webservices-infra/pull/2062
Locally, with `DEBUG=True` try:
* …
=> Add a management command that will send an email to check deliverability

bedrock/mozorg/templates/mozorg/home/home-new.html, bedrock/mozorg/templates/mozorg/home/includes/mofo-donate-promo.html, l10n/en/mozorg/home-new.ftl
Fixes "Protect**~~r~~**" typo that hasn't been published yet (incl. l10n) — the rest is just whitespace/formatting.
> ![Screen Shot 2024-05-25 at 14 52 36](https://github.com/mozilla-l10n/www-l10n/assets/1784648/d0f21ec7-ccf2-4d51-992f-7e621521a9ec)
1. The downstream PR raised QA around dashes/typography https://github.com/mozilla-l10n/www-l10n/pull/404#pullrequestreview-2077285981 so I might include any result of the discussions here too.
2. There's also new menu items ftl content not used in the output eventually https://github.com/mozilla-l10n/www-l10n/pull/404#pullrequestreview-2079294790 so this can also get cleaned up here with the rest.
https://github.com/mozilla-l10n/www-l10n/pull/404#pullrequestreview-2078964607
=> Fix new home ftl typo

.github/workflows/routine_l10n_obsolete.yml
Adds `--author` arg to `gh issue list` cli filter to pinpoint only the past l10n cleanup issue generated by the :octocat: **github-actions[bot]** itself.
- Adds a link to search results to give an idea how much obsolete ftl strings there are.
- Prefixes the issue title with "[bot] …" for better recognition it's created by automation.
- Improves some of the labels to match other workflows conventions.
Fix #14571
[actions/runs/9263192494/job/25481213414](https://github.com/janbrasna/gha-test-gh-issue-cli-cron/actions/runs/9263192494/job/25481213414) over [these](https://github.com/janbrasna/gha-test-gh-issue-cli-cron/issues)
=> Close only bot issues from github-actions by l10n cron job

l10n/en/navigation_v2.ftl
These Fluent strings were leftover from the recent homepage updates, and it was decided that they wouldn't be part of the navigation for now, so we're removing them from the fluent file.
https://github.com/mozilla-l10n/www-l10n/pull/404?notification_referrer_id=NT_kwDOAoWVorQxMDc5NzY1Nzg0Mzo0MjMwOTAyNg#discussion_r1614972205
=> Remove Moz AI and Moz VC Fluent strings from navigation

bedrock/mozorg/templates/mozorg/about/governance/policies/security/bugs.html
Moves from old .html link to current url() page to save one 302 redirect.
I _believe_ this is not generated from outside source or at least the URLs are set here so this is safe to update just here.
_this Is older than where I can see in git history;)_
http://localhost:8000/en-US/about/governance/policies/security-group/bugs/#disclosure
=> Update security bugs policy known issues URL

bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py, bedrock/settings/base.py
Not used since #14561 as all footer "Press" links now point to main EN blog only.
This doesn't seem to be coming back anytime soon, and if so it can always be exhumed from git history.
Closes #14550
`make test` and coverage seem happy
=> Remove press_blog_url helper

media/css/firefox/browsers/chromebook.scss
This PR fixes the issue that the Chromebook dropdown gets cut off.
https://github.com/mozilla/bedrock/issues/14491
1. Checkout this PR
2. Go to http://localhost:8000/en-US//firefox/browsers/chromebook/
3. The dropdown should no long be cut off
4. Review other styles on the page remain the same
=> fix the dropdown cutoff issue

bedrock/admin/templates/admin/base_site.html, bedrock/cms/wagtail_hooks.py
Adds links to the Django Admin and Wagtail Admin that make it easier to move between them.
Wagtail menu links are only visible by superusers/admins, which will be the minority of the 
Django admin top bar
-----
Wagtail menu bar (links are only visible to admins/superusers)
Resolves #14650
=> 14650 Add links to move around admins

bedrock/settings/base.py
Wagtail ships with jinja2 support for the floating context menu on rendered pages, but with the `django_jinja` template engine in use (which is what we have), it appears to not work. Living without it right now is not a big cost, so just tidying up config rather than confuse ourselves
=> Disable the Wagtail Userbar extension for jinja

media/js/base/sentry-consent.es6.js, package-lock.json, package.json, webpack.config.js
Updates Sentry JS client to v8.8.0
N/A
Set `SENTRY_FRONTEND_DSN=https://c3ab8514873549d5b3785ebc7fb83c80@o1069899.ingest.sentry.io/6260331` in your `.env` to test locally.
Requires a browser with DNT/GPC disabled.
=> Update Sentry JS client to v8.8.0

bedrock/base/tests/test_migrations.py
...so that we catch them at PR level, before the root-cause changes get merged
Resolves #14665
* Remember to revert/discard your change to the `BedrockRendition` model
=> Add a unit test to detect missing migrations,

bedrock/settings/base.py
=> Fix settings syntax for adjusting storage backend when GCS config is available

bedrock/base/middleware.py, bedrock/base/tests/test_middleware.py, bedrock/settings/__init__.py, bedrock/settings/base.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
Resolves https://github.com/mozilla/bedrock/issues/14576
This shifts our current install of django-csp to the as yet un-released changes on the main branch, which is a big django-csp refactor that required settings changes.
This PR adds a new middleware, `CSPMiddlewareByPathPrefix`, that allows overriding the default CSP if a path prefix matches the current request path.
The setting for this looks like the following:
```python
CSP_PATH_OVERRIDES={
"/override/path": {
"DIRECTIVES": {
"default-src": ["override.com"]
}
}
}
```
=> Add ability to override CSP based on path prefix

bedrock/settings/__init__.py
This removes a couple old sources from our CSP directives. The `iframe`s were removed in commits in 2019:
* 86fe12e0c10226afeeec5647d5edff7964dfd952
* 7680a3b5cd30ff39e8b602eecb5894b2499eeccc
=> Remove old sources from CSP

media/js/base/sentry-consent.es6.js
Filters out some non-useful / non-actionable JS errors in Sentry to cut down on noise.
#14674
Set `SENTRY_FRONTEND_DSN=https://c3ab8514873549d5b3785ebc7fb83c80@o1069899.ingest.sentry.io/6260331` in your `.env` to test locally.
Requires a browser with DNT/GPC disabled.
=> Filter out non-useful events in Sentry (Fixes #14674)

.github/workflows/pull_request_tests.yml
Turns out Firefox is already preinstalled on the `ubuntu-latest` image, so no need to download the snap version
N/A
=> Run JS tests in CI using ubuntu-latest

bedrock/mozorg/templates/mozorg/includes/mozilla-account-cta-promo.html, bedrock/mozorg/templates/mozorg/includes/mozilla-account-form-promo.html, l10n/en/mozilla-account-promo.ftl
Improves a recently added copy with the word _"joining"_ from an older occurence:
> "Already have an account? [Sign in](#) or [learn more](#) about **_joining_** Mozilla"
- Makes the call-to-action text consistent with an older occurrence elsewhere.
- (The string in this form is already present and localised, so chances are it would be pulled up from [translation memory](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/ui.html#machinery).)
- Avoids changing this in `whatsnew/122` that's currently being removed.
Resolves #14460 
/en-US/firefox/browsers/mobile/ (bottom: form)
/en-US/firefox/ (bottom: cta)
=> Update Mozilla account CTA wording

bedrock/base/templates/403_csrf.html
For the Web deployment, we don't run session or authentication middleware (because it's stateless) so the custom 403 page that alerts to an expired SSO session will blow up (and has done when we've had bots spamming relevant forms)
Next best check is to show the extra message only on the Editing deployment, which is where SSO is used. The settings object is already in the page context via bedrock.base.context_processors.globals
=> Change custom 403 page to not 500

bedrock/base/cache.py, bedrock/base/tests/test_simple_dict_cache.py, bedrock/settings/__init__.py
This is so we can investigate out-of-memory restarts and possibly tune these caches a bit.
=> Add metrics to SimpleDictCache

bedrock/mozorg/templates/mozorg/about/leadership/includes/boards.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
This PR adds alt text for images on leadership page
https://github.com/mozilla/bedrock/issues/14671
=> add alt text for images on leadership page

l10n/en/brands.ftl
Reorders `brands.ftl` strings according to current product families and past EOLs.
This has no intention to remove or mark strings as obsolete, as e.g. the legacy brand names are being referred to from archived privacy pages or historic fxa pages or newsletter templates (they may or may not be used nowadays, but they are currently present nonetheless).
The change has no impact, only moves around the IDs/strings to better show current relations to the individual blocks and tangentially also cleans up actively supported products vs. removed content only for legacy purposes.
🚫🐞
_by checking all the IDs are still present_
=> Update brands.ftl grouping

lib/l10n_utils/fluent.py
Only fall back to a fallback string if it's actually translated.
When both current and fallback strings are untranslated in given locale, an English/default string gets used — but this should prefer the current default over the fallback default, as both are default English anyways, so having a current English is at least a bit better.
Fixes #14461 
_(compare with current prod:)_
http://localhost:8000/de/firefox/#fxa-email-form (de:v1)
http://localhost:8000/da/firefox/#fxa-email-form  (da:v1)
http://localhost:8000/be/firefox/#fxa-email-form  (en:v2)
http://localhost:8000/nn-NO/firefox/#fxa-email-form (en:v2)
http://localhost:8000/pt-PT/firefox/#fxa-email-form (pt:v2)
but no locale should show v1 string in default en, only v2 en or v1 in the language…
=> Fix untranslated fallback strings

bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/firefox/views.py, media/js/firefox/new/desktop/thanks-smoke-test.es6.js, media/static-bundles.json
Adds A/A experiment to `/firefox/new/` page for smoke testing.
Targeting:
- `/en-US/` locale only
- US `country_code` only.
- Windows 10 / 11.
- Edge browser.
- 10% of targeted traffic for each variation.
#14696
Test using browser stack running Windows 10/11 using Edge. You might need to refresh a few times before you hit one of the redirects. Both variations are identical (no changes) since this is a smoke test.
https://www-demo1.allizom.org/en-US/firefox/new/?geo=us
=> Firefox download to install smoke test (Fixes #14696)

Dockerfile
Bumps Node to a more recent 20.x image to satisfy some warnings building dependencies.
#14705
- `make build`
- `make run`
=> Bump node Docker image to 20.14.0-slim (Fixes #14705)

bin/run-db-update.sh
Still does the job - no need to reinvent the wheel.
Will be called from a CronJob in k8s - see https://github.com/mozilla-it/webservices-infra/pull/2215
When all merged, resolves #14715
=> Minor tidying of DB-updater script ahead of use from CMS DB updatery

bedrock/base/tests/test_i18n.py
Fixes test that can be broken if DEV=True in local env
* Try DEV=True and then False in yuor env, running `pytest -k test_i18n.py` each time
=> Ensure test stability regardless of local .env settings for DEV env var

bedrock/base/tests/test_settings.py, bedrock/settings/base.py
TLDR: We just need the root URL of the CDN, from `settings.MEDIA_URL`.
Longer form: 
`settings.MEDIA_URL` is a custom route on our CDN that points to a cloud bucket, which we use for uploaded media from the CMS.
Specifically, due to infra constraints, it has to point to a _sub-path_ in the bucket, not the top/root of it. 
It also needs to be distinct from the CDN route that points to our collected static assets (which are at `https://<CDN_HOSTNAME>/media/` - that is `settings.STATIC_URL` in production)
With all this in mind, `settings.MEDIA_URL`, when set, points to `https://<CDN_HOSTNAME>/media/cms/` 
However, when `django-storages` computes the URL for a object in that CMS bucket, it wants just the hostname of the bucket, not the full CDN/proxy path to the subdir in the bucket, because …
=> Add helper to get only the hostname out of MEDIA_URL

bedrock/base/templates/cron-health-check.html, bedrock/base/views.py
Bedrock will continue to operate with sqlite for local dev, demos and bedrock-test, but otherwise will use postgres as its DB backend.
As such, some of the info on the healthz-cron page will be misleading if postgres is in use, because it's focused on sqlite.
This changeset hides the sqlite-specific data if sqlite is not in use. It also adds a new timestamp that shows the most recent timestamp of all data sources that have been pulled in, as a rough way for us to quickly see that the run-db-update job is still working. (There's also a Dead Man's Snitch watching the relevant job, but this adds a convenient quick look)
Resolves #14734
With sqlite in use - very similar to current Bedrock
With Postgres in use instead
=> Update healthz-cron page re postgres backend

bedrock/base/middleware.py, bedrock/base/tests/test_middleware.py, bedrock/settings/__init__.py
`REPORT_ONLY` no longer lives in the settings dict. This aligns our override middleware with how django-csp works by adding a 2nd override for report-only and updates the middleware to match.
=> Align CSP override middleware's report-only with django-csp

bedrock/settings/__init__.py
Wagtail uploaded images show the image preview using a `blob`. This adds a custom CSP just for the wagtail admin to view these.
This will need to match the request path that loads the image preview, not the source of the image preview. So this needs testing on our wagtail dev or demo site to ensure the path is correct.
#14733
=> Fix #14733: Add custom CSP for wagtail image uploads

docker/bin/build_staticfiles.sh
…
To test this, I did `make build prod` to build a new release image, locally, then shelled in:
```
$ pwd
/app
$ ls static/admin/css
autocomplete.4a81fc4242d0.css  dark_mode.ef27a31af300.css  nav_sidebar.269a1bd44627.css     rtl.css
autocomplete.css               dashboard.css               nav_sidebar.css                  vendor
base.523eb49842a7.css          dashboard.e90f2068217b.css  responsive.css                   widgets.css
base.css                       forms.c14e1cb06392.css      responsive.f6533dab034d.css      widgets.ee33ab26c7c2.css
changelists.9237a1ac391b.css   forms.css                   responsive_rtl.7d1130848605.css
changelists.css                login.586129c60a93.css      responsive_rtl.css
dark_mode.css                  login.css …
```
=> Ensure Docker builds include any CSS needed when the CMS Admin mode is active, too

docs/testing.rst
Adds a temporary note to the docs about Playwright migration
N/A
- `pip install -r requirements/docs.txt`
=> Add note to testing docs about Playwright

bin/run-prod.sh
Now that Bedrock Dev does not use a sqlite DB because it's on postgres, we're performance tuning and are trying to avoid having a k8s initContainer to copy down the DB before bootup: https://github.com/mozilla-it/webservices-infra/pull/2281 
This also means Bedrock needs to NOT look for that DB file when there's a DATABASE_URL defined
=> Allow Bedrock to boot in prod mode if there is no sqlite DB, but only if DATABASE_URL is defined

bedrock/products/templates/products/vpn/download.html, bedrock/products/templates/products/vpn/landing.html
Bumps system requirements for Mozilla VPN to iOS 14.0 and macOS 11.0 and up.
#14727
- http://localhost:8000/en-US/products/vpn/download/
- http://localhost:8000/en-US/products/vpn/?xv=legacy (see FAQ at bottom of page)
=> Bump VPN client system requirements for macOS and iOS (Fixes #14727)

bedrock/firefox/tests/test_views.py, bedrock/firefox/views.py, docs/attribution/0002-firefox-desktop.rst, media/js/base/stub-attribution/stub-attribution.js, tests/unit/spec/base/stub-attribution/stub-attribution.js
Removes `client_id` from stub attribution data since UA is now turned off in production.
#14406
Using a browsers with DNT/GPC disabled:
1. Open https://www-demo3.allizom.org/en-US/firefox/new/?geo=us
2. Open Dev Tools -> Application tab -> Cookies
3. Find www-demo3 and the `moz-stub-attribution-code` cookie.
4. Copy the cookie value to clipboard.
5. Run the following command in your terminal:
```
echo -n 'PASTE_COOKIE_VALUE_HERE' | base64 --decode
```
=> Remove UA client ID from stub attribution data (Fixes #14406)

bin/run-worker.sh, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
Sentry 2.x had some backwards incompatible changes. See the [migration guide](https://docs.sentry.io/platforms/python/migration/1.x-to-2.x)
We didn't end up using anything that changed so there aren't many changes here.
I did notice we need to pass the `--sentry-dsn` to the RQ worker for it to get picked up, so I added that.
=> Upgrade to sentry-sdk 2.x

Makefile, bedrock/cms/management/commands/bootstrap_local_admin.py, bedrock/cms/tests/test_commands.py
If using sqlite locally, when `make preflight` runs, it will replace your local DB.
This changeset at least bootstraps a new admin user for you, even if any local CMS pages will have been lost
Resolves #14798
1. Set `WAGTAIL_ADMIN_EMAIL=youremailhere` in your `.env`
2a. `make preflight` (if you can live with your DB being blasted away) 
2b. `./manage.py bootstrap_local_admin` just to run the new command
=> Support bootstrapping a Django/Wagtail admin user as part of `make preflight`

media/js/base/site.js, tests/unit/spec/base/site.js, tests/unit/spec/firefox/new/common/thanks.js
We no longer actively use this code since https://github.com/mozilla/bedrock/issues/14012 was completed, so we can remove these functions from site.js.
#14404
=> Remove archType and isARM() from site.js (Fixes #14404)

bedrock/mozorg/templates/mozorg/about-base.html
Updates the _"Learn more"_ link in _"Our Products"_ sidebar for all _About_ pages to link to the new `products.landing`.
This was still the old location before `/firefox/browsers` moved to `/firefox` and the new `/products` was created for listing all of it.
#14222
http://localhost:8000/mission/
=> Update About "Our Products" sidebar link

.github/workflows/routine_l10n_obsolete.yml
Updates the l10n cron to add "Frontend" label as well (+unrelated wording update)
ATTN: For the current issue to get closed, it needs to have the "Frontend" tag added too, manually now, as this action uses the tag definition both to open new, but also list the old issue for closing. So for it to work on the currently opened issue ~2months from now, it will only close it if it has both of the labels at that point.
#14571
[runs/9927407215/job/27422314530#step:2:1](https://github.com/janbrasna/gha-cli-cron-test/actions/runs/9927407215/job/27422314530#step:2:1)
=> Update l10n automation tags and wording

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
Wagtail 6 gives us better list-based management of some DB-backed data, which will be very handy for managing translation jobs with `wagtail-localize-smartling`, so upgrading is now essential.
Note that 6.2 LTS is due on 1 August 2024 anyway.
=> Upgrade Wagtail to 6.1.x

bedrock/base/middleware.py, bedrock/base/tests/test_middleware.py, bedrock/settings/__init__.py, bin/qa/check_csp_report.py, gcp/bedrock-demos/cloudrun/mozorg-demo.env.yaml
This changeset adds support for including a CSP report-uri in a certain percentage of pages, so that we can get an idea of whether pages have inappropriate CSP set, but without saturating our logging service, Sentry.
NB: the relevant config to enable this on Dev, Stage and Prod will be in a separate PR, and that work needs to be merged to make this changeset do anything.
Resolve #14451 
I've added a script called `./bin/qa/check_csp_report.py` which we can use to check the proportion of headers being set, either locally or on an actual server.
E.g. with `CSP_REPORT_PERCENTAGE=50`
```
$ ./bin/check_csp_report.py -n 100 http://localhost:8000/en-US/firefox/
Checking http://localhost:8000/en-US/firefox/
100 requests made
defaultdict(<class 'int'>, {'report-uri not present': 51, 'report-uri …
```
=> Support configurable CSP reporting percentage

bedrock/mozorg/views.py, bedrock/settings/__init__.py
This sets the CSP directive `frame-ancestors 'none'` which indicates that we do not want any part of our website used in a frame. This takes precedence over the `X-Frame-Options: DENY` header for browsers that support both. For now we are leaving both in for broad browser support.
#14835 
It's possible to throw an `iframe` on a page whose `src` is another page in bedrock and verify the browser throws a CSP error.
I put one on the mission page:
```
<iframe src="/en-US/about/manifesto/"></iframe>
```
Which produced this error:
```
Content-Security-Policy: The page’s settings blocked the loading of a resource (frame-ancestors) at http://localhost:8000/en-US/mission/ because it violates the following directive: “frame-ancestors 'none'”
```
=> Use `frame-ancestors` for clickjacking control

bedrock/base/i18n.py, bedrock/cms/decorators.py, bedrock/cms/models/pages.py, bedrock/cms/tests/conftest.py, bedrock/cms/tests/decorator_test_views.py, bedrock/cms/tests/test_decorators.py, bedrock/cms/tests/test_models.py, docs/cms.rst
This changeset adds a new decorator (`@prefer_cms`) that we can use to transition from hard-coded Django views to CMS-backed replacement views without having to delete the Django view in order to reveal the CMS page. 
It will try to see if Wagtail can find a live CMS page for the URL path that matches the current Django view's path, and if so, will return that instead. If not, it will let the regular Django view run.
This means that, when someone wants to publish a CMS page to replace a Django view, we don't have to coordinate a code release to remove the Django view and let Wagtail serve the new page instead - it will just hand over gracefully and we can remove the deprecated Django view in a later changeset.
See the updates to `cms.rst` for a fuller explanation
There's no current use of …
=> Add prefer_cms decorator to help with migrating pages from hard-coded to CMS

docs/cms.rst
Adds some initial docs for creating new pages in Wagtail. This does not yet cover things like editing existing pages, or migrating existing Jinja pages.
#14797
=> Add docs for creating new page models in Wagtail (Fixes #14797)

bedrock/cms/management/commands/run_smartling_sync.py, bedrock/settings/base.py, docs/cms.rst, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This changeset drops in wagtail-localize-smartling, which will flow strings from Wagtail to Smartling for L10N and then back again. 
0.2.3 is an early-ish, Minimum Lovable Product version, and there may well be some fast-follow changes from the vendor - those are in discussion at the mo, and we can pick up anything else we want, as it's "our" codebase now.
I've tested it manually, locally, for now, with sandbox-y API keys and it works for the core cases. There are some rough edges but we'll sort them out.
The infra PR needed to accompany these changes will need to:
1) Set the appropriate env vars [as documented](https://github.com/mozilla/wagtail-localize-smartling?tab=readme-ov-file#installation)
2) Set a cron job that runs ./manage.py sync_smartling every X minutes (15?). Doing it as a …
=> Add wagtail-localize-smartling to the project, for Smartling L10N support

.pre-commit-config.yaml
This changeset adds protection against untracked, unapplied or absent Django Migrations, which could cause us some awkward fixups if a PR lacking the right Migration(s) was merged to main and then its migrations run on the DB.
It uses a mozmeao-homed fork of some third-party pre-commit hooks.
It does add ~2s to the runtime of the pre-commit hooks, but it's worth it, I think.
Solves part of #14859 
You can edit a django model (eg change a field) and try to commit it. 
Here's one I made earlier:
=> Add pre-commit hooks to check for untracked, unapplied or absent DB migrations

bedrock/cms/models/base.py, bedrock/cms/tests/test_models.py, bedrock/settings/base.py, docs/cms.rst
This means we can control when a page is available for use in the CMS, versus simply being in the codebase. Also, note that removing a particular page class from this allowlist will not break existing pages that are of that class, but will stop anyone adding a _new_ one.
NB: EVERY TIME we add a new Wagtail Page subclass to the CMS, we must add to the CMS_ALLOWED_PAGE_MODELS setting if we want it to be selectable as a new child page in Production (or ticket up when we do want to add it to the setting)
Resolves #14843 
Locally:
1. Have some pages in your CMS
2. Edit `bedrock.settings.base._allowed_page_models` to comment out one of the two page types there. 
3. Set `DEV=False` in your .env and ensure runserver has been restarted
4. Confirm you can't add that page type as a child page
5. Set …
=> Add support for controlling which CMS Page types can be used in the site

Makefile, bin/integration_tests/run_integration_tests.sh, bin/run-integration-tests.sh, docs/install.rst, docs/redirects.rst, docs/testing.rst
#14851
(`docker-compose run test`) `pytest bedrock/firefox`
is the same as
(`docker-compose run test`) `py.test bedrock/firefox`
also
```sh
mkdir test_infra
mkdir test_infra/fixtures
make test_infra/fixtures/tls.json
make test-cdn  
```
but I'm prolly missing some secret sauce here to run it successfully…:/
=> Update pytest entrypoints

docs/attribution/0007-consent-management.rst, media/js/base/consent/init.es6.js, media/js/base/consent/utils.es6.js, tests/unit/spec/base/consent/consent-utils.js
Adds an optional query parameter that can be used to trigger the consent banner on any URL when viewed in the EU.
#14853
> [!NOTE]
> You'll need to test in a browser with DNT / GPC disabled. On localhost, you'll also need to mock being in an EU country via the `geo` param.
http://localhost:8000/en-US/?geo=gb&mozcb=y
=> Add URL query param to show consent banner in the EU (Fixes #14853)

bedrock/careers/templates/careers/position.html
Request from legal. This updates the link to point to a public Google doc rather than a PDF.
#14875 
http://localhost:8000/careers/listings/ and choose any open position (this will depend on your local data so I can't link directly to a job). The Applicant Privacy Notice link is at the bottom of the page under the Apply Now dropdown.
=> Update applicant privacy notice on job postings [fix #14875]

bedrock/firefox/templates/firefox/nothing-personal/index.html, media/css/firefox/nothing-personal/_animations.scss, media/css/firefox/nothing-personal/_browser.scss, media/css/firefox/nothing-personal/_primary-cta.scss, media/css/firefox/nothing-personal/_sticky-note.scss, media/css/firefox/nothing-personal/styles.scss
Various fixes and changes requested by studio.
* Browser window title alignment - On mobile the titles of the 'browser windows' should align left with space for the dots, and align center on desktop.
* Desktop icon hover styles - Change the hover/focus styles of the mock icons so they more closely mimic desktop icons (and make the easter eggs harder to discover)/
* Open links in new tabs
* fix #14877 - the sticky note slides in smoother
* fix #14878 - the main CTA in the header should default to "learn more" in Firefox if UITour fails to detect default state.
#14877
#14878
=> Fixes for Nothing Personal page [#14824]

bedrock/newsletter/templates/newsletter/knowledge-is-power-confirm.html, bedrock/newsletter/tests/test_views.py, bedrock/newsletter/urls.py, bedrock/newsletter/views.py, media/css/newsletter/newsletter-knowledge-is-power-confirm.scss, media/js/newsletter/confirm-init.es6.js, media/js/newsletter/confirm.es6.js, media/js/newsletter/form-utils.es6.js, media/static-bundles.json, tests/unit/spec/newsletter/confirm.js
Adds newsletter confirmation page for Knowledge is Power (KiP).
#14823
First get your newsletter token by following these steps:
1. Open https://www.mozilla.org/en-US/newsletter/recovery/ and enter your email.
2. Find the recovery email, and click the link that opens the email preference center.
3. Open Dev Tools -> Storage -> Cookies and find the cookie called `nl-token`. Copy it's value (which should be a long alpha-numeric string).
4. Whilst you're here, make sure you are *not* subscribed to KiP (unsubscribe if you are).
Next, open the KIP confirmation page using your token in the URL:
1. Open: `http://localhost:8000/en-US/newsletter/knowledge-is-power/confirm/{INSERT_YOUR_TOKEN_HERE}`
2. When the page loads, click "Confirm".
If you see a "thank you" message then you should now be …
=> Add KIP newsletter confirmation page (Fixes #14823)

media/css/firefox/nothing-personal/_browser.scss
Aligns window titles to the right on mobile.
=> Nothing Personal page, right align window titles [#14824]

bedrock/firefox/templates/firefox/nothing-personal/index.html, media/css/firefox/nothing-personal/_sticky-note.scss, media/css/firefox/nothing-personal/styles.scss
- Added `data-link-text` attributes on anchor tags
- Fixed sticky note position 
Fixes https://github.com/mozilla/bedrock/issues
http://localhost:8000/en-US/firefox/nothing-personal/
=> Add data attributes and fix stickynote position on NP campaign page

bedrock/firefox/templates/firefox/developer/includes/features.html
Fixes fluent string reference for FX Dev page feature description that's repetitive.
The intended string was already included, just not linked.
Fixes #14609 (also closes #14610 as superseded)
http://localhost:8000/firefox/developer/#fordevs
=> Fix Firefox DevTools features duplicate string

media/js/base/sentry-consent.es6.js
The Glean folks took a look at this in [bug 1907022](https://bugzilla.mozilla.org/show_bug.cgi?id=1907022) and agree it's likely a non-actionable network side effect.
N/A
=> Ignore NS_ERROR_ABORT No error message alerts in Sentry front-end

media/js/base/sentry-consent.es6.js
Add an ignore filter for https://mozilla.sentry.io/share/issue/6361b063ea0d4528ac0ef07e181fbb96/
N/A
=> Ignore NS_ABORT_FAILURE error in Sentry JS

media/js/base/sentry-consent.es6.js
Fixes a regression from https://github.com/mozilla/bedrock/pull/14658 (which I think is why we stopped getting things like browser name and referrer in our front-end errors).
N/A
=> Fix error setting httpContextIntegration in Sentry JS

bedrock/firefox/templates/firefox/nothing-personal/index.html
Forgot to add `data-link-text` attributes to the anchor tags in the desktop icon easter eggs. Fixing that now.
Note that these easter eggs are only available on desktop, not mobile.
http://localhost:8000/en-US/firefox/nothing-personal/
=> Add data attributes to Nothing Personal easter egg URLs

.github/dependabot.yml
- Enable dependabot for `/tests/playwright/package.json`.
- Limit to 5 open pull requests per month.
- Group minor/patch updates into a single PR.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups for reference.
Note: I'm adding this as a test before doing it for the main bedrock front-end dependencies.
N/A
=> Enable dependabot for Playwright dependencies

bedrock/mozorg/templates/mozorg/home/home-old.html
Cleans up repeated include outside the switch statement.
#14941 
http://localhost:8000/sco/
=> Remove repeated banner include from legacy home page [fix #14941]

bedrock/firefox/redirects.py, bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
Adds a redirect from /nothingpersonal/ (or /nothing-personal/) to /firefox/nothing-personal/. This makes a URL easier to speak aloud in audio ads.
#14944 
http://localhost:8000/nothingpersonal should redirect to http://localhost:8000/firefox/nothing-personal/
=> Add vanity URL redirect for Nothing Personal page [fix #14944]

Makefile, bin/docker-compose.sh, bin/integration_tests/cleanup_after_functional_tests.sh, bin/integration_tests/docker_compose_for_integration_tests.yml, bin/integration_tests/functional_tests.sh, bin/upload-staticfiles.sh, docker/bin/postbuild.sh, docker/bin/run_tests.sh, docs/install.rst
This is because the ubuntu-latest GHA image no longer supports the V1 compose API, which was breaking our CI.
https://github.com/actions/runner-images/issues/9692
This is a wholesale change, to ensure consistent use of the v2 syntax
I pushed this to `run-integration-tests` and the fact it's running at all shows the change has helped, IMO https://github.com/mozilla/bedrock/actions/runs/10218032453 - please rerun any failed tests on that URL as they should all pass
=> Amend all usage of docker-compose to be docker compose

requirements/prod.txt
Reverts mozilla/bedrock#14959 because it didn't bump deps properly 
🤦 for the review slip by me
=> Revert "Bump django from 4.2.14 to 4.2.15 in /requirements"

bedrock/mozorg/templates/mozorg/impact-report/index.html, bedrock/mozorg/urls.py, bedrock/mozorg/views.py
Switches the /impact/ page to hide the main CTA behind a switch, rather than make past report links non-discoverable.
#14971
Set `SWITCH_IMPACT_REPORT_ACTIVE=False` in your `.env` to hide the main CTA.
http://localhost:8000/en-US/impact/
=> Fix 404 /impact/ page (Fixes #14971)

media/js/firefox/whatsnew/whatsnew-129-na.js
Same fix as we did for WNP 116: https://github.com/mozilla/bedrock/issues/13484
Note: this is a pesky bug as it's not reproducible on localhost. I pushed it to a demo below where the fix can be tested.
Make sure you have UITour enabled for demo1: https://bedrock.readthedocs.io/en/latest/uitour.html#local-development
#14975
https://www-demo1.allizom.org/en-US/firefox/129.0/whatsnew/
=> Fix disappearing reader mode icon on WNP 129 (Fixes #14975)

bedrock/firefox/templates/firefox/whatsnew/includes/mofo-donate-cta.html
Uses hard-coded donate CTA strings over Fluent content for NA+EU locales targeted by the custom WNPs.
This will make any changes the community made in Pontoon for _it, pl, es-ES_ "donate" buttons effectively not display in the current WNP content.
Resolves #14837
http://localhost:8000/it/firefox/128.0/whatsnew/
http://localhost:8000/pt-BR/firefox/88.0/whatsnew/
http://localhost:8000/en-US/firefox/128.0/whatsnew/
http://localhost:8000/en-GB/firefox/128.0/whatsnew/?v=1
=> Prefer supplied CTA content for WNP fundraiser buttons

tests/pages/firefox/welcome/page15.py
Some elements got changed around in https://github.com/mozilla/bedrock/pull/14964 and the button locator for the test was looking for a class that was no longer there, hence the test was failing because it couldn't find the button. This updates the locator so the test can pass again.
http://localhost:8000/firefox/welcome/15/
`pytest --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/firefox/welcome/test_welcome_page15.py`
=> Fix test for welcome 15

bedrock/firefox/templates/firefox/features/translate.html, bedrock/firefox/views.py
Updates the languages on the Firefox Translate feature page.
#14987 
http://localhost:8000/firefox/features/translate/
=> Update list of supported languages on translate feature page [fix #14987]

bedrock/firefox/views.py
Removes a country list definition used in long gone WNP 117 (#14227)
`make test`?
=> Remove WNP117 VPN country list

.github/workflows/a11y_tests.yml, .github/workflows/integration_tests.yml, .gitignore, bedrock/base/templates/macros.html, docs/testing.rst, tests/playwright/global-setup.js, tests/playwright/package-lock.json, tests/playwright/package.json, tests/playwright/playwright.config.js, tests/playwright/specs/a11y/components.spec.js, tests/playwright/specs/a11y/includes/helpers.js, tests/playwright/specs/a11y/includes/locators.js, tests/playwright/specs/a11y/includes/urls.js, tests/playwright/specs/a11y/pages.spec.js
Adds a new Playwright a11y test suite, powered via [Axe Core](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/README.md).
These initial tests are against a small-ish set of our key, most high-traffic pages. The test runs will fail for now and that's fine. They will not block deployments, and will instead run once per-day against www-dev and report via Slack. We can expand the number of pages this test suite covers as we work through issues it identifies.
#14773
- `cd tests/playwright && npm ci && npm run install-deps`
- `npm run a11y-tests`
Once the test run completes, it should fail (which is expected).
The resulting failures will be captured as HTML reports and saved in `./tests/playwright/test-reports-a11y/`. You can open these files in your browser and read …
=> Add a11y test job running against key pages (#14773)

bedrock/newsletter/tests/test_views.py, bedrock/newsletter/urls.py, bedrock/newsletter/views.py
I noticed our UUID regex was inconsistently used, so I decided to update URLs to use `uuid` path converter. Also a few updates around when the token is optional and using `urlparams` for cleaner URL concatenation.
=> Update URLs to use `uuid` path converter

bedrock/sitemaps/utils.py
Stop excluding /zh-CN/ route from sitemap because it is no longer redirected
Resolves https://github.com/mozmeao/www-sitemap-generator/issues/10
=> No longer exclude root page for zh-CN route

bedrock/products/templates/products/landing.html
Updates product headings to `<h2>`
#15002
http://localhost:8000/en-US/products/
=> Fix heading levels on /products/ page (Fixes #15002)

bedrock/mozorg/templates/mozorg/about/index.html
Adds a `<main>` landmark to the /about/ page and fixes level heading issue.
#15001
=> Fix landmark and heading levels on /about/ page (Fixes #15001)

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py, tests/redirects/map_htaccess.py
Removes broken redirects, updates bunch of others.
1. Removes specific redirects leading to MDN 404s and leaves that all to more generic archived content. (Some would still 404 even in the archive (correct url, probably bug in archiving), but less rules here anyways.)
2. Updates more broken MDN links to W3C instead 
3. Redirects archived extensions to gh repo
4. Updates redirects to dead hosts
🚫🐞
http://localhost:8000/editor/midasdemo/securityprefs.html
http://localhost:8000/editor/midasdemo/securityprefs.html%3C/span%3E%3C/a%3E%C2%A0 (this one is in a test;))
http://localhost:8000/about/get-involved
http://localhost:8000/about/participate
http://localhost:8000/community/index.sq.html
http://localhost:8000/join
http://localhost:8000/XBL
http://localhost:8000/xbl
http://localhost:8000/RDF …
=> Update contribute, MDN, wiki redirects

media/js/base/banners/firefox-app-store-banner.es6.js
Shows mobile store banners only to nonFX users.
_(This picks up and supersedes #13331, updating it to current codebase.)_
This was unable to be fixed for a while when FxiOS and Focus stopped identifying themselves beyond generic UIWebView, but the identifiers are back for some time now so they can be told apart from the system engine again.
(At least on phones, or unless asking for "request desktop version" when the UA mimics either desktop Safari or desktop Linux FX, on iPads that's most of the time and even manually requesting mobile site doesn't change it reliably. But that's not issue with this code or changeset just consuming _Mozilla.Client_ and its limitations — the issues are with opinionated choices in the mobile products, as linked e.g. from …
=> Stop showing mobile store banners for current users

bedrock/sitemaps/tests/test_utils.py, bedrock/sitemaps/utils.py
...but not the structural site root, nor the root page in any locale.
Resolves #15022 
* Unit tests should be enough for now
* However, if you have Wagtail content available `DEV=False ./manage.py update_sitemaps` will put an updated sitemap.json file into bedrock/root_files and you can look for the paths to your wagtail pages in there
=> Expand sitemap.json generation to include live, public Wagtail pages

bedrock/base/templates/includes/banners/base.html, bedrock/base/templates/includes/banners/basic.html, bedrock/base/templates/includes/banners/mobile/firefox-app-store.html, bedrock/base/templates/includes/banners/mobile/focus-app-store.html, bedrock/mozorg/templates/mozorg/home/home-new.html, l10n/en/banners/firefox-app-store.ftl, l10n/en/newsletter_form.ftl, l10n/en/ui.ftl
Gives each `<aside>` landmark on the home page a unique label for screen readers.
#15000
=> Add aria-label to aside landmarks on home page (Fixes #15000)

bedrock/firefox/templates/firefox/nothing-personal/index.html, media/css/firefox/nothing-personal/_primary-cta.scss
Adds Apple App Store and Google Play Store badges as primary mobile CTAs on the `/firefox/nothing-personal/` campaign page.
#15020
Demo: https://www-demo1.allizom.org/en-US/firefox/nothing-personal/
http://localhost:8000/en-US/firefox/nothing-personal/
=> Add mobile app store badges to nothing-personal campaign page (Fixes #15020)

bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py
Adds a `v=1` param to WNP 130 URLs to allow Nimbus to test against the default WNP template.
#15034
=> Add default WNP fallback variant to WNP 130 URLs (Fixes #15034)

bedrock/cms/management/commands/run_smartling_sync.py, bedrock/cms/models/base.py, bedrock/settings/base.py
This changeset tweaks some dials related to the Smartling integration from Wagtail, getting it ready for when we move the VPN Resource Center into Wagtail.
Early review is fine - the only extra commit here will be bumping the version of `wagtail-localize-smartling`
**Done**
* Prevent `slug` field on localized pages from being sent to Smartling, and instead keep it synchronised with the source page's slug
* Configure initial set of language codes that we'll handle in the CMS. (These may change, of course, but they follow what we currently have in used for the VPN Resource Centre, which was localized in Smartling. Hopefully we can leverage Smartling's Translation memory automatically when we move those pages into Wagtail)
* Bump `wagtail-localize-smartling` to latest version (0.2.4 - due as …
=> Update Wagtail/ Smartling integration on the Bedrock side

bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py
#15035 added a variant param to show the default template, but Nimbus experiments use a different format of `?branch=foo&variant=bar` (I need to document this, right now it's tribal knowledge and that's my bad).
#15034 
fallback template: http://localhost:8000/firefox/130.0/whatsnew/?branch=experiment-wnp-130-tabs&variant=v1 
custom page: http://localhost:8000/firefox/130.0/whatsnew/?branch=experiment-wnp-130-tabs&variant=v2
Should also get the custom page with no params.
=> Update WNP 130 variant params [#15034]

Dockerfile
In order to run the postgres-to-sqlite export script in k8s, we need to have sqlite3 available there.
This changeset moves it from the 'devapp' image to the 'app-base' image, making it also available in the 'release' image, which we use in production
Contributes to https://github.com/mozilla/bedrock/issues/14660 
```
make build-prod
docker compose run --rm release bash
```
Then confirm you can run `sqlite3` without complaint
=> Make sqlite3 available in the production-grade release Docker image

bedrock/cms/models/base.py, bedrock/cms/tests/conftest.py, bedrock/cms/tests/test_models.py
By default, when a page is added, wagtail-localize will add an Alias per locale for each available locale, unless an actual translation of that page exists. This meant that, prior to this changeset, the languge selector in the footer was including languages which only had an Alias of a page available - and an Alias just links to the en-US content, but with a path of, say /fr/... which is misleading.
There'll be separate work to stop the auto-generation of Alias pages by default but as an extra safeguard, this changeset deliberately ignores Alias pages when computing the list of actual locales available for a CMS-backed page.
Resolves #15037 
Unit tests passing is probably ok for now, but if you have a local setup going with other pages in your DB (@alexgibson) feel free to switch to this …
=> Bugfix: ensure correct list of available translations for a CMS-backed page

bedrock/cms/models/base.py
Prior to this, the preview functionality would 500 until a draft was saved
=> Bugfix: handle error in preview when no page is draft and no aliases can exist yet

bedrock/firefox/templates/firefox/all/lang.html, bedrock/firefox/templates/firefox/all/platform.html, bedrock/firefox/templates/firefox/all/product.html, l10n/en/firefox/all.ftl
Fix https://github.com/mozilla-l10n/www-l10n/pull/426
=> L10n fixes

tests/conftest.py
=> Remove old pytest `allow_thread_sharing` fix

.github/dependabot.yml
It was discussed in Slack that the we should remove dependabot for Python for the following reasons:
- Too noisy / too many PRs open
- Non actionable via the PR interface due to our tooling
- We frequently update them on our own at a regular weekly-ish cadence
- We will still receive security advisories as an indicator of urgent updates
=> Remove dependabot for Python deps

tests/functional/conftest.py
Update download tests after /firefox/all/ refactor.
#15041 
Test locally by calling:
```
pytest -s --base-url http://localhost:8000 -m download tests/functional/test_download.py
```
=> Fix #15041: Update download tests after /all refactor

bedrock/settings/base.py
This changset increases the number of form fields allowed to be submitted in one GET/POST, but only for deployments where the CMS is enabled.
This is needed to support complex pages with lots of (small, but) nested fields.
Ref: https://mozilla.sentry.io/issues/5800147294
=> Fix 400 error when editing Leadership page

tests/playwright/specs/a11y/includes/urls.js
Adds marketing campaign URLs to a11y checker job
N/A
=> Add Firefox campaign URLs to a11y checker

docs/cms.rst, docs/testing.rst, tests/playwright/global-setup.js
- Updates Playwright global setup to remove a deprecation warning from Node.
- Also makes a small docs update to add some relevant links.
https://github.com/mozilla/bedrock/issues/15058
Node fix:
1. `npm start`
2. `cd tests/playwright && npm run a11y-tests`
Once the job finishes, you should be able to see the report files in `tests/playwright/test-results-a11y`.
Docs changes:
=> Fix node warning calling rmdirSync() when running Playwright setup (Fixes #15058)

bin/export-db-to-sqlite.sh, docs/cms.rst
Two fixes in this changeset for bugs which are only relevant to Dev right now.
1. Resolves #15084
`WorkflowState` references `TaskState`, but the latter is not (and can not be) dumped because it may contain sensitive info. So, let's not dump `WorkflowState`, either, because it's not relevant to loacl development anyway
2. Resolves #15085
Because `mozorg.LeadershipPage` was not specced in the allowlist for the DB export, the "Leadership page" only exists as `wagtailcore.Page` metadata - so it appeared in the tree, but couldn't be rendered or edited because there was no corresponding data in the DB for it. We also improve documentation to help avoid this in the future
=> Sqlite DB exporter bugfixes

bedrock/mozorg/templates/mozorg/home/includes/mofo-donate-promo.html
Fix a11y: Change `<aside>` to `<section>` for donation promo
Updated the `<aside>` element to `<section>` in the donation promo section on the home page to improve accessibility and adhere to best practices for landmark usage.
#15078
- Verified that the `<aside>` has been correctly changed to `<section>`.
- Checked the home page with a screen reader to confirm that the donation promo section is no longer misinterpreted as a complementary landmark.
- Ensured that the section is now recognized correctly as part of the main content.
=> Fix a11y: Change <aside> to <section> for donation promo

bedrock/firefox/templates/firefox/all/download.html, bedrock/firefox/templates/firefox/all/lang.html, bedrock/firefox/templates/firefox/all/platform.html, media/css/firefox/all.scss
Some a11y issues needed to be worked on for the updated `firefox/all/` page
- Fixes #15060 
- Fixes #15065 
- http://localhost:8000/en-US/firefox/all/
=> Update a11y for `firefox/all/` page

bedrock/firefox/templates/firefox/nothing-personal/index.html
Changes the link from generic Privacy Hub overview to its Firefox page.
After recent fx.privacy.landing removal, all such links now point to privacy root. This was requested to link to the Firefox specific page instead.
Resolves #15090
/en-US/firefox/nothing-personal/
=> Update Nothing Personal privacy CTA [fix #15090]

eslint.config.js
Ignores linting errors created by Wagtail CMS generated code
N/A
`npm run lint`
=> Add ./static to ESLint ignore paths

.github/dependabot.yml
- Enables Dependabot for bedrock's main NPM dependencies.
- Groups PRs for minor/patch bumps and dependency type.
- Excludes our own self-published NPM packages (such as Protocol), since these are more often than not released intentionally before requiring manual testing in bedrock.
N/A
=> Enable dependabot updates for front-end NPM packages

Makefile, bedrock/cms/management/commands/bootstrap_local_admin.py, bedrock/cms/management/commands/download_media_to_local.py, bedrock/cms/models/images.py, bedrock/cms/test_image_models.py, bedrock/cms/tests/test_commands.py, bin/custom-git-hooks/post-merge, bin/export-db-to-sqlite.sh, bin/sync-all.sh, docs/cms.rst, docs/install.rst
This changeset adds a few things to make it easier to develop CMS pages locally by getting a stable state
* Update "make preflight" command to allow a -- `--retain-db` flag + documentation
* Add `download_media_to_local` management command that copies images from the relevant cloud bucket to your local machine + documentation
Resolves #14659 
Note that you may need to set `WAGTAIL_ADMIN_EMAIL` (and maybe `WAGTAIL_ADMIN_PASSWORD`) in your .env to make it easier to retain access to your local CMS admin each time you refresh your DB - https://bedrock.readthedocs.io/en/latest/cms.html#accessing-the-cms has more on this and is worth a read.
1. Run `make preflight -- --retain-db` and confirm you don't get a new DB - the output will show what's happening
2. Run `./bin/sync-all.sh --retain-db` …
=> Developer experience improvements around DB downloads and getting CMS images

bedrock/base/templates/includes/banners/mobile/firefox-app-store.html, bedrock/base/templates/includes/banners/mobile/focus-app-store.html, bedrock/base/templates/macros.html, bedrock/firefox/templates/firefox/browsers/chromebook.html, bedrock/firefox/templates/firefox/browsers/mobile/index.html, bedrock/firefox/templates/firefox/enterprise/index.html, bedrock/firefox/templates/firefox/includes/download-button-thanks.html, bedrock/firefox/templates/firefox/includes/download-button.html, bedrock/firefox/templates/firefox/includes/download-list.html, bedrock/firefox/templates/firefox/includes/download-unsupported.html, bedrock/firefox/templates/firefox/includes/macros.html, bedrock/firefox/templates/firefox/index.html, bedrock/firefox/tests/test_helpers.py, bedrock/firefox/tests/test_views.py, bedrock/mozorg/templates/mozorg/analytics-tests/ga-index.html, media/css/firefox/browsers-products.scss, media/js/base/base-page-init.js, media/js/base/mozilla-utils.js, tests/pages/firefox/family/landing.py, tests/unit/spec/base/mozilla-utils.js, tests/unit/spec/firefox/new/common/thanks.js
Convert buttons with data-link-type="download" into CTAs.
- data-display-name ➡ data-cta-text 
- data-link-location  ➡ data-cta-position
- data-download-os="Desktop|Android|iOS" ➡ data-cta-type="firefox|firefox_mobile|firefox_focus"
- ~data-link-type~
- ~data-download-language~
- data-download-version is used by stub attribution, don't touch
#14062 
---
---
Notes:
- The documentation update that goes along with these changes is in #14910 
- The unified /all is going to be removed in #14324 so I have not edited those pages.
- 🟢  [Integration tests passed](https://github.com/mozilla/bedrock/actions/runs/10512769936)
=> Convert buttons with data-link-type="download" into CTAs

media/css/protocol/protocol-mozilla.scss
=> Fix new vs. old logo sizing

bedrock/sitemaps/tests/test_utils.py, bedrock/sitemaps/utils.py
(...unless they are also parents of real pages)
In the CMS we use a `StructuralPage` page type to create branches/folders in the page tree.
These `StructuralPage`s do not have content, but allow us to structure URL paths as we need, including matching some routes that already exist in the page tree as static/Django-only paths.
However, we've spotted a bug: prior to this changeset, if there's a static path for `foo/` and a `StructuralPage` for `foo/`, the static paths for `foo/` are dropped from the sitemap in favour of those from the CMS _even if the CMS has fewer locales set up than the static route_. This can be seen here where `/about/` was in the CMS as `StructuralPage` only in `en-US`, but in lots of locales as a static page: …
=> Ensure CMS StructuralPage pages don't appear in the sitemap

bedrock/base/templates/base-protocol-mozilla.html, bedrock/cms/templates/cms/base-protocol.html, bedrock/firefox/templates/firefox/new/basic/base.html, bedrock/firefox/templates/firefox/new/desktop/base.html, bedrock/products/templates/products/vpn/base.html
The firefox/new page uses `extrahead` instead of `site_css` to serve CSS to older IE browsers.
#15138
- http://localhost:8000/en-US/firefox/new/
- http://localhost:8000/en-US/firefox/new/?xv=basic
- http://localhost:8000/en-US/firefox/download/thanks/
- http://localhost:8000/en-US/firefox/download/thanks/?xv=basic
=> Fix missing footer styles on /firefox/new/ and /thanks/ (Fixes #15138)

bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html, bedrock/base/templates/includes/protocol/navigation/navigation.html, bedrock/settings/base.py, l10n/en/navigation_refresh.ftl, media/css/m24/base-navigation-and-footer.scss, media/css/m24/components/navigation-refresh.scss, media/css/m24/vars/color.scss, media/img/m24/arrow-dark-up.svg
https://github.com/mozilla/bedrock/issues/14827
=> Navigation refresh

.github/dependabot.yml
These dependencies need to be kept up to date manually with pre-commit-config.yaml, so this change tells dependabot to ignore them.
N/A
=> Update dependabot.yml to ignore certain front-end deps

tests/playwright/specs/a11y/components.spec.js, tests/playwright/specs/a11y/includes/locators.js
Updates a11y-checker to scan the redesigned footer instead of the old component.
N/A
- `npm start`
- `cd tests/playwright && npm run a11y-tests`
=> Update a11y-checker to scan redesigned footer

tests/functional/firefox/family/test_family.py, tests/functional/test_navigation.py, tests/pages/base.py, tests/pages/firefox/family/landing.py, tests/playwright/specs/navigation.spec.js, tests/playwright/specs/products/vpn/vpn-landing.spec.js
Points navigation tests to the old nav for now, since https://github.com/mozilla/bedrock/pull/14966 merged.
N/A
Successful test run: https://github.com/mozilla/bedrock/actions/runs/10881946899
=> Fix navigation functional tests

bedrock/firefox/templates/firefox/includes/download-unsupported.html, tests/playwright/specs/products/firefox/firefox-channel-desktop.spec.js, tests/playwright/specs/products/firefox/firefox-developer.spec.js, tests/playwright/specs/products/firefox/firefox-new.spec.js, tests/unit/spec/base/datalayer-productdownload.js
We're extending support for Firefox ESR 115 since so many outdated Windows / macOS users rely on it. This PR updates the ESR download buttons shown to unsupported website visitors to always return ESR 115. A special alias has been set up in bouncer here called `firefox-esr115-latest-ssl`
Marking this as a P1 since it needs to go live before the end of September (when `firefox-esr-latest-ssl` starts resolving to ESR 128)
#13753
Successful test run: https://github.com/mozilla/bedrock/actions/runs/10849536114
You can add a class of `windows fx-unsupported` and `osx fx-unsupported` to the `<html>` element to toggle display of the unsupported messaging.
=> Pin ESR 115 for unsupported operating systems (Fixes #13753)

.github/dependabot.yml
https://github.com/mozilla/bedrock/pull/15118 didn't quite work, I should have used `ignore` instead of excluded dependencies from group updates.
Hopefully this should work better, following: https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
N/A
=> Set Dependabot to ignore specific dependency updates

bedrock/base/templatetags/helpers.py, bedrock/cms/cms_only_urls.py, docs/cms.rst
This changeset gives us a way to reverse/generate consistent URLs for paths that we know will be served by the CMS, so that we can use the `url()` helper in templates for pages that don't exist in the static site. 
It does this by expanding the scope of the `url()` jinja helper to also look through a special `cms_only_urls` URLconf.
See the additions to `cms.rst` for more.
Resolves #14871 - although in a different way than we originally thoughts
Try moving the now-deprecated static Leadership page into the cms_only_urls.py:
```
--- a/bedrock/cms/cms_only_urls.py
+++ b/bedrock/cms/cms_only_urls.py
@@ -15,7 +15,7 @@
-# from django.urls import path
+from django.urls import path
def dummy_view(*args, **kwargs):
@@ -26,4 +26,9 @@ def dummy_view(*args, **kwargs):
urlpatterns = (
+    path(
+ …
```
=> Allow the url() helper to get a path for a page that will only exist in the CMS

bedrock/base/templates/includes/protocol/navigation/navigation.html
Adds back m24-logo condition to old nav masthead.
This was added in #15122 but disappeared after #14966 changes, perhaps unintentionally.
Resolves #15165
http://localhost:8000/nl/
=> Fix logo refresh in current nav

bedrock/firefox/templates/firefox/nightly/firstrun.html
Points the Nightly firstrun CTA for QA contributions to wiki instead of QMO site.
Resolves #14991
http://localhost:8000/en-US/firefox/nightly/firstrun/
=> Update Nightly firstrun "Start Testing" link

bedrock/firefox/templates/firefox/features/adblocker.html, l10n/en/firefox/features/adblocker.ftl
Some copy updates.
#15104 
http://localhost:8000/firefox/features/adblocker/
=> Updates to adblocker feature page [fix #15104]

bedrock/base/templates/includes/protocol/footer/footer-refresh.html, bedrock/base/templates/includes/protocol/footer/footer.html, bedrock/firefox/templates/firefox/built-for-you/landing.de.html, bedrock/mozorg/templates/mozorg/about/index-m24.html
Fixes a handful of small things the a11y checker turned up.
- Adds `role="contentinfo"` to both old and new footer components.
- Fixes heading levels in old footer.
- Removes stray `</div>` from German `/built-for-you/` page.
- Adds `<main>` landmark to new `/about/` page.
#15004
- http://localhost:8000/en-US/about/ (new footer)
- http://localhost:8000/de/about/ (old footer)
- http://localhost:8000/de/firefox/built-for-you/
=> Misc a11y fixes

.github/workflows/fluent_linter.yml, .github/workflows/pull_request_tests.yml, .readthedocs.yaml, Dockerfile, bedrock/base/tests/test_views.py, bedrock/cms/tests/test_rendering.py, bedrock/mozorg/management/commands/update_root_store_policy_page.py, bedrock/pocketfeed/api.py, bedrock/pocketfeed/tests/test_api.py, bin/check-pinned-requirements.py, docs/install.rst
We held off on upgrading to Python 3.12 earlier this year to wait for more releases (stability). We're at 3.12.6 to date so we feel safe to upgrade now.
Verify integration tests pass.
=> Update to Python 3.12.x

l10n/en/firefox/features/adblocker.ftl
Added comma (see https://github.com/mozilla-l10n/www-l10n/pull/432#discussion_r1768876738)
https://github.com/mozilla-l10n/www-l10n/pull/432#discussion_r1768876738
http://localhost:8000/firefox/features/adblocker/
=> String fix for adblocker page [#15104]

bedrock/firefox/templates/firefox/built-for-you/landing.de.html, bedrock/firefox/templates/firefox/built-for-you/landing.fr.html
Replaces mobile links on `/firefox/built-for-you/` page with links to customized app store listings.
#15203
- http://localhost:8000/de/firefox/built-for-you/
- http://localhost:8000/fr/firefox/built-for-you/
=> Add custom app store links to built-for-you page (Fixes #15203)

bedrock/base/templates/includes/protocol/footer/footer-refresh.html
Fixes empty cc href in new footer.
The url('foundation.licensing.website-content') needs to be passed in an updated way incl. the attribute etc., and set correctly to the variable actually used in fluent.
Fixes #15167
http://localhost:8000/en-CA/
=> Refresh: Fix footer licensing link render

docs/cms.rst
1024x isn't one of the pregenerated/allowed widths
=> Fix the example of the rendition spec in the CMS docs

bin/export-db-to-sqlite.sh
This changeset fixes a blocking error with the DB export script which failed when it came across data linking the users table to a permissions table, which up until now had been empty. (Adding a non-superuser User to the CMS admin created a row in the `auth_user_group` table, which previously had been empty.)
This changeset:
* Fixes the blocking error when exporting a source DB where the `auth_user_groups` and/or `auth_user_user_permissions` tables have data
These two tables have a non-NULL `user_id` column, which means that the script is now failing because it could not nullify rows in those tables. The data for those rows was being pulled over via FK constraints because we exported the `auth.User` model from the source DB.
The fix was to ensure that we were actually purging those two …
=> Fix DB export script

bedrock/firefox/templates/firefox/nightly/whatsnew.html, l10n/en/brands.ftl, l10n/en/firefox/nightly/whatsnew.ftl
- Created a new string for the page with id `nightly-whatsnew-want-to-know-which-v3`
- Added a new `-brand-name-firefox-labs` string for Firefox Labs in brands.ftl
issue #15187 
- `make test` passed
- I see the new string when running bedrock locally
=> Issue #15187 - Nightly update message should refer to Firefox Labs instead of Nightly Experiments

media/css/m24/components/navigation-refresh.scss
This PR fixes the margin on mobile pages.
https://github.com/mozilla/bedrock/issues/15214
1.Set SWITCH_M24_NAVIGATION_AND_FOOTER to be true in your local env file
2. Go to any page with a sub nav, such as http://localhost:8000/en-US/firefox/new/
3. Resize browser to mobile screen size
=> update top margin for pages with sub nav fixes issue #15214

bedrock/cms/management/commands/download_media_to_local.py
This changeset fixes two issues with the CMS-image downloader:
1) If the output/target dirs did not exist, the downloader errored out (This situation would arise if a developer had not previously uploaded CMS images on their machine, which automatically does create the directories)
2) Ensure that when redownloading images, the DB renditions table is also wiped, else fresh renditions of the images being redownloaded will not be generated -- this could cause confusion if, say, the `original_images` directory is lost and restored with a `--redownload` option (where the renditions might then be stale) or if all of `custom-media` is lost and reinstated via `--redownload` then the renditions wouldn't exist at all, because the DB thinks they already exist.
If you want to manually test this, it …
=> Fix CMS image download

bedrock/firefox/templates/firefox/nothing-personal/includes/browser-macro.html, bedrock/firefox/templates/firefox/nothing-personal/index.html, bedrock/newsletter/forms.py, bedrock/newsletter/templatetags/helpers.py, bedrock/newsletter/tests/test_footer_form.py, media/css/firefox/nothing-personal/_browser.scss, media/css/firefox/nothing-personal/_header.scss, media/css/firefox/nothing-personal/_primary-cta.scss, media/css/firefox/nothing-personal/_sticky-note.scss, media/css/firefox/nothing-personal/styles.scss
Adds a newsletter form to the bottom of `/firefox/nothing-personal/`.
#15218
http://localhost:8000/en-US/firefox/nothing-personal/
=> Add newsletter form to nothing-personal page (Fixes #15218)

bedrock/firefox/templates/firefox/nothing-personal/index.html, bedrock/newsletter/forms.py
The slug was updated so the waitlist will appear in the pref center, so the form submission needs to now match the slug.
=> Update nothing personal college interest as waitlist

Makefile
If `uv pip`, use it, otherwise fall back to `pip`. This also pulls in the `check-pinned-requirements.py` instead of raw `pip list`.
AI helped spit out a skeleton of the `check-pinned-requirements.py` file and I further honed it.
=> Update Makefile to check for `uv pip`

bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py
NA:
- http://localhost:8000/en-US/firefox/131.0/whatsnew/ (en-US no experiment, cookie protection)
- http://localhost:8000/en-US/firefox/131.0/whatsnew/?branch=experiment-wnp-131-tabs&variant=v1 (en-US control)
- http://localhost:8000/en-US/firefox/131.0/whatsnew/?branch=experiment-wnp-131-tabs&variant=v2 (en-US cookie protection)
- http://localhost:8000/en-CA/firefox/131.0/whatsnew/ (en-CA no experiment, cookie protection)
- http://localhost:8000/en-CA/firefox/131.0/whatsnew/?branch=experiment-wnp-131-tabs&variant=v1 (en-CA control)
- http://localhost:8000/en-CA/firefox/131.0/whatsnew/?branch=experiment-wnp-131-tabs&variant=v2 (en-CA cookie protection)
EU:
- http://localhost:8000/en-GB/firefox/131.0/whatsnew/ (en-GB no experiment, cookie protection)
- …
=> Show custom WNP 131 when no experiment params are present

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx131-eu.html
Switches out the right CTA when the template is viewed without experiment params
N/A
http://localhost:8000/en-GB/firefox/131.0/whatsnew/
http://localhost:8000/en-GB/firefox/131.0/whatsnew/?branch=experiment-wnp-131-tabs&variant=v4
http://localhost:8000/en-GB/firefox/131.0/whatsnew/?branch=experiment-wnp-131-tabs&variant=v3
=> Fix WNP 131 CTA for default custom template

docs/attribution/0003-firefox-mobile.rst
The example URLs in this doc are the wrong way around, and the Focus campaign string was incorrect: https://github.com/mozilla/bedrock/blob/main/docs/attribution/0003-firefox-mobile.rst#app-store-redirects
N/A
=> Fix app store url examples in the docs

media/js/base/sentry-consent.es6.js
Silences https://mozilla.sentry.io/issues/3334536137/?project=6260331
See https://github.com/getsentry/sentry-javascript/issues/6945 for context
N/A
=> Ignore non-useful JS error in Sentry

l10n/en/products/vpn/shared.ftl
Restores a string that was accidentally removed in https://github.com/mozilla/bedrock/pull/15243
#15257
http://localhost:8000/en-US/products/vpn/?geo=cn
=> Restore missing VPN shared string (Fixes #15257)

.github/l10n/linter_config.yml
The remaining linter exception was removed from strings when translations changed last year.
Removed in https://github.com/mozilla/bedrock/pull/13644
✅ [actions/runs/10517645057/job/29142138942?pr=14996#step:5:1](https://github.com/mozilla/bedrock/actions/runs/10517645057/job/29142138942?pr=14996#step:5:1)
=> Remove fixed Fluent linter brand exclusions

bedrock/mozorg/templates/mozorg/contact/contact-landing.html
The MDN redirect is broken for anyone who does not have English as their preferred language.
https://bugzilla.mozilla.org/show_bug.cgi?id=1923262
http://localhost:8000/en-US/contact/
=> Update bug writing guidelines link on /contact page (Fixes bug 1923262)

bedrock/firefox/templates/firefox/challenge-the-default/includes/toggles.html, bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
Prevents elements that are visible on the screen but contain `aria-hidden="true"` from receiving keyboard focus (having elements omitted from reading order but included in keyboard navigation can create a confusing state for screen readers).
#15137
http://localhost:8000/de/firefox/challenge-the-default/
=> Prevent aria-hidden elements from receiving keyboard focus (Fixes #15137)

media/css/protocol/protocol-firefox.scss
Fixes the m24-logo jumping around based on what bundle is loaded.
When navigating between pages using protocol-mozilla and protocol-firefox, the m24-logo in old nav shifts — unless the positioning matches between the styles, so this adds the -mozilla treatment to -firefox base too.
Resolves #15207
Set up .env just for the brand refresh:
```python
SWITCH_M24_ABOUT=False
SWITCH_M24_GLOBAL_STYLES=False
SWITCH_M24_HOME=False
SWITCH_M24_LOGO=True
SWITCH_M24_NAVIGATION_AND_FOOTER=False
```
=> Add m24-logo sizing also to protocol-firefox

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2024.html, bedrock/mozorg/urls.py
Added the new transparency report for January–June 2024
> [!NOTE]
> i messed up the commit message by saying h2 🤦🏼 
Fixes https://github.com/mozilla/bedrock/issues/15239
=> H1 2024 Transparency Report

bedrock/firefox/templates/firefox/welcome/page19.html, media/css/firefox/welcome19.scss, media/js/firefox/welcome/welcome19.js, media/static-bundles.json
The latest change came in to add a new CTA for ESR users + to update the primary CTA to take the user straight to the Download Firefox page.
>[!IMPORTANT]
> Make sure UITour is enabled in your ESR browser to test things. Find the steps here: https://bedrock.readthedocs.io/en/latest/uitour.html#local-development
Fixes https://github.com/mozilla/bedrock/issues/15162
=> Added ESR link and updated primary link in Moments Page 

bedrock/cms/wagtail_hooks.py
Shift wagtail menus to require staff, not superuser.
=> Shift wagtail menus to require staff

bedrock/settings/base.py, bedrock/urls/mozorg_mode.py, bin/export-db-to-sqlite.sh, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This branch was originally a test harness for using https://github.com/mozmeao/wagtaildraftsharing/pull/1 in bedrock, but now it's just adding in the completed work from that PR.
In order to test drive this branch (using the steps outlined for reviewing that PR liked above), you need to carry out these steps:
1. Check out this branch by running `git fetch` on whatever your `mozilla` origin is called, then `git switch 15181--wagtail-page-review-without-auth`. 
2. `make install-local-python-deps` to get requirements installed - check that our fork of wagtaildraftsharing is being installed
3. `./manage.py migrate`
4. Start your runserver as usual and then go to https://github.com/mozmeao/wagtaildraftsharing/pull/1 to continue testing
Resolves #15181
=> Add our fork of wagtaildraftsharing to Bedrock

bedrock/settings/base.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This will mean that CMS notifications will go via the task queue.
The default queue of, well, "default" will be used, which is one of the queues already being processed by our worker pods: https://github.com/mozilla/bedrock/blob/main/bin/run-worker.sh#L8
At the moment, the Web deployment does not have Redis available to it so will not have a task queue enabled, and so in turn the emails that web pods send (eg press requests) will have no change to their sending pattern
=> Switch email sending to task queue when available

bin/export-db-to-sqlite.sh
The DB export script is seeming pretty stable now, but never say never, so we should have a Dead Man's Snitch set up to alert us if the export starts to fail, as that has knock-on effects with sitemap generation and site-scanning, as well as local dev.
There's a complementary infra PR that can be merged before or after - the code will only run if the snitch URL is avaiable in the env
Resolves #15221
=> Add a call to a DMS when the DB export script completes

bedrock/base/templates/base-protocol.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html, media/css/m24/components/navigation-refresh.scss, media/js/base/protocol/init-m24-navigation.js, media/js/base/protocol/m24-menu.js, media/js/base/protocol/m24-navigation.js, media/static-bundles.json
This PR refactors the new navigation to remove old styles from the current nav. This is one of the steps to reduce new base CSS bundle size.
https://github.com/mozilla/bedrock/issues/15120
https://github.com/mozilla/bedrock/issues/15196
1. Set `M24_NAVIGATION_AND_FOOTER` switch to be `on`
2. Check out this PR
3. Review navigation styles, it should look and function exactly like before refactoring
=> update nav to remove existing nav styles

bedrock/firefox/templates/firefox/includes/download-unsupported.html
Restores missing attribute required for stub attribution https://github.com/mozilla/bedrock/blob/main/media/js/base/stub-attribution/stub-attribution.js#L165
N/A
=> Restore data-download-version attribute to ESR 115 download links

media/css/m24/components/navigation-refresh.scss
The nav menu close icon was broken, due to a missing path
https://github.com/mozilla/bedrock/issues/15283
`./manage.py waffle_switch M24_NAVIGATION_AND_FOOTER on`
=> Fix icon path in navigation-refresh.scss (Fixes #15283)

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This resolves #15291 where pages could not be added to the CMS
Resolves #15291
=> Bump wagtaildraftsharing to hotfix release

bedrock/firefox/templates/firefox/nothing-personal/index.html
Updates the mobile app store URLs for more specific attribution.
#15274 
App store badges are shown in the page header only on mobile.
=> Update Nothing Personal page app store URLs [fix #15274]

media/css/m24/components/navigation-refresh.scss
This PR removes animation/transition for the nav when reduced motion preference has been specified. 
https://github.com/mozilla/bedrock/issues/15275
1. Check out this PR
2. Set feature switch `M24_NAVIGATION_AND_FOOTER` to be `on`
3. Enable your device's "Reduced Motion" setting
4. Go to http://localhost:8000/en-US/
5. Scroll down the page, the nav animation shouldn't be visible
6. Resize the screen to mobile size and open menu
7. The menu content slide in animation shouldn't be visible
=> Static nav for reduced motion fixes (#15275)

media/css/protocol/protocol-mozilla-2024.scss
Adds support for both old and new branding within the original footer, after switching to the protocol-mozilla-2024 stylesheet.
Only en-* locales, or locales with enough translations get the refresh footer and header, even once the -2024 bundle is used; so the old nav and footer still display for various locales even with all the switches flipped — therefore the 2024 bundle also needs to support m24-logo declaration overrides used in old components.
(Another way could be linking the m24 assets right away in all the 2024 styles, as these should be the correct ones come time for this bundle?)
Resolves #15206
http://localhost:8000/cy/
http://localhost:8000/sco/?xv=legacy
=> Fix m24-logo in 2024 style for old footer

media/css/protocol/protocol-mozilla.scss
Skips targeting base-error template uses for sizing adjustments of m24-logo.
404/500 error pages use `.header-image .logo-mozilla .c-navigation-logo-image` while elsewhere it's `.c-navigation-logo .c-navigation-logo-image` — so this specific selector only targets the old nav, leaving the sizing in base-error header just to the img attrs.
(It could be fine-tuned a bit more though, but that is perhaps to come after cleaning up the outdated variants one day.)
#15130 followup
http://localhost:8000/nl/404
http://localhost:8000/en-US/careers/position/foo/404/ _(with Debug=False)_
=> Fix new logo sizing in base-error

bedrock/base/templates/base-error.html, bedrock/base/templates/base-protocol-mozilla.html, bedrock/base/templates/base-protocol.html, bedrock/base/templates/includes/protocol/footer/footer.html, bedrock/base/templates/includes/protocol/navigation/navigation.html, bedrock/firefox/templates/firefox/new/basic/base.html, bedrock/firefox/templates/firefox/new/desktop/base.html, bedrock/mozorg/views.py
Merges all the different website refresh parts to use a single waffle switch.
For now several parts are still English-only (nav and footer globally, the home and about pages) but if we can get them localized for MVP we'll need to modify some logic for the added locales.
#15289 
Add and DEactivate the new switch:
`./manage.py waffle_switch --create M24_WEBSITE_REFRESH off`
The website should have the current branding.
Flip that switch on and the website should have the new branding.
You can then delete the obsolete switches:
```
M24_NAVIGATION_AND_FOOTER
M24_ABOUT
M24_HOME
M24_LOGO
M24_GLOBAL_STYLES
```
=> Refresh: consolidate under a single waffle switch [fix #15289]

bedrock/newsletter/templates/newsletter/firefox-confirm.html, bedrock/newsletter/urls.py, bedrock/newsletter/views.py, media/css/newsletter/newsletter-firefox-confirm.scss, media/js/newsletter/confirm-init.es6.js, media/js/newsletter/confirm.es6.js, media/static-bundles.json, tests/unit/spec/newsletter/confirm.js
Adds one-click confirmation landing page for Firefox newsletter
#15142
First get your newsletter token by following these steps:
1. Open https://www.mozilla.org/en-US/newsletter/recovery/ and enter your email.
2. Find the recovery email, and click the link that opens the email preference center.
3. Open Dev Tools -> Storage -> Cookies and find the cookie called `nl-token`. Copy it's value (which should be a long alpha-numeric string).
4. Whilst you're here, make sure you are not subscribed to the Firefox newsletter (unsubscribe if you are).
Next, open the confirmation page using your token in the URL:
1. Open: `http://localhost:8000/en-US/newsletter/firefox/confirm/{INSERT_YOUR_TOKEN_HERE}`
2. When the page loads, click "Confirm".
3. Wait to see a "thank you" message and then you should …
=> Add Fx News one-click-subscribe page (Fixes #15142)

bedrock/products/templates/products/vpn/includes/macros.html, bedrock/products/templates/products/vpn/more/base-article.html, bedrock/products/templates/products/vpn/platforms/platform-base.html, bedrock/products/templates/products/vpn/resource-center/landing.html, bedrock/products/views.py, bedrock/settings/base.py
Prevents showing "12 month money back guarantee" copy in countries where subscriptions cannot be purchased directly through the website.
- I also removed some old / unused macros
- There are a couple of old (orphaned) SEO pages where i simplified by removing the guarantee copy, rather than replicate all the country detection logic needed.
#15262
- http://localhost:8000/en-US/products/vpn/?geo=au
- http://localhost:8000/en-US/products/vpn/pricing/?geo=au
- http://localhost:8000/en-US/products/vpn/resource-center/?geo=au
=> Prevent showing guarantee copy for VPN mobile subscription countries (Fixes #15262)

tests/playwright/specs/a11y/includes/urls.js, tests/playwright/specs/a11y/pages.spec.js
Expands the a11y checker test job to a much larger set of URLs. Also creates separate URL lists for mobile and desktop scans, as many pages don't really change much when resized.
#14773
- `npm start`
- `cd tests/playwright`
- `npm run a11y-tests`
=> Expand a11y test coverage (#14773)

bedrock/products/templates/products/vpn/includes/mobile-subscribe.html, l10n/en/products/vpn/pricing-2023.ftl
Fixes an edge case: In countries where subscriptions are only enabled for the Google Play Store, we always want to link to there even if the visitor is on an iOS device.
#15328
1. Open http://localhost:8000/en-US/products/vpn/?geo=BR
2. Mock iOS by changing the `<html>` class name from `osx` to `ios`.
3. Scroll down to the "One subscription for all your devices" section.
=> Show Google Play Store CTA when on an iOS device in Android only country (Fixes #15328)

bedrock/firefox/templates/firefox/nothing-personal/index.html
Changes a dash to an underscore in the Play Store URL, which is set up in the Play Store to show a custom "nothing personal" branded page.
#15274 
You'll need to test on an Android device (faked in dev tools, browserstack, or real). Click the Play Store link should load a customized page showing nothing personal branded screenshots.
=> Fix Andriod link on Nothing Personal page [#15274]

Dockerfile, bedrock/cms/models/images.py, bedrock/cms/test_image_models.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This changeset adds support for generating renditions of animated GIFs, using the Python Wand library (which wraps ImageMagick)
This is working locally when I don't have a task queue enabled, but it is blowing up when we do have a task queue enabled. However, that may be just on my local system (and the local system doesn't _need_ the task queue running). So I'm keen to get this onto Dev and see how it goes in the real infra. Worst case, renditions will fail to be generated for animated GIFs and we'll have to do those synchronously on save (which should hopefully be fine as long as the job takes <30 secs to avoid a k8s timeout), and I'll patch that work in immediately if we need it.
#15330
Will be tested manually on Dev as soon as it lands
=> 15330  add animated gif support to cms

.pre-commit-config.yaml
Since Node 23 came out, fresh installs or updates to our pre-commit hooks will fail for eslint. This is because pre-commit will pick the very new version of Node, because we haven't told it not to.
This change tells pre-commit to use the LTS version installed on the system, which will match what we use for main Bedrock
On `main`: 
```
pre-commit clean
pre-commit install-hooks
```
This will fail for eslint
On this branch - and assuming you have an LTS version of Node installed (eg 20)
```
pre-commit clean
pre-commit install-hooks
```
will now install fine
=> Ensure pre-commit uses LTS version of node

bedrock/careers/templates/careers/includes/footer.html, bedrock/careers/templates/careers/listings.html
Addresses a11y issues - thanks @alexgibson for the tips!
Moving to a h3 from a h4 on the careers listing page did make the font size slightly larger. It looks fine, but of course I'm happy to try to  match the original h4 size with CSS if reviewers think it's worth it.
Resolves #15338 
Run a11y tests - there should now be 14 failures, down from 20, and no failures on the careers pages.
=> Fix accessibility issues on careers pages

bedrock/firefox/templates/firefox/nothing-personal/index.html
Updates copy in head elements as per issue.
Resolves #15355 
Go to http://localhost:8000/en-US/firefox/nothing-personal/ and view source, looking for title and meta name="description" tags
=> Update wording in Nothing Personal page's metadata

bedrock/products/templates/products/vpn/includes/mobile-subscribe.html
- Fixes an issue where the QRCode background image is not displayed when the browser window is exactly 768px wide.
- Also hides the blue "Download the app" CTA on iOS when the user is in a country where Apple subscriptions are not supported.
https://mozilla-hub.atlassian.net/browse/VPN-6674
#15328
1. Open http://localhost:8000/en-US/products/vpn/?geo=br
2. Open dev tools / responsive design mode.
3. Resize the viewport to 768px.
Next, change the platform class on the `<html>` element from `osx` to `ios`.
Now change the platform class from `ios` to `android`.
=> VPN mobile subscription misc fixes (Fixes #15328)

bedrock/mozorg/templates/mozorg/contribute.html
Parts of the page were not contained within landmarks - five of the issues were solved with a fix to invalid html, the last was solved by promoting the newsletter section to become an aside.
Resolves #15340
Run a11y tests and confirm that contribute is not included in the list of failures.
=> Fix a11y landmark issues on contribute 

bedrock/base/templates/base-protocol-mozilla.html, bedrock/base/templates/base-protocol.html, bedrock/firefox/templates/firefox/new/basic/base.html, bedrock/firefox/templates/firefox/new/desktop/base.html, media/css/m24/components/footer-refresh.scss, media/css/m24/navigation-and-footer.scss, media/css/protocol/components/_footer.scss, media/css/protocol/navigation-and-footer.scss, media/css/protocol/protocol-firefox.scss, media/css/protocol/protocol-mozilla-2024.scss, media/css/protocol/protocol-mozilla.scss, media/static-bundles.json
Removes the nav and footer styles from the refreshed Protocol and sets them up in separate bundles. This lets us load only the styling for the appropriate components based on the page language.
This is based on #15312 but is a simplified approach.
#15120
Test with the `M24_WEBSITE_REFRESH` switch both off and on. When off, the site should be all the legacy Mozilla branding. When on, it gets the refreshed branding.
English pages should get the new nav and footer, non-English pages should get the old nav and footer.
=> Refresh: Separate nav and footer styles from protocol base

media/css/protocol/navigation-and-footer.scss
I neglected to define the image path for the footer styles in #15353 and it's throwing build errors. I haven't actually reproduced the error locally so I'm not certain this will fix it, but it also shouldn't hurt. I think it may depend on the order in which Sass files are compiled?
CSS should compile with the appropriate file path for images.
=> Add paths to legacy nav and footer styles [#15120]

bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html, bedrock/base/templates/includes/protocol/navigation/navigation.html, media/css/m24/components/navigation-refresh.scss
- Fixes navigation menu positioning when there's content positioned above the navigation (such as the pencil banner).
- Fixes mobile menu button background color regression.
- Tidies up a few redundant uses of `unset` (from when the new navigation CSS was overriding the old CSS).
- Adds navigation landmark / role.
- I inserted a fake bit of content above the navigation in this PR to make testing easier. I need to remove it again before merging!
- Please test both the desktop and mobile menus, as the fix required some updates to both sets of styles.
https://github.com/mozilla/bedrock/issues/15315
1. Set `M24_WEBSITE_REFRESH` to active in your DB.
2. Open http://localhost:8000/en-US/
3. Hover over the menu items.
1. Resize the browser to mobile screen size.
2. Click the menu button to open …
=> [Refresh] Navigation positioning fix

bedrock/firefox/templates/firefox/enterprise/index.html
Ensure the three picto components contained within a `<ul>` are `<li>` elements instead of `<div>` elements.
Resolves #15341
Run a11y tests to confirm that /firefox/enterprise does not throw up failures.
=> Fix a11y issues on firefox/enterprise

bedrock/mozorg/templates/mozorg/about/manifesto.html
The key change was basically moving the newsletter aside out of the main landmark.
Resolves #15336 
Run a11y tests and confirm that /about/manifesto/ is not listed as a failing test
=> Fix a11y issues with /about/manifesto/

bedrock/cms/management/commands/bootstrap_demo_server_admins.py, bedrock/cms/tests/test_commands.py
This command is intended to be called after a Bedrock Demo has been deployed to Cloud Run so that we can bootstrap users who may then log in via SSO. The value of the users list will come from a GCP Secret as a comma-separated list of email addresses.
The relevant change to the GCP Cloud Build trigger that would use this command will follow as a separate change on the relevant repo.
#15375
`DEMO_SERVER_ADMIN_USERS=test@example.com,test2@example.com ./manage.py bootstrap_demo_server_admins`
Also reviewing the unit tests should be enough for now
=> Add management command to bootstrap admin users on demo servers

bin/export-db-to-sqlite.sh
This changeset fixes two niggles with the DB exporter which were creating a flawed DB export that is stopping ``www-sitemap-generator`` from working 
* We weren't exporting the VPN-related Wagtail models, only the Page models (which constitute only half the data)
* We were INCLUDING Wagtial core `Page`s which were not live - ideally we should not, because in the future they would potentially contain retired (but non-Draft) content; and before a page is first published and only exists as a Draft, having just the `Page` data but no specific model (eg the VPN detail page model), Wagtail blows up because it doesn't have the full picture.
Resolves #15378 
* If you don't have one already, set up a local postgres DB from which to export:
1. `docker compose up db` will start a postgres DB on your …
=> Fix up sqlite DB export

bedrock/mozorg/templates/mozorg/advertising/landing.html
Fix a11y issue by wrapping page content in a <main> element
Resolves issue 15337
/advertising does not come up in list of a11y failures
=> Fix a11y issue by wrapping page content in a <main> element

bin/export-db-to-sqlite.sh
Until we can find a way to exclude both the wagtailcore_page _and_ the related custom model that references this, the exclusion behaviour creates a DB with a state that fails integrity checks, because the custom model references a wagtailcore_page table row which no longer exists
=> Fix issue around partial exclusion of draft pages from DB export

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx132-eu.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx132-na.html, docs/attribution/0001-analytics.rst
Add `data-cta-name` as a supported attribute for CTAs, implement on WNP 132
https://github.com/mozilla/bedrock/issues/15391
`make livedocs` 
WNP 132 is on [demo2](https://www-demo2.allizom.org/en-US/firefox/132.0/whatsnew/) for testing.
=> Add data-cta-name to documentation

bedrock/products/views.py, l10n/en/products/vpn/landing.ftl
This fixes two issues that came out of https://github.com/mozilla/bedrock/issues/15226
1. VPN landing page should now use `products/vpn/landing-2023.ftl` to figure out which locales were active. It was still looking the old file for reference.
2. Restores some strings that were accidentally removed for the invite page. Thankfully this didn't effect anything in prod, as the old file was still being referenced. I've restored the strings here so we can continue to use them.
https://github.com/mozilla/bedrock/issues/15407
- http://localhost:8000/de/products/vpn/
- http://localhost:8000/de/products/vpn/pricing/
- http://localhost:8000/de/products/vpn/invite/
=> VPN landing pages locale fix

bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, bedrock/mozorg/templates/mozorg/home/includes/m24/products.html, l10n/en/navigation_refresh.ftl
Updates both navigation and home page to use full product brand names for Mozilla VPN and Mozilla Monitor.
#15351
Test using `M24_WEBSITE_REFRESH` switch enabled:
=> Update product brand names in nav and on home page (Fixes #15351)

docs/install.rst
Adds docs about adding waffle switch migrations to ship a switch with code, if needed.
=> Add docs on waffle switch migrations

bin/sync-all.sh
This is so that we can boostrap SSO users on the demo servers on Cloud Run. 
This approach is a lot simpler, cleaner and more build-time efficient than doing a multi-stage container build in Cloud Build, but it does add to the complexity of that sync-all script...
* `DEMO_SERVER_ADMIN_USERS=test@example.com,test2@example.com ./bin/sync-all.sh` - to see demo users bootstrapped
* `DEMO_SERVER_ADMIN_USERS=test@example.com,test2@example.com ./bin/sync-all.sh` again, to see what happens if they already exist
* `./bin/sync-all.sh` to  confirm demo users are not bootstrapped if the env var isn't there
=> Support bootstrapping demo users in main DB setup script, if appropriate

media/css/products/vpn/download.scss
Fixes a small layout issue on the VPN download page when on mobile.
Screenshot of the bug: 
https://mozilla-hub.atlassian.net/browse/VPN-6687
1. Open http://localhost:8000/en-US/products/vpn/download/
2. Change the platform class on the `<html>` element from `osx` to `android`.
=> VPN download page CTA margin fix (Fixes #15405)

media/css/m24/components/navigation-refresh.scss
This is a bit of a refactor of the navigation CSS to try and help ensure it's accessible even without JS. This helps make our navigation hopefully more resilient in the case of JS breakage / errors in older browsers.
#15360
=> [Refresh] Progressively enhance navigation (Fixes #15360)

media/css/m24/components/footer-newsletter.scss, media/css/m24/components/footer-refresh.scss, media/css/m24/components/navigation-refresh.scss, media/css/m24/components/pencil-banner.scss, media/css/m24/grid.scss, media/css/m24/spring.scss, media/css/m24/vars/_spacing.scss
Standardize border widths at 2px for refresh.
Tess is standardizing on 2px for all borders and dividers. I added the variable `$border-width` and changed border and border-like properties to use it. 
Fix #15428
🤷‍♀️ No CSS errors? Things still have borders?
=> Refresh: Standardize border widths at 2px (Fix #15428)

bedrock/firefox/templates/firefox/includes/download-unsupported.html, bedrock/firefox/views.py
- Hides ESR115 download link on /firefox/all/ if language is not supported.
- Fallback to `en-US` on `/firefox/new/` if language is not supported.
#15437
/firefox/all/
URLs:
- http://localhost:8000/en-US/firefox/all/desktop-esr/win64/sat/
- http://localhost:8000/en-US/firefox/all/desktop-esr/win64/skr/
/firefox/new/
(Tip: add a class of `fx-unsupported` to the `<html>` element to simulate an unsupported OS)
- http://localhost:8000/skr/firefox/new/
=> Fix 404 ESR115 download links for /sat/ and /skr/ languages (Fixes #15437)

.github/workflows/pull_request_tests.yml
See:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
=> Cancel prev CI runs on new pushes

bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html, bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html
Remove lazy loading attributes from images in the navigation menu that appear by default.
The wordmark always appears above the fold when a page loads.
I went back and fourth on the Firefox icon since it's hidden on mobile but it's used all over the website so I think this is still the right thing to do.
n/a
Images still load.
=> Refresh: Nav - Don't lazy load images in top level of header navigation menu

bedrock/firefox/templates/firefox/firefox-20th/index.html
This PR fixes the SUMO link on Firefox 20th landing page. See details: https://github.com/mozilla/bedrock/pull/15409#issuecomment-2462975026
https://github.com/mozilla/bedrock/issues/15383
http://localhost:8000/en-US/firefox/firefox20/ SUMO link should work now
=> fix SUMO link

bedrock/firefox/templates/firefox/firefox-20th/index.html, bedrock/firefox/templates/firefox/firefox-20th/video-fanart.html
This PR updates the Firefox 20th landing page fan art section. Replace the split image with a video.
https://github.com/mozilla/bedrock/issues/15383
http://localhost:8000/en-US/firefox/firefox20/
http://localhost:8000/en-CA/firefox/firefox20/
http://localhost:8000/en-GB/firefox/firefox20/
http://localhost:8000/fr/firefox/firefox20/
http://localhost:8000/de/firefox/firefox20/
=> add fan art video for Firefox 20th landing page (fix #15383)

bedrock/firefox/redirects.py
Adds two new parameters to the list (not pretty but it's the format they're using in their experiment)
```
"DESKTOP_FEATURE_CALLOUT_SIGNED_INTO_ACCOUNT.treatment_a",
"DESKTOP_FEATURE_CALLOUT_SIGNED_INTO_ACCOUNT.treatment_b",
```
#15470
=> Add new campaign params for experiment [fix #15470]

tests/functional/test_cdn.py
This was the only failing test when run locally, just a difference in casing in how the CDN presents this information.
The `ssl-labs` tests use an external DNS and so cannot test the changes under question. Once deployed we can verify those tests are the same or make adjustments as needed.
Ran the tests locally pointing at a local `/etc/hosts` override to test CDN deployment.
=> fix(tests/cdn): Make check case insensitive

bedrock/products/templates/products/vpn/includes/mobile-subscribe.html, bedrock/products/templatetags/misc.py, bedrock/products/tests/test_helper_misc.py, bedrock/settings/base.py, l10n/en/products/vpn/pricing-2023.ftl, media/css/products/vpn/pricing-refresh.scss
This is a followup to #15262 that adds pricing information for countries where Mozilla VPN must be purchased through a mobile app store.
https://github.com/mozilla/bedrock/issues/15463
- http://localhost:8000/en-US/products/vpn/?geo=AU
- http://localhost:8000/en-US/products/vpn/?geo=BD
- http://localhost:8000/en-US/products/vpn/?geo=BR
- http://localhost:8000/en-US/products/vpn/?geo=CL
- http://localhost:8000/en-US/products/vpn/?geo=CO
- http://localhost:8000/en-US/products/vpn/?geo=EG
- http://localhost:8000/en-US/products/vpn/?geo=GR
- http://localhost:8000/en-US/products/vpn/?geo=ID
- http://localhost:8000/en-US/products/vpn/?geo=IN
- http://localhost:8000/en-US/products/vpn/?geo=KE
- http://localhost:8000/en-US/products/vpn/?geo=KR
- http://localhost:8000/en-US/products/vpn/?geo=MA
- …
=> Add pricing information to VPN mobile subscription CTA (Fixes #15463)

bedrock/mozorg/templates/mozorg/about/includes/m24/community.html, bedrock/mozorg/templates/mozorg/home/includes/m24/resources-grid.html
This PR removes two CTAs from M24 home and about pages.
https://github.com/mozilla/bedrock/issues/15478
Turn on switch `M24_WEBSITE_REFRESH`
=> M24 remove ctas (fix #15478)

bedrock/firefox/templates/firefox/browsers/browser-history.html, l10n/en/firefox/browsers/history/browser-history.ftl
Updates broken link to MDN `<blink>` reference in `browsers/browser-history`
The docs were removed from platform reference (as it's not a part of any living standard), but kept in glossary for posterity: https://developer.mozilla.org/en-US/docs/Glossary/blink_element
Fixes #15484
/firefox/browsers/browser-history/
=> Fix blink link

bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html, media/css/m24/components/navigation-refresh.scss
Adjusts the navigation logo size for both desktop and mobile. Also improves focus ring alignment.
#15477
Enable switch `M24_WEBSITE_REFRESH`
=> Increase navigation logo lockup size (Fixes #15477)

media/css/products/vpn/pricing-refresh.scss
Tiny tweak that adjusts spacing directly after the monthly amount for VPN pricing.
Before:
After:
#15463
http://localhost:8000/pt-BR/products/vpn/?geo=BR
=> Add spacer to VPN mobile pricing display (#15463)

bedrock/firefox/templates/firefox/welcome/page19.html, bedrock/firefox/templates/firefox/welcome/page20.html, bedrock/firefox/templates/firefox/welcome/page21.html, bedrock/firefox/templates/firefox/welcome/page22.html, bedrock/firefox/templates/firefox/welcome/page23.html, bedrock/firefox/templates/firefox/welcome/page24.html
The folks working on the root-ca-succession project have agreed that this feels like the more appropriate link for ESR users.
#15501
- http://localhost:8000/en-US/firefox/welcome/19/
- http://localhost:8000/en-US/firefox/welcome/20/
- http://localhost:8000/en-US/firefox/welcome/21/
- http://localhost:8000/en-US/firefox/welcome/22/
- http://localhost:8000/en-US/firefox/welcome/23/
- http://localhost:8000/en-US/firefox/welcome/24/
=> Update ESR link on /welcome/20/ page to link to /firefox/all/desktop-esr/ (Fixes #15501)

tests/functional/test_cdn.py
I am working with our vendor to resolve this remaining issue but it is a work in process. For now the expectation is that this client (Java version 6u45) cannot connect
https://mozilla-hub.atlassian.net/browse/OPST-1675
Basing this updating off the previously documented IE 6 failure based on the output from the GitHub Action https://github.com/mozilla/bedrock/actions/runs/11855059093/job/33038512250
=> fix(test_cdn): Update CDN TLS expectations

bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html, bedrock/mozorg/templates/mozorg/impact-report/index.html
Now that the 2024 report is finally published we no longer need this switch.
http://localhost:8000/impact/
=> Remove impact report switch logic [no bug]

bedrock/base/templates/includes/canonical-url.html, bedrock/base/templates/includes/protocol/lang-switcher-refresh.html, bedrock/base/templates/includes/protocol/lang-switcher.html, bedrock/base/templatetags/helpers.py, bedrock/base/tests/test_helpers.py, bedrock/cms/decorators.py, bedrock/cms/models/base.py, bedrock/cms/tests/conftest.py, bedrock/cms/tests/decorator_test_views.py, bedrock/cms/tests/test_decorators.py, bedrock/cms/tests/test_models.py, bedrock/cms/tests/test_rendering.py, bedrock/cms/tests/test_utils.py, bedrock/cms/utils.py, bedrock/products/urls.py, bedrock/products/views.py, docs/cms.rst
This changeset ensures that the language picker (and `canonical-url.html` header partial) remains accurate when a page is partly in Wagtail CMS and partly rendered via Django views.
This piece of work was like pulling at a loose thread on a sweater. It may look like there's a lot going on here, so I'll add notes on the Github diff where I think they'll help.
The `prefer_cms` decorator is applied to a regular Django view and will try to load the decorated URL path from the CMS first, then fall back to the original Django view. Previously, when a page came from the CMS, we would set the `translations` context variable to be a list of locales _available in the CMS only_, which had the downside that the language picker in the footer didn't mention the locales that were still available via the …
=> Provide a hybrid list of locales drawn from CMS-backed and Django-backed sources

bedrock/base/templates/macros-protocol.html, bedrock/mozorg/templates/mozorg/cms/about/blocks/leadership_block.html, bedrock/mozorg/templates/mozorg/cms/about/leadership.html, media/css/mozorg/leadership.scss, media/js/mozorg/about-leadership.js
- Fixes some minor a11y issues on the /leadership page.  
- Also removed the sub navigation from this page since it's empty and serves no purpose.
Note I filed a separate issue in Protocol for the incorrect aria role on the side menu: https://github.com/mozilla/protocol/issues/999
#15335
=> Leadership page a11y fixed (Fixes #15335)

bedrock/products/models.py
Renders VPN RC articles on the index page by `first_published_at` date, descending order. This should ensure that the most newly published articles appear first on the page, with the oldest at the bottom.
15517
1. Log into the CMS: http://localhost:8000/cms-admin/
2. Create a structural page with the slug of `products`.
3. Create a child structural page with the slug of `vpn`.
4. Create a child VPN resource center index page with a slug of `resource-center`.
5. Create a RC child page e.g. "Test page 1" and publish.
6. Create a RC child page e.g. "Test page 2" and publish.
7. Verify that "Test page 2" is rendered first on the index page, and "Test page 1" is last.
8. Bonus points for verifying that draft pages always go to the top of the list when published, irrespective of when they were …
=> Order VPN articles by first published date descending (Fixes #15517)

bedrock/settings/base.py
This changeset fixes the problem with the language picker on the CMS-powered VPN RC page, where selecting any language will redirect to en-US. 
It does this by lowering threshold for determining whether there is 'enough' VPN Content to justify an index page
(Settle in with a warm drink. This is a one-character code fix and a zillion characters of explanation.)
Back when the entire VPN RC was powered by Contentful, we added logic that would only allow the index page of the VPN RC to be displayed in a particular locale if there were 'enough' articles translated into that locale.
'Enough' was defined not as a specific threshold but as a percentage of the overall number of documents available in en-US.
Initially, this was fine, but as the number of documents in en-US grew the threshold failed …
=> Fix the language picker issue / inescapable redirect to en-US on the CMS-powered VPN Resource Center index page

bedrock/cms/tests/factories.py, bedrock/cms/tests/test_callbacks.py, bedrock/cms/wagtail_localize_smartling/__init__.py, bedrock/cms/wagtail_localize_smartling/callbacks.py, bedrock/settings/base.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This changset adds support for sending a visual context (a HTML document + relevant URL) to Smartling so that the CAT "live translation preview" tool can be used easily.
* Adds a callback for wagtail-localize-smartling to send visual context to Smartling
* Updates our `wagtail-localize-smartling` and `wagtaildraftsharing` dependencies, to enable the callback mentioned above to be used (and also to generate a useful URL with it)
Resolves #14938 
I've tested this with @cocomo over a Zoom call, so code-level review here is enough
=> Support sending visual context to Smartling, for its CAT tool

bedrock/base/templates/includes/canonical-url.html, bedrock/mozorg/templates/mozorg/credits-faq.html, bedrock/mozorg/views.py
This changeset reduces the number of pages containing a `link`  with `hreflang` of `x-default`. This change will improve/reduce harm to our SEO
You can test-drive this code on https://www-demo8.allizom.org/ - though note that all canonical urls there will refer to www.mozilla.org not www-demo8.allizom.org
To check/confirm:
Resolves #15464
=> Ensure we only use x-default on appropriate pages

bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html
Noticed a validation error in the springboard component due to an unmatched closing tag.
N/A
=> Fix unmatched closing tag in m24-c-springboard

bedrock/settings/__init__.py
Restricts `default-src` to just self _(as we otherwise append all the moz hostnames to the individual policies)_ and also restricts `object-src` to none. (All in `report-only` definition for now to confirm it's not needed.)
Adds `object-src: none` to report-only for helping out surface any hypothetical use.
Defines `default-src: self` in report-only for surfacing any unspecified defaults used in policies.
This doesn't mean everything would have to come from `self` now, the removed hosts are appended to every policy when constructing the settings, so this is only to restrict the defaults, i.e. in case we have not defined the policy (well/correctly/at all).
(This will be redone anyways regarding https://github.com/mozilla/bedrock/issues/11943#issuecomment-2255722632 when every policy gets …
=> Explore more CSP tightening (report-only)

media/css/m24/components/navigation-refresh.scss
Fixes spacing between main navigation menu items in older browsers
#15499
Tested in Chrome 59 on browser stack:
=> Fix navigation menu padding on older browsers (Fixes #15499)

bedrock/settings/__init__.py
Adds media-src CSP-RO rule to make up for RO-removed default-src wildcards.
Restricting defaults in #14897 may trigger some yet undefined policies, this specifically adds self+assets.m.o to media rules, to let it run in report-only for some time to see if that's the only host we need to add.
#15546
`curl -I http://localhost:8000/de/`
http://localhost:8000/de/firefox/built-for-you/?v=2
=> Add limited media-src CSP to report-only

bedrock/settings/__init__.py
Follows up from #15548 adding another host serving videos to add to media-src policy recently added to take precedence over default-src wildcard fallbacks.
This is a new addition, so instead of allowing all the default hosts we're trying to explicitly define the sources (and/or paths if needed) to have an exhaustive list of known media hosts being used around the site.
#15546
curl -I http://localhost:8000/de/
=> Add cdn videos to report-only CSP media-src

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-donation.html
This PR removes a word per stakeholder request. 
This should have been removed in https://github.com/mozilla/bedrock/pull/15509/commits/482c9fb3d03ef3717609a37fe214d8c9e6d1e5a3. It was missed.
https://github.com/mozilla/bedrock/issues/15487
http://localhost:8000/de/firefox/133.0/whatsnew/?v=2&geo=CA
=> remove word per stakeholder request fix (#15485, #15486, #15487)

media/css/m24/base.scss, media/css/m24/root.scss, media/css/protocol/protocol-mozilla-2024.scss
After some progress on #15397 we decided to eschew variable fonts for the time being, but we still need to switch to semibold for headlines to match current designs. 
I also updated the font stack; I think sans-serif is a better fallback for the semi-slab Mozilla Headline and couldn't really find a suitable serif system font.
=> Refresh: update the font stack and headline weight

bedrock/firefox/templates/firefox/nothing-personal/index.html
"personal" -> "private"
#15558 
=> Copy fix for nothing personal page [fix #15558]

media/css/m24/base.scss, media/css/m24/careers.scss, media/css/m24/components/footer-newsletter.scss, media/css/m24/components/footer-refresh.scss, media/css/m24/components/navigation-refresh.scss, media/css/m24/components/pencil-banner.scss, media/css/m24/donate.scss, media/css/m24/feature.scss, media/css/m24/flag.scss, media/css/m24/gallery.scss, media/css/m24/intro.scss, media/css/m24/launchpad.scss, media/css/m24/root.scss, media/css/m24/showcase.scss, media/css/m24/springboard.scss, media/css/m24/theme.scss, media/css/m24/transition.scss, media/css/m24/vars/_grid.scss, media/css/m24/vars/_lib.scss
- Removes use of `@import` in website refresh stylesheets.
- Migrates to using `@use` and `@forward` instead.
#15545
Ensure switch M24_WEBSITE_REFRESH is ON
=> Stop using @import in m24 Sass styles (Fixes #15545)

bedrock/cms/tests/test_callbacks.py, bedrock/cms/wagtail_localize_smartling/callbacks.py, bedrock/settings/base.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This changeset updates our `wagtail-localize-smartling` "visual context" callback to fail gracefully (and with the expected custom exception) when it syncs over a content object (e.g. a Snippet) that has no standalone visual context.
Prior to this change, syncing a Snippet would cause the job to fail and create an inconsistent state between Wagtail and Smartling that needed manual cleanup
https://github.com/mozilla/wagtail-localize-smartling/issues/40
I've tested locally - code-eyes are enough right now
=> Fix failing job when syncing with smartling

bedrock/settings/__init__.py
This PR adds the `upgrade-insecure-requests` directive to our report-only Content Security Policy (CSP). The `upgrade-insecure-requests` directive automatically upgrades `HTTP` requests to `HTTPS`, helping enforce secure communication for all resources while ensuring compatibility with legacy HTTP links.
#15556 
* Verify the addition of the `upgrade-insecure-requests` directive in the report-only CSP header locally. To do this we need to set a couple local env vars:
* DEBUG=False - CSP headers aren't added while in DEBUG mode
* CSP_RO_REPORT_URI=/csp-violation - the report-only header will only be added if this is set.
=> Add `upgrade-insecure-requests` directive to report-only CSP

bedrock/mozorg/templates/mozorg/cms/about/blocks/leadership_block.html, bedrock/mozorg/templates/mozorg/cms/about/leadership.html, media/js/mozorg/about-leadership.js
- Change `<article>` landmark to a regular `<div>` since `role` is applied.
- Start using `aria-controls` and `aria-expanded`.
- Also fixes a heading level issue.
#15538
I tested this with prod CMS data: https://bedrock.readthedocs.io/en/latest/cms.html#fetching-the-latest-cms-data-for-local-work
Running a11y tests should not generate a report for the leadership page after this fix:
- `npm start`
- `cd tests/playwright`
- `npm run a11y-tests`
I also tested this with VoiceOver on macOS to make sure things seemed to make sense.
=> Fix invalid role on /leadership modal links (fixes #15538)

bedrock/base/templates/base-protocol-mozilla.html, bedrock/base/templates/base-protocol.html, bedrock/base/templates/includes/banners/pencil-banner.html, bedrock/base/templates/includes/protocol/footer/footer.html, bedrock/base/templates/includes/protocol/navigation/navigation.html, bedrock/firefox/templates/firefox/new/basic/base.html, bedrock/firefox/templates/firefox/new/desktop/base.html
Updates the template logic to show global elements when their corresponding Fluent files are active, rather than explicitly for English only.
#15570 
Run `./manage.py l10n_update` to get latest Fluent files, if you haven't lately.
Flip switch `M24_WEBSITE_REFRESH` on
You should see the nav, footer, and pencil banner on localized pages for most tier 1 languages (I've verified de, fr, es-ES, it, and a few others). 
Other locales should fall back to the old content in prod mode (I've been using be and ro to test). In dev mode you'll still see the new elements in English.
=> Refresh: show nav, footer, and banner when translations are available [fix #15570]

bedrock/base/templates/includes/banners/fundraiser.html, bedrock/mozorg/templates/mozorg/home/home-new.html, bedrock/mozorg/templates/mozorg/home/home-old.html
Adds a few more languages to the Giving Tuesday donation banner.
#15527
Disable switch `M24_WEBSITE_REFRESH`
- http://localhost:8000/es-ES/?v=a
- http://localhost:8000/es-ES/?v=b
- http://localhost:8000/es-ES/?v=c
- http://localhost:8000/es-MX/?xv=legacy&v=a
- http://localhost:8000/es-MX/?xv=legacy&v=b
- http://localhost:8000/es-MX/?xv=legacy&v=c
- http://localhost:8000/it/?v=a
- http://localhost:8000/it/?v=b
- http://localhost:8000/it/?v=c
- http://localhost:8000/pl/?xv=legacy?v=a
- http://localhost:8000/pl/?xv=legacy?v=b
- http://localhost:8000/pl/?xv=legacy?v=c
- http://localhost:8000/pt-BR/?v=a
- http://localhost:8000/pt-BR/?v=b
- http://localhost:8000/pt-BR/?v=c
=> Add more languages for Giving Tuesday banner (Fixes #15527)

bedrock/products/templates/products/vpn/download.html
Bumps supported version number for VPN on iOS from 14.0 to 15.0
#15581
http://localhost:8000/en-US/products/vpn/download/
=> Bump VPN minimum requirements for iOS 15.0 and up (Fixes #15581)

bedrock/mozorg/templates/mozorg/home/includes/m24/ai-gallery.html
Fix string ID typo in homepage gallery
=> Fix string ID typo in homepage gallery

bedrock/cms/apps.py, bedrock/cms/signal_handlers.py, bedrock/cms/templates/cms/email/notifications/translation_imported__body.txt, bedrock/cms/tests/test_signal_handlers.py
This will probably be a little spammy to start with - emailing each admin once per locale per page/snippet translated, but we will improve this with something custom on the dashboard soon
Resolves #14934 
I've tested locally, connected to our sandbox Smartling account. Here's an example of the email
```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: New translations imported into Bedrock CMS
From: Mozilla.com <noreply@mozilla.com>
To: REDACTED@mozilla.com
Date: Thu, 28 Nov 2024 13:50:37 -0000
Message-ID: <173280183731.63371.2651772802465437955@md2kgyj3pw.local>
Hi there
ACTION REQUIRED: A new translation has been synced back from Smartling
and needs to be published.
It is Job '050f0d53-71f5-4ce4-8d68-941e6383c74e:1:es-ES:2024-11-28T13:3 …
```
=> Trigger an email to admins each time a translation lands back in in the CMS

bedrock/cms/templates/cms/email/notifications/translation_imported__body.txt, bedrock/settings/base.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This changeset makes Smartling job titles easier for translation managers to scan by providing a custom prefix (support for which just landed in wagtail-localize-smartling 0.7.0)
It also fixes a typo in the email template that should have been in an earlier PR
Tested locally - here's a screenshot from our Smartling sandbox
=> Support mozorg-specific prefix on Smartling job titles via CMS

bedrock/settings/__init__.py
No `<base href>` is being used around the site, so this makes sure no malicious code can tamper with relative links. (Once moved from report-only; this is to surface any potential issues first.)
> "Ensures that all relative URLs resolve to trusted origins, maintaining control over URL resolution behavior. Protects user experience and data by preventing exploitation of relative links."
— _Originally posted by @janbrasna in https://github.com/mozilla/bedrock/issues/15555#issuecomment-2495495198_:
> "There don't seem to be any `<base>` elements set visibly from a quick search, and I also don't recall any env settings to inject it for some deployments (e.g. don't see it being used even in `test.bedrock.nonprod.webservices.*`) so the goal is perhaps to set it to `'none'`, right?
> The public …
=> Restrict base-uri in report-only CSP

media/js/firefox/whatsnew/whatsnew-events.js
Adds an extra check to silence a small number of errors we're seeing in Sentry (likely from people on slow / intermittent connections when loading the WNP).
https://mozilla.sentry.io/issues/5349155168/events/?project=6260331
N/A
http://localhost:8000/en-US/firefox/133.0/whatsnew/
=> Add check for Mozilla.Cient in whatsnew-events.js

bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, bedrock/mozorg/templates/mozorg/home/includes/m24/products.html, l10n/en/brands.ftl, l10n/en/mozorg/home-m24.ftl, media/css/m24/components/navigation-refresh.scss, media/css/m24/components/pencil-banner.scss, media/css/m24/launchpad.scss
* Change Mozilla AI to Mozilla.ai [fix #15606]
* Add Relay to products list [fix #15586]
* Update close button style
* Constrain dropdown width
* Add transition to all category link arrow
* Remove underlines from links (hover only)
* Fix mobile category titles
* Use small icons
* RTL fixes
#15564 
#15586 
#15606 
Make sure the main nav looks right and isn't broken?
=> Refresh: nav tweaks [fix #15564]

bedrock/firefox/templates/firefox/built-for-you/landing.de.html, bedrock/firefox/templates/firefox/built-for-you/landing.fr.html, bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html, bedrock/firefox/templates/firefox/developer/firstrun.html, bedrock/firefox/templates/firefox/developer/whatsnew.html, bedrock/firefox/templates/firefox/family/index.html, bedrock/firefox/templates/firefox/nightly/firstrun.html, bedrock/firefox/templates/firefox/nightly/whatsnew.html, bedrock/firefox/templates/firefox/nothing-personal/index.html, bedrock/firefox/templates/firefox/welcome/base.html, bedrock/firefox/templates/firefox/whatsnew/base.html, media/css/firefox/developer/whatsnew-mdnplus.scss, media/css/m24/components/footer-refresh.scss, media/css/m24/components/navigation-refresh.scss, media/css/m24/components/pencil-banner.scss
Keeps Firefox branding on whatsnew, welcome, and campaign pages (mainly for the fonts).
This is admittedly a bit hacky and loads extra fonts so it's a performance hit, but doing it "properly" would probably entail a more significant refactoring of the nav and footer as well as some global styles. We should tackle that at another time. 
#15542
Test a handful of whatsnew and welcome pages with the M24_WEBSITE_REFRESH switch on; make sure the text is rendered in Metropolis and Inter. The footer should use the new Mozilla fonts (only English gets the new footer; other languages get the old footer for now).
http://localhost:8000/firefox/125.0/whatsnew/
http://localhost:8000/firefox/132.0/whatsnew/
http://localhost:8000/firefox/133.0/whatsnew/
http://localhost:8000/firefox/welcome/1/ …
=> Refresh: use Firefox brand fonts on some Firefox pages [fix #15542]

bedrock/base/templates/includes/banners/pencil-banner.html
Removes hard coded locale in donation link
https://github.com/mozilla/bedrock/issues/15592
=> Remove locale from pencil banner donate link (Fixes #15592)

media/css/m24/components/navigation-refresh.scss, media/static-bundles.json
This PR fixes styles issue for M24 navigation.
- The gap between dropdown menu and nav bar on desktop layout is closed off
- the extra thick border between menu and nav bar on mobile is fixed
https://github.com/mozilla/bedrock/issues/15623
=> fix nav position and mobile border issue (fix #15623)

bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, media/css/m24/launchpad.scss
Updates old "black hex" Relay logo to currently used "purple hex" in both homepage launchpad and products submenu.
The proper fix is upstream in https://github.com/mozilla/protocol-assets/issues/87 — or a local asset can be added here in logos to override it temporarily… but there's a viable asset available already.
This is a rather ugly workaround temporarily using [`logo-white.svg`](https://github.com/mozilla/protocol-assets/blob/a99bd40321cde692479d03dcc619a215ef3890a0/logos/firefox/relay/logo-white.svg) instead of [`logo.svg`](https://github.com/mozilla/protocol-assets/blob/a99bd40321cde692479d03dcc619a215ef3890a0/logos/firefox/relay/logo.svg) that has already been done here before from time to time (I know it's _de iure_ designed to be used on dark backgrounds, but it gets the job …
=> Refresh: Update launchpad & submenu Relay logo

bedrock/firefox/templates/firefox/developer/includes/for-developers.html
Removes nonexistent fallback string id.
Obsolete string got removed in [`d08bd22`](https://github.com/mozilla/bedrock/commit/d08bd22c02035bde6328648218b2f9484fb6708d#diff-8f44c0404c88ee1d6aa7167be523aed452b0f7cf2a9c006f99965362d47856a7L81-L84) — but left in the template.
🚫🐞
/en-US/firefox/developer/
=> Fix missing for-developers ftl fallback

media/css/m24/components/navigation-refresh.scss
This PR updates the navigation menu item underline to be visible on hover.
- menu item underline only shows up when hovering
- icon will not be included in the underline section
https://github.com/mozilla/bedrock/issues/15622
=> update navigation menu item underline (fix #15622)

bedrock/mozorg/redirects.py, bedrock/mozorg/templates/mozorg/home/includes/m24/ai-gallery.html, tests/redirects/map_globalconf.py
Updates future.mozilla.org/builders link and relevant redirects to builders.mozilla.org
https://builders.mozilla.org is up now so this is good to go.
#15613
http://localhost:8000/builders/
=> Update builders.m.o location

bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html, media/css/m24/components/navigation-refresh.scss
Change nav tray widths again
- left align logo with content on extra wide screens
- left align products & about menus with logo
- keep small intent on about menu
- add spacer to center menu
n/a
=> Refresh: change nav tray widths again

tests/functional/test_navigation.py, tests/playwright/specs/a11y/components/navigation.spec.js, tests/playwright/specs/footer.spec.js, tests/playwright/specs/navigation.spec.js
This should temporarily skip nav / footer tests until the website refresh has launched in prod. At that point we can update tests for the newly added components.
#15625
=> Temporarily skip nav / footer tests for m24 launch (Issue #15625)

bedrock/careers/management/commands/sync_greenhouse.py
This bleaches inline styles in Greenhouse API sync, to avoid unsafe-inline style CSP violations (and unblock moving that to enforced policies…)
Currently almost all the styles from the original listing data (align, color etc.) are removed already, leaving only either empty `style=""` behind, or a `font-weight: 400` that is the default anyways. So it can be removed completely.
(It will have to go through data sync cron first to update in prod.)
Resolves #15633 (& refs #14840)
`python manage.py sync_greenhouse`
(in my case, in containerized env, it was actually `make clean build run` followed by `make shell` in another session with the management command run from there…)
http://localhost:8000/en-US/careers/position/gh/6135741/
http://localhost:8000/en-US/careers/position/gh/6393976/
=> Remove inline styles from job listings

media/css/m24/components/footer-refresh.scss
This PR updates the footer legal section styles to allow same space before and after legal section.
- Footer legal section spaces
https://github.com/mozilla/bedrock/issues/15659
- Test for various screen sizes
=> same space before and after legal section in footer (fix #15659)

media/css/firefox/browsers/mobile.scss
When on `.ios` or `.android` the send-to-device form is hidden, making the 2col split with just empty space in 50% of the screen feel like a bug. This overrides the split to a single column to make better use of the space (esp. on mobile).
For cases when the form is hidden (making the second column empty), this additionally:
1. resets the grid/display for MD+ breakpoints
2. and also constraints the width in LG+ to be able to keep the noodle graphics but not overflow into it (too much).
Resolves #15648
http://localhost:8000/hi-IN/firefox/browsers/mobile/focus/
http://localhost:8000/ar/firefox/browsers/mobile/android/
http://localhost:8000/el/firefox/browsers/mobile/ios/
(compare desktop vs. mobile device or spoof the uastring to include "android" and "mobile", portrait vs. landscape mode …
=> Streamline fx mobile grid with one column hidden

media/css/m24/components/footer-refresh.scss
This PR fixes the horizontal bar that are present for certain screen sizes
- screen sizes to check: 768 & 1024
- Both `ltr` and `rtl` reading directions
https://github.com/mozilla/bedrock/issues/15596
=> fix horizontal bar at certain screen size (fix #15596)

media/css/m24/components/navigation-refresh.scss, media/css/m24/gallery.scss, media/css/m24/launchpad.scss, media/css/m24/root.scss
Some fonts were too wee on mobile. This bumps a few things up a size and also sets the small button size to 14px.
Also switches to the Mozilla Text font for descriptionless gallery tiles when the text shrinks (seen on the about page).
#15667 
Primarily impacts mobile so test on small viewports, but also make sure nothing breaks on desktop.
=> Refresh: embiggen some font sizes [fix #15667]

bedrock/base/templates/includes/protocol/footer/footer-refresh.html
Adds `TikTok (@firefox)` social account to footer.
Added it to the last position (to align with its fourth position in `@Mozilla` above) without thinking too much whether it should go before of after YT etc.
Resolves #15692
=> Add fx tiktok link to footer

media/css/m24/components/footer-newsletter.scss, media/css/m24/components/footer-refresh.scss
Adds column-gap in footer nav and increases spacing around newsletter logo.
The spacing was not sufficient for mobile layouts. This updates the spacing for all breakpoints, as it seems more appropriate to keep the same spacing size variable, and let it adapt according to atmedia calculations/adaptations at root level.
https://github.com/mozilla/bedrock/issues/15635#issuecomment-2515236569
Also fixes #15598
http://localhost:8000/en-US/#colophon
=> Update footer spacing

media/css/firefox/browsers/mobile.scss
A low effort last-minute addition created a visual regression for RTL languages in a corner case when `bidi()` mixin doesn't cover it; this adds the necessary pseudo manually. (Sorry.)
The edge case that tripped me up is reported upstream:
- https://github.com/mozilla/protocol/issues/1008 (not sure if currently actionable given `:dir()` support and different logic per se, but might be worth documenting how it works under the hood perhaps to ack this limitation)
This instead of relying on `html[dir=rtl] *` does `html :dir(rtl) *` picking up _any_ naturally occurring RTL node along the way no matter what the document sets — so while achieving the same it uses completely different logic. Shouldn't cause any extra trouble, but worth noting nonetheless.
(NB: This rule is basically only for …
=> Fixup RTL noodle background for landscape mobile/tablet

media/css/m24/components/navigation-refresh.scss, media/css/protocol/components/_sub-navigation.scss
Narrow nav menu drop downs
- give drop downs a max-width of 680px (6 columns at 1440px)
- centre them under their link
- remove the indent from the about drop down
- adds a drop shadow and border to the drop downs when menu is sticky
Fix #15708
- have a look on both home and about to make sure it stands out on black and white
- changes should only affect desktop, not mobile
- check sticky changes to
=> Refresh: narrow nav menu (Fix #15708)

bedrock/firefox/templates/firefox/nightly/whatsnew.html, l10n/en/firefox/nightly/whatsnew.ftl
The Firefox Nightly account was migrated to mastodon social.
Update of the link on out Whatsnew page.
=> Update mastodon server for FirefoxNightly account

.github/workflows/build-and-push.yml
=> chore(githubAction): add build workflow initial work for argocd move

bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html, l10n/en/mozorg/home-m24.ftl
Adds alt text to the SVGs following Pattern 5 from Deque: https://www.deque.com/blog/creating-accessible-svgs/
text based on description of flag significance from refresh blog: https://blog.mozilla.org/en/mozilla/mozilla-brand-next-era-of-tech/
Fixes parsing error from Chrome
N/A
Go to http://localhost:8000/en-US/ in Chrome and confirm you do not see errors in console
Using accessibility dev tools confirm you can see alt text on the SVGs
=> Fix parsing error on flag SVG, add titles for alt text

bedrock/base/templates/includes/protocol/footer/footer-newsletter.html, l10n/en/footer-refresh.ftl, media/css/m24/components/footer-newsletter.scss
Update footer newsletter signup to include foundation newsletter as well
mozilla-and-you and mozilla-foundation
Footer newsletter now has two newsletter sign up options
Couple of styling challenges that should be fixed now (and have hopefully not created new issues)
general spacing
large font
- removed explicit grid rows in favour of auto row placement (more resilient with large font
- updated p spacing 
https://github.com/mozilla/bedrock/issues/15585
Go to http://localhost:8000/en-US/ and confirm the newsletter expands with 2 newletters checked: firefox & mozilla foundations
Uncheck both newsletters and confirm you cannot sign up without selecting at least one
Check newsletters and confirm you get thanks message and network tab shows request with expected newsletters
=> Update footer newsletter text and signups (fixes #15585)

bedrock/mozorg/templates/mozorg/contact/contact-landing.html, bedrock/mozorg/templates/mozorg/contact/includes/tab-nav.html
This PR addresses the accessibility issues outlined in [Issue #15339](https://github.com/mozilla/bedrock/issues/15339).
Axe-core violations and changes:
1. ARIA role should be appropriate for the element: Removed `role="navigation"` from `<ul class="category-tabs" role="navigation">`, since "ARIA role navigation is not allowed for given element."
2. Heading levels should only increase by one: Changed `<h4>` tags to `<h3>`, since last heading level was `<h2>`.
3. `<li>` elements must be contained in a `<ul>` or `<ol>`: Wrapped the `<ul>` in a `<nav>` element to ensure semantic structure and proper roles, since "List item parent element has a role that is not role="list"."
Fixes [#15339](https://github.com/mozilla/bedrock/issues/15339)
Used browser Inspector tools and performed manual …
=> Fix: Accessibility issues on contact page

media/css/m24/components/footer-refresh.scss
Avoids using "visited" purple color for Donate CTA in footer of fx base pages.
The color was only set on anchor, not :link — and in m24 base styles the :link generally defines white color — something not present in fx styles, where the visited purple treatment is then applied to this CTA.
Moving the CTA color from anchor to :link/:visited is the easiest fix. I don't see anything that can be negatively impacted by missing the white color on the anchor proper, and just defining it for the pseudos, but felt it's worth noting nonetheless.
Fixes #15701 
http://localhost:8000/en-US/firefox/133.0/whatsnew/#colophon
http://localhost:8000/en-US/firefox/welcome/10/#colophon
(Click the Donate button in the footer so it's marked as visited.)
=> Fix footer donate visited color

l10n/configs/pontoon.toml
Adds `scn` to Pontoon so the community can start localizing strings. This won't activate the locale in production; that should happen later once it reaches some threshold of completeness.
#15728
=> Add scn (Sicilian) to pontoon.toml [fix #15728]

bedrock/base/templates/includes/protocol/footer/footer-refresh.html, bedrock/base/templates/includes/protocol/footer/footer.html
Removes the brand standards link until we have an adequate replacement. I didn't mark the string as obsolete because I expect we'll be able to replace the link in the near future and it'll be good to keep that string around.
#15647 
http://localhost:8000/#colophon
It may be hard to get to the old footer in dev mode but you can switch off M24_WEBSITE_REFRESH locally to verify.
=> Remove brand standards link from footer [fix #15647]

bedrock/mozorg/templates/mozorg/home/includes/m24/showcase-som.html
Copypasta error introduced a double slash, which resolved fine on localhost but isn't working elsewhere so we didn't notice until it hit dev/stage/prod.
=> Fix home SoM image paths [#15727]

media/css/foundation/annual-report-2024.scss
Tweak headings in two columns in SoM
- added `text-wrap-style: balance`
- added a small gutter on the first column headings to for them to wrap before they get too close to the second column
n/a
The problem is most obvious here: 
http://localhost:8000/en-US/foundation/annualreport/2024/#products
=> SOM: Tweak headings in two columns

bedrock/privacy/templates/privacy/base-protocol.html, bedrock/privacy/templates/privacy/index.html, media/css/privacy/privacy-protocol.scss
- Fixes heading level in privacy footnote
- Moves `<main>` landmark to be top level.
#15343
http://localhost:8000/en-US/privacy/
=> Fix a11y issues on /privacy/ page (Fixes #15343)

bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
Fixes a couple of small validation errors I spotted in the new navigation:
1. Removes duplicate `class` attribute on the small Firefox icon in the main menu titles (it looks like `m24-c-menu-item-icon` is not needed here, so safe to remove?)
2. Fixes missing space between attributes on the pocket menu item link.
N/A
=> Fix validation errors in navigation

tests/playwright/specs/a11y/components/navigation.spec.js, tests/playwright/specs/a11y/includes/helpers.js
Ignores the `<blink>` element in navigation a11y scan.
N/A
=> Ignore <blink> element in navigation a11y scan

media/css/l10n/ar/intl.css, media/css/m24/base.scss, media/css/m24/careers.scss, media/css/m24/gallery.scss
RTL audit and fixes
- Don't use our fonts in Arabic
- Animate the line under CTAs in the reverse direction for RTL
- Alignment fixes
#15416
=> Refresh: RTL audit and fixes

bedrock/mozorg/templates/mozorg/about/includes/m24/careers.html, bedrock/mozorg/templates/mozorg/about/includes/m24/community.html, bedrock/mozorg/templates/mozorg/about/includes/m24/news.html, bedrock/mozorg/templates/mozorg/home/includes/m24/ai-gallery.html, bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html, bedrock/mozorg/templates/mozorg/home/includes/m24/issues-gallery.html, bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py, docs/coding.rst, media/css/m24/gallery.scss
Update picture helper, image sizes and loading, tweak gallery cta text.
- edit picture helper to accept height and width on sources
- update tests for picture helper
- add height and width to images on home and about
- double check lazy loading values
- tweak font size on gallery tiles with no description (about news section)
- tweak font weight on gallery cta
Fix #15678
Fix #15621 
#15416 
I was testing by using Firefox's "screenshot full page" feature before scrolling. That shows the empty places reserved for images that lazy load. That way I could check that 1) images that should lazy load had not loaded and 2) the space reserved was roughly the right dimensions.
Using the network panel to cut off your network connection after initial page load might be a good way to do it too. It's …
=> Update picture helper, image sizes and loading, tweak gallery text

media/css/m24/components/footer-newsletter.scss, media/css/m24/components/footer-refresh.scss, media/img/icons/m24-small/up-caret.svg
This PR expands footer lang switch to avoid cutting off long word.
- Footer lang switch shouldn't be cutting off any language
https://github.com/mozilla/bedrock/issues/15609
In order to avoid cutting off any language, the select is quite long and it looks kind of broken when no hovered. 
Same approach worked on the older footer cause the district background color made it clear that the triangle is part of the select dropdown. Might wait when the designer is back for some design tweaks on this.
Tess's take on this:
- default border for the select
- on hover, inverse the colors: black text on white background
=> Expand footer lang switch to avoid cutting off long word (fix #15609)

bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html, media/css/m24/base.scss
Changes c-cta (text-button) size from XL to LG, adding XL as an available theme variant.
This updates all occurrences such as section-cta, donate-cta, flag-cta, careers-cta or feature-cta…
Resolves #15707
=> Make section CTAs smaller

bedrock/firefox/templates/firefox/features/translate.html, l10n/en/firefox/features/translate.ftl
Treat "Firefox Translations" as a single product name in Fluent strings.
- This is the contents of https://github.com/mozilla/bedrock/pull/15459 with the addition of some versioning
- Updated instances of `{ -brand-name-firefox } Translations` to `{ -brand-name-firefox-translations }` in relevant files.
- Ensured consistency by using the pre-defined `{ -brand-name-firefox-translations }` entry from `brands.ftl` across all strings.
- Verified that the changes align with the Fluent localization standards for product naming.
Resolves [Issue #15442](https://github.com/mozilla/bedrock/issues/15442)
- Manually checked that each modified string renders "Firefox Translations" as a single entity in the UI.
- Confirmed the updated strings in different localization scenarios to ensure they display …
=> Use consistent product name for 'Firefox Translations' in Fluent (Fixes #15442)

media/css/m24/components/pencil-banner.scss
This PR vertically centers the pencil banner close button.
Pencil banner close button on various screen sizes, rtl reading direction
https://github.com/mozilla/bedrock/issues/15674
=> vertically center pencil banner close button (fix #15674)

bedrock/base/templates/includes/protocol/navigation/menus/firefox.html, bedrock/firefox/templates/firefox/all/base.html, bedrock/firefox/templates/firefox/all/lang.html, bedrock/firefox/templates/firefox/all/platform.html, bedrock/firefox/templates/firefox/all/product.html, bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html, bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.de.html, bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.es-ES.html, bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.fr.html, bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.it.html, bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.pl.html, bedrock/firefox/templates/firefox/features/adblocker.html, bedrock/firefox/templates/firefox/nightly/whatsnew.html, bedrock/newsletter/templates/newsletter/firefox.html, bedrock/newsletter/templates/newsletter/includes/form.html, l10n/en/firefox/all.ftl, l10n/en/firefox/features/adblocker.ftl, l10n/en/firefox/nightly/whatsnew.ftl, l10n/en/mozorg/newsletters.ftl, l10n/en/navigation.ftl, l10n/en/newsletter_form.ftl
L10n maintenance
- removed obsolete strings which have expired
- discovered CTD templates were referencing a string ID that had been removed, took the translations off prod and hard coded them like the other strings in the CTD templates
Fix #15496
Do a `make preflight` to make sure you have the most recent translations.
http://localhost:8000/fr/firefox/all/
http://localhost:8000/fr/firefox/features/adblocker/
http://localhost:8000/fr/firefox/135.0a1/whatsnew/
http://localhost:8000/fr/newsletter/firefox/
http://localhost:8000/de/firefox/challenge-the-default/
http://localhost:8000/fr/firefox/challenge-the-default/
http://localhost:8000/es-ES/firefox/challenge-the-default/
http://localhost:8000/it/firefox/challenge-the-default/
http://localhost:8000/pl/firefox/challenge-the-default/
=>  Remove obsolete l10n strings (Fix #15496) 

bedrock/settings/__init__.py
This PR adds the upgrade-insecure-requests directive to our Content Security Policy (CSP). This directive automatically upgrades HTTP requests to HTTPS, improving security by ensuring all content is loaded over a secure connection.
This has been in our report-only policy with no issue detected.
#11943
=> Update CSP to move `upgrade-insecure-requests` to enforced policy

bedrock/settings/__init__.py
The `frame-ancestors: 'none'` directive prevents the site from being embedded in any `<iframe>`, `<object>`, or `<embed>` elements, mitigating clickjacking attacks.
This directive has been running in report-only mode, generating reports without enforcing the policy. The reports show no valid embedding attempts, confirming that the directive will protect the website without breaking any legitimate use cases.
#11943
=> Promote CSP `frame-ancestors` directive

bedrock/settings/__init__.py
This broke local dev on Safari but Firefox ignores it for localhost. So we can just not include this CSP directive when DEBUG=True.
#15556
=> Disable `upgrade-insecure-requests` for local dev

media/css/base/banners/firefox-app-store.scss
Clips any overflow so that page width doesn't change.
(Fixes broken RTL product pages on mobile chromium.)
Tried to trace the viewport width to something moving far left, e.g. "image-replaced" or "visually-hidden" -9999px etc. but wasn't able to find the actual culprit (to perhaps change that to bidi or inline-start syntax). This instead makes sure the banner is contained in its box for good measure, which also gets the job done, with not much risk of breaking somewhere.
Resolves #15715
_(webkit+chromium, banner displayed i.e. not dismissed and on detected mobile device etc.)_
http://localhost:8000/ar/firefox/
http://localhost:8000/ar/firefox/mobile
http://localhost:8000/ar/firefox/focus
http://localhost:8000/ar/firefox/android
http://localhost:8000/ar/firefox/ios
=> Fix RTL pages with firefox-app-store banner

.github/workflows/build-and-push.yml
Only run from this repo.
While the repo is already set in `env`, the `jobs.[id].if` context doesn't surprisingly have access to it 🤦 so it's hardcoded (again).
Resolves #15804
https://github.com/janbrasna/bedrock/actions/runs/12633383014 (status: skipped)
=> Skip GHA GAR push from forks

bedrock/sitemaps/tests/test_utils.py, bedrock/sitemaps/utils.py
This changeset fixes a bug where, when generating the list of URLs to pass to the sitemap generator, we were over-replacing the locale code in the string. 
Instead of just turning `/es/some/pages/` into `/some/pages/` we were replacing all occurences of the lang code, giving us a result like `/some/pag/` which would 404.
Now we're much more focused on replacing only the first occurrence of the lang code in the URL, and only if it's wrapped in `/` - see the tests.
Resolves #15805
Tests passing is enough for this - please review them and feel free to challenge them
=> Fix extraction of paths from CMS for the sitemap 

bedrock/firefox/templates/firefox/welcome/page21.html
Consistently use the same title as is the main message heading for page21 (that's otherwise the case of page19, page20 & page22), to avoid any ambiguity.
While not incorrect per se, the two dates _("… **may** start to have problems Jan…" with "… **won’t work** properly Mar…" kinda complement each other)_ have different reasoning — January being concern only for some super-old Fx that will lose access to remote-settings next week, way before the actual root cert expiration begins, so the issue is those clients won't get any future planned moments rollouts to warn them as March gets closer. That demographic was targeted by page20, not page21 (as confirmed by the OP who got page21 in ESR 115.x, that won't stop connecting to mothership in Jan, so the confusion is justified.)
Fixes #15818 …
=> Fix confusing Jan 14 root cert moments title of Mar 14 page content

bedrock/base/templates/includes/protocol/footer/footer-refresh.html, bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html, bedrock/base/templates/macros.html, l10n/en/footer-refresh.ftl, l10n/en/navigation_refresh.ftl
Simplifies our main landmark structure for easier navigation.
Before:
- Promotion complimentary
- navigation
- navigation
- main
- content
- footer primary navigation
- footer secondary navigation
After:
- Promotion complimentary
- Primary navigation
- Firefox navigation
- main
- content
#15814
I tested this using VoiceOver on macOS.
1. Command + F5 to start VoiceOver
2. Control + option + U to enter rotator (landmarks should be the first element type).
https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts
=> Improve top level landmarks (Fixes #15814)

media/css/m24/components/footer-refresh.scss, media/css/m24/launchpad.scss
Resolves home launchpad & colophon RTL alignment, most visible on smaller screens.
Uses logical/flow values where related to surrounding text, but still keeps mzp bidi in cases where it interacts with different parts of layout on left and right specifically.
Fixes #15794
_(best shown <1024 px)_
http://localhost:8000/he/
http://localhost:8000/ar/
=> Fix RTL launchpad & links padding

media/css/m24/components/footer-refresh.scss
Reuses normally invisible "All locales" link from a11y progressive enhancement to also serve as a graceful degradation for switching languages.
Currently only utilized for keyboard navigation. Repurposing that as a generic nonJS access to locales seems worth it.
While the actual locale overview page is slated for removal at some point (perhaps to be replaced with a flavor of 404-locale view that exists elsewhere), as long as it's available it's a viable nonJS route for changing languages that was already there anyways.
Improves #15201
Disable JS, fail `cutsTheMustard()`, or deny loading `*.js` resources.
(no change for normal, JS-enabled consumption)
=> Expose "all locales" link in nonJS

bedrock/newsletter/templates/newsletter/recovery.html, bedrock/newsletter/views.py, media/js/newsletter/form-utils.es6.js, media/js/newsletter/recovery.es6.js, tests/unit/spec/newsletter/form-utils.js, tests/unit/spec/newsletter/recovery.js
In basket the `/api/v1/users/recover/` is a new JSON-only API. This updates the newsletter recovery page to switch to this, POSTing a JSON body instead of form-urlencoded.
- Added the `postJsonToBasket` function. Future APIs can use this as we add more endpoints
- Added the `serializeToJson` helper, similar to `serialize` but returns a JSON object.
No issue, but part of https://github.com/mozmeao/basket/issues/1530
Verify the recovery form works as before.
=> Update newsletter recovery to use new JSON API

media/css/m24/flag.scss
As discussed with Tess, we'd like to keep the text visible on smaller screens to provide toggle animation button label
The above decision also helps make the label more visible for Windows High Contrast Mode
We also want to ensure the button is not overlapped by the sticky nav when focused
Other approaches considered for icon-only toggle animation button label:
- animated text reveal on hover
- custom tooltip
- HTML title attribute
Overall, the visible text label felt simplest and most accessible
Other approaches considered for focused button visibility:
- set custom property with sticky navigation height and use scroll margin to keep focused button below the sticky nav (this did not work when banner was also on page)
https://github.com/mozilla/bedrock/issues/15762 …
=> Fix Animation button accessibility issues (fixes #15762, #15763, #15764)

media/css/careers/_utils.scss, media/css/careers/components/diversity.scss, media/css/careers/components/footer.scss, media/css/careers/components/hero-text.scss, media/css/careers/components/hero-video.scss, media/css/careers/components/home.scss, media/css/careers/components/job-listings.scss, media/css/careers/components/locations.scss, media/css/careers/components/position.scss, media/css/careers/components/testimonials.scss, media/css/careers/styles.scss
Removes use of `@import` from careers pages .scss files.
#10896
=> Migrate /careers to use Sass @use (Issue #10896)

media/css/m24/components/footer-refresh.scss
This PR makes the new footer readable and functional for IE 11.
This is what it looks like now in IE 11, Window 10
RTL
https://github.com/mozilla/bedrock/issues/15536
- Using Broswerstack to test in IE 11, Window 10
- The footer should change at all in newer modern browsers
=> make footer readable and functional for IE 11 (fix #15536)

bedrock/settings/__init__.py
We discovered previews start under `/cms-admin/` but call the underlying page being previewed in a frame and that page lives outside the admin. So we need to allow framing on wagtail hosts so previews work.
=> On hosts with wagtail admin enabled set `frame-ancestors 'self'`

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx135beta.html
This PR updates WNP 135 beta with a copy change.
> Copy in body should change from `available in Firefox Beta 134` to `available in Firefox Beta 135`
https://github.com/mozilla/bedrock/issues/15832
http://localhost:8000/en-US/firefox/135.0beta/whatsnew/
=> wnp 135 beta copy change (fix #15832)

media/css/cms/base.scss, media/css/cms/rich-text.scss
Removes usage of `@import` from `/cms` base style sheet.
#10896
http://localhost:8000/cms-admin/
1. Go to the "Hello World" test page.
2. Click the preview button.
3. Confirm the page renders as expected.
=> Migrate /cms scss from @import to @use (Issue #10896)

media/css/m24/base.scss
Follows up from #15802
Anchor brand colors are not inverted in `@mixin invert-colors` for dark theme, and the blues and greens end up not readable on dark backgrounds. That is mostly overridden to blacks=whites, but here and there some of the original rules end up being higher specificity (or serving a newer color with css variable, but the older via hardcoded values); so this combination needs a tweak.
Only fixing this for css variables should not be an issue, as the dark theme inversion is also done via css variables — so UAs only using hex colors instead of vars won't use dark theme anyways.
Fixes #15800
http://localhost:8000/about/
_(doesn't reproduce locally 🤷 so pasted the generated m24-base into www-dev to test there…)_
https://www-demo1.allizom.org/ …
=> Fixup :visited:focus specificity

docs/cms.rst
… to make it easier to know what's relevant and to where
=> Rearrange some documentation for CMS building

package-lock.json, package.json
Bumps consent banner to the latest version. The only notable change is that the font stack was updated to incorporate the new Mozilla brand font (see https://github.com/mozmeao/consent-banner/pull/67)
#15839
Test in a browser with DNT / GPC disabled:
http://localhost:8000/en-US/products/vpn/?geo=de
=> Update @mozmeao/consent-banner to v1.1.0 (Fixes #15839)

media/css/m24/base.scss
Box decoration break cloning doesn't work as expected with an inline-block element.
All of our current CTA uses are inside a containing block element, so that container can handle block-level layout and let the CTA be inline display.
Chasing underline should only be under text, not blank space
This is more of a future-proofing fix as the [Smaller CTA PR](https://github.com/mozilla/bedrock/pull/15731) seems to have fixed all the reported issues by keeping the text on a single line
Also still helpful for larger font settings
https://github.com/mozilla/bedrock/issues/15683
note: may need to update l10n `./manage.py l10n_update` locally
Check "Let’s build a fairer future" green section on small mobile screen (320px)
And the below section: "Join us and make a difference" …
=> Fix chasing underline under multiple lines (fixes #15683)

bedrock/base/geo.py, bedrock/careers/models.py, bedrock/careers/tests/test_forms.py, bedrock/careers/tests/test_models.py, bedrock/careers/tests/test_utils.py, bedrock/careers/views.py, bedrock/newsletter/utils.py, bedrock/settings/base.py, bedrock/urls.py, profiling/hit_popular_pages.py, requirements/dev.in, requirements/dev.txt
This changeset adds support for profiling Bedrock using [django-silk](https://github.com/jazzband/django-silk) locally (or anywhere the bedrock_test image is used - but _not_ in production).  
It also contains some optimisations - via cacheing - to reduce the DB queries executed on the busiest pages.
Please revew this PR commit by commit, paying sceptical attention to the usage of cacheing etc. They contain details of the number queries saved.
I know that at the moment Bedrock is using a verson of Django's LocMemCache backend - this means that for 45 pods in production, we'll still get plenty of cache misses until the pods have all had a call that warms the cache. It might be that, given the TTL of the cached items, we never really get to that point in prod, but we will in Dev and Stage …
=> Bedrock performance tooling and initial optimisations

media/css/foundation/annual-report-2011.scss, media/css/foundation/annual-report-2019-2020.scss, media/css/foundation/annual-report-2021.scss, media/css/foundation/annual-report.scss, media/css/foundation/feed-icon-guidelines.scss, media/css/foundation/reimagine-open.scss
Removes usage of `@import` from /foundation style sheets.
#10896
- http://localhost:8000/en-US/foundation/annualreport/2021/
- http://localhost:8000/en-US/foundation/annualreport/2020/
- http://localhost:8000/en-US/foundation/annualreport/2019/
- http://localhost:8000/en-US/foundation/annualreport/2018/
- http://localhost:8000/en-US/foundation/annualreport/2017/
- http://localhost:8000/en-US/foundation/annualreport/2016/
- http://localhost:8000/en-US/foundation/annualreport/2015/
- http://localhost:8000/en-US/foundation/annualreport/2014/
- http://localhost:8000/en-US/foundation/annualreport/2013/
- http://localhost:8000/en-US/foundation/annualreport/2012/
- http://localhost:8000/en-US/foundation/annualreport/2011/
- http://localhost:8000/en-US/foundation/annualreport/2010/
- …
=> Migrate /foundation scss from @import to @use (issue #10896)

media/css/privacy/cookie-settings-form.scss, media/css/privacy/privacy-email.scss, media/css/privacy/privacy-protocol.scss
Updates to new Sass `@use` syntax, should be no regression
https://github.com/mozilla/bedrock/issues/10896
http://localhost:8000/en-US/privacy/
http://localhost:8000/en-US/privacy/email/
http://localhost:8000/en-US/privacy/websites/cookie-settings/ 
submit form on cookie settings page to see success message
=> Migrate /privacy to use Sass @use (issue #10896)

bedrock/base/cache.py, bedrock/base/tests/test_hybrid_cache_helpers.py, bedrock/settings/base.py, bin/export-db-to-sqlite.sh
In order to balance the need for a distributed cache with the speed of a local-memory cache (which we'll use in https://github.com/mozilla/bedrock/pull/15628), we've come up with a couple of helper functions that wrap the following behaviour:
**Getting values:**
* If it's in the local-memory cache, return that immediately.
* If it's not, fall back to the DB cache, and if the key exists there, return that, cacheing it in local memory again on the way through
* If the local memory cache and DB cache both miss, just return the default value for the helper function
**Setting values:**
* Set the value in the local memory cache and DB cache at (almost) the same time
* If the DB cache is not reachable (eg the DB is a read-only replica), log this loudly, as it's a sign the helper has not been …
=> Add helpers to support a 'hybrid cache' option that uses locmem + DB cache

bedrock/base/cache.py, bedrock/base/tests/test_hybrid_cache_helpers.py, bedrock/settings/base.py, bin/export-db-to-sqlite.sh
Reverts mozilla/bedrock#15881 which originally backed it out. This has been approved, just needs some prelim work (bootstrapping `hybrid_cache_db_table` via manually SSHing in) first
=> Reinstate "Add helpers to support a 'hybrid cache' option that uses locmem + DB cache""

bedrock/base/templates/base-protocol.html, bedrock/base/templates/includes/protocol/footer/footer-refresh.html
Prevents 2 JS errors on IE8:
- Loading Google Analytics (which seems unsupported there anyways, it throws an error even when it loads).
- Loading the newsletter JS in the footer on redesigned pages.
- Note that we still load GA for IE9, even though it doesn't get regular page specific JS.
#15867
There should be no JS errors when loading the home page on IE8: https://www-demo1.allizom.org/en-US/
=> Prevent JS errors on IE8

bedrock/firefox/templates/firefox/share.html, bedrock/firefox/urls.py
This PR adds a EN version for the Firefox share page.
http://localhost:8000/en-US/firefox/share/
http://localhost:8000/en-CA/firefox/share/
https://github.com/mozilla/bedrock/issues/15861
On Demo 3: 
https://www-demo3.allizom.org/en-US/firefox/share/
https://www-demo3.allizom.org/en-CA/firefox/share/
=> Share Firefox en page (fix #15861)

media/css/firefox/system-requirements.scss
Uses the same callout as #15382, changes gray-30 to gray-20 for consistency.
Also removes:
- compact callout styling, that got removed with MZP v19 update and never adapted (so it's not used anymore?) see [#14084/files](https://github.com/mozilla/bedrock/pull/14084/files)
- logic to only show "Get the most recent…" on "supported systems" by comparing to `body.is-modern-browser`, as that logic also stopped working with MZP v19 update and has no function anymore.
Analogous to #15342
http://localhost:8000/firefox/123.0/system-requirements/
=> Fix contrast in system-requirements callout

bedrock/base/templates/macros.html
For release notes, the subnav helper has to do some path juggling that's commented with HTML comments instead of Jinja comments. This hides it from resulting HTML.
- Turns `<!--` visible comments into `{#` template comments.
- Moves the comments within the conditionals proper.
- Fixes one incorrect wording while at it.
Gets rid of this on output:
> <img width="357" alt="Screenshot 2025-01-13 at 21 17 11" src="https://github.com/user-attachments/assets/2d645d12-83c5-4d07-930a-77afdde8dc2f" />
🚫🐞
http://localhost:8000/en-US/firefox/133.0.3/releasenotes/
http://localhost:8000/en-US/firefox/134.0beta/releasenotes/
http://localhost:8000/en-US/firefox/135.0a1/releasenotes/
http://localhost:8000/en-US/firefox/ios/133.0/releasenotes/
http://localhost:8000/en-US/firefox/android/133.0.3/releasenotes …
=> Hide releasenotes path comments from subnav output

bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, bedrock/mozorg/templates/mozorg/home/includes/m24/products.html, bedrock/products/templates/products/landing.html
This PR adds product pronunciation hint for "Fakespot" for screen readers.
Navigation product menu.
https://github.com/mozilla/bedrock/issues/15530
I have run this through VoiceOver.
=> add product pronunciation hint for screen readers (fix #15530)

bedrock/base/templates/includes/protocol/footer/footer-refresh.html, bedrock/base/templates/includes/protocol/footer/footer.html
Replaces internal `{{ url() }}` links in the footer with hardcoded links to [www.mozilla.org](http://www.mozilla.org/), with the exception of the `/privacy/cookie-settings/` page.
I have also left (for now) calls to the social helper links, such as `mozilla_twitter_url()` and `firefox_twitter_url()`.
N/A
Please test both the new and old footer
`./manage.py waffle_switch M24_WEBSITE_REFRESH on`
`./manage.py waffle_switch M24_WEBSITE_REFRESH off`
=> Hardcode www.mozilla.org links in footer

bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html, bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, bedrock/base/templates/includes/protocol/navigation/menus/firefox.html, bedrock/base/templates/includes/protocol/navigation/menus/innovation.html, bedrock/base/templates/includes/protocol/navigation/menus/products.html, bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html, bedrock/base/templates/includes/protocol/navigation/nav-cta.html, bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html, bedrock/base/templates/includes/protocol/navigation/navigation.html
Replaces internal `{{ url() }}` links in the navigation with hardcoded links to www.mozilla.org, with the exception of the firefox home page, `/firefox/new/` page, and the `/firefox/download/thanks/` page.
N/A
Please test both the new and old navigation
`./manage.py waffle_switch M24_WEBSITE_REFRESH on`
`./manage.py waffle_switch M24_WEBSITE_REFRESH off`
=> Hardcode www.mozilla.org links in navigation

media/css/products/landing.scss, media/css/products/monitor/waitlist.scss, media/css/products/vpn/article.scss, media/css/products/vpn/common-refresh.scss, media/css/products/vpn/common.scss, media/css/products/vpn/components/block.scss, media/css/products/vpn/components/hero.scss, media/css/products/vpn/components/unsupported-language.scss, media/css/products/vpn/download.scss, media/css/products/vpn/features.scss, media/css/products/vpn/invite.scss, media/css/products/vpn/landing-refresh.scss, media/css/products/vpn/platform-download.scss, media/css/products/vpn/pricing-refresh.scss, media/css/products/vpn/resource-center.scss
Removes usage of `@import` from /products style sheets.
https://github.com/mozilla/bedrock/issues/10896
- http://localhost:8000/en-US/products/
- http://localhost:8000/en-US/products/vpn/features/
- http://localhost:8000/en-US/products/vpn/pricing/
- http://localhost:8000/en-US/products/vpn/resource-center/
- http://localhost:8000/en-US/products/vpn/resource-center/what-is-an-ip-address/
- http://localhost:8000/en-US/products/vpn/download/
- http://localhost:8000/en-US/products/vpn/download/windows/thanks/
- http://localhost:8000/en-US/products/vpn/desktop/
- http://localhost:8000/vi/products/vpn/more/what-is-a-vpn/
=> Migrate /products to use Sass @use (Issue #10896)

media/js/base/datalayer-productdownload.es6.js, tests/unit/spec/base/datalayer-productdownload.js
Identify partner builds as "release" channel in analytics 
#15841  
Using the javascript console, click the link and then print the `dataLayer`.
=> Identify partner builds as "release" channel in analytics

media/css/firefox/developer/whatsnew-mdnplus.scss
https://github.com/mozilla/bedrock/issues/15935
Confirm the image path var is correct
=> Re-add protocol img path on mdn whatsnew page (fixes #15935)

bedrock/cms/cms_only_urls.py, bedrock/cms/middleware.py, bedrock/cms/tests/test_middleware.py, bedrock/settings/base.py
This changeset addresses the problem where a request to path in a locale that is not in the CMS does not fall back to a locale variant for that path that _is_ in the CMS.
e.g. if /en-US/about/leadership/ exists in the CMS but /fr/about/leadership does not, typical Bedrock behaviour (for non-CMS pages) would be to redirect to the /en-US/ version as a fallback.
This changeset does more than just punt to en-US, though - it aims to redirect to the best-fit locale available in the CMS based on the user's Accept-Language header, and then will fall back to trying en-US
Fixes #15932
* pull latest dev DB with make preflight
* go to http://localhost:8000/de/about/leadership - should 302 to /en-US/about/leadership
* go to http://localhost:8000/de/asdasdasdas - should 404 without redirecting
* set …
=> Support failing over to a different, preferred locale for CMS pages upon 404

media/css/legal/legal.scss
Updates outdated Sass syntax
https://github.com/mozilla/bedrock/issues/10896
http://localhost:8000/en-US/about/legal/ 
http://localhost:8000/en-US/about/legal/eula/
=> Migrate /legal to use Sass @use (#10896)

bedrock/base/templates/includes/banners/firefox-newsletter.html, bedrock/firefox/templates/firefox/releases/index.html, bedrock/firefox/templates/firefox/releases/notes.html
SEO issue: this will create multiple versions of the same page with different URLs
Rely on analytics events only for internal links. UTM params from:
release index: https://github.com/mozilla/bedrock/pull/15879/files#diff-2d4df3ebb9ddb808d359f7d02159c5f1a31a0af3bdf2c66fb522668140b7ea66R23
release notes: https://github.com/mozilla/bedrock/pull/15879/files#diff-49eefdd97979190284c15980e858f1b1caaf4376eea44474958f7a700d5d11a6R56
https://github.com/mozilla/bedrock/issues/15960
http://localhost:8000/en-US/firefox/releases/
http://localhost:8000/en-US/firefox/135.0/releasenotes/ 
The CTA link should not have any UTM params on the URL
=> Remove internal page UTM params

bedrock/firefox/templates/firefox/share.html
This PR updates links for Firefox share page de and fr versions
http://localhost:8000/de/firefox/share/
http://localhost:8000/fr/firefox/share/
https://github.com/mozilla/bedrock/issues/15949
=> update links for Firefox share page de and fr versions (fix #15949)

media/static-bundles.json
This PR removes duplicate CSS bundle in `media/static-bundles.json`
Test header and footer still functioning as expected.
https://github.com/mozilla/bedrock/issues/15972
=> remove duplicate CSS bundle (fix #15972)

media/css/newsletter/newsletter-confirm.scss, media/css/newsletter/newsletter-country.scss, media/css/newsletter/newsletter-developer.scss, media/css/newsletter/newsletter-family.scss, media/css/newsletter/newsletter-firefox-confirm.scss, media/css/newsletter/newsletter-firefox.scss, media/css/newsletter/newsletter-management.scss, media/css/newsletter/newsletter-monitor-waitlist.scss, media/css/newsletter/newsletter-mozilla.scss, media/css/newsletter/newsletter-online-harassment.scss, media/css/newsletter/newsletter-opt-out-confirmation.scss, media/css/newsletter/newsletter-recovery.scss, media/css/newsletter/newsletter-security-privacy-news.scss, media/css/newsletter/newsletter-updated.scss
Removes usage of `@import` from /newsletter style sheets.
Sets lib with config values where notification component or references to `$image-path` are needed
https://github.com/mozilla/bedrock/issues/10896
http://localhost:8000/en-US/newsletter/security-and-privacy/
http://localhost:8000/en-US/newsletter/security-and-privacy/online-harassment/
http://localhost:8000/en-US/newsletter/confirm/thanks/
http://localhost:8000/en-US/newsletter/updated/
http://localhost:8000/en-US/newsletter/recovery/
http://localhost:8000/en-US/newsletter/opt-out-confirmation/
http://localhost:8000/en-US/newsletter/mozilla/
http://localhost:8000/en-US/newsletter/firefox/
http://localhost:8000/en-US/newsletter/developer/ …
=> Migrate /newsletter to use Sass @use (#10896)

bedrock/base/templates/includes/banners/base.html, bedrock/base/templates/includes/banners/basic.html, bedrock/firefox/templates/firefox/releases/index.html, bedrock/firefox/templates/firefox/releases/notes.html
Currently both the pencil banner and the newsletter banner are identified as `Promotion`. This PR adds a unique aria-label of `Newsletter` for the latter, so they can be more easily identified / navigated to.
#15958
http://localhost:8000/en-US/firefox/134.0/releasenotes/
A11y tests should pass:
- `cd tests/playwright`
- `npm run a11y-tests`
=> Give newsletter landmark a separate aria identifier to the pencil banner (Fixes #15958)

media/css/protocol/components/_footer.scss
Fix CI error
> #47 4.534 ValueError: The file ‘css/media/img/icons/social/bluesky/white.svg’ could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fb246ba63c0>.
Fails to resolve image in old footer without slash
http://localhost:8000/en-US/ with M24_WEBSITE_REFRESH: off
=> Fix media path for bluesky image

bedrock/mozorg/templates/mozorg/about/index-m24.html, bedrock/mozorg/templates/mozorg/home/home-m24.html, media/css/m24/about.scss, media/css/m24/base.scss, media/css/m24/home.scss, media/static-bundles.json
This PR create shared and unshared CSS bundles for M24 home and about us pages.
1. `media/css/m24/base.scss` becomes the new shared stylesheet between home and about page
2. `media/css/m24/home.scss` and media/css/m24/about.scss are the unique stylesheet for home and about page respectively 
https://github.com/mozilla/bedrock/issues/15907
1. Check out this PR
2. Compare home and about page with production site
=> create shared and unshared CSS bundles for M24 home and about us pages (fix #15907)

package-lock.json, package.json
See https://github.com/mozmeao/trafficcop/releases/tag/v3.1.0
There should be no changes that impact any active experiments
N/A
Test in a browser with DNT/GPC disabled
=> Bump @mozmeao/trafficcop to v3.1.0

bedrock/firefox/templates/firefox/landing/get.html, bedrock/firefox/templates/firefox/landing/tech.html, bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/firefox/urls.py, l10n/en/download_button.ftl, l10n/en/firefox/new/desktop.ftl, media/css/firefox/landing/get/marketing-opt-out.scss, media/js/base/stub-attribution/stub-attribution.js, media/js/firefox/landing/get/marketing-opt-out-init.es6.js, media/js/firefox/landing/get/marketing-opt-out.es6.js, media/static-bundles.json, tests/unit/spec/base/stub-attribution/stub-attribution.js, tests/unit/spec/firefox/landing/marketing-opt-out.js
- Adds a custom Firefox landing page that will be used as a destination for people who click on ad links.
- Also updates a couple of strings on `/firefox/new/`, at request of the product team.
The "opt-out" checkbox is effectively a full opt-out of analytics and attribution in general, using the same cookie as our consent banner / cookie settings page. The only new detail is that because it is "opt-out" and not "opt-in", when someone unchecks the input, we must "undo" things like removing attribution parameters from download links and removing the existing attribution cookie.
The checkbox will only appear if:
- Visitors are outside of EU/EAA (e.g. they are in the US).
- The do not have DNT / GPC enabled.
- They have not already explicitly rejected analytics cookies (e.g. via the …
=> Add ToS marketing opt out page (Fixes #15946)

.github/l10n/linter_config.yml, bedrock/base/templates/includes/protocol/footer/footer-refresh.html, l10n/en/firefox/developer.ftl, l10n/en/footer-refresh.ftl
This fixes string issues introduced in #16007. It also introduces a brand check on MDN, and fixes a previous string used in the footer.
The strings are still stuck in review in https://github.com/mozilla-l10n/www-l10n/pull/479, no need for new IDs (cc @peiying2)
=> Fix strings for dev VNP, add MDN to Fluent linter

media/css/protocol/protocol-mozilla-2024.scss
Remove smooth scroll.
- integration tests are complaining about not being able to scroll elements into view, this should fix it.
n/a
=> Fix failing tests: remove smooth scroll

bedrock/privacy/templates/privacy/notices/firefox-2025.html
It seems like this bundle is only applicable to the old privacy notice.
#16031
http://localhost:8000/en-US/privacy/firefox/
=> Remove superfluous JS bundle from new privacy/firefox notice (Fixes #16031)

bedrock/privacy/templates/privacy/faq-v2.html, bedrock/privacy/urls.py, bedrock/privacy/views.py, l10n/en/privacy/faq-v2.ftl
Updates `/privacy/faq/` page copy. There were many edits, so I went with a whole new FTL file to keep things cleaner.
#16029
http://localhost:8000/privacy/faq/
=> Update privacy/faq page copy (Fixes #16029)

l10n/en/privacy/faq-v2.ftl
There's an extra `"`.
I'll fix the strings in the repo, no need for a new ID.
=> Remove left-over double quote from privacy-faq-v2-mozilla-is-not string

bedrock/firefox/templates/firefox/features/translate.html, bedrock/firefox/views.py
_If this changeset needs to go into the FXC codebase, please add the `WMO and FXC` label._ 🤷 
CJK languages added with Fx 135 launch.
Launches Tue 4th Feb.
NB: The current logic strips any (regional) variants in brackets for the generated native names, so the _Chinese (Simplified)_ is listed as "中文" instead of "中文 (简体)":
> <img width="587" alt="Screenshot 2025-01-31 at 21 26 52" src="https://github.com/user-attachments/assets/99cf7a42-170d-46c1-9ca7-a8a7333b9c7b" />
(In case zh-TW is added to the list at some point, it would get listed as "繁体中文" in comparison. That looks reasonable enough, but doublechecking from a native speaker wouldn't hurt whether that's sufficiently politically correct?)
Resolves #15954
http://localhost:8000/en/firefox/features/translate/ …
=> Add ja+ko+zh to translations feature

bedrock/privacy/templates/privacy/includes/privacy-basics.html
Update links for managing privacy settings
- 2 URL changes
- URLs should not have language in them
n/a
This is the two buttons under "Privacy that works for you"
http://localhost:8000/en-US/privacy/firefox/
=> Update links for managing privacy settings

bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/firefox/templates/firefox/new/desktop/experiment-firefox-new-default.html, bedrock/firefox/views.py, media/css/firefox/new/desktop/default-experiment.scss, media/js/firefox/new/desktop/default-experiment-criteria.es6.js, media/js/firefox/new/desktop/default-experiment.es6.js, media/js/firefox/new/desktop/default-opt-out-init.es6.js, media/js/firefox/new/desktop/default-opt-out.es6.js, media/static-bundles.json, tests/unit/spec/base/m24-pencil-banner.js, tests/unit/spec/firefox/new/desktop/default-experiment-criteria.js, tests/unit/spec/firefox/new/desktop/default-opt-out.js
Adds an experiment to the `/firefox/new/` page that displays a "Set Firefox as Default" checkbox above the main download button.
This is a pretty complex experiment set up, with some very specific targeting and logic. So could use some careful review / testing. I tried to add thorough tests.
Experiment targeting:
- US / Canada geos only.
- `en-US` / `en-CA` page languages only.
- Windows OS only.
- 25% traffic for each variation.
Additional notes:
- Experiment redirect should only trigger if there are **not** UTM parameters in the page URL already.
- Since the experiment modifies attribution data, the experiment should also only trigger if the visitor does **not** have an existing attribution cookie (e.g. that might get set on a prior page navigation). …
=> Firefox set as default experiment (Fixes #15895)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx136-eu-pip.html
typo fix: problement to probablement
n/a - reported in slack
http://localhost:8000/fr/firefox/136.0/whatsnew/
=> Fix typo in FR wnp

bedrock/firefox/firefox_details.py, bedrock/firefox/tests/test_firefox_all.py, bedrock/firefox/tests/test_helpers.py
Adds new Linux/ARM64 builds for Release, Beta, and Developer Edition.
Fixes #16065 
https://bugzilla.mozilla.org/show_bug.cgi?id=1678342#c18
https://bugzilla.mozilla.org/show_bug.cgi?id=1934634
=> Add Release, Beta, and Developer Edition Linux/ARM64 builds to firefox/all

bedrock/settings/base.py
In webservices-infra we are adding the pod IP prepended to the env var string plus a comma. If nothing follows the comma, the old code would fail.
This updates the env var processing to allow trailing comma and then we remove the empty string.
=> Update ALLOWED_HOSTS to allow empty

bedrock/settings/base.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This hasn't been used in awhile since we were using `ALLOWED_HOSTS="*"`. But we recently switched to adding the `POD_ID` and correct hosts to this setting, so this is no longer necessary.
=> Remove unused ALLOW_CIDR code and dependency

bedrock/privacy/templates/privacy/notices/firefox-2025.html, media/js/privacy/redirects.es6.js, media/static-bundles.json, tests/playwright/specs/privacy-firefox-crash-reporter.spec.js, tests/playwright/specs/privacy-firefox-health-report.spec.js
Redirect old in-product anchors to sumo articles
There's two old links in-product that used to redirect to anchors on the privacy notice page. These anchors are gone and the associated content was removed. Now we need to redirect to SUMO articles with similar content. Unfortunately we can't catch the anchor links at the django level so we need to redirect after the page loads using javascript.
https://github.com/mozilla/bedrock/issues/16080
I think this is probably an abuse of the Playwright tests so feedback welcome.
| URL | Forwards to |
| ------------- | ------------- |
| http://localhost:8000/legal/privacy/firefox.html#health-report  | `https://support.mozilla.org/kb/technical-and-interaction-data`  |
| http://localhost:8000/legal/privacy/firefox.html#crash-reporter  | …
=> Redirect old in-product anchors to sumo articles

bedrock/base/templates/includes/protocol/footer/footer-refresh.html, l10n/en/footer-refresh.ftl, media/css/m24/components/footer-newsletter.scss, media/css/m24/components/footer-refresh.scss
This PR adds the Mozilla advertising section to footer.
- added new Mozilla advertising section in footer
- removed "Resources" link section
- other footer layout changes (see details in Figma file linked in the issue)
- cleaned up some class names in footer to make it consistent and less confusing
https://github.com/mozilla/bedrock/issues/16075
=> add Mozilla Advertising section to footer (fix #16075)

bedrock/products/templatetags/misc.py, bedrock/products/tests/test_helper_misc.py, bedrock/settings/base.py, media/js/base/fxa-attribution.es6.js, media/js/base/fxa-coupon.es6.js, media/js/base/fxa-product-button.es6.js
Adds new Subplat staging URLs for VPN subscriptions behind the switch `VPN_SUBPLAT_NEXT`
Note that we do not yet have production URLS, those will come later. For now this is only for testing on www-dev.
Adding as P1 as they have requested this be ready for testing on www-dev by March 26th.
#16100
http://localhost:8000/en-US/products/vpn/?utm_source=test&utm_campaign=test&coupon=FIREFOX105
=> Add new Subplat staging URLs for VPN subscriptions (Fixes #16100)

bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/firefox/templates/firefox/new/desktop/experiment-firefox-new-default.html, bedrock/firefox/views.py, media/css/firefox/new/desktop/default-experiment.scss, media/js/firefox/new/desktop/default-experiment-criteria.es6.js, media/js/firefox/new/desktop/default-experiment.es6.js, media/js/firefox/new/desktop/default-opt-out-init.es6.js, media/js/firefox/new/desktop/default-opt-out.es6.js, media/static-bundles.json, tests/unit/spec/firefox/new/desktop/default-experiment-criteria.js, tests/unit/spec/firefox/new/desktop/default-opt-out.js
This reverts commit 52f448f984d837fe19eca24903247b15beba16af.
Basically there was an error on the product side of things that meant people saw an older version of the on-boarding flow and not the one this test should display, so the product team have asked to run this again.
This code has already been reviewed and tested in https://github.com/mozilla/bedrock/pull/16020, so should hopefully be a quick and simple review this time around.
#16096
=> Revert "Remove set-as-default experiment code (Fixes #16095) (#16096)"

bedrock/firefox/templates/firefox/features/translate.html, bedrock/mozorg/templates/mozorg/about/includes/m24/community.html, bedrock/mozorg/templates/mozorg/about/includes/m24/manifesto.html, bedrock/mozorg/templates/mozorg/home/home-new.html, bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html, l10n/en/brands.ftl, l10n/en/firefox/features/translate.ftl, l10n/en/mozorg/about-m24.ftl, l10n/en/mozorg/home-m24.ftl, l10n/en/mozorg/home-new.ftl, l10n/en/navigation_refresh.ftl
This PR removes obsolete l10n strings.
https://github.com/mozilla/bedrock/issues/16085
=> remove obsolete l10n strings (fix #16085)

bedrock/sitemaps/models.py, bedrock/sitemaps/utils.py, bin/run-db-update.sh
I think the main thing left to investigate for whether this will work or not is whether the clock pod keeps the l10n files updated locally or not. I'm pretty sure it does, but that is something we need to double check.
=> Update sitemaps data on clock pod instead of external repo

bedrock/products/templates/products/vpn/windows-download.html
This PR updates the VPN Windows extension download link.
http://localhost:8000/en-US/products/vpn/download/windows/thanks/ step 5
https://github.com/mozilla/bedrock/issues/16087
http://localhost:8000/en-US/products/vpn/download/windows/thanks/
=> update VPN extension download link (fix #16087)

media/css/mozorg/about-transparency.scss
Constrains heading adjustments only to content, to not interfere with other site components.
1. I'm aware the stylistic choice is questionable, I could have nested it in blocks but wanted to make the least meaningless whitespace changes.
2. It all seems to be inside mzp-l-content so that could have been used instead of main however there's a lot of pages to check so went with the simple container constraint.
3. Proper solution should perhaps be constraining that to mzp-c-article or whatever was used there before, and use that as a container; however that's not the case currently, and alas would need more refactoring and careful checking.
Fixes #16123
(also closes #16124)
/about/policy/transparency/
/about/policy/transparency/jan-jun-2024/
/about/policy/transparency/jan-jun-2019/
=> Fix transparency header and footer margins

media/css/products/monitor/article.scss
should fix CI issue from https://github.com/mozilla/bedrock/actions/runs/14200072847/job/39784617561
`Post-processing 'css/monitor-article.css' failed!`
test the monitor pages show as expected
=> Add vars on monitor article lib import

docs/docs/abtest.md
MD version of https://github.com/mozilla/bedrock/pull/16098
Based on [internal Nimbus docs](https://docs.google.com/document/d/1IndQbGtfmIjIEqAULEn4HleiimVfWg-DKkm8zAHMv-w/edit?tab=t.0) [Moz only]
cd to `docs` and run `make serve` to view locally (you may need `make preflight` first to install doc dependencies)
http://127.0.0.1:8765/bedrock/abtest/
=> Add nimbus experiment docs

bedrock/products/models.py
Remove subpage restriction from MonitorArticleIndexPage
It's preventing child pages from being made under the index. Not sure why though.
n/a
=> Remove subpage restriction from MonitorArticleIndexPage

media/css/mozorg/mozilla-account-promo.scss
_If this changeset needs to go into the FXC codebase, please add the `WMO and FXC` label._ 🤷 (the promo is included in more places so most likely yes 🔥🦊)
Needs more specificity for active, focus, visited inherited from base style.
Not sure if these are regressions from overriding fonts and colors in base not yet in protocol theme, or was a preexisting issue so I'm not adding any comments to review if/once MZP v20 lands some of that in defaults. Figured being as explicit about (non-)inheritance can't hurt either way.
Resolves #15925
http://localhost:8000/en/firefox/
http://localhost:8000/en/products/
=> Fix FxA form link contrasts

docs/docs/pipeline.md
… as it no longer works for Bedrock
Preview of changed doc:
=> (chore) Remove references to whatsdeployed.io

media/css/m24/components/navigation-refresh.scss
_If this changeset needs to go into the FXC codebase, please add the `WMO and FXC` label._ 🤷 (most likely 🔥🦊)
Adds a little specificity to menu anchor colors, to hide flash of Fx–themed palette on some pages.
There seems to be some sort of JS delay involved, that applies the final color based on the state of the panel etc. as the final color is often green, not black, and if the link is blue pre-JS, the flash of unexpected color is a bit jarring. This makes the hover anchors on Fx-themed pages consistent with rest of the site.
NB: Went for `:is()` shenanigans only because SASS doesn't allow `a&` (and the selector above is not for anchor but just the pseudo on the class before) and I wanted to keep the rules together with the others, not repeating another block afterwards just for this; …
=> Fix nav hover for fx theme

bedrock/base/templates/base-error.html, bedrock/base/templates/base-protocol-mozilla.html, bedrock/base/templates/base-protocol.html, bedrock/base/templates/includes/protocol/footer/footer.html, bedrock/base/templates/includes/protocol/navigation/navigation.html, bedrock/firefox/templates/firefox/built-for-you/landing.de.html, bedrock/firefox/templates/firefox/built-for-you/landing.fr.html, bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html, bedrock/firefox/templates/firefox/developer/firstrun.html, bedrock/firefox/templates/firefox/developer/whatsnew.html, bedrock/firefox/templates/firefox/family/index.html, bedrock/firefox/templates/firefox/nightly/firstrun.html, bedrock/firefox/templates/firefox/nightly/whatsnew.html, bedrock/firefox/templates/firefox/nothing-personal/index.html, bedrock/firefox/templates/firefox/welcome/base.html, bedrock/firefox/templates/firefox/whatsnew/base.html, bedrock/mozorg/tests/test_views.py, bedrock/mozorg/views.py, media/css/protocol/components/_navigation.scss, media/css/protocol/navigation-and-footer.scss, media/static-bundles.json
Remove `m24-website-refresh` switch and associated fallbacks.
- removed references to switch `m24-website-refresh`
- moved header nav logo override into the css file
- can't do the same with the footer ones because we're using default Protocol for the legacy footer
n/a
To check that the new logo appears on the old header and footer you can edit `{% if ftl_file_is_active('navigation_refresh') and ftl_file_is_active('footer-refresh') %}` to resolve as False. Or change your local env to `DEV=False` and check an untranslated language.
=> Remove refresh switch and associated fallbacks

bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json, l10n/en/mozorg/newsletters.ftl
The `test-pilot` newsletter is being rebranded and started up again as an English only newsletter. As an English only newsletter the thought is we can remove l10n and let the strings from Basket be used as-is, which the marketing team has configured to their liking.
=> Remove test-pilot newsletter l10n strings

root_files/.well-known/matrix/client
Users currently get `MISSING_MATRIX_RTC_FOCUS` error for audio and video calls — this adds the missing Element Call endpoint.
Contrary to the assumption and understanding from #8414 that any delegation to EMS should cover things like this (as it has its own well knowns: https://mozilla.modular.im/.well-known/matrix/client …) the client supposedly only reads the JSON at the apex domain, not the actual cloud/origin instance.
Which would mean bedrock has to actually track any changes to the upstream config, or serve its content instead, proxying, redirecting etc. — I'm trying to understand the options and what's the best practice with hosted EMS in the meantime. This is nonetheless a hotfix for now, to unblock any *RTC usage in the client.
(Users reporting it worked well before the …
=> Enable E2EE A/V for chat.m.o

.github/workflows/publish_docs.yml
This action currently fails with an (expected) error every time someone commits to their fork of bedrock. This added check makes it so we only try building and deploying the docs when commits are made here.
N/A
=> Only build/deploy docs on commits to mozilla/bedrock repo

media/css/protocol/basic-article.scss
Removes top padding on smaller screens in the legal articles 
I chose not to edit article-base since the [privacy notice page](https://www.mozilla.org/en-US/privacy/) uses it.
I think it makes more sense to reverse the media query. Instead of using min-width we could use max-width and set padding to 0 below a certain screen size. I couldn't find a preset breakpoint variable to use though, like I could for `$mq-md`. 
#15944
=> Fix bug #15944: weird gap on mobile articles with sidebar

.github/l10n/check_toml_configs.py, .github/l10n/requirements.txt, .github/workflows/fluent_linter.yml
This will fail the workflow if one of the reference paths listed is missing.
=> Check TOML config file within Fluent linter workflow

bedrock/firefox/redirects.py, bedrock/firefox/tests/test_redirects.py, docs/docs/attribution/0003-firefox-mobile.md
Allowed characters in param values are:
- ASCII leters in upper and lower case
- numbers
- period
- dash
- underscore
=> Move from an allow-list to a regex validator for mobile redirects

media/js/base/protocol/m24-keyboard-focus-trap.es6.js, media/js/base/protocol/m24-menu.es6.js, media/js/base/protocol/m24-navigation.es6.js
This PR updates the m24 navigation to allow mobile navigation keyboard focus trap.
- Mobile navigation should have proper keyboard focus trap
- Desktop navigation should have the same behavior as the prod, following document flow
https://github.com/mozilla/bedrock/issues/16090
1. Checkout this PR
2. Resize screen to mobile size
3. Click on "Menu" to review navigation focus trap
4. Select a menu category to review menu focus trap
5. Return to opened navigation to review navigation focus trap
6. Resize screen to desktop size to review that full sized navigation is not affected
=> mobile navigation keyboard focus trap [fix #16090]

bedrock/settings/__init__.py
This PR introduces the `form-action` directive to the report-only Content Security Policy (CSP) header. The goal is to test and evaluate its compatibility before eventually applying it to the enforced CSP header. The `form-action` directive restricts where forms on the site can send their data upon submission, adding an additional layer of security to prevent potential vulnerabilities.
The `form-action` directive is a key security measure designed to mitigate attacks that exploit form submissions, such as:
- **Phishing and data exfiltration attacks**: Prevents malicious actors from redirecting form submissions to unauthorized or external servers.
- **Clickjacking**: Works in tandem with other CSP directives to ensure that embedded forms are protected.
- **Cross-site scripting (XSS) …
=> Set the `form-action` directive in the report-only CSP

bedrock/cms/middleware.py, bedrock/cms/tests/test_middleware.py
Prior to this fix, we were looking at all (live and draft) pages to find an alternative to redirect to, which caused a 302 loop
Resolves #16202 and is added via PR, not directly to main (which was backed out)
Unit testing passing is enough - i've tested this locally
=> (fix) Stop creating a redirect loop when a draft page matches a URL path - it should correctly 404

bedrock/legal/tests/test_views.py, bedrock/legal/urls.py, bedrock/legal/views.py, bedrock/privacy/templates/privacy/notices/firefox-intro.html, bedrock/privacy/templates/privacy/notices/firefox.html, bedrock/privacy/tests/test_views.py, bedrock/privacy/views.py, media/css/privacy/privacy-firefox.scss
Focus PN and add TOU page updates.
- Made the firefox.html template reusable.
- Moved the intro and sidebar extras to a new file.
- Added a bit of CSS to adjust spacing if there is/isn't an intro
- Updated view for PN
- Added view for TOU
Fix #16015
Run `make preflight` to make sure you have up to date legal-docs.
http://localhost:8000/en-US/privacy/firefox-focus/
http://localhost:8000/en-US/privacy/firefox-focus/?v=product
http://localhost:8000/en-US/about/legal/terms/firefox-focus/
http://localhost:8000/en-US/about/legal/terms/firefox-focus/?v=product
Also http://localhost:8000/en-US/privacy/firefox/ should be unchanged.
=> Focus/Klar PN and TOU (Fix #16015)

l10n/en/sub_navigation.ftl
This PR restores the l10n string for Firefox sub navigation `sub-navigation-more`
http://localhost:8000/en-US/firefox/new/ Sub navigation "More"
https://github.com/mozilla/bedrock/issues/16209
=> restore l10n string for Firefox sub navigation (fix #16209)

tests/functional/test_cdn.py
...not 301 to a different path altogether (which is currently what happens with `/firefox/` --[301]--> `/firefox/new/`
Resolves #16215
=> (fix) Update CDN tests to test paths that will 302 to a locale-prefixed path

bedrock/base/templates/includes/banners/pencil-banner.html, bedrock/products/templatetags/misc.py, bedrock/products/tests/test_helper_misc.py, media/css/m24/components/pencil-banner.scss
This PR:
- adds VPN promo pencil banner
- modified the VPN referral link helper function to make CTA button style optional
1. Homepage pencil banner
2. Existing VPN referral links
https://github.com/mozilla/bedrock/issues/16198
Pencil banner
1. Pencil banner on homepage in English: http://localhost:8000/en-US/
2. Pencil banner not showing on non-homepage English pages: http://localhost:8000/en-US/firefox/new/
3. Pencil banner not showing on non-English homepage: http://localhost:8000/fr/
VPN referral link default button style
- http://localhost:8000/en-US/firefox/welcome/17a/
=> add VPN promo pencil banner (fix #16198)

bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html, bedrock/mozorg/templates/mozorg/home/includes/m24/products.html, bedrock/products/templates/products/landing.html
Update Monitor link in nav, hompage, and /products.
- Links to Monitor in the nav, homepage, and /products pages now go to the monitor CMS landing page.
Fix #15751
- Run `make preflight` to get a copy of the database that includes the /products/monitor/ page
- http://localhost:8000/ click Products > Mozilla Monitor in the gobal nav.
=> Update Monitor link in nav

bedrock/products/templates/products/landing.html
Removes undefined variable
#16225
http://localhost:8000/de/products/
=> Remove undefined utm_params variable from products landing page (Fixes #16225)

bedrock/careers/tests/test_views.py, bedrock/cms/middleware.py, bedrock/cms/tests/test_middleware.py, bedrock/mozorg/tests/__init__.py, bedrock/products/tests/test_models.py, bedrock/settings/__init__.py, bedrock/wordpress/models.py
This changeset
* Handles null bytes in URLs when trying to find fallback CMS pages - previously this would 500, but now we continue to 404. This only showed when running tests against postgres
* Adds support for running tests on postgres: if your .env specs a PG database, then the tests will run on that, else will use the default in-memory sqlite database
* Fixes a few small tests that were failing under postgres
Please check over each commit for sense :)
Reolves #16222
Unit tests passing + code review should be enough. If you want to run it against postgres locally, too, go for it
=> Sanitise CMS locale lookup better + fixup existing tests that failed on postgres

root_files/.well-known/matrix/support
This adds a static JSON file for `.well-known/matrix/support`, which [is part of the spec nowadays](https://spec.matrix.org/v1.14/client-server-api/#getwell-knownmatrixsupport_response-200_contact) to point people and tooling towards a way to report service abuse. This points to [this group](https://groups.google.com/u/0/a/mozilla.com/g/matrix-admins/about), in which I'm an owner.
=> Add `.well-known/matrix/support` file.

media/css/m24/flag.scss
This update restricts the selector to focus-visible, so the button should only be promoted above the nav when keyboard-focused
We initially applied this on all focus, but it can seem broken or buggy for mouse users when the button appears over the nav.
https://github.com/mozilla/bedrock/issues/16151
=> Restrict z-index selector for animation button (fixes #16151)

bedrock/settings/base.py
Adds `tg` to allowed locales in settings to stop 404ing in prod.
Following up from #15021, this is pending approval from l10ns.
This locale is still listed on the global root home page and offered to crawlers, but returns 404 as it is not explicitly allowed. (The reason is explained in both the previous PR and the linked issue.)
After an inquiry during the previous PR into the commitment of keeping Tajik version of wwwmo up to date, the community got very active the following months, and went from ~20% to currently 60%+ of translated content, with the usual key pages as home, products, browsers, vpn etc. above the threshold for enabling the locale. So the question is, whether also the Tajik locale wouldn't be a worthwhile addition, given its recent activity.
#15010
_(in prod mode, with …
=> Enable Tajik localization in prod

media/css/l10n/includes/font-inter.css
Drops WOFF1 src, MZP now only provides WOFF2.
Fix #16247
=> Remove l10n font references to format no longer provided by MZP

bedrock/products/models.py
Monitor articles are ordered using wagtail "path" field.
#16150
- Create monitor articles.
- Edit the order in Wagtail
- Check they are in the right order on the index page
Here's where the reorder option is :
=> Monitor articles are ordered using wagtail "path" field

media/css/firefox/new/basic/thanks.scss, media/css/firefox/new/desktop/thanks.scss
Increase visibility of help link on download thanks
User testing with low-vision users turned up that this was hard to see.
http://localhost:8000/en-US/firefox/download/thanks/
=> Increase visibility of help link on download thanks

docs/docs/download-buttons.md, docs/mkdocs.yml
Brain dump of Firefox download button logic.
N/A
=> Update firefox download button docs

bedrock/firefox/templates/firefox/browsers/browser-history.html, bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html, bedrock/firefox/templates/firefox/channel/base.html, bedrock/firefox/templates/firefox/developer/index.html, bedrock/firefox/templates/firefox/faq.html, bedrock/firefox/templates/firefox/includes/sub-nav-firefox.html, bedrock/privacy/templates/privacy/archive/firefox-relay-2022-10.html
Replaces outdated Firefox family logo with regular Firefox browser logo.
#16252
- http://localhost:8000/en-US/firefox/new/
- http://localhost:8000/en-US/firefox/channel/desktop/
- http://localhost:8000/en-US/firefox/developer/
- http://localhost:8000/en-US/firefox/faq/
- http://localhost:8000/en-US/firefox/browsers/browser-history/
- http://localhost:8000/en-US/firefox/browsers/what-is-a-browser/
- http://localhost:8000/en-US/privacy/archive/firefox-relay/2022-10/
=> Remove Firefox family logo (Fixes #16252)

docs/docs/attribution/0005-consent-management.md
Adds some (hopefully) useful debug info to the cookie consent management docs.
N/A
=> Update cookie banner docs with debug info

bedrock/mozorg/templates/mozorg/robots.txt
Allow crawl of whatsnew and first run so they are deindexed
- Remove whatsnew and firstrun from robots.txt
- Check tags on both have no-index
#16275
🤷‍♀️ Mostly we need to rely on Adria to make sure it's working as intended.
=> Allow crawl of whatsnew and firstrun so they are deindexed (#16275)

bedrock/firefox/templates/firefox/all/base.html
No-index, no-follow /all with different syntax
Google is still crawling these pages and we don't want them to. We'll try this before disallowing.
#16104
=> No-index, no-follow /all with different syntax (#16104)

bedrock/settings/__init__.py
This adds the host for front-end assets which is needed during integration tests or when someone is accessing the origin directly instead of the CDN.
=> Add media assets to CSP explicitly for origin requests

media/css/base/page-not-found.scss, media/css/newsletter/newsletter-updated.scss
_If this changeset needs to go into the FXC codebase, please add the `WMO and FXC` label._ 🤷
yeah 🔥🦊
Uses bidi mixin to prepend different glyphs based on the direction necessary.
It might seem the space is on the wrong side of the RTL content, but this is actually correct (it would get flipped from LTR to RTL when applied.)
Fixes #16282
http://localhost:8000/he/404/
http://localhost:8000/he/newsletter/updated/
=> Fix newsletter & 404 bidi arrows direction

bedrock/firefox/templates/firefox/includes/macros.html, tests/playwright/specs/products/firefox/firefox-platforms.spec.js
Add language swap to download link on firefox/mac just for Japanese
- button updated
- tests added
Resolves #16294
https://mozilla.github.io/bedrock/testing/#running-playwright-tests
` cd tests/playwright &&  npx playwright test --grep "Download Firefox for"`
=> (fix) Ensure Japanese Mac downloads don't 404 on Bouncer

tests/playwright/specs/products/firefox/firefox-platforms.spec.js
Update platform download tests to handle mac or osx in url
- accept `mac` or `osx` in download URL
#16294
=> Update platform download tests to handle mac or osx in url

bedrock/firefox/templates/firefox/features/translate.html
Custom SEO preview/covers were removed in [#13119](https://github.com/mozilla/bedrock/pull/13119/files#diff-29fd6dd7e15e98241ae9acefae642b20fdbcdf0066889e20917157169585df8a), this removes forgotten (=broken) reference.
Has caused 500 on springfield. For some reason here the static helper while not resolving the asset just prints out its literal value without crashing the app.
https://github.com/mozmeao/springfield/issues/167
Before: https://opengraph.dev/panel?url=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Ffeatures%2Ftranslate%2F
After: https://opengraph.dev/panel?url=https%3A%2F%2Fwww-dev.springfield.moz.works%2Fen-US%2Ffeatures%2Ftranslate%2F
=> Remove missing cover reference from translate feature

bedrock/products/templates/products/landing.html
Reverts last SVG coord edit to get the outlined shape back.
This basically matches what is used in /all now.
Fixes #16287
/products
=> Fix product download icon

docs/docs/abtest.md
Add info about setting cookies to traffic cop docs
n/a
`make livedocs` http://127.0.0.1:8765/bedrock/abtest/#cookies-consent
=> Add info about setting cookies to traffic cop docs

bedrock/firefox/templates/firefox/more.html
Reverts one string id change that wasn't intentional.
The string id was a false friend (at the time used in /more as well as /faq) that got swept away with instances of an id being replaced elsewhere. This one was okay to stay nonetheless.
Fixes #16307
/firefox/more/
=> Fixup missing fx/more update description

bedrock/products/templates/products/vpn/landing-refresh-bundle-promo-experiment.html
The pricing section is missing when the variation is manually removed from the URL. This also happens going to the VPN homepage from Google on a PBM window
=> fix landing page pricing section issue when there is no variation

media/css/firefox/features/tips.scss
_If this changeset needs to go into the FXC codebase, please add the `WMO and FXC` label._ 👍 
Adds a missing import to have the asset available.  
When rebranding FxA, another CTA in footer was perhaps moved from -firefox to -mozilla product, and this occurrence was forgotten along the way. So it needs both.
Fixes #16322 
/firefox/features/tips
=> Fix product logo on features/tips

bedrock/firefox/templates/firefox/features/translate.html, bedrock/firefox/views.py
=> (feat) Add Arabic to list of locales supported by Firefox's Translate feature

bedrock/mozorg/templates/mozorg/about/includes/m24/news.html
Fixes outdated image paths that are used as fallback when `picture` element is not supported
https://github.com/mozilla/bedrock/issues/16346
- Check the image `url` matches one of the `srcset` urls in `sources` argument
- News section images should load as usual
=> Update img src attributes on about news section (fixes #16346)

bedrock/base/templates/includes/banners/pencil-banner.html, bedrock/mozorg/templates/mozorg/home/home-m24.html, media/js/base/banners/m24-pencil-banner-mofo-experiment.es6.js, media/static-bundles.json
This PR adds MOFO donation pencil banner experiment
- variations
- languages
- DNT/GPC enabled users see content in variant b and has a different cta link
https://github.com/mozilla/bedrock/issues/16329
Test for `en`, `fr`, `de`, `pt-BR`, `pl`, `it`, `es-ES`
http://localhost:8000/en-US/?v=a
http://localhost:8000/en-US/?v=b
http://localhost:8000/en-US/?v=c
=> add MOFO donation pencil banner experiment (fix #16329)

bedrock/firefox/templates/firefox/releases/notes.html
_If this changeset needs to go into the FXC codebase, please add the `WMO and FXC` label._ 🔥🦊 yeah
Adds `id` anchors to all note/tag headings.
Thoroughly checked for `id` uniqueness, whether there wouldn't be a clash with the same _id_ already existing for something on such pages, but seems safe.
Resolves #16277 (also closes https://github.com/mozilla/nucleus/issues/1077 …)
http://localhost:8000/en-US/firefox/139.0/releasenotes/#known
http://localhost:8000/en-US/firefox/139.0/releasenotes/#community
http://localhost:8000/en-US/firefox/139.0/releasenotes/#html5
=> Add anchors for all release notes headings

.github/workflows/send_mozorg_fluent_strings_to_l10n_org.yml
Moves running the l10n PR for a given SHA from push to workflow completion.
This will be run for every commit on main, not just those touching l10n files. — Tuning down the cron schedule to compensate for that and rut it only once a day as a fallback.
Set to run a few minutes after springfield intentionally.
https://github.com/mozmeao/springfield/issues/250#issuecomment-2941088776
Similar to [`send_firefox_fluent_strings_to_l10n_org.yml`](https://github.com/mozmeao/springfield/actions/workflows/send_firefox_fluent_strings_to_l10n_org.yml)
=> Run open-ftl-pr after artifact build+push

bedrock/mozorg/templates/mozorg/advertising/formats.html
… already uploaded to assets.mozilla.net
Resolves #16368 
Check the target of the `Download PDF` link on http://localhost:8000/en-US/advertising/formats/
=> (feat) Point to new advertising standards PDF,

bedrock/mozorg/templates/mozorg/advertising/formats.html
Updates ad PDF after some upload/caching weirdness 
Depends on https://github.com/mozmeao/assets.mozilla.net/pull/38 - Merged
https://github.com/mozilla/bedrock/issues/16389
=> Remove WIP meta title from pdf by pointing to new asset

root_files/.well-known/org.flathub.VerifiedApps.txt
Add .well-known/org.flathub.VerifiedApps.txt for org.mozilla.vpn
This adds a static file to the `.well-known` directory to complete [app verification](https://docs.flathub.org/docs/for-app-authors/verification) for the [org.mozilla.vpn](https://flathub.org/apps/org.mozilla.vpn) app on Flathub.
Github: flathub/org.mozilla.vpn#1
JIRA:
- [SREIN-173](https://mozilla-hub.atlassian.net/browse/SREIN-173)
- [VPN-7151](https://mozilla-hub.atlassian.net/browse/VPN-7151)
=> Add .well-known/org.flathub.VerifiedApps.txt for org.mozilla.vpn

.github/l10n/linter_config.yml, bedrock/base/templates/includes/protocol/footer/footer-refresh.html, bedrock/firefox/templates/firefox/developer/includes/mdn-features.html, bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/firefox/templates/firefox/nightly/whatsnew.html, bedrock/privacy/templates/privacy/includes/privacy-basics.html, l10n/en/firefox/developer.ftl, l10n/en/firefox/new/desktop.ftl, l10n/en/firefox/nightly/whatsnew.ftl, l10n/en/footer-refresh.ftl, l10n/en/privacy/firefox.ftl
This PR removes expired l10n strings
https://github.com/mozilla/bedrock/issues/16413
=> clean up expired l10n strings (fix #16413)

tests/functional/test_cdn.py
Use different pages to verify caches, accept-language vary, or locale fixups.
Nothing too specific was being checked on that exact pages so any that are supposed to stay active for /de/ too should just do.
#16355
`docker compose run test pytest --base-url https://www.mozilla.org -m cdn`
=> Update general CDN test URLs to something more permanent

bedrock/firefox/tests/test_redirects.py
Makes sure to assert `EXPECTED_FIREFOX_COM_REDIRECT_CODE`
Two recently added test cases adjusted to follow the setup above.
#16355
`MAKE_FIREFOX_COM_REDIRECTS_PERMANENT=False pytest bedrock/firefox`
`MAKE_FIREFOX_COM_REDIRECTS_PERMANENT=True pytest bedrock/firefox`
=> Update more redirect tests for permanent setting

bedrock/firefox/redirects.py, tests/redirects/map_globalconf.py
There are still quite a few other routes that target the `firefox.new` view, or `/firefox/new/` as a path, but we'll tackle those in a separate cleanup: https://github.com/mozilla/bedrock/issues/16431
This is being done to remove the extra hop, for SEO good vibes
=> Amend redirects from /firefox/ to go straight to www.firefox.com

bedrock/base/templatetags/helpers.py, bedrock/base/tests/test_helpers.py
See mozmeao/springfield#276
This combination was not hit here before, so it only exhibited itself with empty CMS data.
https://github.com/mozmeao/springfield/issues/268
Ideally if this could be pushed to a vacant demo to test drive for a bit, locally all seems fine.
=> Handle edge case in locale-list building when prefer_cms is used but there is nothing yet in the CMS

docs/docs/attribution/0002-firefox-desktop.md, docs/docs/firefox-downloads/desktop-download-as-default.md, docs/docs/firefox-downloads/desktop-download-pages.md, docs/docs/mozilla-accounts.md
Update docs for download pages.
Update docs to reflect changes in https://github.com/mozmeao/springfield/pull/366
n/a
[`make livedocs`](https://mozilla.github.io/bedrock/install/?h=livedoc#local_2)
http://127.0.0.1:8765/bedrock/firefox-downloads/desktop-download-as-default/
=> Update docs for download pages

bedrock/products/templates/products/monitor/cms/article.html, bedrock/settings/base.py, media/css/cms/rich-text.scss
Add styles to left and right align images in Monitor Article Page richtext blocks.
- Add Arabic to the available CMS languages when on DEV to make it eaasier to test CMS content on RTL layouts
- Apply CMS styles to the Monitor Article page
- Add styles to left and right align images on richtext blocks
#16150 
- Go to `http://localhost:8000/cms-admin/locales/new/` and create the Arabic locale
- Create a Monitor Article page and add left and right aligned images to the content
- Translate the page to Arabic
- Preview the translated page to check that the image alignments are inverted
=> 16150 Richtext Image alignment

bedrock/firefox/redirects.py
This is not gated behind any preference or a switch of any kind, so can't be changed without shipping actual code changes.
Once this merges, if any other thing needs to ship, this might sail with it all the way… so only merge once comfortable with the longer cache (for BOTH the location, AND the 301 actual code)
Removes shorter caching applied wholesale to all fxc offiste redirects.
Given how 301s are cached aggressively, as a code+location lookahead, often way beyond the max-age headers, this should not make that much difference now, as even the 3hr 301s will most likely be cached for way longer already.
#16355
`make test`
`curl -I http://localhost:8000/firefox/all/`
=> Cache offsite redirects normally

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx142beta.html, media/css/firefox/whatsnew/whatsnew-142beta.scss
Use alpha-PNG of the image to float the text content against the cartoon.
Also move the heading to the top.
#16429 
http://localhost:8000/en-US/firefox/142.3beta/whatsnew/
I've reserved demo7 for stakeholder review if I could ask for a deploy when convenient, but this has been pre-approved already.
=> Add some fun to 142beta WNP layout

bedrock/base/templates/includes/protocol/footer/footer-refresh.html, l10n/en/footer-refresh.ftl
Add a localized "Security" link to the Support section in the footer.
- Added `footer-refresh-security` string to FTL.
- Inserted a new link under the Support section in the footer template pointing to https://www.mozilla.org/security/ .
Closes #16239
=> Add link to Mozilla Security to footer

.gitignore
(Kind of an "empty commit" to trigger fresh tag builds to purge container caches.)
Cleans out `.gitignore` rules from tech no longer used around the repo.
James, sphinx, nose, and sitemaps/etags are long gone.
🚫🐞
=> Remove unused tooling from .gitignore

.github/workflows/build-and-push.yml, .github/workflows/pull_request_tests.yml
⬆️🔥🦊
Until GHA update to a patched version in the runner image and deploy.
https://github.com/actions/runner-images/pull/12669 made a breaking update that enabled `COMPOSE_BAKE` by default. That also had followup fixes released that are necessary for successful runs, however the current GHA runner images deployed ship a version that leaves the build process hanging indefinitely. https://github.com/docker/compose/issues/12998
We need to disable it until a new runner image ships with a version bumped further. Also note it's already reported as deprecated, to `COMPOSE_BAKE=false` be ignored/removed completely in an upcoming release.
https://github.com/actions/runner-images/issues/12685
(Supersedes …
=> Hotfix optout of bake builder in CI

bedrock/sitemaps/tests/test_utils.py, bedrock/sitemaps/utils.py
Removes releases-related URLs from sitemap generation data.
These are exposed in FXC sitemaps that are the canonical source of the pages now.
#16381 
[`@mozmeao/www-site-checker`/actions/runs/16883546251/job/47825284604](https://github.com/mozmeao/www-site-checker/actions/runs/16883546251/job/47825284604)
=> Stop exposing release_notes_urls to sitemaps

bedrock/settings/base.py, lib/l10n_utils/__init__.py
_If this changeset needs to go into the FXC codebase, please add the WMO and FXC label._  👍 ➕ 🔥🦊
Removes code for "Edit on GitHub" footer links long gone.
Since #7373 was labeled _wontfix_ and it's therefore not coming back, there's no reason to keep old code for that around. It might have been actually causing 500s? https://github.com/mozilla/bedrock/issues/14667#issuecomment-2160950302
Hopefully resolves #14667
=> Remove `template_source_url` context and settings for unused GH edit links

media/js/base/protocol/m24-navigation.es6.js
Checks for the object availability correctly.
Will need porting upstream, too.
https://github.com/mozmeao/springfield/issues/380
_(should be in fxc prod already, have the reports calmed down?)_
=> Fix typeof check for MzpSupports in navigation

media/css/careers/components/hero-text.scss, media/css/careers/components/hero-video.scss, media/css/careers/components/home.scss
This PR updates the color theme for career pages.
- hero overloay
- hero text color
- callout text color
https://github.com/mozilla/bedrock/issues/16503
http://localhost:8000/en-US/careers/listings/
=> update career pages theme (fix #16503)

.github/l10n/linter_config.yml, bedrock/products/templates/products/vpn/platforms/windows.html, l10n/en/products/vpn/platforms/windows_v2.ftl
This PR update VPN branding l10n string to be `{ -brand-name-mozilla-vpn }`
https://github.com/mozilla/bedrock/issues/16496
=> update VPN branding l10n string (fix #16496)

bedrock/base/templates/macros.html, bedrock/firefox/templates/firefox/includes/send-to-device.html, bedrock/firefox/templates/firefox/testflight.html, bedrock/mozorg/templates/mozorg/antiharassment-tool.html, bedrock/products/templates/products/vpn/invite.html, l10n/en/send_to_device.ftl
Add different attributes to email input fields across templates to resolve DevTools warnings.
Fixes #15889
=> Add autocomplete attributes for email input fields

media/js/base/fxa-attribution.es6.js, media/js/base/fxa-coupon.es6.js, media/js/base/fxa-product-button.es6.js
Allow passing attribution parameters to SubPlat 3's new `payments.firefox.com` domain.
SubPlat 3 pages are hosted on the `payments.firefox.com` domain rather than `accounts.firefox.com` like before, so the new `payments.firefox.com` domain should be allowed to receive attribution parameters like the `accounts.firefox.com` is.
* [VPN-7226](https://mozilla-hub.atlassian.net/browse/VPN-7226): Fix attribution problem in Mozilla VPNs website
* Upon landing on the [Mozilla VPN product page](https://www.mozilla.org/en-US/products/vpn/) with any of the Bedrock-supported UTM parameters, clicking on the "Get annual subscription" and "Get monthly subscription" links should take users to the SubPlat 3.0 URL with the same UTM parameter values propagated through.
=> fix(attribution): Allow passing attribution parameters to SubPlat 3 (VPN-7226)

bedrock/security/urls.py
Hides the json URL to start sending 404s to users before complete decommissioning.
Currently gone() redirect helpers don't handle locale prefixes, so a path removal is necessary to send error codes on all the locale prefixes for the feed path.
#16519
/pt-CV/security/advisories/cve-feed.json
=> Stop serving cve-feed.json on any path

bedrock/settings/base.py, media/js/base/fxa-attribution.es6.js, media/js/base/fxa-coupon.es6.js, media/js/base/fxa-product-button.es6.js
Update VPN subscription URLs
Fix #16564 
Test links for annual and monthly subscriptions (the URLs forward so inspect source to see they're inserted properly)
http://localhost:8000/en-US/products/vpn/ 
_Note: this is for staging so make sure you're not in prod mode._
=> Update VPN subscription URLs (Fix #16564)

bedrock/products/tests/test_views.py
This PR updates VPN landing page view tests.
All tests should pass.
https://github.com/mozilla/bedrock/issues/16314
`pytest bedrock/products/tests/test_views.py`
=> update VPN landing page view test (fix #16314)

media/css/products/vpn/bundle-promo.scss
Fixup bundle-promo css feature detection using a placeholder asset — as that is collected to be hashed and not found, failing the build.
It has no function there really, but given it's a url() path, it's considered a resource necessary for hashing and deployment.
Using the first nearest asset instead to reference in here — that should be kept around for this functionality anyway.
[/actions/runs/17957484179/job/51072450332](https://github.com/mozilla/bedrock/actions/runs/17957484179/job/51072450332#step:10:7233) ❌ 
`make build-prod`
=> Fixup css@supports url value to pass collectstatic and build

bedrock/products/templatetags/misc.py, bedrock/products/tests/test_helper_misc.py, bedrock/settings/base.py
Make vpn-subplat-next switch permanent
- no more plan IDs
#16386 
In both prod and non-prod mode links should take you to appropriate checkout pages (note: they go through a series of redirects first)
🟢  [run-integration-tests run](https://github.com/mozilla/bedrock/actions/runs/17781284922)
=> Make vpn-subplat-next switch permanent (Fix #16386)

bedrock/base/exceptions.py, bedrock/base/middleware.py, bedrock/base/templates/410.html, bedrock/base/tests/test_middleware.py, bedrock/base/tests/test_views.py, bedrock/base/tests/urls.py, bedrock/base/views.py, bedrock/redirects/util.py, bedrock/urls.py, l10n/en/410.ftl, lib/l10n_utils/__init__.py
Add 410 Gone error handling with custom view, template, and localization support
- Implemented a new 410 error handler in views and middleware
- Added URL routing for 410 errors in urls.py
- Created a 410 error template (410.html) for user-friendly messaging
- Updated tests to cover 404, 410 and 500 error scenarios
- Added localization support for 410 error messages in 410.ftl
> Note: I am not sure about the process for adding new localization strings to Pontoon/Smartling.
Fixes https://github.com/mozilla/bedrock/issues/8964
- Visit /en-US/410/ in development mode to verify 410 error page displays correctly
- Confirm proper status code (410) is returned
- Verify template renders with all localized strings
- Run `pytest lib bedrock`
=> Add 410 error page

bedrock/firefox/redirects.py, bedrock/firefox/tests/test_redirects.py
Readying this redirect for WNP 144, which will be on www.firefox.com but we can't guarantee that all sources of the traffic from FF itself will be pointing straight to www.firefox.com, so this covers that angle - but only for `144.0`
We need to double-check the destination path on www.firefox.com is definitely correct.
If it is, we can probably merge this now because there's an evergreen WNP waiting at the destination, thanks to @maureenlholland 
Resolves #16590
=> (feat) Support a redirect to www.firefox.com for WNP 144.0

bedrock/firefox/templates/firefox/whatsnew/base-new-theme.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx142.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx143-row.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx143-us.html
Fixes a campaign bug in the generated QR code, and updates other hardcoded places that avoided said bug.
Fixes QR code attribution in refresh template. Moves the following ones to that pattern.
Uses inheritance where possible to keep things in one place.
Fixes #16574
http://localhost:8000/en-US/firefox/142.0/whatsnew/
http://localhost:8000/en-US/firefox/143.0/whatsnew/
http://localhost:8000/en-GB/firefox/143.0/whatsnew/
=> Fix WNP attribution of major_version
