bedrock/firefox/templates/firefox/developer.html
bedrock/mozorg/templates/mozorg/download_firefox_button.html
media/css/firefox/developer.less
media/css/sandstone/buttons.less

Simply use the non-simple button, maybe?

Fix Bug 1097297 - Link to other systems & languages on the Firefox Developer Edition page

---

.gitmodules
.travis.yml
bedrock/legal/forms.py
bedrock/legal/templates/legal/emails/fraud-report.txt
bedrock/legal/tests.py
bedrock/legal/views.py
bedrock/mozorg/helpers/misc.py
bedrock/mozorg/templates/mozorg/emails/infos.txt
bedrock/mozorg/tests/test_views.py
bedrock/press/templates/press/emails/speaker-request.txt
bedrock/press/tests.py
vendor-local/vendor.pth

Django 1.6.9

---

docs/uitour.rst

Channel names [provided by MattN](https://bugzilla.mozilla.org/show_bug.cgi?id=1065525#c23).

Add defaultUpdateChannel info to UITour docs.

---

bedrock/firefox/templates/firefox/desktop/tips.html
media/css/firefox/desktop/tips.less
media/js/firefox/desktop/tips.js

* Fixes "Next" pager arrow pointing the wrong direction.
* Also fixes some small-screen layout issues in the header on RTL locales.

[fix bug 1121914] Next pager arrow wrong direction on /firefox/desktop/tips

---

bedrock/security/management/commands/update_security_advisories.py
bedrock/security/tests/test_commands.py

The updater looked for all files with a '.md' extension
that had bee modified. This was looking at README.md in
error. This fixes the behavior to only look at files named
'mfsaYYYY-NN.md'.

Fix security advisory updater including wrong files.

---

bedrock/legal/templates/legal/base-resp.html
bedrock/privacy/templates/privacy/base-resp.html

* Update Firefox Desktop Privacy Notice ([Bug 1121714](https://bugzilla.mozilla.org/show_bug.cgi?id=1121714))
* Load Firefox Hello docs of es-ES, ja and sr locales ([Bug 1121091](https://bugzilla.mozilla.org/show_bug.cgi?id=1121091))
* Include the `add_lang_files` flags to make l10n process easier ([Bug 1121091](https://bugzilla.mozilla.org/show_bug.cgi?id=1121091))

Fix Bug 1121714 - Firefox Desktop Privacy Notice Change (Telemetry Experiments & Domains / Flash)

---

etc/httpd/global.conf

Checking on dev, it looks like the redirect in #2645 didn't work correctly. I think this is just because it needs to be above the rule on Line 89. @jgmize r?

[bug 787269] Redirect signed-script pages to MDN article

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

Adding back in a special exception to show the original Australis /whatsnew tour for ESR31 users updating from ESR24. I've manually downloaded and tested that the /whatsnew tour still runs fine on ESR31

[fix bug 1121209] whatsnew page for ESR24 -> ESR31 updates doesn't show Australis tour

---

media/css/mozorg/home/home-promo.less
media/js/mozorg/home/home.js

Minor regression from #2518
As a side-note, I don't feel too great about having to add more instances of `!important` on other pages where this is used. This is ok for now, but perhaps a better long term option might be to show these links using a configurable option passed in with the download button helper?

[fix bug 1122462] Download Firefox homepage promo missing small links

---

media/js/base/global.js
media/js/test/spec/global.js

On a related note, it no longer seems that [`data-esr-versions`](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/base-resp.html#L6) is used. As it doesn't hurt anything, and may be of use in the future, did not remove from the templates.

Ignore ESR when checking isFirefoxUpToDate. Bug 1122154.

---

bedrock/settings/base.py
media/css/base/svg-animation-check.less
media/js/base/svg-animation-check.js
media/js/firefox/desktop/intro-anim.js
media/js/firefox/hello/index.js

We need to update our UA check for IE Edge, which sadly still can't animate SVG paths using CSS (even though it "supports" all the right bits). :sob: 
Tested with the following UA: `Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0`

[fix bug 1122519] CSS/SVG line animation does not work in IE (Edge mode) Win 10

---

bedrock/security/views.py

The docs could be localized in some way in the future, so I haven’t added redirect tests yet.

Fix Bug 1125011 - Non-existent security advisory translations are not redirected to en-US

---

bedrock/firefox/templates/firefox/nightly_firstrun.html
bedrock/mozorg/templates/mozorg/about/governance/policies/commit.html
bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
bedrock/mozorg/templates/mozorg/about/governance/policies/commit/requirements.html
bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
bedrock/mozorg/templates/mozorg/about/governance/policies/policies.html
bedrock/mozorg/templates/mozorg/about/governance/policies/security/bugs.html
bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/inclusion.html
bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/maintenance.html

- replace {%endblock%} by {% endblock %}
- fix a bug in nightly firefox firstrun page which didn't have a date set for the promo_locale l10n block
The issues above were causing parsing errors of templates when using the './manage.py l10n_check' command
- remove empty <p>{{ _('') }}</p> (no visual impact on the page after removing it)
This issue was causing a warning in the logs:
"warning: Empty msgid.  It is reserved by GNU gettext: gettext("") returns the header entry with meta information, not the empty string."
Note that a couple of trailing spaces in the templates were removed.

Bug 1128957 - Fix block parsing errors in jinja templates

---

bedrock/firefox/templates/firefox/dnt.html

new link: https://support.mozilla.org/kb/private-browsing-browse-web-without-saving-info

[Bug 1129481] updated sumo link to be locale-neutral

---

media/js/base/global.js
media/js/plugincheck/check-plugins.js
media/js/test/spec/global.js

This is the same ESR user detection as I recently implemented on Tabzilla in #2680.

Fix Bug 1128885 - Plugincheck-site considers 31.4.0ESR out of date

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit.html

This page has not been localized so no need to wait l10n. Very chore-ish. Such a paragrach. Wow.

Fix Bug 1129911 - Text error in https://www.mozilla.org/en-US/about/governance/policies/commit/

---

bedrock/mozorg/templates/mozorg/contact/communities/myanmar.html

We have shut down our old Facebook page and now we are using the new one to post community updates.
Facebook Link: https://www.facebook.com/mozillamyanmar

Bug 1131060 - Mozilla Myanmar Community's Facebook Page Link Update

---

bedrock/security/management/commands/update_security_advisories.py
bedrock/security/templates/security/advisory.html

Also remove transaction management from update
advisories command as it breaks things in dev
mode (sqlite) and isn't necessary for this.

Fix bug 1131738: Mark advisory reporter as safe.

---

bedrock/security/templates/security/product-advisories.html
media/css/security/security.less

I pushed -f the branch before committing and #2710 was automatically closed :confused: I cannot reopen the PR so let me try again... :abillings agreed in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1130160) to use hidden anchors I proposed, rather than removing those # signs entirely.

Fix Bug 1130160 - Extra '#' in section headers for roll up pages

---

bedrock/firefox/templates/firefox/os/_get_device.html

A hyphen needs to be removed from the link to point to the proper product page for the ONETOUCH Fire E.

fix Bug 1108278: congstar link is incorrect

---

bedrock/styleguide/templates/styleguide/communications/copy-rules.html

As I described in the bug [1], the heading ID for Tabzilla causes the menu to show up in the middle of the copy rules page [2] instead of the actual "Tabzilla" heading. This commit changes the ID to "tabzilla-heading" so as to not conflict with the Tabzilla CSS.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1132323
[2] https://www.mozilla.org/en-US/styleguide/communications/copy-rules/

Bug 1132323: change Tabzilla heading ID

---

media/js/test/spec/mozilla-image-helper.js

#2733 refactored the platform image helper, so here's updated JS tests to reflect the new behavior

Update Mozilla.ImageHelper JS tests

---

bedrock/privacy/views.py

This issue is caused by a common Markdown error where localized dates are not properly formatted. Continue the loop if `tag.name` doesn't exist. In such cases, dates like `08. svibnja 2013.` will just be `svibnja 2013.` so it should be safe.
This includes a legal-docs submodule update from https://github.com/mozilla/legal-docs/pull/289.

Fix Bug 1132956 - Legal-docs pages for hu and hr throwing errors.

---

media/css/sandstone/sandstone-resp.less
media/js/newsletter/form.js

Fix .form-details not expanding when .footer-newsletter-form gets focus and let the .form-details inherit the text colour of what it's inside of.

Fix Bug 1134058: Show .form-details when form has focus

---

media/js/firefox/firefox-language-search.js

Enable the language filtering without hitting Enter.

Fix Bug 1134936 - Firefox download pages: filter localized builds as you type

---

bedrock/mozorg/models.py

This looks like it would fail at some point. Python
magic is keeping it going I guess. Referencing the manager
instance from the manager class seems bad though.

Fix a potential error in the TwitterCacheManager.

---

bedrock/mozorg/migrations/0002_auto__add_contributoractivity__add_unique_contributoractivity_date_sou.py
bedrock/mozorg/models.py
bedrock/mozorg/tests/test_views.py
bedrock/mozorg/urls.py
bedrock/mozorg/util.py
bedrock/mozorg/views.py
bedrock/settings/base.py
etc/cron.d/bedrock-prod.tmpl
etc/cron.d/bedrock-stage.tmpl
etc/httpd/global.conf
scripts/update_tableau_data.py

Pulls in contributor data directly from the Tableau DB. These
data are published to tableau once a week. Provides a JSON view
for the various views of the data which is set to be cached for
a week. Adds the Apache config for the new URLs. Adds cron jobs
for stage and prod to sync the data weekly. Does not yet remove
the old static files, will do that once the working copies of
the site are using the new datasource.

Bug 1116511: Add tableau data sync and JSON view for MozID.

---

bedrock/base/templates/macros.html
bedrock/firefox/templates/firefox/hello/index.html
bedrock/mozorg/templates/mozorg/plugincheck.html
bedrock/settings/base.py
media/css/base/mozilla-share-cta.less
media/css/firefox/hello/index.less
media/css/plugincheck/plugincheck.less
media/css/privacy/privacy-day.less

Borrowed @jpetto’s work in #2684, includes the following improvements:
* Add the `sky` and `mini` classes to make the styles reusable
* Make the buttons work even when JavaScript is disabled
* Fix the URL encoding
* Use `<aside>`

Fix Bug 1131309 - Add share buttons to 'Check your plugins' page

---

bedrock/mozorg/templates/mozorg/home/home-new.html
media/css/mozorg/home/home-promo.less
media/img/home/voices/promos/hello/hello.svg

Bug 1126956 - Restore Android and Advocacy promos
Bug 1131854 - Firefox Hello promo
Bug 1132231 - update Webmaker promo
@flodolo: We should be all set to release this in English first and other locales can update at their convenience. There are new l10n tags ('hello_promo' and 'webmaker_promo_make') and some others that are reused. I'm reusing 'privacy_day' for the advocacy promo, which was removed and has come back, but it looks like many locales still have the string under that tag. The dev browser promo has moved but the strings are the same so it can continue using the 'fx10_independent' tag, and the same for 'gear_store'. Let me know if I've missed anything.
@jgmize: The new waffle switch 'mozorg-home-neutrality-promo' should be active when this update goes to prod and deactivate at …

Update home page promos

---

bedrock/mozorg/templates/mozorg/home/home-new.html

Per Matej on IRC, I messed up the copy on the Webmaker and Hello promos (small errors, but annoying, and totally my fault).
@flodolo: I am really REALLY sorry about this. If necessary I can wrap these altered strings in yet another tag, if any locales have already updated based on the strings from yesterday. Please tell me what I can do to earn your forgiveness.

Bug 1132231 - fix copy for Webmaker and Hello promos

---

bedrock/firefox/templates/firefox/os/mwc-2015-preview.html

Nothing on the bug for this - it's a direct request from Matej on IRC:
> *matej:* I should have caught this sooner, but can we update the title?
> *matej:* should be "Unleash the Future — Firefox OS — MWC 2015 — Mozilla"

Bug 1120689 Update title on MWC preview for 2015

---

bedrock/security/management/commands/update_security_advisories.py
etc/cron.d/bedrock-prod.tmpl

Reports errors on stderr so we can get cron mail when it happens. The --quiet should mean there's no other output, but we're still sending stdout to /dev/null in the cron.

Fix bug 1136307: Catch all errors and report exceptions for MFSA import.

---

bedrock/styleguide/templates/styleguide/communications/presentations.html
bedrock/styleguide/templates/styleguide/communications/typefaces.html
bedrock/styleguide/templates/styleguide/communications/video.html
bedrock/styleguide/templates/styleguide/identity/firefox-branding.html
bedrock/styleguide/templates/styleguide/identity/firefox-channels.html
bedrock/styleguide/templates/styleguide/identity/firefox-wordmarks.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-branding.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-community.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-partners.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-typography.html
bedrock/styleguide/templates/styleguide/identity/marketplace-branding.html
bedrock/styleguide/templates/styleguide/identity/mozilla-branding.html
bedrock/styleguide/templates/styleguide/identity/mozilla-color.html
bedrock/styleguide/templates/styleguide/identity/thunderbird-channels.html
bedrock/styleguide/templates/styleguide/identity/thunderbird-logo.html
bedrock/styleguide/templates/styleguide/identity/thunderbird-wordmarks.html
bedrock/styleguide/templates/styleguide/identity/webmaker-branding.html
bedrock/styleguide/templates/styleguide/products/firefox-os/action-icons.html
bedrock/styleguide/templates/styleguide/products/firefox-os/icons.html
bedrock/styleguide/templates/styleguide/websites/sandstone-buttons.html
bedrock/styleguide/templates/styleguide/websites/sandstone-colors.html
bedrock/styleguide/templates/styleguide/websites/sandstone-grids.html

Bug 1134492 - move assets.mozilla.org to assets.mozillalabs.com
Updated the links in the html templates  that pointed towards
assets.mozilla.org to point to assets.mozillalabs.org as a first step
in resolving this issue

Bug 1134492 - move assets.mozilla.org to assets.mozillalabs.com

---

bin/update-scripts/dev/update-dev-django.sh
etc/cron.d/bedrock-dev.tmpl

I looked at the logs and dev was being deployed more often
than it should have based on changes in master. This is due
to the request to www-dev.m.o/media/revision.txt sometimes
returning a 500 page. This is seen by the script as different
from the hash on github, and thus it deploys. The problem is that
this error is most likely just the previous deploy finishing up since
deploys now take longer than before. This change both reduces the
frequency of autodeploys to every 20 min and checks the local
revision.txt for what is currently deployed. We might consider
moving to a python-based autodeploy script in future for more
flexibility in checking things on the dev server and github.

Get current hash from local file and run dev autodeploy every 20min.

---

bedrock/security/templates/security/advisories.html

This seems my typo introduced with #2437 :blush:

Fix Bug 1137604 - /security/advisories: abbreviation mismatch: MSFA vs. MFSA

---

bedrock/firefox/templates/firefox/os/mwc-2015-preview.html
media/css/firefox/os/mwc-2015-preview.less

This replaces #2791. It turns out the "All press" link can be en-US only, since this page isn't localized.

Bug 1137904 mwc page headlines

---

bin/update/deploy_base.py

It's updated by cron so this is superfluous.

Remove locale update from deployment.

---

media/css/firefox/partners.less

Mobile partners nav was overlapping family nav submneu due to excessive z-index
See: https://bug1120686.bugzilla.mozilla.org/attachment.cgi?id=8570829&t=7CniihHlyO

Bug 1120686 Fix overlaping menus

---

bin/update/deploy_base.py

This will keep older static files around so that pushes _should_ be
less error prone.

Update static files, product-details, and external files in SRC dir.

---

bedrock/firefox/templates/firefox/os/index.html

The title was changed for the old template, not the new one.
At this point we can't add the new one to the new template without breaking all locales (strings are missing). I suggest waiting for the next update of the page to fix it, since it shouldn't be too far ahead.
This PR restores the existing title for the old template: for locales using the old template, we're currently showing English text.

Bug 1120700 - Fx OS consumer page: restore page title on old template

---

bedrock/firefox/templates/firefox/os/mwc-2015-preview.html
media/css/firefox/os/mwc-2015-preview.less

* Move LG into alphabetical order.
* Add bottom margins between logos on mobile.
* Arrange logos two per row for wide mobile.

Fix bug 1138169 - MWC partner logo updates

---

bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
bedrock/firefox/templates/firefox/all.html
bedrock/firefox/templates/firefox/developer.html
bedrock/firefox/templates/firefox/hello/index.html
bedrock/mozorg/templates/mozorg/plugincheck.html
bedrock/settings/base.py
media/css/base/mozilla-share-cta.less
media/css/firefox/hello/index.less
media/css/plugincheck/plugincheck.less

Here’s another optimization. Introducing the new `site_header_share` block to put the button in `#masthead`. The change will affect the existing [/firefox/hello/](https://www.mozilla.org/en-US/firefox/hello/) and [/plugincheck/](https://www.mozilla.org/en-US/plugincheck/) pages.
This [/firefox/all/](https://www.mozilla.org/en-US/firefox/all/) page has been localized into Japanese only and we have almost the same fallback text, so this is good to go.
I have added one more button for [/firefox/developer/](https://www.mozilla.org/en-US/firefox/developer/) because the change is small and similar. This time again, the existing copy will be used as the l10n fallback.
@alexgibson r?

Fix Bug 1131304 - Add share buttons to 'Download Firefox in your language' page

---

media/js/firefox/firefox-language-search.js

A UX improvement to follow up #2756 that implemented incremental language search on the Firefox download pages.
I have noticed that I cannot go back to the previous page after filtering, because a new history entry is added as I type. It’s actually annoying. It may be better to use `history.replaceState` rather than `history.pushState`. Also, the query param should be removed when the search term is cleared.

Replace history when languages are filtered on download pages, instead of appending (Bug 1134936 follow-up)

---

bin/update-scripts/dev/update-dev-django.sh
bin/update-scripts/prod/update-prod-locale-cron.sh
bin/update-scripts/prod/update-prod-locale.sh
bin/update-scripts/prod/update-prod-php.sh
bin/update-scripts/prod/update-prod-product-details.sh
bin/update-scripts/stage/update-stage-locale.sh
bin/update-scripts/stage/update-stage-php.sh
bin/update/deploy-product-details.py
etc/cron.d/bedrock-dev.tmpl
etc/cron.d/bedrock-prod.tmpl
etc/cron.d/bedrock-stage.tmpl

Moves the scripts run by cron to this repo. Also included is the script to update product-details, but I believe we have to alter chief to have it be the one that is run, or at least symlink to this one from the original path.

Fix bug 1135693: Add update scripts to repo.

---

bedrock/styleguide/templates/styleguide/communications/presentations.html
bedrock/styleguide/templates/styleguide/communications/typefaces.html
bedrock/styleguide/templates/styleguide/communications/video.html
bedrock/styleguide/templates/styleguide/identity/firefox-branding.html
bedrock/styleguide/templates/styleguide/identity/firefox-channels.html
bedrock/styleguide/templates/styleguide/identity/firefox-wordmarks.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-branding.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-community.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-partners.html
bedrock/styleguide/templates/styleguide/identity/firefoxos-typography.html
bedrock/styleguide/templates/styleguide/identity/marketplace-branding.html
bedrock/styleguide/templates/styleguide/identity/mozilla-branding.html
bedrock/styleguide/templates/styleguide/identity/mozilla-color.html
bedrock/styleguide/templates/styleguide/identity/thunderbird-channels.html
bedrock/styleguide/templates/styleguide/identity/thunderbird-logo.html
bedrock/styleguide/templates/styleguide/identity/thunderbird-wordmarks.html
bedrock/styleguide/templates/styleguide/identity/webmaker-branding.html
bedrock/styleguide/templates/styleguide/products/firefox-os/action-icons.html
bedrock/styleguide/templates/styleguide/products/firefox-os/icons.html
bedrock/styleguide/templates/styleguide/websites/sandstone-buttons.html
bedrock/styleguide/templates/styleguide/websites/sandstone-colors.html
bedrock/styleguide/templates/styleguide/websites/sandstone-grids.html

Updated the links in the html templates  that pointed towards
assets.mozillalabs.org to point to assets.mozilla.org but to new urls
as the final part of fixing this issue.

Fix bug 1134492 - update templates to new urls on assets.mozilla.org

---

media/js/mozorg/contact-spaces.js

Small follow-up to #2802:
The latest mapbox update introduced some super high-res map tiles, which are a bit too heavy for some touch devices (like my aging iPad). This change will make it so only the standard tiles are loaded on touch devices, which are generally lesser powered compared to desktop browsers.
I've put this up on demo3 and verified things are much quicker again :+1:  https://www-demo3.allizom.org/en-US/contact/spaces/

[fix bug 1139938] Contact pages should load low-res mapbox tiles for touch devices

---

bedrock/mozorg/templates/mozorg/credits-faq.html

index.html in SVN no longer gets updated per-checkin, so the URL to see recent checkins is wrong. Also a few textual updates.

Bug 1142510 - Update credits FAQ to fix inaccuracies and bad URL

---

.travis.yml
bedrock/externalfiles/__init__.py
bedrock/externalfiles/management/commands/update_externalfiles.py
bedrock/mozorg/credits.py
bedrock/mozorg/tests/test_credits.py
bin/gen-crons.py
bin/update-scripts/prod/update-externalfiles.sh
bin/update-scripts/stage/update-externalfiles.sh
bin/update/deploy_base.py
etc/cron.d/bedrock-prod.tmpl
etc/cron.d/bedrock-stage.tmpl

Also alter the `gen-crons.py` script to have an option to disable creation of the log dir for local test runs. This still runs the check when testing while there is a value in the env var CRON_LOG_DIR, so Travis will still hit that branch of the code.

Fix bug 1142850: Add cron job to update external files hourly.

---

contribute.json

Looking at @Osmose's awesome new https://mozilla.github.io/webdev/ it's clear that our old url for `participate.home` isn't that useful. This should be better.

Make contribute.json participate.home more useful.

---

bedrock/mozorg/middleware.py
bedrock/mozorg/tests/test_middleware.py
bedrock/settings/base.py
etc/httpd/global.conf

Also only include the header when response is a 200
and for a page.

Move Clacks-Overhead handling to bedrock.

---

bedrock/firefox/templates/firefox/android/sms-thankyou.html
bedrock/settings/base.py
media/css/firefox/mobile-sms.less

Replacing the current Share widget with the new one. This page is en-US only, no l10n required.
https://www.mozilla.org/en-US/firefox/sms/sent/

Fix Bug 1133780 - Update social sharing on firefox/sms

---

docs/tabzilla.rst

Part of [Bug 1147139](https://bugzilla.mozilla.org/show_bug.cgi?id=1147139). mozilla.org is no longer serving content via http.

Update Tabzilla document to recommend using https, not protocol relative URLs

---

bedrock/settings/base.py
etc/httpd/global.conf

We have enough content for these locales to enable them on production.

Bug 1117893 - Enable 'ee' and 'yo' on prod

---

bedrock/firefox/templates/firefox/android/sms-send.html

No l10n required. I would be nice to have it in today's push.

Fix Bug 1146474 - Update /en-US/firefox/sms/ With Legal Text & Link

---

bedrock/firefox/firefox_details.py
bedrock/firefox/helpers.py
bedrock/firefox/templates/firefox/all.html
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py

Note: this PR changes the download button code as well for consistency, but the win64 buttons are being disabled by CSS for now. So the visible changes is /firefox/beta/all/ only as requested in the bug.

Fix Bug 1150083 - Make Fx38 Win64 build of beta Available on moz.org

---

bedrock/mozorg/credits.py

A simple mistake. The cache is returning `3600` instead of names, leading to a TypeError.

Fix Bug 1148557 - /en-US/credit page gives 404: Page Not Found

---

bedrock/tabzilla/templates/tabzilla/tabzilla.js

Currently the language switcher will not work, if a site using tabzilla doesn't have Google Analytics, since the actual event action will never be executed.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1151538
See also #2893

Fix Bug 1151538 - Execute callback in tabzilla when GA isn't defined

---

bedrock/firefox/templates/firefox/australis/fx36/firstrun-tour.html

Add waffle switch 'firefox-firstrun-optimizely'

Add optimizely to firstrun: fix bug 1128708

---

requirements/base.txt
requirements/dev.txt

funfactory adds django_nose to INSTALLED_APPS,
so it has to be installed in all envs.

Move django-nose and nose to base requirements.

---

bedrock/firefox/templates/firefox/channel.html
bedrock/firefox/templates/firefox/whatsnew.html
bedrock/foundation/templates/foundation/feed-icon-guidelines/faq.html
bedrock/foundation/templates/foundation/trademarks/policy.html
bedrock/foundation/templates/foundation/trademarks/poweredby/faq.html
bedrock/press/templates/press/speaker-request.html

While looking at [Bug 1146683](https://bugzilla.mozilla.org/show_bug.cgi?id=1146683) I have noticed that some links using `php_url` can be updated. The rest of the links are /MPL/ and /thunderbird/, but as I mentioned in the bug, this function could be retired now.

Update some php_url links

---

bedrock/firefox/templates/firefox/whatsnew-fx37.html

Added waffle switch `firefox-whatsnew-optimizely`

[fix bug 1155830] Enable Optimizely on Firefox 37 whatsnew page

---

bedrock/firefox/templates/firefox/includes/download-button.html

We need to expose those strings to meet the l10n string freeze on April 23. The logic behind the button is coming later.

Add strings for iOS download button, part of Bug 1139961

---

media/css/base/mozid-modal.less

* Makes the  `.window .inner header` selector less broad, to avoid overriding modal content styles should the content also contain a `header` element.
* Adjusts the desktop `#modal .inner` width to fit the grid, and avoid slight overspill when resizing the browser window.
* Removed extraneous `transition: all` on modal `<header>`

Update responsive styling for mozid modal

---

bedrock/base/templates/includes/site-footer.html

The new string is now localized in 57 locales ( ~90% of our l10n user base). Time to remove the switch.

Bug 1144949 - Use "Contribute to this site" for all locales

---

bedrock/base/tests/test_accepted_locales.py
bedrock/mozorg/tests/test_views.py

Moved parens to eliminate "always true" assertions
Removed deprecated simplejson module

Fix syntax and deprecation warnings in tests

---

bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html

Also removed some outdated content (doesn't impact the overall guidelines)
@flodolo: This page doesn't seem to be localized so these content changes shouldn't need an l10n flag. Can you verify?

Fix bug 1156822 - update contact info in participation guidelines

---

bedrock/mozorg/tests/test_views.py
bedrock/mozorg/views.py

The partnership page form did not properly sanitize user input
before including it in the page via AJAX.

Fix bug 945845: Escape error messages sent via AJAX.

---

bedrock/base/templates/includes/site-footer.html
bedrock/mozorg/templates/mozorg/contribute/studentambassadors/landing.html
bedrock/mozorg/templates/mozorg/plugincheck.html

The rest of the links may be updated later once the legal team decides what should they do.
"Firefox Friends" won't probably be localized so l10n shouldn't be a blocker here.

Bug 1164300 - Remove/Update Affiliates Links on moz.org properties, part 1

---

bedrock/settings/__init__.py
bedrock/settings/base.py
requirements/prod.txt

This will not change anything immediately. We still need
to change the local settings in the environments after
deployment of the changes.

Fix bug 1152344: Use django-pylibmc for default cache backend.

---

bedrock/firefox/templates/firefox/hello/index.html
media/css/firefox/hello/index.less
media/js/firefox/hello/index.js

Tested locally with the `browser.uitour.testingOrigins` pref enabled on 38 ESR .
Because this code is only run by Firefox 35+, it might be safe to use `Promise` here, rather than adding another nested callback.
L10n note: There is one new string: “Sorry, Hello is not yet available in Firefox ESR.” Another one, “Get Firefox” is in firefox/desktop/tips.lang so it’s not new. Given the number of Firefox 38 ESR users who will see this message is very small at this time, I’m not sure if we have to wait for l10n. @flodolo how do you think?

Fix Bug 1164424 - Firefox Hello: 'TRY HELLO NOW' button is displayed when using FF38.0esr

---

media/css/sandstone/oldIE.less
media/css/sandstone/sandstone.less

Just some minor housekeeping for our base styles to be consistent with `sandstone-resp.less`

[fix bug 1167169] Consistency for .hidden and .visualy-hidden classes

---

bedrock/firefox/templates/firefox/os/_get_device.html
bedrock/firefox/templates/firefox/os/devices.html
media/js/firefox/os/partner_data.js

* Updates links for Montenegro
* Remove purchase link for Nicaragua

[fix bug 1164371] Broken links on /firefox/os/ 'Get a phone' CTA

---

media/css/base/mozid-modal.less
media/css/base/mozilla-modal.less
media/js/base/mozilla-modal.js

@jpetto r?
A small but worthwhile perf improvement I think. Thoughts? 
I noticed Chrome shows a fair amount of jank opening the modal on /firefox/hello/, and exhibits the same perf on other pages where the new mozid modal styling is going to be used.

[fix bug 1168744] Remove jQuery animations from mozilla modal

---

bedrock/firefox/views.py

This is the final list of spring campaign video URLs that are to be shared for both `/whatsnew` and `/firstrun`. Adding them to master here, so both myself and @jpetto can work from the same list.

Add spring campaign 2015 video URLs

---

bedrock/foundation/templates/foundation/trademarks/faq.html
bedrock/foundation/templates/foundation/trademarks/policy.html
bedrock/legal/templates/legal/fraud-report.html

As per the legal team’s directions. Those pages are not localized.

Fix Bug 1164300 - Remove/Update Affiliates Links on moz.org properties

---

bedrock/security/tests/test_views.py
bedrock/security/views.py

Remove spaces from old file name in case its valid. Return 410
(gone) if no redirect url can be found.

Fix bug 1171181: Respond correctly when no redirect found.

---

media/css/firefox/personal.less

TIL: Chrome still considers `content: '';` as valid content on pseudo elements, needs `content: none;` instead.

[fix bug 1171216] Campaign landing page footer off on Chrome at 760px breakpoint

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

Request has been made to show the older /firstrun tour at /firefox/tour/, at least until we revise what content to show there.

[fix bug 1171652] /firefox/tour/ should still show the older firstrun on-boarding tour

---

media/css/firefox/hello/index.less

Text of "Try Hello Now" secondary (bottom) CTA on /firefox/hello/ is blue (and not very readable) if the link has been visited. This PR keeps the text white.

Fix "Try Hello" link visited color.

---

bin/update/deploy_base.py

This is intended to cause commander to run `deploy_app`
for each host in series instead of parallel like it does now.
It also adds a 5s wait before allowing the next code push to happen.
TODO: Add a check for a 200 response code from the host before proceeding to
the next host.

Deploy to webheads in series.

---

media/css/firefox/personal.less

* Fixes download button link color for unsupported platforms and iOS messaging.
* Also tweaks the dl button link target a little, to fill its parent container.

[fix bug 1171899] Campaign landing page - unsupported platforms link color

---

bedrock/base/middleware.py
bedrock/base/tests/test_middleware.py

Strip characters from url params that cannot be encoded in utf-8

Fix bug 1171183 in LocaleURLMiddleware

---

docs/testing.rst
package.json

Turns out you can pass command-line arguments to scripts as of npm v2.0.0, which allows us to simplify running the functional tests and make things easier to remember.

Simplify functional test commands using npm

---

bedrock/mozorg/templates/mozorg/home/home.html

There was a late copy change that I missed.
@flodolo had you already exposed strings from the previous PR? If so, I'm really sorry.

Bug 1172673 - Update Webmaker promo copy

---

tests/functional/mission.js

Adding functional tests for mission page

---

media/css/firefox/desktop/index.less

Need to use `top` instead of `margin-top` for this page since the intro container is set to `overflow: hidden;` (which makes IE have a sad when it comes to applying negative margin values).

[fix bug 1179790] Header on firefox/desktop page misaligned in IE

---

bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
bedrock/settings/__init__.py
bedrock/settings/base.py

Since "allow-from" [isn't well supported across browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options#Browser_compatibility) I decided to just turn it off on dev (including demos). If anyone knows why this might be a bigger issue, let's discuss it here.

Fix bug 1179847: Support pontoon.m.o in dev mode.

---

media/js/base/global.js
media/js/plugincheck/check-plugins.js
tests/unit/spec/global.js

I’ll implement a new solution using the Tour API as part of Bug 939470, but this is still required.

Fix Bug 1181422 - Plugincheck says ESR 38.1.0 is out of date

---

bedrock/mozorg/templates/mozorg/plugincheck.html
media/css/plugincheck/plugincheck.less
media/js/plugincheck/lib/plugincheck.js

- Adds big red alert telling users Flash is currently vulnerable.
Will need to manually remove this alert when Flash is patched.

Bug 1183218. Add logic to plugincheck to handle empty latest array.

---

bedrock/firefox/templates/firefox/sync.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1180325

Bug 1180325 - Grammar error on the sync feature page

---

bedrock/firefox/templates/firefox/sync.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1180325

Bug 1180325 - Grammar error on the sync feature page - fix

---

bedrock/base/static.py
bedrock/base/tests/test_static.py
bedrock/settings/base.py
wsgi/playdoh.wsgi

Also increase default cache header expiry to 6 hours from 1 minute.
The majority of files used on bedrock are immutable (include the
file content hash) and will be unaffected by this change.

Bug 1182126: Increase fonts cache header to one month.

---

bedrock/firefox/templates/firefox/australis/fx38_0_5/firstrun.html
bedrock/firefox/views.py
media/js/firefox/australis/fx38_0_5/firstrun.js

New CTA logic based on discussion in [bug 1177817](https://bugzilla.mozilla.org/show_bug.cgi?id=1177817#c22):
- Sign up CTA opens `about:accounts?action=signup&entrypoint=uitour`
- Sign in CTA resurrected and now highlights Sync in :hamburger: menu

[fix bug 1177817] Update 38.0.5 firstrun sign in/up CTAs.

---

tests/functional/contribute-signup.js

@alexgibson r? Whilst writing these tests, I discovered and logged 4 bugs, yeah tests!

Adds functional tests for the community signup page

---

bedrock/settings/static_media.py

Noticed this page's menu was broken when looking through Fx URLs the other day. Didn't think it warranted a bug.

Fix /firefox/unsupported-systems/ menu.

---

bedrock/firefox/templates/firefox/australis/fx36/firstrun-tour.html
bedrock/firefox/templates/firefox/australis/fx36/tour-base.html
bedrock/firefox/templates/firefox/australis/fx36/whatsnew-no-tour.html
bedrock/firefox/templates/firefox/australis/fx36/whatsnew-tour.html
bedrock/settings/static_media.py

* `/firefox/36.0/whatsnew/`
* `/firefox/36.0/firstrun/`
* `/firefox/36.0/tour/`

[bug 1171928] Fix static tabzilla on Firefox 36 tour pages

---

tests/unit/spec/base/mozilla-pager.js

- Tests we're not stopping auto-rotate after execution due to spy function not calling through. This wasn't causing failures, but could potentially cause confusion/conflicts in other tests.

Update mozilla-pager.js tests

---

bedrock/firefox/templates/firefox/desktop/customize.html
bedrock/firefox/templates/firefox/desktop/desktop-base.html
bedrock/firefox/templates/firefox/desktop/fast.html
bedrock/firefox/templates/firefox/desktop/index.html
bedrock/firefox/templates/firefox/desktop/trust.html

Noticed while reviewing PR #3125 that `site_header` in `desktop-base.html` isn't needed anymore (due to family nav).
Didn't think a bug was warranted.

Clean up/optimize Fx desktop page templates.

---

media/js/firefox/australis/browser-tour.js
tests/unit/spec/firefox/australis/browser-tour.js

Paying off some technical debt by removing dead code from old tours. Also tidying up the tests a little. Didn't think this warranted a bug (unless someone thinks otherwise!).

Remove dead code from browser-tour.js and update tests

---

.dockerignore
Dockerfile
docker/docker-compose.yml
docker/jenkins/postbuild.sh
docker/jenkins/push2deis.sh
docker/jenkins/push2dockerhub.sh
docker/jenkins/runtests.sh
docker/run-common.sh
docker/run-dev.sh
docker/run-prod.sh
docker/softlinkstatic.py
requirements/docker.txt
requirements/prod.txt

* ~~I'm waiting for #3107 to get merged. Then I will rebase.~~ Rebased of #3107.
* There is a jenkins job that builds against my repository atm https://ci.masterfirefoxos.com/view/www.mozilla.org/job/mozilla_bedrock_docker/ and automatically deploys to
* http://bedrock.masterfirefoxos.com demo
* Everything docker related is under `docker` directory except `Dockerfile`, which we can move when we upgrade to recent docker engine versions 
* Bedrock weights a lot due to static media and locales. Multiple optimizations to bring the image size down to ~550mb. See https://github.com/mozilla/bedrock/pull/3119/files#diff-3254677a7917c6c01f55212f86c57fbfR35

Dockerize bedrock for production

---

bedrock/security/templates/security/known-vulnerabilities.html

https://github.com/mozilla/foundation-security-advisories/pull/5 added Security Advisories for Firefox OS. We need a link to the index page. No bug. Tested locally.

Add a link to Firefox OS Security Advisories

---

bedrock/firefox/urls.py

The Firefox OS TV page, too. We no longer need to waffle these pages. Eliminating some debt.
https://bugzilla.mozilla.org/show_bug.cgi?id=1191923

Bug 1191923 - remove waffle switch for Pocket page

---

bedrock/mozorg/templates/mozorg/home/home.html

Also relates to bug 1192764. This promo used a waffle switch that we shouldn't need to maintain because the whole promo can be removed.

Bug 1152501 - remove Patriot Act campaign promo

---

bedrock/firefox/templates/firefox/desktop/desktop-base.html
bedrock/firefox/templates/firefox/desktop/index.html

As [commented in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1191522#c4), one switch for all `/firefox/desktop/` pages should be sufficient.
Will need to add to [the wiki page](https://wiki.mozilla.org/Mozilla.org/Optimizely) after merge.

[fix bug 1191522] Enable Optimizely on /firefox/desktop/ pages.

---

bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
bedrock/firefox/templates/firefox/hello/start-40.0.html

While we're waiting on the status of #3198, I'd still like to get this into the existing page for Firefox 40.

[fix bug 1198671] Update Hello FTU share URL to point to Hello product page

---

bedrock/foundation/templates/foundation/mocosc.html
bedrock/mozorg/templates/mozorg/about/leadership.html

Also put steering committee members in alphabetical order.
Updated date to August, 2015.
This is a followup on #3248 making a few additional fixes, as spotted by @l-hedgehog

Bug 1198773 - note Mayo as MoCoSC member on leadership page

---

media/css/thunderbird/features.less

@jpetto r? I generally do not like to use id's in CSS but, in this case it is the only way to target the specific page, as it is used by the thunderbird/features page as well.

Fix Bug 1199621, reduce bottom padding of heading on thunderbird email providers page

---

static/.htaccess

Fwiw, we're only using `.woff2` fonts on [one page](https://www.mozilla.org/firefox/windows-10/welcome/) so far, which is only being shown a single time to Firefox users on Windows 10. But we should still add this going forward?

Add woff2 config to .htaccess

---

etc/httpd/global.conf

These redirects are for this set of pages moved to the website-archive server in this commit: https://viewvc.svn.mozilla.org/vc?revision=145674&view=revision

Bug 987852 Add redirects for archived MPL pages

---

bedrock/firefox/urls.py

Bug 1136436 - add waffle switch for iOS product page

---

bedrock/settings/base.py
requirements/base.txt

When SSLify is enabled (disabled by default) will redirect http requests
to https.
@pmclanahan or @jgmize r?

Add sslify for Deis deployments.

---

bedrock/settings/static_media.py

The [merge that happened just before PR #3232 merged](https://github.com/mozilla/bedrock/commit/33a5ff3eaa43b24cc1a502b6cab47fb5ad7cdc79) moved the `simple_footer-resp.less` file, which meant PR #3232 (previously r+'d) was (unknowingly) referencing the file in the wrong spot. What a coincidence!
Anyway, this fixes that.

[fix bug 1190614] Fix footer on /firefox/new/2/.

---

bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/templates/mozorg/home/includes/upcoming-events.html
media/js/mozorg/home/ga-tracking.js

I had this down as a post-GTM clean up bug, but today noticed the GTM JS for home page promo tracking is actually not working correctly. Marking this as do-not-merge for now, as we're going to push this to a demo server for testing.

[fix bug 1188943] Fix GTM tracking on the mozilla.org homepage

---

bedrock/firefox/urls.py
media/css/firefox/ios.less

Also sneaking in a fix for a minor display bug on the sync signed in icon.

Bug 1136436 - remove waffle switch for iOS page

---

etc/httpd/global.conf

This pull request will change the site's redirection settings to fix the bug1200464, which navigate users who attempt to access ja-localzed relesenotes to wrong address.

[bug1200464] Fixed the redirection bugs in ja locale

---

media/css/firefox/ios.less

[fix bug 1136436] Fix CSS typo on /firefox/ios page.

---

etc/httpd/global.conf

Also fix the order of the rules, and add a missing archive redirect for missing.html (get it?).

Bug 1201914 Fix MPL URLs that include .html suffix

---

newrelic.ini
wsgi/playdoh.wsgi

The idea is that we populate `NEW_RELIC_APP_NAME` and `NEW_RELIC_LICENSE_KEY` in the environment and the NR agent grabs the data from there. 
I believe that webops have a different approach with their own `newrelic.ini` file and we continue to respect that here as long as webops don't store their `newrelic.ini` in the root of the repo.
- I tested that on a demo app on deis and works fine
- Added NR environment variables on both clusters for `bedrock-dev` app. `NEW_RELIC_APP_NAME=bedrock-deis-dev`
@pmclanahan r?

Add newrelic.ini for docker.

---

bedrock/base/tests/test_accepted_locales.py
docker/docker-compose.yml
docker/jenkins/runtests.sh

This runs only `./manage.py test`. I see in `travis.yml` that we run `grunt test` and pre-script linters like `flake8`, `runscript check_calendars`.
We probably want to run all these in docker too.  Thoughts @pmclanahan ?

Run tests against the built docker image.

---

bedrock/base/templates/404.html

Re-using existing bug for reference.
The old PHP template has a slightly different text, “here” came after a
comma, so I guess blind copy and paste.
https://www.mozilla.org/en-US/404

Bug 1008100: fix typo in 404 template

---

media/js/firefox/ios.js

We should hold off merging this until we're pretty confident we won't need to do any other pushes (though it's also easy to revert if we have to). This update should not push to prod until we get confirmation that FxiOS is available in the Canada App Store.

Fix bug 1204652 - Firefox for iOS available in Canada

---

media/css/privacy/privacy-day.less

If you look at this page: https://www.mozilla.org/ro/privacy/tips/  the right side quote in green and italic has English-style quotemarks, and they should be Romanian: „”
The en-US page: https://www.mozilla.org/en-US/privacy/tips/
Probably some other locales also need their own specific quote marks in that less rule (German or Russian):
https://www.mozilla.org/ru/privacy/tips/ (should be « » like in French)
https://www.mozilla.org/de/privacy/tips/ (should be „ “ for Germany and Austria)
Honorable mention to [Cristi Silaghi](https://twitter.com/cristi_silaghi_) for bringing this matter to my attention!

Bug 1205265 - Use proper quotes for Romanian in privacy/tips

---

bedrock/firefox/templates/firefox/australis/fx40/firstrun.html
media/js/firefox/australis/fx40/firstrun.js

Need to wait until FxA prod is updated (possibly 9/16?) before merging, but should be reviewed and tested on demo4 now.
https://www-demo4.allizom.org/en-US/firefox/40.0/firstrun/
Instructions for testing FxA staging can be found [here](https://gist.github.com/jpetto/f46f1850737b7a838cad).
Summary of problem/fix:
Currently, users signing in to FxA at `/firefox/40.0/firstrun/` get a less than ideal experience, as the links displayed post-login are contained within the iframe. Our short term fix is to immediately redirect users that sign in to their FxA account settings.
This fix requires a change on the FxA side to force the sign in to complete immediately, as opposed to waiting for an XHR request. Without the FxA change, a redirect will invalidate the sign in.
This PR, tested against FxA …

[fix bug 1199258] Redirect fxa signin users on fx40 firstrun.

---

bedrock/settings/base.py
media/css/firefox/desktop/tips.less
requirements/base.txt

The latest version does error on a broken import in .less files.
I also found and fixed (because it errored) another broken import that
doesn't appear to have been affecting the site.

Fix bug 1206021: Upgrade django-pipeline

---

media/js/base/global.js
media/js/firefox/new.js
tests/unit/spec/base/global.js

Still need to push this to a demo for testing, so marking as do-not-merge for now.

[fix bug 1205282] Enable auto-downloads for IE 9 and above on scene 2 of /firefox/new/

---

media/css/thunderbird/start.less

See my [site compatibility document](https://www.fxsitecompat.com/en-US/docs/2015/direction-independent-css-properies-have-been-unprefixed/) for details.

Fix Bug 1208123 - Correct unprefixed CSS properties on Thunderbird start page

---

bedrock/settings/base.py

This avoids having Django attempt to send mail on errors.

Update ADMINS setting default to empty.

---

docker/jenkins/push2dockerhub.sh
docker/jenkins/push2privateregistries.sh

Script to enable jenkins to push to private registries.
See example run https://ci.us-west.moz.works/job/bedrock_base_image/110/
@jgmize r?
Just before merging enable
https://ci.us-west.moz.works/job/bedrock_registry_upload_us_west/
https://ci.us-west.moz.works/job/bedrock_registry_upload_eu_west/

Push to private docker registries.

---

bedrock/firefox/redirects.py

From IRC:
```
<CamJN> Hey all, https://www.mozilla.org/en-US/firefox/28.0/releasenotes/ is 404ing
```
28.0beta is in the archive, but 28.0 should be served by bedrock.

Fix bug 1210980: Do not redirect Fx 28.0 release notes to archive.

---

bedrock/mozorg/middleware.py
bedrock/mozorg/tests/test_middleware.py
bedrock/settings/base.py

Adds `X-Backend-Server` header in responses.
Added the ENABLE setting so we don't touch the non-Docker installs but I'm happy to remove it if it doesn't make a difference.

Add Hostname Middleware.

---

docker/bin/softlinkstatic.py
docker/dockerfiles/bedrock_code

Uses `collectatic -l` and reduces the image size by [~140mb](https://imagelayers.io/?images=mozorg%2Fbedrock:7d1d934dd94d9946fc6ce20f461e5c207edb3ab8,mozorg%2Fbedrock:2725cbd0b0abacb2cac78123a3432c9b0ae48f75)

Symlink static files.

---

docker/jenkins/run_mcom_tests.sh

Test run: https://ci.us-west.moz.works/job/bedrock_test_dev_us_west/112/console
~~There are still three failing tests~~ Fixed with rnasync cmd
```
FAIL test_firefox_urls.py::TestFirefoxURLs::()::test_urls_ok
FAIL test_notes.py::TestNotes::()::test_that_notes_page_is_reachable
FAIL test_notes.py::TestNotes::()::test_that_all_links_are_valid
```
After talking with @jgmize we agreed to bake a Dockerfile in `mcom-tests` repo and have an automated build in the Docker Hub. This simplifies this script and makes things better for everbody (tm)
See also https://github.com/mozilla/mcom-tests/pull/442
Things to do:
- Fixed by creating bedrock-{stage,prod}-deis.{eu,us}-west.moz.works (cc @pmclanahan @jgmize)
Successful test runs with this configuration:
- …

Update jenkins mcom test runner to use docker.

---

docker/jenkins/periodic_db_update.sh

I've set up an example of this approach at https://ci.us-west.moz.works/view/Bedrock/job/bedrock_periodic_db_update_dev_us_west/ -- to use this, we would set up a periodic job executing this new script for each app and cluster that needed it.

Add periodic db update script for jenkins

---

media/css/privacy/privacy-day.less

This works on both Firefox 41 and 42 (and later).

Fix Bug 1196255 - tabzilla invisible on mobile view of /privacy/tips/

---

bedrock/thunderbird/redirects.py
etc/httpd/global.conf
test_redirects/map_globalconf.py

I forgot to send this earlier… The most of the work mentioned in the bug has actually been done in #3360. This will remove the rest of the legacy Thunderbird redirect rules so the PHP server can be terminated soon.

Fix Bug 1204579 - Consolidate Thunderbird rewrite rules and add some redirects

---

tests/pages/firefox/do_not_track.py

* Waits for accordion to fully expand before clicking again to collapse.

Fix intermittent test failure on firefox dnt page

---

tests/functional/test_l10n.py

This should avoid intermittent failures like this https://webqa-ci.mozilla.com/job/bedrock.dev.win10.ie/14/HTML_Report/
For reference, said redirects are here: https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/redirects.py#L13-L20

Exclude redirected locales from homepage language selector functional tests

---

docs/testing.rst
tests/functional/firefox/test_do_not_track.py
tests/functional/test_contribute.py
tests/functional/test_home.py
tests/functional/test_newsletter.py

Adds `sanity` markers to functional tests, and adds some basic documentation to help explain their purpose.
I have left out certain tests from the sanity suite, including:
* Tests that submit newsletters.
* Tests that rely on long-running timeouts.
* Tests that rely on specific locales being available.
* Tests that rely on cron jobs (e.g. event ical feeds, tweets etc).
Not sure if this is all correct, or if we should tweak things further. But this is good for discussion.

Add sanity markers to Python functional tests

---

media/css/mozorg/home/home-promo.less

Apple's brand guidelines frown upon the uppercase I so we'll override the `text-transform` for just this promo.

Bug 1139654 - use sentence case for iOS home promo button

---

bedrock/base/templates/macros.html
media/css/firefox/family-nav.less

https://bugzilla.mozilla.org/show_bug.cgi?id=1210864

Bug 1210864 - Add Private Browsing to Firefox Family subnav

---

tests/functional/test_l10n.py

https://webqa-ci.mozilla.com/job/bedrock.dev.win10.ie/34/
https://webqa-ci.mozilla.com/job/bedrock.dev.win10.ie/23/
I noticed these two failures both happen when redirected to the `or` locale. My hunch is that IE is matching the URL (www-dev.allizom.**or**g) before the page is redirected, resulting in the last assert failing when the selector becomes stale.

Fix intermittent failure in l10n language selector test

---

docker/dockerfiles/bedrock_functional_tests

Using the python images from registry does not play well with our outdated docker version on the CI server. Debian images are OK for now.
Error https://ci.us-west.moz.works/job/bedrock_functional_tests/65/console
@davehunt  r?

Start from debian:jessie.

---

bedrock/firefox/templates/firefox/android/index.html
bedrock/firefox/templates/firefox/family/index.html
bedrock/firefox/templates/firefox/private-browsing.html

Tested locally Android and Family page, not sure how to check the PB one.

Bug 1221167 - Make alt text on Google Play button localizable

---

bedrock/mozorg/redirects.py
test_redirects/map_globalconf.py

Fix bug 988046: Remove query params from redirect.

---

media/css/firefox/ios.less

We're currently showing the send-to-device widget to locales that don't have the newsletter, so they currently see a blank modal: https://www.mozilla.org/it/firefox/ios/
This PR also shows the App Store badge for iOS users, as it makes more sense to link to it directly.

[fix bug 1224228] Show App Store badge for non-newsletter locales and iOS users

---

tests/functional/contribute/test_contribute.py
tests/functional/contribute/test_events.py
tests/functional/contribute/test_signup.py
tests/functional/contribute/test_stories.py
tests/functional/firefox/test_developer.py
tests/functional/firefox/test_do_not_track.py
tests/functional/test_home.py
tests/functional/test_l10n.py
tests/functional/test_newsletter.py
tests/pages/base.py
tests/pages/firefox/base.py
tests/pages/firefox/developer.py
tests/pages/firefox/do_not_track.py
tests/pages/home.py
tests/pages/newsletter.py
tests/pages/regions/modal.py
tests/pages/regions/newsletter.py

This removes the need for the rather ugly relative imports.

Use absolute imports for page objects

---

bedrock/firefox/redirects.py
bedrock/mozorg/redirects.py
etc/httpd/global.conf
test_redirects/map_globalconf.py

Moved the existing redirect to `firefox/redirects.py` and added tests for both redirects.

[fix bug 1221739] Add a redirect for Hello's Feedback survey links

---

bedrock/firefox/templates/firefox/choose.html

This lets us override strings coming from new.lang (loaded in base-resp.html). Thanks to @pascalchevrel  for the idea.

Bug 1217971 - Add lang file directive to firefox/choose

---

media/css/firefox/private_browsing/private-browsing.less

[bug-1222637] Fixed horizontal scrolling on private-browsing.less 
@jpetto 
rebase went wrong on the other PR, so it's all fixed here, with one commit. :cake:
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1222637 
Old PR: https://github.com/mozilla/bedrock/pull/3554

[bug-1222637] Fixed horizontal scrolling on private-browsing.less

---

media/css/firefox/ios.less

Didn't file a bug, but can if needed. Tested on IE 9 & 10, Fx, Chrome, Safari.

Fix CTA alignment on firefox/ios/ mobile viewports.

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit.html

Fixing my mistake in #3557  :grimacing:

Fix Bug 1226012 - Broken GitHub tutorial link on commit access policy page

---

bedrock/mozorg/templates/mozorg/robots.txt

This change allows the [LinkChecker](http://wummel.github.io/linkchecker/) tool to run against the site and report any broken links. This is much more thorough than the link checking performed in https://github.com/mozilla/mcom-tests/ and can be run as a separate scheduled job that would not necessarily block a deploy due to the unavailability of external sites.
With this change I'm able to run LinkChecker locally (still going strong after 20 minutes). If this is merged and deployed to any environment I'd be happy to set up a Jenkins job to run once a week (alternative suggestions welcome) and send the results to whomever may be interested (again, suggestions?). I'd then like to use this as an opportunity to remove all the link checking from mcom-tests. :link: :smile:
/cc @alexgibson …

Allow LinkChecker to crawl the site for broken links

---

bedrock/mozorg/middleware.py
bedrock/mozorg/tests/test_middleware.py
bedrock/settings/base.py

This will turn on x-backend-server for every instance with a DEIS_APP
env var (which should be all of them running on Deis). It also adds the
value of said var to the header response. Also if DEIS_DOMAIN env var is set
that will be added to the end of that.

Fix bug 1226329: Improve x-backend-server header

---

tests/functional/conftest.py
tests/functional/test_navigation.py
tests/pages/about.py
tests/pages/base.py
tests/pages/contribute/base.py
tests/pages/contribute/contribute.py
tests/pages/contribute/events.py
tests/pages/contribute/signup.py
tests/pages/contribute/stories.py
tests/pages/firefox/products.py

This replaces the following tests from https://github.com/mozilla/mcom-tests:
* [test_about > test_navbar_links_are_visible](https://github.com/mozilla/mcom-tests/blob/c9eacd8f62b11d4a2ab70a230db779932235c801/tests/test_about.py#L36)
* [test_about > test_navbar_link_destinations_are_correct](https://github.com/mozilla/mcom-tests/blob/c9eacd8f62b11d4a2ab70a230db779932235c801/tests/test_about.py#L45)
* [test_about > test_navbar_link_urls_are_valid](https://github.com/mozilla/mcom-tests/blob/c9eacd8f62b11d4a2ab70a230db779932235c801/tests/test_about.py#L56)
* [test_mozillabased > test_navbar_links_are_visible](https://github.com/mozilla/mcom-tests/blob/c9eacd8f62b11d4a2ab70a230db779932235c801/tests/test_mozillabased.py#L92)
The main differences are:
* These tests check the main navigation …

Add main site navigation tests for desktop and mobile views

---

bedrock/teach/templates/teach/smarton/tracking.html

A tiny fix, but worthwhile given this page has a lot of traffic atm.

[fix bug 1228355] Broken link on SmartOn Tracking page

---

bedrock/foundation/templates/foundation/annualreport/2009/a-competitive-world.html
bedrock/foundation/templates/foundation/annualreport/2009/broadening-our-scope.html
bedrock/foundation/templates/foundation/annualreport/2009/index.html
bedrock/foundation/templates/foundation/annualreport/2010/ahead.html
bedrock/foundation/templates/foundation/annualreport/2010/faq.html
bedrock/foundation/templates/foundation/annualreport/2010/index.html
bedrock/foundation/templates/foundation/annualreport/2010/opportunities.html
bedrock/foundation/templates/foundation/annualreport/2010/people.html
bedrock/foundation/templates/foundation/annualreport/2011.html

This fixes most links on these old pages (at least the insecure warnings introduced by the protocol relative URLs). Also explicitly makes links secure than can/should be.

[fix bug 1228341] - Fix protocol relative links on annual report pages

---

bedrock/settings/base.py

Based on https://github.com/mozilla/donate.mozilla.org/blob/master/data/currencies.js and considering the 2nd value as default
The last assumption needs to be confirmed

Bug 1227250 - Update preset amounts for donation form

---

tests/functional/firefox/test_android.py

@davehunt - these two tests are failing in IE due to timing issues, going to skip them until I can make them more robust.

Skip android page tests that are failing in IE

---

tests/functional/firefox/os/test_tv.py
tests/pages/base.py
tests/pages/contribute/contribute.py
tests/pages/firefox/android.py
tests/pages/firefox/base.py
tests/pages/firefox/developer.py
tests/pages/firefox/do_not_track.py
tests/pages/firefox/os/devices.py
tests/pages/firefox/os/tv.py
tests/pages/firefox/os/version/v2_0.py
tests/pages/home.py
tests/pages/page.py
tests/pages/styleguide.py

Addressing a limitation where page regions cannot locate and interact with elements outside of their scope. This allows us to avoid passing the base URL and selenium object for every page region (they're now extracted from the page object) and also solves the problem of referencing page methods/properties from a page region.

Provide PageRegions with a reference to the page they are instantiated from

---

tests/functional/firefox/test_nightly.py
tests/pages/firefox/do_not_track.py
tests/pages/firefox/nightly.py

MIgrating the nightly first run test from https://github.com/mozilla/mcom-tests/blob/master/tests/test_nightlyfirstrun.py
@alexgibson r?

Add test for Firefox nightly first run page

---

media/css/firefox/private_browsing/private-browsing.less

See bottom of the page at
https://www.mozilla.org/et/firefox/private-browsing/

Bug 1230334 - Private Browsing: fix CTA button alignment for longer translations

---

bedrock/firefox/redirects.py

This pull request will add a redirection rule to navigate Japanese users, who access to releasenotes of Firefox for iOS, to Japanese version of the releasenotes they want to read.

fix bug 1224060

---

bedrock/firefox/templates/firefox/feedback/happy.html
bedrock/firefox/templates/firefox/whatsnew-fx37.html
media/css/firefox/whatsnew-fx37.less
media/js/firefox/whatsnew-fx37.js

Bug 1150713
* Update link and content on happy feedback page
* Remove SMS form from FX37 welcome page
Feedback page visible at `/firefox/feedback?score=4`
Welcome page visible at `/firefox/37.0/whatsnew/`
The current welcome page does geolocation to see if SMS is available. This can be triggered manually using `/firefox/37.0/whatsnew/?geo=us`. The updated page still does geolocation to populate the country flydown for the newsletter.

Bug 1150713 Remove straggler SMS page references

---

bedrock/thunderbird/templates/thunderbird/start/release.html

The promo is outdated as Thunderbird is now 11yo.

Fix Bug 1231630 - Remove 10th anniversary promo from Thunderbird start page

---

docker/dockerfiles/bedrock_functional_tests
docker/jenkins/run_functional_tests.sh
docs/testing.rst
tests/functional/contribute/test_contribute.py
tests/functional/contribute/test_signup.py
tests/functional/contribute/test_stories.py
tests/functional/firefox/os/test_devices.py
tests/functional/firefox/os/test_tv.py
tests/functional/firefox/os/version/test_2_0.py
tests/functional/firefox/os/version/test_2_5.py
tests/functional/firefox/os/version/test_all.py
tests/functional/firefox/test_android.py
tests/functional/firefox/test_developer.py
tests/functional/firefox/test_do_not_track.py
tests/functional/firefox/test_new.py
tests/functional/firefox/test_nightly.py
tests/functional/test_home.py
tests/functional/test_mission.py
tests/functional/test_navigation.py
tests/functional/test_newsletter.py
tests/functional/test_styleguide.py

This PR changes sanity tests to use `smoke` markers, and leaves the two new `/firefox/new/` tests marked as both `sanity` and `smoke`.

Rename sanity functional tests to smoke tests

---

bedrock/firefox/templates/firefox/family/index.html
bedrock/firefox/templates/firefox/ios.html
bedrock/firefox/templates/firefox/releases/release-notes.html

* Also added missing query param to a couple of buttons on other pages.

[fix bug 1234136] App Store button on release notes page is 404

---

media/js/firefox/tracking-protection-tour.js
tests/unit/spec/firefox/tracking-protection-tour.js

To test this PR please first:
* [Configure UITour for local development](http://bedrock.readthedocs.org/en/latest/uitour.html#local-development).
* [Set the Tracking Protection tour URL](http://bedrock.readthedocs.org/en/latest/uitour.html#tracking-protection-uitour) to point to your local bedrock instance.

[fix bug 1231785] TP UI Tour does not allow linking to step 2

---

media/css/firefox/releasenotes-firefox.less

Fixing menu links click area + cursor state, and removing trailing spaces in the file.

Bug 1233665 - Menu links on redesigned release notes are hard to click

---

bedrock/mozorg/views.py

They need to not use l10n_utils.

Fix namespace URLs

---

bedrock/styleguide/templates/styleguide/products/firefox-os/icons.html

Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1234166

Bug 1234166 - Fix typo for broken asset link

---

bedrock/firefox/templates/firefox/android/all.html

Replaced old links with bouncer links.

Bug 1226476 - Convert android/all/ to the same format as desktop uses

---

bedrock/mozorg/templates/mozorg/about/governance/policies/module-ownership.html

Hi,
At Mitchell's request (see mozilla.governance) we've just created a new status of "emeritus owner" or "emeritus peer" for ex module owners. This change documents that.
Gerv

Add details of emeritus status for owners and peers

---

tests/functional/firefox/os/version/test_all.py

Adding a test for displaying the news feed, now that #3709 is merged and live.

Update Firefox OS 2.5 page functional test for news feed

---

requirements/base.txt

This brings the version number in setup.py to 1.0 to match what is in requirements so that RNA is no longer downloaded every time peep is run.

Update to latest master of RNA

---

bedrock/base/static.py
bedrock/base/tests/test_static.py

The previous timeout of one month was a bit much and caused a problem with a holiday calendar update.

Change caldata and font cache headers to one week

---

docs/testing.rst
requirements/test.txt
tests/functional/conftest.py
tests/functional/test_download.py
tests/functional/test_download_l10n.py

I'm concerned that if the LinkChecker download jobs failed to find the download links that they could give false confidence that these are not broken. We saw an issue recently where a conditional CSS block caused the LinkChecker to abort early, and the result was success. These tests are an improved version of those in mcom-tests, in that they now check the response code for all platforms and all locales (over 2,300 URLs).
I have not included the 'smoke' marker so these will not be run by the pipeline at this time. I have added a new 'headless' marker, which will allow us to isolate these tests, or to exclude them. It does not make sense, for example, to run these for multiple platforms as we would with the other functional tests.
I suggest replacing the LinkChecker download jobs in the …

Add download link checks

---

tests/functional/test_partnerships.py
tests/pages/partnerships.py

Simply happy path test for requesting a partnership and a negative test when required fields are missing. This replaces the test in [mcom-tests](https://github.com/mozilla/mcom-tests/blob/56382844fe28c27d285c3aecb7614e31bdf4dd39/tests/test_partnerships.py), which only checked visibility of elements. It may be worth later adding interactions with more form fields, or adding tests for any field validation such as e-mail and website.
@alexgibson r?

Add tests for partnerships page

---

bedrock/mozorg/urls.py

`mozorg/button.html` was removed in d8921e105bb6a77ebc2654dbcb2bf876b7244e43 but `mozorg/urls.py` still has the URL which is 404. This PR will simply remove it. No bug.

Remove unused button URL

---

docker/dockerfiles/bedrock_functional_tests
docker/jenkins/properties/functional_tests/full/chrome.properties
docker/jenkins/properties/functional_tests/full/firefox.properties
docker/jenkins/properties/functional_tests/full/ie.properties
docker/jenkins/properties/functional_tests/sanity/ie6.properties
docker/jenkins/properties/functional_tests/sanity/ie7.properties
docker/jenkins/run_functional_tests.sh
docker/jenkins/run_functional_tests_sauce.sh

This removes the default mark expression so that it's possible to run the full suite. It also allows us to run the functional tests against Sauce Labs. @glogiotatidis r?

Add a script for running the functional tests in Sauce Labs

---

docker/jenkins/run_functional_tests.sh
docker/jenkins/run_linkchecker.sh
docker/jenkins/run_tests.sh

This is mainly to make things more convenient when running locally.

Default GIT_COMMIT to HEAD running tests

---

.travis.yml

Puts us onto a rolling FF version for running the JS tests in PR's, while still ensuring some level of legacy coverage.

Use Firefox latest ESR to run JS tests in Travis

---

bedrock/firefox/templates/firefox/developer.html
bedrock/firefox/templates/firefox/installer-help.html
bedrock/firefox/tests/test_base.py

Note: Dev Edition downloads are currently 404 on XP, but hopefully that will be fixed very shortly in [bug 1239685](https://bugzilla.mozilla.org/show_bug.cgi?id=1239685)

[fix bug 1239732] Developer page shows both Desktop and Android downoad buttons on IE6

---

bedrock/thunderbird/details.py

See this [bug for discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=1236045). This PR points to use the new FTP directory for Earlybird, but the l10n builds are still missing.
This should at least fix the download on the `thunderbird/channel` page for en-US.

[bug 1236045] Update Earlybird FTP directory to use latest-comm-aurora

---

tests/functional/firefox/test_developer.py
tests/functional/firefox/test_installer_help.py
tests/pages/base.py
tests/pages/firefox/developer.py
tests/pages/firefox/hello.py
tests/pages/firefox/installer_help.py
tests/pages/firefox/new.py
tests/pages/firefox/sync.py
tests/pages/home.py
tests/pages/thunderbird/channel.py
tests/pages/thunderbird/thunderbird.py

Also makes our download button display tests a bit more robust, by ensuring only one download button is displayed (useful for catching visual regressions like in #3782).

Add functional test for Firefox Installer Help page

---

tests/functional/firefox/test_hello.py

@davehunt - I should have thought of this in the #3793. We can no longer test for a button not being displayed quite as easy. I'd like to address this properly, but this is a quick fix for now.

Fix failing Firefox Hello test

---

docs/uitour.rst
media/js/firefox/australis/australis-uitour.js
media/js/firefox/tracking-protection-tour.js
tests/unit/spec/firefox/tracking-protection-tour.js

setup
-------
* This needs testing using the latest Nightly, at least `46.0a1 (2016-01-17)`.
* Please make sure set Tracking Protection to `Always` in `about:preferences#privacy` (not just in Private Browsing mode).
* Make sure you have [UITour working locally](http://bedrock.readthedocs.org/en/latest/uitour.html#local-development).
URL to test locally: `/firefox/46.01a/tracking-protection/start/?newtab=true`
To test behavior 1:
1.) Open a new tab (make sure you have more than one tab open).
2.) When you get to step 3 of the tour, click "Got it".
Expected result: The tab should close.
To test behavior 2:
1.) Open a single tab (the tour URL being the only tab in the active window).
2.) When you get to step 3 of the tour, click "Got it".
Expected result: Step 4 should be shown
Extra test …

[fix bug 1233773] TP UITour should close tab when not invoked from Private Window

---

tests/pages/firefox/android.py
tests/pages/firefox/base.py
tests/pages/regions/send_to_device.py

@davehunt r?
Looking at the sauce job here it seems IE sometimes triggers a scroll when filling in the form, preventing the submit button from being clicked due to the sticky header. Seen this intermittent a couple of times now.
http://saucelabs.com/jobs/34351f809d864d92acb92918ac205786
This change moves `SendToDevice` into it's own file in `pages.regions`, which I think makes sense as we don't include it in all our Firefox base pages. It also now inherits `FirefoxBasePageRegion` and calls `scroll_element_into_view` before clicking submit, which should hopefully fix the intermittent.

Fix intermittent failure in Android form submission test

---

requirements/test.txt

This should fix the issues in Web QA's Jenkins caused by certain requirements appearing in both `base.txt` and `test.txt`.

Remove duplicated requirements

---

bedrock/legal/redirects.py
bedrock/legal/templates/legal/index.html
bedrock/legal/templates/legal/report-infringement.html
bedrock/legal/urls.py
tests/redirects/map_globalconf.py

The content has been updated in https://github.com/mozilla/legal-docs/pull/469, https://github.com/mozilla/legal-docs/pull/470 and https://github.com/mozilla/legal-docs/pull/471. Have to change the URL as well.
About `legal/redirects.py`: legal-related redirects are currently written in `mozorg/redirects.py`. I'll file a separate PR to move them to `legal/redirects.py`.

Fix Bug 1243240 - Legal would like to have some updates made to https://www.mozilla.org/en-US/about/legal/report-abuse/

---

bedrock/firefox/firefox_details.py
bedrock/firefox/helpers.py
bedrock/firefox/tests/test_helpers.py
media/css/sandstone/buttons.less

Android download button is a total mess, but soon we can improve it… by [dropping the Gingerbread support](https://bugzilla.mozilla.org/show_bug.cgi?id=1245567) and migrating to the new product-details lib.

Fix Bug 1245839 - Aurora mobile download link 404

---

tests/functional/test_plugincheck.py

@schalkneethling r? This test fails in non-firefox browsers as the newsletter is no longer visible on the testing variations if the user does not use Firefox.

[bug 1245208] Temporarily skip plugincheck newsletter test on non-Firefox browsers

---

docker/jenkins/push2dockerhub.sh

This will make it easier to run the latest production docker image locally without having to look up the commit hash.

Tag docker image built w/ tagged commit as latest

---

docker/jenkins/push2dockerhub.sh

Prevent Jenkins from incorrectly reporting a failed job

Return exit code 0 when checking for tag commit

---

bedrock/firefox/templates/firefox/accounts.html
bedrock/firefox/templates/firefox/firstrun/firstrun.html
bedrock/firefox/views.py
docs/firefox-accounts.rst
media/js/firefox/accounts.js
media/js/firefox/firstrun/firstrun.js

Have not yet updated `firefox/accounts.js` as I wanted to first get a sanity check on the approach.
Code is up on demo5:
[https://www-demo5.allizom.org/en-US/firefox/46.0/firstrun/](https://www-demo5.allizom.org/en-US/firefox/46.0/firstrun/)
Change isn't immediately obvious, so I'm logging the FxA iframe `src` to the console. If Fx 46+, `src` string should contain `context=fx_firstrun_v2`. Otherwise, `context=iframe`.
Actual change - after verifying email, Fx 46+ users see a blue "Sync Preferences" button in the iframe. Fx < 46 users do not get this button.
@alexgibson - Pre-review on approach? What do you think about the UITour fallback and timing?

[fix bug 1243890] Update FxA iframe param for Fx46.

---

bedrock/firefox/templates/firefox/hello/index-2016.html

Updating this for en locales only as it's not worth re-translating.

[bug 1240980] Mozilla Support link on Hello page should use title case

---

media/css/firefox/firstrun/firstrun.less

Removing padding improves iframe UI after account confirmation. With padding, grey bottom half of iframe is "floating". Without padding, grey bottom half is butted up against border. (See [the GitHub issue](https://github.com/mozilla/fxa-content-server/issues/3471) for screenshot.)
@alexgibson r?

[fix bug 1245573] Remove padding on firstrun FxA iframe.

---

bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
bedrock/firefox/templates/firefox/includes/simple_footer.html

Added attributes to tabzilla, simple footer, and 'click here' link.

[bug 1248040] Update GTM data attributes on /firefox/new/

---

lib/l10n_utils/__init__.py
lib/l10n_utils/tests/test_template.py

[fix bug 1222137] Enable bedrock locale-based templates.

---

bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/scene2.html

For non en-US visitors, separated templates are currently redirecting to en-US.

[fix bug 1250309] Add lang files to firefox/new separated templates.

---

tests/functional/firefox/test_channel.py
tests/pages/firefox/channel.py

Adds functional tests for the `/firefox/channel/` page.
One thing I'm unsure on is if it's safe to use the normal `wait_for_page_to_load()` here when testing URL's that contain hashes (e.g. `#developer`), or whether it would be safer to use a custom method which can check for the correct HTML class to be added to the content before doing an assert. Tests seem to pass OK without anything extra, but I'm unsure if it's adequate enough.

Add functional tests for /firefox/channel/ page

---

bedrock/firefox/templates/firefox/family/index.html
media/css/firefox/family/index.less

- Removes Firefox OS from the `/firefox/products` page.
- Firefox for iOS has moved into center spot, to make the layout more visually balanced.
- Also cleans up some l10n conditional tags, which means we can also remove Marketplace from the template. I checked with @flodolo and this is ok to do given locales that have active translations.
https://bugzilla.mozilla.org/show_bug.cgi?id=1239863
- Page should now display three products horizontally on wide viewports, and stack vertically on small viewports.
- Page should still look ok in RTL.

[bug 1239863] Remove Firefox OS from products page

---

bedrock/base/templates/macros.html

- Hides Firefox OS on Family Navigation menu
- Only shows Firefox OS in the navigation should the user already be on a Firefox OS page.
Note: this is a temporary hack, until we no longer have the /firefox/os and /firefox/os/ devices pages. I still need to get clarification if this is the correct solution, so marking as do-not-merge for now.
https://bugzilla.mozilla.org/show_bug.cgi?id=1239863
Firefox OS primary link should not be displayed on any pages aside from the Firefox OS pages themselves. This should apply to both desktop and mobile viewports.

[bug 1239863] Hide Firefox OS on Family navigation

---

requirements/test.txt
tests/functional/conftest.py

Reverts mozilla/bedrock#3902
See: https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/1453/

Revert "Update integration test dependencies"

---

docker/jenkins/properties/integration_tests/per_push/firefox.properties
docker/jenkins/properties/integration_tests/per_push/headless.properties
docker/jenkins/properties/integration_tests/per_tag/chrome.properties
docker/jenkins/properties/integration_tests/per_tag/ie.properties
docker/jenkins/properties/integration_tests/per_tag/ie6.properties
docker/jenkins/properties/integration_tests/per_tag/ie7.properties

This will allow us to configure Jenkins to run certain integration test suites for every push, and others only for every tag. The existing properties files have been left behind so that the Jenkins configuration can be updated before these are removed.
N/A
N/A

Separate integration test suites into per push and per tag

---

bedrock/base/templates/macros.html
bedrock/settings/base.py
media/js/base/send-to-device.js
tests/unit/spec/base/send-to-device.js

Note: because the new MSL API requires CORS, the geo lookup will no longer work in IE9 and below. In the case of this widget this should still be fine I think, as the form degrades gracefully to email only (the geo request is only responsible for updating messaging related to SMS).

[fix bug 1242610] Update send to device widget to use Mozilla Location Services

---

docker/jenkins/properties/functional_tests/chrome.properties
docker/jenkins/properties/functional_tests/firefox.properties
docker/jenkins/properties/functional_tests/headless.properties
docker/jenkins/properties/functional_tests/ie.properties
docker/jenkins/properties/functional_tests/ie6.properties
docker/jenkins/properties/functional_tests/ie7.properties

These have been moved to docker/jenkins/properties/functional_tests/ and have been split into per-push and per-tag configurations. Jenkins has now been updated so we can remove the old properties files.
@alexgibson @jgmize r?

Remove functional tests properties files

---

bedrock/firefox/templates/firefox/sync.html
bedrock/firefox/urls.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/firefox/sync.less
media/css/sandstone/lib.less
media/js/firefox/accounts.js
media/js/firefox/sync.js

Add an email field to /firefox/sync/ for Fx users *not* signed in to Sync. This field will propagate to the FxA email field on /firefox/accounts/.
[bug 1249752](https://bugzilla.mozilla.org/show_bug.cgi?id=1249752)
Must have a [profile configured for local or demo testing](http://bedrock.readthedocs.org/en/latest/firefox-accounts.html) and be signed out of Sync. Hit /firefox/sync/, enter an email, click the button, and notice the email field in the FxA iframe is populated.
Variations are currently on demo5 - [v2](https://www-demo5.allizom.org/en-US/firefox/sync/?v=2) and [v3](https://www-demo5.allizom.org/en-US/firefox/sync/?v=3).
Variations are only running for en-US, so no L10n impact.
Waiting on GA confirmation, but code should be ready for review.

[fix bug 1249752] Test FxA email field on /firefox/sync/.

---

bedrock/mozorg/helpers/misc.py
bedrock/mozorg/tests/test_helper_misc.py
media/js/base/mozilla-image-helper.js
tests/unit/spec/base/mozilla-image-helper.js

As `srcset` is now widely supported, we'd prefer to let browsers handle when to load high resolution images rather than using our own custom JS.
[bug 1250225](https://bugzilla.mozilla.org/show_bug.cgi?id=1250225)
If possible, test on both standard and high-resolution screens. Also, check/run Jasmine tests.

[fix bug 1250225] Use srcset for high res images.

---

media/js/base/mozilla-image-helper.js

Seems I was a little too cavalier in removing `isHighDpi` in #3916. Restoring that function, as it's used in a few places:
- [/firefox/channel.js](https://github.com/mozilla/bedrock/blob/master/media/js/firefox/channel.js#L8)
- [/firefox/dev-firstrun.js](https://github.com/mozilla/bedrock/blob/master/media/js/firefox/dev-firstrun.js#L33)
- [/firefox/australis/browser-tour.js](https://github.com/mozilla/bedrock/blob/master/media/js/firefox/australis/browser-tour.js#L157)

[fix bug 1250225] Restore Mozilla.ImageHelper.isHighDpi function.

---

docker/jenkins/build_image.sh

The idea is that we're re-using `DOCKER_IMAGE_TAG` in pre-squashed and squashed images and we end up using an unsquashed bedrock image.  This affects image size.
Took the opportunity to update other parts of the script too. I can git squash if that's preferred.
I tested this manually outside the pipeline and seems to be working.

Docker Updates

---

package.json

Noticed this in some of the [circleci builds errors](https://circleci.com/gh/mozilla/bedrock/21). Seems I forgot to remove it a while back

Remove CasperJS test command from package.json

---

bedrock/settings/static_media.py
docs/uitour.rst
media/js/base/search-params.js
media/js/firefox/australis/australis-uitour.js
media/js/firefox/ios.js
media/js/firefox/sync.js
tests/unit/spec/base/search-params.js

To improve analytics on pages that open `about:accounts` using the `UITour.showFirefoxAccounts` method, we want to pass `utm_` params in to the privileged `about:accounts` tab.
[bug 1250758](https://bugzilla.mozilla.org/show_bug.cgi?id=1250758)
~~**As of 2016-03-03, testing is broken in Nightly. This will be fixed when [bug 1253120](https://bugzilla.mozilla.org/show_bug.cgi?id=1253120) lands. (2016-03-04?)**~~
In Nightly and signed out of Sync, visit [`/firefox/sync/` on demo5](http://www-demo5.allizom.org/firefox/sync/) and click the "Get started with Sync" CTA. This should open `about:accounts` with two default `utm_` parameters added to the URL - `utm_campaign=page referral - not part of a campaign` (URL encoded) and `utm_content=/firefox/sync/`. Visiting …

[fix bug 1250758] Add utm_ params to about:accounts.

---

media/js/base/mozilla-client.js

Increasing the timeout to 300ms as @alexgibson suggested in the bug.

Fix Bug 1253629 - Adjust timeout for getFirefoxDetails()

---

bedrock/firefox/redirects.py
etc/httpd/global.conf
tests/redirects/map_globalconf.py

Redirects `/sync/` to `/firefox/sync/`
https://bugzilla.mozilla.org/show_bug.cgi?id=1252332

[fix bug 1252332] Redirect /sync to /firefox/sync

---

tests/functional/contribute/test_contribute.py
tests/functional/firefox/desktop/test_all.py
tests/functional/firefox/desktop/test_desktop.py
tests/functional/firefox/test_all.py
tests/functional/firefox/test_sync.py
tests/functional/smarton/test_all.py
tests/functional/smarton/test_landing.py
tests/functional/test_about.py
tests/functional/test_home.py
tests/functional/test_mission.py
tests/functional/test_newsletter_embed.py
tests/functional/test_plugincheck.py
tests/pages/firefox/desktop/desktop.py

Makes newsletter functional tests parameterized in order to reduce code duplication and allow for easier testing across multiple pages.
Thoughts @davehunt?

Parameterize newsletter form functional tests

---

.bedrock_demo_env
bin/circleci-demo-deploy.sh
bin/circleci-demo-sync.sh
circle.yml

In order to be deployed a branch must be pushed to mozilla/bedrock and be named "demo__*". If the tests pass the new app will be deployed. The new app will be named after the branch. For example, a branch pushed named "demo__test-whatsnew" will generate an app named "bedrock-demo-test-whatsnew".
I think we should recommend devs mostly use a single branch named for themselves to encourage reuse (e.g. demo__pmac).

Enable deployment of demo instances via git push to origin

---

bedrock/firefox/templates/firefox/includes/top-menu.html

Adda missing link to Firefox iOS page on Firefox top menu navigation.
https://bugzilla.mozilla.org/show_bug.cgi?id=1249726
This older style of navigation is still displayed on pages such as `/firefox/all/`

[fix bug 1249726] Add iOS link to Firefox top menu navigation

---

tests/functional/firefox/test_hello.py
tests/functional/test_newsletter_embed.py
tests/pages/firefox/hello.py

Adds functional tests for redesigned `/firefox/hello/` product page.
Note: this page is not yet live in production, so is currently only visible on dev: https://www-dev.allizom.org/en-US/firefox/hello/
Adding a blocker to merging this which can be removed after the page goes live on March 8.

Add functional tests for redesigned Firefox Hello page

---

tests/functional/firefox/test_hello.py

Going to have to skip this test until Firefox 45 is available in Sauce Labs (I should have thought of this before merging).

Temporarily skip Hello test until FF 45 is available in automation

---

setup.cfg

I noticed we're currently running form submission destructive tests against `bedrock-prod-deis` URLs, which we probably should not be doing.
@davehunt r?

Mark bedrock-prod as sensitive URL for functional tests

---

bedrock/firefox/templates/firefox/new/scene2.html
media/css/firefox/new/scene2.less

Fix a regression introduced since #3806 has landed.

Fix Bug 1254938 - Google Play button on /firefox/new/ scene 2 has wrong width

---

bedrock/settings/base.py

This PR simply updates the external file URLs of the credits and forums data, so that the SVN repo can be shut down soon.

Fix Bug 1188890 and 1188893  - Move credits and forums data out of SVN

---

bedrock/mozorg/redirects.py
tests/redirects/map_htaccess.py

Fixes a lot of 404s to the following URL:
/en-US/add-ons/kodakcd
Original redirect from .htaccess in the .com svn repo.

Bug 1255882: Fix kodak addon redirect

---

bin/circleci-trigger-jenkins.sh
circle.yml

Instead of from Github directly since we have a bit more control.
This allows us to be sure that only pushes to master, and no other
branch, will trigger the full build pipeline.

Trigger Jenkins deployment pipeline from CircleCI

---

bedrock/firefox/firefox_details.py

Fix Bug 1244465 - Firefox /all/ download pages intermittently show localized strings in the title

---

Procfile
bin/cron.py

Currently it imports the whole django setup and commands and runs those functions, but we've run into issues as some of these commands don't expect for the process to persist. This change makes the cron script simply call the same commands in a subshell.

Convert cron script to just call management commands

---

bedrock/mozorg/forms.py
bedrock/newsletter/templates/newsletter/includes/form.html
bedrock/newsletter/views.py

Changes "privacy policy" to "privacy notice" and updates the link.
@flodolo and @pmclanahan - This changes some strings but I'm unsure how to use an l10n tag in a .py file, or if that's even possible. I was unable to find any examples; I suspect that helper is just for templates.

Bug 1244200 - update privacy link in newsletter forms

---

bedrock/firefox/templates/firefox/family/index.html

Updates the line of Hello copy on the /firefox/products page to better describe what the product now delivers.
https://bugzilla.mozilla.org/show_bug.cgi?id=1260370

[fix bug 1260370] Update Hello copy on /firefox/products/ page

---

media/js/base/nav-main-resp.js
media/js/base/nav-main.js

Mainly just indentation changes.
N/A
- Responsive nav can be tested on many pages (e.g. home page).
- Old nav can still be seen on pages such as `/firefox/all/`

Lint navigation menu JS files

---

bedrock/base/templates/includes/site-footer.html
bedrock/base/templates/macros.html
bedrock/firefox/templates/firefox/choose.html
bedrock/firefox/templates/firefox/family/index.html
bedrock/mozorg/templates/mozorg/home/home.html
media/js/firefox/family-nav.js

Bug 1248040 - https://bugzilla.mozilla.org/show_bug.cgi?id=1248040

[bug 1248040] Update GTM data attributes missed on first pass through

---

media/js/foundation/annual2011.js
media/js/foundation/annual2012.js
media/js/foundation/annual2013.js

Lint JS files for annual report pages. This is mainly indentation and single quote changes.
- /foundation/annualreport/2011/
- /foundation/annualreport/2012/
- /foundation/annualreport/2013/
Note: There is some cleanup we could do with regard to DOM querying & caching selectors on the older 2011 page, but that's not the aim right now.
N/A
Should be a fairly safe change, mostly style related as opposed to changing any logic. Just a quick test to make sure there are no obvious regressions should be enough.

Lint Mozilla Annual Report JS files

---

requirements/base.txt

v0.3.12 brings special testing email addresses:
* `success@example.com` will not hit basket and will return success.
* `failure@example.com` will not hit basket and will raise an exception.
These should be used to test live email forms for UX regresions.

Fix bug 1261886: Upgrade basket-client

---

tests/functional/contribute/test_friends.py
tests/pages/contribute/friends.py

Adding functional tests to recently updated `/contribute/friends/` page. **Heavily** influenced by [existing newsletter tests](https://github.com/mozilla/bedrock/blob/master/tests/functional/test_newsletter.py).
[bug 1261078](https://bugzilla.mozilla.org/show_bug.cgi?id=1261078)
Just run the tests:
`py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/contribute/test_friends.py`

[fix bug 1261078] Add tests to new /contribute/friends/ page

---

bedrock/settings/static_media.py
media/js/base/uitour-lib.js
media/js/firefox/accounts.js
media/js/firefox/android.js
media/js/firefox/australis/browser-tour.js
media/js/firefox/australis/common.js
media/js/firefox/australis/fx36/tour.js
media/js/firefox/australis/fx38_0_5/firstrun.js
media/js/firefox/australis/no-tour.js
media/js/firefox/dev-firstrun.js
media/js/firefox/dev-whatsnew.js
media/js/firefox/firstrun/firstrun.js
media/js/firefox/firstrun/learnmore/learnmore.js
media/js/firefox/hello/hello-ftu.js
media/js/firefox/hello/start-45.js
media/js/firefox/hello/start-ftu.js
media/js/firefox/tracking-protection-tour.js
media/js/firefox/whatsnew_38/pocket-uitour.js
media/js/firefox/whatsnew_38/whatsnew-pocket.js
media/js/firefox/whatsnew_38/whatsnew-video.js
media/js/firefox/whatsnew_42/variant-a.js
media/js/firefox/win10-welcome-init.js
media/js/firefox/win10-welcome.js

- Lint JS files related to /whatsnew, /firstrun, and UITour related files.
- Renames `australis-uitour.js` to `uitour-lib.js` and moves to `/js/base/`, as much of the site now uses this file.
N/A
Mostly small changes, but some manual testing of pages would be appreciated for good measure.

Lint Firefox /whatsnew, /firstrun and /tour related JS files

---

bedrock/base/templates/includes/site-footer.html
bedrock/mozorg/templates/mozorg/contribute/studentambassadors/landing.html

This also removes a Firefox Friends link on the Firefox Student Ambassadors page, as requested in Bug 1249419.

Fix Bug 1262603 - remove "friends" and "partner" links from footer site wide

---

tests/functional/firefox/os/test_fxos_navigation.py

FxOS nav functional tests are [failing due to a missing import](https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/4776/console).
`py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/firefox/os/test_fxos_navigation.py`

Fix incorrect import for FxOS nav tests.

---

media/css/firefox/sync.less

Currently the Arabic Sync page looks like this:
but it should look like this:

fix the rtl css on the sync page

---

media/css/firefox/private_browsing/private-browsing.less

the plus sign in the RTL pages is not in the right place:
and should appear like this:

fix the position of the plus sign in the private browsing page

---

bedrock/settings/base.py
tests/redirects/map_locales.py

The tests passed, and manual test also works well.

Fix Bug 1263193 - www.mozilla.org redirected to zh-CN page in zh-TW Edge and IE 11 on Win 10

---

bedrock/mozorg/templates/mozorg/contact/communities/japan.html

Forgot to add Flickr :camera: as part of #4032.

Follow up Bug 1261866 - Update links and redirects to mozilla.jp

---

bedrock/foundation/templates/foundation/licensing/website-content.html

This also fixes a typo found in Bug 1202557. No l10n affected.

Bug 669608 - Change link to Creative Commons Attribution Share-Alike v3.0

---

tests/functional/test_download.py

[fix bug 1266682] Remove Play Store links from headless download tests

---

Procfile

The dev deployments are currently running the `web` process type. After merging we can scale the web workers down and supervisor workers up. The demo environments are already running supervisor via the Dockerfile `CMD`.
@pmclanahan r?

Add supervisor to Procfile for bug 1266665

---

bedrock/firefox/templates/firefox/onboarding/user-actions-pinsearch.html

Simple copy change proposed by @alexgibson in #4076 and approved by Matej in [the copy bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1259543#c3).
[bug 1261482](https://bugzilla.mozilla.org/show_bug.cgi?id=1259543#c3)

[fix bug 1261482] Update pin it copy for OS X.

---

bedrock/firefox/templates/firefox/os/_get_device.html
bedrock/firefox/templates/firefox/os/devices.html
media/js/firefox/os/partner_data.js

**summary**
Removed links and data for unavailable phones.

fix Bug 1250543 - Broken partner links on /firefox/os/devices/ page

---

bedrock/firefox/firefox_details.py
bedrock/firefox/helpers.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py

This is due this Friday, April 29.

Fix Bug 1245567 - Remove Firefox for Android 2.3 Gingerbread from www.mozilla.org

---

.github/PULL_REQUEST_TEMPLATE.md

As mulled over on IRC yesterday:
- Removes guidelines section (people don't read/use it).
- Leaves just the headings for our own use.
- Leaves the checklist for tests/l10n changes.

Simplify GitHub pull request template

---

bedrock/newsletter/templates/newsletter/existing.html

Hides the form and adds a short maintenance message behind the waffle switch `newsletter-maintenance-mode`
@flodolo These are new strings so it may be better to put them in an l10n tag, but we don't have any useful fallback content to show if they aren't localized so maybe showing English is better than nothing? But I believe the plan is to get good locale coverage before we merge this. Let me know if a tag is preferable.
https://bugzilla.mozilla.org/show_bug.cgi?id=1266481

[fix bug 1266481]  Add a maintenance message when email pref center is unavailable

---

bedrock/firefox/templates/firefox/new/redesign/base.html

Just get the ol' Optimizely up on them thar fancy, city-slicker /new pages. I reckon it should be a quick review.
[bug 1271702](https://bugzilla.mozilla.org/show_bug.cgi?id=1271702)

[fix bug 1271702] Add Optimizely snippet to new /new pages.

---

bedrock/mozorg/middleware.py
bedrock/mozorg/tests/test_middleware.py
bedrock/settings/base.py
requirements/base.txt

Also enable CORS support for newsletter view. This should help static sites like for Viewsource to fully support newsletter signups with decent fallback for non-ajax posts.

Update CORS handling to work with preflight

---

bedrock/mozorg/templates/mozorg/contribute/tasks/stumbler.html
media/js/mozorg/contribute/taskview.js

Improve stability of delegated click handling on various contribute tasks.
[bug 1272030](https://bugzilla.mozilla.org/show_bug.cgi?id=1272030)
Make sure task completion functions as expected in A-grade browsers and IE 10+. Make sure non-completion events (e.g. clicking "Learn more about encryption" link) work normally and do not initiate a task completion event.
IE 9 and below do not support `visibilityChange`, and thus do not visually indicate task completion. I could find no support for `document.msHidden` when testing IE 8 and 9, so I removed that conditional from the code.

[fix bug 1272030] Update /contribute/signup task event handling.

---

docker/jenkins/cleanup_after_functional_tests.sh

@davehunt when the $DRIVER=Remote it seems that we run the tests [locally on the CI node](https://github.com/mozilla/bedrock/blob/master/docker/jenkins/run_integration_tests.sh#L20-49). Is `Remote` the correct characterization or do we mean `Locally`?

Remove running selenium containers after local tests only.

---

bedrock/base/middleware.py
bedrock/settings/base.py

Setting BASIC_AUTH_CREDS environment variable will now protect the entire site with that username and password. Value of the variable must be colon separated username and password (e.g. "theuser:thepass").

Bug 1266185: Add the ability to enable basic auth

---

bedrock/mozorg/templates/mozorg/contribute/index.html
bedrock/mozorg/templates/mozorg/contribute/tasks/devtools-challenger.html
bedrock/mozorg/templates/mozorg/contribute/tasks/encryption.html
bedrock/mozorg/templates/mozorg/contribute/tasks/firefox-mobile.html
bedrock/mozorg/templates/mozorg/contribute/tasks/joy-of-coding.html
bedrock/mozorg/templates/mozorg/contribute/tasks/stumbler.html
bedrock/mozorg/views.py
media/css/mozorg/contribute/taskview.less

1.) Hides the "Want to get involved? Here’s how." steps on /contribute until we have email signups again. Shows a simple "Get Involved" CTA reusing existing strings.
2.) Adds a link underneath the Joy of Coding video that says "View more Joy of Coding videos on Air Mozilla" (since the video suggests there are links below on the page)
3.) Changes the Joy of Coding thank you message from "Thanks for getting involved" to "Thanks for watching".
4.) Changes the Dev Tools Challenger CTA button from "Learn More" to "Visit Dev Tools Challenger".
5.) Fixes the broken App Store button link on the firefox mobile task page.
6.) Changes the encryption task title from "Take the pledge" to "Become an encryption champion". See [Bug 1272023](https://bugzilla.mozilla.org/show_bug.cgi?id=1272023) for …

[fix bug 1271424] Improve copy and UX on some /contribute/signup tasks

---

bedrock/firefox/templates/firefox/new/redesign/scene2.html
media/css/firefox/new/redesign/scene2.less
media/css/firefox/new/scene2.less
media/js/firefox/new/scene2.js

- Adds a fallback `href` for the direct download link on scene2 that points to `/firefox/all/`, should the JS fail to update the direct download link.
- Only trigger the auto-download click if a supported visible platform link is detected.
- If a user lands directly on scene 2 with JS disabled, show all the download buttons and hide the (JS dependent) direct download link.
https://bugzilla.mozilla.org/show_bug.cgi?id=1257796
- Test both the old and new scene2 templates with JS disabled.
- Test landing directly on scene2 with an unknown user agent (set `site.platform` to `other`). The page should no longer go into an infinite redirect loop by clicking the empty direct download link.
**Note:** I've only updated the `href` fallback link on the new template design, since this is en-US only …

[fix bug 1257796] Make scene2 of /firefox/new more resilient to unknown platforms

---

bedrock/mozorg/forms.py
bedrock/mozorg/tests/test_views.py

Student Ambassadors form throws 500 when using the test email "success@example.com" because the mock response does not include token.

Fix bug 1274235: Fix key error when basket returns no token

---

bedrock/mozorg/templates/mozorg/contribute/tasks/devtools-challenger.html
bedrock/mozorg/templates/mozorg/contribute/tasks/taskview-base.html
bedrock/settings/static_media.py
media/css/mozorg/contribute/taskview.less
media/css/newsletter/moznewsletter-subscribe.less
media/js/mozorg/contribute/taskview.js

- Switches /contribute task pages to use `moznewsletter-subscribe.less`.
- Adds a reusable "light" theme style based on existing work.
- Updates the button CSS styling on task pages as per [bug 1270200](https://bugzilla.mozilla.org/show_bug.cgi?id=1270200).
https://bugzilla.mozilla.org/show_bug.cgi?id=1273071
https://bugzilla.mozilla.org/show_bug.cgi?id=1270200
Nothing too specific, just test general responsiveness. Also make sure no visual regressions introduced in other Mozilla newsletter pages.

[fix bug 1273071] Newsletter signup forms on /contribute task pages have non-responsive styling

---

bedrock/base/storage.py

Our CDN does it for us so the .gz files were unused.
https://support.cloudflare.com/hc/en-us/articles/200168086-Does-CloudFlare-gzip-resources

No longer gzip compress static assets in app

---

bedrock/firefox/urls.py

Same applies to /ab-CD/firefox/channel/android/, so fixed it as well.
https://bugzilla.mozilla.org/show_bug.cgi?id=1241969

[Bug 1241969] don't ignore the requested language when opening /ab-CD/firefox/

---

bedrock/firefox/urls.py

Reverts mozilla/bedrock#4133
After merging and deploying this to dev, we found that (for example) https://bedrock-dev.us-west.moz.works/it/firefox/ would still redirect to https://bedrock-dev.us-west.moz.works/en-US/firefox/new/

Revert "[Bug 1241969] don't ignore the requested language when opening /ab-CD/firefox/"

---

bedrock/firefox/templates/firefox/firstrun/firstrun.html
media/css/firefox/firstrun/firstrun.less

Update subhead copy on `/firstrun` page.
[bug 1275006](https://bugzilla.mozilla.org/show_bug.cgi?id=1275006)

[fix bug 1275006] Update subhead copy on /firstrun.

---

bedrock/base/templates/macros.html
bedrock/firefox/templates/firefox/android/index.html
bedrock/firefox/templates/firefox/ios.html
bedrock/settings/static_media.py
docs/send-to-device.rst
media/css/base/send-to-device-micro.less
media/css/firefox/android.less
media/css/firefox/ios.less
media/js/base/send-to-device.js
media/js/firefox/ios.js
tests/functional/firefox/test_ios.py
tests/pages/firefox/ios.py

- Embeds the send-to-device form on `/firefox/ios` instead of requiring a modal.
- Both `/firefox/ios` and `/firefox/android` now use a shared `send-to-device-micro.less` stylesheet.
- Embedded form styles are now standalone, instead of overriding `send-to-device.less`.
- Clicking the "Get Firefox for iOS" button in the nav now scrolls the form into view.
- Updates functional tests for iOS page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1270789
- Test both `/firefox/ios` and `/firefox/android` for regressions (either form styling or display logic).

[fix bug 1270789] Use embedded version of send-to-device form on /firefox/ios/page

---

media/js/base/core-datalayer-init.js

Since I merged this we've had 2 consecutive test failures in the pipeline:
https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/6085/
https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/6084/
I don't yet quite understand the failure, but I'm going to remove the call to it for now until I dig in deeper.

Disable call to Mozilla.Analytics.updateDataLayerPush due to test failure

---

tests/pages/base.py

The recent switch to PyPOM inadvertently dropped the wait for the seed URL to be loaded. This patch restores it. @alexgibson r?

Restore waiting for the seed URL to be loaded in functional tests

---

tests/functional/firefox/new/test_thank_you.py

@davehunt r?
https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/6087/
I think this test is failing due to some kind of slight change in timing. It passes for me locally, and the page still works as expected when manual testing. But for some reason it is now failing in the pipeline. I need some time to try and figure it out and debug the issue, but for now I think we might need to skip this test :/

Skip thank you page test due to flakyness in the pipeline

---

media/js/base/core-datalayer-init.js
tests/functional/firefox/new/test_thank_you.py

@davehunt r?
The last pipeline run was [green](https://ci.us-west.moz.works/view/Bedrock%20Pipeline/), so I think [Bug 1275978](https://bugzilla.mozilla.org/show_bug.cgi?id=1275978) may have been resolved. Going to try re-enabling this test and `updateDataLayerPush()` since I believe the failure was likely related to this bug (which explains the randomness of the sudden failure).

Re-enable skipped test and Analytics.updateDataLayerPush

---

bedrock/firefox/templates/firefox/new/redesign/scene1.html

- Updates download page copy on scene 1 for en-US version of the page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1275770

[fix bug 1275770] Update headline + value proposition copy on download page

---

bedrock/settings/static_media.py

FxA iframe is invisible on https://www.mozilla.org/en-US/firefox/46.0.1/firstrun/?v=1 due to the bundle missing the newly created `mozilla-fxa-iframe.less` file.
N/A
Make sure above URL displays FxA iframe.

Fix ?v=1 firstrun onboarding test FxA iframe visibility

---

bedrock/mozorg/forms.py
bedrock/mozorg/templates/mozorg/emails/partnerships.txt
bedrock/mozorg/tests/test_views.py
bedrock/mozorg/views.py

- Update partner submission page to use an email instead of salesforce
https://bugzilla.mozilla.org/show_bug.cgi?id=1253001
https://bedrock-demo-agibson.us-west.moz.works/en-US/about/partnerships/

[fix bug 1253001] Update partner submission page to use an email instead of salesforce

---

bedrock/mozorg/templates/mozorg/contribute/tasks/stumbler.html

Point Play Store button to the Stumbler app instead of the Fx for Android app.
https://bugzilla.mozilla.org/show_bug.cgi?id=1277964
Make sure the link works?

[fix bug 1277964] Fix Stumbler app store link.

---

media/css/base/page-not-found.less

https://bugzilla.mozilla.org/show_bug.cgi?id=1275509

[fix bug 1275509] Privacy link text on 404 page lacks sufficient contrast

---

bedrock/firefox/templates/firefox/family/index.html
media/css/firefox/family/index.less

Adds our standard language switcher to the footer of /products
https://bugzilla.mozilla.org/show_bug.cgi?id=1275431

[fix bug 1275431] Add language switcher to product page footer

---

media/js/base/core-datalayer.js
tests/unit/spec/base/core-datalayer.js

- Fixes a bug where internal links we're being reported incorrectly in IE9. I had trouble reproducing this locally, but James seems confident this should fix the issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1278426
Visit `/firefox/new` and click the download button. The `href` that gets passed in `Analytics.updateDataLayerPush()` should be `/firefox/new/?scene=2` (omitting the host and locale). The same applies to any internal link.

[fix bug 1278426] IE Download events broken in IE9 and below

---

bedrock/firefox/helpers.py
bedrock/firefox/templates/firefox/includes/download-button.html
media/css/sandstone/buttons.less
media/js/base/site.js

This is required before Firefox 49 hits the Aurora channel next week on Thursday or Friday. I know the download button code is a total mess but we have to handle it anyway…
How to test this manually:
1. Make sure product-details is up-to-date
2. Change the condition in `helpers.py` from `>= 49` to `>= 48`
3. Spoof the browser’s UA string so that it looks like Snow Leopard, Lion or Mountain Lion, e.g. `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:49.0) Gecko/20100101 Firefox/49.0`
4. Load /firefox/channel/
5. Check if the desktop DevEdition button is disabled while other buttons are enabled

Bug 1255518 - Firefox download buttons: drop support for OS X 10.6-10.8 in August 2016

---

bedrock/firefox/helpers.py
bedrock/firefox/templates/firefox/includes/download-button.html
media/css/sandstone/buttons.less
media/js/base/site.js

Reverts mozilla/bedrock#4174
Functional test failures after this merge. Need to update tests and re-submit.

Revert "Bug 1255518 - Firefox download buttons: drop support for OS X 10.6-10.8 in August 2016"

---

bedrock/firefox/helpers.py
bedrock/firefox/templates/firefox/includes/download-button.html
media/css/sandstone/buttons.less
media/js/base/site.js

#4174 was reverted in #4179. This fixes the CSS rule as discussed on IRC.

Fix Bug 1255518 - Firefox download buttons: drop support for OS X 10.6-10.8, take 2

---

bedrock/mozorg/templates/mozorg/contribute/tasks/firefox-mobile.html
tests/functional/contribute/test_tasks.py
tests/functional/test_newsletter_embed.py
tests/pages/contribute/task/dev_tools_challenger.py
tests/pages/contribute/task/encryption.py
tests/pages/contribute/task/joy_of_coding.py
tests/pages/contribute/task/mobile.py
tests/pages/contribute/task/stumbler.py
tests/pages/contribute/task/twitter.py
tests/pages/contribute/tasks.py

- Adds functional tests for the new `/contribute` task pages.
- Adds task pages to parameterized newsletter tests.
Note: I decided against clicking the actual task CTA buttons that open new tabs, since it would introduce a dependency on loading third-party sites in our tests. I think asserting that our own pages look/function as expected is probably enough here. 
It would have been nice to test the "thank you" message after switching tabs, but I think this would likely prove to be more trouble in the long run that it is beneficial. The "thank you" message is only a piece of text, and not something I would class as critical to the page (i.e. even if it broke, people could still complete the tasks as normal).
- N/A
- I had to add a new selector for one of the firefox-mobile task page as a …

Add functional tests for /contribute tasks

---

bedrock/mozorg/templates/mozorg/home/home-a.html
media/js/mozorg/home/home-a.js

Update `data-link-name` attribute on Firefox in-page nav item to distinguish from Firefox primary nav item.
https://bugzilla.mozilla.org/show_bug.cgi?id=1279222
Can add the following after line 156 in `home-a.js` to verify correct value is being logged to GA on scroll:
```
console.log({
'event': 'scroll-section',
'section': gtmSection
});
```
On click, `data-link-name` and `data-link-type` are automatically transmitted to GTM.

[fix bug 1279222] Update GTM on homepage prototpye A.

---

bedrock/settings/base.py

- Removes 'hu' from the list of send to device locales.
https://bugzilla.mozilla.org/show_bug.cgi?id=1281045
- Verify that both `/hu/firefox/ios/` and `/hu/firefox/android/` should display app store badges instead of the send to device form.

[fix bug 1281045] Remove 'hu' from send to device locales

---

media/css/mozorg/about-patents.less

The red title box wasn't playing well with adjacent content. Looks like a minor regression, just needed some CSS fixes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1281951

[fix bug 1281951] patent page title formatting

---

bedrock/mozorg/forms.py

The field name in the clean method was misspelled.

Fix bug 1280217: FSA Major free text should pass to basket

---

media/js/base/core-datalayer-init.js
media/js/base/core-datalayer.js
media/js/base/mozilla-client.js
media/js/base/mozilla-fxa-iframe.js
tests/unit/spec/base/core-datalayer.js

Additions to the Core DataLayer Object, including making sure that the Firefox and plugin details have been pushed to the dataLayer before the Core DataLayer Object is pushed to ensure that data is available when a pageview is triggered.
https://bugzilla.mozilla.org/show_bug.cgi?id=1270316

[bug 1270316] Core DataLayer Additions

---

media/css/sandstone/sandstone-resp.less
media/css/sandstone/sandstone.less

Without a specific `font-family` set on `<input>` and `<button>` elements, the font falls back to that dictated by the UA stylesheet. It appears simply adding `font-family: inherit;` to the `.base-button` class fixes the issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1282903
Check instances of `class="button"`. Specific examples are:
- `/about/`
- `/firefox/ios/`
- `/firefox/ios/testflight/`
- `/firefox/new/?v=1` (with Fx)
- `/firefox/new/` (with up-to-date Fx)

[fix bug 1282903] Swap system font for Open Sans on buttons.

---

docs/analytics.rst
docs/index.rst

Added an Analytics page with a quick overview of Google Tag Manager and the dataLayer, and included instructions on adding data attributes when adding new elements to mozilla.org. Peter German has reviewed and signed off on content.

Add analytics page to Read The Docs

---

bedrock/privacy/templates/privacy/notices/firefox.html

Modified a selector in the template to accommodate a new paragraph outside of the expanding "Things you should know" section, as [requested in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1282173#c1).

Fix Bug 1282173 - Changes to 2 Legal docs

---

bedrock/mozorg/forms.py
bedrock/mozorg/tests/test_views.py

Basket now supports adding all of the data necessary for the FSA form in a single subscribe call. Let's do that as the old way is error prone.

Do student ambassadors basket update with one call

---

bedrock/mozorg/views.py

Partnership form should not send the email if the submitted address is at example.com. This is a reserved testing domain and will never have valid email accounts. This is specifically so that the selenium tests for this page will not send mail to the list for these tests.

Send no email for @example.com addresses

---

docker/jenkins/properties/integration_tests/per_tag/ie6.properties
docker/jenkins/properties/integration_tests/per_tag/ie7.properties

This should avoid generating headless tests before collection when they're not needed. e.g:
https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/6822/

Don't generate headless tests when running IE SauceLabs jobs

---

bedrock/mozorg/templates/mozorg/home/home-a.html
bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/templates/mozorg/home/includes/survey-a.html
bedrock/settings/static_media.py
media/css/mozorg/home/survey.less
media/js/mozorg/home/survey-a.js
media/js/mozorg/home/survey-generator.js

Add survey to current homepage for en-US, non-Firefox users.
https://bugzilla.mozilla.org/show_bug.cgi?id=1283043
Make sure survey displays on homepage for en-US, non-Fx users. Also ensure no regressions on homepage prototype A (`/?v=a`) survey.

[fix bug 1283043] Add survey to en-US home page.

---

bedrock/mozorg/templates/mozorg/home/home-b.html
bedrock/mozorg/templates/mozorg/home/includes/survey-b.html
bedrock/settings/static_media.py
media/css/mozorg/home/survey.less
media/js/mozorg/home/home-b.js
media/js/mozorg/home/survey-b.js

Adds a survey to homepage prototype B. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1275629#c15
Survey should appear after scrolling to the Firefox section. Survey should not be shown below 760px wide. Make sure no regressions on prototype A survey.

[fix bug 1275629] Add survey to home prototype B.

---

bedrock/base/context_processors.py
bedrock/base/middleware.py
bedrock/mozorg/tests/__init__.py
lib/l10n_utils/dotlang.py
lib/l10n_utils/helpers.py
lib/l10n_utils/translation.py

Using Django's i18n infra for activation of translation means that it looks for .mo files to decide whether to activate it. This means that only those languages that ship with Django will activate. Since we have our own i18n system anyway we can copy their mechnics with a much more simple system.

Fix languages not recognized by Django

---

bedrock/mozorg/templates/mozorg/contact/spaces/london.html
media/js/mozorg/contact-data.js

Actual building of new office is two buildings south, updated the marker position
https://bugzilla.mozilla.org/show_bug.cgi?id=1282532
Tested the image by calling the image url with the new parameters.

Bug 1288360 - Set marker on correct building for Mozilla's London office. r?alexgibson

---

media/css/firefox/new/horizon/scene1.less

- Some minor tweaks to speed up the sunrise animation. ~~Marking as do-not-merge for now until we've had feedback from Ty~~.
https://bugzilla.mozilla.org/show_bug.cgi?id=1287390
- `/en-US/firefox/new/?v=1`

[fix bug 1287390] Updates to sunrise animation on firefox download page

---

bedrock/base/tests/test_accepted_locales.py
bedrock/base/tests/test_context_processors.py
bedrock/mozorg/tests/__init__.py
bedrock/settings/base.py
bedrock/settings/jenkins.py
bin/jenkins.sh
circle.yml
docker/jenkins/run_tests.sh
docs/install.rst
requirements/base.txt
requirements/dev.txt

Remove most of nose libs. Nose itself is still required for nose.tools functions.

Switch from django-nose to py.test

---

bedrock/firefox/templates/firefox/all.html

LGPL requires us to provide access to source code where we provide access to binaries, and Firefox contains some LGPLed code. It doesn't have to be high profile; here's one suggested way.
https://bugzilla.mozilla.org/show_bug.cgi?id=1167570
Loaded on my machine :-)

Bug 1167570 - Add "Source Code" download link to https://www.mozilla.org/firefox/all/

---

bedrock/settings/base.py

Hope this would be the last time to hardcode the version on Bedrock ;-)

Fix Bug 1289796 - default ios version should be 5.0 instead of 4.0 in release notes

---

docs/uitour.rst

Just tidying up after myself (I forgot to remove this when we decommissioned the Hello FTU some time ago).

Remove Hello FTU instructions from UITour docs

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

- Adds appropriate redirect for `/hacking/` so a 404 is not returned.
https://bugzilla.mozilla.org/show_bug.cgi?id=1288647
I was not sure how to address the "Testing" and "Checklist" portions of this template. I did follow the [Managing Redirects](http://bedrock.readthedocs.io/en/latest/redirects.html#add-a-redirect) documentation and ran the following tests: `py.test -r a -m smoke tests/redirects/`. This returned the following results: "2033 passed, 37 deselected in 27.98 seconds" which looked good to me!
If there's anything more I can do, let me know.

Fix Bug 1288647: Bad Mozilla Hacking Links

---

media/css/mozorg/manifesto.less

Minor regression from deleting mosaic.less in bfe0591cb5cd46d53ba335227e8116149040e124 which was easy to miss in review thanks to cached files; the breakage doesn't appear until you reprocess the manifesto CSS bundle without the mosaic styles.
https://bugzilla.mozilla.org/show_bug.cgi?id=1291909
For local testing, delete your local files from /static/css and rerun collectstatic to ensure you're seeing the changes and not a old file.

[fix bug 1291909] broken mosaic on manifesto page

---

bedrock/firefox/templates/firefox/family/index.html
bedrock/firefox/templates/firefox/features.html
bedrock/firefox/templates/firefox/hello/index.html
media/css/firefox/family/index.less
media/css/firefox/features.less

Removes the Hello blurbs and links from /firefox/products and /firefox/features and also removes the waffle switch from /firefox/hello.
This needs to go to production on Monday, 8 August
https://bugzilla.mozilla.org/show_bug.cgi?id=1292612

[fix bug 1292612] remove Hello from products and features pages

---

docs/firefox-accounts.rst
media/js/base/mozilla-fxa-iframe.js

The FxA team is working on an update to the mechanism that authorizes embedding of their iframe. This change is to allow that team to test their new approach. Functionally, nothing should change on mozilla.org due to this PR.
After the new auth mechanism is fully in place, we will file a follow-up PR to remove the current `ping` postMessage auth.
https://bugzilla.mozilla.org/show_bug.cgi?id=1262892
Make sure nothing has changed/no regressions have appeared due to this change. Test locally, on [demo5](https://www-demo5.allizom.org/en-US/firefox/accounts/) (which points to @shane-tomlinson's FxA server for testing the new auth), and on [demo 4](https://www-demo4.allizom.org/en-US/firefox/accounts/) (which points to FxA stage).
(**Reminder:** The iframe only loads on Fx 39+, so shouldn't …

[fix bug 1262892] Add origin param to FxA iframe src.

---

requirements/base.txt

Fix the issue where passing --clean to the `rnasync` command wouldn't run the update if there were no new notes.

Upgrade django-mozilla-rna

---

bedrock/mozorg/templates/mozorg/contribute/friends.html
bedrock/newsletter/templates/newsletter/includes/macros.html
bedrock/newsletter/templates/newsletter/mozilla-and-you.html
bedrock/newsletter/templates/newsletter/one_newsletter_signup.html

Updates the standard "thank you" message shown when subscribing to a newsletter. This uses the l10n tag "newsletter_thanks_072016" and I think the same string resides in both main.lang and in newsletter.lang. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1278380

[fix bug 1278380] Update newsletter thank you message

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html

Update Level 3 policy to match agreement in mozilla.governance.
https://bugzilla.mozilla.org/show_bug.cgi?id=1295618
Textual change only; getting bedrock running is a PITA. Can we have a CMS, please?
module.js:340
throw err;
^
Error: Cannot find module 'readable-stream/duplex'
...

Bug 1295618 - update Level 3 policy to match agreement in mozilla.governance.

---

bedrock/base/database.py
bedrock/events/utils.py
bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
bedrock/mozorg/templates/mozorg/home/home.html
bedrock/settings/__init__.py
bedrock/settings/base.py
bin/circleci-demo-sync.sh
bin/sync_all
circle.yml
docker/run-common.sh
docker/run-dev.sh
docker/run-prod.sh

* Alter config to start wsgi process even without database server
* Change some templates to avoid relying on db data
* No longer run migrations on container start

Fix 1295691: Bedrock process starts without database

---

bedrock/firefox/templates/firefox/includes/download-button.html

Adds the same `data-*` attributes that currently exist on the smart download button to the direct links offered to users with no JS or on an unsupported platform.
https://bugzilla.mozilla.org/show_bug.cgi?id=1296114
Make sure no regressions?

[fix bug 1296114] Add GA to no-JS download links.

---

bedrock/security/templates/security/bug-bounty/faq-webapp.html

Removing hosts from eligible list, they were decomissioned
https://bugzilla.mozilla.org/show_bug.cgi?id=1295743

Removing hostnames from eligible list. Hosts decomissioned.

---

docs/uitour.rst
media/js/firefox/new/scene1.js

- A new UITour method was added in Firefox 48 that tells us if the user profile supports the "Reset Firefox" dialog that we show to up-to-date users on /firefox/new/. This prevents edge-case weirdness, like in [bug 1126559](https://bugzilla.mozilla.org/show_bug.cgi?id=1126559).
https://bugzilla.mozilla.org/show_bug.cgi?id=1274207
- Load `/firefox/new/` in Firefox 48 (make sure you update from product details first), with [UITour enabled](http://bedrock.readthedocs.io/en/latest/uitour.html#local-development). You should still see the "Refresh Firefox" button, and clicking it should still open up the dialog.
- Test this is working for both the old and new template designs.

[fix bug 1274207] Download page should only show 'Refresh Firefox' button if reset is supported

---

media/css/firefox/ios.less

Fixes a minor regression - iOS users visiting /firefox/ios/ should only see an app store badge / link, and not the send to device form as well.
https://bugzilla.mozilla.org/show_bug.cgi?id=1295554
If you can't test on an iOS device changing the class on `<html>` to `ios` should give the same result.

[fix bug 1295554] Firefox iOS page shows both App Store button and Send to Device widget when viewed on iOS

---

bedrock/firefox/templates/firefox/testflight.html

Followup to #4294 to remove superfluous 10n tags, as page is en-US only.
https://bugzilla.mozilla.org/show_bug.cgi?id=1281230

[bug 1281230] Remove l10n tags from TestFlight page template

---

bedrock/settings/base.py
requirements/base.txt

Also add setting for XSS filter header. All are disabled by default so that we can turn them on and test. Also remove sslify and replace with SecurityMiddleware

Bug 1249774: Add SecurityMiddleware and settings for HSTS

---

tests/functional/test_generated_pages.py

@pmac @jgmize r?
I ended up deciding to test only the main pages that list generated content, as opposed to exhaustively parsing the links in each page as it ended up generating thousands of tests. I think this should generally give us enough confidence to alert us when something is broken, although I'd be happy to expand it a bit further if we think it's worth it.

[fix bug 1295693] Add headless http status integration tests for pages that rely on external data

---

bedrock/mozorg/templates/mozorg/about.html
bedrock/mozorg/templates/mozorg/mission.html
bedrock/settings/static_media.py
media/css/mozorg/about.less
media/css/mozorg/mission.less

This is a follow-up to removing the mosaic header on these two pages. It updates the header design and also divorces these pages from about-base.less, which a lot of other pages reference and I didn't want to break that base template and have to update all those other pages as well.
* Replace the mosaic with a single image
* Update newsletter form on /mission
* Some format cleanup and minor fixes
https://bugzilla.mozilla.org/show_bug.cgi?id=1272635

[bug 1272635] Update header on /about and /mission pages

---

bedrock/settings/static_media.py

Removes lingering reference to the recently deleted (see #4259) `mosaic.less`. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1290313
Ensure `/about/manifesto` still renders properly.

[fix bug 1290313] Remove reference to deleted mosaic.less

---

bedrock/foundation/templates/foundation/trademarks/faq.html
bedrock/foundation/templates/foundation/trademarks/policy.html

This page is localized into Japanese only. I'll update the translation later.

Fix Bug 1297571 - Updates needed to links on https://www.mozilla.org/en-US/foundation/trademarks/policy/

---

bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html

Update web bounty HOF with Q2 2016 winners
n/a

Update Web Bounty HOF with Q2 Bounty winners

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

I found these URLs on the back of a sticker. They should work.

Add redirects for careers and donate

---

bedrock/mozorg/templates/mozorg/contact/spaces/auckland.html
bedrock/mozorg/templates/mozorg/contact/spaces/beijing.html
bedrock/mozorg/templates/mozorg/contact/spaces/berlin.html
bedrock/mozorg/templates/mozorg/contact/spaces/london.html
bedrock/mozorg/templates/mozorg/contact/spaces/mountain-view.html
bedrock/mozorg/templates/mozorg/contact/spaces/paris.html
bedrock/mozorg/templates/mozorg/contact/spaces/portland.html
bedrock/mozorg/templates/mozorg/contact/spaces/san-francisco.html
bedrock/mozorg/templates/mozorg/contact/spaces/taipei.html
bedrock/mozorg/templates/mozorg/contact/spaces/tokyo.html
bedrock/mozorg/templates/mozorg/contact/spaces/toronto.html
bedrock/mozorg/templates/mozorg/contact/spaces/vancouver.html

- Fixes mapbox static images on /spaces pages. For some reason the mozorg.cdn.mozilla.net image file no longer seems to work in the request. I'm not 100% clear why it stopped working but this fixes it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1298402
Load each spaces page and make sure the static image is displayed as expected.

[fix bug 1298402] Mapbox static images on /contact pages are 400

---

bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html

Missing name from web bounty q2 16
n/a

Add missing name to q2 2016

---

bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html

Under the Diversity and Inclusion section, in the sublist for "Some Mozillians may identify with activities or organizations that do not support the same inclusion and diversity standards as Mozilla. When this is the case:", there's an occurrence of "when if" in the sentence "when if (a) and (b) are met, other Mozillians should treat this as a private matter, not a Mozilla issue."
I suspect this was meant to be either "when" or "if" but not both, since either makes sense on its own, while both are ungrammatical.
I haven't filed a bug but would be happy to do so if such a change rises to that level.
I haven't tested, as I used GitHub's built-in support for editing files to fix this grammar nit.

correct minor grammar nit ("when if")

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2016.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
bedrock/mozorg/urls.py

Adds a transparency report for the first half of 2016, and adds a link to the old 2015 report. I don't believe any of this content is localized.
We're awaiting final sign-off from Denelle before it goes live so marking do-not-merge for now but we can still begin code review.
https://bugzilla.mozilla.org/show_bug.cgi?id=1295170

[fix bug 1295170] add transparency report for Jan-Jun 2016

---

media/js/mozorg/about-transparency.js

- Scrolls hash/element into view after FAQ accordion has initialized on page load.
- Also small refactor to the existing matchMedia logic to make things a little more DRY.
https://bugzilla.mozilla.org/show_bug.cgi?id=1299943
- URL : `/about/policy/transparency`
- Loading the page in Firefox with a hash should now scroll to the correct position.
- Make sure no other regressions in other browsers?

[fix bug 1299943] Transparency Report definition anchors scroll out of view

---

bedrock/firefox/templates/firefox/releases/release-notes.html
bedrock/firefox/urls.py
bedrock/releasenotes/tests/test_base.py
bedrock/releasenotes/views.py

- Brings back the System Requirements link to release notes pages, replacing the bugzilla list of bugs).
- Also enables System Requirements pages for Android releases (seem to exist for 46.0 and onward for all channels), so older versions still get the old SUMO link.
https://bugzilla.mozilla.org/show_bug.cgi?id=1261810

[fix bug 1261810] Bring back the system requirements link to release notes

---

bedrock/base/templates/product-all-macros.html
bedrock/firefox/templates/firefox/android/index.html
bedrock/firefox/templates/firefox/desktop/customize.html
bedrock/firefox/templates/firefox/ios.html
bedrock/firefox/templates/firefox/new/horizon/scene1.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/private-browsing.html
bedrock/firefox/templates/firefox/sync.html
bedrock/firefox/templates/firefox/whatsnew_42/whatsnew.html
bedrock/firefox/templates/firefox/win10-welcome.html
bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
bedrock/mozorg/templates/mozorg/contribute/index.html
media/js/base/core-datalayer-init.js
media/js/base/core-datalayer.js
tests/unit/spec/base/core-datalayer.js

-Added data attributes for download version and language on downloads on /firefox/all page. 
-Added data attributes for cta positions on cta buttons.
-Added Release Window Version to core datalayer object which pulls from the data-latest-firefox attribute on the `<html>` element on the page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1286903
https://bugzilla.mozilla.org/show_bug.cgi?id=1286933

Data attribute additions

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

This PR will fix the Bug 1262593. Modified urls.py to redirect http://www.mozilla.org/unix/remote to the archived page http://www-archive.mozilla.org/unix/remote.html 
https://bugzilla.mozilla.org/show_bug.cgi?id=1262593

Bug 1262593 - [404] http://www.mozilla.org/unix/remote.html

---

bedrock/firefox/redirects.py
bedrock/firefox/templates/firefox/nightly_whatsnew.html
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/firefox/nightly_whatsnew.less
tests/redirects/map_globalconf.py

[Demo server](https://bedrock-demo-nightly-whatsnew.us-west.moz.works/en-US/firefox/52.0a1/whatsnew/) is ready.
Note: The en-US locale is hardcoded in the MDN link, otherwise the GA query params are omitted on redirect. Until the issue is fixed at MDN side, let's keep the locale.

Fix Bug 1275483 - Create What's New page for Firefox Nightly

---

circle.yml
gulpfile.js

Now that #4271 merged, we can start to do some nice things like use ES6 in our gulp file 😉 
Note: this also updates CircleCI to use node 4

Convert gulpfile.js to use ES6

---

media/js/firefox/mobile-download-desktop.js

Previously provided adjust.com App Store links were incorrect. Also, alphabetized 'em.
https://bugzilla.mozilla.org/show_bug.cgi?id=1299336#c39
Ensure no regressions or typos.

[fix bug 1299336] Update App Store links on mobile download desktop page

---

bedrock/firefox/templates/firefox/mobile-download-desktop.html
bedrock/firefox/urls.py

Deactivates newly created `/firefox/mobile-download/desktop/` URL due to promotion being delayed. Expectation is for page to be released around time of Fx 50 (11/8/2016).
https://bugzilla.mozilla.org/show_bug.cgi?id=1302507

[fix bug 1302507] Deactivate mobile-download/desktop URL.

---

tests/functional/test_download_l10n.py

Adds `/firefox/nightly/all/` to the existing download link tests.
@jgmize r?

Add /firefox/nightly/all/ to download link tests

---

bedrock/redirects/tests/test_util.py
bedrock/redirects/util.py

Discovered via Sentry: https://sentry.prod.mozaws.net/marketing/bedrock-prod-eu-west/issues/349078/

Fix unicode error in redirects

---

docker/bin/softlinkstatic.py

The content of the hashed CSS files is different from the non-hashed versions. In the former the references to other files (e.g. images) have been changed to their hashed versions.  We want to keep these versions since they are served with far-future cache headers and thus reduce our server loads.

Fix bug 1300090: Exempt css files from softlinkstatic.py

---

bedrock/firefox/templates/firefox/family/index.html
bedrock/firefox/templates/firefox/features.html

Failed to remove a few mentions of Hello when updating these pages. These are string changes so I've tagged them with `fx49_remove_hello` (cc: @flodolo and @peiying2)
https://bugzilla.mozilla.org/show_bug.cgi?id=1292612

[bug 1292612] Remove Hello from title and desc

---

bedrock/mozorg/templates/mozorg/contribute/studentambassadors/landing.html

The FSA program is transitioning to Mozilla Campus Clubs. For the time being we will just update the wording to the website and forward students to the [new program](http://campus.mozilla.community).
Changes have already tested locally and l10n is not required.

Update wording for Firefox Student Ambassadors transitioning

---

media/js/base/mozilla-client.js
media/js/firefox/desktop/common.js
media/js/firefox/desktop/index.js
media/js/firefox/desktop/tips.js
media/js/firefox/family-index.js
media/js/firefox/new/scene1.js
media/js/firefox/releasenotes.js
media/js/plugincheck/check-plugins-redesign.js
media/js/plugincheck/check-plugins.js
tests/unit/spec/base/mozilla-client.js

- Switches checks for `_isFirefoxUpToDate()` to only use the major version number until Firefox 49 is released (see bug for context).
https://bugzilla.mozilla.org/show_bug.cgi?id=1301721
- Check in both current & older Firefox (or change UA) to ensure no regressions.

[fix bug 1301721] isFirefoxUpToDate should only use the major version until FF 49 is released

---

.bedrock_demo_env
bedrock/settings/base.py

If a csp-report-uri were to be enabled in prod it could be disasterous. Potentially tousands to POSTs from thousands of browsers all at once. We could DDOS ourselves. Let's only turn this on when we really mean to.
However, if we're going to use CSP in prod we should always have it on so that we catch issues as early as possible. We'll default the middleware to "On", but leave the option to turn it off should we need to.

Change CSP default "on" & csp-report default "off"

---

bedrock/settings/base.py

Also default x-xss-protection to enabled. These changes will further improve our HTTP Observatory score.

Enable x-content-type-options header

---

docs/firefox-accounts.rst
media/js/base/mozilla-fxa-iframe.js
tests/unit/spec/base/mozilla-fxa-iframe.js

Removes now deprecated ping authorization for FxA iframe embed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1262897
Make sure FxA iframe loads and functions properly locally and on [demo4](https://www-demo4.allizom.org/firefox/accounts/).
**You need to update your `user.js` file for local and demo testing!**
There's a new config value required to test FxA on local, demo, and the dev server. Add the following to the `user.js` file associated with your local and demo server testing profiles:
```
user_pref("webchannel.allowObject.urlWhitelist", "https://accounts.firefox.com https://accounts.stage.mozaws.net https://content.cdn.mozilla.net https://input.mozilla.org https://support.mozilla.org https://install.mozilla.org https://stomlinson.dev.lcip.org/");
```
Marking as **Do Not Merge** …

[fix bug 1262897] Remove deprecated FxA ping auth

---

media/js/plugincheck/lib/plugincheck.js

- Fixes plugincheck page in Nightly by avoiding enumerating directly on navigator.mineTypes when checking for Java version.
https://bugzilla.mozilla.org/show_bug.cgi?id=1303076
- You need to have Java plugin installed to reproduce the error.
- Test that plugincheck loads in Nightly (and release for good measure)

[fix bug 1303076] Fix plugincheck to avoid enumerating on navigator.mimeTypes

---

bedrock/settings/base.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1305179
@pmac r?

[fix bug 1305179] Add tagmanager.google.com to CSP script src

---

bedrock/settings/base.py

List of removed locales: be, brx, ee, ha, ig, ln, sat, sw, wo, yo.

[fixed bug 1305063] Remove inactive locales from PROD_LANGUAGES

---

.bedrock_demo_env
Procfile
bedrock/scheduler_utils.py
bin/cron_db.py
bin/cron_l10n.py
docker/run-supervisor.sh
etc/supervisor_available/cron_db.conf
etc/supervisor_available/cron_l10n.conf

This will allow us to run supervisord in www-dev that will run the site and a process to keep l10n updated. It allows us to run this without also running the other cron tasks that update the DB in every container, since we use a separate clock container for that. Demo instances will also run the DB update process via supervisor.
The idea is that if you run `docker/run-supervisor.sh` and `DEV=True` in your environment, it will run the site and the `bin/cron_l10n.py` script. If you also set `DB_CRON=True` in your environment, it will add `bin/cron_db.py` to the processes. This should only really be used in demos and other single process instances. Other instances (like www-dev.allizom.org) use a real DB and have a separate docker container running just the `cron_db.py` script.

Give ability to run supervisor for dev

---

bedrock/mozorg/templates/mozorg/contact/spaces/portland.html

pdx.mozillausa.org was a broken link.
None.
None, just removed the link.

Removed odd and broken link to pdx.mozillausa.org

---

bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html

I’ve found and fixed the following issues while moving the [Japanese translation](http://www.mozilla-japan.org/about/policies/participation.html) to [mozilla.org](https://www.mozilla.org/ja/about/governance/policies/participation/):
* Replace “behaviour” with the en-US spelling
* Remove unnecessary spaces
* Fix a l10n bracket issue

[no bug] Fix minor issues on Community Participation Guidelines

---

bedrock/newsletter/templates/newsletter/existing.html
bedrock/newsletter/tests/test_views.py
bedrock/newsletter/views.py

Add subscription confirmation handling to `/newsletter/existing/`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1297399
Make sure newsletter preferences can be updated when confirming and not confirming subscription.

[fix bug 1297399] Show pref form on email confirmation.

---

bedrock/newsletter/templates/newsletter/existing.html

Hide form fields associated with unsubscribing from users that just confirmed their subscription.
https://bugzilla.mozilla.org/show_bug.cgi?id=1297399#c20
Make sure updating preferences after confirming still works.

[fix bug 1297399] Hide unsubscribe fields from newsletter confirm users.

---

bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html

Update Web Bounty HOF with Q3 Bounty winners
Not a code change
Add Q3 winners, 3 missing names from Q1, 1 from q2

Update Web Bounty HOF with Q3 Bounty winners

---

bedrock/firefox/templates/firefox/releases/release-notes.html

Updated the release notes page template. The "/firefox/releases/" page is now linked to the release notes page. The link can be found in the 'Other Resources" section.
https://bugzilla.mozilla.org/show_bug.cgi?id=1306002

[Fix for Bug 1306002] - Release notes page should link to /firefox/releases/

---

tests/functional/newsletter/test_newsletter_embed.py
tests/functional/test_home.py
tests/functional/test_l10n.py
tests/functional/test_navigation.py
tests/functional/test_technology.py
tests/pages/base.py
tests/pages/home.py
tests/pages/technology.py

Updated functional tests for the new home page. This also required creating a page object for the Technology page in order to test the main site navigation, so I added a test for the technology page blog feed as a separate commit.

Bug 1305661 functional tests for home / technology page

---

media/css/pebbles/base/oldIE.scss

- This should fix the test failures that blocked yesterday's push.
https://bugzilla.mozilla.org/show_bug.cgi?id=1309149

[fix bug 1309149] oldIE.scss is missing download button component

---

bedrock/firefox/redirects.py
tests/redirects/map_globalconf.py

https://ci.us-west.moz.works/job/bedrock_integration_tests/1286/
@pmac r?

Fix channel redirect for legacy URLs

---

bedrock/firefox/templates/firefox/includes/download-button.html
bedrock/firefox/templates/firefox/includes/firefox-footer-links.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/base/mozilla-modal.less
media/css/firefox/new/all-test-variations.less
media/img/firefox/new/down-arrow.svg
media/js/firefox/new/all-test-variations.js
media/js/firefox/new/experiment-all-links.js

Adds two variations to scene 1 of `/firefox/new`. Each variation adds a link underneath the primary download button that:
1. sends the user to `/firefox/all`
2. opens  a modal containing direct download links for all platforms, app store badges, and another primary download button
Understood that the JS is very much a hack right now for the modal variation. If that variation ends up winning, we'll need to figure out a more robust implementation.
Code to serve variations w/out Optimizely will come in a follow-up PR.
https://bugzilla.mozilla.org/show_bug.cgi?id=1295181
The usual. Ensure new links only display when download button is present (i.e. not when using up-to-date Firefox) and only for en-US. Double check old IE.
https://bedrock-demo-jpetto-fxnew.us-west.moz.works/en-US/firefox/new/? …

[fix bug 1295181] Test /all links on /firefox/new/.

---

bedrock/security/tests/test_utils.py
bedrock/security/utils.py

* [Add optional description before all CVEs](https://bugzilla.mozilla.org/show_bug.cgi?id=1310736)
* [Ensure CVEs are ordered correctly](https://bugzilla.mozilla.org/show_bug.cgi?id=1310734)

Fix some issues with YML formatted security advisories

---

media/js/firefox/new/experiment-all-links.js

Shrinking audience significantly to reduce risk. According to pg, should give us enough data in 2 days at this new rate.
https://bugzilla.mozilla.org/show_bug.cgi?id=1295181#c29
Make sure double control variation works as expected. (Easiest way is probably to boost the `v=3` variation percentage.)

[fix bug 1295181] Update audience size/segmentation for fx /new all test

---

media/js/base/global.js

Bug 1311037 - The language switcher doesn't take the anchor into account
https://bugzilla.mozilla.org/show_bug.cgi?id=1311037
Manual testing

Bug 1311037 - The language switcher doesn't take the anchor into account

---

media/js/base/mozilla-traffic-cop.js
tests/unit/spec/base/mozilla-traffic-cop.js

Ensure URL hash is handled appropriately in redirect URL when present in the original URL.
As the variant experience could be completely different from the control - hash element may not exist, we may want a "fresh" (no page scrolling) UX - I decided to drop the hash instead of adding it back to the variation URL.
However, I'm not completely sold on this approach. I suppose it could be a config option with the default being no hash, but that smells like over-engineering. My gut is saying leave it off until a specific case arises where we need it.
It would be relatively simple to add the hash on to the variation URL, so, thoughts?
https://bugzilla.mozilla.org/show_bug.cgi?id=1311052
Change a local test to have 100% variation coverage and open some private windows.

[fix bug 1311052] Traffic Cop will ignore URL hash.

---

bedrock/firefox/templates/firefox/new/scene2.html
bedrock/settings/base.py
bedrock/settings/static_media.py
media/js/firefox/new/pixel.js

This is pretty much just a reversal of https://github.com/mozilla/bedrock/commit/6f30fd090b658a34a1ef706e8a21f7819be2f8c3
@jpetto r?

[bug 1311423] Re-enable flashtalking pixel on /firefox/new/

---

media/css/foundation/foundation.less

mozilla.org/foundation has a horizontal scroll on small webkit viewports due to a flexbox bug. This solves that.
https://bugzilla.mozilla.org/show_bug.cgi?id=1309321
Visual
Programs now stay within the appropriate column.

Fix foundation homepage on webkit small screen

---

bedrock/base/templates/base-pebbles.html
bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html

While Pontoon is only loaded on dev environments, it still throws JS errors in older browsers such as IE.
This can be a bit annoying when trying to debug real issues, so let's not load it for older browsers.

Don't load Pontoon on dev for older browsers

---

bedrock/firefox/templates/firefox/new/scene1-ie8.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/sandstone/buttons.less
media/js/base/oldie-nojs.js
media/js/firefox/new/experiment-oldie-nojs.js

Prep pages to serve updated/minimal JS to IE <= 8. ~~Traffic will be directed by Optimizely experiment (to be created).~~ Traffic will be directed using our Traffic Cop.
Also removes some of the code (bundles, template & view logic) from the /all test run in early October. (Assets from that test still exist as they will likely be re-purposed for a future test.)
https://bugzilla.mozilla.org/show_bug.cgi?id=1288517
~~Test `/firefox/new/?v=2` and `/firefox/new/` in modern browsers and in IE 7 & 8.~~
Make sure `/firefox/new/?v=1` functions correctly in IE 7 (regular download button), IE 8 (no JS download buttons), and modern browsers (regular download button). Make sure Traffic Cop experiment functions as expected.

[fix bug 1288517] Test dumb download links in IE <= 8.

---

bedrock/mozorg/templates/mozorg/moss/index.html

Copy update/fix requested by Gerv.
https://bugzilla.mozilla.org/show_bug.cgi?id=1307998#c21

[fix bug 1307998] Remove superfluous copy from MOSS home page.

---

bedrock/base/templates/product-all-macros.html
bedrock/firefox/firefox_details.py
bedrock/firefox/templates/firefox/all.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/tests/test_helpers.py
bedrock/settings/static_media.py
bedrock/thunderbird/details.py
bedrock/thunderbird/templates/thunderbird/includes/download-button.html
bedrock/thunderbird/tests/test_base.py
bedrock/thunderbird/tests/test_helpers.py
media/css/firefox/all-oldIE.less
media/css/firefox/all.less
media/css/firefox/new/all-test-variations.less
media/css/pebbles/components/_buttons-download.scss
media/css/sandstone/buttons.less
media/js/base/site.js
media/js/firefox/new/all-test-variations.js
tests/unit/spec/base/site.js

- Still WIP but opening this early to make sure I'm on the right path in terms of implementation.
https://bugzilla.mozilla.org/show_bug.cgi?id=1304538
Demo:
- https://www-demo1.allizom.org/en-US/firefox/new/
- https://www-demo1.allizom.org/en-US/firefox/all/
- https://www-demo1.allizom.org/en-US/firefox/channel/desktop/

[fix bug 1304538] Add sha-1 download buttons for IE 6-8

---

bedrock/mozorg/views.py

Check correct lang file (as used in [the new homepage template](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/home/home.html#L8)) in the view when deciding which template to serve.
https://bugzilla.mozilla.org/show_bug.cgi?id=1313323
(Bug doesn't actually reference this issue - @flodolo mentioned it in IRC, but the 2 may well be related.)

[fix bug 1313323] Fix home 2016 lang file name.

---

bedrock/newsletter/views.py

Update title and description of the `app-dev` newsletter.
https://bugzilla.mozilla.org/show_bug.cgi?id=1313371
As this newsletter is now English only, and since the Firefox Friends newsletter is also English only and [currently untranslated](https://www.mozilla.org/fr/newsletter/existing/80a58e10-88ee-4369-aabe-881da32a1aba/), I don't think we need to block on/code around L10n.

[fix bug 1313371] Update app-dev newsletter title & description.

---

media/css/mozorg/about-forums.less

Add highlighting for :target to forums page. Added background colour to the target element & added some padding to the .forums > li element.
https://bugzilla.mozilla.org/show_bug.cgi?id=1313032

[fix Bug 1313032] - highlight the target element on the forums page

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

Redirect /download.html to /firefox/products/
https://bugzilla.mozilla.org/show_bug.cgi?id=681572

Fix BUG 681572. redirect /download.html to /firefox/products/

---

bedrock/firefox/templates/firefox/developer.html
docs/newsletters.rst

Updates the en-* newsletter title and hides the language selector. Non en-* locales get the fallback `mozilla-and-you` newsletter.
Also removes section in docs referring to the [recently removed embeddable URL](https://github.com/mozilla/bedrock/pull/4406) for the developer newsletter.
https://bugzilla.mozilla.org/show_bug.cgi?id=1313508
Make sure no typos?

[fix bug 1313508] Update /firefox/developer/ newsletter.

---

docs/firefox-accounts.rst
docs/install.rst
gulpfile.js

- Removes running the local dev server as a child-process that's part of the gulp command, as it sometimes causes the heebie jeebies after a rebase.
@craigcook r?

Remove local dev-server child-process from default gulp command

---

bedrock/newsletter/templates/newsletter/index.html
bedrock/newsletter/tests/test_views.py
bedrock/newsletter/views.py

Updates the newsletter id used on [mozilla.org/newsletter/](https://www.mozilla.org/en-US/newsletter/).
https://bugzilla.mozilla.org/show_bug.cgi?id=1313714
Make sure I didn't miss updating any dependencies.

[fix bug 1313714] Update newsletter id on /newsletter.

---

bedrock/mozorg/templates/mozorg/home/home-a.html
bedrock/mozorg/templates/mozorg/home/home-b.html
bedrock/mozorg/templates/mozorg/home/home-c.html
bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/tests/test_views.py
bedrock/mozorg/views.py
bedrock/settings/static_media.py
media/css/mozorg/home/home.scss
media/js/mozorg/home/experiment-home-fx-copy.js

Prepare experiment to test 3 different copy blocks in the Firefox section of the home page.
Also removes gap in Firefox copy for all variants & control, and shortens Firefox section a bit.
https://bugzilla.mozilla.org/show_bug.cgi?id=1313717
Ensure variants load as expected for en-* locales.

[fix bug 1313717] Homepage Fx copy tests.

---

bedrock/settings/local.py-dist

As we have moved from `bedrock/settings/local.py` to `/.env`, removing `bedrock/settings/local.py-dist` to avoid confusion/clean up codebase.
Nope.
Double check that no references or dependencies remain to `local.py`.

Remove local.py-dist

---

media/css/mozorg/home/home.scss

Fixes copy display issue in Fx copy section on home page introduced by #4458.
https://bugzilla.mozilla.org/show_bug.cgi?id=1317171
Make sure text is no longer covered by tree images for various locales.

[fix bug 1317171] Stop home Fx copy from being covered by image.

---

bedrock/newsletter/templates/newsletter/developer.html
bedrock/newsletter/templates/newsletter/firefox.html
bedrock/newsletter/templates/newsletter/mozilla.html

- Adds meta descriptions for newsletter landing pages (re-using page subtitles)
https://bugzilla.mozilla.org/show_bug.cgi?id=1316631

[fix bug 1316631] Newsletter landing pages are missing meta descriptions

---

gulpfile.js
lockdown.json
package.json
static/.gitignore

Add a little `gulp static:clean` task as a handy alternative to using `git clean` for static media (which is arguably simpler, but this seems a little less dangerous for accidents occurring). I stopped short of running this automatically when just running `gulp`, but it's something we *could* also do if we thought it was beneficial enough (although it could create issues of its own). But it seems like this is mainly useful for PR's that remove code, which are obvious enough to spot.

Add gulp clean task for /static when in local development

---

bedrock/mozorg/templates/mozorg/internet-health.html
tests/functional/test_internet_health.py

- Updates a link.
- Removes a line of copy from a string. @flodolo says we haven't started translating this page yet, so I don't believe we need an l10n tag.
https://bugzilla.mozilla.org/show_bug.cgi?id=1319158

[fix bug 1319158] Change link on /internet-health/ page

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-50.html
bedrock/settings/static_media.py

Adds a reference to the correct JS files/bundle to the Fx 50.0 whatsnew template.
(The JS file was included in the original PR #4425, but wasn't added as a bundle/to the template. 😞 )
https://bugzilla.mozilla.org/show_bug.cgi?id=1319842
Double-check previously merged JS file and ensure all is well when used.

[fix bug 1319842] Use correct JS bundle for Fx 50 whatsnew.

---

media/css/mozorg/internet-health.scss

If localized copy is shorter than en-US, section footer overlaps section icon. Adds a `min-height` to the copy area to force footer below icon.
https://bugzilla.mozilla.org/show_bug.cgi?id=1319684
Delete/shorten text in any one of the sections and make sure section footer doesn't overlap icon.

[fix bug 1319684] Fix internet health section heights for L10n.

---

bedrock/newsletter/templates/newsletter/developer.html
bedrock/newsletter/templates/newsletter/mozilla.html

Add the optimizely block to two newsletter templates (mozilla and developer)
https://bugzilla.mozilla.org/show_bug.cgi?id=1319891
Verified that tag shows up in code. Ran tests on newsletter application, which passed.

[fix bug 1319891] Add optimizely block to newsletter templates

---

bedrock/mozorg/templates/mozorg/internet-health.html

Updates the meta title, description, and page image.
https://bugzilla.mozilla.org/show_bug.cgi?id=1319909
Make sure no typos or L10n issues?

[fix bug 1319909] Update internet health page meta.

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
tests/redirects/map_globalconf.py

An unthrottled Fx update that opens /whatsnew/ causes
massive spike in traffic to bedrock, so these pages
can not be uncached at the CDN.

Remove non-fx redirect from firstrun/whatsnew

---

bedrock/privacy/redirects.py
bedrock/privacy/templates/privacy/index.html
bedrock/privacy/urls.py
tests/redirects/map_globalconf.py

Creates a custom privacy URL for Firefox Focus visitors hitting the `de` locale.
https://bugzilla.mozilla.org/show_bug.cgi?id=1319207
Ensure that visiting `/de/privacy/firefox-focus/` redirects to `/de/privacy/firefox-klar/`. Also ensure any non-de locale hitting `/privacy/firefox-klar/` is redirected to `/{locale}/privacy/firefox-focus/`.

[fix bug 1319207] Add custom privacy URL for Firefox Focus in de locale.

---

bedrock/newsletter/views.py

A valid API key is requrired if they're interacting with a private newsletter
(e.g. the NDA Mozillians one)

Fix bug 1318429: Include basket api key with email pref center update

---

bedrock/mozorg/templates/mozorg/home/includes/takeover-2016.html
media/js/mozorg/home/takeover-2016.js

So in my enthusiasm for localizing the currency with the fancy new Intl API I foolishly broke the entire form. I was replacing the label contents with the localized text and didn't even notice that I was also replacing the hidden radio buttons.
This fixes my stupid mistake by wrapping the label text in a span and replacing THAT instead.
https://bugzilla.mozilla.org/show_bug.cgi?id=1321440
Verify the form works and submits the selected value to donate.mozilla.org

[fix bug 1321440] unbreak fundraising takeover buttons

---

bedrock/mozorg/templates/mozorg/technology.html
bedrock/settings/static_media.py
media/css/mozorg/technology.scss
media/js/mozorg/technology.js

- Adds Rust video modal to `/technology` landing page using YouTube JS API.
- The ask is to show the video in English for all locales until we can add subtitles (sorry in advance).
https://bugzilla.mozilla.org/show_bug.cgi?id=1320666
- Still need to verify GA events on demo.

[fix bug 1320666] Embed Rust video in modal overlay on /technology landing page

---

bedrock/base/templates/includes/google-search-activist.html
bedrock/foundation/templates/foundation/base-resp.html
bedrock/foundation/templates/foundation/index.html
bedrock/foundation/urls.py
bedrock/foundation/views.py
bedrock/mozorg/templates/mozorg/about.html
bedrock/mozorg/templates/mozorg/about/manifesto.html
bedrock/mozorg/urls.py
bedrock/mozorg/views.py
bedrock/settings/base.py
bedrock/settings/static_media.py
media/css/foundation/foundation.less
media/css/mozorg/about.less
media/css/mozorg/manifesto.less
media/css/pebbles/components/google-search.scss
media/js/base/search-activist.js
media/js/mozorg/experiment-search-activist.js

Adds a Google custom search box to a few pages:
* /about
* /about/manifesto
* /foundation/*
This is the "Activist" search indexing sites mostly focused on advocacy, web education, internet health, etc.
The test will be English only and uses the switch `mozorg-search-activist`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1319244
Mostly visual, since we're doing some CSS hackery to customize the look of their search box. Also verify searching works as expected and doesn't throw JavaScript errors.

[bug 1319244] test Activist cross-site search

---

bedrock/mozorg/templates/mozorg/home/includes/takeover-2016.html

I got the campaign ID wrong for the UTM params. This corrects that mistake.
https://bugzilla.mozilla.org/show_bug.cgi?id=1316375#c25

[bug 1316375] Update EOY campaign ID

---

bedrock/settings/base.py

Follow up of bug 1316375, updating the currencies after the changes landed in https://github.com/mozilla/donate.mozilla.org/commit/7e9b6825f8fe2a15971e57f2edec335df8f768fd
https://bugzilla.mozilla.org/show_bug.cgi?id=1320119
- Check donate link on homepage footer

Bug 1320119 - Update donate currencies

---

tests/functional/test_download_l10n.py

@pmac r?
No rush to look at this, I know you're traveling! (It's 4.30am and I'm awake, so thought I might as well try and do something productive).
P.S - I ran this locally and it passes.

Skip broken Fennec link for 'be' until bug 1321262 is resolved

---

bedrock/foundation/templates/foundation/about.html
bedrock/mozorg/templates/mozorg/about/leadership.html

Just cleaning up. This content no longer needs to be hidden behind a switch.
https://bugzilla.mozilla.org/show_bug.cgi?id=1320808

[bug 1320808] Remove Turvey announcement switches

---

bedrock/security/templates/security/bug-bounty/faq-webapp.html

This adds the Observatory to the bug bounty list, and removes Persona.
@jeffbryner, can I get some r+ on the addition of the Observatory?
https://bugzilla.mozilla.org/show_bug.cgi?id=1321479

Remove Persona from the web sec bounty and add the Observatory

---

bedrock/foundation/templates/foundation/annualreport/2015/index.html

Remove spurious whitespace in links from 2015 annual report.
Not reported to Bugzilla. Is this something I should do next time?
None, seems obvious enough...

Remove spurious whitespace in links from 2015 annual report

---

bedrock/foundation/templates/foundation/documents/index.html

Add links to the 2015 annual report and tax filings which are currently missing.
Not reported to Bugzilla. Is this something I should do next time?
None, seems obvious enough...

Add links to 2015 annual report and tax filings

---

bedrock/firefox/templates/firefox/all.html

We now have more locales, let’s be proud of it :) We’re still not localizing this page, so I’m not adding a l10n tag.
https://bugzilla.mozilla.org/show_bug.cgi?id=1323417
Description & Tweet on https://www.mozilla.org/en-US/firefox/all/ are updated.

Fixes bug 1323417 - Update the number of languages on firefox/all to 90

---

Procfile
bedrock/mozorg/management/commands/update_product_details_files.py
bedrock/mozorg/tests/test_commands.py
bedrock/security/management/commands/update_security_advisories.py
bedrock/security/tests/test_commands.py
bedrock/settings/base.py
bedrock/utils/git.py
bedrock/utils/migrations/0001_initial.py
bedrock/utils/models.py
bedrock/utils/tests/test_git.py
docker/run-clock.sh
etc/supervisor_available/cron_db.conf

Reset git repos from git-based data import commands (e.g. update_security_advisories) when data import fails but the git update succeeds. In this way the next run of the command will try again and see all of the changed files.

Fix bug 1315082: Reset git repos on failed db updates

---

bedrock/settings/static_media.py
media/js/mozorg/home/takeover-2016.js

We were previously using sessionStorage to disable the takeover once you'd seen it, but it meant you'd get the takeover again with any new session. It was decided that was potentially annoying to repeat visitors, so this switches to a permanent cookie with a 7 day expiration.
https://bugzilla.mozilla.org/show_bug.cgi?id=1316375
Verify that the cookie is being set, is set to expire in 7 days, and that the takeover isn't shown again when the cookie is present. The takeover should also not be shown if cookies are disabled (otherwise you'd see it on every refresh).

[bug 1316375] Set a cookie for the EOY takeover

---

bedrock/newsletter/templates/newsletter/firefox.html

Adds an optimizely code block behind a waffle switch to the firefox newsletter template.
https://bugzilla.mozilla.org/show_bug.cgi?id=1324161

[fix bug 1324161] Add optimizely block to firefox newsletter template

---

bedrock/firefox/templates/firefox/private-browsing.html

Some links on /firefox/private-browsing included a hard-coded en-US locale. Removing the locale from the URL lets SUMO's locale detection redirect appropriately.
https://bugzilla.mozilla.org/show_bug.cgi?id=1324141

[fix bug 1324141] Remove locale from SUMO links

---

bedrock/firefox/redirects.py
bedrock/mozorg/redirects.py
tests/functional/test_l10n.py
tests/redirects/map_globalconf.py

- Do not merge while translations to existing pages are checked on demo.
https://bugzilla.mozilla.org/show_bug.cgi?id=1316044
https://www-demo1.allizom.org/zh-TW/

[fix bug 1316044] Remove redirects from mozilla.org/zh-TW to http://mozilla.com.tw/

---

bedrock/legal/redirects.py
bedrock/legal/templates/legal/index.html
bedrock/legal/templates/legal/terms/firefox-hello.html
bedrock/legal/urls.py
bedrock/privacy/redirects.py
bedrock/privacy/templates/privacy/archive/hello-2014-11.html
bedrock/privacy/templates/privacy/archive/hello-2016-03.html
bedrock/privacy/templates/privacy/archive/index.html
bedrock/privacy/urls.py
tests/functional/test_generated_pages.py

Archives the current Hello [privacy policy](https://www.mozilla.org/privacy/firefox-hello/) and [terms of service](https://www.mozilla.org/about/legal/terms/firefox-hello/). Adds redirects from decommissioned URLs to the new archive pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1321033
Content on archive pages is copy/paste from HTML generated by existing legal docs markdown, so double check tag completion/nesting. Make sure redirects work as expected.

[fix bug 1321033] Hello EOL legal doc cleanup/archival.

---

bedrock/firefox/templates/firefox/channel/desktop.html
bedrock/firefox/templates/firefox/developer.html

We need a distinct switch so we can turn off the traffic cop redirect without disabling search entirely. The new switch is `experiment-search-developer`
https://bugzilla.mozilla.org/show_bug.cgi?id=1323315

[bug 1323315] Add separate switch for dev search traffic cop

---

bedrock/settings/static_media.py
docs/mozilla-traffic-cop.rst
media/js/base/mozilla-cookie-helper.js
media/js/base/mozilla-traffic-cop.js
media/js/mozorg/home/takeover-2016.js
tests/unit/spec/base/mozilla-traffic-cop.js

- Also adds enabled() cookie feature detect function to helper
https://bugzilla.mozilla.org/show_bug.cgi?id=1324722
- Test to make sure no I didn't introduce any regressions, or miss any other pages/experiments?

[fix bug 1324722] Relocate Mozilla.Cookies helper to site.js bundle

---

bedrock/firefox/templates/firefox/releases/release-notes.html
media/css/firefox/desktop/index.less
media/css/firefox/desktop/tips.less
media/css/firefox/releasenotes-firefox.less
media/js/firefox/desktop/common.js
media/js/firefox/desktop/tips.js
tests/functional/firefox/desktop/test_desktop.py

- Simplifies download button logic on a few remaining pages (we already covered the home page and main download page in different bugs):
- `/firefox/desktop/`
- `/firefox/desktop/tips/`
- `/firefox/releasenotes/`
I decided to leave `/products/` as is, since the download bar is more of a conditional UI, and the additional changes to `/desktop` already make it easier for Firefox pre-release users to download.
https://bugzilla.mozilla.org/show_bug.cgi?id=1323707
- Test to make sure no visual regressions, download buttons show correctly etc.

[fix bug 1323707] Remove conditional logic that hides download buttons from Firefox users

---

bedrock/mozorg/templates/mozorg/contact/spaces/auckland.html
bedrock/mozorg/templates/mozorg/contact/spaces/london.html
bedrock/mozorg/templates/mozorg/contact/spaces/mountain-view.html
bedrock/mozorg/templates/mozorg/contact/spaces/portland.html
bedrock/mozorg/templates/mozorg/contact/spaces/san-francisco.html
bedrock/mozorg/templates/mozorg/contact/spaces/toronto.html
bedrock/mozorg/templates/mozorg/contact/spaces/vancouver.html

It seems people occasionally drop into local office IRC channels seeking Firefox support. Those channels are mainly for folks in those offices, not necessarily for the general public, so this removes IRC channels from the contact pages for Mozilla spaces (leaving them for local communities).
This replaces #4538

[no bug] Remove IRC contact info from Mozilla spaces

---

bedrock/firefox/templates/firefox/family/index.html

Updates copy on /products to be consistent with the newer download page messaging.
https://bugzilla.mozilla.org/show_bug.cgi?id=1323829

[fix bug 1323829] Update non-Fx header copy on /firefox/products/

---

bedrock/firefox/firefox_details.py
bedrock/firefox/templates/firefox/all.html
bedrock/firefox/templates/firefox/channel/android.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py
bedrock/firefox/views.py
tests/functional/test_download_l10n.py

* A cleaned-up version of #4382
* Create [/firefox/android/aurora/all/](https://bedrock-demo-android-all.us-west.moz.works/en-US/firefox/android/aurora/all/) and [/firefox/android/nightly/all/](https://bedrock-demo-android-all.us-west.moz.works/en-US/firefox/android/nightly/all/) to complete /all/ download pages
* List only the multi-locale builds on all the Android /all/ pages, as discussed in the bug
[Bug 1301650](https://bugzilla.mozilla.org/show_bug.cgi?id=1301650)
* Those new /all/ pages for Nightly and Aurora can be found on [/firefox/channel/android/](https://bedrock-demo-android-all.us-west.moz.works/en-US/firefox/channel/android/)
* The single-locale builds should not be listed any more.
* The api-9 code will be deleted ([Bug …

Fix Bug 1301650 - Implement mozilla.org/firefox/android/nightly/all to list all localized Fennec Nightly builds

---

Jenkinsfile
bin/circleci-trigger-jenkins.sh
bin/tag-release.sh
circle.yml
docker/jenkins/check_if_tag.sh

The new Jenkins Multibranch Pipeline will now start the bedrock build jobs instead of having CircleCI do it. This wil mean having to push to a "prod" branch to trigger a prod deployment, but it should be much better and faster than waiting for Circle.

Switch to using a Jenkins Multibranch Pipeline for deploy

---

bedrock/firefox/firefox_details.py
bedrock/firefox/templates/firefox/channel/android.html
bedrock/firefox/templatetags/helpers.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py

* Use the Google Play store link for Firefox Aurora on the [Android channel page](https://www.mozilla.org/en-US/firefox/channel/android/), instead of direct archive links for ARMv7 and x86.
* Add a [Learn More](https://support.mozilla.org/kb/participate-firefox-android-testing-program) link to the Aurora section, which was created in [Bug 1304445](https://bugzilla.mozilla.org/show_bug.cgi?id=1304445). The string has been localized for the desktop channel page, so no l10n required here.
[Bug 1304448](https://bugzilla.mozilla.org/show_bug.cgi?id=1304448)
* The channel page shows the Google Play link and Learn More link for Aurora.
* No other changes.

Fix Bug 1304448 - Figure out a way from mozilla.org to be able to install Firefox aurora on Google play

---

media/js/mozorg/manifesto.js

Add support for linking to each principle by utilizing the History API.
[Bug 1325284](https://bugzilla.mozilla.org/show_bug.cgi?id=1325284)
* Open, navigate and close the modal.
* Load the page with a hash in the URL, like `#principle-01`.

Fix Bug 1325284 - It isn't possible to directly link to a manifesto principle

---

bedrock/firefox/redirects.py
bedrock/redirects/tests/test_util.py
bedrock/redirects/util.py
tests/redirects/map_globalconf.py

Currently [/firefox/channel/](https://www.mozilla.org/en-US/firefox/channel/) is redirected to [/firefox/channel/desktop/](https://www.mozilla.org/en-US/firefox/channel/desktop/) unconditionally. It should be redirected to [/firefox/channel/android/](https://www.mozilla.org/en-US/firefox/channel/android/) on Android and [/firefox/channel/ios/](https://www.mozilla.org/en-US/firefox/channel/ios/) on iOS.
[Bug 1326383](https://bugzilla.mozilla.org/show_bug.cgi?id=1326383)
Spoof the UA string and visit /firefox/channel/, then make sure the URL is redirected to one of the platform-dependent locations.

Fix Bug 1326383 - When I visit nightly.mozilla.org on Android, it takes me to a page about *Desktop* Nightly (with no Android download options)

---

bedrock/mozorg/templates/mozorg/about/leadership.html

Just cleans up the switch now that we no longer need it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1323841

[bug 1323841] Remove boyd-announce switch from leadership page

---

bedrock/foundation/urls.py

Sets SOM 2015 as the default. After this makes it to prod, we can remove the SWITCH_SOM_2015 switch.
https://bugzilla.mozilla.org/show_bug.cgi?id=1317727

[fix bug 1317727] Set SOM 2015 as default.

---

bedrock/base/templates/macros.html
bedrock/legal/templates/legal/fraud-report.html
bedrock/mozorg/templates/mozorg/contribute/studentambassadors/join.html
bedrock/mozorg/templates/mozorg/credits.html
bedrock/mozorg/templates/mozorg/partnerships.html
bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/tests/test_helper_misc.py
bedrock/newsletter/templates/newsletter/existing.html
bedrock/newsletter/templates/newsletter/recovery.html
bedrock/newsletter/templates/newsletter/updated.html
bedrock/press/templates/press/speaker-request.html

Since `mozilla.org` is now all `https` 🔒, we don't really need a `secure_url` helper. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1322704
Ensure no regressions on links or forms. It's on [a demo](https://bedrock-demo-jpetto-secureurl.us-west.moz.works/en-US/) as well.

[fix bug 1322704] Remove secure_url helper.

---

media/js/firefox/new/scene2.js

- Removes legacy GA download event, simplifying the JS for scene2 of the download page considerably.
https://bugzilla.mozilla.org/show_bug.cgi?id=1311643
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/

[fix bug 1311643] Remove legacy 'virtual-pageview' GA event from scene2 of /firefox/new/

---

bedrock/firefox/templates/firefox/os/index.html

- Removes a link that was missed in #4558 
https://bugzilla.mozilla.org/show_bug.cgi?id=1324736

[fix bug 1324736] Remove Firefox OS participation hub link

---

bedrock/firefox/redirects.py
bedrock/firefox/templates/firefox/channel/desktop.html
tests/redirects/map_globalconf.py

Like #4555, the following URLs should be redirected to an appropriate channel page depending on the UA. To simplify the code, I used the `aurora` anchor for the desktop Developer Edition as well. iOS doesn't have Nightly nor Aurora, but it's probably still better to show the iOS channel page instead of the desktop equivalent.
* https://www.mozilla.org/nightly/
* https://www.mozilla.org/aurora/
* https://www.mozilla.org/beta/
* https://www.mozilla.org/firefox/nightly/
* https://www.mozilla.org/firefox/aurora/
* https://www.mozilla.org/firefox/beta/
[Bug 1328409](https://bugzilla.mozilla.org/show_bug.cgi?id=1328409)
Spoof the UA string and visit those URLs, then make sure you're redirected to one of the platform-dependent locations.

Fix Bug 1328409 - Make Firefox pre-release redirects platform-aware

---

bedrock/newsletter/templates/newsletter/mozilla.html

- Updates copy based on winning Optimizely experiment (almost 14% improvement in sign up conversions).
https://bugzilla.mozilla.org/show_bug.cgi?id=1328404

[fix bug 1328404] Update copy for Mozilla newsletter signup page

---

docs/uitour.rst
media/js/base/uitour-lib.js

- Adds a new UITour function to open about:newtab and updates bedrock docs.
- ~~Marking as do-not-merge for now until uplifted to Firefox 51, but it is testable in the latest Nightly as of now.~~
https://bugzilla.mozilla.org/show_bug.cgi?id=1322726
Make sure it works as expected.

Update UITour lib and docs for showNewTab()

---

bedrock/base/templates/base-pebbles.html
bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
bedrock/mozorg/templates/mozorg/home/includes/nav.html
bedrock/mozorg/templates/mozorg/moss/base.html
media/css/mozorg/home/home.scss
media/css/mozorg/internet-health.scss
media/css/mozorg/technology.scss

- Exposes links for new landing pages in main nav for all locales (enough locales now have the translated strings).
- Hides the nav download button at tablet breakpoints to accommodate the new longer strings. I would have liked a way around this, but testing different locales it just becomes too squished to fit everything on 😢. The other option would be to hide the wordmark, but I settled on it being more important for the header (particularly for the home page, which also features a separate Firefox download CTA). 
https://bugzilla.mozilla.org/show_bug.cgi?id=1316892
- We have a few variations on the masthead for different pages, so double check to make sure I didn't miss any more?

[fix bug 1316892] Expose nav links to /technology and /internet-health for all locales

---

bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/templates/mozorg/home/includes/nav.html
media/css/mozorg/home/home.scss

While the takeover was behind a switch, the navbar changes weren't. This puts those style changes behind the same switch as the takeover (using a class for the color; kinda kludgey but it only needs to last a day).
https://bugzilla.mozilla.org/show_bug.cgi?id=1331048
Ensure the navbar shows the old wordmark and coloring when the switch is off.

[bug 1331048] Hide navbar styling behind switch

---

bedrock/mozorg/templates/mozorg/internet-health.html
media/css/mozorg/internet-health.scss

Adds a block to the internet health landing page that links to internethealthreport.org. The block is behind the switch `internet-health-report-live` which we should flip once the website is confirmed live (planned for 19 January around 9am PST).
Uses the l10n tag `mozorg-health-report` for two new strings. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1330435

[fix bug 1330435] Add link to internet health report to health landing

---

bedrock/firefox/templates/firefox/new/scene2.html

- Marking as do-not-merge for now, as I have some reservations about the accuracy of the new headline.
https://bugzilla.mozilla.org/show_bug.cgi?id=1330441

[fix bug 1330441] Update headline on download confirmation page

---

tests/functional/newsletter/test_newsletter_embed.py
tests/functional/test_home.py
tests/functional/test_l10n.py
tests/functional/test_navigation.py

We hit some intermittent failures on the last prod push [1], [2] in IE as it seem to have trouble detecting the homepage popup that appears at the bottom of the screen. I could sink a ton of time into debugging this to try and make it more resilient, but this probably isn't worth it as it's only going to be around for a couple of weeks. This PR skips said tests in IE.
We need to remember to unskip these tests again when the popup gets removed.
[1] https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/11163/
[2] https://ci.us-west.moz.works/job/bedrock_integration_tests_runner/11169/

Skip home page tests in IE due to brand popup

---

bedrock/firefox/templates/firefox/new/break-free/scene2.html
bedrock/firefox/templates/firefox/new/scene2.html
bedrock/firefox/templates/firefox/new/way-of-the-fox/scene2.html
bedrock/settings/base.py
media/js/firefox/new/pixel.js

- Replaces Flashtalking Tracking Pixel With DoubleClick
- Updates switch name for the pixel to be more generic. We'll have to remember to turn this on again in staging / prod, and remove the old switch.
- We'll need to make sure the flip `SWITCH_TRACKING_PIXEL` is turned on on stage / prod prior to pushing this. The double click switch (`SWITCH_DOUBLE_CLICK`) should be turned on Feb 1st (this will toggle off Flash Talking).
https://bugzilla.mozilla.org/show_bug.cgi?id=1331069
- Demo: https://www-demo1.allizom.org/en-US/firefox/new/?scene=2
- Test that the correct pixel is triggered depending on the switch?

[fix bug 1331069] Replace Flashtalking Tracking Pixel With DoubleClick

---

bedrock/mozorg/templates/mozorg/about/leadership.html

Removes Hoffman from active MoCo board and moves him to emeritus status. It's a fairly minor code change, no l10n impact, and should go to production as soon as possible.
https://blog.lizardwrangler.com/2017/01/31/a-thank-you-to-reid-hoffman/
https://bugzilla.mozilla.org/show_bug.cgi?id=1335248

[fix bug 1335248] Remove R. Hoffman from MoCo board

---

bedrock/mozorg/templates/mozorg/about/leadership.html

Updates the download links to point to assets.mozilla.org.
https://bugzilla.mozilla.org/show_bug.cgi?id=1330090

[fix bug 1330090] Update leadership photo download links

---

root_files/favicon.ico
root_files/favicon.png

Makes /favicon.ico work, thus avoiding many 404s.

Add symlinks to favicon.ico to root files

---

.stylelintrc

As mentioned in #4610 (and #4607), Stylelint could use a rule to ensure newlines between CSS declarations. This change adds the rule "declaration-block-semicolon-newline-after" ([view on Stylelint](https://stylelint.io/user-guide/rules/declaration-block-semicolon-newline-after/)) with value "always -multi-line".
Ie, with this new rule, now this:
```less
#swatch_f4f4f4 .swatch span {
background-color: #f4f4f4; color: #000;
}
```
will trigger a warning; and this:
```less
#swatch_f4f4f4 .swatch span {
background-color: #f4f4f4;
color: #000;
}
```
will not.

Add "declaration-block-semicolon-newline-after" rule to Stylelint

---

bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py

The data includes a timestamp, so we can't cache for long.

Update the stub-attribution-code view to use a 5 min cache header

---

bedrock/foundation/templates/foundation/moco.html

Missed a spot. 
Also updating bio links for Mitchell and Chris.
https://bugzilla.mozilla.org/show_bug.cgi?id=1335248

[fix bug 1335248] Remove Hoffman from MoCo board

---

media/css/pebbles/includes/_animations.scss
media/css/sandstone/animations.less
media/css/sandstone/lib.less
media/css/sandstone/oldIE.less
media/css/sandstone/sandstone-resp.less
media/css/sandstone/sandstone.less

Fix CSS linting errors for Sandstone and Pebble libraries, as laid out in the bug report.
https://bugzilla.mozilla.org/show_bug.cgi?id=1332675
There are now no error messages when the following commands are run:
```bash
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/pebbles/**/*.scss"
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/sandstone/**/*.less"
```

[fix bug 1332675] Fix CSS linting errors in Sandstone and Pebbles

---

media/css/styleguide/identity-firefox.less
media/css/styleguide/identity-firefoxos.less
media/css/styleguide/identity-marketplace.less
media/css/styleguide/identity-mozilla.less
media/css/styleguide/identity-persona.less
media/css/styleguide/identity-webmaker.less
media/css/styleguide/products-firefox-os.less
media/css/styleguide/styleguide-lib.less
media/css/styleguide/styleguide.less

Fix CSS linting errors for the styleguide, as laid out in the bug report.
https://bugzilla.mozilla.org/show_bug.cgi?id=1332677
There are now no error messages when the following command is run:
```bash
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/styleguide/**/*.less"
```

[fix bug 1332677] Fix CSS linting errors for styleguide

---

media/css/csrf-failure.less

Fix CSS linting errors for the CSRF failure page, as laid out in the bug report.
https://bugzilla.mozilla.org/show_bug.cgi?id=1332663
There are now no error messages when the following command is run:
```bash
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/csrf-failure.less"
```

[fix bug 1332663] Fix CSS linting errors for CSRF failure page

---

media/css/mozorg/mpl-1-1-annotated.scss
media/css/mozorg/mpl-differences.scss

- Fixed
Fix the CSS linting errors for the MPL and namespace pages.
[#1332650](https://bugzilla.mozilla.org/show_bug.cgi?id=1332650)
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/mozorg/mpl-1-1-annotated.scss"
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/mozorg/mpl-differences.scss"
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/mozorg/namespaces.scss"

[bug 1332650][CSS linting] MPL and namespace pages

---

bedrock/firefox/firefox_details.py
bedrock/firefox/templates/firefox/dnt.html
bedrock/firefox/templates/firefox/new/base.html
bedrock/firefox/templates/firefox/new/onboarding/scene1.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/thunderbird/details.py
bedrock/thunderbird/templates/thunderbird/features.html

Rename 'OS X' to 'macOS' on various appropriate user facing components, like on download page.
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1330000

Bug 1330000 - Rename 'OS X' to 'macOS' on download pages / buttons

---

media/css/base/menu-resp.less
media/css/base/menu.less
media/css/base/mozilla-accordion.less
media/css/base/mozilla-modal.less
media/css/base/mozilla-video-poster.less
media/css/base/send-to-device-micro.less
media/css/base/send-to-device.less
media/css/base/simple_footer.less

Fix CSS linting errors for media/css/base/*.less, as laid out in the bug report.
https://bugzilla.mozilla.org/show_bug.cgi?id=1332665
There are now no error messages when the following command is run:
```bash
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/base/**/*.less"
```

[fix bug 1332665] Fix CSS linting errors for media/css/base/

---

media/css/firefox/firstrun/new-firstrun.less

@craigcook 
The FxA iFrame has not been tested at sizes smaller than 318px.
https://bugzilla.mozilla.org/show_bug.cgi?id=1337451

[fix bug 1337451] - resize fxa iframe on new /firstrun to a width that has been tested

---

media/js/base/global.js
media/js/base/mozilla-fxa-iframe.js
tests/unit/spec/base/mozilla-fxa-iframe.js

#4579 [introduced a regression](https://github.com/mozilla/bedrock/pull/4579/files#diff-dc9018ca2e4502c42779505aa8eeaea4L181) whereby users logging in to the FxA iframe stopped being redirected to the FxA settings page. This resulted in a significant uptick in errors on the FxA side (which is how the bug was discovered), as well as poor UX (the user saw a "Working..." error message in the iframe that never went away).
This PR fixes that regression, and adds tests.
https://bugzilla.mozilla.org/show_bug.cgi?id=1337448
On demo3, using a profile configured to work with the FxA staging server, log in to Sync on the current firstrun page [1]. You should be redirected to the FxA accounts settings URL.
Also on demo3, using the same profile as above, log in to Sync on the soon to be released …

[fix bug 1337448] FxA redirect after login.

---

bedrock/firefox/firefox_details.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py
bedrock/settings/base.py

* Fix bug 1331667: Use the "aurora-latest-l10n-ssl" product
* Fix bug 937865: Use bouncer "latest" products for all buttons

Fix bug 1324579: Use new nightly and aurora "latest" bouncer products

---

bedrock/firefox/templatetags/helpers.py
bedrock/firefox/tests/test_helpers.py
bedrock/thunderbird/details.py
bedrock/thunderbird/templatetags/helpers.py
bedrock/thunderbird/tests/test_helpers.py

Remove the unnecessary, obsolete fallback code so download links are always localized.

Fix Bug 1338394 - Firefox/Thunderbird channel & download pages serve en-US builds on localized pages for mac users

---

bedrock/newsletter/templates/newsletter/index.html

Currently, the sign-up invitation text misleadingly refers to Firefox tips and tricks, when the newsletter is only delivering Mozilla news.
https://bugzilla.mozilla.org/show_bug.cgi?id=1337123

Fix bug 1337123: Update newsletter sign-up language to avoid confusion

---

docs/l10n.rst

Mostly nits, plus:
* Add note about using underscores for l10n_has_tag
* Remove l10n_merge (I’ve never seen such a command, and can’t find
references in the code)

[no bug] Improve l10n documentation

---

docs/mozilla-traffic-cop.rst
media/js/base/mozilla-traffic-cop.js
tests/unit/spec/base/mozilla-traffic-cop.js

MDN is *probably* going to use Traffic Cop for an upcoming test, and will need the ability to have longer lasting cookies. This is in preparation for that use-case.
Nope.
Make sure tests pass? Could also create a local example and ensure cookie remains after closing the tab.

Allow user to optionally specify duration of Traffic Cop cookie.

---

media/css/mozorg/internet-health.scss
media/css/mozorg/internet-health/privacy-security.scss
media/css/mozorg/technology.scss

Updated site footer for pages /technology, /internet-health, /internet-health/privacy-security
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1332248

Bug 1332248: Site footer needs updating to the new wordmark (for pages /technology, /internet-health, /internet-health/privacy-security)

---

bedrock/firefox/firefox_details.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/settings/base.py

- Updates bedrock's logic for including funnelcake query params in download links, so it now only happens for Windows and en-US. This avoids scenarios where the download could 404 for other platforms, should anyone come across a link like below:
https://www.mozilla.org/en-US/firefox/new/?f=99
https://bugzilla.mozilla.org/show_bug.cgi?id=1340087
- I added some unit tests, but this could still use some careful review.
- Demo URL: https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?f=99

[fix bug 1340087] Update funnelcake logic to include IDs for windows only

---

bedrock/firefox/firefox_details.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py

Bug 1339870 will fix it such that we can simply use e.g.  firefox-aurora-stub for all locales like we can for beta and release. So we'll be able to remove our special handling of nightly and aurora. Until then we have to only serve stub to en-US windows users.

Bug 1339870: Only offer stub for en-US aurora and nightly

---

bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py

Removes framing exemption from /firefox/new/ which was added in bug 1004598.

Bug 1341547: Deny framing of /firefox/new/

---

bedrock/base/templates/macros.html

made the "Private Browsing"  link in Firefox navigation to point to /firefox/private-browsing/
https://bugzilla.mozilla.org/show_bug.cgi?id=1341005

Fix Bug 1341005 - "Private Browsing" link in Firefox navigation should point to /firefox/private-browsing/

---

media/js/mozorg/contribute/contribute-landing.js

Pause video playback when a user closes the modal on the /contribute page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1341242

fix Bug 1341242 - Video on /contribute does not stop playing when closing modal

---

bin/tag-release.sh

This pushes the commit you just tagged to the prod branch, not just master. I needed to push master~1 to prod first, since the HEAD of master contains a migration. This will allow me to do this kind of thing with the normal `tag-release.sh` script.

Push HEAD to prod when tagging release.

---

media/css/sandstone/sandstone-resp.less

Adjusted the height of the mail input box of the /about/governance/ page to align properly with the sign up button.
https://bugzilla.mozilla.org/show_bug.cgi?id=1336524

Fix Bug 1336524 - The sign up button should be aligned properly with the mail input box - governance page

---

bedrock/mozorg/templates/mozorg/about/forums/forums.html

- Removes out of date mozilla-labs forum links to dead projects.
https://bugzilla.mozilla.org/show_bug.cgi?id=1340599

[fix bug 1340599] Remove hard-coded mozilla-labs forum links

---

bedrock/mozorg/templates/mozorg/internet-health.html

Fixes my stupidity when I replaced the wrong block of text.
https://bugzilla.mozilla.org/show_bug.cgi?id=1335569
Verify the "Open Innovation" section appears as it used to and that the "Digital Inclusion" section has a "Learn more" link to the new DI page.

[bug 1335569] Fix IH landing page for digital inclusion

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html

Removes Chris Hofmann from l10n-voucher list on access-policy page
https://bugzilla.mozilla.org/show_bug.cgi?id=1343648
None, admittedly (sorry!)

Fixes bug 1343648; removes chofmann from l10n-voucher section.

---

bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html

Currently there's an English string exposed in production, since the page was localized.

Bug 1335569 - Revert unwanted string change in IH privacy-security

---

media/css/firefox/all.less

- We're currently showing `Windows (XP/Vista)` sha-1 download links on `/firefox/organizations/all` by default, along side regular bouncer links. This has happened because there are now two ESR releases.
- This PR updates the CSS to hide the sha-1 links by default, showing them only to users who need it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1345416
- By default only regular bouncer links should be shown.
- Setting a class of `windows sha-1` on the HTML element should toggle showing the sha-1 bouncer links.

[fix bug 1345416] Hide sha-1 download links by default on /organizations/all/

---

bedrock/firefox/templates/firefox/includes/download-list.html
bedrock/firefox/templates/firefox/new/base.html
bedrock/firefox/templates/firefox/new/onboarding/base.html
bedrock/firefox/templates/firefox/new/onboarding/scene1.html
bedrock/firefox/templates/firefox/new/scene1.html

- Moves the link to `/all` from the footer to inside modal on `/firefox/new/` (footer links are due to be removed in [Bug 1342235](https://bugzilla.mozilla.org/show_bug.cgi?id=1342235))
- This doesn't fix the discover-ability problem for other pages once the footer links are removed, but it should fix things for this most critical page. Arguably the links in the footer we're way too hard to find anyway.
- This PR uses existing strings in `main.lang` and `download_button.lang`, so it shouldn't require any l10n conditional tags.
https://bugzilla.mozilla.org/show_bug.cgi?id=1344240

[fix bug 1344240] Move /all link from page footer to inside modal on /firefox/new/

---

jenkins/utils.groovy

We're seeing random failures, and this would help prevent having to run the full deployment again.

Add one retry to integration test runs

---

.stylelintrc
lockdown.json
package.json

Updates our versions of these libraries, prompted by running into errors when the older versions tried to parse newfangled grid properties.
Verify it doesn't break anything. I ran gulp-stylelint on the entire /css folder and it turned up no new errors. I ran collectstatic and found no Sass parsing errors. Pages are rendering as they should.

[no bug] Update node-sass to 4.5 and gulp-stylelint to 3.9

---

requirements/linkchecker.txt

I noticed our linkchecker job wasn't running correctly, hopefully this should fix it: https://ci.us-west.moz.works/job/bedrock_linkchecker_prod_eu_west/852/console

Add requests v2.13.0 to linkchecker.txt requirements

---

docker/bin/run_linkchecker.sh
requirements/linkchecker.txt

Turns out LinkChecker checks for a good version of python-requests in a dumb way, so it sees version "2.13.0" as being lower than "2.2.0". Also the project seems to have been abandoned, so there isn't a newer release, though it seems this issue has been fixed in the master branch.
Easiest fix is to just downgrade requests to the latest version that is < 2.10.0, which is what I've done.

Downgrade Requests to fix LinkChecker

---

bedrock/settings/base.py

Not sure why we weren't doing this before. Bedrock lends itself perfectly to etags and our CDN provider is ready for their use:
https://support.cloudflare.com/hc/en-us/articles/218505467-Does-CloudFlare-support-ETag-headers-
Django docs for the feature enabled:
https://docs.djangoproject.com/en/1.8/ref/middleware/#module-django.middleware.common

Fix bug 1347663: Add etag headers to responses

---

bedrock/security/tests/test_views.py
bedrock/security/views.py

They were causing a miss-match in HTML and static file cache.  I will be investigating ways in which we can more efficiently use our CDN caches.

Fix bug 1344381: Disable last-modified headers from security pages

---

bedrock/newsletter/tests/test_forms.py
bedrock/newsletter/utils.py

We need to allow 5 char locales (e.g. zh-TW) to post to basket.

Fix bug 1082122: Allow 5 char locales for newsletters

---

bedrock/firefox/firefox_details.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/mozorg/tests/test_views.py
bedrock/settings/base.py

All locales for beta and release, and en-US only for aurora and nightly.

Bug 1344220: Enable stub installer for win64

---

bedrock/firefox/tests/test_firefox_details.py
bedrock/settings/base.py

Stub installer for win64 is scheduled to ride the Fx 55 train, we should not enable it for more channels (aurora, beta, release) until we're told that smart switching has been enabled in the stub.

Fix bug 1348610: Win64 stub installer only for Nightly

---

bedrock/mozorg/templates/mozorg/home/home.html
media/css/mozorg/home/home.scss
media/js/mozorg/home/home.js

- Adds link to /firefox/android/all/ to homepage Firefox CTA
https://bugzilla.mozilla.org/show_bug.cgi?id=1349760

[fix bug 1349760] Add link to /firefox/android/all to homepage

---

bedrock/mozorg/templates/mozorg/developer/css-grid-demo.html
media/css/mozorg/developer/css-grid-demo.scss

The code example shown wasn't accurate to the actual code that rendered the demo. This fixes that mismatch.
https://bugzilla.mozilla.org/show_bug.cgi?id=1349284
Assure the code example for display matches the actual CSS. We can double-check all the examples but I think this was the only one.

[fix bug 1349284] Show correct CSS for grid example

---

bedrock/mozorg/templatetags/misc.py
bedrock/releasenotes/tests/test_base.py

This is a redirect bug affecting Thunderbird Beta users. [/thunderbird/51.0/releasenotes/](https://www.mozilla.org/thunderbird/51.0/releasenotes/), for example, should be redirected to [/thunderbird/51.0beta/releasenotes/](https://www.mozilla.org/thunderbird/51.0beta/releasenotes/) instead of [/firefox/51.0beta/releasenotes/](https://www.mozilla.org/firefox/51.0beta/releasenotes/).
[/thunderbird/52.0/releasenotes/](https://www.mozilla.org/thunderbird/52.0/releasenotes/) -> [/thunderbird/52.0beta/releasenotes/](https://www.mozilla.org/thunderbird/52.0beta/releasenotes/) and so on.
[Bug 1329514](https://bugzilla.mozilla.org/show_bug.cgi?id=1329514)
Load the URL above (or any other version) to make sure you'll be taken to the Thunderbird Beta release notes. Note that past major releases like …

Fix Bug 1329514 - Thunderbird beta: Help | About | 'release notes' brings up *Firefox* beta page

---

bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html

John Whitlock was mistakenly attributed.

Fix misattributed bug bounty

---

bedrock/firefox/templates/firefox/android/index.html
bedrock/firefox/templates/firefox/channel/android.html
bedrock/firefox/templates/firefox/channel/base.html
bedrock/firefox/templates/firefox/channel/desktop.html
bedrock/firefox/templates/firefox/channel/ios.html
bedrock/firefox/templates/firefox/desktop/index.html
bedrock/firefox/templates/firefox/family/index.html
bedrock/firefox/templates/firefox/ios.html
bedrock/firefox/templates/firefox/private-browsing.html
bedrock/firefox/templates/firefox/sync.html

Updating the following pages with [these](https://docs.google.com/spreadsheets/d/1kFpqkkssd-keOyVS13azQS_iJ8ESNtvqjZ5TLy5hBq0/edit#gid=0) meta-decriptions and titles:
- https://www.mozilla.org/en-US/firefox/products/
- https://www.mozilla.org/en-US/firefox/desktop/
- https://www.mozilla.org/en-US/firefox/ios/
- https://www.mozilla.org/en-US/firefox/private-browsing/
- https://www.mozilla.org/en-US/firefox/sync/
- https://www.mozilla.org/en-US/firefox/releases/
- https://www.mozilla.org/en-US/firefox/android/
https://bugzilla.mozilla.org/show_bug.cgi?id=1345338#c12
Ensure various meta titles and descriptions are updated as denoted [here](https://docs.google.com/spreadsheets/d/1kFpqkkssd-keOyVS13azQS_iJ8ESNtvqjZ5TLy5hBq0/edit#gid=0).

fix bug 1345338 Update titles+metadata on mozilla.org/firefox/*

---

bedrock/base/templates/base-pebbles.html
bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
bedrock/base/templates/includes/optimizely.html
bedrock/settings/static_media.py
media/js/base/gtm-snippet.js
media/js/base/optimizely-snippet.js

Wraps Optimizely script in a DNT check. Essentially mirrors method used for GTM.
https://bugzilla.mozilla.org/show_bug.cgi?id=1218626
Ensure Optimizely loads when DNT is disabled, and does not load with DNT enabled.

[fix bug 1218626] Wrap Optimizely script in DNT check.

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2016.html
bedrock/mozorg/urls.py
media/css/mozorg/about-transparency.less

Adds a transparency report for July-December 2016 and moves the previous one to "past reports." No l10n required.
https://bugzilla.mozilla.org/show_bug.cgi?id=1336573
https://bedrock-demo-craigcook.us-west.moz.works/en-US/about/policy/transparency/jul-dec-2016/

[fix bug 1336573] Jul-Dec 2016 transparency report

---

bedrock/foundation/templates/foundation/advocacy.html

Just adding missing spaces around “—”, before we start translating this page.
N/A

Missing spaces around “—” in /foundation/advocacy/

---

media/js/firefox/new/scene2.js
tests/pages/firefox/new/thank_you.py

- Changes functional test for download page to use a custom class when DOM is ready, rather than wait for the window load event.
https://bugzilla.mozilla.org/show_bug.cgi?id=1354334
- I ran this branch against the full test suite and it passed: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/21/pipeline

[fix bug 1354334] Fix timing for download thank-you page functional test

---

bedrock/firefox/templates/firefox/channel/ios.html

Currently falling back to a description, which doesn't make sense.

Bug 1345338 follow-up: update fallback title in firefox/channel iOS page

---

bedrock/firefox/templates/firefox/accounts.html
bedrock/firefox/templates/firefox/android/index.html
bedrock/firefox/templates/firefox/australis/fx38_0_5/firstrun.html
bedrock/firefox/templates/firefox/desktop/desktop-base.html
bedrock/firefox/templates/firefox/desktop/index.html
bedrock/firefox/templates/firefox/installer-help.html
bedrock/firefox/templates/firefox/mobile-download-desktop.html
bedrock/firefox/templates/firefox/releases/release-notes.html
bedrock/firefox/templates/firefox/sync.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-50.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-base-42.html
bedrock/mozorg/templates/mozorg/about.html
bedrock/mozorg/templates/mozorg/contribute/signup.html
bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/templates/mozorg/mission.html
bedrock/mozorg/templates/mozorg/plugincheck.html
bedrock/newsletter/templates/newsletter/developer.html
bedrock/newsletter/templates/newsletter/firefox.html
bedrock/newsletter/templates/newsletter/mozilla.html
bedrock/teach/templates/teach/smarton/tracking.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1355458
(We should clean up these switches afterward too)

[fix bug 1355458] Remove Optimizely from all pages except /new and /firstrun

---

bedrock/base/templates/base-pebbles.html
bedrock/firefox/templates/firefox/base-pebbles.html
bedrock/firefox/urls.py
media/css/mozorg/home/home.scss
media/css/mozorg/internet-health.scss
media/css/mozorg/internet-health/health-subpage.scss
media/css/mozorg/technology.scss
media/css/pebbles/components/_masthead.scss

@jpetto @craigcook - it occurred to me that we don't yet have a base template in the Firefox app that uses pebbles. I think it might be a good idea to create a common base template which all the new hub pages can inherit from. This gives us the following things:
- All pages have the correct Favicon / social meta data.
- For non-en locales, we'll likely have to fix up some sort of minimal header since they don't get the new global nav. For now I've just updated the default header in `./base-pebbles.html` to use the new logo. This did mean some slight refactoring of the existing header CSS on other pages, as there are so many versions of the same `#masthead` CSS :/
Thoughts?
Testing:
--------
- New base template for en-US should get the global nav, other locales the old nav (but with new …

Add pebbles base template for /firefox app

---

docs/install.rst

The command for securely upgrading pip in the current documentation:
`$ bin/pipstrap.py`
is outdated because the script it uses has been taken out.  It therefore results in  the error message:
`-bash: bin/pipstrap.py: No such file or directory`
The documentation needs to be changed to reflect that this script has been removed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1356059

[fix bug 1356059] update the 'securely upgrade pip' command

---

media/js/privacy/privacy.js

- Temporarily hides the download button in global nav on the /privacy pages to help facilitate a funnelcake experiment.
https://bugzilla.mozilla.org/show_bug.cgi?id=1354304
- Button should not be visible in Firefox, but still visible to other browsers.

[fix bug 1354304] Hide download button on /privacy/firefox page for funnelcake experiment

---

bedrock/firefox/templates/firefox/firstrun/firstrun-horizon.html

- Updates headline on `/firstrun` page to make it clearer that creating an account is not required.
https://bugzilla.mozilla.org/show_bug.cgi?id=1347187

[fix bug 1347187] Update headline on firstrun page

---

bedrock/firefox/templates/firefox/android/index.html
bedrock/firefox/templates/firefox/channel/android.html
bedrock/firefox/templates/firefox/channel/base.html
bedrock/firefox/templates/firefox/channel/desktop.html
bedrock/firefox/templates/firefox/channel/ios.html
bedrock/firefox/templates/firefox/desktop/index.html
bedrock/firefox/templates/firefox/family/index.html
bedrock/firefox/templates/firefox/ios.html
bedrock/firefox/templates/firefox/private-browsing.html
bedrock/firefox/templates/firefox/sync.html

A follow up to bug 1345338 where we were to set new meta titles and descriptions. Turns out there were left over prefix and suffixes still existing on many of these page titles. This bug removes those.
[Previous Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1345338)
[Previous PR](https://github.com/mozilla/bedrock/pull/4736)
[Titles and pages](https://docs.google.com/spreadsheets/d/1kFpqkkssd-keOyVS13azQS_iJ8ESNtvqjZ5TLy5hBq0/edit#gid=0)
[Current Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1355173)
@jpetto r?

Fix Bug 1355173 - Get rid of title prefix/suffix on certain Firefox pages (SEO)

---

media/css/pebbles/global.scss

Don’t load the fonts everywhere until we’re sure we need them everywhere.
https://bugzilla.mozilla.org/show_bug.cgi?id=1355512

[bug 1355512] remove Zilla from pebbles global

---

bedrock/firefox/templates/firefox/new/base.html
bedrock/firefox/templates/firefox/new/break-free/scene1.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/way-of-the-fox/scene1.html

Experiments need to be run on two variants of `/firefox/new/`.
Also, confirmed with cmore that Optimizely only needs to be on scene 1, and only for en-US audiences (for the time being, anyway).
https://bugzilla.mozilla.org/show_bug.cgi?id=1349729#c21
Make sure Optimizely loads as expected, and no typos or anything.

[fix bug 1349729] Add Optimizely snippet to /firefox/new/ variations.

---

bedrock/settings/base.py
media/js/base/stat-counter.js

- Fixes CSP error for when script is loaded securely: https://www.mozilla.org/en-US/firefox/52.0/firstrun/

[bug 1352821] Fix StatCounter CSP script error

---

bedrock/firefox/templates/firefox/firstrun/firstrun-horizon.html
bedrock/firefox/templates/firefox/firstrun/new-firstrun.html

- Pass along funnelcake ID's along in the utm_source to the /firstrun FxA iframe.
https://bugzilla.mozilla.org/show_bug.cgi?id=1354710
- If page contains funnelcake query param e.g. `?f=110`, then `utm_source` should equal `firstrun_f110`.
- If pages does not have funnelcake query param, `utm_source` should just be `firstrun`.

[fix bug 1354710] Firstrun pages need to pass funnelcake parameters to FxA

---

bedrock/firefox/firefox_details.py
bedrock/firefox/templates/firefox/new/break-free/scene1.html
bedrock/firefox/templates/firefox/new/onboarding/scene1.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/way-of-the-fox/scene1.html
bedrock/firefox/templatetags/helpers.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py

Add option to download_firefox helper to include the locale in the URL for the scene2 page.

Fix bug 1290962: Include locale in Fx download scene2 URL

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-50.html

Updates lang files for `whatsnew-50.html` (as per @flodolo's request).

[fix bug 1355333] Update lang files for /whatsnew 50.

---

bedrock/firefox/templates/firefox/new/scene2.html

New experiment needs to target `?scene=2`. This PR just adds the Optimizely snippet to that template (for `en-US` only).
https://bugzilla.mozilla.org/show_bug.cgi?id=1356017

[fix bug 1356017] Add Optimizely snippet to ?scene=2.

---

bedrock/firefox/templates/firefox/new/break-free/scene2.html
bedrock/firefox/templates/firefox/new/onboarding/scene2.html
bedrock/firefox/templates/firefox/new/scene2.html
bedrock/firefox/templates/firefox/new/way-of-the-fox/scene2.html

Politely asks search engines not to index /firefox/new/?scene=2
https://bugzilla.mozilla.org/show_bug.cgi?id=1357173

[fix bug 1357173] Add noindex to scene 2 of download page

---

bedrock/firefox/templates/firefox/channel/desktop.html

Simply add a link to the new [Firefox Nightly Release Notes](https://www.mozilla.org/firefox/nightly/notes/) to the [desktop channel page](https://www.mozilla.org/firefox/channel/desktop/). The *Release Notes* string is already used for Beta and Developer Edition, so no l10n changes required here.
[Bug 1359609](https://bugzilla.mozilla.org/show_bug.cgi?id=1359609)
Visit the desktop channel page and make sure the Release Notes link is displayed under Nightly.

Fix Bug 1359609 - Add Nightly release notes link to desktop channel page

---

bedrock/base/templates/base-pebbles.html
bedrock/base/templates/base-resp.html
bedrock/base/templates/includes/global-nav.html
bedrock/foundation/templates/foundation/base-resp.html
bedrock/mozorg/templates/mozorg/about-base.html
bedrock/mozorg/templates/mozorg/about.html
bedrock/mozorg/templates/mozorg/about/history.html
bedrock/mozorg/templates/mozorg/about/leadership.html
bedrock/mozorg/templates/mozorg/about/manifesto.html
bedrock/mozorg/templates/mozorg/contact/contact-base.html
bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
bedrock/mozorg/templates/mozorg/internet-health.html
bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
bedrock/mozorg/templates/mozorg/mission.html
bedrock/mozorg/templates/mozorg/technology.html
media/css/base/global-nav.less
media/css/pebbles/components/_global-nav.scss
media/js/base/mozilla-global-nav.js

- Nav open state now locks scrolling the page (desktop viewport only).
- Close button in the drawer menu now animates (desktop viewport only).
- Improves a11y support for nav using WAI-ARIA roles.
- Deprecate custom GA events in favor of dynamic data-attributes (already tested on a demo with Peter).
- Updated styling for nav download button.
- Small style tweaks to main nav for mobile viewports.
- Pages under each top-level section are now highlighted on page load.
https://bugzilla.mozilla.org/show_bug.cgi?id=1353587
- Demo: https://www-demo5.allizom.org/en-US/
- Test both pebbles and sandstone pages for any CSS regressions.
- Test wide desktop (locked nav) and smaller screens (regular page scrolling).

[fix bug 1353587] Global nav incremental improvements

---

bedrock/firefox/templates/firefox/base-pebbles.html

- Add global nav default highlight attribute
- Use correct Twitter / Facebook accounts in meta data
- Remove superfluous /firefox/new lang file

Update Firefox base template for new hub pages

---

bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/js/firefox/new/experiment-funnelcakes-110-113.js

Adds experiment for funnelcakes 110 - 113 to `/firefox/new` for en-US, Windows, desktop, non-Firefox users.
Must add following funnelcake config to env:
```
FUNNELCAKE_110_PLATFORMS=win
FUNNELCAKE_110_LOCALES=en-US
FUNNELCAKE_111_PLATFORMS=win
FUNNELCAKE_111_LOCALES=en-US
FUNNELCAKE_112_PLATFORMS=win
FUNNELCAKE_112_LOCALES=en-US
FUNNELCAKE_113_PLATFORMS=win
FUNNELCAKE_113_LOCALES=en-US
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1348129
Visit `/en-US/firefox/new/` on Windows (or with `windows` hard-coded in `window.site.getPlatform()`) in a browser with DNT disabled. Should get one of 4 variations 28% of the time.
(Funnelcakes are not yet active.)
https://bedrock-demo-jpetto-fc.us-west.moz.works/en-US/firefox/new/

[fix bug 1348129] Experiment for funnelcakes 110-113.

---

bedrock/settings/base.py

Starting April 19th we've seen a massive increase in API calls with the old key. I'd like to rotate the key, to see if someone else is using the old key and possibly restrict its usage.

Update Mozilla Location Service API key

---

bedrock/firefox/templates/firefox/firstrun/new-firstrun.html
bedrock/firefox/views.py

Follow-up to #4778. More requirements came in to:
1. Show standard/canonical `/firefox/new/` scenes 1 & 2 for funnelcake 110
2. Use `new-firstrun.html` for funnelcakes 111, 112, & 113
3. Add updated `utm_source` logic to `new-firstrun.html` template
https://bugzilla.mozilla.org/show_bug.cgi?id=1360462
https://bugzilla.mozilla.org/show_bug.cgi?id=1360397
- Ensure `/firefox/new/?f=110` shows the standard/canonical template.
- Ensure `/firefox/new/?f=[111-113]` shows the `onboarding/scene[1-2].html` template.
- Ensure `/firefox/53.0/firstrun/?f=110` shows the standard/canonical template
- Ensure `/firefox/53.0/firstrun/?f=[111-113]` shows the `new-firstrun.html` template.
https://bedrock-demo-jpetto-fc.us-west.moz.works/en-US/firefox/new/?f=110 …

[fix bug 1360462] Update funnelcake download & firstrun views for 110-113

---

bedrock/redirects/redirects.py
tests/redirects/map_htaccess.py

Django handles this properly now. We no longer need this.
See bug 1300373 for more details.

Fix bug 1300373: Remove redirect handler for trailing slashes

---

media/js/firefox/new/experiment-funnelcakes-110-113.js

Reduces audience size initially to be careful testing funnelcakes. Will increase audience size as soon as funnelcakes are considered safe.
https://bugzilla.mozilla.org/show_bug.cgi?id=1348129#c44

[fix bug 1348129] Adjust funnelcake experiment audience size

---

bedrock/firefox/templates/firefox/firstrun/new-firstrun.html

Removes custom `entrypoint` param behavior on FxA iframe.
https://bugzilla.mozilla.org/show_bug.cgi?id=1361175
Make sure `entrypoint` params matches FxA implementations on other pages.

[fix bug 1361175] Remove custom entrypoint param from firstrun template

---

bedrock/redirects/redirects.py
bedrock/redirects/util.py
tests/redirects/map_htaccess.py

Manually prevent the redirect helper function from returning protocol relative URLs (e.g. //google.com/) as this could allow unexpected redirection to other domains and we never need to redirect to an unknown protocol.
Also add shortcuts that skip Django's `reverse` function when the input is obviously a URL.

Fix bug 1300373: redirect helper never return protocol relative URLs

---

bedrock/firefox/templates/firefox/nightly_firstrun.html

On the [Nightly firstrun page](https://www.mozilla.org/en-US/firefox/nightly/firstrun/):
* Replace One and Done, which is no longer available, with Get Involved with QA
* Remove Nightly user badge, which is also no longer available
The One and Done link has been exposed as a localizable string, but no locale has customized the URL so far. Given that, l10n shouldn't be a blocker here. Cc @flodolo for the string updates.
[Bug 1350305](https://bugzilla.mozilla.org/show_bug.cgi?id=1350305)
Just visit the firstrun page to see the links are updated/removed.

Fix Bug 1350305 - Replace One and Done, remove badge link on Nightly firstrun page

---

media/js/firefox/new/experiment-funnelcakes-110-113.js

Funnelcakes look good at 1% per variation - increasing to 7% per.
https://bugzilla.mozilla.org/show_bug.cgi?id=1348129#c47

[fix bug 1348129] Increase experiment audience size.

---

bedrock/firefox/templates/firefox/releases/release-notes.html
media/css/firefox/releasenotes-firefox.less

Show the relevant bug ID on each note entry to make Nightly release notes more informative. Currently bug IDs are displayed only when manually added to the description, but there's actually the bug ID field for each note, so let's use it.
[Bug 1360034](https://bugzilla.mozilla.org/show_bug.cgi?id=1360034)
* Open the Nightly release notes at `/firefox/nightly/notes/` to see a bug ID reference on each note, like [this screenshot](https://bug1360034.bmoattachments.org/attachment.cgi?id=8862500).
* Open non-Nightly release notes e.g. `/firefox/notes/` or `/firefox/beta/notes/` to make sure bug IDs are not displayed.

Fix Bug 1360034 - Show bug ID field in Nightly release notes

---

bedrock/firefox/templates/firefox/releases/aurora-notes.html
bedrock/firefox/templates/firefox/releases/beta-notes.html
bedrock/firefox/templates/firefox/releases/release-notes.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1333294

[fix bug 1333294] Remove links to iOS release notes

---

media/css/firefox/nightly_firstrun.less

Remove an unnecessary scrollbar due to `overflow-x: hidden` on both `<html>` and `<body>`.
[Bug 1355072](https://bugzilla.mozilla.org/show_bug.cgi?id=1355072)
Open the Nightly firstrun page at `/firefox/nightly/firstrun/`, resize the window, and make sure there is only one vertical scrollbar.

Fix Bug 1355072 - [nightly] First run page, has 2 vertical scrollbars if you change the window size.

---

bedrock/firefox/templates/firefox/all.html
media/css/firefox/all.less

Fix the mobile menu on [/firefox/nightly/all/](https://www.mozilla.org/en-US/firefox/nightly/all/) unreadable due to white text on white background. This PR also fixes the height of the header Nightly logo in the mobile viewport.
[Bug 1349339](https://bugzilla.mozilla.org/show_bug.cgi?id=1349339)
Visit `/firefox/nightly/all/`, resize the window, and make sure the drop down menu items are readable.

Fix Bug 1349339 - Mobile menu on /nightly/all is unreadable

---

media/css/firefox/features/common.scss

https://bugzilla.mozilla.org/show_bug.cgi?id=1363239

[fix bug 1363239] Header CSS height differences on new /firefox/features/ page

---

bedrock/firefox/templates/firefox/new/break-free/base.html
bedrock/firefox/templates/firefox/new/break-free/scene2.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/base.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/browse-up-to-you/scene2.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/conformity-not-default/scene2.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/private-not-option/scene2.html
bedrock/firefox/templates/firefox/new/onboarding/base.html
bedrock/firefox/templates/firefox/new/onboarding/scene2.html
bedrock/firefox/templates/firefox/new/way-of-the-fox/base.html
bedrock/firefox/templates/firefox/new/way-of-the-fox/scene2.html

Adds `<meta name="robots" content="noindex,follow">` to all `/new` variations, both scene's 1 & 2.
https://bugzilla.mozilla.org/show_bug.cgi?id=1359878
Make sure my haste isn't making waste.

[fix bug 1359878] Add noindex to /new variation templates

---

bedrock/settings/static_media.py
media/css/firefox/new/fx-lifestyle/base.less

Fixes a CSS bundle name copy pasta bug in original PR, and adjusts bottom padding.
https://bugzilla.mozilla.org/show_bug.cgi?id=1363554

[fix bug 1363554] Fix /new variation UI issues.

---

bedrock/firefox/templates/firefox/base-pebbles.html
bedrock/firefox/templates/firefox/features/base.html
bedrock/firefox/templates/firefox/features/fast.html
bedrock/firefox/templates/firefox/features/independent.html
bedrock/firefox/templates/firefox/features/index.html
bedrock/firefox/templates/firefox/features/private-browsing.html
bedrock/firefox/templates/firefox/products/android.html
bedrock/firefox/templates/firefox/products/desktop.html
bedrock/firefox/templates/firefox/products/ios.html

Updates Firefox hub page titles as per the original spec.
https://bugzilla.mozilla.org/show_bug.cgi?id=1363411
Titles should match this doc https://docs.google.com/spreadsheets/d/1Xx5HxJhV3L304g67e3757uNWeuGqS6wu8eg-H93umdw/edit?ts=58fed2cd#gid=0

[fix bug 1363411] Update Firefox hub page titles

---

bedrock/firefox/templates/firefox/includes/release-menu.html

* Add a channel page link to the top menu on release notes.
* Remove Developer Edition link from Android/iOS notes.
Release notes are not localized, so no l10n changes required.
[Bug 1359091](https://bugzilla.mozilla.org/show_bug.cgi?id=1359091)
Visit release notes and make sure there is a channel link based on the platform. The label says **Firefox Beta** on the iOS notes, **Firefox Nightly & Beta** otherwise.

Fix Bug 1359091 - Release notes top menu should have a link to the pre-release channel page

---

bedrock/firefox/templates/firefox/new/fx-lifestyle/more-protection/scene1.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/more-protection/scene2.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/working-out/scene1.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/working-out/scene2.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/you-do-you/scene1.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/you-do-you/scene2.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/firefox/new/fx-lifestyle/base.less
media/css/firefox/new/fx-lifestyle/browse-up-to-you.less
media/css/firefox/new/fx-lifestyle/conformity-not-default.less
media/css/firefox/new/fx-lifestyle/more-protection.less
media/css/firefox/new/fx-lifestyle/private-not-option.less
media/css/firefox/new/fx-lifestyle/working-out.less

- Three new variations for ad campaigns, based on previous templates.
https://bugzilla.mozilla.org/show_bug.cgi?id=1363543
- Copy pasta errors are likely the biggest error prone thing here
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?xv=moreprotection
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?xv=workingout
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?xv=youdoyou

[fix bug 1363543] /new variations to support ad campaigns - private, general, competitor

---

bedrock/firefox/templates/firefox/releases/aurora-notes.html
bedrock/firefox/templates/firefox/releases/beta-notes.html
bedrock/firefox/templates/firefox/releases/release-notes.html
media/css/firefox/releasenotes-firefox.less

Under the Other Releases drop down menu:
* Replace Desktop **Latest Beta** link with **Latest Beta & Developer Edition**
* Add Desktop **Latest Nightly** link
* Remove Android **Latest Aurora** link
Plus redundant code clean-up.
[Bug 1358198](https://bugzilla.mozilla.org/show_bug.cgi?id=1358198)
Open any release notes page, and make sure the Other Releases drop down menu contains **Latest Beta & Developer Edition** and **Latest Nightly** under Desktop as well as **Latest Beta** under Android. Note that **Latest Nightly** for Android will be added later, so it shouldn't be there for now.

Fix Bug 1358198 - Remove Aurora/DevEdition links from Release Notes navigation, add Desktop Nightly link instead

---

bedrock/firefox/templates/firefox/releases/release-notes.html

The Desktop/Android navigation switches on older release notes, like [52.0](https://www.mozilla.org/en-US/firefox/52.0/releasenotes/), should link to the equivalent notes rather than the latest notes. There is the `equivalent_release_url` variable available in the template so let's use it.
[Bug 1311121](https://bugzilla.mozilla.org/show_bug.cgi?id=1311121)
Visit any older Desktop/Android release notes and click the navigation link to see if it works as expected.

Fix Bug 1311121 - Links to past Firefox for Android release notes all point to current version

---

bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html

Just updated the list for Q1 2017.
Everything seems good on local bedrock instance.

Update the web bug bounty Hall of Fame to have q1 2017

---

bedrock/base/templates/includes/canonical-url.html
bedrock/firefox/redirects.py
bedrock/firefox/urls.py
tests/redirects/map_globalconf.py

I'd like to have this be more automatic based on an alternate template and the
languages activated for it so that locales would automatically migrate to the new URL
as locales are activated, but this should fix the immediate issue.

Fix bug 1364452: Add ability to specify alternate canonical paths per locale

---

bedrock/firefox/templates/firefox/new/base.html
bedrock/firefox/templates/firefox/new/batm/base.html
bedrock/firefox/templates/firefox/new/batm/free.html
bedrock/firefox/templates/firefox/new/batm/nimble.html
bedrock/firefox/templates/firefox/new/batm/private.html
bedrock/firefox/templates/firefox/new/batm/resist.html
bedrock/firefox/templates/firefox/new/batm/scene1.html
bedrock/firefox/templates/firefox/new/batm/scene2.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/base.html
bedrock/firefox/templates/firefox/new/onboarding/scene1.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/firefox/new/batm.scss
media/css/firefox/new/break-free.scss
media/css/firefox/new/way-of-the-fox.scss
media/js/firefox/new/scene1-batm.js

- Adds another new ad campaign download page variation
https://bugzilla.mozilla.org/show_bug.cgi?id=1363802
https://bugzilla.mozilla.org/show_bug.cgi?id=1364988
- It's a new page, so some basic cross browser testing should cover things?
- Check for copy / pasta?
Demo:
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?xv=batmfree
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?xv=batmprivate
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?xv=batmnimble
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?xv=batmresist

[fix bug 1363802] /new variation to support ad campaign - BATM

---

media/css/base/global-nav.less
media/css/firefox/features/common.scss
media/css/firefox/hub/home.scss
media/css/firefox/product-page.scss
media/css/hubs/_sub-nav.scss
media/css/mozorg/home/home.scss
media/css/mozorg/internet-health.scss
media/css/mozorg/internet-health/health-subpage.scss
media/css/mozorg/technology.scss
media/css/newsletter/newsletter-developer.scss
media/css/newsletter/newsletter-firefox.scss
media/css/newsletter/newsletter-mozilla.scss
media/css/pebbles/base/elements/_forms.scss
media/css/pebbles/components/_buttons-download.scss
media/css/pebbles/components/_buttons.scss
media/css/pebbles/components/_global-nav.scss
media/css/pebbles/components/_modal.scss
media/css/pebbles/components/_newsletter.scss
media/css/pebbles/global.scss
media/css/pebbles/includes/_variables.scss
media/css/pebbles/includes/fonts/_open-sans.scss
media/css/pebbles/includes/fonts/_zilla-slab.scss

This sets Zilla Slab as the base font for all Pebbles-based pages, with Open Sans as a secondary accent font. This started just to fix the fake italics on Firefox hub pages, but adding two more weights of Zilla on top of the four weights of Open Sans was too much. This way it's two fonts in and two fonts out. And we might as well make the leap to global Zilla sooner rather than later (just in Pebbles; no Zilla in Sandstone). 
https://bugzilla.mozilla.org/show_bug.cgi?id=1363955
https://bedrock-demo-craigcook.us-west.moz.works
This only impacts Pebbles-based pages, so that's the home page, all the new Firefox pages, /technology, /internet-health (and subpages), /about/leadership, /moss, /newsletter/mozilla, /newsletter/firefox, /newsletter/developer.... I think that's it.

[fix bug 1363955] Switch Pebbles to Zilla Slab

---

bin/envcat
docker/bin/prep_demo.sh
docs/pipeline.rst
jenkins/branches/demo/pmac-new-pipeline.yml
jenkins/branches/prod.yml
jenkins/default.groovy

Was only needed for the "-deis" suffix on stage and prod but those are going away.
I've added a few more fixes to this one in subsequent commits:
* switch to dockerized envcat so we don't have to worry with installing it globally on the jenkins box
* more testing success message to a single one at the end of the build to make it a bit less chatty on IRC
* Remove old demo config file

Remove app name suffix from deployment

---

bedrock/mozorg/templates/mozorg/internet-health/decentralization.html

- Fixes broken link and updates string for quotation source (uses l10n tag `health-decentralization-link`)
https://bugzilla.mozilla.org/show_bug.cgi?id=1363913
- Link should be fixed for both old and new strings.

[fix bug 1363913] Fix broken link on decentralization page

---

bedrock/firefox/templates/firefox/releases/nightly-feed.xml
bedrock/firefox/templates/firefox/releases/nightly-notes.html
bedrock/firefox/urls.py
bedrock/releasenotes/tests/test_base.py
bedrock/releasenotes/views.py

Add an Atom feed of the [Firefox Nightly notes](https://www.mozilla.org/en-US/firefox/nightly/notes/) so people can subscribe to the latest changes in Nightly.
[Bug 1359037](https://bugzilla.mozilla.org/show_bug.cgi?id=1359037)
* Visit `/firefox/nightly/notes/feed/` to make sure the feed is served properly.
* Visit `/firefox/nightly/notes/` to make sure there is a link to the feed. In Firefox, **Subscribe to This Page...** in the **Bookmarks** menu will be enabled.

Fix Bug 1359037 - Provide some syndication feature to Nightly release notes

---

bedrock/firefox/redirects.py
tests/redirects/map_globalconf.py

- Adds UTM params to two existing redirects.
https://bugzilla.mozilla.org/show_bug.cgi?id=1364928
- Updated redirect tests to make sure params are being passed along correctly.

[fix bug 1364928] Add UTM params to /firstrun/learnmore/ and /windows-10/welcome/ redirects

---

bedrock/firefox/templates/firefox/includes/download-button.html
bedrock/firefox/templates/firefox/installer-help.html
tests/functional/firefox/test_installer_help.py
tests/pages/firefox/installer_help.py

Add a Firefox Nightly download button to the [installer help page](https://www.mozilla.org/en-US/firefox/installer-help/).
[Bug 1058017](https://bugzilla.mozilla.org/show_bug.cgi?id=1058017)
Visit `/firefox/installer-help/` and make sure there is a Nightly download button.

Fix Bug 1058017 - Stub installer for Nightly not working, redirect page missing Nightly

---

bedrock/security/tests/test_views.py
bedrock/security/urls.py

Fix some older advisory URLs not redirected properly.
[Bug 1236936](https://bugzilla.mozilla.org/show_bug.cgi?id=1236936)
Visit `/security/announce/mfsa2005-31.html` and other URLs written in `test_views.py` to make sure you'll be directed to the correct advisories.

Fix Bug 1236936 - Many broken links in Security Advisory pages

---

bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html

Updates community participation guidelines (aka code of conduct).
This is all new text but the previous version was only translated in Japanese so far. Given the nature of this document, and because it's a complete rewrite, I don't think we should let ja fall back to the old guidelines; we should probably just delete the lang file from ja and let it be translated again as if it were a new page.
In the very near future I think this will be managed as markdown files in an external repo (https://github.com/mozilla/diversity).
https://bugzilla.mozilla.org/show_bug.cgi?id=1364268

[fix bug 1364268] Update Community Participation Guidelines

---

bedrock/firefox/templates/firefox/all.html
bedrock/firefox/templates/firefox/releases/nightly-notes.html
media/css/firefox/all.less
media/css/firefox/releasenotes-firefox.less
media/css/sandstone/buttons.less
media/css/sandstone/lib.less
media/css/sandstone/oldIE.less
media/css/sandstone/sandstone-resp.less
media/css/sandstone/sandstone.less

* Change the logo and headline on the [Firefox Nightly notes](https://www.mozilla.org/en-US/firefox/nightly/notes/).
* Redesign the page by adopting the current [download page](https://www.mozilla.org/en-US/firefox/nightly/all/)'s theme.
* Repurpose Aurora's `space` visual style which is no longer used.
[Bug 1359102](https://bugzilla.mozilla.org/show_bug.cgi?id=1359102)
Check out the [demo server](https://bedrock-demo-nightly-notes.us-west.moz.works/en-US/firefox/nightly/notes/) to see everything looks right.

Fix Bug 1359102 - Release notes for Nightly need to display the Firefox Nightly logo + wording fixes

---

bedrock/firefox/templates/firefox/releases/nightly-notes.html
bedrock/firefox/templates/firefox/releases/release-notes.html
media/css/firefox/releasenotes-firefox.less

The download button on release notes should be matching the product's platform/channel, regardless of the visitor's browser, to avoid any confusion.
[Bug 1289074](https://bugzilla.mozilla.org/show_bug.cgi?id=1289074), [Bug 1362900](https://bugzilla.mozilla.org/show_bug.cgi?id=1362900)
Open various release notes and make sure the download button and the adjacent All Firefox downloads link match the product's platform/channel.
Exceptions:
* Fennec Aurora release notes links to Nightly, because Aurora is going away
* ESR notes doesn't have download buttons
* iOS release notes doesn't have the All Firefox downloads link

Fix Bug 1289074 - Download buttons on Dev Edition and Beta release notes pages point to Release channel

---

bedrock/firefox/templates/firefox/features/base.html
bedrock/firefox/templates/firefox/features/index.html
bedrock/firefox/templates/firefox/hub/home.html
bedrock/firefox/templates/firefox/products/desktop.html

Add Optimizely block to the new Fx Hub pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1361873
Make sure no copy pasta mistakes.

[fix bug 1361873] Add Optimizely to Fx Hub pages.

---

bin/run-prod.sh
docker/bin/run_integration_tests.sh

Meinheld (the default) is causing problems at tests startup, but works better when deployed.

Use sync gunicorn worker class for smoke tests

---

docker/bin/docker_build.sh

This will allow other jobs (configurator e.g.) to use
the ":latest" images for testing and other things.

Tag all images as "latest" during prod push

---

bedrock/base/templates/includes/news-feed.html

Rewords the blog CTA in the news feed from "The Firefox Frontier" to "Read More".
https://bugzilla.mozilla.org/show_bug.cgi?id=1367270
Passing: 
```(venv) bedrock$ py.test lib bedrock/firefox```

[fix bug 1367270] Reword blog CTA in news feed

---

media/js/base/core-datalayer-page-id.js
media/js/base/dnt-helper.js
media/js/base/gtm-snippet.js
media/js/base/mozilla-pixel.js
media/js/base/mozilla-traffic-cop.js
media/js/base/optimizely-snippet.js
media/js/base/stat-counter.js
media/js/base/stub-attribution.js
tests/unit/spec/base/core-datalayer-page-id.js
tests/unit/spec/base/dnt-helper.js
tests/unit/spec/base/mozilla-pixel.js
tests/unit/spec/base/stub-attribution.js

Adds functionality to pass original referrer ([set in a cookie by Traffic Cop](https://github.com/mozilla/trafficcop/pull/5)) to GTM after a Traffic Cop redirect has taken place.
**Note** - Version of Traffic Cop in this PR matches that pending in [`mozilla/traffic-cop #6`](https://github.com/mozilla/trafficcop/pull/6)
https://bugzilla.mozilla.org/show_bug.cgi?id=1364236
Biggest things to check:
1. Correct info is being passed to GTM in `core-datalayer-page-id.js`
2. Changing namespace around `dntEnabled` hasn't broken anything
3. General sanity around changes

[fix bug 1364236] Pass original referrer from traffic cop to GA

---

docker/bin/docker_build.sh
jenkins/default.groovy

This will ensure that the test image is available to the other jobs that need to tests bedrock instances.

Include test image in push to dockerhub

---

media/js/privacy/privacy.js

- Button was temporarily hidden for an experiment.
https://bugzilla.mozilla.org/show_bug.cgi?id=1354304
- Button should no longer be hidden in Firefox browsers.

[fix bug 1354304] Unhide download button on privacy page

---

bedrock/firefox/templates/firefox/new/batm/free.html

Adds Optimizely snippet to the `?xv=batmfree` variation of `/firefox/new/`. Other BATM variations will have different experiments, so keeping these switches specific to a single variation.
https://bugzilla.mozilla.org/show_bug.cgi?id=1367774
Look for silly mistakes?

[fix bug 1367774] Add Optimizely to /new/?xv=batmfree variation.

---

bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html

Oops, missed a string.
https://bugzilla.mozilla.org/show_bug.cgi?id=1364268#c13

[bug 1364268] Participation guidelines, enclose string for l10n

---

bedrock/firefox/firefox_details.py
bedrock/firefox/templates/firefox/includes/download-button.html
bedrock/firefox/templatetags/helpers.py
bedrock/firefox/tests/test_firefox_details.py
bedrock/firefox/tests/test_helpers.py
bedrock/releasenotes/tests/test_base.py
bedrock/styleguide/templates/styleguide/websites/sandstone-all-download-buttons.html

Firefox Nightly for Android is now available on [Google Play](https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora). This PR uses the Google Play link for the Nightly download button accordingly and removes the Aurora support.
[Bug 1369120](https://bugzilla.mozilla.org/show_bug.cgi?id=1369120)
Visit `/firefox/channel/android/` to see the Nightly download button goes to Google Play. Meanwhile `/firefox/android/nightly/all/` still has direct links.

Fix Bug 1369120 - Use Google Play link for Fennec Nightly

---

bedrock/firefox/templates/firefox/new/batm/free.html
bedrock/firefox/templates/firefox/new/batm/private.html

Adds Optimizely snippet to the `?xv=batmprivate` variation of `/firefox/new/`.
Also changes switch name for `?xv=batmfree` variation to be more explicit (adds `-optimizely` suffix).
**This will require renaming the currently enabled switch `SWITCH_FIREFOX_NEW_BATMFREE` to `SWITCH_FIREFOX_NEW_BATMFREE_OPTIMIZELY`.**
https://bugzilla.mozilla.org/show_bug.cgi?id=1367774#c19
Look for copy pasta errors.

[fix bug 1367774] Add Optimizely to /new/?xv=batmprivate variation.

---

bedrock/firefox/redirects.py
tests/redirects/map_globalconf.py

Canonicalize the capitalized `Firefox` URL so it won't end up with a 404 page.
[Bug 1369732](https://bugzilla.mozilla.org/show_bug.cgi?id=1369732)
Visit `/Firefox` and `/en-US/Firefox` to see those URLs are redirected to `/firefox/`.

Fix Bug 1369732 - Redirect http://mozilla.org/Firefox to https://www.mozilla.org/firefox/

---

tests/functional/firefox/test_home.py
tests/pages/firefox/home.py

As the home page blog feed presence is potentially very fickle, best to remove the test for now so as not to block test runs should a blog post not be available.
Kept the [property/region on the page class](https://github.com/mozilla/bedrock/blob/master/tests/pages/firefox/home.py#L24) in the event we want to reinstate a version of this test later on.
Nope.
Ensure tests still pass and no other code should be removed.

Remove Fx home blog feed functional test

---

media/css/base/global-nav.less
media/css/hubs/_sections.scss
media/css/hubs/_sub-nav.scss
media/css/pebbles/components/_global-nav.scss
media/css/pebbles/includes/_variables.scss
media/css/sandstone/lib.less
media/js/hubs/sub-nav.js

The first iteration of the global nav had some hard-coded widths designed around the specific English links and didn't really handle links wrapping when they get lonk, which is almost guaranteed to happen once we start localizing those labels. This makes a few tweaks to the nav so when links wrap to a second line it doesn't look too horrible.
https://bugzilla.mozilla.org/show_bug.cgi?id=1353587
Since the navbar is only English right now you'll have to change some content locally to really test the wrapping. Try adding longer text in existing links as well as additional links, both in the main nav and subnav.

[bug 1353587] Make global nav accommodate text wrapping

---

bedrock/firefox/templates/firefox/sync-en.html
bedrock/firefox/templates/firefox/sync.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/urls.py
bedrock/firefox/views.py

Update copy on `/firefox/sync` for `en-*` locales only.
These changes are knowingly temporary. The Sync page is scheduled to be changed significantly (functionality & copy) when brought into the Fx Hub (Q3?).
https://bugzilla.mozilla.org/show_bug.cgi?id=1366815#c10
Ensure minor changes to `firefox/sync.html` do not cause any new issues with non `en-*` locales.
Ensure `firefox/sync-en.html` displays the correct content for the following three states:
**Firefox, logged in to Sync**
- *Headline*: Browse boldly. Connect your devices.
- *Subhead*: Add Firefox on your personal devices to get your bookmarks, open tabs and passwords anywhere. Get secure access to everything you need when you sign into your Firefox Account.
- *Small subhead*: Add Firefox to more devices now.
**Firefox, not logged …

[fix bug 1366815] Update /firefox/sync copy for en-*.

---

bedrock/mozorg/templates/mozorg/about/forums/forums.html

Update the [Forums page](https://www.mozilla.org/en-US/about/forums/) to modify MDN forum entries so those have a link to Discourse instead of Google Groups.
[Bug 1370337](https://bugzilla.mozilla.org/show_bug.cgi?id=1370337)
Visit `/about/forums/` to see the 3 MDN forums have been replaced with the custom entries, while others remain the same.

Fix Bug 1370337 - On /about/forums, replace mdn entries with links to Discourse

---

bedrock/firefox/views.py
bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/tests/test_helper_misc.py
bedrock/settings/base.py

Just a quick update to remove some out of date query string params from donate.mozilla.org links.
I didn't create one seemed too insignificant, and felt a pull request was enough. I can create one if needed though :)

Remove EOY2015 related query strings from donate.mozilla.org links.

---

bedrock/base/templates/includes/canonical-url.html

Some locales on mozorg are not supported by Google and other search engines, and those `<link rel="alternate">` lines lead to errors on the SEM dashboard. This PR removes the known 7 locales from the alternate locale list.
[Bug 1364470](https://bugzilla.mozilla.org/show_bug.cgi?id=1364470)
Check the homepage, for example, to see the 7 locales are not included in the alternate locale list, while the language switcher at the bottom of the page still offers these locales.

Fix Bug 1364470 - Update Country Codes in Hreflang tags

---

bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
bedrock/mozorg/templates/mozorg/internet-health/index.html
bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
bedrock/mozorg/templates/mozorg/internet-health/web-literacy.html

My gut reaction is: let's never do this again. 
We ended up duplicating strings all over the place by adding a new page to a connected system every couple of weeks. 
This tries to fix the mess, and it would be blocking us from exposing new strings for the hub (we need it merged and pushed to prod), since it moved shared strings (nav menu, newsletter) to a shared file.
CC @peiying2

[no bug] Use shared lang files in all Internet Health pages

---

bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54-ja-zhcn-base.html
bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54.de.html
bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54.html
bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54.ja.html
bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54.zh-CN.html
bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54.zh-TW.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-50.zh-TW.html
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/firefox/whatsnew/whatsnew-54.less
media/js/firefox/whatsnew/experiment-whatsnew-54-de.js
media/js/firefox/whatsnew/experiment-whatsnew-54-ja-zhcn.js

**Experiment 1: de**
Basically running the same experiment we ran for zh-TW on Fx 53 whatsnew, but now for de. 50% should get `?v=a`, which is the control with the send to device widget. 50% get `?v=b`, which is the QR code.
**Experiment 2: ja & zh-CN**
`?v=c` is the control, and has no primary CTA (just app store badges). `?v=d` is the QR code.
Also:
- reverts `data-link-name` on the updated wordmark to `tabzilla` (at pg's request)
- moves app store badges further "below the fold" if either send to device widget or QR code are present (these are the "primary CTAs")
https://bugzilla.mozilla.org/show_bug.cgi?id=1365741#c4
https://bugzilla.mozilla.org/show_bug.cgi?id=1365741#c6
In a browser with DNT disabled, make sure `/de/firefox/54.0/whatsnew/` loads the variations outlined above. Also …

[fix bug 1365741] Fx54 /whatsnew: Add experiments for de, ja, & zh-CN.

---

jenkins/branches/virginia.yml

I pushed this to the virginia branch to trigger a deployment to work around some issues pulling the bedrock image from the docker hub. Pasting partial IRC transcript:
```
12:45 PM H<hms-flintstone-325> 🚨 FAILURE: Deploy bedrock-dev-virginia: Branch master build #325: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/325/pipeline
12:46 PM C<•craigcook> not sure what's up with Virginia...
1:02 PM J<jpetto> we waiting on virginia before pushing, eh?
1:02 PM J<jpetto> looks like a 502 - likely not code related. jgmize?
1:08 PM J<•jgmize> jpetto: working on it now
1:08 PM J<jpetto> thx
1:18 PM M<mr_slate> [bedrock] jgmize created virginia (+1 new commit): https://github.com/mozilla/bedrock/commit/be0a62d993ef
1:18 PM M<mr_slate> bedrock/virginia …
```

Push virginia dev

---

bedrock/base/templates/includes/news-feed.html
bedrock/firefox/templates/firefox/features/base.html
bedrock/firefox/templates/firefox/hub/home.html
bedrock/firefox/templates/firefox/products/product-base.html
bedrock/mozorg/templates/mozorg/internet-health/index.html

- Updated news feed links on hub pages to use the correct utm_campaign values.
https://bugzilla.mozilla.org/show_bug.cgi?id=1371832
- Blog links on Firefox hub pages should use `utm_campaign=fx-content-hub`
- Blog links on Internet Health hub page should use `utm_campaign=ih-content-hub`
- Make sure I didn't miss any pages?

[fix bug 1371832] Use correct utm_campaign params in hub news feeds

---

bedrock/firefox/templates/firefox/features/base.html
bedrock/firefox/templates/firefox/hub/home.html
bedrock/firefox/templates/firefox/products/desktop.html
media/css/base/global-nav.less
media/css/firefox/features/common.scss
media/css/firefox/hub/home.scss
media/css/firefox/product-page.scss
media/css/hubs/_buttons.scss
media/css/hubs/_cards-block.scss
media/css/hubs/_cards.scss
media/css/hubs/_common.scss
media/css/hubs/_news-feed.scss
media/css/hubs/_sub-nav.scss
media/css/pebbles/components/_global-nav.scss
media/img/hubs/cta-arrow.svg

Changes the main download button to green and link colors to blue. These may become global colors in pebbles but limited to just the hub pages for now.
https://bugzilla.mozilla.org/show_bug.cgi?id=1370326
Make sure I didn't miss a page. There shouldn't be any more burnt orange links.

[fix bug 1370326] Change button and link colors on hub pages

---

bedrock/firefox/firefox_details.py
bedrock/firefox/tests/test_firefox_details.py

The bouncer prefix for Firefox Developer Edition has been changed from `firefox-aurora` to `firefox-devedition`. The download buttons on mozilla.org have to be updated accordingly.
[Bug 1357379](https://bugzilla.mozilla.org/show_bug.cgi?id=1357379)
Visit `/firefox/channel/desktop/`, `/firefox/developer/` and `/firefox/developer/all/` to make sure the Developer Edition download buttons are working properly.

Fix Bug 1357379 - Download links for Dev Edition will need to be updated post Dawn

---

bedrock/firefox/firefox_details.py
bedrock/firefox/tests/test_firefox_details.py

Reverts mozilla/bedrock#4862
Had to revert due to test failures. Bouncer is returning 404s, which is the cause of the below failures from the [test run](https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/332/pipeline/):
```
=========================== short test summary info ============================
FAIL tests/functional/test_download_l10n.py::test_localized_download_links[https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=win64&lang=be]
FAIL tests/functional/test_download_l10n.py::test_localized_download_links[https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=win&lang=be0]
FAIL tests/functional/test_download_l10n.py::test_localized_download_links[https://download.mozilla.org/?product=firefox-deved …
```

Revert "Fix Bug 1357379 - Download links for Dev Edition will need to be updated post Dawn"

---

docs/uitour.rst

Documentation update for UITour. 
~~This awaits firefox review and merge so I'm adding the `blocked` and `do not merge` labels. ~~
- This has been data reviewed [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1343510#c33). 
- We wait for related patch to be accepted in firefox before merging.

[bug 1343510] Add documentation for UITour's createdWeeksAgo and resetWeeksAgo.

---

bedrock/base/templates/includes/global-nav.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/scene2.html

Seems we're squandering precious Google-juice by not linking to our own page. This update changes the main Firefox link in the global nav to point to /firefox for en-US, and we can remove that conditional once we have good locale coverage for that page. JS hijacks the link (until bug 1367793 changes that) so human users won't notice but robots will still follow the href.
This also links the logo on the /new page to /firefox, again only for en-US until /firefox is localized. Only on the standard download page (both scenes) and none of the numerous variants which shouldn't be indexed anyway.
Nav links - https://bugzilla.mozilla.org/show_bug.cgi?id=1372331
Logo link - https://bugzilla.mozilla.org/show_bug.cgi?id=1372328

Bugs 1372331, 1372328 - Change Firefox links in global nav, add link to /new

---

bedrock/base/templates/includes/global-nav.html
media/js/base/mozilla-global-nav.js

- Makes the top horizontal links on the global link behave like, duh - links.
- No longer auto expand/collapse sub menu's on drawer toggle (since only direct clicks from the user now trigger state change).
https://bugzilla.mozilla.org/show_bug.cgi?id=1367793
- Demo: https://www-demo5.allizom.org/en-US/
- Ensure links behave like links, naturally.
- Ensure sidebar still works as normal via the menu button.

[fix bug 1367793] Global nav links should behave like links

---

bedrock/firefox/templates/firefox/features/fast.html
bedrock/firefox/templates/firefox/features/index.html
bedrock/firefox/templates/firefox/features/private-browsing.html
bedrock/firefox/templates/firefox/hub/home.html
bedrock/firefox/templates/firefox/products/desktop.html
bedrock/mozorg/templates/mozorg/internet-health/includes/podcast.html
bedrock/mozorg/templates/mozorg/internet-health/index.html
media/css/firefox/features/common.scss
media/css/firefox/product-page.scss
media/css/hubs/_card-image-large.scss
media/css/hubs/_cards-block.scss
media/css/hubs/_cards.scss

- Improves general consistency for link targets on Firefox hub pages (also Internet Health hub for good measure)
https://bugzilla.mozilla.org/show_bug.cgi?id=1370818
- Best clean `/static` dir prior to reviewing: `gulp static:clean`.

[fix bug 1370818] Inconsistent link targets on /firefox

---

bedrock/firefox/templates/firefox/releases/nightly-notes.html
bedrock/firefox/templates/firefox/releases/release-notes.html

* Specify the Nightly `og:image` and favicon
* Add links to the Nightly blog
[Bug 1371495](https://bugzilla.mozilla.org/show_bug.cgi?id=1371495)
Visit `/firefox/nightly/notes/` to see the favicon and page image are the Nightly branding. In Firefox the Nightly News feed should be discoverable via the Bookmarks menu. There is also a link to the blog in the Other Resources section at the bottom of the page.

Fix Bug 1371495 - Specify Nightly page image and icon for Nightly release notes

---

bedrock/firefox/templates/firefox/new/batm/machine-a.html
bedrock/firefox/templates/firefox/new/batm/machine-b.html
media/js/firefox/new/scene1-batm-anim.js

Adds the `v=` param to download buttons, and also loads the correct JS on the B version.
https://bugzilla.mozilla.org/show_bug.cgi?id=1366397
Ensure the buttons on both page variants are getting both the `xv=batmprivate` and `v=a/b` parameters and that it's being passed through scene 2.

[fix bug 1366397] BATMAn - add variant param to download button

---

bedrock/firefox/templates/firefox/new/scene1.html
bedrock/settings/static_media.py
media/js/firefox/new/experiment-search-retention-funnelcakes.js

Adds experiment for funnelcakes 114 - 118 to `/firefox/new` for en-US, Windows, desktop, non-Firefox users geolocated in the US.
(I checked with Hanno regarding the increased hits to `location.services.mozilla.com` and he said it wont be a problem.)
Must add following funnelcake config to env:
```
FUNNELCAKE_114_PLATFORMS=win
FUNNELCAKE_114_LOCALES=en-US
FUNNELCAKE_115_PLATFORMS=win
FUNNELCAKE_115_LOCALES=en-US
FUNNELCAKE_116_PLATFORMS=win
FUNNELCAKE_116_LOCALES=en-US
FUNNELCAKE_117_PLATFORMS=win
FUNNELCAKE_117_LOCALES=en-US
FUNNELCAKE_118_PLATFORMS=win
FUNNELCAKE_118_LOCALES=en-US
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1363499
Visit `/en-US/firefox/new/` on Windows (or with `windows` hard-coded in `window.site.getPlatform()`) in a browser with DNT disabled. Should get one of 5 …

[fix bug 1363499] Experiment for funnelcakes 114-118.

---

root_files/projects/calendar/caldata

If the symlink is to /static is will be broken and cause errors if "manage.py collectstatic" is not run first.
/cc @jpetto

Change symlink for calendar data

---

bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/scene2.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/js/firefox/new/experiment-win64-funnelcakes-scene2.js
media/js/firefox/new/experiment-win64-funnelcakes.js

Adds a funnelcake experiment for Win64 builds for de, es-ES, fr, pt-BR, and ru locales.
**DO NOT MERGE:** Waiting on green light from the Win64 team. Code is good for review though.
https://bugzilla.mozilla.org/show_bug.cgi?id=1309847
Add the following to your config:
```
FUNNELCAKE_105_PLATFORMS=win
FUNNELCAKE_105_LOCALES=pt-BR,fr,de,ru,es-ES
FUNNELCAKE_106_PLATFORMS=win
FUNNELCAKE_106_LOCALES=pt-BR,fr,de,ru,es-ES
```
On a Windows 64 VM (the MsEdge/Win10 VM works, or hack `window.site.platform` to return `windows` and hack `experiment-win64-funnelcakes-scene2.js` to skip the Win64 userAgent check), visit `/firefox/new/?f=105` and `/firefox/new/?f=106` with any of the locales listed above.
`?f=105` should download a full build of the Win32 funnelcake. `?f=106` should download a full build …

[fix bug 1309847] Win64 funnelcake experiment.

---

bedrock/base/templates/includes/global-nav.html
bedrock/base/templates/includes/sub-nav.html
bedrock/firefox/templates/firefox/features/base.html
bedrock/firefox/templates/firefox/hub/home.html
bedrock/firefox/templates/firefox/includes/download-button.html
bedrock/firefox/templates/firefox/new/onboarding/scene1.html
bedrock/firefox/templates/firefox/new/onboarding/scene2.html
bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/scene2.html
bedrock/firefox/templates/firefox/products/android.html
bedrock/firefox/templates/firefox/products/desktop.html
bedrock/firefox/templates/firefox/products/focus.html
bedrock/firefox/templates/firefox/products/ios.html
bedrock/firefox/templatetags/helpers.py
bedrock/firefox/tests/test_helpers.py
bedrock/mozorg/templates/mozorg/home/includes/nav.html

- Add an optional `download_location` parameter to the button helper, which can be used to specify the location of a button on any given page, passed to GA via a data attribute.
- Adds data attributes to all buttons on new style hub pages, plus the global and sub nav components (We're is not concerned with older legacy pages right now).
- Also adds data attributes to `/firefox/new/`
~- Still need to confirm this is what Peter expects to see, so do not merge for now.~
https://bugzilla.mozilla.org/show_bug.cgi?id=1359982
https://www-demo3.allizom.org/en-US/firefox/

[fix bug 1359982] Add location tag to download button

---

bedrock/firefox/templates/firefox/new/batm/scene1.html

After testing different copy treatments on the BATM download page, this makes the winning version permanent.
https://bugzilla.mozilla.org/show_bug.cgi?id=1367774#c30

[bug 1367774] Update BATM download page copy

---

bedrock/firefox/templates/firefox/releases/nightly-feed.xml

* Fix the current first entry not showing up on feedly, probably due to an [interoperability issue](https://validator.w3.org/feed/check.cgi?url=https://www.mozilla.org/en-US/firefox/nightly/notes/feed/).
* [Optimize the feed for feedly](https://blog.feedly.com/10-ways-to-optimize-your-feed-for-feedly/) by specifying the cover image and icon.
[Bug 1371470](https://bugzilla.mozilla.org/show_bug.cgi?id=1371470)
Visit `/firefox/nightly/notes/feed/` to see the first entry no longer contains `&amp;gt;` in the source. The feed should contain `<webfeeds:cover>` and `<webfeeds:icon>`, should be [validated](https://validator.w3.org/feed/).

Fix Bug 1371470 - Fix & optimize Firefox Nightly Notes feed

---

bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/scene2.html
bedrock/firefox/templates/firefox/new/survey.html
bedrock/settings/static_media.py
media/css/firefox/new/common.less
media/js/firefox/new/survey.js

- Adds a simple survey link to both scene1 and scene2 of /firefox/new/
- Survey shows for en-US Desktop only, at 50% sample rate.
- Query params are passed along to the survey.
https://bugzilla.mozilla.org/show_bug.cgi?id=1366952
- Both scene1 and scene2 for en-US. Survey should show up 50% of the time as expected.

[fix bug 1366952] Add survey to /firefox/new/

---

media/js/firefox/new/survey.js

Since the link is behind a switch but the JS isn't, we'll make sure the survey link exists in the DOM before trying to show it.

[bug  1366952] Add conditional to download survey link JS

---

bedrock/firefox/templates/firefox/hub/home.html

- Updates 2 quotes on /firefox/
- Both use hard-coded, English only strings (no l10n impact)
https://bugzilla.mozilla.org/show_bug.cgi?id=1375728
- Check for copy pasta errors?

[fix bug 1375728] Update 3rd party quotes on /firefox/

---

media/css/base/global-nav.less
media/css/hubs/_masthead.scss
media/css/hubs/_sub-nav.scss
media/css/pebbles/components/_global-nav.scss

- Updates download button color in the fallback navigation which gets shown for locales that don't yet get the global navigation e.g. https://www-dev.allizom.org/de/internet-health/
- This PR also tweaks the default button padding in both the global and sub navigation, so "Firefox herunterladen" still fits on one line.
https://bugzilla.mozilla.org/show_bug.cgi?id=1370326
- Test `/de/internet-health/` and make sure both nav and sub-nav buttons look ok.
- Test `/en-US/` homepage (pebbles), test `/en-US/about/` (sandstone) for any regressions.

[bug 1370326] Update button color for fallback navigation

---

media/caldata/calendars.json

Changed date span end year for already updated Spanish Calendar to 2017
https://bugzilla.mozilla.org/show_bug.cgi?id=1325879

Changed year for already updated Spanish Calendar

---

bedrock/firefox/templates/firefox/channel/desktop.html

Update the "frightening" Nightly description on [/firefox/channel/desktop/](https://www.mozilla.org/en-US/firefox/channel/desktop/). Cc @flodolo @peiying2
[Bug 1375100](https://bugzilla.mozilla.org/show_bug.cgi?id=1375100)
Open the channel page to make sure the new copy is displayed.

Fix Bug 1375100 - Update the Nightly copy to be slightly less frightening.

---

bedrock/firefox/templates/firefox/products/focus.html

- Updates values copy on /firefox/focus/ page to match other hub page strings for l10n

[bug 1350170] Update values copy on /firefox/focus/ for l10n

---

.github/PULL_REQUEST_TEMPLATE.md

Removes the checklist from the PR template because:
1. We tend to use labels for l10n as they are more easily visible in the PR view.
2. People often confuse the integration tests checkbox with the unit test run in CI

Remove checklist from pull request template

---

media/css/firefox/all.less

- Hides sha-1 links on /all for small screen sizes. These should not have been visible by default.
https://bugzilla.mozilla.org/show_bug.cgi?id=1377769
- Resize the browser down to small viewport size. Sha-1 links should not be visible (where as they are currently visible on prod).
- Adding a class of `windows sha-1` to the `<html>` element should still make the sha-1 links visible (hiding the regular bouncer links).

[fix bug 1377769] Hide sha-1 bouncer links on /all for small screens

---

bedrock/firefox/templates/firefox/features/fast.html

- Removes some erroneous copy/pasta braces introduced in #4908.
- Does not effect existing strings or l10n.
https://bugzilla.mozilla.org/show_bug.cgi?id=1376816

[fix bug 1376816] Fix title on /firefox/features/fast/

---

bedrock/foundation/templates/foundation/annualreport/2015/faq.html

The word "internet" was written without the first"i"
A typography correction
No bugzilla link
No test required

Correct typography mistake

---

bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/templates/mozorg/technology.html

- Updates some links & copy on the home page and /technology page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1372304
- Make sure link destinations work and no copy pasta errors?

[fix bug 1372304] Update Mozorg links for Emerging Technologies

---

bedrock/privacy/templates/privacy/index.html
bedrock/privacy/templates/privacy/notices/firefox-cliqz.html
bedrock/privacy/urls.py
bedrock/privacy/views.py
media/css/privacy/privacy.less

- Creates the template and URL for the privacy notice added in #4946.
- Also added a link to the new notice in `/privacy/`
https://bugzilla.mozilla.org/show_bug.cgi?id=1378992
- Make sure you update git sub-modules to include the latest commits from legal-docs.
- Visit `/firefox-cliqz/` and make sure the page displays correctly.

[fix bug 1378992] Add Firefox + Cliqz privacy page

---

bedrock/firefox/templates/firefox/new/fx-lifestyle/working-out/scene1.html

Just adds the Optimizely block with a unique switch name for en-US only.
https://bugzilla.mozilla.org/show_bug.cgi?id=1375967
Make sure no silly mistakes.

[fix bug 1375967] Add Optimizely to Fx new lifestyle workingout variant

---

bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html

Contributor "Vaibs" send us an email to our security e-mail address and asked for his listing in the hall of fame to be changed to his real name. I have confirmed that he is in fact the same person that found the bug back then.
Can we get this change in?
N/A
N/A

Contributor asking for a name change in the Hall Of Fame

---

media/js/base/mozilla-fxa-iframe.js
tests/unit/spec/base/mozilla-fxa-iframe.js

- Adds `?service=sync` as a temporary workaround to avoid an unwanted redirect back to /signin.
https://bugzilla.mozilla.org/show_bug.cgi?id=1380825
Demo: https://www-demo3.allizom.org/en-US/firefox/54.0/firstrun/
1. Launch a new profile using [settings required](http://bedrock.readthedocs.io/en/latest/firefox-accounts.html#demo-server-testing) for testing against a demo instance of bedrock / fxa server.
2. Sign in with an existing Fx Account.
3. Verify that upon successful signin you are redirected to https://accounts.firefox.com/settings?service=sync

[fix bug 1380825] Firstrun page should add  param upon opening FxA's settings page

---

media/css/firefox/features/common.scss
media/css/mozorg/developer/index.scss

Minor visual regression from #4960

[bug 1378137] Fix lazy-image placeholder color on /firefox/features/

---

bedrock/base/templates/includes/news-feed.html
bedrock/firefox/templates/firefox/hub/home.html
bedrock/firefox/templates/firefox/products/android.html
bedrock/firefox/templates/firefox/products/desktop.html
bedrock/firefox/templates/firefox/products/focus.html
bedrock/firefox/templates/firefox/products/ios.html
bedrock/mozorg/templates/mozorg/developer/index.html
bedrock/mozorg/templates/mozorg/internet-health/index.html
media/css/firefox/features/common.scss
media/css/firefox/features/detail.scss
media/css/firefox/focus.scss
media/css/firefox/hub/_outro.scss
media/css/firefox/hub/home.scss
media/css/firefox/product-page.scss
media/css/hubs/_cards-block.scss
media/css/hubs/_cards.scss
media/css/hubs/_common.scss
media/css/hubs/_header.scss
media/css/hubs/_masthead.scss
media/css/hubs/_news-feed.scss
media/css/hubs/_sub-nav.scss
media/css/mozorg/developer/hub/_newsletter.scss
media/css/mozorg/developer/index.scss
media/css/mozorg/internet-health/hub/_campaign.scss
media/css/mozorg/internet-health/hub/_newsletter.scss
media/css/mozorg/internet-health/index.scss
media/css/pebbles/base/elements/_document.scss
media/css/pebbles/components/_footer.scss
media/css/pebbles/includes/_functions.scss
media/css/pebbles/includes/mixins/_typography.scss

- Updates headings in Pebbles to fit the [new typographic scale](http://craigcook.github.io/etc/typescale/).
- Changes all labels to sentance case
- Updates product headings to incorporate the word "Browser".
- Moves header CSS to a shared component.
- Updates nav and subnav CSS to accommodate RTL.
Note: I've lowered the base size of Zilla from 20px to 18px for the body copy on all hub pages. If we stuck exactly to the scale linked above, the base size should be 16px. For the regular Zilla weight however, 18px *looks* the same size as 16px in Open Sans. Zilla at 16px looks around 14px, and feels just too small. The two just aren't well balanced enough imho :/
https://bugzilla.mozilla.org/show_bug.cgi?id=1369144
https://bugzilla.mozilla.org/show_bug.cgi?id=1375636 …

[fix bug 1369144] Adjust Fx Hub headers & sub-headers

---

bedrock/firefox/redirects.py

While copy issues are addresses on the Send Tabs page, product needs to ship with a link to the upcoming `/firefox/features/send-tabs/` page. This is a temporary redirect just to get that URL to not 404. Will be removed when send tabs page goes live.
https://bugzilla.mozilla.org/show_bug.cgi?id=1370574#c15
Ensure I did the redirect correctly.

[fix bug 1370574] Add temporary redirect for send tabs page.

---

bedrock/privacy/templates/privacy/index.html

- Removes link to Persona in the /privacy sidebar.
- Ask for now is to remove only the link, but keep the `/persona/privacy-policy/` URL around.
https://bugzilla.mozilla.org/show_bug.cgi?id=1380845

[fix bug 1380845] Remove Persona privacy link

---

bedrock/firefox/templates/firefox/products/developer.html

Changes a CTA to avoid a duplicate string. Also changes some headlines and CTAs to sentence case. A few headings appear to be title case but only because the feature name is treated as a proper noun (e.g. "Responsive Design Mode").
The page hasn't yet been exposed to l10n so I don't think we need tags for these changes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1382107

[fix bug 1382107] Developer Edition string updates

---

bedrock/base/templates/includes/global-nav.html
media/css/base/global-nav.less
media/css/pebbles/components/_global-nav.scss
media/css/pebbles/includes/_variables.scss
media/css/sandstone/lib.less

- Adds Pocket to the global nav primary links
- ~Still waiting on some copy blurb, so do-not-merge for now.~
- Also fixes a missing `utm_campaign` param name on outgoing links.
https://bugzilla.mozilla.org/show_bug.cgi?id=1382807

[fix bug 1382807] Add Pocket to global nav links

---

bedrock/firefox/templates/firefox/new/batm/scene2.html
bedrock/firefox/templates/firefox/new/fx-lifestyle/working-out/scene2.html

- batm*
- workingout
Adds Optimizely block for scene 2's targeted by experiment.
Accompanying config change is at mozmeao/www-config#26.
https://bugzilla.mozilla.org/show_bug.cgi?id=1375967
Make sure no typos or regressions.
Optimizely should end up added to these URLs:
- `firefox/new/?xv=batmprivate&scene=2`
- `firefox/new/?xv=workingout&scene=2`

[fix bug 1375967] Add Optimizely to scene 2 on /new variations:

---

bedrock/settings/base.py
wsgi/app.py

When used as a Django middleware all asset responses include all headers intended for page responses (e.g. CSP and XSS protection).  Switch to WSGI middleware to avoid sending extra data as well as to avoid confusing Safari.

Use Whitenoise as wsgi middleware, not Django

---

bedrock/base/templates/includes/site-footer.html
media/css/pebbles/components/_footer.scss
media/css/sandstone/sandstone-resp.less
media/css/sandstone/sandstone.less

- Updates site footer to add links to `/firefox/focus/` and `/firefox/channel/` pages.
- Also updates some of the keywords in existing links (at @hoosteeno's request).
- `Mozilla` and `Firefox` headings become links.
- Also fixes an existing CSS bug in the non-responsive version of the footer styles, where `:hover` & `:focus` link styles weren't being applied (you can test this on the `/styleguide` pages).
The intent here is to push this out for `en` locales now and begin translating the new strings. Once enough locales have updated, we can remove the conditional.
https://bugzilla.mozilla.org/show_bug.cgi?id=1380317
- Check for any typos? (see [final spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1380317#c14) in the bug for reference).

[fix bug 1380317] Update site footer Firefox links

---

bedrock/base/templates/includes/global-nav.html

Fixes a bug introduced in #4990. This is what I get for trying to rush something in at the end of the day 😩

[bug 1382807] Fix missing base url for Pocket link in nav drawer

---

tests/pages/regions/newsletter.py

Our newsletter tests started failing as a side effect of our footer expanding in height in #4995. This was an unrelated change in behavior since Selenium automatically scrolls elements into view when clicked. The taller footer meant the newsletter submit button was now being obscured by the sticky navigation, which you can see in [this video](https://saucelabs.com/beta/tests/8d5fcdd435204e0c842b487185a93e1e/). Note you need to be logged in to view the recording. This fix scrolls the newsletter into view before interacting with it.
Failure: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/prod/120/pipeline
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/41/pipeli …

Scroll newsletter into view before expaning form in functional tests

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

Redirect `/developers/` to [`/developer/`](https://www.mozilla.org/developer/) so it won't lead to 404 Not Found.
[Bug 1384370](https://bugzilla.mozilla.org/show_bug.cgi?id=1384370)
Just visit `/developers/` to make sure you'll be taken to `/developer/`.

Fix Bug 1384370 - Redirect https://www.mozilla.org/en-US/developers - redirect to /developer

---

bedrock/firefox/redirects.py
bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

Split from #4937. Simply remove all the redirects to mozilla.jp which have been added over the course of years as per requested by the Mozilla Japan team (including me). We have discussed today and decided to proceed with the change. The removal shouldn't require any confirmation or approval from MoCo management.
[Bug 1384823](https://bugzilla.mozilla.org/show_bug.cgi?id=1384823)
Visit `/ja/` or `/ja/about/` to make sure those URLs will no longer be redirected. Those pages have already been localized so you'll just get Japanese content there.

Fix Bug 1384823 - Remove all redirects to mozilla.jp

---

bedrock/privacy/templates/privacy/index.html

Changing to the Mountain View office instead of San Francisco.
https://bugzilla.mozilla.org/show_bug.cgi?id=1385052

[fix bug 1385052] Update mailing address on privacy page

---

bedrock/mozorg/templates/mozorg/home/home.html

Change the Mozilla VR link to the new canonical URL: vr.mozilla.org
[Bug 1384360](https://bugzilla.mozilla.org/show_bug.cgi?id=1384360)
Visit the homepage and make sure the ﻿﻿﻿﻿Virtual Reality Platform goes to vr.mozilla.org, though it's still redirected to mozvr.com.

Fix Bug 1384360 - Mozilla.org Home - Our Innovations - VR Link Update for Fx55

---

bedrock/mozorg/templates/mozorg/technology.html

Update the title, description and links of the IoT section on the [Technology](https://www.mozilla.org/technology/) page. Used a l10n tag so this can be shipped soon for en-US.
[Bug 1384365](https://bugzilla.mozilla.org/show_bug.cgi?id=1384365)
Visit `/technology/` and make sure the IoT section is updated as per the request in the bug.

Fix Bug 1384365 - Mozilla.org/Technology Internet of Things - Change title, description, and links (in this card)

---

bedrock/mozorg/templates/mozorg/plugincheck-update.html
bedrock/mozorg/urls.py
bedrock/mozorg/views.py
bedrock/settings/static_media.py
media/css/plugincheck/plugincheck-update.scss
media/js/plugincheck/plugincheck-update.js

The plugin check functionality is deprecated but there are still old Firefoxes with in-product links to the page, which now presents misleading information. This creates a new plugincheck page encouraging users to update Firefox. This will entirely replace the old page once we have decent locale coverage, at which time we can delete the old plugincheck page and assets.
https://bugzilla.mozilla.org/show_bug.cgi?id=1380841
https://bedrock-demo-craigcook.us-west.moz.works/en-US/plugincheck/
There are three states with different messaging:
* Latest Firefox (or pre-release)
* Outdated Firefox
* Not Firefox
It should detect minor versions as well - e.g. Firefox 54.0 should be treated as out of date because 54.0.1 is the latest - but that could be tricky to test if you don't have a stale browser …

[fix bug 1380841] Add Firefox update to plugincheck page

---

bedrock/security/templates/security/product-advisories.html

PollBot is a collection of bots that poll for the state of things during the release process. One of these polls checks mozilla.org for a release's security advisories. This change adds a `data-version` attribute to the advisory links so it is easier for a scraper to locate and verify them. 
https://github.com/mozilla/PollBot/issues/6
(Please advise on how Bedrock tests HTML templates)

Add data-version attribute to security advisory links

---

bedrock/firefox/templates/firefox/new/sem/unsupported-browser/scene1.html
bedrock/firefox/templates/firefox/new/sem/unsupported-browser/scene2.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
media/css/firefox/new/sem.less

- Adds a new sem page variation at `/firefox/new/?xv=unsupported-browser`
- Removes Antoniobold font from headings on all /sem page variations, [as requested here](https://bugzilla.mozilla.org/show_bug.cgi?id=1383063#c15).
Marking as do-not-merge for now, as I have a feeling supporting > IE8 for first-class CSS may not be enough for this one 😩 
https://bugzilla.mozilla.org/show_bug.cgi?id=1386434
TODO

[fix bug 1386434] /new variation for 'unsupported browser' referrals

---

bedrock/mozorg/templates/mozorg/developer/index.html

Updates the DevTools links to point to the redesigned Firefox Developer Edition page instead of MDN. No string changes, just link URLs.
https://bugzilla.mozilla.org/show_bug.cgi?id=1381601

[fix bug 1381601] Link to Dev Edition page from Dev Hub

---

bedrock/firefox/templates/firefox/features/password-manager.html

Updates a string on the Password Manager page to avoid recommending a specific add-on since we can't guarantee its status with the move to WebExtensions. Uses the l10n tag `fxfeature-remove-lastpass`
https://bugzilla.mozilla.org/show_bug.cgi?id=1383843

[fix bug 1383843] Remove LastPass from password manager feature page

---

media/css/firefox/firstrun/onboarding.less

- Fixes an overlapping link issue on `/firstrun` that only effects longer strings on certain locales.
https://bugzilla.mozilla.org/show_bug.cgi?id=1387034
- Testing `de` or `fr` locales should no longer have the issue.

[fix bug 1387034] L10n layout issue on /firstrun page

---

bedrock/firefox/templates/firefox/hub/home.html

Adds CNET article in first position, moves MakeUseOf article to second position, and removes Verge article.
https://bugzilla.mozilla.org/show_bug.cgi?id=1387205

[fix bug 1387205] Update Firefox hub third-party articles

---

bedrock/wordpress/api.py
bedrock/wordpress/models.py
bedrock/wordpress/tests/test_data/posts.json
bedrock/wordpress/tests/test_models.py

* Reset featured_media to empty dict for any problem
* Add tests for failed media fetching
* Catch TypeError in model method to ensure it won't break for users

Ensure failed blog featured_media does not break pages

---

media/js/base/mozilla-notification-banner-init.js
media/js/plugincheck/plugincheck-update.js

Looks like maybe a copy pasta virus. Tricky one to catch in code review, as the bug always resulted in `true` (as the function *does* exist).
https://bugzilla.mozilla.org/show_bug.cgi?id=1388535
Ensure the errors are gone for non-Fx browsers, and that the code still functions as expected in Fx.

[fix bug 1388535] Fix JS error on banner init and plugincheck.

---

bedrock/releasenotes/tests/test_base.py
bedrock/releasenotes/views.py

They were still redirecting to aurora notes, which is now stuck at an old version as well. Sys Requirments redirect had the same problem.

Fix bug 1389178: Dev Edition notes redirect to beta

---

bedrock/security/templates/security/bug-bounty/faq.html
bedrock/security/templates/security/bug-bounty/hall-of-fame.html

update hall of fame to q2 2017 and remove thunderbird from faq

---

bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
bedrock/mozorg/templates/mozorg/internet-health/includes/sub-nav.html
bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
bedrock/mozorg/templates/mozorg/internet-health/web-literacy.html
bedrock/settings/static_media.py
media/css/mozorg/internet-health/health-subpage.scss

Use the common subnav include on health subpages, which gives us the "Openness" text change the bug originally requested while also paying down a little tech debt. This removes some strings from the various subpages.
The common subnav uses the tag `health-june-campaign-updates` but perhaps we have enough coverage now to remove it? https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=mozorg/internet-health/shared.lang
https://bugzilla.mozilla.org/show_bug.cgi?id=1359617

[fix bug 1359617] Change health subpages to standard subnav

---

bedrock/settings/base.py

Just noticed we were not promoting the official German and French Twitter handles, this is fixing it.
Filing a bug to get approval from Liz or Sierra

Update the list of official Twitter accounts

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2017.html
bedrock/mozorg/urls.py

Adds a transparency report for the first half of 2017.
https://bugzilla.mozilla.org/show_bug.cgi?id=1381094
https://bedrock-demo-craigcook.us-west.moz.works/en-US/about/policy/transparency/jan-jun-2017/

[fix bug 1381094] Publish Jan-Jun 2017 transparency report

---

bedrock/base/templates/includes/global-nav.html

Just adds two missing `</div>` tags to the Pocket section of the left-drawer global nav.

Fix unclosed tags in Pocket section of global nav.

---

bedrock/base/templates/includes/global-nav.html
bedrock/firefox/templates/firefox/includes/hub/sub-nav.html

Remove instances of "browser" from global nav and firefox subnav.
https://bugzilla.mozilla.org/show_bug.cgi?id=1391046
==== short test summary info ====
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_change_lang_country
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_get_token
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_get_user_not_found
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_newsletter_no_order
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_newsletter_ordering
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_post_user_not_found
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterVie …

[fix bug 1391046] Remove 'browser' from global/firefox top nav

---

bedrock/mozorg/templates/mozorg/about/leadership.html

Small but urgent update to Mitchell's bio, changing "co-chairs the U.S. Department of Commerce Digital Economy Advisory Board" to the past tense.
https://bugzilla.mozilla.org/show_bug.cgi?id=1391480

[fix bug 1391480] Update to Mitchell Baker’s bio

---

bedrock/base/templates/base-pebbles.html
bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
media/js/base/mozilla-notification-banner-init.js
media/js/base/mozilla-notification-banner-modal-init.js
media/js/base/mozilla-notification-banner.js
tests/unit/spec/base/mozilla-notification-banner.js

Promotes winning copy to the default for site-wide banner and alternate firstrun/whatsnew banner.
https://bugzilla.mozilla.org/show_bug.cgi?id=1388871
Essentially ensure no regressions introduced in terms of banner functionality. Also make sure strings are showing up properly in banners.
**Note that banners will be en-US only while new strings are localized.**
https://www-demo5.allizom.org/en-US/
*banner only has 5% display frequency for `/firstrun` and `/whatsnew`*
https://www-demo5.allizom.org/en-US/firefox/54.0/firstrun
https://www-demo5.allizom.org/en-US/firefox/54.0/whatsnew
1. Download an old version of Fx. 53.0.2 is available [here](https://ftp.mozilla.org/pub/firefox/releases/53.0.2/)
2. Once you have installed / opened the browser, open a new tab and type 'about:config'. Accept …

[fix bug 1388871] Promote update banner winning copy.

---

media/css/firefox/hub/home.scss

Fixes a CSS regression for the main header on /firefox/ at small screen sizes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1392973
- Check responsiveness.
- Check non-en locales with longer strings.
- Check RTL.

[fix bug 1392973] /firefox/ CSS header alignment issues on smaller screens

---

bedrock/foundation/templates/foundation/about.html

Update and sort board members listed on [About the Foundation](https://www.mozilla.org/en-US/foundation/about/) page.
[Bug 1392774](https://bugzilla.mozilla.org/show_bug.cgi?id=1392774)
Just open the page and make sure the list is updated as described in a [bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1392774#c1).

Fix Bug 1392774 - Update copy in https://www.mozilla.org/en-US/foundation/about/

---

bedrock/firefox/templates/firefox/firstrun/onboarding-a.html
bedrock/firefox/templates/firefox/firstrun/onboarding-b.html
bedrock/firefox/templates/firefox/firstrun/onboarding.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/firefox/firstrun/onboarding.less
media/js/firefox/firstrun/experiment-firstrun-copy.js

- Adds an A/B copy test on /firstrun (en-US only).
- Fixes formatting in `onboarding.less`
https://bugzilla.mozilla.org/show_bug.cgi?id=1392473
- Ensure traffic cop experiment works as expected with DNT disabled (each version is set to 5% sample rate)
- Ensure correct variations load for both `?v=a` and `?v=b`.
- Ensure no visual regressions.
Demo:
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/55.0/firstrun/
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/55.0/firstrun/?v=a
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/55.0/firstrun/?v=b

[fix bug 1392473] Copy test on /firstrun page

---

bedrock/firefox/templates/firefox/includes/download-list.html
bedrock/firefox/templates/firefox/new/onboarding/scene1.html
bedrock/firefox/templates/firefox/new/scene1.html
media/css/firefox/new/other-platforms.less
media/js/firefox/new/scene1.js

Updates link messaging for advanced install options and other languages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1386622#c27
Make sure new UX is sane, and old UX (for un-translated locales) isn't broken.
https://www-demo5.allizom.org/firefox/new/

[fix bug 1386622] Update /new strings for advanced installs.

---

bedrock/firefox/templates/firefox/features/independent.html

Correct a wrong statement on [/firefox/features/independent/](https://www.mozilla.org/en-US/firefox/features/independent/), under the "A browser on a mission" section. Requires l10n.
[Bug 1391287](https://bugzilla.mozilla.org/show_bug.cgi?id=1391287)
Just visit the page and make sure the copy is updated properly.

Fix Bug 1391287 - Statement and claim on firefox/features/independent

---

bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html

Adds a section to the CPG about future updates/amendments/modifications. L10n for this page is handled differently than most bedrock pages so we've opted not to wrap the new text in an l10n tag (cc @peiying2)
https://bugzilla.mozilla.org/show_bug.cgi?id=1364268

[fix bug 1364268] Add modification section to participation guidelines

---

bedrock/mozorg/templates/mozorg/about/governance/organizations.html

Updating the [Mozilla Organizations page](https://www.mozilla.org/en-US/about/governance/organizations/). From the bug:
> Not sure who manages this Organizations page, but given the organizational transition is a known fact and mozilla.jp has already been converted to a local community portal site, no one should argue against the edit.
[Bug 1395075](https://bugzilla.mozilla.org/show_bug.cgi?id=1395075)
Just open the page and make sure the paragraph in question is gone.

Fix Bug 1395075 - Remove Mozilla Japan from Mozilla Organizations page

---

bedrock/firefox/templates/firefox/organizations/faq.html

Update the second last section on the [ESR FAQ page](https://www.mozilla.org/en-US/firefox/organizations/faq/). Add the French mailing list, remove the Japanese list, and replace the contact person. I've also used a direct link for the English list to avoid confusion.
[Bug 1395013](https://bugzilla.mozilla.org/show_bug.cgi?id=1395013)
Just visit the FAQ page, and make sure the lists are updated as explained.

Fix Bug 1395013 - Update Firefox ESR mailing list links

---

bedrock/base/templates/includes/global-nav.html

Fixes a minor regression from https://github.com/mozilla/bedrock/commit/15acbe8cb0e25da3719e89587af70d6f4fd21069 wherein the definition for `firefox_url` was removed but we missed the second reference to it further down.
https://bugzilla.mozilla.org/show_bug.cgi?id=1395269
The "Firefox" heading in the subnav flyout should link to /firefox/ (JS overrides that link behavior).

[fix bug 1395269] Broken Firefox link in global nav

---

bedrock/mozorg/templates/mozorg/moss/_alittlebitmore.html
bedrock/mozorg/templates/mozorg/moss/base.html
bedrock/mozorg/templates/mozorg/moss/index.html
bedrock/mozorg/templates/mozorg/moss/mission-partners-india.html
bedrock/mozorg/urls.py

Restoring previously-merged-and-since-reverted content changes for Mission Partners: India program, slated to launch in August 2017.
https://bugzilla.mozilla.org/show_bug.cgi?id=1385645

[fix bug 1385645] Update MOSS pages for Global Mission Partners: India

---

bedrock/mozorg/templates/mozorg/robots.txt
bedrock/settings/base.py

Disallows indexing of all pages in `/etc` app.
https://bugzilla.mozilla.org/show_bug.cgi?id=1395575

[fix bug 1395575] Disallow index of /etc app.

---

bedrock/firefox/firefox_details.py
bedrock/firefox/tests/test_base.py
bedrock/firefox/tests/test_firefox_details.py
media/css/pebbles/components/_buttons-download.scss
media/css/sandstone/buttons.less

The download link of Firefox Nightly for Android is broken due the an Android API update. Firefox 56+ requires Android 4.1 (API 16) instead of Android 4.0.3 (API 15). This PR will fix the issue. This kind of complexity will be solved once Android Nightly gets bouncer URLs :sweat_smile:
Updated the relevant CSS files as well, but I think it's no longer used since all the Android download buttons are currently pointing Google Play.
[Bug 1396550](https://bugzilla.mozilla.org/show_bug.cgi?id=1396550)
* Visit `/firefox/android/nightly/all/` and make sure the ARM download link works properly. The label should say "ARM devices (Android 4.1+)".
* Visit `/firefox/android/beta/all/`. The label should say "ARM devices (Android 4.1+)".
* Visit `/firefox/android/all/`. The label should still say "ARM …

Fix Bug 1396550 - Firefox for Android Nightly is pointing at obsolete api-15 folder

---

bedrock/releasenotes/views.py

I've just removed the 1-hour caching option from the release notes, so the HTML pages will always be up-to-date. Non-Nightly release notes could still be cached, but there's an idea to [provide feeds for those notes](https://bugzilla.mozilla.org/show_bug.cgi?id=1366651) as well.
Adding `@cache_control_expires(1)` to `def nightly_feed` won't solve the issue, because the caching timing of the Atom feed and HTML page won't be the same.
[Bug 1396560](https://bugzilla.mozilla.org/show_bug.cgi?id=1396560)
I think there's no easy way to test the change.

Fix Bug 1396560 - Release notes updates for nightly are published before the HTML page is updated

---

bedrock/firefox/templates/firefox/new/sem/base.html
bedrock/firefox/templates/firefox/new/sem/fast/scene1.html
bedrock/firefox/templates/firefox/new/sem/fast/scene2.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py

- Enables `firefox/new/?xv=fast` for translation
- Checks for lang file `'firefox/new/sem'`
https://bugzilla.mozilla.org/show_bug.cgi?id=1392680
- Check that this deck of cards is still standing (thankfully we have some tests)

[fix bug 1392680] Enable /new/?xv=fast for l10n to support German ad campaign

---

bedrock/firefox/tests/test_views.py

- Adds unit tests to make sure:
- `/firefox/new/` never contains a noindex tag.
- `/firefox/new/?scene=2` always contains a noindex tag.
https://bugzilla.mozilla.org/show_bug.cgi?id=1396623
- Add a noindex to scene1, tests should fail.
- Remove noindex from from scene2, tests should fail.

[fix bug 1396623] Add unit tests for noindex meta tag on /firefox/new template

---

bedrock/firefox/templates/firefox/new/scene1.html
bedrock/firefox/templates/firefox/new/scene2.html
bedrock/firefox/templates/firefox/new/survey.html
bedrock/settings/static_media.py
media/css/firefox/new/common.less
media/js/firefox/new/survey.js

- Adds a survey link to `/firefox/new/` for 100% of en-US audience (as specified in the bug).
- ~**do-not-merge** until I find out if this should be on scene2 also.~
https://bugzilla.mozilla.org/show_bug.cgi?id=1387573
- Make sure survey link displays correctly

[fix bug 1387573] Add user intent survey to /new

---

bedrock/base/templates/macros.html

Updates strings so we can begin supporting SMS in multiple countries. New strings are behind the tag `sendto_updates_bug1395342`
https://bugzilla.mozilla.org/show_bug.cgi?id=1395342

[bug 1395342] Update strings for send-to-device widget

---

bedrock/base/templates/includes/site-footer.html
bedrock/firefox/templates/firefox/australis/firstrun.html
bedrock/firefox/templates/firefox/includes/download-button.html
bedrock/firefox/templates/firefox/products/focus.html
bedrock/thunderbird/templates/thunderbird/includes/download-button.html

In bug  1367183 we agreed to change the anchor text of various privacy policy notices on the site to distinguish them from *marketing content* about privacy.
https://bugzilla.mozilla.org/show_bug.cgi?id=1367183#c11
* Opened several pages that historically had different footers (e.g. homepage, Firefox pages, styleguide pages) and verified content of anchor text in footer
* Opened /firefox/focus/, /firefox/new/, /firefox/, /thunderbird/ pages to verify content of anchor text under download buttons.
=== short test summary info ===
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_change_lang_country
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_get_token
FAIL bedrock/newsletter/tests/test_views.py::TestExistingNewsletterView::test_ge …

[fix bug 1367183] Change anchor text of privacy policy links

---

bedrock/base/templates/includes/global-nav.html
bedrock/firefox/templates/firefox/includes/hub/sub-nav.html

- Adds "Developer Edition" to secondary nav on Firefox
- ~en-US only for now, until we have enough locales translated with the new string.~
https://bugzilla.mozilla.org/show_bug.cgi?id=1391829

[fix bug 1391829] Add Dev Edition to Firefox secondary nav

---

media/js/mozorg/home/home-b.js

Adds final analytics requirements to the new home page. Essentially just adds a handler for the Sync button when *not* wired up to UITour.
https://bugzilla.mozilla.org/show_bug.cgi?id=1392501

[fix bug 1392501] Update Analytics on new en-US homepage.

---

docker/bin/run_integration_tests.sh

Fixes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/71/pipeline
See: #5113 for more context

Pin SauceLabs to Chrome 60 due to outdated chromedriver

---

bedrock/base/templates/macros.html
bedrock/base/templatetags/helpers.py
bedrock/settings/base.py
media/css/base/send-to-device-micro.less
media/css/base/send-to-device.less
media/js/base/send-to-device.js
tests/unit/spec/base/send-to-device.js

This adds a setting for specifying supported countries as they'll be added as support is added in Salesforce.

Fix bug 1400369: Send-to-device widget support multiple countries

---

bedrock/etc/templates/etc/firefox/retention/thank-you-a.html
bedrock/etc/templates/etc/firefox/retention/thank-you-b.html
media/css/etc/firefox/retention/thank-you-b.scss
media/css/etc/firefox/retention/thank-you.scss

Two small changes.
1. Updating a link that was requested. Should be straight forward enough.
2. If the page width is wide enough for thank-you-b https://www.mozilla.org/en-US/etc/firefox/retention/thank-you-b/ the "it's all thanks to you" blerb is no longer centered inside the confetti. The css changes should address this.

Some small changes to FF retention pages in css and a link.

---

bedrock/mozorg/templates/mozorg/home/home-b.html

Adds lang files to the new (en-US only, for now) home page to re-enable the language selector in the footer.
https://bugzilla.mozilla.org/show_bug.cgi?id=1401479
Ensure using the language selector on the en-US homepage sends you to the old home page for any other locale.

[fix bug 1401479] Add lang selector to new home page.

---

bedrock/newsletter/forms.py
bedrock/newsletter/templates/newsletter/includes/form.html
bedrock/newsletter/tests/test_forms.py
bedrock/newsletter/tests/test_views.py
bedrock/newsletter/views.py
media/css/mozorg/home/home-b.scss
media/css/mozorg/home/home.scss
media/css/newsletter/fxnewsletter-subscribe.less
media/css/newsletter/moznewsletter-subscribe.less
media/css/newsletter/newsletter-developer.scss
media/css/newsletter/newsletter-firefox.scss
media/css/newsletter/newsletter-mozilla.scss
media/css/pebbles/components/_newsletter.scss
tests/functional/contribute/test_friends.py
tests/functional/firefox/test_ios_testflight.py
tests/functional/newsletter/test_newsletter_embed.py
tests/functional/newsletter/test_newsletter_landing.py
tests/pages/contribute/friends.py
tests/pages/firefox/ios_testflight.py
tests/pages/newsletter/base.py
tests/pages/regions/newsletter.py

Removes the email format option (HTML/Text) from all newsletter forms (except from the preference center at `/newsletter/existing/`).
https://bugzilla.mozilla.org/show_bug.cgi?id=1396949
Ensure newsletter forms can be submitted successfully, both the standard footer forms and the form at `/newsletter/existing/`.

[fix bug 1396949] Remove format option from newsletter forms.

---

bedrock/base/templates/base-pebbles.html
bedrock/base/templates/base-resp.html
bedrock/base/templates/base.html
bedrock/mozorg/templates/mozorg/home/includes/nav.html
media/css/hubs/_masthead.scss
media/css/mozorg/home/home.scss
media/css/pebbles/components/_masthead.scss
media/css/sandstone/sandstone-resp.less
tests/functional/test_navigation.py
tests/pages/base.py

- Adds a link to `/firefox/` in the old nav, now that the Firefox hub is fully localized.
- This adds the string `"Firefox"`, but should be ok with l10n?
https://bugzilla.mozilla.org/show_bug.cgi?id=1399173
- Make sure i didn't miss any other occurences of the old nav template?

[fix bug 1399173] Add link to /firefox/ in the old site navigation

---

docs/javascript-libs.rst
docs/mozilla-lazy-load.rst
docs/mozilla-notification-banner.rst

- Adds docs for both `mozilla-lazy-load.js` and `mozilla-notification-banner.js`
None
- Check for typos, make sure docs compile ok?

Add docs for JS lazy-load and notification libs

---

bedrock/firefox/templates/firefox/features/base.html
bedrock/firefox/templates/firefox/features/send-tabs.html
bedrock/firefox/templates/firefox/features/sync-old.html
bedrock/firefox/templates/firefox/features/sync.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/urls.py
bedrock/firefox/views.py
media/css/firefox/features/sync.scss
tests/functional/firefox/features/test_features.py

- Updates `features/sync` and `features/send-tabs` pages with more prominent CTA's.
- **Do not merge** until we confirm GA is all working as expected.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1393549
- https://bugzilla.mozilla.org/show_bug.cgi?id=1393548
Demo:
- https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/features/sync/
- https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/features/send-tabs/
CTA states to test:
- Firefox signed into Sync (shows mobile buttons, custom header)
- Firefox signed out of Sync (shows create account button)
- Non-Firefox (shows download button)
- Firefox for iOS (shows SUMO link, custom header)
- Firefox for Android (shows SUMO link, custom header)
- Old Firefox (v < 31) (shows update firefox link)
Also test to make sure there are …

[fix bug 1393549, bug 1393548] Update Sync and Send Tabs feature pages

---

tests/functional/firefox/test_developer.py

The new page is behind a switch and makes testing problematic until it's in production. We'll just skip the test temporarily and update after Tuesday.

[bug 1396029] Skip functional test until we can remove the switch

---

bedrock/firefox/views.py

Somewhere along the way we got redundant tags for both "private" and "privacy." This sets "privacy" as the One True Tag and we'll re-tag any previous blog posts.
https://bugzilla.mozilla.org/show_bug.cgi?id=1402029

[fix bug 1402029] Standardize ‘privacy’ tag for blog feeds

---

bedrock/etc/templates/etc/firefox/retention/thank-you-a.html
bedrock/etc/templates/etc/firefox/retention/thank-you-b.html

Analytics tagging for the CTA links on the new FF Retention pages.
https://www.mozilla.org/en-US/etc/firefox/retention/thank-you-a/
https://www.mozilla.org/en-US/etc/firefox/retention/thank-you-b/
https://bugzilla.mozilla.org/show_bug.cgi?id=1402113

Firefox Retention pages, updating links for metrics.

---

bedrock/mozorg/templates/mozorg/book.html

Update the Book of Mozilla to include the new verse heralding the release of Firefox 57 (bug 1370613).

Fix bug 1401708: The Beast awakens

---

bedrock/firefox/urls.py

- Quantum preview page is [now live](https://www.mozilla.org/en-US/firefox/quantum/), so this is a PR to tidy up and remove the switch that's no longer needed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1396005
- Page should still load as expected.

[bug 1396005] Remove switch for Quantum preview page

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-56.html
media/css/firefox/whatsnew/whatsnew-56.scss

- Adds a link to `/firefox/quantum/` on the `/whatsnew` 56 page for both English and German locales only.
- Reuses "Learn more" string that is already translated.
- **Do not merge** until the quantum page is live.
https://bugzilla.mozilla.org/show_bug.cgi?id=1401308
- Ensure no visual regressions.
- Ensure link shows for only English and German locales.

[fix bug 1401308] Add 'Learn more' link for /firefox/quantum/ to whatsnew 56

---

bedrock/privacy/templates/privacy/notices/firefox-quantum.html

https://github.com/mozilla/bedrock/pull/5131/files#diff-1df9cc4f76b0aaabd6c07634c259aec0R29 introduced an error in production when the footnote did not exist. This PR handles that situation.

Handle empty footnote in quantum privacy notice

---

bedrock/firefox/templates/firefox/quantum.html

The [Quantum landing page](https://www.mozilla.org/firefox/quantum/) is only offered in English and German, so people get there from the blog post, other media articles, etc. cannot download the Beta build in their language. This PR instead uses a language neutral link to workaround the issue for the time being.
[Bug 1403443](https://bugzilla.mozilla.org/show_bug.cgi?id=1403443)
Just make sure the "Or try beta" link has no locale.

Fix Bug 1403443 - Firefox Quantum page is promoting only en-US and de builds

---

bedrock/firefox/templates/firefox/quantum.html

- Updates blog links on `/firefox/quantum/` page for `de` locale.
https://bugzilla.mozilla.org/show_bug.cgi?id=1402927
- Check correct links are shown the both en-US and de.

[fix bug 1402927] Update Quantum blog links for German locale

---

bedrock/privacy/views.py

Prevents errors when loading old format of Firefox privacy policy
No issue
Using /en-US/privacy/firefox/ should load new template using /hu/privacy/firefox/ should load old template with old privacy policy

Conditional use new or old template for Firefox privacy policy

---

bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/tests/test_helper_misc.py
bedrock/releasenotes/models.py
bedrock/releasenotes/tests/test_base.py
bedrock/releasenotes/tests/test_models.py
bedrock/releasenotes/views.py
bedrock/thunderbird/templates/thunderbird/releases/release-notes.html

* Add ability to get release notes URL to Release model.
* Add Release instance to Note for fixed_in_release property.

Fix error in thunderbird release notes template

---

bedrock/privacy/redirects.py
bedrock/privacy/templates/privacy/archive/hello-2014-11.html
bedrock/privacy/templates/privacy/archive/hello-2016-03.html
bedrock/privacy/templates/privacy/index.html
bedrock/privacy/templates/privacy/notices/firefox-cloud.html
bedrock/privacy/urls.py
bedrock/releasenotes/tests/test_models.py

As requested in the bug, all traffic to '/privacy/firefox-cloud/' should be redirected to '/privacy/firefox/'
https://bugzilla.mozilla.org/show_bug.cgi?id=1394042
Requests for '/privacy/firefox-cloud/' should redirect to '/privacy/firefox/'

Fix Bug 1394042, redirect cloud services pn to Fx pn

---

bedrock/releasenotes/models.py
bedrock/releasenotes/tests/test_models.py

Was getting IndexError trying to get the first item in an empty list because we were not checking for an empty list after filtering out non-public releases in the equivalent_release_for_product method.

Fix exception when equavalent releases exist but none are public

---

docker/bin/run_integration_tests.sh
jenkins/branches/prod.yml
jenkins/branches/run-integration-tests.yml

Fixes #5156
SauceLabs ended support for Windows XP (IE6 & IE7) last night: https://wiki.saucelabs.com/pages/viewpage.action?pageId=70068108
IE8 on Windows 7 is now the oldest IE they support, so this PR moves sanity tests to run with this specific configuration.
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/80/pipeline/

Run sanity functional tests in IE8

---

docker/bin/run_integration_tests.sh
tests/functional/test_home_old.py
tests/pages/contact.py
tests/pages/home_old.py

- Ensures we continue running existing tests against the old home page (de).
- Adds a new baseline test for the current (en-US only) home page.
- Also un-pins Chrome 60, now fixing #5113 
https://bugzilla.mozilla.org/show_bug.cgi?id=1402421
https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/81/pipeline

[fix bug 1402421] Update functional tests for the new homepage

---

media/css/firefox/firstrun/firstrun.less

@pmac
On windows, when arriving on the page there is a scroll bar on the right, that bar disappears once the animation starts. This was because the button on the page was not positioned until the animation starts.
So, I moved the styles to position the button outside of the styles for the animation.
https://bugzilla.mozilla.org/show_bug.cgi?id=1402131
note: 
Once the fxa container is visible, if the screen is small, the scroll bar will come back - this is necessary to allow the user to scroll along the fxa form. I noticed that `notification-banner.css` adds a `margin-bottom` of 100px on the `#fxa-iframe-config` element. this makes the scroll bar appear a little earlier than necessary, but I figured this is being used for something I am unaware of - so I did not touch it.

remove scroll bar from windows re: Bug 1402131

---

bedrock/base/templates/includes/canonical-url.html

Hoping this helps. Does seem like an omission.

Fix bug 1405107: Add an en-US entry to alternet hreflang tags

---

bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
media/js/base/send-to-device.js

This is so the SMS infra can pick the proper message that is deliverable in said country and language.

Bug 1400369: Send-to-device sends country and language when available

---

media/css/privacy/firefox-privacy.scss

* Pick up https://github.com/mozilla/legal-docs/pull/951 and the subsequent PRs that makes the word **Firefox** always bold in all locales
* Fix spaces between the logo and text, and the text and time accordingly
* Shorten the title's width which could be longer in some locales, notably **ru**
* Fix RTL layout as well
N/A
Visit the **cs**, **es-ES**, **id**, **pt-BR** and **ru** locale pages, and make sure the layout looks good.

(no bug) Fix title format on localized Firefox Privacy Notice

---

bedrock/releasenotes/models.py
bedrock/releasenotes/tests/test_models.py

Currently for example /firefox/notes/ could redirect to the latest Firefox for Android if it were newer.

Fix wrong product returned for latest notes

---

media/js/firefox/new/survey.js

- Adjust sample rate limit of existing Firefox survey on /new from 25% to 5% (survey is getting more responses than needed currently).
https://bugzilla.mozilla.org/show_bug.cgi?id=1387573#c26

[fix bug 1387573] Adjust sample rate limit for firefox/new/ survey

---

bedrock/firefox/templates/firefox/firstrun/cliqz-funnelcake-119-122.html

- German funnelcake pages are not shown correctly on staging: https://www.allizom.org/de/firefox/56.0/firstrun/?f=120. You can replicate this locally with `Dev=False`
- Set `Dev=False` and the pages should display as expected.

[bug 1392855] Add firstrun lang file to Cliqz funnelcake experiment pages

---

media/js/base/mozilla-notification-banner-modal-init.js

- We've had a couple of reports of users seeing the out-of-date notification banner on /whatsnew when updating to Firefox 56. On both occasions, their UA string has turned out to be incorrect. Fresh profiles seem to fix things, so it could well be due to a rouge extension. This change switches to using UITour instead of the the UA string, which should give us more accurate client information.
https://bugzilla.mozilla.org/show_bug.cgi?id=1406299
- Verify that the banner on /whatsnew is still shown only to Firefoxen 2 major versions out of date or more.

[fix bug 1406299] Update banner on /whatsnew should query UITour to avoid incorrect UA strings

---

bedrock/firefox/redirects.py
tests/redirects/map_globalconf.py

Fix Android notes missing due to a catch-all redirect recently added in [Bug 1405436](https://bugzilla.mozilla.org/show_bug.cgi?id=1405436) / #5176. Redirect those URLs to the relevant release notes instead of the product home page.
[Bug 1406766](https://bugzilla.mozilla.org/show_bug.cgi?id=1406766)
Make sure all of these URLs work properly.
* `/firefox/android/55.0` ->  `/firefox/android/55.0/releasenotes/`
* `/firefox/android/56.0/releasenotes/`
* `/firefox/android/57.0beta/releasenotes/`

Fix Bug 1406766 - Firefox for Android notes are missing

---

bedrock/firefox/templates/firefox/channel/android.html
bedrock/firefox/templates/firefox/channel/desktop.html

Update the links from the [channel](https://www.mozilla.org/en-US/firefox/channel/desktop/) page to /all/ pages since the 64-bit version is now default. Also use the term "platforms" instead of "builds" to be consistent with the [/new/](https://www.mozilla.org/en-US/firefox/new/) page. So this basically replaces "**All Languages and Builds (incl. Win 64)**" with "**All Languages and Platforms**" (which I think was the original copy.)
This Requires a l10n update, but we can use "All Languages and Builds" as the fallback string, which has already been used on the Android channel page.
[Bug 1387466](https://bugzilla.mozilla.org/show_bug.cgi?id=1387466)
Just visit the channel page and make sure the new link copy is displayed.

Fix Bug 1387466 - Adjust download page strings to remove "(incl. Win 64)" now that Win64 builds are default on all channels

---

bedrock/firefox/templates/firefox/new/scene1.html
bedrock/settings/static_media.py
media/js/firefox/new/experiment-unbranded-search-funnelcakes.js

Adds funnelcakes for unbranded search experiment. en-US locale/US geo only, so should not conflict with de only Cliqz funnelcakes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1406139
Ensure experiment works as expected - 30% chance of a funnelcake when using Windows/non-Fx with DNT disabled.

[fix bug 1406139] Add unbranded search funnelcake experiment.

---

media/css/privacy/firefox-privacy.scss

In some locales, notably French, the constricted `max-width` of the content is causing the Choose button to overlap the text. I always felt that `600px` was going to be to narrow, so here I extended it to `700px` and tested `en`, `fr`, `de`, `it` and there is now enough breathing room.
https://bugzilla.mozilla.org/show_bug.cgi?id=1407349
Ensure that the Choose button does not overlap the text in various locales, most notably Franch.

Fix Bug 1407349, expand max-content to prevent choose button from overlapping text

---

bedrock/firefox/templates/firefox/products/developer-quantum.html

In #5143 I missed that the change was not only a final period, but also an added 'the'. Can we use the same description in all 3 pages (landing, whatsnew, firstrun)? We're currently showing the description untranslated on the landing page.

[no bug] Use same string as page description for Dev Edition

---

bedrock/privacy/templates/privacy/base.html

Removes tabzilla from localized versions of the new privacy pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1404301
Load `/de/privacy/firefox/` and resize the window down to mobile sized viewport. The Tabzilla wordmark should no longer obscure the Mozilla logo.

[fix bug 1404301] Remove Tabzilla from new Firefox Privacy Policy

---

bedrock/firefox/forms.py
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py

This removes the form validation that I failed to remove before.  It also enables the proper message when basket says that the number is invalid.

Bug 1395342: Send to device number field not US only

---

bedrock/firefox/templates/firefox/firstrun/membership-b.html
media/js/firefox/firstrun/membership.js

- Updated skip link on /firstrun membership experiment.
https://bugzilla.mozilla.org/show_bug.cgi?id=1392860#c70
- Link should now load `about:home` instead of the newsletter page.

[fix bug 1392860] Update skip link on /firstrun membership experiment

---

bedrock/firefox/templates/firefox/firefox-quantum.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/settings/static_media.py
media/css/firefox/components/_buttons.scss
media/css/firefox/quantum-landing.scss
media/js/firefox/quantum-landing.js
tests/functional/firefox/test_home.py
tests/functional/newsletter/test_newsletter_embed.py

Updates the /firefox page to mirror the current /firefox/quantum with additional copy updates.
https://bugzilla.mozilla.org/show_bug.cgi?id=1405076
Ensure that is switch is not enabled the current content hub version of the page is shown.

Fix Bug 1405076, firefox landing page layout and content updates

---

media/js/base/mozilla-client.js
media/js/base/mozilla-notification-banner-init.js
media/js/base/mozilla-notification-banner-modal-init.js
tests/unit/spec/base/mozilla-client.js

- Sets site wide notification to only trigger if at least 2 major versions out of date.
- Also moves logic to a shared function and adds unit tests.
https://bugzilla.mozilla.org/show_bug.cgi?id=1389676
- Notification should only show for Firefoxes 2 major releases old or less.

[bug 1389676] Trigger notification  if 2 major versions out of date

---

media/js/base/mozilla-client.js
media/js/base/mozilla-notification-banner-init.js
media/js/base/mozilla-notification-banner-modal-init.js
tests/unit/spec/base/mozilla-client.js

@jpetto sorry - I read through my commit after it merged and thought I could have made my comments / logic a little clearer. Sorry to bug you again on this, but hopefully this reads a bit nicer than it did originally.

[bug 1389676] Update client logic for isFirefoxOutOfDate()

---

bedrock/mozorg/templates/mozorg/home/home-new.html
bedrock/mozorg/templates/mozorg/home/home.html

Change the Servo link on the [home page](https://www.mozilla.org/), located under Our innovations.
[Bug 1401039](https://bugzilla.mozilla.org/show_bug.cgi?id=1401039)
Visit the home page and make sure the Servo link goes to the new landing page on Mozilla Research.

Fix Bug 1401039 - /home Servo link change

---

media/css/mozorg/mission.less

The newsletter form on the [mission](https://www.mozilla.org/en-US/mission/) page doesn't look good on mobile. Copy a portion of CSS from `about.less` to solve the issue. Other pages using this style have no problem.
[Bug 1408501](https://bugzilla.mozilla.org/show_bug.cgi?id=1408501)
Visit `/mission/`, switch to the responsive mode, and make sure the icon is not overlapping with the copy.

Fix Bug 1408501 - Newsletter signup on mission page has overlapping image at phone size
