- etc/httpd/global.conf
Added locales: pl, sr, sv-SE, tr
> Bug 1115066 - Add more locales to Thunderbird start page redirect

- bedrock/firefox/tests/test_base.py
- bedrock/mozorg/forms.py
- bedrock/mozorg/templates/mozorg/partnerships.html
- bedrock/mozorg/views.py
- media/css/mozorg/partnerships.less
- media/css/sandstone/sandstone-resp.less
- media/js/mozorg/partnerships.js
Tested that information is going through to Salesforce as expected (both with and without new fields).
> Add extra fields for users interested in Tiles. Bug 1110147.

- etc/httpd/global.conf
Do not merge until #2406 goes live to avoid a potential conflict.
> Fix Bug 1110927 - 301 redirect legacy pages that are 404ing

- bedrock/firefox/templates/firefox/new.html
- bedrock/settings/base.py
- media/css/firefox/new.less
- media/js/firefox/new.js
- Add minor JS optimizations.
- Remove GA experiment snippet (no longer used).
> Add refresh button to /firefox/new/. Bug 1027318.

- etc/httpd/global.conf
Fix pushed to demo4: https://www-demo4.allizom.org/firefox/releases/whatsnew/
> Fix bug 1014823 redirect

- etc/httpd/global.conf
> [fix bug 1121082] Redirect /hello to /firefox/hello

- bedrock/firefox/views.py
Received a request to display the video on all Spanish variants.
Not sure if a) need a bug for this b) there are smarter ways to do it
> Bug 1121096 - Hello product page: display video for all Spanish variants

- bedrock/firefox/templates/firefox/hello/start.html
> [fix bug 1120725] Update link for users with no Hello target

- bedrock/mozorg/helpers/download_buttons.py
- bedrock/mozorg/tests/test_helper_download_buttons.py
- media/css/sandstone/buttons.less
- media/js/base/site.js
This needs to be merged this Friday, January 16. Do not merge before that, or links will be broken.
> Fix Bug 1118339 - Update https://www.mozilla.org/en-US/firefox/channel/#aurora for Android ARM links to reflect new FTP directory changes

- bedrock/mozorg/templates/mozorg/home/home-new.html
- media/css/mozorg/home/home-promo.less
This is for the small Advocacy promo, which has limited space and some languages have long words (de and nl so far). We can keep this PR open for a while and add more locales as they arise.
> Bug 1112324 - updates to privacy day home promo

- docs/uitour.rst
- media/js/firefox/australis/australis-uitour.js
Please see: https://bugzilla.mozilla.org/show_bug.cgi?id=1124628
> [fix bug 1124628] Remove pinned tab APIs from UITour lib & docs

- bedrock/privacy/templates/privacy/privacy-day.html
>  Bug 1109318 Update GA campaign for Privay Day

- bedrock/styleguide/templates/styleguide/identity/marketplace-color.html
* Changes the hex value for the color 'Marketplace Light Blue' to #0095DD
> Fixes Bug 1122937 - Errornous hex color value

- media/js/firefox/hello/index.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1127120
> [fix bug 1127120] Add GA events for download/update buttons

- bedrock/foundation/templates/foundation/mocosc.html
This page is not localized yet, so no need to wait l10n.
> Fix Bug 1129130 - Hyperlinking bios to Steering Committee page

- bedrock/firefox/templates/firefox/tiles.html
@flodolo does this work for you?
> Fix Bug 1124724 - Tiles product page update copy mozilla.org/en-US/firefox/tiles/

- media/js/test/karma.conf.js
- media/js/test/spec/browser-tour.js
Added some base tests for `browser-tour.js`
> [no bug] Add test suite for browser-tour.js

- AUTHORS
- CONTRIBUTING.md
Just thought it was a good idea.
> Encourage use of humans.txt

- bedrock/gigabit/templates/gigabit/apply.html
- bedrock/gigabit/templates/gigabit/gigabit.html
- bedrock/gigabit/templates/gigabit/terms.html
Also clean up a couple of date cache busters.
> Fix bug 1132317: Fix gigabit pages errors.

- bedrock/shapeoftheweb/templates/shapeoftheweb/main.json
Syncs copy content. r? @pmclanahan @ckprice
> Syncing content with Google doc, part of the l10n hand-over

- bedrock/mozorg/forms.py
- bedrock/settings/base.py
Travis CI builds are failing due to these errors, affecting several PRs.
> Fix pep8 errors: W503 line break before binary operator

- bedrock/base/templates/base-resp.html
- bedrock/base/templates/base.html
As recommended on http://humanstxt.org/.
> Add author link tag to base templates for humans.txt

- bedrock/firefox/templates/firefox/hello/start.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- docs/uitour.rst
- media/js/firefox/hello/start.js
* Send Custom Variable to GA containing the referral
* Add referral to localStorage on copy/email link
* Retreve referral from localStorage on tour connect and send to GA
* Hide info panels when Contacts tab is clicked (it's okay that they don't see it if they switch back to Rooms)
* Update docs
https://bugzilla.mozilla.org/show_bug.cgi?id=1130198
> [fix bug 1130198] Update Hello FTU for GA36

- bedrock/firefox/templates/firefox/includes/mwc_2015_schedule.html
- bedrock/firefox/templates/firefox/os/mwc-2015-preview.html
These changes were requested via email from John Bernard. Not filed in a bug (yet?).
> Bug 1120689 Last minute MWC preview text tweaks

- bedrock/mozorg/templates/mozorg/about/governance/organizations.html
This page has not been localized so we don't have to wait l10n.
> Fix Bug 1132835 - 404 linking to /contribute/local from /about/governance/organizations

- media/js/privacy/privacy.js
> Fix Bug 1136224 - firefox hello privacy policy link to tokbox privacy policy broken

- bedrock/settings/base.py
> Moves mustache out of the bundle and into the page

- media/js/firefox/hello/index.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1130194
@jpetto r?
> [fix bug 1130194] Add FTU tracking to Hello product page

- bin/update-scripts/dev/update-dev-django.sh
- bin/update-scripts/dev/update-dev-locale.sh
- bin/update-scripts/dev/update-dev-php.sh
- etc/cron.d/bedrock-dev.tmpl
Also fix dev chief autodeploy script.
> Fix bug 1136559: Add dev deploy cron scripts to repo.

- media/css/firefox/new.less
- media/css/newsletter/ios.less
Tweak for spacing around list on firefox/new @breakMobileLandscape and some text sizing tweaks to the subscribe form to avoid zooming in iOS.
> Bug 1126578: iOS CTA updates and newsletter

- media/css/firefox/family-nav.less
- media/js/firefox/family-nav.js
- Provide <= IE 8 fallback for tertiary nav button
- Remove sticky nav from <= IE 8.
> Bug 1135092. Add small IE fixes to fx family nav v1.

- bedrock/firefox/firefox_details.py
- bedrock/firefox/templates/firefox/all.html
- bedrock/firefox/tests/test_base.py
- bedrock/mozorg/helpers/download_buttons.py
- bedrock/mozorg/templates/mozorg/download_firefox_button.html
- bedrock/mozorg/tests/test_helper_download_buttons.py
- media/css/firefox/all.less
- media/css/sandstone/buttons.less
- media/js/base/site.js
- media/js/test/spec/site.js
Windows 64 builds are coming Friday, Feb 27.
> Fix Bug 1126837 - Make Fx38 Win64 build of Dev Edition Available on moz.org

- bedrock/mozorg/templates/mozorg/about/leadership.html
Reusing the original bug as reference.
> Bug 1134522 - Leadership page, fix string not properly wrapped

- bedrock/shapeoftheweb/templates/shapeoftheweb/main.json
> Fix Bug 1126417, made content updates for shape of the web

- bedrock/shapeoftheweb/templates/shapeoftheweb/main.json
@ckprice r? This is for point 1 of https://bugzilla.mozilla.org/show_bug.cgi?id=1133089
> Fix Bug 1133089, remove last three lines of legend text

- bedrock/styleguide/templates/styleguide/websites/sandstone-tabzilla.html
- root_files/humans.txt
Trying to get involve for the first time by taking and fixing this [bug 1135711](https://bugzilla.mozilla.org/show_bug.cgi?id=1135711)
> Fix bug 1135711 - Garbled sentence in Tabzilla page of the style guide

- bedrock/firefox/templates/firefox/includes/family-nav.html
- etc/httpd/global.conf
- media/css/firefox/family-nav.less
and redirect /mwc/ to /firefox/partners/
> Bug 1142583 Remove MWC from fx family nav

- bedrock/foundation/templates/foundation/trademarks/list.html
@alexgibson oh yes its a one line PR!
> Fix Bug 1143911: Add MDN Conference To List Of Trademarks.

- bedrock/styleguide/templates/styleguide/identity/firefox-family-platform.html
This fixes bug as seen on [bugzilla-1135705][1]. 
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1135705
> Fix Bug 1135705

- bedrock/firefox/templates/firefox/android/index.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1148468
> [fix bug 1148468] Update video link on Android page

- etc/httpd/global.conf
Oops! Missed this in PR #2861.
> Bug 1108828 - /b/ redirect for heartbeat pages

- etc/httpd/global.conf
> Bug 1148127 - fix redirects for product page

- bedrock/firefox/templates/firefox/sync-old.html
- bedrock/settings/base.py
- media/css/firefox/family-nav.less
- media/css/firefox/sync-old.less
- media/js/firefox/sync-old.js
- Bug 1150558. Padding/spacing on desktop subnav items.
> Bug 1151355. Fx family nav on old sync pages.

- bedrock/firefox/templates/firefox/os/_get_device.html
- bedrock/firefox/templates/firefox/os/devices.html
- media/js/firefox/os/partner_data.js
- Remove sv availability from ZTE Open II.
- Add sv availability to Alcatel OTF C.
- Update sv purchase link.
> Bug 1151927. Update FxOS El Salvador availability.

- bedrock/base/templates/macros.html
- media/css/firefox/family-nav.less
- media/js/firefox/family-nav.js
- Fix overlapping when clicking V2 top level items
- Fix overlapping when hovering then tab focusing
> Bug 1150567. Fix fx family nav text overlap.

- bedrock/mozorg/templates/mozorg/home/home-new.html
Uses the waffle switch "patriot-act-home-promo"
> Fix bug 1152159 - Add Patriot Act Section 215 home promo

- media/js/plugincheck/check-plugins.js
> Fix Bug 1112277, stop using jsonp with plugincheck

- bedrock/mozorg/templates/mozorg/plugincheck.html
- media/js/plugincheck/check-plugins.js
@alexgibson Fixed the branch name to point to the bug so, merging here and will close the previous pull request.
> Marks outdated plugins as outdated not vulnerable

- media/js/base/global.js
- media/js/plugincheck/check-plugins.js
- media/js/test/spec/global.js
> Fix Bug 1153588, support SeaMonkey on plugin check

- bedrock/foundation/templates/foundation/mocosc.html
Removed Li Gong, added a link to Jim Cook's bio.
> Bug 1159845 - update Foundation Steering Committee page

- bedrock/firefox/templates/firefox/hello/index.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1153316
> [fix bug 1153316] Remove WebRTC link

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
> Bug 1108828 - change parameter name for heartbeat pages

- media/css/firefox/family/index.less
- media/css/sandstone/lib.less
- Use mixin on firefox family landing page.
> Add aurora-bars mixin.

- etc/httpd/global.conf
> Fix Bug 1162669 - Thunderbird latest sysreq/relnotes links are redirected to website-archive

- media/css/mozorg/home/home.less
- media/css/sandstone/sandstone-resp.less
- media/css/sandstone/sandstone.less
https://bugzilla.mozilla.org/show_bug.cgi?id=519530
> Bug 519530 Adding/updating visited link color.

- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
This update just added some data to the html page for
> updating bug bounty hall of fame for Q1 2015 and Q4 2014

- bedrock/firefox/templates/firefox/hello/index.html
- media/css/firefox/hello/index.less
- media/js/firefox/hello/index.js
- Add "Try Hello" CTA to sticky nav.
> Bug 1160212. Fix Hello animation for high-res Android.

- media/js/base/global.js
- media/js/plugincheck/check-plugins.js
- media/js/test/spec/global.js
> Fix Bug 1161938, support other Gecko based browsers

- media/css/sandstone/buttons.less
@alexgibson - Gimme the points!!
> Add flat green button style.

- etc/httpd/global.conf
Needed for 38.0.5beta release notes.
> Allow double dot beta release notes: fix bug 1163979

- .travis.yml
Just found out about this. Should reduce our failures due to network glitches.
> Use travis_retry for all actions requiring network access.

- bedrock/mozorg/templates/mozorg/contribute/friends.html
- media/css/mozorg/contribute/friends.less
> Fix Bug 1164216, add video to wom page and small other tweaks

- bedrock/lightbeam/templates/lightbeam/about.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1162886
> Bug 1162886 - remove things that have been removed from the add-on

- media/css/base/mozid-modal.less
Minor tweak to moz-id modal header styling, as per https://bugzilla.mozilla.org/show_bug.cgi?id=1136937#c27
> Update mozid modal header sizing

- bedrock/firefox/templates/firefox/os/_get_device.html
- bedrock/firefox/templates/firefox/os/devices.html
- media/js/firefox/os/partner_data.js
Both countries do indeed have the same purchase URL.
This needs to go out today.
@alexgibson or @sgarrity r?
> Bug 1166324 fxos orange klif cameroon

- bedrock/mozorg/templates/mozorg/contentservices/about.html
- bedrock/mozorg/templates/mozorg/contentservices/faq.html
- bedrock/mozorg/templates/mozorg/contentservices/index.html
- bedrock/mozorg/templates/mozorg/contentservices/start.html
- bedrock/mozorg/templates/mozorg/contentservices/tiles.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1168159
> Bug 1168159 - Copy changes to Content Services site

- media/js/firefox/new.js
> [fix bug 1164295] Add pixel to /new for downloads

- bedrock/firefox/templates/firefox/desktop/index.html
- media/css/firefox/desktop/index.less
- media/js/firefox/desktop/common.js
- media/js/firefox/desktop/index.js
- Also a little JS linter cleanup.
> Bug 1156877. Fx desktop up-to-date message.

- contribute.json
contributebot mentions the first 3 in its message.
> Reorder contribute.json IRC contacts.

- bedrock/firefox/templates/firefox/personal.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1171493
> [bug 1171493] Add Optimizely to firefox/personal

- tests/functional/plugincheck.js
- tests/lib/config.js
- tests/lib/helpers.js
> Adds functional tests for /plugincheck

- bedrock/security/templates/security/base.html
- bedrock/security/templates/security/bug-bounty.html
- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
- bedrock/security/templates/security/client-bug-bounty.html
- bedrock/security/templates/security/web-bug-bounty.html
- bedrock/security/urls.py
I have added a couple new pages and expanded the pages to the current bug bounty program. This includes new payouts, links to the hall of fame, and clarification on requirements.
> Updating bug bounty pages with changes to program

- docs/index.rst
- docs/testing.rst
- package.json
- tests/config.json
- tests/functional/android.js
- tests/functional/family-nav.js
- tests/functional/firefox-new.js
- tests/functional/firefox-os-devices.js
- tests/functional/firefox-os.js
- tests/functional/home.js
- tests/functional/plugincheck.js
- tests/lib/config.js
- tests/lib/helpers.js
This is now working locally and also running successfully on Travis while pointed at dev.
I still need to figure out a way to get Travis to start up a local bedrock server to point Casper at, so we can test against changes in PR's instead of what's already on dev.
> Add CasperJS functional test suite

- bedrock/foundation/templates/foundation/mocosc.html
- bedrock/mozorg/templates/mozorg/about/leadership.html
Removing Andreas Gal, promoting David Bryant
> Fix bug 1174786 - updates to leadership and steering committee pages

- tests/functional/newsletter.js
@alexgibson r? Not 100% sure the way I am testing form submission 'fail' when validation fails but hey, that is what pull requests are for right ;)
> Add functional tests for newsletter page

- bedrock/mozorg/templates/mozorg/plugincheck.html
@flodolo r? I took a stab at this, did I understand what you meant correctly? Thanks!
> Fix Bug 1175439, cleanup l10n tags on plugincheck page

- tests/functional/firefox-personal.js
- tests/lib/config.js
> Adds tests for the Firefox personal page

- media/js/firefox/sync.js
Some fallout from the huge GTM migration PR :(
> [fix bug 1177810] get started with sync button does nothing

- tests/functional/firefox-products.js
> Add functional tests for products page

- tests/functional/contribute.js
> Adding functional tests for the community landing page

- tests/functional/firefox-sync.js
- tests/lib/config.js
> Adding functional tests for Firefox Sync

- media/js/base/global.js
- media/js/mozorg/contribute/contribute-2015-ga.js
- media/js/mozorg/contribute/contribute-faces.js
- media/js/newsletter/form.js
Marking as DNM for now, as needs testing on a demo server
> [fix bug 1174838] Update mozilla.org form tracking

- media/css/firefox/family/index.less
This is ready, please review, I didn't file a bug because it's a small issue
> Fix the title in the product page for RTL

- tests/unit/karma.conf.js
@alexgibson r? A small oversight I also missed ;p
> Remove junit as reporter from karma.conf

- tests/functional/contact.js
- tests/functional/home.js
- tests/lib/config.js
- tests/lib/helpers.js
> Up the Casperjs waitTimeout to avoid test timeouts

- media/css/mozorg/mission.less
This is ready, please review, I filled a bug here #1180553
> [RTL] Mission Page doesn't support the RTL direction

- bedrock/mozorg/templates/mozorg/plugincheck.html
> Fix Bug 1183598, remove flash warning from plugincheck page

- media/js/plugincheck/lib/plugincheck.js
- tests/unit/spec/plugincheck/lib/plugincheck.js
> Fix Bug 1183558, audit plugincheck code and add additional unit tests

- docs/uitour.rst
I still need to verify that this is indeed all correct before merging.
> Update UITour documentation for Firefox 40

- tests/functional/contribute-friends.js
> Add functional test for Firefox Friends page

- tests/functional/contribute-events.js
> Adds functional tests for the community events page

- tests/functional/contribute-stories.js
@alexgibson r? Here I combined the tests for https://www.mozilla.org/en-US/contribute/stories/ and individual community member pages such as /contribute/stories/shreyas/ into one test suite as they are essentially the same page.
> Casper tests contribute stories

- bedrock/mozorg/templates/mozorg/contribute/contribute-tasks-survey.html
With some conditional messaging on the survey page.
> Bug 1168359 - contribute A/B test copy tweaks

- media/css/base/mozilla-share-cta.less
- media/css/l10n/az/intl.css
- media/css/l10n/el/intl.css
- media/css/l10n/ga-IE/intl.css
- media/css/l10n/gd/intl.css
- media/css/l10n/tr/intl.css
We still have to figure out locales need to be updated. So this is WIP. DO NOT MERGE.
> Fix Bug 1174423 - Disable font-variant: small-caps for ga-IE, evaluate exclusion of other locales

- bedrock/mozorg/templates/mozorg/contribute/signup.html
@craigcook @alexgibson r? See comments here for more:
https://bugzilla.mozilla.org/show_bug.cgi?id=1185475#c1
> Fix Bug 1185475, ensure all fields are implcitly or explicitly associated a11y

- media/js/mozorg/contribute/contribute-2015.js
- tests/functional/contribute-signup.js
> Fix Bug 1185457, remove required attrbiute from field when selection changes and container collapse

- bedrock/mozorg/forms.py
- media/css/mozorg/contribute/contribute-2015.less
- media/js/mozorg/contribute/contribute-2015.js
> Fix Bug 1185468, set country as required and style as other required fields when state is invalid

- bedrock/mozorg/templates/mozorg/contribute/signup.html
- media/css/mozorg/contribute/contribute-2015.less
- tests/functional/contribute-signup.js
> Fix Bug 1185471, improve layout of server sent error list

- .travis.yml
> Remove coveralls ping from travis

- bedrock/mozorg/templates/mozorg/plugincheck.html
- media/css/plugincheck/plugincheck.less
- media/js/plugincheck/check-plugins.js
- tests/functional/plugincheck.js
> Fix Bug 1172986, show message when no plugins are found

- bedrock/mozorg/templates/mozorg/plugincheck.html
- media/js/plugincheck/check-plugins.js
> Fix Bug 1163628, switch research links to point to DDG

- bedrock/firefox/templates/firefox/os/_get_device.html
- bedrock/firefox/templates/firefox/os/devices.html
- media/js/firefox/os/partner_data.js
- Add MTN to list of One Touch Fire E operators.
> [fix bug 1186221] FxOS Orange Klif Egypt availability.

- tests/functional/styleguide.js
> Adds functional tests for styleguide

- bedrock/thunderbird/templates/thunderbird/releases/index.html
- bedrock/thunderbird/templates/thunderbird/releases/release-notes.html
- bedrock/thunderbird/templates/thunderbird/releases/system_requirements.html
Haven't fully tested this change locally yet, but should fix things.
> [fix bug 1190378] No CSS on thunderbird system-requirements pages

- bedrock/firefox/templates/firefox/australis/fx40/firstrun.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- bedrock/settings/base.py
- bedrock/settings/static_media.py
- media/css/firefox/australis/fx40/firstrun.less
- media/js/firefox/australis/fx40/firstrun.js
Will need to merge prior to Fx40 launch on 8/11 so we can test FxA integration on stage. FxA should be ready to test on stage on Tuesday, 8/4.
> [fix bug 1150231] Fx40 firstrun experience.

- media/css/plugincheck/plugincheck.less
> Fix Bug 892587, ensure plugincheck display correctly at mobile viewports

- bedrock/settings/static_media.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1191105
> Fix bug 1191105 - add Tabzilla CSS to iOS newsletter page

- bedrock/legal/templates/legal/impressum.html
- bedrock/legal/templates/legal/index.html
- bedrock/legal/urls.py
- bedrock/settings/static_media.py
- etc/httpd/global.conf
- media/css/legal/impressum.less
https://bugzilla.mozilla.org/show_bug.cgi?id=1003737
> Bug 1003737 - Port and update /de/impressum/ to bedrock

- media/js/firefox/new.js
@craigcook r? Looks like discussions are still ongoing, but for now it's removed.
> [fix bug 1168440] Remove Spring pixel

- etc/httpd/global.conf
I recommended a redirect with the wrong URL over in https://github.com/mozilla/bedrock/pull/3179
:fearful:
> Bug 1003737 Fix URL in German legal redirect

- media/js/base/global.js
- media/js/plugincheck/check-plugins.js
- tests/unit/spec/base/global.js
Do not merge before August 11. @alexgibson r?
> Fix Bug 1192354 - Remove Firefox 31 ESR detection

- tests/functional/firefox-tiles.js
> Adding functional test for firefox/tiles

- bedrock/mozorg/templates/mozorg/plugincheck.html
- media/css/plugincheck/plugincheck.less
- media/js/plugincheck/check-plugins.js
- media/js/plugincheck/tmpl/plugincheck.ui.tmpl.js
> Fix Bug 882309, provide link to advisory when plugin is vulnerable

- bedrock/firefox/templates/firefox/australis/fx38_0_5/firstrun.html
- bedrock/firefox/templates/firefox/australis/fx40/firstrun.html
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/css/firefox/australis/fx38_0_5/firstrun.less
- media/css/firefox/australis/fx40/firstrun.less
- media/js/firefox/australis/fx38_0_5/firstrun.js
- media/js/firefox/australis/fx40/firstrun.js
- Enable display of FxA frame error (see [FxA issue #2934](https://github.com/mozilla/fxa-content-server/issues/2934))
> [fix bug 1195391] Remove video from Fx38+ firstrun.

- media/js/firefox/new.js
This is a duplicate of #3024.
r?
> [fix bug 1196404] Add Pixel for IE/Edge campaign

- media/js/firefox/australis/common.js
> [bug 1187829] Update Waypoint JS trigger on australis page

- tests/functional/firefox-partners.js
> Add functional tests for Firefox partners page

- bedrock/firefox/templates/firefox/includes/download-button.html
- bedrock/mozorg/templates/mozorg/home/home.html
- tests/functional/firefox-personal.js
- tests/functional/firefox-sync.js
- tests/functional/plugincheck.js
> Fix Bug 1196471, remove id from download button to avoid duplicate ids

- tests/functional/firefox-dnt.js
> Add functional tests for the Firefox DNT page

- bedrock/firefox/templates/firefox/os/faq.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1189927
> Bug 1189927 - Content updates need to be made on the FxOS FAQ

- bedrock/foundation/templates/foundation/mocosc.html
- bedrock/mozorg/templates/mozorg/about/leadership.html
> Fix Bug 1198773, Add Mark Mayo to steering committee page, and update titles on leadership page

- bedrock/foundation/templates/foundation/mocosc.html
Thanks to @reedloden for catching a title update we missed in https://github.com/mozilla/bedrock/commit/a9370f3649213e50408166bf83451be79bdbc548#commitcomment-12941205
@schalkneethling r?
> Update title on mocosc.html for bug 1198773

- etc/httpd/global.conf
These were unintentionally removed in 769f05dd60334f54182f6cfdb91f6cff13a851ac
> Bug 1201198 Add back commiter agreement redirects

- bedrock/mozorg/templates/mozorg/mpl/1.1/index.html
- bedrock/mozorg/templates/mozorg/mpl/historical.html
- bedrock/mozorg/templates/mozorg/mpl/index.html
> Fix Bug 1201196, fix broken link to text file for MPL 1.1

- bedrock/firefox/templates/firefox/includes/download-button.html
- media/css/firefox/personal.less
- media/css/mozorg/home/home-promo.less
- media/css/sandstone/buttons.less
@craigcook r? I navigated around the site with JS turned off and all looks good.
> Fix Bug 1196468, fix header nesting for download button

- bedrock/mozorg/templates/mozorg/home/home.html
- media/js/mozorg/home/ga-tracking.js
A followup to #3268 - I missed this in the first PR, but I since noticed the main nav tracking was messed up too.
> [fix bug 1188943] Fix GTM nav link tracking on homepage

- bedrock/mozorg/templates/mozorg/home/home.html
> Fix Bug 1199145, add about link to landing page

- docker/jenkins/updatemaxmind.sh
- Created jenkins job that runs daily and uploads maxmind db to s3 for bedrock use. (currently disabled) 
https://ci.us-west.moz.works/view/Bedrock%20Docker/job/bedrock-maxmind-update/
@pmclanahan can you upload maxmind creds to our database? Also r?
> Script to upload maxmind db to S3.

- bedrock/foundation/templates/foundation/licensing/website-content.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1202557
> Bug 1202557 - Updates to Site Licensing Policies page

- bedrock/externalfiles/__init__.py
- bedrock/externalfiles/migrations/0001_initial.py
- bedrock/externalfiles/models.py
- bedrock/externalfiles/tests.py
- bedrock/mozorg/credits.py
- bedrock/mozorg/forums.py
- bedrock/mozorg/templates/mozorg/credits.html
- bedrock/settings/__init__.py
* Add model for externalfiles.
* Add simple dict cache for model instances.
* Add migration for new model.
Only thing left is to fix and add tests. I'll do that in the morning.
> Store externalfiles data in the DB.

- media/css/styleguide/styleguide.less
> Fix Bug 1188811, fix color contrast of links in fxos styleguide

- Dockerfile
External files are stored in database since baf6555.
> Don't run update_externalfiles in Dockerfile.

- bin/update/deploy_base.py
> Update externalfiles after database migrations

- media/js/firefox/new.js
Code taken straight from #3225.
@alexgibson r?
> [fix bug 1206129] Add tracking pixel to /firefox/new/.

- bedrock/settings/static_media.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1206171
> Bug 1206171 - firefox/android/all menu-resp.less 

- bedrock/base/templates/base-resp.html
- bedrock/base/templates/base.html
- bedrock/mozorg/templates/mozorg/home/home.html
- bedrock/mozorg/templates/mozorg/mission.html
- bedrock/research/templates/research/base.html
- bedrock/settings/static_media.py
- bedrock/styleguide/templates/styleguide/base.html
- media/css/mozorg/contribute/contribute-2015.less
- media/css/styleguide/styleguide.less
@alexgibson r?
I am waiting on feedback re https://bugzilla.mozilla.org/show_bug.cgi?id=1205828#c4 and clarity with regards to the "Participate" link but, it's good for a general code review.
> Fix Bug 1205828, add new nav elements to non fx pages

- docs/coding.rst
https://bugzilla.mozilla.org/show_bug.cgi?id=1183183
> Bug 1183183 Update docs to include CSS block inclusion

- tests/functional/contribute-signup.js
- tests/functional/styleguide.js
@schalkneethling r? Couple of tests needed updating post #3329 merging.
> Update functional tests for contribute/signup and /styleguide

- docker/jenkins/run_mcom_tests.sh
Need to update test jenkins jobs just before merging.
Test run https://ci.us-west.moz.works/job/bedrock_test_dev_us_west/61/
@jgmize r?
> Add mcom_tests jenkins script.

- bedrock/settings/base.py
> Enable database connection reuse for mysql and postgres.

- bin/update-scripts/dev/update-dev-locale.sh
This will require a change on the admin node, so please
coordinate merging this with me so this server change can
be made just prior to merging this.
> Fix bug 1210368: Update dev to use locales from git.

- bedrock/events/fixtures/events.json
- bedrock/events/helpers.py
- bedrock/events/models.py
- bedrock/events/tests/test_models.py
- bedrock/events/utils.py
- bedrock/mozorg/templates/mozorg/contribute/events.html
- Show only events that haven't started on home page.
> [fix bug 1191009] Update events filters.

- .travis.yml
- bedrock/base/tests/test_accepted_locales.py
- bedrock/newsletter/tests/test_footer_form.py
- bedrock/settings/base.py
- lib/l10n_utils/tests/test_commands.py
- lib/l10n_utils/tests/test_template.py
Mostly involved updating some mocks and tests.
> Update tests to pass without l10n files.

- bedrock/base/views.py
- bedrock/settings/base.py
- bedrock/urls.py
This URL will return 200 OK. To be used with Deis health checks.
> Add healthcheck URL.

- docker/jenkins/include_l10n.sh
This introduces PROD_ONLY env variable which will be used by jenkins
jobs after l10n to determine execution path: When PROD_ONLY is true
only push_to_stage jobs run and push_to_dev jobs are not run.
PROD_ONLY is true when the job is time triggered and therefore it's
updating only locales and not code. This image with the updated locales
should be pushed to staging and production and not to dev which maybe
already in a newer code version.
Secondly a image build from code merges would run `svn up` and update
the locales making the next time triggered job to believe that there are
no locale changes and therefore skip pushing the latest version to
production. To tackle this FORCE_TIME_TRIGGER_UPDATE gets introduced to
force pushing previously checkout locales to production on time triggers.
> Update jenkins include_l10n script.

- bin/update-scripts/dev/update-dev-locale.sh
- bin/update/deploy_dev_base.py
This is unreverting #3385 and doing #3386 again but only for dev/demo.
> Bug 1210368: Use git-based locale data on dev/demo servers

- docs/contribute.rst
- docs/install.rst
- docs/l10n.rst
- docs/vagrant.rst
Note: I also updated a line about the shortcut for source, it's not specific to zsh, been using it in bash for years :)
> Update l10n docs now that translations are on GitHub

- docker/jenkins/include_l10n.sh
Use https://github.com/mozilla-l10n/bedrock-l10n for locales. This code already runs on https://ci.us-west.moz.works/job/bedrock_l10n_image/
> Update l10n docker image to use git l10n repo.

- bin/update-scripts/prod/update-prod-locale.sh
- bin/update-scripts/stage/update-stage-locale.sh
- bin/update/deploy_base.py
- bin/update/deploy_dev_base.py
This just changes the deployment and cron scripts. I'll need to manually
update the `locale` dir on the admin node for this to work, so please coordinate
the merging of this with me.
> Bug 1210368: Convert legacy infra from svn to git for locales.

- media/css/mozorg/home/home-promo.less
> Fix Bug 1214112, updated background color of android tile

- bin/update/deploy_base.py
- bin/update/deploy_dev_base.py
Should be an if statement to avoid returning non 0.
> Fix check_locale again.

- docker/dockerfiles/bedrock_code
> Do not include product details in docker image.

- bedrock/firefox/templates/firefox/choose.html
> Fix Bug 1214232, switch to default headline for /choose

- bedrock/base/templates/includes/site-footer.html
- bedrock/mozorg/redirects.py
- bedrock/mozorg/templates/mozorg/contact/contact-base.html
- bedrock/mozorg/templates/mozorg/contact/contact-landing.html
- bedrock/mozorg/urls.py
- media/css/mozorg/contact-spaces.less
- media/js/mozorg/contact-spaces.js
- tests/functional/contact.js
@jpetto r?
@flodolo I am pretty sure this is not localized but, just putting an l10n label on this in case. If indeed it is not needed, you can just remove the label. Thanks!
> Fix Bug 1205858, adds new default contact us tab to contact page

- bedrock/mozorg/templates/mozorg/contact/contact-landing.html
- bedrock/press/forms.py
- bedrock/press/templates/press/emails/press-inquiry.txt
- bedrock/press/templates/press/includes/resources.html
- bedrock/press/templates/press/press-inquiry.html
- bedrock/press/templates/press/speaker-request.html
- bedrock/press/tests.py
- bedrock/press/urls.py
- bedrock/press/views.py
- bedrock/settings/static_media.py
- etc/httpd/global.conf
- media/css/press/press.less
> Fix Bug 1210426, adds press inquiry page

- bedrock/settings/base.py
Set some env vars and it'll do the right thing.
> Add email settings for sending from AWS SES.

- docker/jenkins/push2deis.sh
More stats, more logs, more fun!
(I already updated the env variables in jenkins)
> Ping NewRelic on deploy.

- bedrock/mozorg/templates/mozorg/contact/contact-landing.html
> Fix Bug 1205858, updated content for contact tab

- bedrock/press/forms.py
- bedrock/press/templates/press/emails/press-inquiry.txt
- bedrock/press/templates/press/press-inquiry.html
- bedrock/press/tests.py
> Fix Bug 1215229, add email field to inquiry form

- bedrock/firefox/templates/firefox/choose.html
> Fix Bug 1217214, update first blurb to uppercase Web

- bedrock/firefox/redirects.py
- bedrock/mozorg/redirects.py
- bedrock/settings/__init__.py
- etc/httpd/global.conf
- test_redirects/base.py
- test_redirects/map_globalconf.py
This is the last of 'em. For global.conf that is.
> Port remaining redirects from global.conf

- bedrock/base/templates/includes/lang_switcher.html
- bedrock/tabzilla/templates/tabzilla/tabzilla.js
- media/js/base/global.js
- tests/pages/base.py
Hi, I think I have fixed bug 1215145, fixing the language selector.
https://bugzilla.mozilla.org/show_bug.cgi?id=1215145
I only just realized it was assigned to someone after completing necessary changes. I wasn't sure whether to do a pull request or not, so I did anyway.
Thank You.
> Bug-1215145-fix-lang-selector

- bedrock/firefox/urls.py
- bedrock/firefox/views.py
> Fix Bug 1217211, redirect choose to new until November 3rd

- bedrock/firefox/templates/firefox/choose.html
> Fix Bug 1214822, redirect ios users to ios product page from choose

- bedrock/infobar/templates/infobar/infobar.jsonp
- bedrock/infobar/tests.py
- bedrock/infobar/urls.py
- bedrock/infobar/views.py
- bedrock/settings/base.py
- bedrock/urls.py
> Fix Bug 1217353, adds new infobar app to bedrock

- .travis.yml
- bin/run-functional-tests.sh
- docker/dockerfiles/bedrock_functional_tests
- requirements/test.txt
- requirements/test_redirects.txt
To build the Docker image:
```
cp docker/dockerfiles/bedrock_functional_tests Dockerfile
docker build -t bedrock_functional_tests .
rm Dockerfile
```
To run the tests in Docker containers using Selenium Grid:
```
docker run -d --name selenium-hub selenium/hub:2.48.2
docker run -d --link selenium-hub:hub selenium/node-firefox:2.48.2
docker run -v `pwd`/results:/app/results \
--link selenium-hub:hub \
-e SELENIUM_HOST=hub \
bedrock_functional_tests
```
For additional nodes run several `node-firefox` containers by repeating the command to run it.
To run the tests using Sauce Labs:
```
docker run -v `pwd`/results:/app/results \
-e DRIVER=SauceLabs \
-e SAUCELABS_USERNAME=[user] \
-e SAUCELABS_API_KEY=[key] \
-e BROWSER_NAME=Firefox \
-e PLATFORM="Windows 10" \
-e SCREEN_RESOLUTION=1280x1024 \ …
```
> Create a Dockerfile for running the Python functional tests

- docker/jenkins/cleanup_after_functional_tests.sh
- docker/jenkins/run_functional_tests.sh
This is already used in https://ci.us-west.moz.works/job/bedrock_functional_tests/
/cc @pmclanahan @jgmize @davehunt
> Add functional tests build step.

- bedrock/firefox/templates/firefox/choose.html
@alexgibson r? Pretty similar to [this](https://github.com/ckprice/bedrock/commit/870012889f712aa54bdc538baf961e8773eceb0c).
> [fix bug 1219795] Add Optimizely to Fall Campaign Page

- bedrock/firefox/templates/firefox/choose.html
> Fix Bug 1213891, update urls to smarton and private browsing

- bedrock/firefox/templates/firefox/push.html
Left a stray tag here, just tidying up after myself
> Fix stray tag on firefox/push FAQ

- bedrock/teach/templates/teach/smarton/tracking.html
- media/js/teach/smarton.js
Fall back to a plain link, opens in a new tab.
> Bug 1220844 - Remove the interactive embed from SmartOn Tracking

- bedrock/firefox/templates/firefox/choose.html
Doh!
@alexgibson @jpetto @schalkneethling quick r?
> [bug 1221223] Swap links on /choose/

- bedrock/settings/base.py
> Change default FXA_IFRAME_SRC to prod

- bin/update/deploy_base.py
> Remove update_externalfiles call from deploy_base

- bedrock/mozorg/templates/mozorg/about/manifesto.html
> Fix Bug 1222144, fixes source parameter on manifesto page

- bedrock/base/templates/base-resp.html
- bedrock/base/templates/base.html
- bedrock/base/templates/includes/site-footer.html
- bedrock/mozorg/templates/mozorg/home/home.html
- bedrock/settings/base.py
> Fix Bug 1221826, update header and footer donate urls en-US only

- docs/quickstart.rst
Corrected spelling on quickstart.rst from depdencies to dependencies
> Corrected spelling on quickstart.rst

- bedrock/teach/templates/teach/smarton/tracking.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1222773
> [Bug 1222773] fixed outdated link

- bedrock/firefox/templates/firefox/private-browsing.html
- media/css/firefox/private_browsing/private-browsing-conditionals.less
- media/js/base/global.js
- media/js/firefox/ios.js
- media/js/firefox/private-browsing.js
- tests/unit/spec/base/global.js
- Fix bug on Windows where download button shows for
up to date Fx users.
- Fix bug on Windows where two download buttons show
for out of date Fx users.
> [fix bug 1222181] Update PB CTA URL for Android/iOS.

- bedrock/firefox/templates/firefox/ios.html
> Point tracking protection link to private browsing product page on iOS product page

- bedrock/mozorg/templates/mozorg/home/home.html
- media/css/mozorg/home/home-promo.less
> Fix Bug 1218583, swap gear and webmaker promos and update content

- bedrock/mozorg/templates/mozorg/contact/communities/indonesia.html
**Bugzilla:** https://bugzilla.mozilla.org/show_bug.cgi?id=1186049
> Bug 1186049 – update indonesia community website link

- etc/httpd/global.conf
@pmclanahan r?
followup from https://github.com/mozilla/bedrock/pull/3459#issuecomment-155505902
> Pass all firefox/ios urls through to bedrock

- bedrock/styleguide/templates/styleguide/identity/webmaker-branding.html
@craigcook r? This is still blocked :( but at least the work is not lost yet.
> Fix Bug 1175199, update webmaker styleguide page to reference new logo

- bedrock/settings/base.py
> Fix Bug 1223570, update donate link for pt-BR, de, fr and es

- bedrock/firefox/templates/firefox/os/ver/2.5.html
- media/js/firefox/os/firefox-os-2.5.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1221303
Adding pixel id to both buttons.
> Bug 1221303 - Update pixel id

- bedrock/firefox/templates/firefox/releases/release-notes.html
- bedrock/firefox/urls.py
- bedrock/releasenotes/tests/test_base.py
- bedrock/releasenotes/views.py
> Fix ios system requirements

- bedrock/firefox/templates/firefox/new.html
> Fix Bug 1224299, update /new headline to match that of /choose

- tests/functional/firefox/os/test_devices.py
> Temporarily disable /os/devices/ functional tests

- tests/functional/firefox/os/test_devices.py
- tests/functional/firefox/test_do_not_track.py
- tests/pages/base.py
- tests/pages/contribute/contribute.py
- tests/pages/contribute/signup.py
- tests/pages/contribute/stories.py
- tests/pages/firefox/base.py
- tests/pages/firefox/developer.py
- tests/pages/firefox/do_not_track.py
- tests/pages/firefox/os/devices.py
- tests/pages/home.py
- tests/pages/newsletter.py
- tests/pages/page.py
- tests/pages/regions/modal.py
- tests/pages/regions/newsletter.py
Also introduces a method for scrolling elements into view, which avoids the family header navigation on affected pages.
> Refactor page and region objects under a common base class

- bedrock/mozorg/templates/mozorg/home/home.html
See https://bugzilla.mozilla.org/show_bug.cgi?id=1214038#c12 - @jpetto r?
> Removes period from after Dec on eoy homepage promo

- bedrock/teach/templates/teach/smarton/security.html
> Fix Bug 1225737, shorten tweet text on cybersecurity and wrap in en-US conditional

- media/js/base/nav-main-resp.js
This is a small change to make functional testing easier (see: https://github.com/mozilla/bedrock/pull/3575#discussion_r45218569)
> [fix bug 1225896] Adjust mobile nav menu aria state timing

- bedrock/mozorg/templates/mozorg/home/home.html
- media/css/mozorg/home/home-promo.less
> Fix Bug 1225275, swap pb and ios, update color for ios and gear

- tests/functional/test_navigation.py
- tests/pages/base.py
- tests/pages/page.py
> Wait for the page URL to be in the current URL when loading pages

- tests/pages/base.py
@davehunt r?
https://webqa-ci.mozilla.com/job/bedrock.dev.win10.ie/100/
> Fix intermittent failure in language selector test

- tests/functional/test_styleguide.py
cc @davehunt - looks like this is failing intermittently in IE, going to skip this test until I can dig into what's up.
> Temporarily disable styleguide nav test

- bedrock/foundation/templates/foundation/annualreport/2014/faq.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1224565
> Bug 1224565 - Fix: Add pdf url

- media/css/mozorg/home/home-promo.less
@alexgibson @flodolo r? Main locales tested are:
en-gb, en-ca, de, pt-br, de, es-es, it and nl
> Fix Bug 1228015, reduced font size on eoy home promo

- media/js/firefox/android.js
This is a minor code change to make functional testing easier, plus a (small) accessibility improvement.
> [fix bug 1228295] Set pager tabs on /firefox/android/ to disabled when inactive

- bedrock/foundation/templates/foundation/annualreport/2009/broadening-our-scope.html
- bedrock/foundation/templates/foundation/base-resp.html
- bedrock/foundation/templates/foundation/index.html
- bedrock/foundation/templates/foundation/openwebfund/more.html
- bedrock/grants/templates/grants/base.html
- bedrock/mozorg/helpers/misc.py
- bedrock/mozorg/redirects.py
- bedrock/mozorg/templates/mozorg/contact/contact-landing.html
- bedrock/mozorg/templates/mozorg/contribute/index.html
- bedrock/mozorg/templates/mozorg/contribute/thankyou.html
- bedrock/mozorg/tests/test_helper_misc.py
- bedrock/settings/base.py
- test_redirects/map_globalconf.py
> Fix Bug 1227250, replace all instances of sendto donate links with donate.

- requirements/base.txt
> Upgrade Django to 1.7.11 to fix bug 1226782

- requirements/base.txt
> Upgrade rna for "rnasync --force": fix bug 1230452

- bedrock/firefox/templates/firefox/firstrun/firstrun-e.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-f.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-g.html
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/css/firefox/firstrun/variants.less
@alexgibson mozlando r? :) thx
> Fix Bug 1226830, adds firstrun variants

- bedrock/mozorg/templates/mozorg/mosaic-grid.html
- media/js/libs/jquery.gridrotator.js
For GitHub to display the JS file changes, try ignoring white space changes with `?w=1`
> [fix bug 1230326] Mosaic loading.gif should load from CDN

- bedrock/base/templates/macros.html
- bedrock/firefox/firefox_details.py
- bedrock/firefox/templates/firefox/family/index.html
- bedrock/firefox/templates/firefox/ios.html
- bedrock/firefox/templates/firefox/mobile-download.html
- bedrock/firefox/templates/firefox/new.html
- bedrock/firefox/templates/firefox/private-browsing.html
- bedrock/firefox/tests/test_helpers.py
- bedrock/mozorg/helpers/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- bedrock/settings/appstores.py
- bedrock/settings/base.py
- media/js/base/global-init.js
- media/js/base/global.js
- tests/unit/spec/base/global.js
> Fix Bug 1229244 - Users should be navigated to localized App Store

- bedrock/mozorg/forms.py
- bedrock/mozorg/templates/mozorg/contribute/studentambassadors/join.html
Remove:
- Firefox Flicks
- Firefox for Android
https://bugzilla.mozilla.org/show_bug.cgi?id=1226265
> Fixes bug 1226265 - Firefox Student Ambassadors Form Remove Specific Newsletters

- bedrock/firefox/templates/firefox/new.html
- bedrock/settings/static_media.py
- media/css/firefox/new-v2.less
- media/css/firefox/new/v2-buttons.less
- media/css/firefox/new/v2-sandstone-resp.less
- v2: Custom/slim sandstone & buttons CSS
- v4: Async fonts, custom sandstone, no optimizely
> [fix bug 1231201] /firefox/new/ performance test v2/4.

- bedrock/mozorg/email_contribute.py
> Bug 1228727 - [ko] Set up email for Get Involved page

- bedrock/foundation/templates/foundation/index.html
New foundation page copy can be found [here](https://docs.google.com/document/d/16zylCLM66kft-ylGNITuxDPyOvc1OxxCOYvo5yE51O0/edit).
> Fix bug 1225630 update foundation page copy

- bedrock/firefox/templates/firefox/feedback/happy.html
- bedrock/firefox/templates/firefox/feedback/unhappy.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
@pmac r? Note: This should not be merged before December 15th, but is good for code review before then.
> Fix Bug 1224614, adds eoy fundraising CTA to post heartbeat landing pages

- requirements/test.txt
Upgrades us to pytest-selenium with improved error handling. I also updated the other packages while I was there.
> Update to the latest stable test requirement package versions

- media/js/mozorg/home/takeover.js
> Fix Bug 1233620, do not display homepage takeover to Firefox for iOS users

- bedrock/mozorg/forms.py
- bedrock/mozorg/templates/mozorg/partnerships.html
- media/js/mozorg/partnerships.js
@jpetto r? This needs to be merged after https://github.com/mozilla/mcom-tests/pull/466 has been merged to avoid test breakage.
> Fix Bug 1233018, remove tiles copy from partnerships page and form

- etc/httpd/global.conf
> Fix Bug 1233959, add infobar entry to global.conf

- docker/jenkins/run_linkchecker.sh
> Allow multiple URLs when running LinkChecker in Jenkins

- bedrock/teach/templates/teach/smarton/surveillance.html
Added en-us to url in order to fix the broken link.
> Bug 1235036 - Broken link on SmartOn Surveillance page

- bedrock/mozorg/templates/mozorg/credits.html
Hard code link to eliminate caching localized link
> Fix link to home page on /credits: fix bug 1235426

- tests/pages/firefox/products.py
https://webqa-ci.mozilla.com/job/bedrock.dev.win10.ie/172/
> Fix intermittent test failure on Firefox Products page

- tests/functional/firefox/test_android.py
- tests/pages/firefox/android.py
- tests/pages/firefox/base.py
Note: this is currently blocked from merging due to the form failing on dev. I've filed a bug which can hopefully be resolved: https://bugzilla.mozilla.org/show_bug.cgi?id=1235534
> Add functional tests for Send to Device form on Android page

- bedrock/security/management/commands/update_security_advisories.py
- bedrock/security/tests/test_commands.py
Also clean up any Products left without advisories after said deletions.
> Fix bug 1235480: Fix deletion of removed MFSA advisories

- bedrock/teach/templates/teach/smarton/surveillance.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1238321
> [fix bug 1238321] Replace TextSecure and RedPhone on Android with Signal

- docker/jenkins/run_functional_tests.sh
@alexgibson this should fix the pipeline
> Add a link to the bedrock instance in Jenkins when running the functional tests

- bedrock/foundation/templates/foundation/mocosc.html
- bedrock/mozorg/templates/mozorg/about/leadership.html
This is ready for initial review, but shouldn't merge until her Mozillians profile is public and her press bio is live and we can verify the links.
> Fix bug 1238686 - Add Katharina Borchert to Leadership page

- media/css/mozorg/home/home-promo.less
- media/css/sandstone/buttons.less
Fix bug 1239814 - home promo shows desktop links for Android devices
> Fix bug 1239801 - home promo missing App Store button on iOS

- requirements/test.txt
> Update Selenium to version 2.49.0

- tests/functional/thunderbird/test_channel.py
- tests/functional/thunderbird/test_thunderbird.py
- tests/pages/thunderbird/channel.py
- tests/pages/thunderbird/thunderbird.py
@davehunt r? I totally forgot to include the Thunderbird pages :scream:
> Update Thunderbird tests to use download button PageRegion

- etc/httpd/global.conf
Fix the intermittent 404. Follow up #3780. Part of Bug 1226476.
> Add RewriteRule for /firefox/android/beta/all/

- media/css/firefox/ios.less
- tests/functional/contribute/test_contribute.py
- tests/functional/firefox/test_android.py
- tests/functional/firefox/test_ios.py
- tests/functional/test_home.py
- tests/pages/firefox/ios.py
> Add functional tests for Firefox iOS page

- docker/dockerfiles/bedrock_functional_tests
Fix https://ci.us-west.moz.works/job/bedrock_functional_tests/495/console
> Add lxml deps to bedrock_functional_tests

- bedrock/mozorg/templates/mozorg/about/governance/organizations.html
- bedrock/mozorg/templates/mozorg/about/governance/roles.html
> [fix bug 1237282] Broken links on governance pages

- tests/pages/contact.py
This should hopefully fix intermittent failures such as:
https://ci.us-west.moz.works/job/bedrock_functional_tests_sauce/346/
https://ci.us-west.moz.works/job/bedrock_functional_tests_sauce/376/
https://ci.us-west.moz.works/job/bedrock_functional_tests_sauce/371/
@davehunt r?
> Fix intermittent test failures on contact pages

- media/css/mozorg/about-lean-data.less
> Bug 1237070 - Ensure github button text is white for visited state

- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
> 3rd quarter updates for hall of fame

- bedrock/mozorg/templates/mozorg/home/home.html
- media/css/mozorg/home/home-promo.less
English-only, no 1l0n, so I didn't even wrap the strings.
> Fix bug 1244335 - Foundation home promo, "Food, Water, Shelter"

- bedrock/mozorg/templates/mozorg/contribute/tasks/v1/joy-of-coding.html
- bedrock/mozorg/templates/mozorg/contribute/tasks/v2/joy-of-coding.html
- media/css/mozorg/contribute/signup.less
- media/js/mozorg/contribute/taskview.js
> Fix Bug 1246806, ensure video element interactions work, remove underline from button hover state

- media/js/mozorg/contribute/taskview.js
> Fix Bug 1225884, send GA events on tweet form clicks

- docker/jenkins/push2dockerhub.sh
This is not implemented: https://github.com/docker/docker/issues/2619
> Remove unsupported "-f" flag from docker push cmds

- media/js/plugincheck/check-plugins.js
> Fix Bug 1245230, add GA pings of plugin totals on load

- bedrock/mozorg/templates/mozorg/contribute/whimsy-test.html
- bedrock/mozorg/urls.py
> Fix Bug 1248413, remove temporary Whimsy test page

- bedrock/base/templates/macros.html
- media/css/firefox/android.less
@jpetto r?
@flodolo We have this string already but, not on this page perhaps?
> Fix Bug 1206178, add android/all link to android send to device widget

- bedrock/gigabit/templates/gigabit/apply.html
Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1249481
Original request from the Program Manager: https://github.com/mozilla/teach.mozilla.org/issues/1628
:smiley: Thanks!
> Fixes Bug 1249481 - update Gigabit pilot period dates

- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/scene2.html
- Should match current /new template waffle switch name
during A/B testing
> [fix bug 1248728] New /new templates - update waffle switch names

- media/js/mozorg/contact-spaces.js
> Fix Bug 1221087, set map state correctly for sub page landing state

- bedrock/base/templates/includes/site-footer.html
- bedrock/base/templates/macros.html
Adding data attributes to nav and footer links on /firefox/desktop/ page templates.
> [bug 1248040] Update GTM data attributes on /firefox/desktop/

- media/js/plugincheck/check-plugins.js
> Fix Bug 1249892, filter out undefined entries in the response array

- tests/functional/smarton/test_all.py
- tests/functional/smarton/test_landing.py
- tests/pages/smarton/base.py
- tests/pages/smarton/landing.py
Adds functional tests for SmartOn series pages
Please make sure relevant tests pass in both Firefox and a non-Firefox browser (e.g. Chrome)
> Add functional tests for SmartOn pages

- bedrock/legal/templates/legal/fraud-report.html
- bedrock/mozorg/templates/mozorg/contribute/studentambassadors/landing.html
These pages are not localized.
> Fix Bug 1249419 - Update links to Firefox Friends

- bin/run-integration-tests.sh
> Disable HTML report generation in integration tests due to known bug

- requirements/test.txt
- tests/functional/conftest.py
Update test dependencies for the integration tests.
N/A
Running a few of the integration tests (and verifying that Travis is happy) should be enough.
> Update integration test dependencies

- docker/jenkins/run_mcom_tests.sh
Removing the now unused script to run the mcom-tests, as these have now all been migrated into the integration tests.
N/A
Nothing needed, the references to this script have already been removed from Jenkins.
> Remove the script to run the mcom-test as these have now all been migrated

- bedrock/firefox/redirects.py
- bedrock/firefox/tests/test_base.py
- bedrock/redirects/util.py
- bedrock/settings/base.py
- tests/redirects/map_globalconf.py
> Replace obsolete tests for vary: user-agent

- bedrock/mozorg/templates/mozorg/mission.html
> Fix Bug 1251061 - Update /mission copy

- .eslintignore
- .eslintrc.js
- media/js/base/dnt-helper.js
- media/js/base/global-init.js
- media/js/base/global.js
- media/js/firefox/dev-firstrun.js
- media/js/firefox/dev-whatsnew.js
- media/js/firefox/developer.js
- media/js/firefox/geolocation-demo.js
- media/js/firefox/private-browsing.js
- media/js/mozorg/contact-spaces.js
- media/js/newsletter/form.js
- media/js/plugincheck/check-plugins.js
- media/js/plugincheck/lib/version-compare.js
- media/js/plugincheck/tmpl/plugincheck.ui.tmpl.js
- media/js/teach/smarton-landing.js
- media/js/teach/smarton.js
Updates our ESLint config and defines globals (brings our number of errors down from 7587 to 4493!)
> Update ESLint config and define globals

- bedrock/mozorg/email_contribute.py
- bedrock/mozorg/tests/test_views.py
> Fix bug 1250519: Remove BSD newsletter subscribe

- bedrock/foundation/templates/foundation/licensing/website-content.html
> Fix Bug 1253473 - A change is needed to https://www.mozilla.org/en-US/foundation/licensing/website-content/

- docs/redirects.rst
> Update documentation for running redirect tests (closes #3904)

- bedrock/firefox/views.py
> [bug 1240980] Remove Hello page waffle switch

- tests/functional/test_not_found.py
- tests/pages/not_found.py
> Add functional test for 404 page

- docs/pipeline.rst
> Add cheet sheet for prod push to pipeline docs.

- Dockerfile
Followup from https://github.com/mozilla/bedrock/pull/3931/files#r55686643
@pmclanahan r?
> Remove redundant pipstrap

- bedrock/firefox/redirects.py
- tests/redirects/map_htaccess.py
Original redirects from .htaccess file in the .com svn repo
> Bug 1255882: Add redirects for old Fx pages

- requirements/base.txt
@pmclanahan r?
See https://github.com/mozilla/bedrock/pull/3960#issuecomment-197457318 for details.
> Upgrade rna to fix clock process error in rnasync

- .bedrock_demo_env
- bin/circleci-demo-sync.sh
It was failing to do so due to some environment settings.
> Demos built by CircleCI should update product-details

- bin/circleci-demo-sync.sh
* Have it run the fxos feed update
* Have it use the .bedrock-demo-env settings
> Fix CircleCI demo deploy data

- circle.yml
> Add tagged release deployment to circle.yml

- .bedrock_demo_env
> Add GTM container ID for demo deployments

- bedrock/mozorg/templates/mozorg/about-base.html
- bedrock/mozorg/templates/mozorg/about/patents/license-1.0.html
- bedrock/mozorg/urls.py
https://www.mozilla.org/en-US/about/patents/license/ is not localized.
> Fix Bug 1257703 - Update MOSPL with v1.1 revisions

- bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
* Updating https://www.mozilla.org/en-US/about/governance/policies/participation/
* No L10n required
* Should be live by Monday
> Fix Bug 1259408 - Minor revision to Community Participation Guidelines

- docs/testing.rst
> Add documentation for running functional tests in Sauce Labs

- media/js/teach/smarton-landing.js
- media/js/teach/smarton.js
> Lint Smarton pages JS files

- docs/mozilla-accordion.rst
- media/js/base/mozilla-accordion-gatrack.js
- media/js/base/mozilla-accordion.js
- tests/unit/spec/base/mozilla-accordion.js
> Lint mozilla-accordion.js files

- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/ios.html
- bedrock/firefox/templates/firefox/mobile-download.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/templates/firefox/new/variants/scene1/base.html
- bedrock/firefox/templates/firefox/new/variants/scene2/base.html
- bedrock/firefox/templates/firefox/private-browsing.html
- bedrock/firefox/templates/firefox/releases/release-notes.html
- bedrock/firefox/templates/firefox/sync.html
- bedrock/mozorg/templates/mozorg/contribute/tasks/v1/firefox-mobile.html
- bedrock/mozorg/templates/mozorg/contribute/tasks/v2/firefox-mobile.html
- media/js/firefox/sync.js
Bug 1248040 - https://bugzilla.mozilla.org/show_bug.cgi?id=1248040
> [bug 1248040] Update GTM data attributes on mobile download buttons

- media/js/mozorg/contribute/contribute-2015-ga.js
- media/js/mozorg/contribute/contribute-2015.js
- media/js/mozorg/contribute/contribute-faces.js
- media/js/mozorg/contribute/contribute-page.js
- media/js/mozorg/contribute/contribute-studentambassadors-join.js
- media/js/mozorg/contribute/signup.js
- media/js/mozorg/contribute/taskview.js
Lint `/contribute` pages JS files.
N/A
I must admit, I'm a little lost on all these different versions of the contribute pages. As far as I can tell, some are not used - but I don't know what the long term plan is for these pages so linted them anyway.
> Lint contribute page JS files

- Gruntfile.js
- media/js/base/dnt-helper.js
- media/js/base/global-init.js
- media/js/base/global.js
- media/js/base/mozilla-image-helper.js
- media/js/base/mozilla-modal.js
- media/js/base/mozilla-pager.js
- media/js/base/search-params.js
- media/js/base/site.js
- media/js/base/svg-animation-check.js
- tests/unit/spec/base/global.js
- tests/unit/spec/base/mozilla-accordion.js
- tests/unit/spec/base/mozilla-client.js
- tests/unit/spec/base/mozilla-form-helper.js
- tests/unit/spec/base/mozilla-image-helper.js
- tests/unit/spec/base/mozilla-pager.js
- tests/unit/spec/base/mozilla-svg-image-fallback.js
- tests/unit/spec/base/search-params.js
- tests/unit/spec/base/send-to-device.js
- tests/unit/spec/base/site.js
- tests/unit/spec/firefox/australis/browser-tour.js
- tests/unit/spec/firefox/new-ios-redirect-helper.js
- tests/unit/spec/firefox/win10-welcome.js
- tests/unit/spec/mozilla-smoothscroll.js
- tests/unit/spec/plugincheck/lib/plugincheck.js
- tests/unit/spec/plugincheck/lib/utils.js
- tests/unit/spec/plugincheck/lib/version-compare.js
- tests/unit/spec/tabzilla.js
- Lints our common JS files that are shared in many pages.
- Lints our JS test specs and adds them to the ESLint grunt task.
N/A
I've given this some manual testing, and changes seem pretty safe. I guess the main thing is to make sure any renamed functions aren't also called from anywhere else that I may have missed. I've done a check and think all is ok, but a second sweep would be good.
> Lint common JS files and test specs

- media/js/base/svg-animation-check.js
- media/js/firefox/channel.js
- media/js/firefox/desktop/common.js
- media/js/firefox/desktop/customize.js
- media/js/firefox/desktop/intro-anim.js
- media/js/firefox/desktop/tips.js
- media/js/firefox/developer.js
- media/js/firefox/family-index.js
- media/js/firefox/family-nav.js
- media/js/firefox/firefox-language-search.js
- media/js/firefox/geolocation-demo.js
- media/js/firefox/hello/index.js
- media/js/firefox/installer-help.js
- media/js/firefox/ios.js
- media/js/firefox/mwc-2015-map.js
- media/js/firefox/new-ios-redirect.js
- media/js/firefox/new/redesign/scene1-common.js
- media/js/firefox/new/scene1.js
- media/js/firefox/new/scene2.js
- media/js/firefox/os/devices.js
- media/js/firefox/os/firefox-os-2.5.js
- media/js/firefox/os/mwc-2015-preview.js
- media/js/firefox/os/partner_data.js
- media/js/firefox/pocket.js
- media/js/firefox/private-browsing.js
- media/js/firefox/releasenotes.js
- media/js/firefox/sync-animation.js
- media/js/firefox/sync.js
- Lint remaining JS files related to Firefox app.
N/A
Mostly small changes, but some manual testing of pages would be appreciated for good measure.
> Lint remaining Firefox app JS files

- circle.yml
- media/js/firefox/dev-firstrun.js
- media/js/firefox/dev-whatsnew.js
- tests/unit/spec/base/send-to-device.js
- tests/unit/spec/firefox/australis/browser-tour.js
This should pass once #4038, #4043 and #4044 are merged (nearly there!)
> Enable ESLint task in CircleCI

- bedrock/firefox/templates/firefox/firstrun/learnmore/yahoo-search.html
Adding a do-not-merge label for now, until someone has confirmed the titles are correct.
> [fix bug 1262259] Update page title for Yahoo learn more updates

- bedrock/mozorg/redirects.py
- tests/redirects/map_globalconf.py
> [fix bug 784411] Redirect /about/mission/ to /mission/

- bedrock/firefox/templates/firefox/android/index.html
- bedrock/firefox/templates/firefox/desktop/desktop-base.html
- bedrock/firefox/templates/firefox/family/index.html
- bedrock/firefox/templates/firefox/hello/index-b.html
- bedrock/firefox/templates/firefox/ios.html
- bedrock/firefox/templates/firefox/os/index.html
- bedrock/firefox/templates/firefox/pocket.html
- bedrock/firefox/templates/firefox/private-browsing.html
- bedrock/firefox/templates/firefox/sync.html
- bedrock/newsletter/templates/newsletter/includes/form.html
Remove conditionals introduced in #3995 and #4023
> Fix bug 1258998 - Remove en-* conditional on newsletter title and button

- bedrock/mozorg/templates/mozorg/about/leadership.html
Just dropping the "Dr." prefix.
https://bugzilla.mozilla.org/show_bug.cgi?id=1262286
> [bug 126286] Update Sean White

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/family/index.html
- bedrock/firefox/templates/firefox/hello/index.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/mozorg/templates/mozorg/home/home.html
- bedrock/mozorg/templates/mozorg/home/includes/upcoming-events.html
- media/js/firefox/channel.js
2nd round
bug 1248040 - https://bugzilla.mozilla.org/show_bug.cgi?id=1248040
Pages updated:
firefox/ios/
firefox/products/
firefox/channel/
firefox/hello/
firefox/new/
Homepage
> [bug 1248040] Update GTM data attributes missed on first pass through -

- Procfile
> Revert "Add supervisor to Procfile for bug 1266665"

- bedrock/gigabit/templates/gigabit/apply.html
- bedrock/gigabit/templates/gigabit/gigabit.html
Fixed bugzilla bug 1267409
https://bugzilla.mozilla.org/show_bug.cgi?id=1267409 :smile:
> Fixed bug 1267409 - updated Gigabit Twitter handle

- gulpfile.js
> Make sure ESLint covers all JS unit tests

- docker/run-prod.sh
> Respect WEB_CONCURRENCY environment variable

- docker/jenkins/include_l10n.sh
> Remove PROD_ONLY from include_l10n.sh

- docker/jenkins/include_l10n.sh
> Use latest tagged commit instead of fetching url

- bedrock/security/templates/security/web-bug-bounty.html
> Update and fixup web bounty rules, award  amount

- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
> Bug ?: Update for bug bounty q1 2016

- bedrock/base/middleware.py
- bedrock/mozorg/middleware.py
- bedrock/mozorg/tests/test_middleware.py
- bedrock/settings/base.py
https://docs.djangoproject.com/en/1.7/topics/http/middleware/#marking-middleware-as-unused
> Disable middleware using the Django way

- bedrock/security/templates/security/bug-bounty/faq-webapp.html
Clean up commit on original PR (#4135).
[bug 1267573](https://bugzilla.mozilla.org/show_bug.cgi?id=1267573)
Only HTML updates. Make sure no typos or other tag/structure releated errors.
> Bug 1267573 update webapp bug bounty faq

- docs/install.rst
> Update documentation for running local server using Gulp

- bedrock/mozorg/templates/mozorg/home/home-a.html
Last minute GA/GTM updates.
https://bugzilla.mozilla.org/show_bug.cgi?id=1277245
Make sure there aren't any typos?
> [fix bug 1277245] Add GA data-* attrs to home prototype A nav

- media/js/mozorg/home/home-a.js
Add `dataLayer` call when scrolling down to primary sections on the page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1277252
Make sure `dataLayer` call is being made with appropriate values when scrolling down only.
Make sure no regressions caused by removing `'intro', 'intro'` Waypoint. (This Waypoint was in place to reset the nav highlight, but the `'action', 'intro'` Waypoint takes care of this when scrolling up.)
> [fix bug 1277252] Add scroll tracking to home prototype A

- docs/uitour.rst
> Update UITour documentation for getConfiguration('appinfo')

- bedrock/thunderbird/templates/thunderbird/start/release.html
- media/css/thunderbird/start.less
- Replaces #4181
https://bugzilla.mozilla.org/show_bug.cgi?id=1239386
> Bug 1239386 - Add donations to Thunderbird start page.

- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-horizon.html
- bedrock/firefox/templates/firefox/firstrun/firstrun.html
- bedrock/firefox/templates/firefox/onboarding/fxa-complex.html
- bedrock/settings/base.py
- docs/firefox-accounts.rst
- media/js/base/mozilla-client.js
- media/js/base/mozilla-fxa-iframe.js
- media/js/firefox/accounts.js
- media/js/firefox/firstrun/firstrun.js
- tests/unit/spec/base/mozilla-client.js
- tests/unit/spec/base/mozilla-fxa-iframe.js
Please explain the changes you're making, complete with a description of the issue and
a summary of the proposed solution.
Please refer to the bug description.
Include a direct link to the associated bug on Bugzilla.
https://bugzil.la/1264843
Please leave some directions for the reviewer on how to test your pull request. List which
pages need attention, and what the reviewer should pay close attention to. If the change
requires testing in any specific browsers or platforms, please provide a list.
Just visit an modified page and append ?dist=mozillaonline to its url.
> Bug 1264843 - embed FxA server in China within Fx China repack

- media/js/mozorg/home/home-b.js
Add GA to open/close slidey sections.
https://bugzilla.mozilla.org/show_bug.cgi?id=1286251
You could maybe just `console.log` the object in the `dataLayer.push`?
> [fix bug 1286251] Add GA to homepage prototype B.

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/android/index.html
- bedrock/firefox/templates/firefox/mobile-download.html
- bedrock/firefox/templates/firefox/new/horizon/includes/mobile-promo.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/templates/firefox/onboarding/fxa-complex.html
- bedrock/firefox/templates/firefox/onboarding/user-actions-mobileprivacy.html
- bedrock/firefox/templates/firefox/private-browsing.html
- bedrock/firefox/templates/firefox/releases/release-notes.html
- bedrock/firefox/templates/firefox/sync.html
- bedrock/mozorg/templates/mozorg/contribute/tasks/firefox-mobile.html
- bedrock/mozorg/templates/mozorg/contribute/tasks/stumbler.html
- bedrock/mozorg/templates/mozorg/home/home-b.html
- bedrock/settings/appstores.py
- bedrock/settings/base.py
- media/js/base/global-init.js
- media/js/base/global.js
- tests/unit/spec/base/global.js
Please explain the changes you're making, complete with a description of the issue and
a summary of the proposed solution.
Please refer to the bug description.
Include a direct link to the associated bug on Bugzilla.
https://bugzil.la/1264843
Please leave some directions for the reviewer on how to test your pull request. List which
pages need attention, and what the reviewer should pay close attention to. If the change
requires testing in any specific browsers or platforms, please provide a list.
Just visit an modified page and append ?dist=mozillaonline to its url.
>  Bug 1264843: link to China build of Fx4A, for display within Fx China repack

- bedrock/gigabit/templates/gigabit/apply.html
- bedrock/gigabit/templates/gigabit/terms.html
- media/css/gigabit/gigabit.less
Update Gigabit Community Fund Terms and Conditions
https://bugzilla.mozilla.org/show_bug.cgi?id=1286645
Content-only changes. gulp test passes.
Closes https://github.com/mozilla/learning.mozilla.org/issues/1922
> Update Gigabit T&C, link to 2016 Proposal Template

- lib/l10n_utils/tests/test_translation.py
- lib/l10n_utils/translation.py
These are pretty simple tests, but so are the utilities. I've not yet come up with a way to test the thread-safety of these (though for our use that's not vital). Also we need some headless real tests but that would rely on installed translations so I'm not yet sure how to accomplish it. Let's discuss.
> Add unit-tests for translation utilities

- docker/dockerfiles/bedrock_base
> pip install requirements/test.txt in bedrock_base

- bedrock/mozorg/templates/mozorg/about/leadership.html
> [bug 1263268] Use l10n tag for leadership intro copy changes

- requirements/base.txt
Fix issue with rnasync with non 200 response from nucleus.
> Upgrade requests and django-synctool

- bedrock/security/templates/security/bug-bounty/faq-webapp.html
Update eligible bug list and reporting instructions
None, only modification of text content.
n/a
> Update eligible bug list and reporting instructions

- tests/functional/newsletter/test_newsletter_embed.py
> Temporarily skip homepage newsletter embed tests

- bedrock/firefox/templates/firefox/testflight.html
Update page title & description to help users find Firefox iOS Beta.
https://bugzilla.mozilla.org/show_bug.cgi?id=1281230
Make sure I didn't cook any copy pasta.
> [fix bug 1281230] Update TestFlight page title & description

- .gitignore
- bedrock/mozorg/management/commands/update_product_details_files.py
- bedrock/settings/base.py
- bin/cron.py
Downloads the files locally, checks them, then loads the modified files into the database.
> Add command to download, verify, and update product-details

- docker/jenkins/push2dockerhub.sh
- docker/jenkins/push2privateregistries.sh
> Stop using ghprbActualCommit

- media/caldata/calendars.json
> Fixed Trinidad and Tobago Calendar Link

- bedrock/gigabit/templates/gigabit/apply.html
Added 2 links to /gigabit/apply page
https://bugzilla.mozilla.org/show_bug.cgi?id=1301472
> Added 2 links to /gigabit/apply page

- bedrock/mozorg/templates/mozorg/about/leadership.html
Correct Sean White's title to SVP, udpate other SVPs to "SVP" for consistency.
https://bugzilla.mozilla.org/show_bug.cgi?id=1303470
> [bug 1303470] Update SVP titles

- docker/jenkins/build_image.sh
Switch to https://github.com/goldmann/docker-squash/ for compatibility with docker 1.12
@pmac or @glogiotatidis r?
> Update docker-squash command in build_image.sh

- bedrock/foundation/templates/foundation/advocacy.html
- bedrock/foundation/templates/foundation/index.html
- bedrock/foundation/templates/foundation/issues.html
- bedrock/foundation/templates/foundation/leadership-network.html
- media/css/foundation/foundation.less
> Demo foundation pages refresh

- bedrock/mozorg/templates/mozorg/about/leadership.html
Updates Mitchell's bio to match that on the press center blog.
https://bugzilla.mozilla.org/show_bug.cgi?id=1305799
Ensure no typos?
Page is not localized, so shouldn't be an issue changing strings.
> [fix bug 1305799] Update Mitchell's bio.

- docker/dockerfiles/bedrock_l10n
> Switch to webdev user before copying locale

- bedrock/mozorg/views.py
> Handle errors fetching BlogArticles from DB

- bedrock/mozorg/templates/mozorg/technology/index.html
- bedrock/settings/static_media.py
- media/js/mozorg/experiment-technology-page.js
> [bug 1295248] Add redirect experiment to /technology page

- docs/install.rst
> Add docs for feature flipping with deis config

- bedrock/mozorg/management/commands/update_blog_feeds.py
- bedrock/mozorg/models.py
- bedrock/mozorg/tests/test_commands.py
- bedrock/mozorg/tests/test_models.py
> Improve code and tests for blog feed fetching/parsing

- docker/jenkins/build_image.sh
> Validate squashed tag exists before using

- bedrock/mozorg/templates/mozorg/about/leadership.html
- tests/functional/test_leadership.py
- tests/pages/leadership.py
- Adds functional tests for opening / closing / cycling modal on `/about/leadership` page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1305954
- I had to make some additions to the HTML template to facilitate easier testing, so this change needs to be tested locally.
> [fix bug 1305954] Create functional tests for Leadership page

- bedrock/mozorg/cron.py
- bedrock/mozorg/tests/test_util.py
- bedrock/mozorg/util.py
- bedrock/settings/base.py
- bedrock/settings/local.py-dist
No need for support for multiple accounts and keys.
> Bug 1309050: Update Twitter API to use one app credentials

- bedrock/base/templatetags/helpers.py
- bedrock/base/tests/test_waffle.py
- bedrock/base/waffle.py
- bedrock/firefox/tests/test_base.py
- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- docs/install.rst
* Avoid import issues by providing a separate module for this function
* Document using feature flipping within Python
> Move switch function for use in python code

- bedrock/security/templates/security/partials/cve.html
- bedrock/security/tests/test_utils.py
- bedrock/security/utils.py
- media/css/security/security.less
A real effort to make these things look nice is coming in a near-future sprint.
> Some small improvements to MFSA YAML styling and function

- bedrock/security/management/commands/update_security_advisories.py
- bedrock/security/tests/test_commands.py
- bedrock/security/tests/test_utils.py
- bedrock/security/utils.py
Also MFSA YAML files can have blank or missing values for some keys.
> Fix bug 1311863: Do not delete updated MFSA files

- media/css/sandstone/sandstone-resp.less
Increased the input email width for mobile view. Decreased the .span_narrow of form-title by 1 unit & Increased the .span_narrow of form-submit by 1 unit for tablet.
https://bugzilla.mozilla.org/show_bug.cgi?id=1276217
Checked on only the contact page using the built-in options in Responsive Design Mode of Firefox.
> Fix Bug 1276217 - Visual regressions in default newsletter embed forms 

- docs/uitour.rst
> Update UITour docs to include Sync device count reporting

- bedrock/newsletter/templates/newsletter/recovery.html
- media/css/newsletter/newsletter.less
- Fixes a number of regressions that have happened over time.
- Clears floated form fields so error list no longer overlaps.
- Fixes button / form field overlap at medium screen widths.
- Improves responsive styling to better handle variable length strings for l10n.
https://bugzilla.mozilla.org/show_bug.cgi?id=1312538
- Test different screen widths, different locales.
- Test error message display.
> [fix bug 1312538] Improve layout for email submission with errors

- bedrock/mozorg/redirects.py
- tests/redirects/map_globalconf.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1313023
> [fix bug 1313023] Redirect /story to donate.mozilla.org

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- bedrock/settings/base.py
> Bug 1278981: Add service to sign Stub Attribution URL params

- README.md
Update the license info in `README.md` from MPL/GPL/LGPL tri-license to MPL 2.0.
> Update license to MPL 2

- .github/CONTRIBUTING.md
- README.md
Copied from:
https://github.com/mozilla/addons-server/blob/master/CODE_OF_CONDUCT.md
Thanks to @andymckay
> Add Code of Conduct notice

- bedrock/newsletter/views.py
- bin/cron.py
Also change blog updates to hourly
> Email pref center no hit basket in maint. mode.

- static/.gitignore
@pmac r?
Fixing a mistake I made in #4462 where I meant to remove the reference to `.hcaccess`
> Don't ignore .gitignore in /static directory

- tests/functional/test_internet_health.py
> Skip blog feed test until cron has run in production

- bedrock/mozorg/redirects.py
- tests/redirects/map_globalconf.py
- tests/redirects/map_htaccess.py
redirect /support/thunderbird to appropiate sumo section.
https://bugzilla.mozilla.org/show_bug.cgi?id=682619
My local tests failed. Creating this PR for input.
> fix bug 682619. redirect /support/thunderbird to appropiate sumo section

- bedrock/foundation/urls.py
Switch can be enabled with the following env var:
```
SWITCH_SOM_2015=on
```
> Add switch for enabling the 2015 annual report

- bedrock/mozorg/templates/mozorg/about/leadership.html
Update Sylvie Veilleux's bio on the [leadership page](https://www.mozilla.org/en-US/about/leadership/).
[Bug 1323882](https://bugzilla.mozilla.org/show_bug.cgi?id=1323882)
Check if the bio copy is updated.
> Fix Bug 1323882 - Update Sylvie's bio on the Leadership Page

- Procfile
- bedrock/mozorg/management/commands/update_product_details_files.py
- bedrock/mozorg/tests/test_commands.py
- bedrock/security/management/commands/update_security_advisories.py
- bedrock/security/tests/test_commands.py
- bedrock/settings/base.py
- bedrock/utils/git.py
- bedrock/utils/migrations/0001_initial.py
- bedrock/utils/models.py
- bedrock/utils/tests/test_git.py
- docker/run-clock.sh
- etc/supervisor_available/cron_db.conf
This reverts commit d962ef4b771f8ee13ea071143a237f5a8c54e6e6 which itself reverted an earlier attempt at this but which caused some tests to fail. Let's try it again.
> Fix bug 1315082: Store git repo state in the db

- media/css/firefox/all.less
Fixed Search box responsive styling on /firefox/all page
https://bugzilla.mozilla.org/show_bug.cgi?id=1301363
> Fixed Search box responsive styling on /firefox/all page

- media/caldata/SlovakHolidays.ics
[Bug 1324212] - Update Slovak holiday calendar until 2020
Update Slovak holiday calendar until 2020
https://bugzilla.mozilla.org/show_bug.cgi?id=1324212
The ICS file is directly used as a Lightning calendar, so it is a valid ICS calendar file.
> [Bug 1324212] - update Slovak holiday calendar

- Jenkinsfile
> Fix jenkinsfile for master deploys

- Jenkinsfile
- bin/irc-notify.sh
- docker/jenkins/demo_deploy.sh
Add color and bold support to IRC messages. This also allows us (others) to use the notification from other scripts. I'm thinking I should extract this into a more useful and general purpose IRC notification script, but this will improve things for now.
> Move jenkins IRC notification to bash script

- docs/mozilla-pager.rst
- docs/mozilla-traffic-cop.rst
- media/js/base/mozilla-traffic-cop.js
Update docs and make small performance change to Traffic Cop lib.
> Improves Traffic Cop docs, and performs small refactor on lib.

- bin/tag-release.sh
- docs/pipeline.rst
> Add git remote CLI switch for tag-release.sh script

- media/css/foundation/annual2011.less
Fixed the broken mobile layout of 2011 annual report.
https://bugzilla.mozilla.org/show_bug.cgi?id=1329618
> Fix Bug 1329618 - Fixed the broken mobile layout of 2011 annual report.

- docs/firefox-accounts.rst
Adds bit to the FxA docs to get things working w/CSP.
> Update FxA docs.

- bedrock/mozorg/templates/mozorg/home/home.html
- bedrock/mozorg/templates/mozorg/home/includes/nav.html
- media/css/mozorg/home/brand-takeover.scss
- media/css/mozorg/home/home.scss
- media/js/mozorg/home/brand-takeover.js
- tests/pages/home.py
We need to merge / push this before tomorrow as when we flip the switch off again, the old branding will come back.
> [bug 1331048] Remove brand switch from main navigation

- tests/pages/home.py
Hopefully fixes https://ci.us-west.moz.works/job/bedrock_integration_tests/1494/
> Fix home page tests for brand popup

- bedrock/mozorg/templates/mozorg/mpl/2.0/faq.html
Add another question to the MPL 2.0 FAQ, as agreed by Gerv and Luis.
None
N/A
> Add Q26 about physical distribution

- media/css/thunderbird/landing.less
- media/css/thunderbird/start.less
there were a CSS linting errors and I fixed them 
https://bugzilla.mozilla.org/show_bug.cgi?id=1332678
there was a problem bug 1333938 and I switched newsletter tests false in my .env
>  [fix Bug 1332678] fixed CSS linting errors

- bedrock/foundation/templates/foundation/base-resp.html
- bedrock/foundation/templates/foundation/index.html
Fixing hardcoded strings + donate URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1331479
> Bug 1331479 - /foundation localization fixes

- media/js/mozorg/internet-health/privacy-day-egg.js
Adds a GA event when the egg is activated.
> [bug 1332477] Add analytics for easter egg

- media/js/mozorg/internet-health/privacy-day-egg.js
Minor corrections to work better with GTM.
> [bug 1332477] Amend analytics for easter egg

- bedrock/settings/base.py
> [bug 1331069] Remove Flashtalking pixel

- bedrock/settings/base.py
For my piece of mind more than anything else :)
> [bug 1279291] Default to stub attribution rate of 1 for DEV only

- media/js/mozorg/home/home.js
Just caught this after merging #4618
> [bug 133513] Fix JS error on home page scroll detection

- media/css/mozorg/about-base.less
- media/css/mozorg/about-forums.less
- media/css/mozorg/about-lean-data.less
- media/css/mozorg/about.less
- media/css/mozorg/contact-spaces-oldie.less
- media/css/mozorg/contact-spaces.less
- media/css/mozorg/contribute/contribute-base.less
- media/css/mozorg/contribute/friends.less
- media/css/mozorg/contribute/studentambassadors/landing.less
- media/css/mozorg/history-slides.less
- media/css/mozorg/itu.less
- media/css/mozorg/manifesto.less
- media/css/mozorg/mission.less
- media/css/mozorg/partnerships.less
- media/css/mozorg/projects/calendar.less
Fix CSS linting errors for /media/css/mozorg/
https://bugzilla.mozilla.org/show_bug.cgi?id=1332674
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/mozorg/**/*.less"
./node_modules/gulp-stylelint/node_modules/.bin/stylelint "media/css/mozorg/**/*.scss"
> [fix bug 1332674] Fix CSS linting errors for /media/css/mozorg/

- docker/jenkins/utils.groovy
@pmac apologies for missing this before merging
> Fix DEIS_APPS in pushPrivateReg

- Jenkinsfile
- bin/irc-notify.sh
- docker/jenkins/utils.groovy
- jenkins.yml
* Use the full app URL with suffix for integration tests
* Better failure message for deployment testing stage
* Fix demo deploy success notification
* Output usable URL for stage and prod deis apps during deployment
* Deploy IRC notifications use BlueOcean build URLs
* Only push requested apps to private registry
> Jenkinsfile deployment improvement

- Jenkinsfile
Was injecting the string "null" instead of "".
> Fix deployment app suffix and url

- bedrock/thunderbird/templates/thunderbird/start/base-resp.html
> [fix bug 1337446] Add google analytics to Thunderbird start page

- Jenkinsfile
- docker/jenkins/utils.groovy
> Use demo app alias URLs in IRC notifications

- docs/uitour.rst
> [typo] Remove extra dot.

- bedrock/firefox/redirects.py
- tests/redirects/map_globalconf.py
- tests/redirects/test_urls.py
> Remove /firefox/panorama redirect and test

- bedrock/thunderbird/templates/thunderbird/start/base-resp.html
> [bug 1337446] Add site js dependency for google analytics

- bedrock/thunderbird/templates/thunderbird/start/base-resp.html
> [bug 1337446] Add common js dependency to thunderbird start page for GA 

- bedrock/settings/base.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1338072
> Bug 1338072 - Add fallback for zh-HK

- media/css/firefox/firstrun/new-firstrun.less
- media/js/base/mozilla-fxa-iframe.js
- media/js/firefox/firstrun/new-firstrun.js
- tests/unit/spec/base/mozilla-fxa-iframe.js
@shane-tomlinson @craigcook
- the skip button fades on the form in the iframe being engaged, and solidifies on it being unengaged. 
- the skip button dissapears altogether one a form has been submitted
https://bugzilla.mozilla.org/show_bug.cgi?id=1338348
> Hide and show skip button for new /firstrun

- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
> update hall of fame with all of 2016

- Jenkinsfile
- docker/bin/build_images.sh
- docker/bin/check_if_tag.sh
- docker/bin/cleanup_after_functional_tests.sh
- docker/bin/docker_build.sh
- docker/bin/push2deis.sh
- docker/bin/push2dockerhub.sh
- docker/bin/push2privateregistries.sh
- docker/bin/run_integration_tests.sh
- docker/bin/run_linkchecker.sh
- docker/bin/run_tests.sh
- docker/bin/set_git_env_vars.sh
- docker/envfiles/master.env
- docs/pipeline.rst
- jenkins.yml
- jenkins/utils.groovy
* Add ability to toggle smoke tests
* Add ability to toggle deployment
* Add ability to toggle integration tests
* Add ability to toggle pushing docker images to public registry
* Add branch name to deploy image
* Add bash utility for setting git environment variables
> Add more options to jenkins.yml for deployments

- tests/functional/newsletter/test_newsletter_embed.py
- tests/functional/test_home.py
- tests/functional/test_l10n.py
- tests/functional/test_navigation.py
I meant to re-enable these tests in #4663 but totally forgot.
> [bug 1335120] Re-enable home page functional tests for IE

- bedrock/firefox/firefox_details.py
- bedrock/firefox/tests/test_firefox_details.py
- bedrock/mozorg/tests/test_views.py
- bedrock/settings/base.py
My proposal for how to most easily control funnelcake configuration with environment variables.
> Bug 1345467: Allow per experiment configuration of funnelcake platforms and locales

- bedrock/foundation/templates/foundation/annualreport/2011.html
- bedrock/mozorg/templates/mozorg/about/history-details.html
> Fix Bug 1347697 - /about/history/details/ throwing 500s

- bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Using [grip][] now to better ensure that the result matches the expection from Github as close as possible.
[grip]: https://github.com/joeyespo/grip
> Fix bug 1343200: Use a better tool to process policy markdown

- bedrock/settings/base.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1346687
> Fix Bug 1346687 - Enable be on production for mozilla.org

- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
> name missing from hall of fame. adding.

- bedrock/mozorg/templates/mozorg/about/leadership.html
Also updates A. Plohman’s title
https://bugzilla.mozilla.org/show_bug.cgi?id=1348376
https://bugzilla.mozilla.org/show_bug.cgi?id=1348083
> [fix bug 1348376] Update titles for D. Bryant and E. Rescorla

- bedrock/mozorg/templates/mozorg/about/leadership.html
Corrected titles and updates to both bios.
https://bugzilla.mozilla.org/show_bug.cgi?id=1348376
> [fix bug 1348376] Correct titles/bios for Bryant and Rescorla

- media/css/sandstone/sandstone-resp.less
- media/css/sandstone/sandstone.less
Fixes: https://www-dev.allizom.org/en-US/firefox/new/
> [bug 1342235] Fix default footer heading color for sandstone

- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
Simple update of bug bounty HTML stuff
> Update Bug Bounty for Q4 2016

- bedrock/mozorg/templates/mozorg/about/leadership.html
New bio for Chris. This page is not localized.
https://bugzilla.mozilla.org/show_bug.cgi?id=1350978
> [fix bug 1350978] Update Chris Beard’s leadership bio

- bedrock/settings/base.py
- bedrock/wordpress/api.py
- bedrock/wordpress/management/commands/update_wordpress.py
- bedrock/wordpress/migrations/0001_initial.py
- bedrock/wordpress/models.py
- bedrock/wordpress/tests/test_api.py
- bedrock/wordpress/tests/test_data/media_75.json
- bedrock/wordpress/tests/test_data/posts.json
- bedrock/wordpress/tests/test_data/tags.json
- bedrock/wordpress/tests/test_data/tags_all.json
- bedrock/wordpress/tests/test_models.py
- bedrock/wordpress/tests/test_views.py
- bedrock/wordpress/views.py
- bin/cron.py
- bin/sync-all.sh
- requirements/dev.txt
Adds a generic view to include blog posts in a template context as well as methods on the model manager to easily filter by tags and blogs. If a blog post has featured media, you can get the URL to whatever size you want via a helper method on the model object.
> Bug 1353794: Add app to consume and store wordpress data

- bedrock/base/templates/base-pebbles.html
- bedrock/base/templates/base-resp.html
- bedrock/base/templates/base.html
- bedrock/base/templates/includes/stat_counter.html
- bedrock/firefox/templates/firefox/australis/firstrun.html
- bedrock/firefox/templates/firefox/australis/whatsnew.html
- bedrock/firefox/templates/firefox/desktop/customize.html
- bedrock/firefox/templates/firefox/features.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-horizon.html
- bedrock/firefox/templates/firefox/firstrun/firstrun.html
- bedrock/firefox/templates/firefox/firstrun/new-firstrun.html
- bedrock/firefox/templates/firefox/firstrun/ravioli.html
- bedrock/firefox/templates/firefox/firstrun/yahoo-retention.html
- bedrock/firefox/templates/firefox/releases/release-notes.html
- bedrock/firefox/templates/firefox/sync.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-42.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-50.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-zh-tw-49.html
- bedrock/mozorg/templates/mozorg/about.html
- bedrock/mozorg/templates/mozorg/plugincheck.html
- bedrock/settings/base.py
- bedrock/settings/static_media.py
- media/js/base/stat-counter.js
Adding analytics tool as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1352821
https://bugzilla.mozilla.org/show_bug.cgi?id=1352821
> [Fix bug 1352821] Add additional analytics tool

- media/caldata/calendars.json
The dates were not changed for this holiday calendar
https://bugzilla.mozilla.org/show_bug.cgi?id=1324212
> Bug 1324212 - Fix dates for Slovak holiday calendar

- media/css/base/global-nav.less
- media/css/pebbles/components/_global-nav.scss
https://bugzilla.mozilla.org/show_bug.cgi?id=1362056
> [fix bug 1362056] Reduce empty whitespace at top of global nav

- bedrock/firefox/templates/firefox/features/index.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1361494
> [fix bug 1361494] Add Optimizely to /firefox/features/ page

- bedrock/firefox/templates/firefox/hub/home.html
Fixes incorrect 3rd party quote attribution.
https://bugzilla.mozilla.org/show_bug.cgi?id=1363488
> [fix bug 1363488] Fx Hub home - fix 3rd party quote attribution

- bedrock/settings/__init__.py
- bedrock/settings/base.py
Everything goes to STDOUT depending on the LOG_LEVEL setting.
> Fix bedrock's logging config

- media/js/hubs/sub-nav.js
This isn't causing any issues that I can tell of, but something that seems to be a simple fix anyway.
https://bugzilla.mozilla.org/show_bug.cgi?id=1369047
> [fix bug 1369047] Fix JS error in sub-nav.js on IE8

- jenkins/branches/tokyo.yml
I pushed this file to the tokyo branch to trigger a dev deploy. Merging to master will not have an effect directly, but will be available for arbitrary deployments in the future based off the new master.
> Push tokyo dev

- media/css/legal/legal.less
https://bugzilla.mozilla.org/show_bug.cgi?id=1372320
> [fix bug 1372320] Update legal-docs

- bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
- bedrock/security/templates/security/web-bug-bounty.html
Remove a site from the Bug Bounty list and clarify an exception.
> Remove Grafana and tweak wording on browser specificity

- bedrock/base/tests/test_views.py
- bedrock/base/views.py
- bedrock/settings/base.py
- bedrock/urls.py
https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-CloudFlare-IP-Geolocation-do-
> Switch to a bedrock geoip service using our CDN headers

- docker/dockerfiles/bedrock_l10n
> Fix locale dir copy in l10n dockerfile

- docs/uitour.rst
Update profileCreatedWeeksAgo and profileResetWeeksAgo.
> [bug 1343510] Update UITour documentation.

- bedrock/firefox/templates/firefox/products/android.html
> [bug 1363300] Fix copy on /firefox/android for l10n

- media/css/hubs/_sub-nav.scss
The Fx subnav was 2px off and it was driving me crazy.
Not deserving of one.
Make sure it lines up and doesn't cause any regressions.
> [no bug] Fix small padding issue on Fx subnav

- bedrock/mozorg/templates/mozorg/moss/_alittlebitmore.html
- bedrock/mozorg/templates/mozorg/moss/base.html
- bedrock/mozorg/templates/mozorg/moss/index.html
- bedrock/mozorg/templates/mozorg/moss/mission-partners-india.html
- bedrock/mozorg/urls.py
plus other tweaks to reflect the way MOSS is now running
MOSS is launching a new track focussed on India; this content supports that launch. It needs to be reviewed and staged, but not pushed live until the launch date, which will be in early August. (We hope a Hindi translation of some of this content will follow.)
None
Tested locally by me
> First version of new Global Mission Partners: India pages

- bedrock/settings/base.py
add locale azz to mozilla.org production
https://bugzilla.mozilla.org/show_bug.cgi?id=1383220
https://www-dev.allizom.org/azz/
> fix bug 1383220, enable locale azz on production for mozilla.org

- media/js/base/mozilla-traffic-cop.js
Brings in the latest version of Traffic Cop. We can now do experiments that execute arbitrary JS instead of performing a redirect.
https://github.com/mozilla/trafficcop/issues/7
Make sure existing experiments work with no regressions.
The following URL (updated with latest version of TC) has an experiment running for IE 10 and greater (with DNT off, geolocated in US). You should get a funnelcake variation within a few tries:
https://bedrock-demo-jpetto-tc.us-west.moz.works/en-US/firefox/new/
I tested this on a VM and the experiment ran successfully.
> Updates Traffic Cop to latest release (customCallback ability).

- bedrock/etc/models.py
- bedrock/etc/redirects.py
- bedrock/etc/tests.py
- bedrock/etc/urls.py
- bedrock/etc/views.py
- bedrock/privacy/redirects.py
- bedrock/settings/base.py
- bedrock/urls.py
Adds scaffolding for new `bedrock/etc` app.
https://bugzilla.mozilla.org/show_bug.cgi?id=1383115
Make sure all files added are required, and no-indexing is set up correctly.
> [fix bug 1383115] Add new bedrock/etc app for one-off pages.

- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
Updates the Web Bug Bounty HoF for Q2 2017.
N/A
N/A
> Update Web Bug Bounty for Q2 2017

- bedrock/firefox/templates/firefox/new/onboarding/scene1.html
Spotted some left-over from #5036
> [bug 1363499] Remove search retention funnelcake experiment code

- bedrock/mozorg/templates/mozorg/about/leadership.html
Removes John McSorley
https://bugzilla.mozilla.org/show_bug.cgi?id=1392279
N/A
> removed John McSorley

- README.md
> Add link to in readme to mozilla.org

- bin/run-for-integration-tests.sh
- docker/bin/run_integration_tests.sh
> Update product-details for code docker image

- bedrock/etc/templates/etc/firefox/retention/thank-you-a.html
- bedrock/etc/templates/etc/firefox/retention/thank-you-b.html
- media/css/etc/firefox/retention/thank-you-a.scss
- media/css/etc/firefox/retention/thank-you-b.scss
- media/css/etc/firefox/retention/thank-you.scss
Localize the Firefox retention thank you pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1388860
> Wrap Firefox retention thank you pages in l10n blocks.

- bedrock/settings/base.py
> add locale trs to mozilla.org per bug1393562

- bedrock/privacy/templates/privacy/notices/firefox-quantum.html
- bedrock/privacy/views.py
- bedrock/settings/static_media.py
- media/css/privacy/firefox-privacy.scss
- media/img/privacy/arrowhead-down-16.svg
- media/img/privacy/arrowhead-up-16.svg
- media/js/privacy/firefox-privacy.js
This adds the new revised Firefox privacy policy page located at privacy/firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=1396007
No special testing scenarios.
> Fix Bug 1396007, adds revised Firefox privacy policy page

- bedrock/firefox/views.py
> Fix check for Dev Edition firstrun and whatsnew lang file

- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2017.html
Small copy updates per legal request
https://bugzilla.mozilla.org/show_bug.cgi?id=1381094#c20
> Fix Bug 1381094, small copy updates to transparency report

- bedrock/newsletter/forms.py
- bedrock/newsletter/templates/newsletter/includes/form.html
- bedrock/newsletter/tests/test_forms.py
- bedrock/newsletter/tests/test_views.py
- bedrock/newsletter/views.py
- media/css/mozorg/home/home-b.scss
- media/css/mozorg/home/home.scss
- media/css/newsletter/fxnewsletter-subscribe.less
- media/css/newsletter/moznewsletter-subscribe.less
- media/css/newsletter/newsletter-developer.scss
- media/css/newsletter/newsletter-firefox.scss
- media/css/newsletter/newsletter-mozilla.scss
- media/css/pebbles/components/_newsletter.scss
- tests/functional/contribute/test_friends.py
- tests/functional/firefox/test_ios_testflight.py
- tests/functional/newsletter/test_newsletter_embed.py
- tests/functional/newsletter/test_newsletter_landing.py
- tests/pages/contribute/friends.py
- tests/pages/firefox/ios_testflight.py
- tests/pages/newsletter/base.py
- tests/pages/regions/newsletter.py
Reverts mozilla/bedrock#5105
Discussion in governance is not complete. We should restore this until a final decision is made.
> Revert "[fix bug 1396949] Remove format option from newsletter forms."

- tests/pages/internet_health.py
Fixes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/584/pipeline/
> [bug 1399585] Update Internet Health hub functional test

- tests/functional/firefox/test_quantum.py
- tests/pages/firefox/quantum.py
- Adds some basic functional tests for the new Firefox Quantum preview page
https://bugzilla.mozilla.org/show_bug.cgi?id=1404275
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/87/pipeline
> [fix bug 1404275] Create functional tests for the /firefox/quantum/ page

- bedrock/firefox/templates/firefox/hub/home.html
> [fixes #5163] Update Vogue links to https on Firefox home page

- media/css/privacy/firefox-privacy.scss
Bryant provided some feedback on the current implementation of the design for the new privacy policies. You can see his suggestions here[1] and here[2]. There are some things I did not do, and you can see my explanation for why, here[3].
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1396007#c99
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1396007#c101
[3] https://bugzilla.mozilla.org/show_bug.cgi?id=1396007#c103
https://bugzilla.mozilla.org/show_bug.cgi?id=1396007
Ensure there are no regressions because of the new styling.
> Fix Bug 1396007, visual updates to new privacy policy based on design feedback

- README.md
fixing small typos in README.md
> fixing small typos in README.md

- bedrock/base/tests/test_urlresolvers.py
- bedrock/base/urlresolvers.py
Before this change for pages that have an en-GB translation, other non-supported english locales (e.g. en-CA) would redirect to en-GB because it is first aphabetically. This should respect CANONICAL_URLS since we say in the header tags that en-CA's URL is the en-US variant.
> Fix bug 1405103: Respect CANONICAL_URLS for unsupported URL locales

- bedrock/firefox/templates/firefox/products/developer-quantum.html
I missed that the paragraphs was in the incorrect order during code review 😿 This pull requests resolves that.
https://github.com/mozilla/bedrock/issues/5196
Ensure the order of the paragraphs matches the conditional logic
> Swaps paragraphs to correctly fit the conditional

- docker/dockerfiles/bedrock_build
Updates from the upstream repo:
https://github.com/nodejs/docker-node/blob/d3ca6d89aefc1cd354819d85d9e1a91f773e7839/6.11/slim/Dockerfile
> Pull in latest versions of Nodejs and Yarn

- bedrock/settings/base.py
Listed changes in https://bugzilla.mozilla.org/show_bug.cgi?id=1399530
> Bug 1399530 - Update donate currencies and values

- bedrock/security/templates/security/bug-bounty.html
- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
> update hall of fame for q3

- README.md
> Fixed A Comma

- bedrock/firefox/templates/firefox/developer-quantum-whatsnew.html
- media/css/firefox/developer-quantum-whatsnew.scss
Post launch copy updates for developer whatsnew page
https://bugzilla.mozilla.org/show_bug.cgi?id=1399276
Ensure no regressions
Ensure all new strings are correctly wrapped in conditionals and for l10n
> Fix Bug 1399276, post launch content update for dev whatsnew

- bedrock/firefox/templates/firefox/developer-quantum-firstrun.html
- media/css/firefox/developer-quantum-firstrun.scss
Post launch copy updates for developer firstrun page
https://bugzilla.mozilla.org/show_bug.cgi?id=1399277
Ensure no regressions
Ensure all new strings are correctly wrapped in conditionals and for l10n
> Fix Bug 1399277, post launch content updates for dev firstrun

- docs/install.rst
> Update /docs/install.rst. Command on Windows

- bedrock/newsletter/forms.py
- bedrock/newsletter/tests/test_forms.py
No longer require a valid URL, but do limit max length.
> Fix bug 1413953: Accept more source_url values

- docker/bin/apt-install
- docker/dockerfiles/bedrock_base
Re https://github.com/mozmeao/infra/issues/641
> Switch to using official Python base docker image

- media/js/base/dnt-helper.js
Found by @emceeaich in https://github.com/mozilla-bteam/bmo/pull/265#pullrequestreview-75300820
> (no bug) Fix a typo in dnt-helper.js

- bedrock/firefox/templates/firefox/features/quantum/fast.html
- bedrock/firefox/templates/firefox/features/quantum/independent.html
- bedrock/firefox/templates/firefox/features/quantum/index.html
- bedrock/firefox/templates/firefox/features/quantum/private-browsing.html
Updates open graph images for quantum.
https://bugzilla.mozilla.org/show_bug.cgi?id=1415607
Make sure I didn't miss anything?
> [fix bug 1415607] Update og images for quantum.

- bedrock/firefox/templates/firefox/firstrun/firstrun_quantum.html
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/css/firefox/firstrun/firstrun_quantum.less
- media/img/firefox/firstrun-quantum/quantum-logo.svg
- media/js/firefox/firstrun/firstrun_quantum.js
r=@craigcook 
Redesign firstrun "wow moment"
https://bugzilla.mozilla.org/show_bug.cgi?id=1397532
- Whoever is responsible for ` /media/css/base/notification-banner.less` (see line 157) will need to add new "special hackz" for this page ;D
> Bug 1397532 - New quantum firstrun animation.

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- tests/functional/firefox/test_quantum.py
> [fix bug 1415599] Redirect /firefox/quantum/ to /firefox/

- .gitignore
- bedrock/firefox/templates/firefox/hub/home-quantum.html
Updates copy to be more inclusive.
@peiying2 has been made aware via IRC.
> Updates new Fx home page copy to be more inclusive.

- media/css/firefox/new/quantum/common.scss
Fixes minor regression noticed in https://github.com/mozilla/bedrock/commit/e0b2791d2795b1f97a2724a3a71e59c12c83bae6#commitcomment-25545129
Make sure this causes no other regressions?
> [bug 1397381] Fix footer small link styling on /new

- bedrock/firefox/templates/firefox/new/quantum/scene1.html
> Remove hard-coded locale in SUMO link on/firefox/new/

- bedrock/firefox/templates/firefox/hub/home-quantum.html
Updates copy based on request from MoFo.
https://bugzilla.mozilla.org/show_bug.cgi?id=1416805
> [fix bug 1416805] Update copy on Fx home page.

- bedrock/mozorg/templates/mozorg/about/leadership.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1416961
> [fix bug 1416961] Update Chris Beard’s bio on leadership page

- bedrock/mozorg/templates/mozorg/home/home-quantum.html
Updates tagline on the home page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1417983
> [fix bug 1417983] Update homepage tagline.

- requirements/prod.txt
The current New Relic plugin is old, this PR updates to the latest version.
https://github.com/mozmeao/infra/issues/640
> update to latest new relic

- tests/functional/firefox/test_home.py
- tests/pages/firefox/home.py
Updates some base functional tests for the updated Firefox home page.
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/143/pipeline/
> [fix bug 1416710] Update functional tests for Firefox home page

- tests/functional/firefox/test_home.py
Testing to see if is causing the sporadic Jenkins issues https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/prod/194/pipeline/
> Remove Firefox smoke test

- jenkins/default.groovy
- jenkins/utils.groovy
Hopefully this will improve the stage and prod deployment success rate.
> Add more retry and better handling to integration tests

- media/css/mozorg/history-slides.less
Noticed this old logo while working on something else. This page is very legacy, but easy enough to update the logo.
Newp.
Check for silly mistakes?
> [no bug] Update Fx logo on /about/history slides.

- bedrock/base/templatetags/helpers.py
- bedrock/base/tests/test_helpers.py
- bedrock/mozorg/templates/mozorg/home/includes/fundraiser-eoy2017.html
- bedrock/mozorg/tests/test_views.py
- bedrock/mozorg/views.py
Adds a helper function to get donate params for a view.
https://bugzilla.mozilla.org/show_bug.cgi?id=1425886
> [fix bug 1425886] Add donation params helper function.

- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
Couple minor updates came in via email after making the Q3 Hall of Fame update.
> Couple minor post-Q3 bug bounty HoF revisions

- bedrock/firefox/templates/firefox/new/reggie-watts/base.html
- bedrock/firefox/templates/firefox/new/reggie-watts/scene1.html
- bedrock/firefox/templates/firefox/new/reggie-watts/scene2.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
Opens up reggiewatts campaign for de locale (pending completed localization).
https://bugzilla.mozilla.org/show_bug.cgi?id=1413995#c13
Ensure no regressions and that all is in place for localization.
> [fix bug 1413995] Open reggiewatts /new variation for de locale.

- bedrock/security/templates/security/bug-bounty/hall-of-fame.html
> update hall of fame for 4th quarter 2017

- docker/bin/cleanup_after_functional_tests.sh
- docker/bin/run_integration_tests.sh
- docker/bin/set_git_env_vars.sh
Something is broken. I'll investigate later.
> Revert deployment changes

- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
Just the usual hall of fame updates. Not much to it, thanks!
> Q4 2017 Hall of Fame changes

- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
A couple more late respondents for the Q4 2017 list. Thanks!
> Couple more Q4 2017 bounty people

- bedrock/redirects/tests/test_util.py
- bedrock/redirects/util.py
Found errors via Sentry:
https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/611704/
> Fix errors with redirects with merge_queries=True

- bedrock/foundation/templates/foundation/mocosc.html
- bedrock/mozorg/templates/mozorg/about/leadership.html
Changes Mitchell's title from "Executive Chairwoman" to just "Chairwoman" and also adds some new bits to her bio.
https://bugzilla.mozilla.org/show_bug.cgi?id=1425359
Check for typos?
> [fix bug 1425359] Update Mitchell Baker’s title and bio

- bedrock/firefox/templates/firefox/firstrun/base-pebbles.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/css/base/mozilla-fxa-iframe.scss
- media/css/firefox/firstrun/firstrun-quantum.scss
- Converts current `/firstrun` page from Sandstone to Pebbles.
- Improves responsive layout for narrow screens.
- Adds RTL styles.
https://bugzilla.mozilla.org/show_bug.cgi?id=1439718
Demo: https://www-demo3.allizom.org/firefox/58.0/firstrun/
> [fix bug 1439718] Convert /firstrun from Sandstone to Pebbles

- bedrock/firefox/templates/firefox/new/reggie-watts/base.html
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/templates/firefox/new/wait-face/base.html
Moving this smaller bit of #5463 to this PR so that it can get in more quickly than that larger and more disruptive change.
> Bug 1438302: Remove canonical and hreflang from scene2

- tests/functional/test_link_hreflang_tags.py
Fixes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/874/pipeline
> [bug 1442327] Update hreflang headless tests

- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
Updates copy for one variation.
> [fix bug 1441597] Update copy for FxA copy test.

- bedrock/base/templates/includes/site-footer.html
- bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1443881
> [fix bug 1443881] Update Instagram link in footer

- bedrock/settings/static_media.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1444996
> [fix bug 1444996] Subnav on /technology is not sticky

- bedrock/newsletter/tests/test_views.py
- bedrock/newsletter/views.py
Otherwise basket will guess at a best language.
> Always send lang with newsletter preferences updates

- bin/db_s3_utils.py
This should mean easier use of db download script for developers.
> Use python's sha256 instead of requiring a shell program

- bin/bootstrap.sh
- docs/contribute.rst
- docs/index.rst
- docs/install.rst
* Add bootstrap.sh command and use in install docs
> Update docs to reflect current reality

- bedrock/firefox/templates/firefox/firstrun/facebook-container.html
- media/css/firefox/firstrun/firstrun-facebook-container.scss
Small design tweaks to the Facebook container `/firstrun` page.
Design comments given in Slack.
> [fix bug 1450106] Design tweaks for FB container firstrun page.

- docs/install.rst
- docs/l10n.rst
- docs/pipeline.rst
> Doc updates about dev env defaults

- docker/dockerfiles/bedrock_build
Should help with CI failures due to failed Docker builds.
> Update NodeJS installs in builder image

- media/css/firefox/new/portland.scss
Small UX updates to this campaign page:
- Remove gradient from text in hopes of fixing intermittent invisible text
- Make purple border *almost* fill the screen for big enough viewports
- Make font sizes slightly smaller
https://bugzilla.mozilla.org/show_bug.cgi?id=1454502
Ensure no regressions, and make sure page still looks good on older IE.
> [fix bug 1454502] Update /new Portland variation UX.

- bedrock/security/management/commands/update_security_advisories.py
- bedrock/security/migrations/0005_mitrecve_mfsa_ids.py
- bedrock/security/models.py
> Add MFSA URLs to CVE feed entries

- bedrock/mozorg/templates/mozorg/about/leadership.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1459063
> [fix bug 1459063] Update Mitchell Baker’s bio on leadership page

- bedrock/firefox/templates/firefox/enterprise/index.html
- tests/pages/firefox/enterprise.py
Update the /enterpise tests to reflect the updated CTA.
Bug 1458036
> Bug 1458036: Update test to reflect new CTA.

- bedrock/firefox/templates/firefox/enterprise/signup-thanks.html
- bedrock/firefox/templates/firefox/organizations/organizations.html
Copy tweaks to /enterprise and /organizations.
https://bugzilla.mozilla.org/show_bug.cgi?id=1458040
https://bugzilla.mozilla.org/show_bug.cgi?id=1460744
Closes https://github.com/mozilla/bedrock/issues/5683
Replaces #5686
> Fix Bug 1460744, 1458040 Copy tweaks to /enterprise and /organizations.

- bedrock/grants/templates/grants/index.html
This PR is to add a new line and link in the grants page: 
Academic Research: Learn more about academic research grants program on this page.
> fixed bug 1459079 update copy

- bedrock/mozorg/templates/mozorg/contact/spaces/portland.html
Update space page for Portland
https://bugzilla.mozilla.org/show_bug.cgi?id=1461500
> [Fix bug 1461500] Update Portland space page

- bedrock/security/management/commands/update_security_advisories.py
- bedrock/security/models.py
- bedrock/security/tests/test_models.py
> Add product and version info to security CVE feed descriptions

- bedrock/base/templates/base-protocol.html
> Fix one template for css bundle use that slipped through

- bedrock/firefox/templates/firefox/organizations/organizations.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1425784#c20
> Highlight the GPO support

- bin/deploy.sh
- jenkins/branches/iowa-a-prod.yml
- jenkins/branches/iowa-a.yml
- jenkins/default.groovy
- jenkins/global.yml
- jenkins/utils.groovy
Add iowa-a deployment based on git-sync-operator
#5762
https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/iowa-a/17/pipeline
> Add iowa-a deployment based on git-sync-operator for #5762

- tests/functional/firefox/test_accounts_features.py
- tests/pages/firefox/accounts_features.py
Fixes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1058/pipeline
https://bugzilla.mozilla.org/show_bug.cgi?id=1457004
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/196/pipeline/
> [bug 1457004] Update functional tests for /firefox/accounts/features/ page

- bin/deploy.sh
See error in https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1077/pipeline/
> Fix source of set_git_env_vars.sh in deploy.sh

- Makefile
Add `-f` to `git submodule update` in `make submodules`
> Force git sumodule update

- bin/deploy.sh
Fix issue seen in https://ci.us-west.moz.works/job/bedrock_multibranch_pipeline/job/master/1089
> Fix DEPLOYMENT_NAME to pull yaml from $CLUSTER_NAME subdir

- bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
There were some Markdown -> HTML rendering issues that were discovered on dev.
> Bug 1470221: Formatting fixes for PKI Policy 2.6

- bedrock/mozorg/templates/mozorg/home/home-en.html
Fixes https://github.com/mozilla/bedrock/issues/5921
> Update pocket card dates on the home page (Fixes #5921)

- .gitignore
- bin/upload-staticfiles.sh
- docker/bin/build_staticfiles.sh
- jenkins/default.groovy
This copies the files out of the docker container and uploads them to the stage and prod s3 buckets when a prod deploy is happening (stage and prod are both deployed during a prod deployment). 
/cc @jpetto @jgmize @metadave
> Upload static media to s3 on deploy

- docs/abtest.rst
- docs/index.rst
> Add a/b testing to docs

- bedrock/mozorg/templates/mozorg/about/leadership.html
Update Mark Surman bio on leadership page 
https://github.com/mozilla/bedrock/issues/5978
> update Mark Surman bio with correct formatting.

- bedrock/base/management/commands/update_www_config.py
- bedrock/base/middleware.py
- bedrock/base/views.py
- bedrock/mozorg/middleware.py
- bedrock/mozorg/tests/test_middleware.py
- bedrock/settings/base.py
- bin/cron.py
Move to `CLUSTER_NAME` from the environment and `APP_NAME`
derived from `HOSTNAME`.
> Fix #5983: Remove DEIS_* settings

- bedrock/mozorg/templates/mozorg/about-en.html
- bedrock/mozorg/templates/mozorg/home/home-en.html
- package.json
- yarn.lock
Update Protocol library and add new element to anywhere we used the billboard component.
> Update Protocol and add new element to billboards

- bedrock/mozorg/templates/mozorg/internet-health/index.html
Changing the HTML this often negatively impacts cache and potentially SEO.
> Fix #6016: Remove server-side shuffle of internet-health issues

- bedrock/firefox/views.py
Fixes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1156/pipeline
> Import switch for /firefox/new/ in views.py

- bedrock/security/templates/security/bug-bounty.html
- bedrock/security/templates/security/bug-bounty/faq.html
- bedrock/security/templates/security/client-bug-bounty.html
- bedrock/security/templates/security/web-bug-bounty.html
Set h1 as <title> for bug bounty pages
https://github.com/mozilla/bedrock/issues/6062
> Set h1 as <title> for bug bounty pages

- bedrock/mozorg/templates/mozorg/home/home-en.html
Every line but the last must end with a , not a ;
https://github.com/mozilla/bedrock/issues/5741
> Fixing typo in js+ld

- bedrock/newsletter/templates/newsletter/developer.html
Stages copy change correctly.
#5935
> Fix #5935: Reverse copy in l10n_has_tag() on newsletter/developer

- .gitignore
- bedrock/base/templates/macros.html
- bedrock/mozorg/templates/mozorg/fxa-iframeless-test.html
- bedrock/mozorg/urls.py
- bedrock/settings/base.py
- docs/firefox-accounts-iframe.rst
- docs/firefox-accounts.rst
- docs/pipeline.rst
- media/css/base/mozilla-fxa-form.scss
- media/css/mozorg/fxa-iframeless-test.scss
- media/js/base/mozilla-fxa-form.js
- media/static-bundles.json
Adds iframe-less FxA form.
https://bugzilla.mozilla.org/show_bug.cgi?id=1446023
https://www-demo5.allizom.org/en-US/fxa-iframeless-test/
This PR is intended to only add the `macro` for this form. The test page will be removed prior to final review/merge.
> Bug 1446023 iframeless fxa form

- bedrock/firefox/templates/firefox/releases/system_requirements.html
Add channel to system requirements page title. Except if it's release, omit channel if it's release.
mozilla/bedrock/issues#6053
> Add channel to system requirements page title

- bin/slack-notify.sh
When failure occurs during prod build.
> Send additional slack message to alert channel

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- bedrock/settings/base.py
See https://github.com/mozilla-services/stubattribution/issues/82
> Truncate stub attribution code if over max length

- bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Also update the process in a comment on the page to include anchor generation in future updates.
> Fix bug 1485175: Add anchors to certs policy page

- bedrock/base/templates/includes/site-footer.html
All links in the footer should be in the link graph as it makes sense for users and crawlers to click and follow them.
> Removing nofollow from footer

- bedrock/base/templates/includes/protocol/site-footer.html
https://github.com/mozilla/bedrock/pull/6113
> Removing nofollow from footer links

- bedrock/mozorg/templates/mozorg/about/policy/lean-data.html
- media/css/mozorg/about-lean-data.less
There are some pre-existing alignment problems on mobile that I did not address.
> Move lean data off sandstone

- .gitignore
- bedrock/mozorg/templates/mozorg/robots.txt
- bedrock/settings/base.py
- bedrock/sitemaps/utils.py
Also add system-requirements URLs to sitemap.
Fixes #6048
> Sitemap: exclude /firefox/*/all/, fix missing URLs, and add grants urls

- bedrock/mozorg/templates/mozorg/contact/communities/asia-south-pacific/india.html
> Fix link to mozillaindia.org

- bedrock/legal/templates/legal/terms/firefox-reality.html
- bedrock/legal/urls.py
- bedrock/privacy/templates/privacy/index.html
- bedrock/privacy/templates/privacy/notices/firefox-reality.html
- bedrock/privacy/urls.py
- bedrock/privacy/views.py
- media/css/privacy/privacy.less
Also pull latest legal-docs repo master.
> Fix #6179: Add Firefox Reality legal docs pages

- media/css/base/mozilla-fxa-form.scss
Remove fxa-form width. This should be handled on a per-page basis because it depends on where the form is placed. 
#6173 #6168
> Remove fxa-form width

- bedrock/newsletter/templates/newsletter/existing.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1483611
> [fix bug 1483611] Remove interest section from newsletter preferences page

- bedrock/firefox/templates/firefox/new/compare/scene1-chrome-2.html
- bedrock/firefox/templates/firefox/new/compare/scene1-edge-2.html
- bedrock/firefox/templates/firefox/new/compare/scene1-safari-2.html
- media/css/firefox/new/compare.scss
- Updates browser comparison tables with regard to Private Browsing mode features.
#6202
> Update SEM browser comparison tables (Fixes #6202)

- bedrock/settings/base.py
> Add 'tl' to list of production languages

- bedrock/newsletter/templates/newsletter/existing.html
> [bug 1483611] Revert removal of interest section from newsletter preferences

- bedrock/firefox/templates/firefox/features/adblocker.html
Updating the title and description for the adblocker page 
https://github.com/mozilla/bedrock/issues/6116
> Change title and description for adblock page

- media/caldata/SlovakHolidays.ics
Add new one-time public holiday
Add new one-time state holiday into Slovak holiday calendar
https://bugzilla.mozilla.org/show_bug.cgi?id=1499831
The ICS file is directly used as a Lightning calendar, so it is a valid ICS calendar file.
> [Bug 1499831] - Add new one-time state holiday into Slovak holiday calendar

- bedrock/mozorg/templates/mozorg/contribute/tasks/joy-of-coding.html
There is a broken link on the Joy of Coding Page. I have replaced it with the official Youtube Playlist.
> Updated broken link on Joy of Coding Page

- root_files/yandex_7bdb48599fe21f87.html
> Add Yandex verification HTML file

- bedrock/firefox/templates/firefox/election/index.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-election.html
Update instances of "Election Bundle" to "U.S. Election Bundle" for clarification.
#6317
> Update copy to "U.S. Election Bundle" (Fixes #6317)

- bedrock/base/templates/macros.html
- this will enable us to track it in GA
bedrock/mozilla#5974
- no copy-pasta errors 🍝
> Add data-button-name to submit button on FxA form

- bedrock/firefox/urls.py
Fixes https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1292/pipeline/
> Fix /firefox/ URL pattern (#5944)

- bedrock/mozorg/templates/mozorg/internet-health/index.html
- bedrock/mozorg/templates/mozorg/internet-health/web-literacy.html
Update to new global protocol nav.
> Update nav on /internet-health and internet-health/web-literacy

- tests/pages/internet_health.py
Fixes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1301/pipeline/
> Fix failing integration test on /internet-health/

- tests/functional/test_internet_health.py
> Remove /internet-health/ from smoke tests

- bedrock/firefox/templates/firefox/features/private-browsing.html
Move instructions up the page based on stakeholder feedback.
https://github.com/mozilla/bedrock/issues/6361#issuecomment-433492808
> Move instructions up

- bin/slack-notify.sh
> Ignore errors with slack notifications during deployment

- bedrock/firefox/templates/firefox/election/index.html
- bedrock/firefox/templates/firefox/pocket.html
- bedrock/firefox/templates/firefox/recommended.html
- bedrock/mozorg/templates/mozorg/about-en.html
- bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
- bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
- bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
- bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
- bedrock/mozorg/templates/mozorg/locales.html
- tests/functional/firefox/features/test_adblocker.py
- tests/functional/firefox/test_election.py
- tests/functional/firefox/test_pocket.py
- tests/functional/firefox/test_recommended.py
- tests/functional/newsletter/test_newsletter_embed.py
- tests/functional/test_about.py
- tests/functional/test_browser.py
- tests/functional/test_lean_data.py
- tests/functional/test_locales.py
- tests/pages/base.py
- tests/pages/browser.py
- tests/pages/firefox/election.py
- tests/pages/firefox/features/adblocker.py
- tests/pages/firefox/pocket.py
- tests/pages/firefox/recommended.py
- tests/pages/lean_data.py
- tests/pages/locales.py
- tests/pages/regions/newsletter.py
- Adds new functional tests for recently created Protcol pages.
#5995
Successful test run in Sauce Labs: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/213/pipeline/
> Update functional tests for Protocol pages (Fixes #5995)

- bedrock/firefox/templates/firefox/fights-for-you.de.html
- bedrock/firefox/templates/firefox/fights-for-you.html
Add adjust links so mobile users are directed to their app stores.
https://github.com/mozilla/bedrock/issues/6387
Test the links?
> Add direct links to Focus product

- media/css/firefox/fights-for-you.scss
- media/css/protocol/base/fonts/sharpsans.scss
Add sharp sans to fffy page
https://github.com/mozilla/bedrock/issues/6387
Do you see the font?
> Add sharp sans to fffy page

- media/css/mozorg/home/fundraiser2018.scss
A few small tweaks requested in https://github.com/MozillaFoundation/Design/issues/301#issuecomment-441793545 that I failed to notice earlier. Not urgent and needn't block the banner going live.
#6465 
https://github.com/MozillaFoundation/Design/issues/301#issuecomment-441793545
Check that things line up nicely on small viewports and that I didn't make anything worse.
> [#6465] Mobile CSS fixes for fundraising banner

- bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
I neglected to update this URL in #6528. Oops.
#6500 
Just verify the link.
> [bug 1506402] Update employee anti-harrassment policy link

- bedrock/foundation/templates/foundation/annualreport/2017/index.html
- Two minor text amends to SOM.
#6478
> Minor text updates to SOM 2017 page (#6478)

- bedrock/pocketfeed/models.py
- bedrock/pocketfeed/tests/test_data/articles.json
- bedrock/pocketfeed/tests/test_models.py
> Fix issues caused by duplicate articles in Pocket feed

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64-base.html
Bug [#1508494](https://bugzilla.mozilla.org/show_bug.cgi?id=)
> Update image paths

- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
These need to be added manually since the translations are in the templates themselves.
Re bug 1508494
> Add locales to Fx 64 WNP

- media/js/base/search-params.js
Remove jQuery dependency from search-params.js
#6504
File has very good unit tests associated with it.
> Remove jQuery dependency from search-params.js

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64-base.html
- media/css/firefox/whatsnew/whatsnew-64.scss
- media/css/protocol/components/_state-fxa.scss
- media/static-bundles.json
Conditional messaging based on if the user is signed in or not.
I assumed only users in FF64 will see this page so it's not very robust from that perspective.
Also, not sure if fxa-state was moved to Protocol as part of #6503. I might have to re-base on that once it's merged.
> WPN 64 Conditional formatting

- jenkins/branches/master.yml
- jenkins/branches/prod.yml
This reverts commit 6e558016e64cb109547f7c86dbc9ce8467762335.
> Revert "Skip integration tests because of bug 1513622"

- bin/upload-staticfiles.sh
This adds pushing media to a dev bucket where we were only uploading to a stage and prod bucket during prod pushes.
> Upload static media to s3 for www-dev

- bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.fr.html
Small text change
- Close mozilla/bedrock#6636
- Fix bug 1514398
> Text change to French WN64

- bedrock/base/templates/includes/protocol/navigation/menu/about.html
> Fix missing image reference in nav card (#6471)

- bedrock/mozorg/templates/mozorg/home/includes/fundraiser-eoy2018.html
- media/css/mozorg/home/fundraiser2018.scss
Another copy change, now with added doom and gloom for the new year! English only, other locales still get the old strings.
#6580
> [fix #6580] Home fundraising banner copy update

- bedrock/firefox/templates/firefox/home.html
- media/css/firefox/home.scss
Updates copy and adds cta link to /firefox sync section.
#6335 
https://bedrock-demo-firefox-sync.oregon-b.moz.works/en-US/firefox/
> (Fixes #6335) Update /firefox sync section.

- bin/upload-staticfiles.sh
upload staticfiles to stage bucket on push to stage branch
#6730
Push this to the stage branch on origin and verify that staticfiles are uploaded to the correct bucket.
> Fix #6730: upload staticfiles to stage bucket on stage branch

- bedrock/mozorg/templates/mozorg/about/leadership.html
- Updates cbeard's bio on `/about/leadership/`.
- Needs to be live before the 24th (hence the p1)
#6727
> Update CBeard bio on the leadership page (Fixes #6727)

- bedrock/settings/base.py
- bin/run-sync-all.sh
- docker/envfiles/stage.env
Also pull proper database during build for staging.
> Pull proper content cards during docker build
