- bedrock/mozorg/templates/mozorg/about/leadership.html
Fix the title of Angela Plohman. EVP ➡️ Executive Vice President. That's it!
[Bug 1405834](https://bugzilla.mozilla.org/show_bug.cgi?id=1405834)
Visit `/about/leadership/` and make sure her title is correct.
> Fix Bug 1405834 - Update copy in https://www.mozilla.org/en-US/about/leadership/

- bedrock/mozorg/templates/mozorg/home/includes/fx-quantum-promo.html
- Uses URL helper instead of hard coded relative path.
https://bugzilla.mozilla.org/show_bug.cgi?id=1409993
> [fix bug 1409993] 'Learn more' link on Quantum home page promo does a 301 redirect

- bedrock/base/templates/macros.html
- bedrock/base/templatetags/helpers.py
- bedrock/base/tests/test_helpers.py
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- bedrock/settings/base.py
- docs/send-to-device.rst
Not all messages will be available in the same list of countries.  This ensures we're able to provide the best experience by showing the SMS version only to people in the countries for which we have an SMS message that works for them.
> Bug 1395342: Configure send-to-device SMS countries per message-set

- bedrock/firefox/templates/firefox/australis/base.html
- bedrock/firefox/templates/firefox/firstrun/base.html
- bedrock/firefox/templates/firefox/whatsnew/base-pebbles.html
- bedrock/firefox/templates/firefox/whatsnew/base.html
- bedrock/settings/static_media.py
- media/js/base/mozilla-client.js
- media/js/base/mozilla-notification-banner-firstrun-whatsnew-init.js
- tests/unit/spec/base/mozilla-client.js
Adds a check to make sure a ` /firstrun` or `/whatsnew` page is at least 2 major releases out of date before trying to show a notification.
https://bugzilla.mozilla.org/show_bug.cgi?id=1406299
Out of date notification should only be shown if using an old firefox AND the /firstrun or /whatsnew page is also old (2 major versions out of date).
> [fix bug 1406299] Only show notification if /whatsnew page URL is out of date

- media/css/firefox/new/quantum/_other-platforms.scss
- media/css/firefox/new/quantum/common.scss
- Fixes a link alignment issue on /de/firefox/new/
https://bugzilla.mozilla.org/show_bug.cgi?id=1409094
- Load /de/firefox/new/ (make sure to pull latest .lang files)
- Resize the browser to around 790px wide and make sure link is aligned correctly.
> [fix bug 1409094] Link alignment issue on /de/firefox/new/

- bedrock/base/templates/includes/site-footer.html
- bedrock/settings/base.py
- lib/l10n_utils/__init__.py
It will be a link to the current template source on github.
Original inspiration for this commit from:
https://github.com/l-hedgehog/bedrock/commit/36f011c0
> Fix bug 836587: Add "Source code for this page" link to footer

- bedrock/firefox/templates/firefox/features/send-tabs-a.html
- bedrock/firefox/templates/firefox/features/send-tabs-b.html
- bedrock/firefox/templates/firefox/features/send-tabs.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/css/firefox/features/experiment-send-tabs.scss
- media/js/firefox/features/experiment-send-tabs-video.js
- media/js/firefox/features/experiment-send-tabs.js
Adds an A/B test to `/firefox/features/send-tabs/`. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1401245
https://bedrock-demo-jpetto-sendtabs.us-west.moz.works/en-US/firefox/features/send-tabs/?v=a (control)
https://bedrock-demo-jpetto-sendtabs.us-west.moz.works/en-US/firefox/features/send-tabs/?v=b (video variation)
> Bug 1401245 send tabs video experiment

- bedrock/newsletter/tests/test_views.py
- bedrock/newsletter/views.py
Using the update_user like it was doing was clearing out newsletter subscriptions.
> Fix bug 1405042: Newsletter country update page use user-meta basket API

- media/css/firefox/channel.less
Fixes text alignment on desktop (/en-US/firefox/channel/desktop/)
https://bugzilla.mozilla.org/show_bug.cgi?id=1405533
> fix bug 1405533: Misaligned text on Channel Desktop Landing

- bedrock/firefox/templates/firefox/new/quantum/scene1.html
- Updates the headline on `/firefox/new/` to match the headline on `/firefox/`.
- Uses l10n tag `firefox_quantum_new_headline`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1397381#c51
Check for copy pasta?
> [bug 1397381] Update /firefox/new/ headline

- media/js/firefox/quantum/features-scroller.js
- Removes auto play from videos on /firefox because it's wasteful of users bandwidth.
- Note: I've left the auto-pause functionality, as I think leaving video playing that is no longer in the viewport is still a useful feature.
https://bugzilla.mozilla.org/show_bug.cgi?id=1416499
Make sure no regressions from code removal?
> [fix bug 1416499] Remove autoplay from videos on /firefox

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- tests/functional/firefox/test_android.py
- tests/functional/firefox/test_focus.py
- tests/functional/firefox/test_ios.py
Redirects `/firefox/android/`, `/firefox/focus/`, and `/firefox/ios/` to `/firefox/mobile/` for 57 launch.
https://bugzilla.mozilla.org/show_bug.cgi?id=1416496
Ensure correct pages load with switch on and off.
> [fix bug 1416496] Redirect mobile product pages to new mobile page.

- bin/cron.py
We want it to be faster on release-day, and slower on others.
> Make release-notes update timing configurable

- bedrock/firefox/templates/firefox/firstrun/firstrun_quantum.html
- media/css/firefox/firstrun/firstrun_quantum.less
- media/js/base/mozilla-fxa-iframe.js
- media/js/firefox/firstrun/firstrun.js
- media/js/firefox/firstrun/firstrun_quantum.js
- tests/unit/spec/base/mozilla-fxa-iframe.js
@craigcook 
Small visual tweaks for the firstrun page. 
Wave 7 stays to the left for rtl and ltr locales.
Add white background to show through for mix-blend-mode. so we never see colour off of the waves.
connect messaging for fxa-iframe hiding and showing the skip button when appropriate
shrink iframe to tested size to enable multi-column layout
> bug 1397532 change rtl treatment of wave and add white background

- bedrock/firefox/templates/firefox/base-resp.html
- bedrock/firefox/templates/firefox/base.html
Updates Firefox wordmark in base templates (e.g. header on `/firefox/all/`)
https://bugzilla.mozilla.org/show_bug.cgi?id=1413353
Check I didn't miss any other occurences?
> [bug 1413353] Update Firefox wordmark in base templates

- bedrock/firefox/templates/firefox/hub/home-quantum.html
- Sets `preload="none"` on all videos except the top Firefox vs Chrome video.
- This gets the page down to around 2.7MB on a hard refresh. not as small as I'd like but it's a quick win for a small tweak.
https://bugzilla.mozilla.org/show_bug.cgi?id=1417112
https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/
> [fix bug 1417112] Only preload metadata for first video on /firefox

- bedrock/firefox/templates/firefox/releases/release-notes.html
- bedrock/releasenotes/models.py
This was removed in 900fc99d24044e66b82d9c85717c665dea2e39f6. We can now add it back since iOS release notes are now being maintained.
> Fix bug 1416825: Add iOS link to release notes

- bedrock/teach/templates/teach/smarton/tracking.html
After some changes on AMO, the link to the privacy add-ons on `/smarton/tracking/` is now a 404. This PR just updates the URL as requested by the AMO team.
mozilla/addons-frontend#3920
Make sure new link works?
> [fix AMO issue #3920] Fix broken link to AMO privacy add-ons.

- bedrock/firefox/templates/firefox/firstrun/firstrun_quantum.html
- media/css/firefox/firstrun/firstrun_quantum.less
- media/js/firefox/firstrun/firstrun_quantum.js
This disables the background wave animation in Linux and older Windowses (less than Win8), as well as a simplified end transition. Macs and newer Windowses (Win8 and up) should appear the same as before.
This is hopefully a temporary patch to address the most pressing concerns reported on Linux and older Windows machines that lack GPU acceleration until we can regroup and look into revising the page for better performance across all platforms and devices.
The diff looks a bit bigger than it really is because a lot of lines just changed indentation.
https://bugzilla.mozilla.org/show_bug.cgi?id=1417888
https://www-demo4.allizom.org/firefox/57.0/firstrun/
This uses UITour so you'll need to whitelist test domains in `browser.uitour.testingOrigins`
Test the page in Firefox 57+ on Windows 7 and …
> [bug 1417888] Disable firstrun animation for some platforms

- media/css/firefox/new/quantum/common.scss
- media/css/firefox/new/quantum/scene1.scss
Fixes a minor issue where the tracking pixel added to scene2 was causing a small bar of white space below the footer 🙄.
https://bugzilla.mozilla.org/show_bug.cgi?id=1417105
Make sure no other visual regressions in the page?
> [fix bug 1417105] Extra white space at the bottom of the /firefox/new/?scene=2

- bedrock/base/templates/includes/site-footer.html
- Updates site footer links to reflect Quantum page changes.
- All strings are already in [main.lang](https://raw.githubusercontent.com/mozilla-l10n/www.mozilla.org/master/en-US/main.lang), so l10n should not be required?
https://bugzilla.mozilla.org/show_bug.cgi?id=1416725
Make sure translated strings show up as expected?
> [fix bug 1416725] Update Firefox site footer links

- bedrock/firefox/templates/firefox/channel/base.html
- bedrock/firefox/templates/firefox/quantum.html
Fixes 500 on the /channel pages after removal/rename of social sharing images. Test failure: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/703/pipeline/
(appologies I missed these in the PR)
N/A
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/117/pipeline/
> Remove outdated meta page images from /channel pages

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- tests/functional/firefox/test_mobile.py
- tests/pages/firefox/mobile.py
- Adds functional tests for the main CTA states on `/firefox/mobile/`
- Removes switch/condtional view.
Note: 
- We're missing tests for android / ios platforms directly showing the mobile badges, because we don't currently have those platforms set up in our automation (future project?).
- I also started down the path of trying to test the features scroller link clicks, but this turned into a Selenium can o' worms from hell (because some browsers support `position: sticky;` and others don't). I gave in and decded just to concentrate on the main page CTA's.
https://bugzilla.mozilla.org/show_bug.cgi?id=1416710
> [bug 1416710] Add functional tests for /firefox/mobile/ page

- bedrock/base/templates/includes/site-footer.html
Adds a link to the main blog in the global footer. 
@peiying2 The string "Blog" already seems to be in main.lang, I suspect because it appears in the global nav so I'm not sure how many locales have translated it so far. But if it's an older string we might already be really well covered and could merge this right away. If not, we can wrap it in a conditional.
https://bugzilla.mozilla.org/show_bug.cgi?id=1419110
> [fix bug 1419110] Add blog link to global footer

- media/js/base/search-params.js
- tests/unit/spec/base/search-params.js
Forces all values in the object returned by `utmParamsFxA` to be strings, as `UITour.showFirefoxAccounts` fails if any values are numeric.
https://bugzilla.mozilla.org/show_bug.cgi?id=1419125
Ensure no regressions?
> [fix bug 1419125] Ensure string values in utmParamsFxA.

- bedrock/mozorg/templates/mozorg/about/governance/roles.html
Remove Brendan since he is no longer an owner of the Governance module. Also add ID attributes to the headings so that the old anchors work.
> Fix bug 1417972: Update ultimate authority governance role

- bedrock/firefox/templates/firefox/developer-quantum-firstrun.html
- bedrock/firefox/templates/firefox/developer-quantum-whatsnew.html
- media/css/firefox/developer-quantum.scss
Adds Dev Edition playground links to `/firefox/58.0a2/firstrun/` and `/firefox/58.0a2/whatsnew/`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1416068
Check for copy/pasta errors?
> [fix bug 1416068] Add Dev Playground Links to DevEdition Onboarding Pages

- bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54.html
- media/js/firefox/whatsnew/whatsnew-54.js
- This fixes an issue on `/whatsnew` when updating from 56.0 -> 56.0.1 -> 57.0, where the page for 56.0.1 says Firefox is up-to-date (which isn't technically true).
URL: `/firefox/56.0.1/whatsnew/?oldversion=56.0`
https://bugzilla.mozilla.org/show_bug.cgi?id=1419573
- Make sure the message does not display using on outdated version of Firefox.
> [fix bug 1419573] Only show 'Your Firefox is up to date' on /whatsnew if it's the latest version

- bedrock/base/templates/includes/global-nav.html
- bedrock/mozorg/templates/mozorg/developer/includes/sub-nav.html
- bedrock/mozorg/templates/mozorg/technology.html
- media/css/mozorg/technology.scss
Adds new sub navigation items that are consistent between the /developer and /technology pages
https://bugzilla.mozilla.org/show_bug.cgi?id=1391847
/technology and /developer should have the same sub navigation but:
1) when on /technology, the first item in the subnav will be Developer Hub and link to /developer
2) when on /developer, the first item in the subnav will be Technology Hub and link to /technology
> Fix Bug 1391847, changes to secondary nav for /developer and /technology

- bedrock/firefox/templates/firefox/whatsnew/fx54/whatsnew-54.html
- media/js/firefox/whatsnew/whatsnew-54.js
Fixes 2 errors I made in #5312 :/
- Removes stray closing `</div>`
- Ensure the JS is included for all locales (it was previously only included in the template if send-to-device was supported).
https://bugzilla.mozilla.org/show_bug.cgi?id=1419573
- Make sure conditional messaging works for locales such as `it`.
- Make sure no other regressions?
> [bug 1419573] Fix up to date message for non send-to-device /whatsnew locales

- bedrock/firefox/templates/firefox/mobile.html
- media/css/firefox/mobile.scss
- Adds disclaimer & link to Disconnect on the privacy sections of `/firefox/mobile/`
https://bugzilla.mozilla.org/show_bug.cgi?id=1414326
- Check for copy/pasta errors?
> [fix bug 1414326] Add Disconnect link to /firefox/mobile/ page

- bedrock/wordpress/api.py
- bedrock/wordpress/management/commands/update_wordpress.py
- bedrock/wordpress/models.py
- bedrock/wordpress/tests/test_models.py
Used to delete all entries before adding again from the server.  Now uses the server post ID and modified time to only update those that need updating and removing older posts.
> Make update_wordpress command efficient with DB writes

- bedrock/firefox/templates/firefox/hub/home-quantum.html
Adds the Optimizely block to the new Firefox home page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1422042
Make sure no copy pasta?
> [fix bug 1422042] Add Optimizely block to new Firefox home page.

- .gitignore
- bedrock/externalfiles/__init__.py
- bedrock/externalfiles/management/commands/update_externalfiles.py
- bedrock/settings/base.py
Converts community data (external files) updates to use git just like we do for release notes and security advisories. These files are already in a git repo together.
The way it's currently done is inefficient and tends to change the database more often than is necessary.
> Update community data via git

- bedrock/firefox/templates/firefox/firstrun/email-first-experiment/index-a.html
- bedrock/firefox/templates/firefox/firstrun/email-first-experiment/index-b.html
- bedrock/firefox/templates/firefox/firstrun/firstrun_quantum.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/css/firefox/firstrun/firstrun_quantum.less
- media/js/firefox/firstrun/experiment-firstrun-email-first.js
- media/js/firefox/firstrun/firstrun_quantum.js
@alexgibson - here's the WIP I mentioned in bugzilla.
Add the FxA email-first experiment to the quantum firstrun page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1405822
https://docs.google.com/document/d/1seUQEXOR-JGD6ff77iAP8lzDjW-BPengXugUzo-p2UQ
I have yet to add tests, and have lots of questions.
* Are `a` and `b` typical names for a variation? I see a combination of `a`, `b`, and `1`, `2`, `3`, etc.
* When an A/B test changes copy, do you use a single template for both variants or create separate templates? I went with a single template and if statements to control which copy is displayed.
* The [way I set the template context](https://github.com/mozilla/bedrock/compare/master...shane-tomlinson:fxa-email-first-experiment?expand=1#diff-784e0d4de42af29595e70315a6be5337R422) seems …
> feat(fxa): Add the email-first experiment to the firstrun page

- bedrock/firefox/templates/firefox/hub/home-quantum.html
Updates copy in the "Faster" section on `/firefox/`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1423026
Check for typos?
> [fix bug 1423026] Update faster copy in /firefox

- bedrock/mozorg/templates/mozorg/home/includes/netneutrality-12-2017.html
- media/css/mozorg/home/netneutrality-12-2017.scss
Got a directive from Jascha to go all in on this banner and make it a full-page takeover (it just pushes everything down, doesn't cover it up).
https://bugzilla.mozilla.org/show_bug.cgi?id=1423237
https://bedrock-demo-craigcook.us-west.moz.works/en-US/
Verify expected behavior and no breakage. Especially verify nothing in the new CSS is impacting the slender version on /firefox/new/
> [bug 1423237] Embiggen the NN protest banner

- bedrock/firefox/redirects.py
- bedrock/privacy/redirects.py
- tests/redirects/map_globalconf.py
Adds a 301 permanent redirect for `/privacy/firefox-fire-tv/` and 302 temporary redirect for `/firefox/fire-tv/` (actual product page forthcoming).
We need to get these redirects live by EOD Dec 18 (today).
https://bugzilla.mozilla.org/show_bug.cgi?id=1425865
> [fix bug 1425865] Add redirects for Fire TV

- bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
- bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
- Update the list of web bug bounty sites to add pto.mozilla.org
- Update the hall of fame for Q3 2017, update some URLs for previous hall-of-famers
None, small HTML update.
> Web bug bounty related updates

- bedrock/firefox/templates/firefox/new/quantum/scene2.html
Add optimizely block to quantum scene2 page so we can track downloads in Optimizely experiments.
https://bugzilla.mozilla.org/show_bug.cgi?id=1422042
```
(venv) bedrock$ py.test lib bedrock/firefox
<snip>
================================================ 278 passed, 1 skipped in 12.17 seconds ===============================================
```
> [bug 1422042] Add optimizely block to quantum scene2

- docker/bin/run_integration_tests.sh
- jenkins/branches/master.yml
- jenkins/branches/prod.yml
- jenkins/branches/run-integration-tests.yml
- jenkins/utils.groovy
- tests/functional/test_download.py
- tests/functional/test_download_l10n.py
I'm not sure if this will help with our deployment woes or not, but it does seem inefficient at best to test every download URL on the site 6* per deployment. I'll explain:
The download tests find all download links on the various `*/all/` pages. That comes out to around 3,000 unique URLs, almost all of which point to bouncer (download.mozilla.org). That means that we're sending 3,000 requests to bouncer for each deployment, per app, per region. Since we deploy stage and prod to 3 regions during a prod deployment that comes out to 6 deployments and 18,000 requests. These are just `HEAD` requests, so the CDN isn't sending the download bytes, but it does seem wasteful to check those for every app in every region, especially since the checks are all coming from the Jenkins box.
> Avoid testing all download URLs more than once per deployment

- docker/bin/run_integration_tests.sh
- tests/functional/test_download.py
- tests/functional/test_download_l10n.py
This may mean slower tests for download links, but shouldn't be much slower. Advantages are that it's much more simple, it has no chance of collecting a different number of tests at different times, and does not call out to the site for these pages even when those tests aren't going to run.
> Move link gathering out of test discovery for download tests

- media/js/plugincheck/plugincheck.js
- Fixes plugincheck to treat pre-release versions of Firefox as up-to-date.
- Also adjusts the logic to only check against the major version number.
https://bugzilla.mozilla.org/show_bug.cgi?id=1393035#c4
- Test pre-release versions of Firefox are considered as up-to-date.
- Test old versions are considered out of date.
- Test latest ESR is considered as up-to-date.
> [fix bug 1393035] Plugin check doesn't recognize nightly as FF

- docs/coding.rst
Fix a typo "tempalte" by replacing it with "template".
None
None
> Typo fix: replace "tempalte" with "template"

- bedrock/firefox/templates/firefox/all.html
Revise the page description of the [Firefox ESR download page](https://www.mozilla.org/en-US/firefox/organizations/all/) which I forgot to update as part of my previous PR #5330. The new description excludes the "Learn more" link for easier l10n.
[Bug 1421584 - Change ESR page content to make it clear that ESR is for sysadmins and mailing list subscription is optional](https://bugzilla.mozilla.org/show_bug.cgi?id=1421584)
Just visit the page and make sure it has the new copy.
> Follow up Bug 1421584 - Update ESR download page description

- bedrock/base/templates/product-all-macros.html
Stops locale search boxes from autocompleting terms from other sites/searches.
https://bugzilla.mozilla.org/show_bug.cgi?id=1426735
Make sure no regressions?
> [fix bug 1426735] Disable native autocomplete on locale searches.

- bedrock/firefox/templates/firefox/new/scene2.html
- Updates link to `/firefox/all` on `/firefox/new/?scene=2` to mention platforms as well as languages. For context, see https://github.com/mozilla/bedrock/issues/5300.
https://bugzilla.mozilla.org/show_bug.cgi?id=1427724
- Page should display the new copy as expected when l10n tag is active.
> [fix bug 1427724] Link to /firefox/all/ on scene2 of /firefox/new/ should mention other platforms

- bedrock/utils/git.py
- bedrock/utils/tests/test_git.py
Strange state when initial setup of git repos happened under a different config than the running container. This should fix this by using repo URLs directly.
> Git repos avoid using remotes

- bedrock/mozorg/templates/mozorg/technology.html
- Updated Quantum CTA link on `/technology` to "Learn more", since the link goes to a product page and is not an actual download button.
- Also removes a bunch of l10n tags since [coverage on this page](https://l10n.mozilla-community.org/langchecker/?website=www.mozilla.org&file=mozorg/technology.lang&action=translate) seems complete.
https://bugzilla.mozilla.org/show_bug.cgi?id=1402967
- Check I didn't miss any other occurences of obsolete l10n tags?
> [bug 1402967] Update Quantum link text on /technology

- bedrock/firefox/templates/firefox/includes/hub/sub-nav.html
- Links to https://blog.mozilla.org/firefox-de/ in the Firefox sub nav for the `de` locale.
- Removes hard-coded `en` conditional for `Extensions` as we now have the string in in [main.lang](https://l10n.mozilla-community.org/langchecker/?website=www.mozilla.org&file=main.lang&action=translate).
- Removes some old strings that are no longer used e.g. `Desktop Browser` etc.
https://bugzilla.mozilla.org/show_bug.cgi?id=1429255
- Sub nav "Blog" link should go to https://blog.mozilla.org/firefox-de/ for `/de/firefox/` only.
> [fix bug 1429255] Link to German Firefox blog from subnav on 'de' locale

- jenkins/branches/frankfurt-prod.yml
- jenkins/branches/frankfurt.yml
- jenkins/branches/master.yml
- jenkins/branches/prod.yml
- jenkins/branches/tokyo-prod.yml
- jenkins/branches/tokyo.yml
The selenium tests seem to be more stable than headless.
> Run only firefox tests in k8s clusters

- docker/bin/cleanup_after_functional_tests.sh
- docker/bin/run_integration_tests.sh
- docker/bin/set_git_env_vars.sh
If you try a deployment of two branches with the same commit (e.g. master and prod) it will often fail due to conflicting container names when they were just using commit hash. Adding the branch name should eliminate these failures.
> Use branch name in test container names; avoid conflicts

- bedrock/firefox/templates/firefox/home.html
- Adds shared Schema.org microdata include to `/firefox/`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1405409
- Microdata should be present when inspecting the markup for `/firefox/` (but nothing visually noticable to the page).
> [fix bug 1405409] Add microdata to /firefox/ page

- media/img/firefox/template/page-image-quantum.png
Add a symlink to page-image.png, and since it's the same file as page-image-quantum.png, the hashed name will be the same as it was originally, thus continuing to serve the image at the old URL.
> Bug 1430147: Restore page-image-quantum.png

- bedrock/settings/base.py
- Removes `yahoo_purple` and `yahoo_green` tracking pixels from the download page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1343033
- Ensure DoubleClick pixel still loads as expected.
> [fix bug 1343033] Remove Yahoo! tracking pixels from download page

- bedrock/mozorg/credits.py
- bedrock/mozorg/tests/test_credits.py
The Credits file parser was not expecting non-ascii characters in the 2nd column (the sort key). This patch will convert those accented characters to their ascii equalivents for sorting purposes.
> Fix bug 1430641: Fix credits file unicode errors

- bedrock/mozorg/templates/mozorg/technology.html
- Updates main CTA and small link on IoT section of `/technology`.
- New string is behind the l10n tag `1429633_iot_update`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1429633
- Check for copy/pasta?
> [fix bug 1429633] Update IoT CTA's on /technology page

- bedrock/base/templatetags/helpers.py
- bedrock/base/tests/test_helpers.py
Main difference from urlencode is that it converts spaces to "%20" instead of "+".
> Add a mailtoencode template filter

- bedrock/firefox/templates/firefox/switch.html
- media/css/firefox/switch.scss
This makes some layout tweaks to bring the download button higher up the page (let's pretend a fold exists for the moment). Main tweaks are:
* lose the horizontal rule between tagline and steps.
* move the step numbers inline with the steps (in windows wide enough).
* reduce step font-size (since the columns are narrower).
* generally tighten up spacing all around.
The arbitrary target size was 1280x800, anything shorter may still have to scroll but such is the nature of the web.
This also updates the GA tagging on the share links.
https://bugzilla.mozilla.org/show_bug.cgi?id=1429321
https://bedrock-demo-craigcook.us-west.moz.works/en-US/firefox/switch/
> [bug 1429321] Switch page, reduce vertical space

- docs/l10n.rst
- media/css/etc/firefox/retention/thank-you.scss
- media/css/firefox/firstrun/firstrun.less
- media/css/firefox/firstrun/firstrun_quantum.less
- media/css/firefox/new/batm.scss
- media/css/firefox/new/fx-lifestyle/its-your-web.less
- media/css/firefox/whatsnew/send-to-device.scss
- media/css/l10n/ar/intl.css
- media/css/l10n/az/intl.css
- media/css/l10n/fa/intl.css
- media/css/l10n/ff/intl.css
- media/css/l10n/ja/intl.css
- media/css/l10n/ko/intl.css
- media/css/l10n/ro/intl.css
- media/css/l10n/zh-CN/intl.css
- media/css/l10n/zh-TW/intl.css
- media/css/mozorg/developer/css-grid-demo.scss
- media/css/mozorg/manifesto.less
- media/css/pebbles/includes/fonts/_open-sans.scss
- media/css/pebbles/includes/fonts/_zilla-slab-highlight.scss
- media/css/pebbles/includes/fonts/_zilla-slab.scss
- media/css/sandstone/fira-fonts.less
- media/css/sandstone/fonts.less
- media/css/styleguide/styleguide.less
- Adds `font-display: swap;` descriptor to our generic `@font-face` stack, eliminating FOIT in browsers that support it (Currently in Chrome & FF 58+. It's also in Safari Tech Preview). This makes text content readable much earlier in the page loading process, especially for those on slower connections.
https://bugzilla.mozilla.org/show_bug.cgi?id=1427719
- Demo: https://www-demo1.allizom.org/en-US/
- Hard-refreshing pages in both Chrome and Firefox (58+) is the easiest way to view the change in behavior on individual pages. I also did some basic tests on mobile using web page test, which you can see in the bug.
- Make sure I didn't miss any `@font-face` rules?
> Implement font-display: swap; to remove FOIT

- tests/functional/firefox/test_switch.py
- tests/functional/firefox/test_whatsnew.py
- tests/pages/firefox/switch.py
- tests/pages/firefox/whatsnew.py
- Adds functional tests for:
- `/firefox/switch/`
- `/id/firefox/whatsnew/`
- `/zh-TW/firefox/whatsnew/`
N/A
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/168/pipeline/
> Add functional tests for /firefox/switch and locale-specific /whatsnew pages

- jenkins/branches/master.yml
- jenkins/branches/prod.yml
- jenkins/global.yml
For now this adds it as the last cluster for dev, stage, and prod deployments. It will be shuffeled to the primary cluster when us-west is decommissioned.
> Add Oregon-B cluster to deployment

- bedrock/settings/base.py
This will allow us to have a single "Bedrock Prod" Sentry Project for example, and to filter based on region.
> Add site to Sentry config

- bedrock/firefox/templates/firefox/home.html
- bedrock/firefox/templates/firefox/includes/hub/sub-nav.html
- bedrock/firefox/templates/firefox/mobile.html
- bedrock/mozorg/templates/mozorg/developer/includes/sub-nav.html
- bedrock/mozorg/templates/mozorg/developer/index.html
- bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
- bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
- bedrock/mozorg/templates/mozorg/internet-health/includes/sub-nav.html
- bedrock/mozorg/templates/mozorg/internet-health/index.html
- bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
- bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
- bedrock/mozorg/templates/mozorg/internet-health/web-literacy.html
- media/css/hubs/_sub-nav.scss
- Highlights the current page/link in the sub nav manus under Firefox, Internet Health, and Technology.
https://bugzilla.mozilla.org/show_bug.cgi?id=1429891
- Make sure all pages show the correct current hightlight color when navigating through the menus.
> [fix bug 1429891] Highlight current link/page in sub navigation menus

- bedrock/firefox/templates/firefox/releases/nightly-notes.html
- bedrock/firefox/templates/firefox/releases/release-notes.html
- bedrock/releasenotes/models.py
- bedrock/releasenotes/tests/releases/firefox-58.0a1-nightly.json
- bedrock/releasenotes/tests/test_base.py
- bedrock/releasenotes/tests/test_models.py
- bedrock/releasenotes/views.py
Show a "coming soon" page for unpublished releases on production, where people get a 404 page at this time. The draft notes can still be previewed on stage.
**Do not merge yet** until the copy gets reviewed by @pascalchevrel.
[Bug 1431348 - Unpublished Release notes should not be 404 but should get a default template with a "coming soon" message instead](https://bugzilla.mozilla.org/show_bug.cgi?id=1431348)
This is actually difficult to test with actual release data depending on the timing. Currently [59.0beta](https://www.mozilla.org/en-US/firefox/59.0beta/releasenotes/) is unpublished so this page will be "coming soon" once this PR is merged, like [this screnshot](https://screenshots.firefox.com/MjqzpkbJdVq3rCpA/127.0.0.1).
> Fix Bug 1431348 - Unpublished Release notes should not be 404 but should get a default template with a "coming soon" message instead

- bedrock/releasenotes/models.py
- bedrock/releasenotes/tests/test_models.py
Drafts were not being deleted on refresh of data when DEV = False (as it is in production. This fixes that.
> Fix multiple objects returned error for release notes

- bedrock/firefox/templates/firefox/new/scene1.html
Windows installer links in the "Advanced install options & other platforms" should point to the full installers. (Currently pointing to stub installer for both 32 and 64-bit links.)
https://bugzilla.mozilla.org/show_bug.cgi?id=1386622#c38
> [fix bug 1386622] force full win installers in modal on /new page.

- bedrock/firefox/templates/firefox/mobile.html
- media/css/firefox/mobile.scss
Add Android APK link to mobile download modal on /firefox/mobile/
[Bug 1434019](https://bugzilla.mozilla.org/show_bug.cgi?id=1434019)
> Add Android APK link to mobile download modal

- bedrock/firefox/views.py
- bedrock/settings/base.py
- requirements/base.txt
Fix the firefox/dnt/ view to provide the `request.DNT` variable.
> Fix #5427: Remove DNT Middleware

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
These were causing exceptions due to encoding errors. The stub attribution service has a whitelist that doesn't include any such domains anyway. We now ignore those.
> Fix attribution_code with non-ascii domain referrers

- media/js/firefox/firstrun/firstrun_quantum.js
Use UITour method to navigate to about:newtab (normally `Error: Access to 'about:newtab' from script denied`) that is also being updated to focus the address bar.
https://bugzilla.mozilla.org/show_bug.cgi?id=1425454
https://bug1425454.bmoattachments.org/attachment.cgi?id=8946540
> Fix Bug 1425454 - The onboarding flow should end up focusing the awesomebar instead of the search box in the page

- bedrock/firefox/templates/firefox/releases/release-notes.html
Wording change
Bug 1436686 Update wording on 'Coming soon' release notes page
Local testing
> Bug 1436686 Update wording on 'Coming soon' release notes page

- bedrock/firefox/templates/firefox/nightly_whatsnew.html
* Change Firefox Nightly to Nightly on the [whatsnew page](https://www.mozilla.org/en-US/firefox/59.0a1/whatsnew/) for copy consistency.
* The localized strings will be updated by @peiying2 or @flodolo so no l10n tag is added here.
[Bug 1436437 - Change one instance of LongBrandName to ShortBrandName on Nightly You've been upgraded page](https://bugzilla.mozilla.org/show_bug.cgi?id=1436437)
Just open the page to see the new copy.
> Fix Bug 1436437 - Change one instance of LongBrandName to ShortBrandName on Nightly You've been upgraded page

- bedrock/firefox/templates/firefox/new/wait-face/base.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/js/firefox/new/experiment-firefox-new-waitface.js
- media/js/firefox/new/wait-face-scene1.js
Add a trafficcop experiment to send half of visitors to an xv template to a different xv template, if they are non-Firefox desktop users in en-US with specific parameters.
https://bugzilla.mozilla.org/show_bug.cgi?id=1434764
Unit testing of templates passes after adjusting tests.
Sparse functional testing works as expected -- 50% of chrome visits end at the 2nd template.
Please consider the way this PR works with params. I believe analytics will work as we want it to work with this setup, and user flow works as expected, but would appreciate scrutiny of this approach.
> [bug 1434764] Add TrafficCop experiment for waitface video

- bedrock/firefox/templates/firefox/new/scene2.html
- Updates the "click here" link copy on `/firefox/new/?scene=2` to be less mouse-pointer centric (also a bit more descriptive for screen readers).
https://bugzilla.mozilla.org/show_bug.cgi?id=1407278
- Ensure no regressions in new & fallback copy.
> [fix bug 1407278] Update 'click here' link text on /firefox/new/?scene=2

- media/css/firefox/mobile.scss
- media/css/hubs/_nav-download-button-remove.scss
- Hides button in the top nav (& sticky sub nav) on `/firefox/mobile/` which both download the desktop product.
https://bugzilla.mozilla.org/show_bug.cgi?id=1429849
- Both global nav and sub nav buttons should be hidden.
> [fix bug 1429849] Hide button in top nav on /firefox/mobile/

- bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
Through some sloppy duplication on my part the wrong quote has been on this page for months. 😳 This corrects that error.
I've wrapped the entire block in the l10n tag `iot_interoperable_quote` and removed the old quote as I think it's probably better to show nothing at all than to show the wrong content.
https://bugzilla.mozilla.org/show_bug.cgi?id=1438373
> [fix bug 1438373] Correct pullquote on Decentralization page

- bedrock/firefox/templates/firefox/organizations/organizations.html
* Replace an outdated wiki link on the [ESR page](https://www.mozilla.org/en-US/firefox/organizations/) with the MDN article.
* Remove another link plus a mention of Thunderbird.
[Bug 1427250 - Out of date link in the Firefox ESR page](https://bugzilla.mozilla.org/show_bug.cgi?id=1427250)
Visit the ESR page to found the new copy.
> Fix Bug 1427250 - Out of date link in the Firefox ESR page

- bedrock/mozorg/templates/mozorg/about/leadership.html
Minor corrections via email:
> Internet should be internet in the first paragraph
> 
> and The Web Summit should just be Web Summit in the last.
https://bugzilla.mozilla.org/show_bug.cgi?id=1425359
> [fix bug 1425359] Correct typos in Mitchell’s bio

- bedrock/firefox/templates/firefox/home.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1438895
> [fix bug 1438895] Remove locale_in_transition from dl buttons on /firefox

- bedrock/firefox/templates/firefox/home.html
- bedrock/firefox/templates/firefox/includes/hub/sub-nav.html
- bedrock/firefox/templates/firefox/new/reggie-watts/base.html
- bedrock/firefox/templates/firefox/new/wait-face/base.html
- Updates links for `https://blog.mozilla.org/firefox-de/` to `https://blog.mozilla.org/firefox/de/` now that the German Firefox blog content has been moved.
https://bugzilla.mozilla.org/show_bug.cgi?id=1429255
- Make sure URLs still show the expected content?
> [fix bug 1429255] Update links to /firefox/de/ blog

- bedrock/base/templates/includes/global-nav.html
- bedrock/firefox/templates/firefox/home.html
- bedrock/firefox/templates/firefox/new/base.html
- bedrock/mozorg/templates/mozorg/home/home.html
- Adds `(UK)` to page titles and logo attributes on key `/en-GB/` pages, to try and avoid duplicate content penalties in Google search.
https://bugzilla.mozilla.org/show_bug.cgi?id=1438302
- `/en-GB/`, `/en-GB/firefox/` and `/en-GB/firefox/new/` should all display `(UK)` as expected in the respective places. Other locales should show as normal.
> [bug 1438302] Avoid duplicate content on key 'en-GB' pages

- tests/functional/test_link_hreflang_tags.py
Hopefully this will tell us if we're actually seeing any incorrect metadata from these pages.
> Bug 1438302: Add canonical link tag tests to headless integration tests

- tests/functional/test_link_hreflang_tags.py
Smoke tests run against the code image which doesn't have locales.  These tests require the localization files.
> Mark hreflang tests as not smoke

- bedrock/mozorg/templates/mozorg/technology-en.html
Since en-* locales have a separate template it wasn't picking up the list of translations, and so it appeared from the English page that it wasn't translated. This also meant that the en-GB version was redirecting to the en-US since that locale isn't active for the "mozorg/technology-en" langfile.
> Add translations back to english Tecnology page

- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/settings/static_media.py
- media/css/firefox/new/experiment-dev-edition.scss
- media/js/firefox/new/experiment-firefox-new-dev-edition.js
Adds experiment placing a callout for Dev Edition on scenes 1 & 2 of `/firefox/new/` for en-US only.
https://bugzilla.mozilla.org/show_bug.cgi?id=1432236
Make sure you have DNT/tracking protection disabled.
https://bedrock-demo-jpetto.us-west.moz.works/en-US/firefox/new/
> [fix bug 1432236] Add dev edition experiment to /firefox/new/.

- media/js/base/mozilla-utils.js
- tests/unit/spec/base/mozilla-utils.js
- Removes dynamic `itms-apps://` links for Firefox on iOS, as the protocal does not work for some newer webviews by default.
https://bugzilla.mozilla.org/show_bug.cgi?id=1440404
- Visit `/firefox/new/` on an iOS device, and the download button should use `https://` and not `itms-apps://`.
- Clicking the download button should still redirect to the native app store as expected.
> [fix bug 1440404] Remove custom URL scheme for app store links to Firefox on iOS

- bedrock/base/templates/product-all-macros.html
- bedrock/firefox/firefox_details.py
- bedrock/firefox/views.py
- media/css/firefox/all.less
* Highlight recommended builds on the [Firefox download page](https://www.mozilla.org/en-US/firefox/all/)
* l10n: there is 1 new string: _Recommended_
[Bug 1430027 - On the download page, for Linux, highlight the 64-bit version (to limit the number of 32 downloads)](https://bugzilla.mozilla.org/show_bug.cgi?id=1430027)
* [Demo server](https://bedrock-demo-firefox-all.us-west.moz.works/en-US/firefox/all/) is available
* The change should not affect download pages other than Firefox for desktop.
> Fix Bug 1430027 - On the download page, for Linux, highlight the 64-bit version (to limit the number of 32 downloads)

- bedrock/firefox/templates/firefox/tracking-protection-tour.html
- bedrock/settings/base.py
- Removes `/firefox/tracking-protection/start/` from our XML sitemap.
- Also removes canonical/hreflang URLs from template, since this is a noindex page.
https://bugzilla.mozilla.org/show_bug.cgi?id=1442229
- I wasn't sure how to test the generated sitemap locally?
> [fix bug 1442229] Exclude /firefox/tracking-protection/start/ from sitemap.xml

- media/js/firefox/new/experiment-firefox-new-waitface.js
Addresses utm_parameter change requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1434764#c9. See https://github.com/mozilla/bedrock/pull/5443 for history of this code.
> [bug 1434764] utm_source is Facebook

- bedrock/base/templates/includes/canonical-url.html
- Removes `hreflang` attribute from canonical link on all pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1442327
> [fix bug 1442327] Remove hreflang in canonical tag

- bedrock/base/templates/includes/canonical-url.html
- Adds missing languages to `hreflang` for Google-juice.
https://bugzilla.mozilla.org/show_bug.cgi?id=1442565
Demo: https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/
> [fix bug 1442565] Missing languages in hreflang

- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/css/firefox/firstrun/firstrun-quantum.scss
- media/js/firefox/firstrun/experiment-firefox-firstrun-fxa.js
Adds copy experiment for `/firefox/firstrun/`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1441597
Has a 12% chance of being entered into an experiment:
https://www-demo4.allizom.org/en-US/firefox/58.0/firstrun/
Or, hit each variation directly:
- https://www-demo4.allizom.org/en-US/firefox/58.0/firstrun/?v=a (control)
- https://www-demo4.allizom.org/en-US/firefox/58.0/firstrun/?v=b
- https://www-demo4.allizom.org/en-US/firefox/58.0/firstrun/?v=c
- https://www-demo4.allizom.org/en-US/firefox/58.0/firstrun/?v=d
- https://www-demo4.allizom.org/en-US/firefox/58.0/firstrun/?v=e
- https://www-demo4.allizom.org/en-US/firefox/58.0/firstrun/?v=f
> [fix bug 1441597] Add FxA copy experiment to /firstrun.

- bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
- media/css/newsletter/newsletter-opt-out-confirmation.scss
- Fixes subhead font-size being smaller than body copy on small screens.
- Use title case for for button.
- Add placeholder text to email field.
https://bugzilla.mozilla.org/show_bug.cgi?id=1442129
> [fix bug 1442129] Opt-out confirmation page tweaks

- tests/functional/test_download_l10n.py
test_localized_download_links is currently failing due to a legitimate 404 for a localized nightly build
https://bugzilla.mozilla.org/show_bug.cgi?id=1445077
This should mark the failing test as an expected failure.
> Mark test_localized_download_links as xfail due to bug 1445077

- bedrock/firefox/templates/firefox/new/wait-face/base.html
- bedrock/firefox/templates/firefox/new/wait-face/scene1-newcopy.html
- bedrock/firefox/templates/firefox/new/wait-face/scene1-switch.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- bedrock/settings/static_media.py
- media/js/firefox/new/experiment-firefox-new-waitface-switch.js
- media/js/firefox/new/waitface-switch-experiment-datalayer.js
- media/js/hubs/sub-nav.js
- requirements/base.txt
Adds "switch" experiment for `/firefox/new/?xv=waitface`.
Also updates `python-decouple` so values in a local `.env` file do not override `patch`es to `os.environ`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1443921
**Not** using Firefox, on desktop, with DNT disabled, hit:
https://bedrock-demo-jpetto.us-west.moz.works/en-US/firefox/new/?xv=waitface&utm_medium=display&utm_source=facebook&utm_campaign=x&utm_content=switch-lp
Or, hit each variation directly (again, **not** using Firefox):
- https://bedrock-demo-jpetto.us-west.moz.works/en-US/firefox/new/?xv=waitface&utm_medium=display&utm_source=facebook&utm_campaign=x&utm_content=switch-lp&v=1
- https://bedrock-demo-jpetto.us-west.moz.works/en-US/firefox/new/?xv=waitface&utm_medium=display&utm_source=facebook&utm_campaign=x&utm_content=sw …
> [fix bug 1443921] Add /new waitface switch experiment.

- tests/functional/test_download_l10n.py
Remove xfail added in #5504 
https://bugzilla.mozilla.org/show_bug.cgi?id=1445077
Tests are reporting XPASS in latest runs; xfail no longer necessary.
> Remove xfail now that bug 1445077 is resolved

- bedrock/releasenotes/tests/releases/firefox-for-android-58.0a1-nightly.json
- bedrock/releasenotes/tests/test_base.py
- bedrock/releasenotes/views.py
* Show a "coming soon" message for draft/unpublished Firefox for Android notes, just like desktop notes.
* Fix a bug in the test added in #5408: `DEV=False` was missing.
[Bug 1445648 - Unpublished Android release notes get a 404 message on production instead of the coming soon message](https://bugzilla.mozilla.org/show_bug.cgi?id=1445648)
Already tested in #5408, so I think no additional tests are required.
> Fix Bug 1445648 - Unpublished Android release notes get a 404 message on production instead of the coming soon message

- bedrock/security/templates/security/bug-bounty/faq-webapp.html
- bedrock/security/templates/security/web-bug-bounty.html
Moves the "How To Submit Bugs" to the FAQ and then adds a couple links to it in the top level Bug Bounty entry form.
https://github.com/mozilla/bedrock/issues/5502
Ran Bedrock locally, all links seem to work correctly. No display issues or anything.
@claudijd, could I get some quick r? on this? Thanks!
> Move the bug submission process to the FAQ. Fixes #5502.

- media/css/pebbles/includes/mixins/_typography.scss
- Updates our `font-size-level` mixins in Pebbles, so that headings never become smaller than our base font size for body copy (something I have to frequently fight against).
- I decided against sneaking this into the homepage redesign PR, since it touches other pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1447269
- This touches a lot of pages, but it only really makes a couple of pixels difference to certain bits of copy. So should hopefully be a fairly safe change.
> [fix bug 1447269] Headings should not be smaller than base font size on small screens

- media/css/firefox/firstrun/firstrun-quantum.scss
- media/css/firefox/firstrun/firstrun.less
Changes the color of the skip button so it doesn't overshadow or compete with the signup button (which recently changed from gray to blue).
I opted for blue text and border instead of dark gray so it wouldn't look disabled, but it's still secondary to the more prominent signup button. Happy to adjust colors if someone has a better suggestion.
https://bugzilla.mozilla.org/show_bug.cgi?id=1399654
https://bedrock-demo-craigcook.us-west.moz.works/firefox/58.0/firstrun/
Older versions, too: https://bedrock-demo-craigcook.us-west.moz.works/firefox/55.0/firstrun/
> [fix bug 1399654] Firstrun - change skip button to gray

- bedrock/firefox/templates/firefox/includes/download-list.html
- bedrock/firefox/templatetags/helpers.py
- bedrock/firefox/tests/test_helpers.py
- media/css/firefox/new/_other-platforms.scss
Reorganize the recommended and traditional builds on [`firefox/new/`](https://www.mozilla.org/en-US/firefox/new/) like #5432.
[Bug 1441818 - New advanced download page should not put Windows 32 & Linux 32 at the same level](https://bugzilla.mozilla.org/show_bug.cgi?id=1441818)
Open `/firefox/new/`, click on "Advanced install options & other platforms" and see the builds reordered like [this screenshot](https://screenshots.firefox.com/05SqX3GR1KuC1BxI/www-local.allizom.org).
> Fix Bug 1441818 - New advanced download page should not put Windows 32 & Linux 32 at the same level

- media/css/firefox/firstrun/firstrun-quantum.scss
- media/js/firefox/firstrun/firstrun_quantum.js
- Also fixes bug 1447724 - text artifacts caused by svg animation
Improves `/firstrun` page performance by removing animation on SVG waves. Also fixes text artifacts near animated Sync SVG images.
https://bugzilla.mozilla.org/show_bug.cgi?id=1417888
https://bugzilla.mozilla.org/show_bug.cgi?id=1447724
Ensure page elements are visible and transitions are working on all supported OSs.
> [fix bug 1417888] Remove /firstrun bg animation.

- bedrock/privacy/templates/privacy/base-quantum.html
Adds a link back to `/privacy/` on all Quantum-themed privacy pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1403474
Ensure I did the L10n correctly?
> [fix bug 1403474] Add back link to quantum privacy pages.

- bedrock/firefox/firefox_details.py
- bedrock/firefox/redirects.py
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/tests/test_helpers.py
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- docs/mozilla-notification-banner.rst
- media/js/base/mozilla-notification-banner-firstrun-whatsnew-init.js
- media/js/base/mozilla-notification-banner-init.js
- media/js/base/mozilla-pixel.js
- media/js/base/stub-attribution.js
- media/js/firefox/new/reggie-watts-scene1.js
- media/js/firefox/new/wait-face-scene1.js
- tests/functional/test_download.py
- tests/pages/firefox/new/thank_you.py
- tests/unit/spec/base/mozilla-notification-banner.js
- tests/unit/spec/base/stub-attribution.js
Having the page from which Firefox is actually downloaded be a "real" url and not a parameterized version of another URL will be better for a number of reasons, not least of which is that it will enable us to host a static version of the site that allows downloads.
> Bug 1438302: Move /firefox/new/?scene=2 to /firefox/download/thanks/

- bedrock/mozorg/templates/mozorg/about/manifesto.html
- media/css/mozorg/manifesto.scss
- media/css/pebbles/base/elements/_links.scss
- media/css/pebbles/includes/_variables.scss
- media/img/mozorg/about/manifesto/cta-arrow.svg
- media/js/mozorg/manifesto.js
- Added addendum text behind a switch.
- Added supporting CSS.
- Updated tweet button styling and content.
[Bug 1445070 - Addendum to manifesto](https://bugzilla.mozilla.org/show_bug.cgi?id=1445070)
- Addendum is hidden until the switch is activated
- The page title "The Mozilla Manifesto" is properly positioned with the switch enabled or disabled 
- RTL
> Bug 1445070: Addendum to the Manifesto

- bedrock/privacy/templates/privacy/base-quantum.html
- Fixes page titles for Quantum-themed Privacy policy pages.
https://bugzilla.mozilla.org/show_bug.cgi?id=1449561
- Page title for `/privacy/firefox/` should read "Firefox Privacy Notice - Mozilla"
> [fix bug 1449561] Firefox privacy page title

- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- Show locale specific templates for `id` and `zh-TW` when updating to `/firefox/59.0/whatsnew/`
https://bugzilla.mozilla.org/show_bug.cgi?id=1449558
- `/id/firefox/59.0/whatsnew/` and `/zh-TW/firefox/59.0/whatsnew/` should show locale specific templates when `Dev=False`.
> [fix bug 1449558] Include locale specific templates for zh-TW and id in 59.0 /whatsnew

- media/css/firefox/firstrun/firstrun-quantum.scss
- Fixes iframe alignment on `/firstrun/`
https://bugzilla.mozilla.org/show_bug.cgi?id=1449743
Demo: https://www-demo3.allizom.org/en-US/firefox/59.0/firstrun/
> [fix bug 1449743] Firstrun iframe is off center

- bedrock/mozorg/templates/mozorg/about/manifesto.html
Updates the title to "The Mozilla Manifesto Addendum" for English, other locales still get the original title until we can find another way to distinguish.
This also removes the switch since we no longer need it (I'll make a follow-up PR to www-config after this merges).
https://bugzilla.mozilla.org/show_bug.cgi?id=1450155
> [fix bug 1450155] Update Manifesto title for English

- bedrock/mozorg/templates/mozorg/about/manifesto.html
- media/js/mozorg/manifesto.js
Updating how the social sharing links are tracked to rely on the global configuration and not custom config for this page.
[Bug 1445070 - Addendum to manifesto](https://bugzilla.mozilla.org/show_bug.cgi?id=1445070#c10)
Open in a browser without DNT or TP, open network panel, click link, watch for call to Google. (Might only work on [a demo](https://bedrock-demo-shobson.us-west.moz.works/en-US/about/manifesto/)?)
> Update tracking on social share links

- media/css/mozorg/contribute/contribute-base.less
Moves a few UI elements lower in z-space. 
https://github.com/mozilla/bedrock/issues/5503
https://bugzilla.mozilla.org/show_bug.cgi?id=1444995
* Confirmed full-screen video works as expected in Fx, Chrome, Edge
* Confirmed the presence/appearance of nav on wide/narrow screens in Fx, Chrome, Edge (not sure why nav had a z-index=1).
* Confirmed the carousel continues to appear and advance as expected on wide/narrow screens in Fx, Chrome, Edge.
* Confirmed nav and links in carousel continue to work as expected on wide/narrow screens in Fx, Chrome, Edge.
> [fix bug 1444995] Fullscreen video in Chrome goes on top of UI

- bedrock/base/templates/includes/canonical-url.html
- Skip `/zh-CN/` hreflang on the home page, as it redirects to `http://www.firefox.com.cn/`
https://bugzilla.mozilla.org/show_bug.cgi?id=1448875
- Visit the homepage and you should not see either `hreflang="zh-CN"` or `hreflang="zh"` listed as alternate links.
- Visit any other page, such as `/firefox/` and both `hreflang="zh-CN"` or `hreflang="zh"` should be listed.
> [fix bug 1448875] Skip /zh-CN/ home page hreflang

- bedrock/firefox/templates/firefox/facebookcontainer/index.html
- media/css/firefox/facebook-container.scss
The extension is only available for desktop Firefox. This adds an alternative CTA for mobile browsers promoting Firefox Focus.
https://bugzilla.mozilla.org/show_bug.cgi?id=1449758#c26
The mobile tagline and CTA should only be shown when Android or iOS are detected, and the platform-appropriate store badge should appear.
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/facebookcontainer/
> [fix bug 1449758] Add Focus CTA for mobile browsers

- bedrock/newsletter/management/commands/update_newsletter_data.py
- bedrock/newsletter/models.py
- bedrock/newsletter/tests/test_misc.py
- bedrock/newsletter/utils.py
Checks for a difference before refreshing the data. This prevents the database checksum from changing needlessly every sync.
> Only change the DB if the Newsletter data has changed

- bedrock/mozorg/templates/mozorg/credits-faq.html
- media/css/mozorg/credits-faq.less
- Since `/credits/` is a supported non-locale, remove LANG from canonnical URL on `/credits/faq/`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1401728
- Visit `/credits/faq/` and the canonical URLs should be `https://www.mozilla.org/credits/faq/` and not `https://www.mozilla.org/en-UScredits/faq/`
> [fix bug 1401728] Omit LANG from canonical URL on /credits/faq/

- bedrock/firefox/templates/firefox/facebookcontainer/index.html
“Facebook” is a proper noun and should always be capitalized in English. We need to get this string updated so l10n can begin.
https://bugzilla.mozilla.org/show_bug.cgi?id=1453144
> [bug 1453144] Facebook Container - fix typo

- bedrock/firefox/templates/firefox/new/berlin/base.html
- bedrock/firefox/templates/firefox/new/berlin/scene1.html
- bedrock/firefox/templates/firefox/new/berlin/scene2.html
Adds lang files so the template will render for `/de/`.
I think this can only be tested on stage/prod.
> [fix bug 1447445] Add lang files to Berlin fxnew variation.

- bedrock/mozorg/middleware.py
This is not likely to help much, but it can't hurt. It's possible that some cache is not respecting just the 'max-age=0' header and needs the extra bits that the Django never_cache util provieds.
> Set better no-cache headers for l10n redirect responses

- bedrock/redirects/redirects.py
- tests/redirects/map_globalconf.py
Catch the case where there is no slash
Catch the case where there is no trailing slash.
[Bug 1388914 - Delete thunderbird content](https://bugzilla.mozilla.org/show_bug.cgi?id=1388914)
Does it redirect?
> Bug 1388914: Redirect /thunderbird to thunderbird.net

- bedrock/base/middleware.py
- bedrock/base/tests/test_middleware.py
- bedrock/base/tests/test_urlresolvers.py
- bedrock/base/urlresolvers.py
- bedrock/firefox/views.py
- media/js/base/mozilla-utils.js
- tests/unit/spec/base/mozilla-utils.js
This is not yet in a mergable state IMHO, but I would like for people to let me know what they think of the proposal and technique. There must be a better way to parse the current URL, but this does work. Needs tests, but there don't seem to currently be tests for the lang switcher function.
> Fix #5581: Switch lang switcher to client-side

- bedrock/base/templates/includes/site-footer.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1455460
The two links to facebook in the footer should be gone with no ill effects to layout.
> Fix Bug 1455460: Removed two links to facebook from footer per request from Janis G.

- bedrock/base/templates/base-pebbles.html
- bedrock/base/templates/base-resp.html
- bedrock/base/templates/base.html
- bedrock/settings/base.py
Bedrock sets HSTS for www.mozilla.org, but only a request from the root domain itself can set it for the root domain. This will set HSTS for all visitors to the site.
> Fix bug 1299817: Add img tag to set HSTS header for mozilla.org

- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- Adds [scoped](http://jinja.pocoo.org/docs/2.10/templates/#block-nesting-and-scope) modifier to `fxa_iframe` block, so it can access the `utm_source` variable.
https://bugzilla.mozilla.org/show_bug.cgi?id=1457539
- Ensure both default and copy variations show the correct UTM params.
> [fix bug 1457539] utm_source Empty for FxA iframe

- bedrock/firefox/templates/firefox/facebookcontainer/index.html
- media/css/firefox/facebook-container.scss
Adds a German-language video to display for the DE locale. All other locales fall back to the English video.
The original video is hosted by us but the German video is on youtube, I'm not sure why, it's what I was given.
https://bugzilla.mozilla.org/show_bug.cgi?id=1449758#c30
- Ensure the German video shows when LANG == 'de'.
- Ensure the English video shows for all other locales.
- Ensure the video resizes correctly at different breakpoints.
- No regressions, please.
> [fix bug 1449758] Add Facebook Container video for German

- docs/install.rst
Current snippet renders as `$ git submodule update –init –recursive` which is incorrect.
> Fix legal docs code snippet for updating git submodules

- bedrock/firefox/templates/firefox/whatsnew/index.id.html
Fix link on play store button to use adjust link.
[[Retention] update /whatsnew mobile CTA version - variation for Indonesia - Rocket](https://bugzilla.mozilla.org/show_bug.cgi?id=1455199)
- link on play store button
> Bug 1455199: Fix link on play button

- docker/bin/push2dockerhub.sh
It was removed in a new version and we've just recently upgraded
> Remove -e option from "docker login"

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx60.html
1. Update FxA iframe param
2. Use localized link for Fx accounts 'learn more' for non en-US
https://bugzilla.mozilla.org/show_bug.cgi?id=1457024#c43
https://github.com/mozilla/bedrock/pull/5607#discussion_r186730832
1. Ensure iframe still loads correctly.
2. Ensure correct URL is used for `Learn more about Firefox Accounts` link for `en-US` and non `en-US` (e.g. `de`).
https://www-demo4.allizom.org/en-US/firefox/60.0/whatsnew/
Instructions for testing the iframe on demo4 can be found in #5607.
> [fix bug 1457024] Fixes for Fx60 WNP:

- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- bedrock/firefox/templates/firefox/firstrun/index.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fxa.html
Features page is en only, link to sync for others
As spotted in: https://github.com/mozilla/bedrock/pull/5666/files#diff-6da246948f44628799c88b281633818bR43
> Bug 1444561: Features page is en only, link to sync for others

- bedrock/firefox/templates/firefox/organizations/organizations.html
- media/js/firefox/firefox-language-search.js
* Fix the Firefox 52 ESR download button on [/firefox/organizations/](https://www.mozilla.org/en-US/firefox/organizations/) leading to 60 ESR download links.
* Simply use a hash in the link and switch between tabs depending on it.
* Note that the button will be removed in this August once 52 ESR reaches EOL.
[Bug 1460968 - Button to "Get Firefox 52 ESR" points to ESR 60 (on /organizations)](https://bugzilla.mozilla.org/show_bug.cgi?id=1460968)
Click the Firefox 52 ESR download button and see 52 ESR downloads first.
> Fix Bug 1460968 - Button to "Get Firefox 52 ESR" points to ESR 60 (on /organizations)

- bedrock/firefox/templates/firefox/enterprise/index.html
- media/css/firefox/enterprise.scss
- tests/functional/firefox/test_enterprise.py
- tests/pages/firefox/enterprise.py
- Updates `/firefox/enterprise/` page with links to both general release and ESR downloads.
- Page is not yet localized, so copy changes should be fine as-is.
https://bugzilla.mozilla.org/show_bug.cgi?id=1458036
Demo:
-------
https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/enterprise/
> [fix bug 1458036] Copy updates to /firefox/enterprise/ page

- bedrock/firefox/templates/firefox/enterprise/index.html
- bedrock/firefox/templates/firefox/organizations/organizations.html
https://github.com/mozilla/bedrock/pull/5695 updated the tests for the Firefox Enterprise page but the old CTA was still visible and the new one was behind a switch, which meant the test looking for the new button wasn't finding it. Since that switch is no longer needed the ideal fix for the breaking test is to just remove the switch, making the new button visible for all.
https://bugzilla.mozilla.org/show_bug.cgi?id=1458036
> [bug 1458036] Clean up Enterprise switch

- wsgi/app.py
This was causing the app container to fail to start since New Relic was trying to start with a non existing config file called "False", thus causing the smoke tests to file since the app container did not stay running.
> Fix default setting for Newrelic INI File in wsgi/app.py

- bedrock/firefox/templates/firefox/enterprise/index.html
1. Change Firefox Rapid Release URL to https://www.mozilla.org/en-US/firefox/all/
1. Change Firefox ESR URL to https://www.mozilla.org/en-US/firefox/organizations/all/
Resolves #5718 
Click links.
> Resolves #5718 - 2 URL Changes to /enterprise

- bedrock/base/management/commands/update_www_config.py
- bedrock/base/templates/cron-health-check.html
- bedrock/base/views.py
- bedrock/externalfiles/management/commands/update_externalfiles.py
- bedrock/mozorg/management/commands/update_product_details_files.py
- bedrock/releasenotes/management/commands/update_release_notes.py
- bedrock/releasenotes/utils.py
- bedrock/security/management/commands/update_security_advisories.py
- bedrock/utils/git.py
- bedrock/utils/migrations/0002_auto_20180522_1249.py
- bedrock/utils/models.py
- bedrock/utils/tests/test_git.py
- requirements/base.txt
This is so that we can display the current commit synced to the db for each external repo on the /healthz-cron/ page. We also link to the repo, the commit, and display how long ago the repo was last updated.
Fix #5726
> Add more data to git repo state in the database

- bedrock/base/templates/base-protocol.html
- media/css/protocol/components/_download-button.scss
- media/css/protocol/components/_footer.scss
- media/css/protocol/components/_global-nav.scss
- media/css/protocol/components/_masthead.scss
- media/css/protocol/oldIE.scss
- media/css/protocol/protocol.scss
- Adds a new base template for Protocol.
- Ports the following components which do not yet exist in Protocol:
- Global nav
- Legacy masthead
- Download button
- Footer
- Adds a universal Protocol stylesheet for legacy IE browsers.
- Adds temporary test page for demo purposes.
https://github.com/mozilla/bedrock/issues/5752
Demo page: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/protocol-test/
> Add base template for Protocol design system (Fixes #5752)

- media/css/newsletter/fxnewsletter-subscribe.less
- Fixes sizing issue for newsletter logo on `/firefox/channel/desktop/` (and othe pages).
https://github.com/mozilla/bedrock/issues/5761
- Test using a low resolution screen.
> Newsletter logo is too large on low-res screens (Fixes #5761)

- bedrock/mozorg/templates/mozorg/moss/foundational-technology.html
- bedrock/mozorg/templates/mozorg/moss/index.html
- bedrock/mozorg/templates/mozorg/moss/mission-partners.html
Submitting a squashed #5743 with a different branch name to see if the tests pass.
It includes updates to the links to apply (Apply now buttons), disclosure copy and and change to the copy on frequency of evaluations.
The Do Not Merge tag has been applied due to the fact that the content should go live on June 1st (anytime) and not before
Issue #5730.
> [fix issue 5730] MOSS content updates for June 1

- docker-compose.yml
- docs/install.rst
- gulpfile.js
- package.json
Many docs and some external services are configured for port 8000, so let's keep it.
> Switch back to using port 8000 for local dev

- bedrock/firefox/templates/firefox/releases/nightly-feed.xml
- bedrock/firefox/templates/firefox/releases/release-notes.html
- media/css/firefox/releasenotes-firefox.less
Rename the **HTML5** section on the [Firefox release notes](https://www.mozilla.org/en-US/firefox/62.0a1/releasenotes/) to **Web Platform** to reflect the reality. This just changes the label in HTML and Atom feed so the backward compatibility in Nucleus will be maintained.
[Bug 1466834 - Rename or merge HTML5 section on Firefox release notes](https://bugzilla.mozilla.org/show_bug.cgi?id=1466834)
Open the 62.0a1 notes to see the new label like this:
> Fix Bug 1466834 - Rename or merge HTML5 section on Firefox release notes

- bedrock/firefox/urls.py
- bedrock/newsletter/urls.py
- bedrock/security/urls.py
All urls should end with a trailing slash, fix places where they're missing.
Closes https://github.com/mozilla/bedrock/issues/5783
Pages without trailing slash redirect 301 to the one with trailing slash.
> Fix #5783 - URLs available to resolve +/- trailing slash

- bedrock/firefox/templates/firefox/accounts-features.html
The button macro contains block level elements that can't be nested in a `<p>`. Change the `<p>` to a `<div>`.
https://github.com/mozilla/bedrock/pull/5749#issuecomment-395673226
> Fix DOM nesting

- Makefile
- docker-compose.yml
- docs/install.rst
Most developers won't need to build their own Docker images. Pulling our pre-built ones from the Docker Hub will work perfectly for them.  This patch changes the install instructions to reflect this as well as changing the majority of the Makefile commands to depend on pull rather than build.
> Move install instructions and Makefile to mostly just pull

- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2017.html
- bedrock/mozorg/urls.py
- Add Jul-Dec 2017 report
- Update links on landing page to link to newest report
- Add previous report to list of previous reports
- Add new question to FAQ
-  The transparency report has not been localized in the past.
Closes mozilla/bedrock#5747
- check I found all the links to the old report
> Add Jul-Dec 2017 Transparency Report

- bedrock/privacy/templates/privacy/faq.html
- bedrock/privacy/templates/privacy/index.html
- bedrock/privacy/urls.py
- Create new Privacy FAQ page
- Add link to it from privacy landing page
The privacy index page is currently translated but the sub pages do not appear to be. I'm not sure what the right thing to do with the new FAQ page is.
Closes mozilla/bedrock#5759
> Add Privacy FAQ

- bedrock/mozorg/templates/mozorg/about/governance/governance.html
- bedrock/mozorg/templates/mozorg/about/governance/roles.html
Update the [Governance](https://www.mozilla.org/en-US/about/governance/) page content based on the recent news group discussion.
[Bug 1467709 - Updates to governance pages /about/governance/](https://bugzilla.mozilla.org/show_bug.cgi?id=1467709)
Open the page, and check if the content is updated properly as specified in the bug.
> Fix Bug 1467709 - Updates to governance pages /about/governance/

- media/css/mozorg/home/home-2018.scss
Fixes system requirements link color contrast on home page
#5820
- A quck way to test this PR is to set a class on `oldmac` on the `<html>` element when viewing the home page (replacing your regular OS e.g. `osx`).
> Fix color contrast on links within Firefox homepage banner (Fixes #5820)

- bedrock/mozorg/templates/mozorg/contact/contact-base.html
One of the two OSM link wasn't in the Jinja trans statement
https://bugzilla.mozilla.org/show_bug.cgi?id=1465965
Checked manually
> Fix Bug 1465965: wrapped text in Jinja trans statement

- bedrock/releasenotes/tests/test__utils.py
Marks failing* `/releasenotes` util test with `xfail`.
* Only seems to fail in Circle, but not in Jenkins or locally.
> [fix #5829] xfail releasenotes timed cache test.

- bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Adds `class=prose` to all lists so they get the correct CSS styling.
[Bug 1461220 - List formatting broken on /about/governance/policies/security-group/certs/policy/](https://bugzilla.mozilla.org/show_bug.cgi?id=1461220)
Do the lists have bullets and numbers?
> Fix Bug 1461220: Add prose class to lists

- bin/deploy.sh
Fix issue in https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1076/pipeline/ where `git reset --hard origin/git-sync-operator` resulted in 
`fatal: ambiguous argument 'origin/git-sync-operator': unknown revision or path not in the working tree.`
> Use temp config_checkout in deploy.sh

- bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
OpenHatch has [closed its doors](https://blog.openhatch.org/2017/celebrating-our-successes-and-winding-down-as-an-organization/) and is no longer providing assistance to new contributors. Removing it from the page lest we lead new contribs down a blind alley.
None. Just something I spotted while reading the Open Innovation page.
> Remove OpenHatch

- jenkins/default.groovy
Address issues like https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1083/pipeline/ due to concurrent builds possible with separate commits.
> Remove git commit from build lock

- bedrock/privacy/redirects.py
- bedrock/privacy/templates/privacy/index.html
- bedrock/privacy/templates/privacy/notices/firefox-fire-tv.html
- bedrock/privacy/urls.py
- bedrock/privacy/views.py
- media/css/privacy/privacy.less
- tests/redirects/map_globalconf.py
- Adds a new privacy notice for Firefo for Fire TV at `/privacy/firefox-fire-tv/`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1469981
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/privacy/firefox-fire-tv/
> [fix bug 1469981] Firefox for Fire TV Privacy Notice

- bedrock/firefox/templates/firefox/organizations/organizations.html
One button read "Get Firefox ESR 60" and the other read "Get Firefox 52 ESR". This updates them to consistently use the "Get Firefox [version] ESR" format for both.
This page doesn't appear to be localized but if it is I can add a tag for this string change.
https://twitter.com/pratab_a/status/1012637039119011840
> [no bug] Consistent labeling for ESR buttons

- bedrock/privacy/templates/privacy/index.html
- media/css/privacy/privacy.less
A link was omitted in PR #5850 but strings had already been extracted so this separate PR adds the link behind new tag, `updates-072018`
#5745
> [#5745] Add principles link to privacy sidebar

- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
- bedrock/mozorg/urls.py
Removes the switch added in #5848 now that the page is live. This should also address intermittent errors occurring in production (see https://github.com/mozilla/bedrock/issues/5747#issuecomment-402277888)
> [#5747] Clean up transparency report switch

- bedrock/mozorg/templates/mozorg/moss/foundational-technology.html
- bedrock/mozorg/templates/mozorg/moss/mission-partners.html
Swapped out the old application link for MOSS (a Google Form that's been deprecated) for the current link (to the new Fluxx application) on two pages in the MOSS templates.
> Swapped out old MOSS applicaiton link for new one

- bedrock/base/templates/macros.html
Long term I think we should really move this to a Python FxA helper, as this marco is doing a lot of logic (and could do with some unit tests?). But this should hopefully fix the analytics issues for short term.
https://github.com/mozilla/bedrock/issues/5870
- Make sure the URLs match the expected format highlighted in the issue?
> Remove invalid chars from UTM params on /firefox/accounts/features/ CTAs (Fixes #5870)

- bedrock/firefox/templates/firefox/channel/android.html
- bedrock/firefox/templates/firefox/channel/desktop.html
- media/css/firefox/channel.less
- Replaces https://github.com/mozilla/bedrock/pull/5843
- Updates privacy copy
- Updates copy on /channel/android/ to match desktop
- Updates legal-docs to reflect the new pre-release text linked to from /channel
**Note:** ~strings are not yet final.~ The ask is for this to go out on the 10th, as we're still waiting for an update to the Firefox privacy notice.
https://github.com/mozilla/bedrock/issues/5746
- Check for copy pasta?
> /channel/desktop page content update

- bedrock/firefox/templates/firefox/new/berlin/base-herz.html
Fixes issue #5913 
Strings are hard-coded in German, no l10n impact.
> [#5913] Update /firefox/new “herz” variant headline

- bedrock/firefox/templates/firefox/releases/release-notes.html
- More user friendly page titles
- Remove title suffix
Closes #5751 
- Do all the different release versions still have a well formatted title?
> Update release notes page titles

- Dockerfile
- Makefile
CircleCI was only running a partial build of our images for pull-requests, but we need it to run the full release build so that we can make sure all assets build correctly before merge.
> Fix #5928: Run full release Docker build in PR tests

- bedrock/base/templates/macros.html
When I added the new button_class param I neglected to append it to the other buttons shown for other cases (mobile, outdated Firefox, etc).
Test in Firefox on a mobile device or use dev tools to hide/unhide the various bits.
> [#5862] FxA button - append button_class to fallback buttons

- bedrock/base/templates/base-protocol.html
- bedrock/base/templates/includes/protocol/lang-switcher.html
- bedrock/base/templates/includes/protocol/site-footer.html
- bedrock/mozorg/templates/mozorg/home/home-en.html
- media/css/mozorg/home/home-2018.scss
- media/css/protocol/components/_footer.scss
- media/css/protocol/components/_global-nav.scss
- media/css/protocol/components/_masthead.scss
- media/css/protocol/protocol.scss
- media/js/base/protocol/init-lang-switcher.js
- media/js/mozorg/home/home.js
- media/static-bundles.json
- package.json
- tests/functional/test_l10n.py
- yarn.lock
- Update bedrock to `@mozilla-protocol/core` v2.0.0.
- Update bedrock homepage to use `@mozilla-protocol/tokens` values.
- Update homepage footer & language switcher to use Protocol components.
- Use `protocol-oldIE` bundle for fallback CSS.
**Blocked by**: https://github.com/mozilla/protocol/issues/174
N/A
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/197/pipeline
Things to test for:
> Update @mozilla-protocol/core to v2.0.1

- bin/move_hashed_staticfiles.py
- bin/upload-staticfiles.sh
Instead of trying to match filenames it is more accurate to use the JSON map Django gives us to move the hashed files to a new directory and do the `aws s3 sync` separately for each type of file.
> Use staticfiles.json map to set proper cache headers in s3

- bedrock/security/templates/security/bug-bounty.html
- bedrock/security/templates/security/client-bug-bounty.html
- bedrock/security/templates/security/web-bug-bounty.html
We've added Safe Harbor language to our bug bounty pages and have updated client and web bounty pages accordingly. Also added a link to the client bounty submission form.
These are changes to the bug bounty mozilla.org pages from Marshall Erwin and others on the legal team. These are text only changes to conform to new language.
There is no open issue or bug for this.
> Changes to bug bounty pages for safe harbor

- bedrock/security/templates/security/base.html
- bedrock/security/templates/security/bug-bounty.html
- bedrock/security/templates/security/client-bug-bounty.html
- bedrock/security/templates/security/index.html
Updating sidebar and main index to link to top level bug bounty page because there was only a hidden link to the overall progrm. Fixed mailto: links and updated language for the first time in eight years for clarity.
> Update security sidebar and main index to link to top level bug bounty page

- media/js/firefox/new/better-browser-experiment.js
Updates the query params being verified to match those out in the wild.
https://bugzilla.mozilla.org/show_bug.cgi?id=1452765#c36
Code should now match a URL like the following:
https://www.mozilla.org/en-US/firefox/new/?gclid=EAIaIQobChMIrIazwNLZ3AIVE1cNCh197wCvEAMYAiAAEgJ3WPD_BwE&gclsrc=aw.ds&utm_campaign=Firefox%7cGG%7cSearch%7cNB%7cExact%7cSP%7cUS%7cEN%7cDK%7cText%7cCompetitor&utm_content=A144_A203_A008874&utm_medium=cpc&utm_source=google&utm_term=internet%20explorer
> [fix bug 1452765] Update betterbrowser experiment query params.

- bedrock/legal_docs/tests/test_base.py
- bedrock/legal_docs/views.py
- lib/l10n_utils/dotlang.py
Also filter out legal-docs translations that are not production bedrock locales.
see also: https://github.com/mozilla/legal-docs/issues/1155
> Fix #6000: Map legal-docs locales to bedrock prod locales

- bedrock/foundation/templates/foundation/about.html
Update about page (https://www.mozilla.org/en-US/foundation/about/ ) to remove Cathy Davidson.
#6002
> Fix #6002: Remove Mozilla Board member from Foundation/About page

- bedrock/base/templates/404.html
- Removes canonical and hreflang's from URLs that are 404.
#5895
- Hit `/en-US/404/` locally to test.
> 404 pages must not include canonical and hreflang x-default (Fixes #5895)

- tests/functional/firefox/new/test_download_yandex.py
@craigcook I totally forgot that these tests will only pass once we enable Yandex on prod. Once this is merged we can push to prod before enabling on stage to test.
> Skip Yandex functional tests until switch is enabled

- bedrock/base/templates/includes/site-footer.html
Adds a general privacy link and a press center link, to replace those being removed from the About page. Since the new About page is English-only (for now), the Privacy link is also English-only to avoid string conflicts (otherwise it would show two identical strings for most locales). We need to get the "Website Privacy Notice" fully localized in main.lang so we can remove these conditionals.
> Add press and privacy links to footer

- bedrock/mozorg/templates/mozorg/home/home-en.html
- bedrock/mozorg/views.py
- bedrock/pocketfeed/api.py
- bedrock/pocketfeed/management/commands/update_pocketfeed.py
- bedrock/pocketfeed/models.py
- bedrock/pocketfeed/tests/test_api.py
- bedrock/pocketfeed/tests/test_models.py
The fallback image is currently passed through `lazy_img` but could be used in other contexts, so this should be handled at the view or template layer.
Also increase the number of articles fetched to 8 and limit the display to 4. This will help if one of the fetched articles fails to store for some reason.
Only update pocket articles when timestamp changes. This will prevent the DB from appearing to change on every run of `update_pocketfeed`.
Fix warnings from storing non-aware datetime objects for pocket.
> Fix #6036: Handle no pocket article image in template

- bedrock/mozorg/templates/mozorg/about-en.html
Bring back translations to /en-US/about/
> Fix #6047: Add about langfile to new about-en.html template

- bedrock/firefox/redirects.py
- tests/redirects/map_globalconf.py
The version with the trailing slash already redirects, this just includes the URL without the trailing slash.
> Fix #6045: Redirect /firefox/download to /firefox/new/

- docker/bin/push2dockerhub.sh
Add :prod-latest tags for production images. This means that local devs would get updated images with updated dependencies much more quickly just via a `make pull` instead of having to build fresh images themselves.
> Use :latest docker tags for builds from "master"

- bedrock/firefox/templates/firefox/releases/system_requirements.html
Display product name on system requirements pages instead of "Firefox" so we can tell the system requirements for "Firefox for Android" apart.
Closes #6053 
Firefox system requirements are linked to from here: https://www.mozilla.org/en-US/firefox/all/
Firefox Android system requirements are linked to from here: https://www.mozilla.org/en-US/firefox/android/60.0beta/releasenotes/
As far as I can tell the page is not translated so it's okay to update the strings.
> Add product name to titles

- bedrock/grants/templates/grants/info.html
Set h1 as <title> for grants pages
https://github.com/mozilla/bedrock/issues/6078
> Set h1 as <title> for grants pages

- bedrock/firefox/templates/firefox/tracking-protection-tour.html
Updates two strings in the Tracking Protection tour using the l10n tag `tp_tour_firefox_201809`
https://bugzilla.mozilla.org/show_bug.cgi?id=1466235
Issue #6056 
https://www-demo4.allizom.org/firefox/62.0a1/tracking-protection/start/?step=3
https://www-demo4.allizom.org/en-US/firefox/62.0a1/tracking-protection/start/?step=3&newtab=true
You'll need to whitelist `https://www-demo4.allizom.org` in about:config > browser.uitour.testingOrigins
> [fix bug 1466235] Update tracking protection tour strings

- bedrock/releasenotes/tests/test__utils.py
Assumption is this was failing due to a race condition, so bumped the `time.sleep` up `0.1` to be just greater than the specified cache timeout (of `1.0`).
As long as this passes in Circle, we should be good...I think.
> [fix #5829] Improve releasenotes version change test.

- media/css/firefox/whatsnew/whatsnew-62.scss
https://github.com/mozilla/bedrock/issues/5946#issuecomment-417498724
You'll need to view the page with an outdated Firefox so the "up to date" message is hidden; verify the header logos look acceptable (Firefox on the left, Mozilla/Pocket on the right in wide viewports). Short of using an actual old Firefox you can also fake it by removing the "show-up-to-date-messaging" class in devtools, or locally commenting out the `checkUpToDate` function in whatsnew-62.js.
To see the sendto widget you'll need to either be signed into a Firefox account or fake it by firing the `showFirefoxMobile()` event in whatsnew-62.js. There's a "learn more" link in the privacy statement below the form field. It should be blue when unvisited, purple when visited.
> [#5946] CSS fixes for Whatsnew62

- media/css/firefox/whatsnew/whatsnew-62.scss
Fixing the new bug my previous bug fix introduced.
The Mozilla logo should appear on the right in large viewports for all page states besides the Pocket promo. It should be hidden in small viewports.
> [#5946] Fix Mozilla logo display on whatsnew62

- tests/functional/firefox/new/test_download_yandex.py
Yandex is now enabled in production, so removing the skip for functional tests.
> Enable Yandex functional tests (#5635)

- bedrock/firefox/templates/firefox/developer/firstrun.html
- bedrock/firefox/templates/firefox/developer/index.html
- bedrock/firefox/templates/firefox/developer/whatsnew.html
- media/css/firefox/developer/developer.scss
- media/css/firefox/developer/firstrun.scss
- media/css/firefox/developer/whatsnew.scss
* Add "Learn more" links to the highlights section on firefox/developer/
* Link images in the highlights section on
* firefox/developer/
* firefox/62.0a2/firstrun/
* firefox/61.0a2/whatsnew/
Follow up to #6122
Changes were tested locally. Sorry for not providing test links.
> Fix inconsistencies in Developer Edition pages

- bedrock/firefox/templates/firefox/tracking-protection-tour/index.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-0.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-1.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-2.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- media/js/firefox/tracking-protection-tour.js
- Updates existing Tracking Protection tour for Content Blocking shield study, to launch during 63 Beta.
- Shield study will be en-US only for Firefox 63 Beta, but the ask is to localize these new strings ahead of rolling out to all locales post-study.
- Strings have been [tested and verified on demo](https://bugzilla.mozilla.org/show_bug.cgi?id=1484585#c10) by the Firefox team. Further QA will happen when this goes to production before the shield study is launched.
~I will update here when strings are final~ strings are final
**Needs to be in prod for Monday 10th September**
#6082
First, make sure to **test in Nightly** (strings have not yet been uplifted to Beta).
Next, whitelist UITour for the demo instance by creating a new preference called `browser.uitour.testingOrigins` in …
> Update Tracking Protection tour strings for Content Blocking shield study (#6082)

- media/css/firefox/features/detail.scss
The password manager icon is wider than most, needed a width adjustment in the CSS to prevent clipping the sides.
#6135
> [fix #6135] Icon clipped on /firefox/features/password-manager/

- jenkins/branches/master.yml
Due to continuing issues with 504s: https://github.com/mozmeao/infra/issues/908
> Remove frankfurt from master deploys

- bedrock/firefox/templates/firefox/new/compare/scene1-chrome-2.html
- media/css/firefox/new/compare.scss
Adds a footnote to the Chrome comparison (V2) page indicating which versions were compared.
https://github.com/mozilla/bedrock/pull/6143#issuecomment-419564801
> [#6141] Add disclaimer to Chrome comparison page

- bedrock/firefox/templates/firefox/new/compare/scene1-chrome-2.html
- bedrock/firefox/templates/firefox/new/compare/scene1-edge-2.html
- bedrock/firefox/templates/firefox/new/compare/scene1-safari-2.html
Change text to speech to "Yes" for Chrome.
Remove "Languages available" for all three.
#6166 
https://github.com/mozilla/bedrock/issues/6141#issuecomment-420738661
> [#6141, #6166] Update browser comparison pages

- bedrock/mozorg/templates/mozorg/about-en.html
- media/js/mozorg/about-en.js
- media/static-bundles.json
The new about page was loading the home page JS bundle (probably an artifact of save-as). This adds a new JS bundle for the about page for the lazyloading images and newsletter form, minus the video and waypoints stuff.
#6175 
Just make sure the page works as it should without errors. Images should load and the newsletter form should expand and submit.
> [Fix #6175] Fix about page JS bundle

- media/css/firefox/developer/developer.scss
- media/css/firefox/developer/firstrun.scss
The styling for the bottom download CTA on the dev edition pages was moved to a separate include file in https://github.com/mozilla/bedrock/pull/6132 but we forgot to `@import` it back into the main style sheet.
Also removed a redundant mixin.
Before (unstyled):
After (styled):
The dev edition whatsnew and firstrun pages also have the same section, but promoting Nightly:
Verify the page section is styled on all three pages, and that the whatsnew and firstrun pages for dev edition show the Nightly logo. And the usual testing for responsiveness etc.
> Fix bottom download CTA on dev edition pages

- bedrock/privacy/templates/privacy/notices/firefox-monitor.html
- bedrock/privacy/urls.py
- bedrock/privacy/views.py
Adds a new page for the Firefox Monitor terms and privacy notice. The URL will be https://www.mozilla.org/privacy/firefox-monitor/ This page is currently *NOT* linked from the main privacy page.
Also updates the legal-docs submodule.
This needs to be in production on 20 September if possible.
#6205 
https://bugzilla.mozilla.org/show_bug.cgi?id=1491440
> [fix #6205] Add Firefox Monitor privacy notice

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/profile/profile-base.html
- bedrock/firefox/templates/firefox/profile/profile-downgrade.html
- bedrock/firefox/templates/firefox/profile/profile-migrate.html
- bedrock/firefox/urls.py
- media/css/base/mozilla-fxa-form.scss
- media/css/firefox/profile-per-install.scss
- media/css/protocol/components/_fxa.scss
- media/js/base/mozilla-fxa-form.js
- media/static-bundles.json
Adds two variant pages explaining the new changes in profile management to users with multiple installs. This change is targeted for Firefox 64 but is due to land in Nightly in a few days so we need to a) secure the URLs since they'll be in-product and b) allow plenty of time for l10n before the release of Fx64.
Note this also includes some changes in the iframeless FxA macro that can have impact on other current FxA work such as #5974 
#6054 
#5655 
https://bugzilla.mozilla.org/show_bug.cgi?id=1474285
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/profile-migrate/
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/profile-downgrade/
> [#6054, #5655] Profile-per-install messaging

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/new/fx/scene1.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- media/css/base/mozilla-fxa-form.scss
- media/css/firefox/new/scene1-fx.scss
- media/js/base/mozilla-client.js
- media/js/firefox/new/scene1-fx-experiment-x.js
- media/js/firefox/new/scene1-fx-experiment-y.js
- media/js/firefox/new/scene1-fx-experiment.js
- media/static-bundles.json
- update client.js to not need jQuery to run (please look at this closely)
- add experiment using x and y for variations
- experiment is triggered on scene1 for en-US
- then traffic cop checks for current Firefox Desktop usage before starting experiment
- Firefox users are split 50% to x and 50% to the control (y)
- x variant users are sent to the scene2 page which does not ask for email address again
mozilla/bedrock#5974
https://www-demo4.allizom.org/en-US/firefox/new/
You will need to enable UITour for demo4 and/or localhost to do the testing.
The different states to test are here: https://github.com/mozilla/bedrock/issues/5974#issuecomment-412686553
> experiment to add FxA CTA to /new

- bedrock/firefox/redirects.py
- tests/redirects/map_globalconf.py
> Fix #6209: Redirect /pocket to /firefox/pocket

- bedrock/firefox/templates/firefox/all.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/scene2.html
- media/css/firefox/all.less
- media/css/firefox/new/scene1.scss
- media/css/firefox/new/scene2.scss
- media/js/base/site.js
- media/js/firefox/new/scene1.js
* Firefox 52 ESR reaches the EOL on September 5. The Firefox download buttons have to be updated to show a warning to Windows XP/Vista users while allowing downloads
* See [my bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1339226#c17) for details and screenshots
* I don’t know how Protocol works so didn’t add any warning styling to `media/css/protocol/components/_download-button.scss`
There are 2 new short strings. The latter is TBD
```html
<a href="%(url)s">Mozilla no longer provides security updates for Firefox on Windows XP or Vista</a>, but you can still download the final Windows 32-bit version below.
```
```html
You’re using an insecure, outdated operating system <a href="%(url)s">no longer supported by Firefox</a>.
```
[Bug …
> Fix Bug 1339226 - Update download buttons for Windows XP/Vista users once Firefox 52 ESR reaches EOL

- bedrock/settings/base.py
Now that we're distributing sqlite databases with these data we should use it in non-prod situations as well. The file-based data is very old.
> Always use database product-detail storage

- bedrock/firefox/redirects.py
> /firefox/download/thanks redirects to /firefox/new/ (Fixes #6210)

- media/css/base/notification-banner.less
- media/css/pebbles/components/_notification-banner.scss
- media/js/base/mozilla-notification-banner.js
Make notification banner content container visible 
#6246 
Load https://www.mozilla.org/en-US/firefox/60.0.2/whatsnew/?oldversion=59.0.2 in an out of date version of firefox.
> Make notification banner content container visible to fix #6246

- bedrock/mozorg/urls.py
Fix intermittent NoReverseMatch error
#6252
check https://www.mozilla.org/en-US/internet-health/open-innovation/ and https://www.mozilla.org/en-US/grants/ (or local/dev/demo equivalent)
> Fix #6252 by using mozorg.moss.index name for url 

- bedrock/firefox/templates/firefox/developer/includes/highlights.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1494310
> [fix bug 1494310] Rename shadow-outside to shape-outside on /firefox/developer/

- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-0.html
- A minor string change: "Restart tour" to "Restart Tour".
- Both strings are already in the template, so no l10n required.
#6082
- Test in Nightly.
- Page should be opened in a private browsing window with Content Blocking enabled.
- URL: `/firefox/63.0/tracking-protection/start/?variation=0`
> Capitalize 'Restart Tour' in variation 0 of Tracking Protection tour (#6082)

- bedrock/legal/urls.py
- bedrock/legal/views.py
- bedrock/legal_docs/tests/test_base.py
- bedrock/legal_docs/views.py
- bedrock/mozorg/util.py
- bedrock/newsletter/tests/test_footer_form.py
- bedrock/newsletter/tests/test_views.py
- bedrock/privacy/views.py
- docs/l10n.rst
- lib/l10n_utils/__init__.py
- lib/l10n_utils/dotlang.py
- lib/l10n_utils/gettext.py
- lib/l10n_utils/tests/test_base.py
- lib/l10n_utils/tests/test_dotlang.py
- lib/l10n_utils/tests/test_template.py
- tests/redirects/map_globalconf.py
This modifies how several parts of translation in bedrock work:
1. You can now provide a list of locales in `active_locales` in the template context that will be the list of available translations for the page.
2. You can now provide a list of locales in `add_active_locales` to add extra available translations for the page.
3. The `page()` and `LangFilesMixin` helpers are updated to support these new context items.
4. You can now create and use `en-US` locale-specific-templates.
> Fix #5851: Support overriding or ammending list of locales

- media/css/firefox/new/compare.scss
- media/css/firefox/new/scene2.scss
- media/css/firefox/pocket.scss
- media/css/firefox/whatsnew/whatsnew-62.scss
- media/css/mozorg/about-en.scss
- media/css/mozorg/home/home-2018.scss
- media/css/mozorg/lean-data.scss
- media/css/privacy/privacy-email.scss
- media/css/protocol/components/_download-button.scss
- media/css/protocol/components/_footer.scss
- media/css/protocol/components/_global-nav.scss
- media/css/protocol/components/_masthead.scss
- media/css/protocol/oldIE.scss
- media/css/protocol/protocol.scss
- package.json
- yarn.lock
- I'm updating Protocol in a separate PR here to make the navigation easier to review, plus there are more changes here not directly related to the nav, so it probably makes sense to do this separately.
N/A
- You'll need to run `make build` after pulling this PR down locally to pick up the new npm package inside docker.
- Things to check:
> Update @mozilla-protocol/core to v2.4.2

- bedrock/newsletter/templates/newsletter/existing.html
- bedrock/newsletter/views.py
Exclude interest newsletters in formset to avoid error state where newsletters are in initial data but not in final form submission.
Fix bug 1483611
> Fix email pref center

- media/css/firefox/election.scss
> Hide nav download button on /firefox/election/ page (Fixes #6288)

- bedrock/firefox/templates/firefox/tracking-protection-tour/index.html
Adds a tracker that loads a cookie to the Content Blocking tour, in order to fix a bug when only cookie restrictions are enabled.
https://bugzilla.mozilla.org/show_bug.cgi?id=1495671
1. Test using **Firefox Beta**
2. Set `browser.contentblocking.ui.enabled` to `true`
3. [Enable UITour](https://bedrock.readthedocs.io/en/latest/uitour.html#local-development) for demo and/or local dev.
4. Open `about:preferences#privacy`
5. Set Content Blocking prefs like so:
- Third party cookies - block trackers OR block all third parties
- All Detected Trackers - OFF or Only in private mode
- Slow Loading Trackers - OFF
Expected results: step 3 of the tour should display correctly (with info panel pointed at control center).
Test URL: `/firefox/63.0/tracking-protection/start/?newtab=true`
> [fix bug 1495671] Content Blocking Tour breaks on step 3 with only cookie restrictions enabled.

- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-1.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-2.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- Exposes content blocking tour variations to all locales.
- Adds some last minute string changes due to FastBlock not shipping in FF 63.
- Needs to be in production before FF 63 launch (10/23).
https://bugzilla.mozilla.org/show_bug.cgi?id=1498290
https://bugzilla.mozilla.org/show_bug.cgi?id=1499589
> [fix bug 1498290] Expose locale versions of Content Blocking Tour

- bedrock/mozorg/templates/mozorg/home/home-en-election.html
Update first card title from "Get the Firefox Election Bundle" to "Get the Firefox U.S. Election Bundle" per request from legal.
> Update Firefox Election Bundle card title

- bedrock/firefox/templates/firefox/developer/includes/highlights.html
- media/css/firefox/developer/developer.scss
- media/css/firefox/developer/includes/highlights.scss
Use flexbox instead of float to fix the broken layout. The reported page is French but this could happen in any locale.
[Bug 1500250 - Broken layout on https://www.mozilla.org/fr/firefox/developer/](https://bugzilla.mozilla.org/show_bug.cgi?id=1500250)
Visit /fr/firefox/developer/ and make sure the layout is fixed.
> Fix Bug 1500250 - Broken layout on https://www.mozilla.org/fr/firefox/developer/

- media/js/firefox/new/yandex/scene1.js
Add data attributes to Yandex download button.
**data-link-name="Yandex redirect"
data-link-type="Download Firefox (RU)"**
_optional_
_data-link-position="primary cta"
data-link-group="" //any extra info
data-cta-position="" //any extra info_
#6276
> Add data attributes to Yandex download button

- bedrock/mozorg/templates/mozorg/about/forums/cancellation.html
- bedrock/mozorg/templates/mozorg/about/forums/etiquette.html
- bedrock/mozorg/templates/mozorg/about/forums/forums.html
- bedrock/mozorg/templates/mozorg/about/policy/patents/guide.html
- bedrock/mozorg/templates/mozorg/about/policy/patents/index.html
- bedrock/mozorg/templates/mozorg/about/policy/patents/license-1.0.html
- bedrock/mozorg/templates/mozorg/about/policy/patents/license.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
- Follow up on conversion off Sandstone
- The nav menu macro needs the body to be set this way instead of with the block
- Also a small formatting fix for the transparency index page.
> Change how ID is set on forms, patents, and transparency

- bedrock/firefox/templates/firefox/releases/release-notes.html
- media/css/firefox/releasenotes-firefox.less
* Always show the Developer section and the **Developer Information** link on Firefox release notes, so the redundant **Changes affecting developers** item no longer has to be added manually to each note.
* Fix the alignment of elements on the section.
[Bug 1500952 - Always show Developer Information link even if there’s no Developer item](https://bugzilla.mozilla.org/show_bug.cgi?id=1500952)
* Visit `/en-US/firefox/64.0a1/releasenotes/` and make sure the Developer section is visible.
* Visit `/en-US/firefox/55.0a1/releasenotes/` and make sure 1 developer item and the Developer Information link are visible.
Here are the screenshots 😃
> Fix Bug 1500952 - Always show Developer Information link even if there's no Developer item

- bedrock/foundation/templates/foundation/index.html
Add to the description of the corporation that it owns and is responsible for mozilla.org websites other than foundation.mozilla.org per legal request.
[1500937](https://bugzilla.mozilla.org/show_bug.cgi?id=1500937)
> Add clarifying legal copy to /foundation

- bedrock/firefox/templates/firefox/tracking-protection-tour/index.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-0.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-1.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/variation-2.html
Fixes #6358
@pmac this is the only filter I could find that seems to fix the issue. Curious if this is ok, or if there's a better way?
You can test this URL in a **private browsing window** to see the result (step 3 should show the string in question). You'll also need to whitelist your local dev server for [UITour](https://bedrock.readthedocs.io/en/latest/uitour.html#local-development)
`/da/firefox/63.0/tracking-protection/start/?step=1&variation=1`
> Truncated strings in Content Blocking tour for some locales (Fixes #6358)

- media/js/base/mozilla-fxa-form.js
Ensures that only users with `distribution` equal to `mozillaonline` get redirected to the Chinese re-pack FxA URL.
#6365
I believe the only way to truly test this is with non-default builds of Firefox. We should test with both the China re-pack and a Fedora build, but I'm not sure how to easily do this.
HOWEVER, we do have [existing code checking against this specific value](https://github.com/mozilla/bedrock/blob/bb1a65b048f130a4e1baa70a1a040eb462838c55/media/js/firefox/firstrun/firstrun_quantum.js#L67), so I think this is pretty safe.
> [fix #6365] Make FxA email form JS china re-pack distribution check more specific

- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/channel/base.html
- bedrock/firefox/templates/firefox/enterprise/index.html
- media/css/firefox/accounts.scss
- media/css/firefox/enterprise.scss
- Adds Protocol navigation component to `/firefox/channel/`, `/firefox/accounts/` and `/firefox/enterprise/` pages.
#6381
> Add main navigation to /firefox/channel/, /firefox/accounts/ and /firefox/enterprise/ (Fixes #6381)

- bin/deploy.sh
Use independent cluster deployments to allow different values per cluster-- for example, the number of replicas, as some clusters need more replicas than others.
https://github.com/mozmeao/infra/issues/965
During deploy, values from the files in all-clusters deployments should no longer override the cluster-specific deployments.
> Eliminate all-clusters templates and use independent deploys

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/new/fx/scene1.html
- Change campaign parameters on fx-fxa experiment form.
- Add URL to explanations about how to pick campaign values
https://github.com/mozilla/bedrock/issues/5974
Make sure I got these right:
utm_source = firefox-new
utm_content = firefox-new-fxa-v1 
utm_campaign = firefox-new
utm_term = existing-users
entrypoint = firefox-new
form_type = email
You need to be in Firefox to test, you might also need to enable UI Tour (I can't remember, tryfirst before going to that trouble?)
Up on demo here: https://bedrock-demo-shobson.oregon-b.moz.works/en-US/firefox/new/?v=x
> Change campaign parameters on fx-fxa experiment form

- bedrock/base/templates/includes/protocol/navigation/menu/firefox.html
- Updates Pocket link in navigation to point directly to `https://getpocket.com/firefox_learnmore/`.
Note: the `/firefox/pocket/` page is staying around, at least for now, as it might have some SEO value still.
#6450
> Remove interstitial link to Pocket in the main navigation (Fixes #6450)

- bedrock/firefox/templates/firefox/releases/index.html
- bedrock/firefox/templates/firefox/releases/release-notes.html
- Adds Protocol navigation menu to `/firefox/releases/` and `/firefox/releasenotes/` pages.
#6403
> Add Protocol navigation to release notes pages (Fixes #6403)

- bedrock/mozorg/templates/mozorg/technology.html
- Updates newsletter form on `/technology` to subscribe to Mozilla Labs newsletter (English locales only).
#6400
https://bugzilla.mozilla.org/show_bug.cgi?id=1503021
> Add Mozilla Labs newsletter form to /technology (Fixes #6400)

- bedrock/base/templates/includes/protocol/navigation/menu/firefox.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1506463
> [fix bug 1506463] Fix typo in Firefox subtitle in navigation

- media/css/firefox/developer/developer.scss
The Dev Edition product page at https://www.mozilla.org/firefox/developer/ uses some CSS to hide the standard download button in the global nav, but the new global nav has different classes so the new button isn't hidden. We just need to add the appropriate class name to the page style sheet. 
#6473
> [fix #6473] Hide Fx download button in nav on Dev Edition product page

- bedrock/foundation/redirects.py
- tests/redirects/map_globalconf.py
Add in redirects for various `/foundation/` paths on Bedrock, leading to the new foundation homepage on foundation.mozilla.org.
Closes #6467
> Implement redirects to foundation.mozilla.org

- bedrock/settings/base.py
Those changes will be particularly important for the upcoming fundraising banner in https://github.com/mozilla/bedrock/pull/6501
Changes:
- Adding CAD since we now have en-CA support on moz.org
- Adjusting currency presets based on latest exchange rates.
- Fixed CLP values, they were quite off
> Update currency presets for 2018 Fundraising banner

- media/css/mozorg/home/fundraiser2018.scss
Reduces some redundant CSS by eliminating the button `@import` and just adding the button styling directly.
Make sure buttons look right on both English and non-English pages.
> [#6465] Reduce home fundraiser button styles

- bedrock/mozorg/views.py
This endpoint should never be cached. (Query params _should_ keep it from being cached, but better to be explicit.)
> Add never_cache decorator to FxA OAuth endpoint.

- bedrock/firefox/urls.py
- Sets active locales for `/firefox/fights-for-you/` campaign page ([docs link](https://bedrock.readthedocs.io/en/latest/l10n.html#specifying-active-locales-in-views)).
#6387
- With `Dev=False` in your `.env` file, both English and German should be available in the language switcher in the page footer.
> Set active locales for FFY campaign page (#6387)

- bedrock/base/templates/includes/lang_switcher.html
- bedrock/base/templates/includes/protocol/lang-switcher.html
- media/css/pebbles/components/_footer.scss
- media/css/sandstone/sandstone-resp.less
- Adds a link to the new `/locales/` page from the language switcher in the main site footer.
#6455
- Lang switcher in footer should appear as expected on Protocol, Pebbles, and Sandstone pages.
> Add link to /locales/ page from the main footer (Fixes #6455)

- media/css/mozorg/home/fundraiser2018.scss
Close button wasn't working because it was being obscured by elements over top of it.
https://github.com/mozilla/bedrock/issues/6525
Can you close the banner? Does it conflict with the z-index of anything else on the page?
> Raise z-index of close button

- bedrock/firefox/templates/firefox/fights-for-you.html
There is a JS on click event for the survey interactions and the survey link is marked up to cause an event. We only need one event for the link click so I'm removing the event on the link, leaving the event which is attached to the banner.
https://github.com/mozilla/bedrock/issues/6387
Link still works? You can test in Chrome with the Analytics Pros tool too if you want.
> Remove duplicate analytics event

- bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
- bedrock/mozorg/templates/mozorg/about/governance/policies/reporting.html
- bedrock/mozorg/urls.py
- media/css/mozorg/participation-reporting.scss
- media/static-bundles.json
Updates Participation Guidelines and adds a new reporting page. String changes are behind the l10n tag `participation_nov2018`
https://bugzilla.mozilla.org/show_bug.cgi?id=1506402
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/about/governance/policies/participation/
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/about/governance/policies/participation/reporting/
> [fix bug 1506402] Update Participation Guidelines, add reporting

- bedrock/firefox/templates/firefox/fights-for-you.de.html
- bedrock/firefox/templates/firefox/fights-for-you.html
- media/css/firefox/fights-for-you.scss
- media/js/firefox/fights-for-you.js
- media/static-bundles.json
Add en and de videos to FFFY campaign page
Closes mozilla/bedrock#6387
I'm not very confident with this one, please give it a good look.
- Videos open and play when button is pressed
- Videos do not play if button not pressed or if closed button pressed
- Video and associated container does not display on the page until the button is pressed
- https://bedrock-demo-shobson.oregon-b.moz.works/en-US/firefox/fights-for-you/
- https://bedrock-demo-shobson.oregon-b.moz.works/de/firefox/fights-for-you/
> Add en and de videos to FFFY campaign page

- bedrock/firefox/templates/firefox/home-b.de.html
- bedrock/firefox/templates/firefox/home-b.fr.html
- bedrock/firefox/templates/firefox/home-c.de.html
- bedrock/firefox/templates/firefox/home-c.fr.html
- bedrock/firefox/templates/firefox/home.html
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- bedrock/privacy/templates/privacy/email.de.html
- bedrock/privacy/templates/privacy/email.fr.html
- bedrock/privacy/urls.py
- media/js/firefox/home/experiment-pre-download-locales.js
- media/static-bundles.json
- Enables pre-download experiment on `/firefox/` for `de` and `fr` locales at 25% of traffic.
**Do not merge** until https://www.mozilla.org/en-US/privacy/email/ is localized in French and German.
#6456
Demo URLs:
https://bedrock-demo-agibson.oregon-b.moz.works/fr/firefox/
https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/
Note: test in a non-Firefox browser on Windows with DNT disabled.
> Run firefox pre-download experiment for de and fr locales (Fixes #6456)

- bedrock/firefox/templates/firefox/new/compare/scene1-ie-2.html
- media/js/firefox/new/compare-ie-experiment.js
@stephaniehobson the experiment seems to trigger ok for me with the correct UTM values, but I did notice I had included an incorrect cohort size for the control variation. This should fix it.
I also removed the experiment bundle from the variation 2 template, since it only needs to be triggered by the default template.
> Fix IE SEM comparison page cohort sizes (#6466)

- bedrock/mozorg/urls.py
- Fixes regex bug in `/about/` page URL.
https://github.com/mozilla/bedrock/issues/6539
> Fix /about/ page URL regex (Fixes #6539)

- tests/functional/firefox/test_accounts.py
- tests/pages/firefox/accounts.py
I think I had a version of this working at some point previous to the new page merging but it's possible I never committed it, or never pushed it, or pushed it and it got overwritten in a rebase, or something who knows... the week is a bit of a blur. Anyway, I think this updates the tests for the new accounts page and it's passing locally so maybe I did something right. At the time I'm submitting this PR (late on Friday night, I might add) I've pushed it to the `run-integration-tests` branch but Jenkins is unresponsive and probably needs a kick, but I'm going to submit the PR anyway. If I'm completely off base feel free to just close it but if I'm on the right track I'm happy to tweak until we get there. And I'm babbling and should probably go to bed.
> Update tests for new accounts page

- bedrock/firefox/templates/firefox/accounts-2018.html
- media/css/firefox/accounts-2018.scss
There are app store badges in the page that are shown on iOS and Android devices in place of the CTA links that open modals. Because they shared a class with the same buttons that appear inside the modal, they were becoming visible when the modal was triggered on desktop. This just gives those mobile-only buttons a different class name so they're not caught in the same selector when the modal appears.
Side note: right now this shows both iOS and Android badges on either device. We should probably show Android badges only on Android and iOS badges only on iOS, but that was more of a refactor than I wanted to put into fixing this basic UX bug. This is good enough for now and maybe we can make additional improvements later.
#6556 
On desktop, click a CTA link for lockbox, pocket, or notes. …
> [fix #6556] Keep basic store badges hidden when modal opens

- bedrock/firefox/templates/firefox/concerts.html
- media/js/firefox/concerts.js
Moving the start time up because the opening act wants to get in on the stream. This also adds the URL to the button, though the page at the other end isn't up yet.
> [#6444] Concerts - update start time, add opening act, add stream URL

- bedrock/settings/base.py
This will allow us to add *.allizom.org to the CSP header in dev and staging deployments.
https://github.com/mozilla/bedrock/issues/6570
> Convert CSP_DEFAULT_SRC from static to everett config

- bedrock/firefox/templates/firefox/concerts.html
- bedrock/mozorg/templates/mozorg/home/home-en.html
Updates content for the period after the Phosphorescent show but before we announce the next one, using the switch `firefox-concert-one-over` (boring switch names are because so much was unknown when this was all first built, we expected to have two concerts announced at the same time, etc etc...).
#6587 
You can fake the between-show state in local dev mode by changing all the `{% if switch('firefox-concert-one-live') %}` switches to `{% if not switch('firefox-concert-one-live') %}`
> [fix #6587] Firefox Concerts between-show content updates

- media/static-bundles.json
- Removes unused JS helper from common JS bundles
https://github.com/mozilla/bedrock/issues/6504
> Remove Mozilla.ImageHelper from common JS bundle (#6504)

- bedrock/firefox/templates/firefox/accounts-2018.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64-base.html
Add query params to FxA sign in links, specifically `service=sync` so the user is actually signed in to Sync.
https://github.com/mozilla/bedrock/issues/6610
Ensure querystring for `accounts-2018.html` is accurate/good enough for now.
Ensure adding this querystring won't negatively impact any user flow (e.g. user's not using Firefox).
> [fix #6610] Add query params to FxA sign in links.

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64-base.html
> [fix #6610] Fix typo in FxA querystring.

- bedrock/firefox/redirects.py
/firefox/firefox.html redirects to /firefox/new
#6512
> Add firefox.html redirect (#6512)

- bedrock/firefox/templates/firefox/releases/release-notes.html
- media/css/firefox/releasenotes-firefox.less
This will support a change in Nucleus to add the "enterprise" tag.
See https://github.com/mozilla/nucleus/issues/63
Fix #6591
> Add enterprise category to release notes pages

- media/js/base/core-datalayer-init.js
- media/js/base/core-datalayer.js
- tests/unit/spec/base/core-datalayer.js
- Removes jQuery code from `core-datalayer.js` and `core-datalayer-init.js` files.
#6504
> Remove jQuery from core-datalayer JS files (#6504)

- bedrock/mozorg/templates/mozorg/about/governance/policies/reporting.html
Missed a string: "Investigation" on line 152.
#6609
> [fix #6609] Enclose string for l10n on CPG reporting page

- tests/functional/test_download_l10n.py
Test is failing on [master](https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1398/pipeline/) because `urls` is returning an empty array since it removes all links for `/firefox/android/beta/all/`.
https://github.com/mozilla/bedrock/pull/6597
- Bug 1513622 seems fixed, so I think we can just remove this line entirely now.
> Fix broken download test

- media/js/base/core-datalayer-init.js
- Reverts removal of jQuery ready handler from `core-data-layer-init.js`. It seems like running this code prior to DOM ready was causing some weird race condition when querying UITour 😕. 
We'll have to be a bit more careful when testing removing jQuery from this file in the future. For now, this just reverts the change.
#6624
> Revert to jQuery DOM ready handler in core-datalayer-init.js (Fixes #6624)

- bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
Pocket's bug bounty program is moving to Mozilla's program.
https://bugzilla.mozilla.org/show_bug.cgi?id=1512252
> Adding Pocket to Mozilla's Bug Bounty program

- bedrock/mozorg/templates/mozorg/contact/contact-landing.html
Adds a link to https://getpocket.com/sponsor to the contact landing page. This page doesn't seem to be localized so no l10n tag needed.
#6544
> [fix #6544] Add Pocket sponsorship link to contact landing

- bin/run-integration-tests.sh
Per our discussion last week, we're going to increase the number of pytest reruns to reduce the need to rerun the entire test suite on failure.
> Double pytest reruns

- bedrock/firefox/templates/firefox/new/scene1.html
- media/js/firefox/new/experiment-win10-taskbar-funnelcake.js
- media/static-bundles.json
Adds a funnelcake experiment to /new targeting Windows 10 and en-US, with a 50/50 split between funnelcake builds 138 (control) and 139 (the experiment).
#6586
https://bugzilla.mozilla.org/show_bug.cgi?id=1493595
> [#6586] Add win10 taskbar pinning funnelcake experiment

- bedrock/firefox/templates/firefox/home.html
- Places `fr` and `de` pre-download experiment locales behind separate switches so that we can shut each off independently.
**Note:** this PR should not be merged before https://github.com/mozmeao/www-config/pull/175 is order for the experiment to continue running without interruption.
#6634
> Separate fr and de locales in pre-download experiment (Fixes #6634)

- bedrock/mozorg/templates/mozorg/home/includes/fundraiser-eoy2018.html
- media/css/mozorg/home/fundraiser2018.scss
Updates headline and body copy for the home page fundraising banner. Only for English; other locales still get the old strings.
#6580
> [fix #6580] Updating fundraising banner copy

- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2018.html
- bedrock/mozorg/urls.py
Updated transparency report with [current information.](https://docs.google.com/document/d/1inLs0TpZHt2kfmaU3ODlhRWCybLl4_HhrARel5xv5W4/edit#heading=h.vvyxsb7n8bru)
**Switch config:** https://github.com/mozmeao/www-config/pull/176
#6479 
https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/about/policy/transparency/
> Transparency Report: jan-june 2018 update ( #6479)

- bedrock/foundation/templates/foundation/trademarks/distribution-policy.html
It looks like PR #6059 had a mistake in it. The [line with the trademark-permissions email address](https://github.com/mozilla/bedrock/blob/b13e0f962ee4e131daf94e8ce4a43ff27e538fc5/bedrock/foundation/templates/foundation/trademarks/distribution-policy.html#L98) defines the `permissions` variable which contains the email address, but then uses the `trademarks` variable instead.
> Fix broken trademark-permissions email link

- bedrock/foundation/templates/foundation/licensing.html
`trademark-permissions@mozilla.org` is the incorrect address.
`trademark-permissions@mozilla.com` is correct.
#6651
> (Fixes #6651) Bug fix, incorrect trademark-permissions email link

- bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
Remove the now-irrelevant SVN section from the [Mozilla Commit Access Policy](https://www.mozilla.org/en-US/about/governance/policies/commit/access-policy/) page. We don’t have SVN repositories any more. Some other portions may also be outdated, but these are untouched.
https://bugzilla.mozilla.org/show_bug.cgi?id=1504292
Open the page, and make sure the SVN section is gone.
> Fix Bug 1504292 - Remove SVN section from Mozilla Commit Access Policy

- bedrock/firefox/templates/firefox/fights-for-you.fr.html
- bedrock/firefox/urls.py
Adds a French translation of the Firefox Fights For You page.
#6584 
https://bedrock-demo-craigcook.oregon-b.moz.works/fr/firefox/fights-for-you/
Lucille is reviewing to make sure all the text is in the right place (since I don't read French).
> [fix #6584] Add French translation of FFFY page

- media/js/mozorg/home/home.js
The script was only attaching the click event to the latest matching button (the last one appended to the DOM) so the first button had no event. This uses a jQuery selector to attach the click to all matching buttons. 
#6592 
The sticky banners are currently hidden because of the fundraising banner. To bring them back locally you'll need to remove the `{% if not switch('fundraising-eoy2018') %}` conditions around each sticky banner in `home-en.html`
Firefox shows the accounts CTA and all other browsers show the download CTA so you'll need to test in different browsers. Both sticky banners should be dismissed when you click the X. It sets a cookie named `sticky-home-cta-dismissed` so you'll need to delete that cookie to get the banner back.
> [fix #6592] Fix home sticky banner dismiss button

- bedrock/firefox/templates/firefox/new/scene2.html
- media/js/firefox/new/experiment-win10-taskbar-funnelcake-scene2.js
- media/static-bundles.json
- Serves 64bit funnelcake build for Windows to visitors who hit the following URLs:
- `/firefox/download/thanks/?f=138`
- `/firefox/download/thanks/?f=139`
Disclaimer: code here is based on what we did for #4922
https://bugzilla.mozilla.org/show_bug.cgi?id=1493595
https://bugzilla.mozilla.org/show_bug.cgi?id=1517138
https://github.com/mozilla/bedrock/issues/6586
> Serve 64bit funnelcake to Win10 taskbar experiment visitors (Issue #6586)

- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
Removes transparency report switch.
www-config: https://github.com/mozmeao/www-config/pull/180
#6665
> Remove Dec 2018 Transparency Report switch

- bedrock/firefox/templates/firefox/accounts-2018.html
Update link utm params on fxa sign up bottom (top of page.)
OLD: https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v3&entrypoint=mozilla.org-button-light&utm_content=%2Ffirefox%2Faccounts%2F&utm_campaign=Create%20an%20Account
NEW: https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v3&entrypoint=accounts-page&utm_source=accounts-page&utm_content=accounts-page-top-cta&utm_medium=referral&utm_campaign=fxa-benefits-page
#6673
> (Fixes #6673) Update utm params on fxa sign up button

- bedrock/mozorg/templates/mozorg/home/home-en.html
Changes the blurb in the FFFY card from "You have the right to your own life — and your own data." to "You have the right to own your life — and your data."
#6686
> [fix #6686] Correct copy in FFFY home page card

- bedrock/firefox/views.py
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1508494#c22
> Add 'id' to the list of active locales for /whatsnew 64 (bug 1508494)

- bedrock/firefox/templates/firefox/content-blocking-tour/index.html
- bedrock/firefox/templates/firefox/content-blocking-tour/variation-2.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- Updates content blocking tour for Firefox 65.
- Creates a new view for `/firefox/{version}/content-blocking/start/`, which will be used for 65. FF 64 and below will continue to open `/tracking-protection/start/` so that they won't see the new string changes introduced here.
~🚨Strings are not yet final🚨~
#6639
Note: Make sure UITour is enabled to test these changes. Also Test in either Nightly or Firefox 65.
Demo URLs:
Test in a **normal window**:
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/65.0/content-blocking/start/?newtab=true
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/65.0/content-blocking/start/?newtab=true&variation=2
Test in a **Private Window**:
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/65.0/content-blocking/start/
- …
> Update content blocking tour for Firefox 65 (Fixes #6639)

- docker/bin/run_integration_tests.sh
- jenkins/branches/prod.yml
- jenkins/branches/run-integration-tests.yml
- Bumps our sanity tests to run against IE9 in SauceLabs, due to IE8 now being [unsupported](https://wiki.saucelabs.com/display/DOCS/2018/10/16/Announcing+End+of+Life+for+Internet+Explorer+8+on+Windows+7).
Fixes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/prod/367/pipeline/
Successful test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/235/pipeline/175/
> Switch sanity tests to run against IE9

- bedrock/firefox/templates/firefox/dedicated-profiles.html
- bedrock/firefox/urls.py
- media/css/firefox/whatsnew/whatsnew-nightly.scss
Adds a one-time page warning Nightly users about the impending switch to dedicate profiles for each install. It's English-only, no l10n.
Although right now it's a one-time use page aimed at Nightly, maybe we'll need to modify/repurpose it later for when this profile change lands in other channels. Just a thought.
https://bugzilla.mozilla.org/show_bug.cgi?id=1519084
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/dedicated-profiles/
> [Fix 1519084] Add Nightly update page for dedicate profiles

- media/js/base/site.js
- media/js/firefox/facebook-container-video.js
- media/js/mozorg/home/home.js
- Adds a global `is-firefox` class addition to `site.js` in the head of the base template.
#6623
> Fix home page flicker when loading in Firefox (Fixes #6623)

- bin/run-sync-all.sh
- bin/tag-release.sh
- docs/pipeline.rst
- jenkins/branches/stage.yml
This will speed up deployment times by allowing deployment and testing against dev and stage deployments in parallel, and allowing immediate deployment to prod branch if needed.
https://github.com/mozmeao/infra/issues/981
Push this to the stage branch, look for notification of job starting in #www-notifications in Mozilla slack with link to Jenkins job
> Separate stage from prod deployment

- media/css/newsletter/newsletter.less
css responsive layout bug fix.
#6672
[1513869](https://bugzilla.mozilla.org/show_bug.cgi?id=1513869)
Words remain inside borders on small screen size.
Locally, use this hash to see page -- /newsletter/existing/843c18f0-63a8-4c0a-9953-777d1c12ae80/
> (Fixes #6672) Fix responsive table bug

- bedrock/foundation/templates/foundation/licensing.html
Updates legal copy in 'Website Content' section on foundation/licensing/
#6714 
https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/foundation/licensing/
> (Fixes  #6714) Update licensing page copy

- bedrock/firefox/templates/firefox/new/base.html
- bedrock/firefox/templates/firefox/new/scene1_linux.html
- bedrock/firefox/templates/firefox/new/scene1_mac.html
- bedrock/firefox/templates/firefox/new/scene1_windows.html
Fixes #6728 
Demos: 
https://bedrock-demo-agibson.oregon-b.moz.works/firefox/new/
https://bedrock-demo-agibson.oregon-b.moz.works/firefox/windows/
https://bedrock-demo-agibson.oregon-b.moz.works/firefox/mac/
https://bedrock-demo-agibson.oregon-b.moz.works/firefox/linux/
> Fix broken string translation for /firefox/new/ page title (Fixes #6728)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- media/css/firefox/whatsnew/whatsnew-65.scss
- media/js/firefox/whatsnew/whatsnew-65.js
- media/static-bundles.json
- Adds page at `/firefox/65.0/whatsnew/`, reusing the existing /whatsnew page and strings from 63.0. Much of this code has already been reviewed / tested, with the exception of the following:
- There is a new newsletter CTA added to the page, but this reuses strings from `main.lang`, so there should be no additional l10n requirements.
- Needs to be live in production **before Jan 22nd**.
Page logic:
- If a user is not signed into an account, show the existing Firefox Account sign-up bar at the top of the page.
- If a user is already signed into an account, and they are in a locale that supports the Firefox newsletter, show a newsletter sign-up form in place of the Firefox Account form. *
- If a user is already signed into an account, and they are not in a valid newsletter locale, do …
> Add /whatsnew page for Firefox 65 (Fixes #6352)

- Dockerfile
- bin/cron.py
- bin/run-db-update.sh
- bin/sync-all.sh
* Only pull data that doesn't require auth during build as secrets aren't available.
* Also run migrations and db updates during dev image build.
> Update external data during docker build

- bedrock/privacy/templates/privacy/base-protocol.html
- bedrock/privacy/templates/privacy/notices/firefox-quantum.html
- media/css/privacy/privacy-protocol.scss
- media/js/privacy/privacy-protocol.js
- media/static-bundles.json
- Reverts removal of accordion functionality from `privacy/firefox` pages, that was removed in https://github.com/mozilla/bedrock/pull/6278.
Note: whilst restoring this code I realised it was never very accessible. The ARIA support isn't great, and the individual sections are not expandable via keyboard 😩. There seems to be some urgency in restoring this that I don't fully understand (from a legal point of view), but if we are to support this accordion as a feature long term, then we should at least file bugs and make sure our privacy content is accessible to everyone.
#6713
> Revert removal of accordion from /privacy/firefox/ pages (Fixes #6713)

- media/js/firefox/new/experiment-win10-taskbar-funnelcake.js
Downloads have been a bit slower than projected, so we're increasing the sample size in order to reach the target total so we can turn off the experiment before Firefox 65 ships (thus avoiding the need for funnelcake builds of Fx65).
https://bugzilla.mozilla.org/show_bug.cgi?id=1493595#c56
> [bug 1493595] increase sample rate for win10 taskbar experiment

- bin/deploy.sh
Check to see if the file exists before updating it. Deployment failed when deploy.sh tried to update the non-existant file.
https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/prod/374/pipeline/
> Fix deployment for clusters with no clock-deploy.yaml

- tests/unit/spec/base/mozilla-highlight-target.js
- Looks like this nested `it` statement was tripping up Karma on latest node versions.
#6681
- Running `gulp js:test` locally should still pass.
> Fix JS unit test error (Fixes #6681)

- bedrock/mozorg/redirects.py
Adds a redirect from `/decentralization` to `/internet-health/decentralization/`
#6756
> [fix #6756] Add vanity redirect for decentralization

- bedrock/base/templates/base-pebbles.html
- bedrock/base/templates/base-resp.html
- bedrock/base/templates/includes/protocol/navigation/index.html
- bedrock/firefox/templates/firefox/content-blocking-tour/index.html
- bedrock/firefox/templates/firefox/new/base.html
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/templates/firefox/tracking-protection-tour/index.html
- media/css/firefox/accounts-2018.scss
- media/css/hubs/_nav-download-button-remove.scss
- media/css/pebbles/components/_protocol-nav.scss
- media/css/protocol/components/_navigation.scss
- media/css/protocol/includes/_navigation-hide-download-button.scss
- media/css/sandstone/protocol-nav.scss
- media/js/base/global-fxa-cta-experiment.js
- media/static-bundles.json
- tests/functional/test_internet_health.py
- Adds a global Firefox Accounts signup button to the main navigation, shown only to Firefox users, replacing the existing download button.
Experiment cohorts:
- Firefox (up-to-date, release channel) users on en-US locale.
- 90% see download button (control)
- 10% see FxA button.
#6629
- Test using the **current release version** of Firefox, with **DNT disabled**.
- Depending on which variant you get, a cookie is stored. You may need to clear this cookie before refreshing to see the other variant.
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/
> Global FxA CTA experiment for Firefox users (Fixes #6629)

- bedrock/foundation/redirects.py
Don’t require a trailing slash when redirecting to foundation.m.o
Is my regex correct?
Does this break any other redirects?
> [no bug] Fix /foundation redirects

- bedrock/firefox/templates/firefox/channel/base.html
- bedrock/firefox/templates/firefox/features/index.html
- media/css/firefox/channel.less
Removes Test Pilot content from 2 pages, and some CSS that made the content work. Fixes #6776 .
#6776 
Browser tested in Firefox 65 wide/narrow screen, LTR/RTL locales.
> Remove test pilot content

- bedrock/base/templates/includes/protocol/navigation/menu/about.html
- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- bedrock/settings/base.py
Use the `press_blog_url()` template tag for localized links in the new global nav.
The tag is defined in [`mozorg/templatetags/misc.py`](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templatetags/misc.py#L333) and the list of press blogs is defined in [`settings/base.py`](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L707).
This also updates the list of local press blogs, adding `/press-br/` (which was launched some time after the initial batch of local press blogs but apparently just never got added here) and changing all Spanish locales to use the general `/press-es/` blog (we used to have a separate blog at `/press-latam/` but it was recently decommissioned and redirected).
Also updates related tests.
#6787 
We have local press blogs for de, …
> [fix #6787] Link to local press center blogs in global nav

- media/js/base/global-fxa-cta-experiment.js
- Increases experiment sample rate from 10% to 90%.
#6792
> Set FxA global CTA experiment sample rate to 90% (#6792)

- bedrock/base/templates/includes/protocol/navigation/index.html
- Changes `utm_content=Get%20a%20Firefox%20Account` to `utm_content=get-firefox-account`.
- Also changes `data-button-name="Create a Firefox Account"` to `data-button-name="Get a Firefox Account"` so that it better matches the button text.
#6809
> Fix utm_content value for global FxA CTA in navigation (Fixes #6809)

- bedrock/styleguide/templates/styleguide/index.html
The previous URL redirected anyways - this is just a simple URL change :)
> Update Mozilla link with the new Mozilla Design

- bedrock/base/templates/base-pebbles.html
- bedrock/base/templates/base-resp.html
- bedrock/base/templates/includes/protocol/navigation/index.html
- media/js/base/global-fxa-cta-experiment.js
- Enables global FxA experiment for `de` and `fr` locales.
- Updates FF version requirements from latest release to >= 57 (Quantum).
- Adds each locale via a separate switch, so that we can start/stop independently.
#6792
> Test global FxA CTA in German and French locales (Fixes #6792)

- media/js/privacy/privacy-protocol.js
- Fixes "Show all" button on `/privacy/firefox/`.
#6817
> Fix privacy page toggle (Fixes #6817)

- bedrock/firefox/templates/firefox/mobile.html
- media/css/firefox/mobile.scss
- media/js/firefox/mobile/mobile.js
Refactors firefox/mobile mobile view to see app store buttons instead of modal.
#6643
> (Fixes #6643) Replace modal with app store buttons for mobile.

- media/js/firefox/new/yandex/scene1.js
- tests/unit/spec/firefox/new/yandex/scene1.js
- Removes Yandex A/B test from `/ru/firefox/new/` and makes 100% of audience geolocated in Russia see the Yandex content.
#6752
> Remove Yandex test, make 90% cohort the 100% default (Fixes #6752)

- bedrock/mozorg/templates/mozorg/mpl/headers/index.html
The HTTP scheme was deprecated by Mozilla a while back: https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/
> Use HTTPS for links to licenses

- bedrock/mozorg/templates/mozorg/home/home-de.html
- bedrock/mozorg/templates/mozorg/home/home-en.html
- bedrock/mozorg/templates/mozorg/home/includes/macros.html
- bedrock/mozorg/tests/test_views.py
- bedrock/mozorg/views.py
- tests/functional/test_home.py
- Adds German editorial homepage at `/de/`.
- Converts English homepage components to reusable macros, shared by both templates.
- Adds German homepage to existing functional tests.
#6585
You might need to run `make fresh-data` to test this PR locally, as all the card content is stored in the admin/DB.
Successful intergration test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/249/pipeline/
> Add German editorial home page (Fixes #6585)

- media/js/firefox/concerts.js
- Adds additional params to the oAuth metric-flow on the `/firefox/concerts/` page.
https://github.com/mozilla/bedrock/issues/6839
> Send entrypoint and form_type when calling /metrics-flow (Fixes #6839)

- yarn.lock
- It looks like #6635 updated Protocol using the `npm` command, as opposed to `yarn` (which is what [bedrock uses](https://bedrock.readthedocs.io/en/latest/install.html#local-installation) to lock down dependencies). This PR makes sure the Yarn lockfile installs the correct version.
https://github.com/mozilla/bedrock/pull/6635#issuecomment-467867258
> Update yarn.lock file with correct Protocol dependency (#6635)

- docker-compose.yml
- gulpfile.js
- media/static-bundles.json
- package.json
- yarn.lock
- Upgrade Gulp to v4.0.0
- Upgrade `ansi-colors`
- Upgrade `yargs`
- Upgrade `browser-sync`
- Upgrade `concurrently`
- Remove `gulp-watch`
Notes: We have many outdated npm packages involved in our gulp script. I resisted upgrading the world in order to keep the scope of this change as small as possible.
#6683
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/
Successful integration test run: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/250/pipeline/
Checklist:
> Upgrade Gulp to v4.0.0 (Fixes #6683)

- bedrock/privacy/templates/privacy/index.html
The string as sent to l10n doesn't match the string in the template. Rather than ask localizers to reformat it's easier to just update the template to match what's already been translated.
#6863 
https://bedrock-demo-craigcook.oregon-b.moz.works/privacy/
For local testing you'll need to make sure you have the latest strings (I had to run `make build` since I hadn't updated in a while).
> [fix #6863] Match data request string format on privacy page

- bedrock/firefox/templates/firefox/developer/includes/engage.html
This PR updates the 'Get involved' URL for engaging with Firefox DevTools. The Github organisation has recently be renamed and the old link doesn't work anymore.
none
Tested locally.
> Update 'Get involved' link for devtools

- bedrock/mozorg/templates/mozorg/about-2019.html
- bedrock/mozorg/tests/test_views.py
- bedrock/mozorg/views.py
- Exposes the new `/about/` page for localization.
#6828
> Localize the new /about page (Fixes #6828)

- bedrock/firefox/templates/firefox/new/install/scene1.html
- docs/index.rst
- docs/stub-attribution.rst
- media/js/base/stub-attribution-custom.js
- media/js/firefox/new/install/variant.js
- media/static-bundles.json
- tests/unit/karma.conf.js
- tests/unit/spec/base/stub-attribution-custom.js
- Adds a script that enables passing custom data to the Stub Attribution service for first-party experiments.
- Adds documentation on how Stub Attribution works.
- Converts the "how to install" experiment code to use the new script (this experiment is finished in prod, but I figured this would be a good way to test locally that this all works).
#6871
- Open `/firefox/new/` using Chrome on Windows.
- Once redirected to a variation, inspect cookies in dev tools and copy the value for `moz-stub-attribution-code`.
- [Decode](https://www.base64decode.org/) that base64 value, and it should match the params configured in the experiment (e.g. `source=www.mozilla.org&medium=download_button&campaign=download_thanks_page&content=download_thanks_install_experiment-v-a`).
> Make 'measuring installs' a repeatable, modular piece of code (Fixes #6871)

- bedrock/base/templates/includes/protocol/navigation/index.html
- bedrock/firefox/templates/firefox/accounts-2018.html
- bedrock/firefox/templates/firefox/concerts.html
- bedrock/firefox/templates/firefox/election/index.html
- bedrock/firefox/templates/firefox/includes/download-button.html
- bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
- bedrock/firefox/templates/firefox/whatsnew/index-lite.id.html
- media/css/firefox/accounts-2018.scss
- media/css/firefox/fights-for-you.scss
- media/css/mozorg/about-en.scss
- media/css/protocol/protocol.scss
- package.json
- yarn.lock
Update Protocol to version 5.0.0
Remember to `make build` to get the right version of Protocol.
Breaking changes and the pages I tested them on:
- css: Add basic styles for hr elements (mozilla/protocol#296)
- does this break any HRs already on protocol pages?
- http://localhost:8000/en-US/firefox/windows-64-bit/
- http://localhost:8000/en-US/privacy/firefox/
- css: (breaking) Rename download button theme to product button theme (mozilla/protocol#273)
- http://localhost:8000/en-US/ (look at nav menu and download banner for nonFX users, sticky banner, and bottom of the page)
- http://localhost:8000/en-US/firefox/accounts/
- http://localhost:8000/en-US/firefox/concerts/
- http://localhost:8000/en-US/firefox/election/ (non Firefox user download button)
- …
> Update Protocol to version 5.0.0

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
Update deprecated button classname `mzp-t-download` to new `mzp-t-product`
> Update deprecated button classname (bugfix WNP66)

- bedrock/firefox/templates/firefox/campaign.html
- We didn't translate the existing meta title & description when porting over the /firefox/campaign/ page. This PR removes those custom strings so the page falls back to using the standard page title / description
#6829
> Remove untranslated meta title and description from /campaign page (#6829)

- media/js/base/core-datalayer-init.js
- media/js/base/mozilla-client.js
- Fixes a bug where calling `getFxADetails()` twice in quick succession sometimes resulted in the second call returning too early with incorrect data.
#6904
This is a tiny code change but could do with some careful testing:
> Fix race condition in Mozilla.Client.getFxaDetails() (Fixes #6904)

- media/css/protocol/components/_navigation.scss
Only hide the button in the navbar, leave others alone.
> [#6887] Global FxA, increase specificity of button hiding rule

- bedrock/firefox/templates/firefox/home/index.de.html
- bedrock/firefox/templates/firefox/home/index.fr.html
- bedrock/firefox/templates/firefox/home/index.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- media/css/firefox/home/home.scss
- media/css/firefox/home/pre-download-newsletter.scss
- media/js/firefox/home/pre-download-newsletter.js
- media/static-bundles.json
- Reinstated the pre-download newsletter modal on /firefox/
- Incorporated design/copy tweaks to signup form.
- 100% audience for English, German and French locales.
- Modal is behind the switch `firefox_pre_download_newsletter`
~**Still need to write tests, so not yet ready for review**~
It occured to me that I can't write functional tests for this just yet, becuase the feature is behind a switch 😕. I'll file a separate issue to write tests once we're confident that things are OK data-wise.
#6886
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/
> Reinstate pre-download newsletter modal on /firefox/ (Fixes #6886)

- bedrock/security/management/commands/update_security_advisories.py
- bedrock/security/tests/test_utils.py
> Bug 1533839: Exclude non-CVE advisories from Mitre feed

- media/js/base/mozilla-utils.js
- media/js/firefox/new/yandex/scene1.js
- media/js/mozorg/contact-spaces.js
- tests/unit/spec/base/mozilla-utils.js
- remove jQuery dependency
- add test for initLangSwitcher
#6504
> Remove jQuery dependency (#6504)

- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/views.py
- media/css/firefox/new/_firefox-account.scss
- media/css/firefox/new/_other-platforms.scss
- media/css/firefox/new/scene1.scss
- media/css/pebbles/components/_modal.scss
- media/js/base/mozilla-modal.js
- media/js/firefox/new/scene1.js
- media/js/firefox/new/scene1_fxa_modal.js
- media/static-bundles.json
- tests/functional/firefox/new/test_download.py
- tests/pages/firefox/new/download.py
Adds an FxA prompt on the main download page in a modal. Should only be shown to users on Firefox 57 and up (post-quantum) and only if they're not signed into FxA already.
New strings are behind the tag `fxnew_account_032019`.
Still a work in progress so I'm trying out the draft PR function for the first time... What I need to do and need help with:
For the FxA check, I don't know why `client.getFxaDetails` is returning false for `setup` when I do it in `scene1.js` but returns true in `mozilla-fxa.js`, clearly I'm missing something obvious but it's on the outer edges of my JS knowledge so I'm just spinning my wheels trying to figure it out by trial and error alone.
For the tests... I have no idea what I'm doing. I took a stab at some copypasta but then found I can't get tests to run …
> [#6707] Add Firefox Account CTA on /new

- bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-a.html
- bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-b.html
- bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-c.html
- bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-d.html
- bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-e.html
- bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-f.html
- bedrock/firefox/templates/firefox/new/privacy-dmt/scene2.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- media/css/firefox/new/scene1-privacy-dmt.scss
- media/css/firefox/new/scene1.scss
- media/js/firefox/new/experiment-privacy-dmt.js
- media/static-bundles.json
Adds six variant download pages behind the switch experiment_firefox_new_privacy_dmt as well as a custom variant of /download/thanks/.
- Replaces https://github.com/mozilla/bedrock/pull/6925 since Craig is out on PTO.
- Adds some review fixes
https://github.com/mozilla/bedrock/issues/6899
https://github.com/mozilla/bedrock/issues/6920
Demo URL: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/
Variations:
https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=priv-dmt&v=1
https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=priv-dmt&v=a
https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=priv-dmt&v=b
https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=priv-dmt&v=c …
> Dry market test for privacy feature messaging

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
Switch name in the view doesn't match the [template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/new/scene1.html#L18), this should fix things
> Fix dry-market experiment switch name

- media/static-bundles.json
- Fixes FxA signup analytics on `/firefox/66.0/whatsnew/`
https://github.com/mozilla/bedrock/issues/6945
> Fetch tokens for FxA metrics flow on /66.0/whatsnew/ (Fixes #6945)

- bedrock/firefox/templates/firefox/new/scene1.html
- docs/stub-attribution.rst
It occured to me that in the headline experiment on `/firefox/new/` we're overriding the regular stub attribution block in the `scene1.html` template, but we only really need to do this for the locales the experiment applies to.
This PR adds back the regular `stub-attribution` bundle for all other locales. It also adds an extra check for `STUB_ATTRIBUTION_RATE` (which is already 100% in production, but if we ever had to suddenly turn it off for any reason then the experiment would comply).
#6851
> Include stub-attribution bundle for non-experiment locales on /firefox/new/ (#6851)

- bedrock/firefox/templates/firefox/campaign.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/yandex/base.html
- bedrock/firefox/templates/firefox/recommended.html
Remove the word "Truly" from instances of "Truly Private Browsing with Tracking Protection" 
#6299 
New strings are behind l10n tags on:
- firefox/campaign
- firefox/new
- /ru/firefox/new/
- firefox/this-browser-comes-highly-recommended/
> Remove the word "Truly" from "Truly Private Browsing" (Fixes #6299)

- bedrock/firefox/templates/firefox/windows-64-bit.html
- media/css/firefox/windows-64-bit.scss
Add download button to hero on firefox/windows-64-bit/
#6892
Download button in hero has unique GA data.
No potential l10n issues? (Page is not currently localized, but perhaps in future.)
> Add download button to Windows 64-bit hero. (Fixes #6892)

- bedrock/firefox/templates/firefox/releases/release-notes.html
Make it  clear to the user what they are downloading when they click download on the release notes pages.
Part of the work for #6880.
Here are examples of each type of note:
- Android
- http://localhost:8000/en-US/firefox/android/60.0.2/releasenotes/
- Android Beta
- http://localhost:8000/en-US/firefox/android/66.0beta/releasenotes/
- Android Aurora
- http://localhost:8000/en-US/firefox/android/54.0a2/auroranotes/
> Add product name to download button (#6880)

- bedrock/firefox/templates/firefox/releases/aurora-notes.html
Aurora notes template handles both desktop and android browsers.
Fix #6930
Desktop Aurora: https://www.mozilla.org/en-US/firefox/32.0a2/auroranotes/
Android Aurora: https://www.mozilla.org/en-US/firefox/android/54.0a2/auroranotes/
> Desktop Aurora no longer has Android Aurora gtm_page_id

- media/css/firefox/new/scene2.scss
- Fixes newsletter layout on /thanks/ in Internet Explorer.
- Also fixes text contrast issue on field legend.
#6031
> Fix newsletter layout on /thanks/ for IE (Fixes #6031)

- bedrock/firefox/templates/firefox/accounts-2018.html
- media/css/firefox/accounts-2018.scss
- Adds a primary CTA to the `/firefox/accounts/` page for both Firefox Android and Firefox iOS users:
#6694
> Add primary CTA for iOS and Android visitors to /accounts page (Fixes #6694)

- media/css/firefox/releasenotes-firefox.less
- media/js/firefox/releasenotes.js
- media/static-bundles.json
Removing sticky menu in preparation for port to Protocol.
As part of #6880 
- Did I remove all files and functions?
- Any JS errors?
http://localhost:8000/en-US/firefox/60.0.2/releasenotes/
> Release notes nav no longer sticky (#6880)

- bedrock/firefox/templates/firefox/releases/aurora-notes.html
- bedrock/firefox/templates/firefox/releases/beta-notes.html
- bedrock/firefox/templates/firefox/releases/dev-browser-notes.html
- bedrock/firefox/templates/firefox/releases/esr-notes.html
- bedrock/firefox/templates/firefox/releases/nightly-notes.html
- bedrock/firefox/templates/firefox/releases/notes.html
- bedrock/firefox/templates/firefox/releases/release-notes.html
- bedrock/releasenotes/models.py
- Move product logic into channel templates
- Set defaults in notes.html based on product details
- Tried to avoid hard coding values we can get from product details
- Affected attributes:
- gtm-page-id
- Channel name
- Product name
- Primary Heading
- Download title (does not appear to be displayed, but will be in Protocol)
- Download button
- Download all link
- Remove `notes_heading_primary` block in favour of `primary_heading` variable
- to accommodate grouping if/else logic by product
- default value is now `_('%s <br> Release Notes')|format(product_name)`
- release and nightly have custom values for the latest version
- Set gtm_page_id using `page_id` variable
- to accommodate grouping if/else logic by product
Clean-up work in preparation for #6823
Here are examples of each type of …
> Release notes: move logic into channel templates

- bedrock/firefox/views.py
Fixes unreachable URLs when the `experiment_firefox_new_privacy_dmt` switch is enabled.
- `/en-US/firefox/new/?xv=betterbrowser`
- `/en-US/firefox/new/?xv=safari`
- `/en-US/firefox/new/?xv=edge`
#6974
> Fix SEM download page display logic (Fixes #6974)

- docs/stub-attribution.rst
- media/js/base/stub-attribution-custom.js
- tests/unit/spec/base/stub-attribution-custom.js
- Avoids overwriting stub attribution data if the referal is from AMO.
#7003
- I've verified this is working as expected locally, and also added tests for the new conditional.
> Avoid overwriting AMO referral data in custom stub attribution script (Fixes #7003)

- bedrock/firefox/redirects.py
- tests/redirects/map_globalconf.py
Redirect /firefoxfightsforyou to /firefox/fights-for-you/
#6979
> Add fffy redirect (fixes #6979)

- bedrock/mozorg/templates/mozorg/home/home-de.html
- Adds subhead to `/de/` home page for existing Firefox users.
#6980
> Add subhead to hero section on Mozilla.org for DE homepage (Fixes #6980)

- jenkins/branches/master.yml
- jenkins/branches/prod.yml
- jenkins/branches/stage.yml
- tests/functional/test_download.py
- tests/functional/test_download_l10n.py
- tests/functional/test_generated_pages.py
Add [request timeouts](http://docs.python-requests.org/en/latest/user/advanced/#timeouts).
#7015
- https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/277/pipeline
- https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/278/pipeline/
`docker run --rm -e BASE_URL=https://www.mozilla.org -e PYTEST_PROCESSES=5 -e MARK_EXPRESSION=download mozorg/bedrock_test:3bfb111f16fbb3e642416fd67ac3fb86646507ea bin/run-integration-tests.sh`
> Add timeout params to test requests for #7015

- media/js/firefox/new/scene1_fxa_modal.js
- Fixes JS error on /firefox/new/
#7026
> Fix JS error on /firefox/new/ whern using Firefox (Fixes #7026)

- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/tests/test_views.py
- De-index `/firefox/download/thanks/ page to stop it showing in search results.
#7024
> Deindex /download/thanks/ (Fixes #7024)

- Makefile
Remove files left over from previous builds in other branches
https://github.com/mozilla/bedrock/issues/7028#issuecomment-480883105
Create a new file without adding to git, run `make clean`, verify file is deleted.
> Add `git clean -f` to `make clean`

- README.md
Shifted the anchor link to the main project from `GitHub` to `this project` for more understandability and to prevent ambiguity.
Hopefully the changes are valid and good to be merged.
(my first contribution here.)
No issue filed for the same as changes are small and only to README
Same reason as above.
> Shifted anchor link to project repo in readme

- media/js/base/mozilla-utils.js
Alternative QR Code for Fx China repack was introduced in #5260, and it's currently broken.
https://bugzilla.mozilla.org/1542992
* Setup UITour permission for test [1]
* Set "distribution.id" with Services.prefs.getDefaultBranch("distribution.").setCharPref("id", "MozillaOnline"); in Firefox's browser console.
* Visit /firefox/mobile/, the QR code shown should link to https://www.firefox.com.cn/mobile/qrcode-redirect/
[1]: https://bedrock.readthedocs.io/en/latest/uitour.html#local-development
> Bug 1542992 - Get distribution link with the correct attribute name

- media/css/mozorg/home/home-2018.scss
- media/js/mozorg/home/home.js
Fixed homepage sticky banner issues (1) in referenced issue. No changes to address (2) as unsure of desired behavior.
#6989
- in mobile download sticky has same padding above and below button
- in mobile sticky doesn't ever appear over footer
- in safari mobile scrolling down from top of website doesn't reveal sticky
> Fix download sticky issues on homepage #6989

- .github/CONTRIBUTING.md
- README.md
GitHub suggests that we should be linking to the new `CODE_Of_CONDUCT.md` file from our readme and contributing markdown docs:
> Link to code of conduct from readme and contributing docs

- media/js/base/core-datalayer-init.js
- media/js/base/core-datalayer.js
- tests/unit/spec/base/core-datalayer.js
- Adds a new `win10SUser` property to the core `dataLayer` page event object in GA.
#6984
Demo: https://www-demo2.allizom.org/en-US/
> Quantify daily unique users of Win10 S mode attempting to download Firefox (Fixes #6984)

- bedrock/firefox/templates/firefox/releases/notes.html
- media/css/firefox/releasenotes.scss
Tighten up spacing on the release notes pages.
Fix #7070
Sample pages for testing
- http://localhost:8000/en-US/firefox/66.0/releasenotes/
- http://localhost:8000/en-US/firefox/65.0/releasenotes/
- http://localhost:8000/en-US/firefox/55.0/releasenotes/
- http://localhost:8000/en-US/firefox/35.0/releasenotes/
- http://localhost:8000/en-US/firefox/52.7.1/releasenotes/
- http://localhost:8000/en-US/firefox/67.0a1/releasenotes/
- http://localhost:8000/en-US/firefox/android/60.0.2/releasenotes/
> Tighten up spacing on release notes

- .github/ISSUE_TEMPLATE/sprint_task.md
- We're using Zenhub for estimates now, so there's no need to keep this in the existing issue template.
N/A
> Remove estimates table from sprint task template

- bedrock/firefox/templates/firefox/new/newsletter/scene1-a.html
- bedrock/firefox/templates/firefox/new/newsletter/scene1-b.html
- bedrock/firefox/templates/firefox/new/newsletter/scene1-c.html
- bedrock/firefox/templates/firefox/new/newsletter/scene1-d.html
- bedrock/firefox/templates/firefox/new/newsletter/scene1-e.html
- bedrock/firefox/templates/firefox/new/newsletter/scene2-a.html
- bedrock/firefox/templates/firefox/new/newsletter/scene2-b.html
- bedrock/firefox/templates/firefox/new/newsletter/scene2-c.html
- bedrock/firefox/templates/firefox/new/newsletter/scene2-d.html
- bedrock/firefox/templates/firefox/new/newsletter/scene2-e.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/new/scene2.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- media/css/firefox/new/newsletter/scene1-embed.scss
- media/css/firefox/new/newsletter/scene1-pre-download.scss
- media/css/firefox/new/newsletter/scene2-centered.scss
- media/js/firefox/new/newsletter/experiment.js
- media/js/firefox/new/newsletter/scene1-embed.js
- media/js/firefox/new/newsletter/scene1-modal.js
- media/js/firefox/new/newsletter/scene2-centered.js
- media/js/firefox/new/newsletter/scene2-embed.js
- media/js/firefox/new/newsletter/variation.js
- media/static-bundles.json
- tests/functional/firefox/new/test_download.py
- Adds a multi-variant newsletter treatment test to `/firefox/new/`
#6950
Experiment criteria: 
- Non-Firefox desktop browsers
- Windows, 
- en-US locale.
- DNT disabled.
Testing:
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=a (Control).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=b (Improved post-download newsletter on /thanks).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=c (Pre-download modal on scene 1).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=d (Pre-download embedded form on /thanks).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=e (Embedded form on scene1)
> Pre-download newsletter experiments on /new (Fixes #6950)

- bedrock/base/templates/includes/protocol/navigation/index.html
- Removes `en` conditional on showing the FxA CTA in the global navigation, shown to existing Firefox users.
#7080
> Remove en conditional on FxA button in global navigation (Fixes #7080)

- bedrock/base/templatetags/helpers.py
- bedrock/base/tests/test_settings.py
- bedrock/firefox/views.py
- bedrock/settings/appstores.py
- bedrock/settings/base.py
- docs/install.rst
- tests/redirects/map_locales.py
Locales removed:
* bn-BD, bn-IN (now 'bn')
* as, en-ZA, mai, or
Also removed references to en-ZA from code.
> Bug 1542118 - Unify Bengali as 'bn', remove obsolete locales

- bedrock/firefox/templates/firefox/accounts-2018.html
We missed an instance of 'log-in' in https://github.com/mozilla/bedrock/pull/7069. L10n of the changes hasn't started yet so we can put it behind the same tag.
> [#6953] Accounts page, ‘log-in’ to ‘login’ in meta description

- bedrock/mozorg/redirects.py
Redirect /gear to https://mozillagear.corpmerchandise.com/
#6971
Visit /gear, verify redirected to https://mozillagear.corpmerchandise.com/
> Redirect /gear to fix #6971

- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- Sets both `de` and `en-US` as active locales for the new election page.
Fixes #7099
> Enable German locale for election page (Fixes #7099)

- bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- Repurposes `/firefox/66.0/whatsnew/` for dev edition at `/firefox/68.0a2/whatsnew/` and for beta at `/firefox/68.0beta/whatsnew/`.
- There are no string changes, so this is reusing `firefox/whatsnew_66.lang`.
- Updates Firefox Accounts tracking parameters, so that we can tell how many accounts this page creates in the beta/developer channels.
- Dev Edition page is behind a switch, falling back to regular dev edition page (as we may only want to show this once to devs).
#7043
> Show whatsnew pages for Beta and Dev Edition (Fixes #7044, #7043)

- bedrock/mozorg/templates/mozorg/home/home-en.html
- bedrock/mozorg/templates/mozorg/home/includes/fundraiser-apr2019.html
- media/css/mozorg/home/fundraiser-apr2019.scss
- media/js/mozorg/home/fundraiser-apr2019.js
- media/static-bundles.json
Adds a fundraising banner to coincide with publication of the new Internet Health Report. Uses the switch name `home-fundraising-apr2019` and it's English only. I'll file a www-config PR to flip the switch once this makes it to prod. The original request was for the 26th but the report is already out so we could probably do it sooner.
#7047 
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/
> [#7047] Add April 2019 fundraising banner

- bedrock/firefox/templates/firefox/new/scene1_linux.html
- bedrock/firefox/templates/firefox/new/scene1_mac.html
- bedrock/firefox/templates/firefox/new/scene1_windows.html
- Exposes the strings in `/firefox/windows/`, `/firefox/mac/` and `/firefox/linux/` for localization (behind an l10n tag).
- includes `firefox/new/quantum.lang` in each template so these pages share the same strings as `/firefox/new/`.
#7056, 
#7057, 
#7058
> Localize Firefox platform-specific download pages (#7056, #7057, #7058)

- media/css/l10n/vi/intl.css
Zilla Slab doesn’t support the full Vietnamese character set resulting in an ugly mix of characters. This adds an intl.css file that reassigns Open Sans in place of Zilla Slab when the language is Vietnamese.
#6844 
https://bedrock-demo-craigcook.oregon-b.moz.works/vi/
Browse the site in Vietnamese, ensure that instances of Zilla Slab are displaying in Open Sans instead.
> [fix #6844] Don’t use Zilla Slab in Vietnamese

- bedrock/firefox/templates/firefox/enterprise/sla.html
- bedrock/firefox/urls.py
- media/css/firefox/enterprise-sla.scss
- media/css/firefox/fights-for-you.scss
- media/css/protocol/base/fonts/sharpsans.scss
- media/js/firefox/enterprise-sla.js
- media/static-bundles.json
Adds a page for the Firefox Enterprise service level agreement at /firefox/enterprise/sla/
#6779 
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/enterprise/sla/
> [fix #6779] Add Firefox Enterprise SLA

- bedrock/firefox/views.py
I noticed on the two following URLs, the newsletter form wasn't being displayed if already signed-in to a Firefox account.
- http://127.0.0.1:8000/en-US/firefox/68.0beta/whatsnew/
- http://127.0.0.1:8000/en-US/firefox/68.0a2/whatsnew/
#7043
> Show newsletter on FF 68 /whats page for beta and dev edition (#7043)

- bedrock/base/templates/includes/protocol/navigation/index.html
- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/accounts-2018.html
- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
Standardizing FxA parameters so they are uniform across the site.
#7061
- Format for `entrypoint`: `domain-point_of_CTA`
> Standardizing fxa utm parameters and values (#7061)

- bedrock/base/templates/macros-protocol.html
- Adds `data-card-tag` attribute to Protocol card macro for GA.
#7090
> Add data-card-tag attribute to card macro (Fixes #7090)

- bedrock/firefox/tests/test_base.py
A few nose functions remain after the Django 1.11 update.
> Remove lingering nose functions from tests (post django 1.11 update)

- wsgi/app.py
We are getting the following message in NR: 
> Some modules were uninstrumented during the current time window: meinheld.server, gunicorn.app.base. Make sure newrelic.agent.initialize() is called before any of these modules are imported. Visit the documentation for more information.
This PR re-orders the imports in the wsgi app as per the message above and [the docs](https://docs.newrelic.com/docs/agents/python-agent/installation/python-agent-advanced-integration#manual-integration).
> Import newrelic.agent first in wsgi app

- wsgi/app.py
After https://github.com/mozilla/bedrock/pull/7149 was merged the deployment in https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1643/pipeline failed, with the following traceback:
```
[2019-05-02 19:31:07 +0000] [1693] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
worker.init_process()
File "/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
self.load_wsgi()
File "/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
self.wsgi = self.app.wsgi()
File "/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File …
```
> Remove unused ability to use custom newrelic.ini

- bedrock/firefox/templates/firefox/campaign/compare/scene1-edge.html
- bedrock/firefox/templates/firefox/campaign/compare/scene1-safari.html
- Updates `/en-US/firefox/campaign/?xv=safari` and `/en-US/firefox/campaign/?xv=edge`
#6536
> Update browser comparison pages for auto-play blocking in Firefox (Fixes #6536)

- bedrock/firefox/templates/firefox/election/index-fr.html
- bedrock/firefox/views.py
Add French version of EU Elections page.
This needs to be reviewed and approved but can't be merged and pushed until the card 1 content is updated.
https://github.com/mozilla/bedrock/issues/6849
- Card 1 is expected to be in English.
https://bedrock-demo-election.oregon-b.moz.works/fr/firefox/election
> Add French version of EU Elections page

- bedrock/mozorg/templates/mozorg/about/governance/roles.html
- bedrock/mozorg/templates/mozorg/about/leadership.html
Updating the Reps description as per https://discourse.mozilla.org/t/reps-description-update-feedback-required/38346.
https://github.com/mozilla/Reps/issues/379
* Go to /about/governance/roles/ and observe the new text
* Go to /about/leadership/ and observe the new description below "Mozilla Reps Council"
> Update Reps descriptions

- wsgi/app.py
The param was previously customizable by env var, but no existing config used a value other than 'newrelic.ini', and I made an incorrect assumption that it was the default when I removed the customization support in https://github.com/mozilla/bedrock/pull/7150  
Dev is currently working, need to push to stage to verify fix.
> Add 'newrelic.ini' param to newrelic.agent.initialize()

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/accounts-2018.html
- bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
- media/js/base/fxa-utm-referral.js
- media/static-bundles.json
Per conversation in #6854
https://github.com/mozilla/bedrock/issues/6854#issuecomment-482443889
This is a rough draft of validating utm_source params.
#6854
Search url for preexisting source params.
1. if utm_source is present, [validate with regex](https://mozilla.github.io/application-services/docs/accounts/metrics.html#descriptions-of-metrics-related-query-parameters)
2. if utm_source is not present, use value passed to `fxa_link_fragment` macro.
> FxA validation of utm parameters (#6854)

- bedrock/base/templates/includes/protocol/site-footer.html
Recently, at the request of the legal team, we added a sentence to the footer reading "Visit Mozilla Corporation’s not-for-profit parent, the Mozilla Foundation." and linking to foundation.mozilla.org. Since that was a new string in the global footer we wrapped it in an English conditional until other locales could get up to date.
At the time of this PR it's been translated in 61 locales but we have 99 locales active, so I'm hesitant to remove the condition entirely. But at the very least we can expand the subset for now (Janis requested this for German but I took the liberty of including several more).
> [no bug] Show footer MoFo link for more languages

- bedrock/firefox/templates/firefox/new/trailhead/download-b.html
- bedrock/firefox/templates/firefox/new/trailhead/thanks.html
- Spotted this typo when extracting strings for l10n.
- Also added another commit to include noindex tag in /thanks/`
#7177
> Fix typo in /firefox/new/ trailhead page

- bin/tag-release.sh
- Script now suggests a letter to press to back out
- Script only requires a single character of input before progressing
- Script outputs "Cancelled." if the tag is cancelled
> Indicate next steps and give feedback when cancelling

- tests/functional/test_download_l10n.py
Fixes: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1665/pipeline
@pmac I didn't test this (plucked it out of git history), but should hopefully work?
> Temporarily skip 404 download link test

- tests/functional/test_download_l10n.py
Bug 1552228 has been fixed, so we can once again test all the download
links. This effectively reverts #7199 and #7200.
> Revert devedition download test skips

- bedrock/base/templates/includes/protocol/navigation/menu/developers.html
- bedrock/mozorg/templates/mozorg/developer/includes/sub-nav.html
- bedrock/mozorg/templates/mozorg/home/home.html
Websites team was asked to remove the gaming link under 'developers' in nav.
R.I.P games.mozilla.org. :ghost:
#1793
games.mozilla.org is removed from navigation.
> Remove games.mozilla.org from nav and home. (Fixes #7193)

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
Add optional `style` utm parameter to FxA form.
The form on WNP67.0.5 needs to pass `style=trailhead`
#7238
Breaks other fxa forms?
> Add 'style' utm param to fxa form (#7238)

- jenkins/branches/frankfurt-prod.yml
Only deploy bedrock-prod
Run headless test suite
This commit triggered https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/frankfurt-prod/24/pipeline
> Reconfigure frankfurt-prod branch

- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
Fixes https://github.com/mozilla/bedrock/issues/7246
> Localized /firefox/67.0.1/whatsnew/ URLs redirect to /en-US/ (Fixes #7246)

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/developer/whatsnew-fx68-trailhead.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68-trailhead.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- Shows the trailhead WNP for Beta and Dev Edition:
- `/firefox/68.0beta/whatsnew/`
- `/firefox/68.0a2/whatsnew/`
- Updates UTM params to attribute referals from each URL.
#7248
#7249
> Show trailhead /whatsnew page for Beta and Dev Edition (Fixes #7248, #7249)

- tests/functional/firefox/test_accounts.py
Test fails because the page is behind a switch, so we'll just skip it for now. We can unskip once the switch is cleaned up post-launch.
> Skip accounts page test

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/accounts-2018.html
- bedrock/firefox/templates/firefox/accounts-2019.html
In a recent change the default "signin" action was overwritten, effectively making "email" the new default and "signin" no longer an option. This adds back signin as an explicit option.
https://bugzilla.mozilla.org/show_bug.cgi?id=1555626
> [fix bug 1555626] Add signin action to fxa_link_fragment macro

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
- media/css/firefox/whatsnew/whatsnew-67.0.5.scss
- media/js/firefox/whatsnew/up-to-date.js
- media/static-bundles.json
- Tweak design slightly (omitting new fonts and button blue color because that will arrive in a protocol update)
- Add JS to display "Congrats! You’re using the latest version of Firefox." banner.
#7256
#7244 
https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/firefox/67.0.1/whatsnew/
> Trailhead WNP: add up to date banner JS, design tweaks. (Fixes #7256, #7244)

- bedrock/firefox/firefox_details.py
- bedrock/firefox/tests/test_firefox_details.py
Also move `firefox-esr-next` to use bouncer aliases setup for that product. Re [bug 1408868](https://bugzilla.mozilla.org/show_bug.cgi?id=1408868).
Followup work to actually add the buttons to pages is still needed.  To use this you simply use `win-msi` or `win64-msi` as the `platform` argument to the download helpers.
Re [bug 1493205](https://bugzilla.mozilla.org/show_bug.cgi?id=1493205)
Re #7265
> Add support for win-msi and win64-msi in download URL helpers

- media/js/base/mozilla-fxa-form.js
- Fetch `flow_id` and `flow_begin_time` for non-Firefox browsers when signing up from /accounts.
#7269
> Fetch FxA metrics for non-FF browsers on /accounts (Fixes #7269)

- bedrock/base/templates/includes/protocol/navigation/index.html
- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/accounts-2018.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
In #7061 it was decided that when we send someone to FxA we would like to record it in GA with an Event Action that includes FxA. `FxA-ServiceName` was decided on with `FxA-Sync` being the only service currently passed to FxA from moz.org.
With the work on #7197 I realized the button in the fxa_email_form was not updated at that time.
In testing that I realized that the other links we updated in #7113 were sending two events for each click.
This PR:
- Updates fxa_email_form to trigger event action FxA-Sync click (via the data-link-type attribute)
- Changes data-button-name to data-link-name when link-name is FxA to improve data quality
Fix #7252
> Buttons and links to FxA trigger FxA-Sync event action only (#7252)

- bedrock/firefox/templates/firefox/accounts-2019.html
We have a German blog post to link to from /de/firefox/accounts/
#7275
> Link to German blog post from /de/firefox/accounts/ page (Fixes #7275)

- bedrock/base/templates/macros.html
- bedrock/firefox/firefox_details.py
- bedrock/firefox/templates/firefox/accounts-2018.html
- bedrock/firefox/templates/firefox/facebookcontainer/index.html
- bedrock/firefox/templates/firefox/fights-for-you.de.html
- bedrock/firefox/templates/firefox/fights-for-you.fr.html
- bedrock/firefox/templates/firefox/mobile.html
- bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
- bedrock/firefox/tests/test_helpers.py
- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- bedrock/settings/appstores.py
- bedrock/settings/base.py
- Creates standardized adjust links for mobile products that all redirect to the correct app stores if clicked on desktop.
#7214
Demo page: https://www-demo1.allizom.org/en-US/adjust-test/
> Use standardized adjust links across the site (Fixes #7214)

- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
This PR makes the entrypoints on this page match, using the one that was already standard.
Local testing, the link still worked.
> Firstrun fxa_link_fragment conforms to new standards

- bedrock/mozorg/templates/mozorg/about/leadership.html
Update's Amy Keating's title from General Counsel to Chief Legal Officer
https://bugzilla.mozilla.org/show_bug.cgi?id=1557173
> [fix bug 1557173] Leadership page: update Amy Keating’s title

- bedrock/mozorg/templates/mozorg/home/home-en.html
- bedrock/mozorg/templates/mozorg/home/includes/fundraiser.html
- media/css/mozorg/home/fundraiser.scss
- media/js/mozorg/home/fundraiser.js
- media/static-bundles.json
Resurrecting the banner again, aiming to go live on 13 June and run for at least a week. Uses the switch `home-fundraising-jun2019`
#7296
> [fix #7296] Add home page fundraising banner for June 2019

- media/css/firefox/features/safebrowser.scss
The safebrowser page referenced an image that was deleted in 1785c2b2492454e6c9411a17f9fc18e65ef75359
> Fix safebrowser.scss for Protocol 7

- bedrock/firefox/views.py
- tests/functional/firefox/test_accounts.py
Cleans up the `firefox_accounts_trailhead` switch and unskips the test. We can remove the switch from www-config once this is in production.
> [#7132] Trailhead accounts page: clean up switch

- bedrock/base/templates/includes/protocol/navigation/menu/firefox.html
Replace "Firefox Quantum Desktop Browser" with "Firefox Desktop Browser" in global nav.
#7303
> Replace Firefox Quantum w. Firefox Desktop Browser in global nav (#7303)

- bedrock/base/templates/macros-protocol.html
- bedrock/mozorg/templates/mozorg/home/home-de.html
- tests/functional/test_home.py
- update card layout to 12 card layout
- change video CTA to "Learn more" which is in the main.lang file 
See #7308, Fix #7319 
Needs to be tested with the content cards on dev. Localhost and demos will both use those.
See it here: https://bedrock-demo-shobson.oregon-b.moz.works/de/
> Change card layout on DE homepage (#7308)

- bedrock/firefox/templates/firefox/accounts-2019.html
- media/css/firefox/accounts-2019.scss
- media/js/base/mozilla-monitor-button.js
- media/static-bundles.json
- Adds signed-in state for Firefox users on `/firefox/accounts`.
- New string added behind the tag `accounts-signed-in-06132019`.
**Do not merge** until we have copy approval.
#6907
Demo: https://www-demo5.allizom.org/en-US/firefox/accounts/
> Add signed-in state on /firefox/accounts/ (Fixes #6907)

- tests/functional/test_home.py
Update homepage locale test_download_button_is_displayed_locales from `es` to `es-ES` to avoid redirect.
#7311
> Update homepage locale test_download_button_is_displayed_locales

- bedrock/firefox/templates/firefox/releases/system_requirements.html
- media/css/firefox/system-requirements.scss
- media/static-bundles.json
Convert System Requirements to Protocol 
Fix #7335
I did not try to put version specific icons on all these pages like I did the Release Notes. The icons are Release, Beta, Aurora, and Nightly.
The newsletter sign up has been removed from these pages. We can add it back once we have a Protocol port of it (in #7141).
- http://localhost:8000/en-US/firefox/54.0a2/system-requirements/
- http://localhost:8000/en-US/firefox/67.0beta/system-requirements/
- http://localhost:8000/en-US/firefox/57.0/system-requirements/
- http://localhost:8000/en-US/firefox/android/66.0.5/system-requirements/
There is no design spec to match. I borrowed heavily from the Privacy Notice page.
> Convert System Requirements to Protocol (#7335)

- bedrock/firefox/templates/firefox/accounts-2019.html
Removing an extra bracket showing up for locales that are not using the latest copy
> Remove trailing bracket

- media/js/base/mozilla-fxa.js
- tests/functional/firefox/test_accounts.py
- tests/pages/firefox/accounts.py
- tests/pages/regions/join_firefox_form.py
- Updates existing test to cover functionality of the "Join Firefox" form.
- Adds a new test for signed-in state.
- Adds a `signed-in=true` query param override to `mozilla-fxa.js` for easier state testing.
#7327
Successful integration test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/325/pipeline
> Improve functional tests for /firefox/accounts/ page

- bedrock/firefox/redirects.py
- bedrock/firefox/urls.py
- tests/redirects/map_globalconf.py
redirect for /accounts to /firefox/accounts
#7287
> Create redirect for /accounts to /firefox/accounts (Fixes #7287)

- bedrock/firefox/templates/firefox/all-unified.html
Fixes a small error brought up during string extraction: https://github.com/mozilla-l10n/www.mozilla.org/pull/310#discussion_r299559069
> Fix smart quote in /firefox/all/ page copy

- docs/install.rst
Following on from the Django 2 upgrade, here are updated installation docs around virtualenv and the Python version that needs to be used.
> Update install docs for a Python 3 environment

- requirements/base.txt
Just bumping to the latest point release of Django 2.2
([hashin](https://pypi.org/project/hashin/) makes this so easy to update :sunglasses:)
> Update Django 2.2.1 -> 2.2.3

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- Repurposes the /whatsnew pages from 67 for Firefox 68 at `/firefox/68.0/whatsnew/`.
- No changes other than passing new UTM and referral params.
#7367
> Enable /whatsnew page for Firefox 68 (Fixes #7367)

- bedrock/firefox/templates/firefox/enterprise/index.html
- bedrock/firefox/templates/firefox/enterprise/signup-thanks.html
- bedrock/firefox/templates/firefox/enterprise/signup.html
- media/css/firefox/enterprise.scss
- Add protocol-basic template and style sheet
- use it for the form pages
- tweak form page styles as necessary
Depends on #7353.
Fix #7352
Please do not look at the /enterprise landing page as part of this. I had to copy the style sheet from #7353 to avoid SCSS errors. Before publishing this PR will have to be re-based on #7353 and incorporate any review feedback from there.
> Convert Enterprise form pages to Protocol (#7352)

- bedrock/mozorg/templates/mozorg/contribute/events.html
Search Console and the [structured data testing tool](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Fcontribute%2Fevents%2F) throws errors, as "location" is from type "thing". I fixed that, so we can be aware of errors occuring around our brands and products. The location should be now type = Place and the venue is set as Adress. The warnings will remain.
> Fixing microdata error on events

- bedrock/base/templates/product-all-unified-macros.html
- Fixes incorrect version number for esr_next.
#7406
> Fix version number for multiple ESR on /firefox/all (Fixes #7406)

- bedrock/firefox/templates/firefox/enterprise/index.html
I spotted a typo in the page title and wanted to quickly fix it. 😁
> Fix "browser" typo on Enterprise page title

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/mobile.html
- bedrock/mozorg/templates/mozorg/about-2019.html
- bedrock/mozorg/templates/mozorg/home/includes/macros.html
- removed two cases of "data-link-type=button" where "data-link-type" is captured.
- Double checked for other instances where this occurs.
- Ran tests locally - all pass
#7392
We might want to make sure we are getting events as expected?
> Removed Attributes causing duplication of events [Fixes #7392]

- bedrock/base/templates/product-all-unified-macros.html
- bedrock/firefox/templates/firefox/all-unified.html
- media/css/firefox/all/all-unified.scss
- media/js/firefox/all/all-downloads-unified.js
- tests/unit/spec/firefox/all/all-downloads-unified.js
- Enables MSI installers for Firefox ESR 68.0esr on `/firefox/all/`
#7410
Successful integration test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/347/pipeline
> Selecting ESR on /all should let me download an MSI installer (Fixes #7410)

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/accounts-2019.html
- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/developer/whatsnew-fx68-trailhead.html
- bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68-trailhead.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html
There were some inconsistencies on different /whatsnew templates on format of utm params in the `fxa_email_form` macros, this PR should standardize them.
#7387
- Consistent UTM values across FxA referrals on /whatsnew pages.
- Any templates missed?
> Standardize fxa_email_form UTM values. (Fixes #7387)

- .circleci/config.yml
- .eslintrc.js
- media/js/base/stub-attribution-macos.js
- media/js/firefox/tracking-protection-tour.js
- package.json
- tests/unit/karma.conf.js
- tests/unit/spec/base/mozilla-client.js
- tests/unit/spec/base/mozilla-notification-banner.js
- tests/unit/spec/base/mozilla-pager.js
- tests/unit/spec/base/mozilla-traffic-cop-funnelcake-geo.js
- tests/unit/spec/base/search-params.js
- tests/unit/spec/base/send-to-device.js
- tests/unit/spec/firefox/all/all-downloads-unified.js
- tests/unit/spec/firefox/new/yandex/scene1.js
- tests/unit/spec/firefox/tracking-protection-tour.js
- yarn.lock
- Updates both Jasmine, Sinon, and Karma to the latest versions.
- Run tests in both Firefox and Chrome.
- Updates `merge-stream` (dependency for bumping CircleCI image to Node.js 10.0).
- Removes unused `karma-coverage` dependency.
The biggest change here is that Jasmine tests are now seeded to run in a random order, whereas previously they always ran sequentially. To get the test suite to pass, I had to fix some tests that had dependencies on running order.
#6867
Before testing this locally run both `make build` for the docker image and also `yarn` to install dependencies locally.
Successful integration test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/327/pipeline
> Upgrade Jasmine and Karma dependencies (Fixes #6867)

- bedrock/firefox/templates/firefox/nightly_whatsnew.html
TriageBot was just decommissioned, so we shouldn't mention it or link to it any more. I couldn't find any mentions of it other than the Nightly whatsnew page.
This page is localized but since this is just a deletion it shouldn't need an l10n tag.
#7413
> [fix #7413] Remove TriageBot from Nightly WNP

- .stylelintrc
- gulpfile.js
- media/css/sandstone/buttons.less
- media/css/sandstone/lib.less
- media/css/sandstone/mixins/at2x.less
- package.json
- yarn.lock
- Updates `stylelint` and `gulp-stylelint` to the latest version.
- Updates `merge-stream` (dependency for bumping CircleCI image to Node.js 10.0).
#6869
> Update stylelint (Fixes #6869)

- bin/img.sh
- docs/coding.rst
- package.json
- yarn.lock
This bash script works on images in git's staging area. It will:
- optimize PNG, JPG, and SVG files
- check the SVGs have a viewbox (needed for IE support)
- check that any high res images have low res equivalents (this should turn up naming miss matches between high and low res files).
See #6480
Add some images to the git staging area.
Run the script like `./bin/img.sh`
- see if it prompts you for a TinyPNG API key
- see if it saves properly
- create test .png and .svg and .jpg files and see if it compresses them
- create a file with the -high-res sufix and see if it complains there's no low res version
- create a low res version and see if it stops complaining
- does it work as expected? How is the UX? Do you understand the report it generates?
- are my assumptions good?
> Add script to optimize images #6480

- bin/tag-release.sh
- Checks `master` and `stage` to make sure a tagged release matches what is on staging
- Fixes the double question that was hurting my head
No bug this has just been, er, bugging me.
> Compare master and stage hash during deployment

- bedrock/firefox/templates/firefox/new/trailhead/download.html
- media/css/firefox/new/trailhead/download.scss
- media/js/firefox/new/trailhead/join-modal.js
- media/static-bundles.json
- tests/functional/firefox/new/test_download.py
- tests/pages/firefox/new/download.py
- Adds a join Firefox modal to /firefox/new/.
- Modal is shown when clicking "Download Now"
- Modal is shown only to Firefox users who aren't already signed-in to an account.
#7232
Demo URL: https://www-demo5.allizom.org/en-US/firefox/new/
Successful integration test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/344/pipeline
> Add Join Firefox modal to /firefox/new/ (Fixes #7232)

- media/css/mozorg/contribute/contribute-base.less
- Added `font-style: normal;` in .events-table. 
[Issue #7398](https://github.com/mozilla/bedrock/issues/7398)
Manual
> Updating contribute-base.less to fix italic addresses on /contribute/events/.

- bedrock/firefox/templates/firefox/enterprise/signup.html
This replaces some of the HTML form fields on the [Enterprise "signup" page](https://www.mozilla.org/en-US/firefox/enterprise/signup/). Content was provided by marketing/IT.
Fixes https://github.com/mozilla/bedrock/issues/7469
- open the Enterprise page
- click the call to action button "Find Out More"
- fill out the form and submit it
- confirm we received an entry on the Salesforce side
> Revise form fields based on latest marketing and Salesforce output

- bedrock/firefox/templates/firefox/developer/includes/engage.html
- bedrock/mozorg/templates/mozorg/about/forums/forums.html
There were a couple links to discourse.mozilla-community.org. This is just updating them to point directly to discourse.mozilla.org.
> update Discourse links on a couple pages

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
Fixes the header logo width so it's no longer squished. The same template is shown to release, beta, and dev edition.
#7484
> [fix #7484] Fix whatsnew logo width

- bedrock/firefox/templates/firefox/accounts-2019.html
In https://github.com/mozilla/bedrock/blob/d83bd3934b6014886e986a7073303b0e75b83292/bedrock/firefox/templates/firefox/accounts-2019.html#L61-L80 there are 3 different entrypoints for the same page. We need these to be uniform.
The template includes 6 referral links that include utm and entrypoint parameters; all 6 should have the same values in those params.
This PR sets those params in variables and interpolates the variables in the referral links, to help keep these parameters uniform.
> Standardize params on /firefox/accounts/

- bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
- bedrock/mozorg/templates/mozorg/contribute/index.html
- media/css/mozorg/contribute/contribute-base.less
- media/js/mozorg/contribute/contribute-survey.js
- media/static-bundles.json
- tests/functional/contribute/test_contribute.py
Shows up a `surveygizmo` survey in /contribute page. The survey is going to be different per locale. Currently only focusing in `en-US`. This is going to be extended for the rest of top 5 locales of this page.
#7314 
I've already tested locally that different (dummy) surveys shows up per different locale. For now `en-US` shows up as expected.
> Show survey (per locale) in /contribute page

- media/js/base/mozilla-fxa-form.js
- Fixes JavaScript error preventing the /accounts form working for Firefox on iOS.
- [Debugging notes here](https://github.com/mozilla/bedrock/issues/7483#issuecomment-516027881).
#7483
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/firefox/accounts/
> Fix firefox/accounts form for Firefox on iOS (Fixes #7483)

- bedrock/privacy/views.py
`bedrock/privacy/templates/privacy/notices/firefox.html` was deleted in https://github.com/mozilla/bedrock/commit/248e345e72861e0ed937235dfd5d418d98bcda3d and we didn't realize it was still in use by some locales (for whatever reason, looks like some markdown style thing). This updates the view so all should use the `firefox-quantum.html` template.
My bad for not catching this in review 😞 
Verify Firefox privacy notices load without error. Some effected locales to test are ro, hu, and el
> Fix privacy notice template name

- bedrock/legal/templates/legal/firefox.html
This stray legal page was extending the privacy page template that got removed in #7462.
URL: http://127.0.0.1:8000/en-US/about/legal/firefox/
#7513
> Port Firefox legal page to Protocol (Fixes #7513)

- media/css/hubs/_sub-nav.scss
- media/css/pebbles/components/_protocol-nav.scss
- media/css/pebbles/includes/_variables.scss
- media/css/sandstone/lib.less
- media/css/sandstone/protocol-nav.scss
- Updates the "Download Firefox" and "Get a Firefox Account" nav CTA's on pebbles and sandstone templates to match (more closely, not exact) to the protocol nav styles.
- Changes more neon shade of green used in pebbles and sandstone to the slightly darker shade we have used other places.
#7430
- non-firefox and firefox browsers.
- breaks old template design accidentally?
> Update sandstone & pebbles nav styles. (Fixes #7430)

- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
Another regression from https://github.com/mozilla/bedrock/commit/248e345e72861e0ed937235dfd5d418d98bcda3d
The transparency report pages are still using Pebbles and extending `mozorg/about-base.html`, which was just switched over to Protocol and the transparency pages lost some of their styling. Switching the base template back to Pebbles fixes that, and we'll work on porting them to Protocol another time.
> Fix transparency report base template

- bedrock/contentcards/models.py
- bedrock/contentcards/tests/test_models.py
- bedrock/mozorg/tests/test_commands.py
- bedrock/pocketfeed/tests/test_models.py
- bedrock/releasenotes/tests/test_base.py
- bedrock/releasenotes/tests/test_models.py
- bedrock/settings/base.py
- bedrock/utils/git.py
- bedrock/wordpress/tests/test_models.py
- bin/cron.py
- lib/l10n_utils/tests/test_dotlang.py
- lib/l10n_utils/tests/test_template.py
- requirements/base.txt
pathlib2 is a backport of the Python 3.4+ standard library pathlib. This PR just removes the now superfluous library and switches all code to use the stdlib version. It also cleans up some flake8 errors in some of the files updated.
> Remove pathlib2

- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2019.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2018.html
- bedrock/mozorg/urls.py
- media/css/mozorg/about-transparency.scss
Adds Transparency reports for H2/2018 and H1/2019 along with requested changes to the main Transparency page
about/policy/transparency/jul-dec-2018/
about/policy/transparency/jan-jun-2019/
https://github.com/mozilla/bedrock/issues/7036
https://github.com/mozilla/bedrock/issues/7356
All copy was provided, but we should keep an eye out for paste errors.
> Transparency report 2018 h2

- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
`firstrun-quantum.html` was replaced/renamed in a64a4be72b0e41748c050ff1d0afdca8b95b8aa3 but we missed this reference to the old template.
#7544 
This template should only appear for Firefox alphas prior to v 57.0
> [fix #7544] Fix legacy dev/aurora firstrun template

- media/js/mozorg/home/home.js
- media/js/mozorg/home/youtube.js
- media/static-bundles.json
- Defers loading the YouTube API on the homepage until a user interacts with a video card.
- This is the [suggested short term solution](https://github.com/mozilla/bedrock/issues/7423#issuecomment-513918095) until we refactor how we handle video.
#7423
> Defer loading YouTube API on homepage (Fixes #7423)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
- media/js/firefox/whatsnew/experiment-whatsnew-68-de.js
- media/js/firefox/whatsnew/experiment-whatsnew-68-enGB.js
- media/js/firefox/whatsnew/experiment-whatsnew-68-enUS.js
- media/js/firefox/whatsnew/experiment-whatsnew-68-fr.js
- media/static-bundles.json
Actual traffic to the experiment (see original issue #7457 ) has been lower than anticipated (possibly as a result of some other instrumentation issues recently uncovered) so we need to bump up the percentages to reach statistical significance in a timely manner.
The new traffic split for each variant, in each locale:
- en-US: 5%
- en-CA: 14%
- en-GB: 2%
- de: 10%
- fr: 14%
This also splits US and GB since they're different percentages now.
#7547
> [fix #7547] Adjust WNP68 experiment

- docs/browser-support.rst
- docs/index.rst
> Browser Support Page added

- bedrock/mozorg/management/commands/update_product_details_files.py
- bedrock/mozorg/tests/test_commands.py
- bedrock/settings/base.py
Instead of scraping product-details.mozilla.org we can directly use the source files for that from a git repo managed by release engineering.
Fix #6998
> Use releng product-details repo directly

- bedrock/base/templates/includes/protocol/navigation/index.html
- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/accounts-2019.html
- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/concerts.html
- bedrock/firefox/templates/firefox/new/scene1.html
- bedrock/newsletter/templates/newsletter/includes/form-protocol.html
- bedrock/newsletter/templates/newsletter/includes/form.html
- docs/analytics.rst
- docs/firefox-accounts.rst
- Updates datalayer attributes to new spec provided in the issue.
- Documents the new spec.
#7541
The following templates should all conform to the new spec:
> Implement Generic CTA datalayer attributes (Fixes #7541)

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/concerts.html
- docs/firefox-accounts.rst
- media/js/base/mozilla-fxa-form-init.js
- media/js/base/mozilla-fxa-form.js
- media/js/base/mozilla-monitor-button-init.js
- media/js/base/mozilla-monitor-button.js
- media/js/firefox/accounts-2019.js
- media/js/firefox/concerts.js
- media/js/firefox/whatsnew/account-conditional-ctas.js
- media/static-bundles.json
Replaces #7546
#7531
#7533
#7532
This has already been reviewed pretty well. The additional commits make a bug fix that was breaking the monitor button flow request if an optional parameter was present, and also update the docs.
> Update metrics-flow parameters and stop double-requesting flow IDs

- bedrock/settings/base.py
Brings back support for Etags and NotModified responses.  It seems support for these were lost in the Django 2 upgrade.
Fix #7617
> Add ConditionalGetMiddleware

- bedrock/privacy/templates/privacy/notices/firefox-quantum.html
- bedrock/privacy/templates/privacy/notices/websites.html
I could move this to a parent template and remove GA from all privacy notices since it's these notices where one learns about privacy options and opt-out procedures.
> Fix bug 1576673: Disable GA on Fx Privacy Notice

- bedrock/base/tests/test_views.py
- bedrock/base/views.py
- docs/coding.rst
- lib/l10n_utils/__init__.py
This is my proposal so far. I've not yet written docs yet because I'd like some feedback on this approach first. The idea is basically that in your `views.py` file you'd import this new class, create a subclass for your redirector, and then add a URL for that. It would look like this:
```python
from bedrock.base.views import GeoRedirectView
class WhatsNewRedirectorView(GeoRedirectView):
geo_urls = {
'US': 'firefox.whatsnew-us',
'IN': 'firefox.whatsnew-in',
}
default_url = 'firefox.whatsnew'
```
This would redirect people in the US to the URL named `firefox.whatsnew-us` and in India to `firefox.whatsnew-in` and everyone else to `firefox.whatsnew`. Then you just add this view to the `urls.py` at a URL and the others as well and we're good to go. You can also use full URLs and not just URL …
> Add generic Geo redirector view class

- bin/sync-all.sh
This change should still allow us to get DMS notifications
if the data fails to update during normal operation but will
avoid breaking the docker image build if some data fetch fails.
> Do not let data update failure stop the Docker build

- bedrock/privacy/templates/privacy/notices/base-notice-paragraphs.html
- bedrock/privacy/templates/privacy/notices/websites.html
- Fixes bug described in the issue.
#7645
> Fix websites privacy notice expanders and page title (Fixes #7645)

- .circleci/config.yml
- package.json
- yarn.lock
- Updates remaining front-end dependencies to latest NPM versions.
- Removes `gulp-cli` from CircleCI script, as it no longer needs to be installed separately.
#7503
Make sure to run `make build` before testing this branch locally.
Successful test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/356/pipeline
> Update front-end dependencies (Fixes #7503)

- bedrock/firefox/templates/firefox/developer/firstrun.html
- bedrock/firefox/templates/firefox/developer/index.html
- bedrock/firefox/templates/firefox/developer/whatsnew.html
- Fixes missing image reference on dev edition /firstrun page.
- Add wordmark back to /whatsnew and /developer pages.
N/A
> Fix missing Dev Edition landing page wordmarks

- bedrock/settings/base.py
Fix #6152
I looked at /firefox/mobile/ which has the btn-app-store.svg l10n image in it. I looked at the source of the page with my change and without, and with this change the image path in the HTML was for the localized image.
> Fix the l10n_img helper in DEV mode

- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
Functions like `l10n_img`, `platform_img`, `lazy_img`, and `high_res_img` all wanted the image path to be passed in without the `img/` prefix, but the normal `static` function did want that.  This change allows the developer to be consistent and use the same path for all of the image calls.
> Allow normal "img/" path prefix for helper functions

- bedrock/firefox/templates/firefox/enterprise/sla.html
Changes `https://mozilla.force.com/enterprise` to `https://enterprise-help.mozilla.com`, and also replaces the URL in copy with the same variable (which I should have done in the first place). This page isn't localized so there should be no impact on the string changes.
#7667
> [fix #7667] Update Enterprise SLA help link

- bedrock/mozorg/templates/mozorg/about/leadership.html
- As per a request from Mitchell
N/A
> Change 'Emeritus' board members to 'Former' on /leadership page

- bedrock/legal/templates/legal/terms/firefox-private-network.html
- bedrock/legal/urls.py
- bedrock/privacy/templates/privacy/base-protocol.html
- bedrock/privacy/templates/privacy/notices/firefox-private-network.html
- bedrock/privacy/urls.py
Replaces: https://github.com/mozilla/bedrock-private/pull/80
> Add Firefox Private Network privacy policy & legal terms (Fixes #7623)

- bedrock/base/templates/macros-protocol.html
Remove card description truncation.
I think the content team has been submitting sensible length strings and we have been clipping them in funny ways.
Fix #7690
No really long strings already in use?
> Remove card description truncation Fix #7690

- bedrock/firefox/templates/firefox/accounts-2019.html
String change to support family of products marketing
See #7684 (Corresponds to the change coming to the homepage banners, trying to give a coherent story to the user)
> String change to support family of products marketing (#7684)

- bedrock/foundation/templates/foundation/trademarks/distribution-policy.html
- bedrock/foundation/templates/foundation/trademarks/policy.html
Updating copy changes for our Trademark policy
#7622
The new copy can be found here:  https://docs.google.com/document/d/1p4Lr4EQMmzsRHwtt3OYyl9eObALTBjdnie5Oqku9y48/
> Trademark copy changes [fixed  #7622]

- bedrock/firefox/templates/firefox/developer/index.html
- bedrock/firefox/templates/firefox/features/adblocker.html
- bedrock/firefox/templates/firefox/firstrun/firstrun.html
- bedrock/firefox/templates/firefox/unsupported-systems.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
- bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
- bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
- bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
- bedrock/privacy/templates/privacy/base-protocol.html
- media/css/firefox/developer/includes/newsletter.scss
- media/css/firefox/enterprise/sla.scss
- media/css/firefox/features/adblocker.scss
- media/css/firefox/firstrun/firstrun.scss
- media/css/firefox/unsupported-systems.scss
- media/css/firefox/whatsnew/whatsnew-67.scss
- media/css/mozorg/lean-data.scss
- package.json
- yarn.lock
- Update Protocol version to 8.1.0
- Use Protocol's emphasis box
- Convert narrow content to use mzp-t-narrow where possible
- Remove mzp-c-newsletter class from places where its styles were overridden (mostly in places that did not have an image to the left of the form)
Fix #7734
Remember to `make build`.
- Emphasis box: 
- http://localhost:8000/en-US/firefox/64.0/firstrun/
- Narrow content:
- http://localhost:8000/en-US/about/policy/lean-data/stay-lean/
- http://localhost:8000/en-US/about/policy/lean-data/engage-users/
- http://localhost:8000/en-US/about/policy/lean-data/build-security/
- http://localhost:8000/en-US/firefox/features/adblocker/
- http://localhost:8000/en-US/firefox/unsupported-systems/
- http://localhost:8000/en-US/firefox/enterprise/sla/ (just removed a class that …
> Update to Protocol 8.1.0

- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- tests/pages/firefox/whatsnew.py
- Changes our current /whatsnew/ page URLs to use the new `GeoRedirectView` class.
Note: We're not yet doing any geo-specific pages, so for now everything will redirect to `/whatsnew/all/`. For example, `/firefox/70.0/whatsnew/` will redirect to `/firefox/70.0/whatsnew/all/` (which is the default, global view).
#7637
Successful test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/364/pipeline
> Make /whatsnew urls use the new Geo redirector view class (Fixes #7637)

- bedrock/exp/templates/exp/base/base.html
- Small followup to #7508, to make sure that jQuery is still loaded if the convert swithc is set to off.
#7508
> Make sure jQuery is included if convert switch is set to off (#7508)

- media/js/firefox/whatsnew/whatsnew-69.js
- Attempts to measure the % of people who may have a Firefox profile issue where UITour isn't working as expected.
#7671
> Detect UITour failure / non-response on what's new page (Fixes #7671)

- docs/uitour.rst
- media/js/base/uitour-lib.js
- Adds a new UITour function required for Skyline related pages.
#7753
Please make sure you have enabled UITour for local testing, using the [instructions here](https://bedrock.readthedocs.io/en/latest/uitour.html#local-development).
1. Open http://127.0.0.1:8000/en-US/privacy/firefox/
2. Open the Web Console.
3. Paste Mozilla.UITour.showProtectionReport();
Expected result:
The `about:protections` page should open in the same tab.
> Update UITour library for showProtectionReport (Fixes #7753)

- bedrock/firefox/redirects.py
This is the Firefox send tab menu:
The "learn about send tab" menu item links to a marketing page that was removed. Let's redirect users to the sumo page instead.
See bug 1577449.
> Redirect to send tab sumo article

- media/js/privacy/privacy-firefox.js
- Fixes bug described in the issue linked below.
https://github.com/mozilla/bedrock/issues/7758
Please test using Firefox, with [UITour enabled](https://bedrock.readthedocs.io/en/latest/uitour.html#local-development) for local development.
> Privacy preferences button is missing on /privacy/firefox/ (Fixes #7758)

- media/js/base/site.js
- tests/unit/spec/base/site.js
- Fixes iOS detection for iPad running iPadOS.
#7299
> Identify iPadOS as iOS and not macOS (Fixes #7299)

- bedrock/firefox/templates/firefox/welcome/page1.html
- bedrock/firefox/views.py
- docs/firefox-accounts.rst
* Modifies parameters on lifecycle page 1 to anticipate lifecycle page 2
* Modifies parameters on lifecycle page 1 to correspond to conventions
* Documents conventions
> Change lifecycle page instrumentation to a better standard format

- bedrock/firefox/urls.py
Updates the URL regex to require a trailing slash.
#7799
> [fix #7799] redirect welcome/1 to welcome/1/ (with trailing slash)

- bedrock/mozorg/templates/mozorg/about/leadership.html
Adds notes indicating members of the steering committee:
- Mitchell Baker
- Chris Beard
- Michael DeAngelo
- Amy Keating
- Roxi Wen
- Sean White
- Dave Camp
(These notes existed previously so the associating styling is still there)
I also added an explanatory comment about the ordering because there is a reason for it, it just isn't evident from looking at the page and I don't think anyone but me knows about it. :)
> [#7794] Add Steering Committee notes to leadership page

- docs/uitour.rst
Added logins to target-types docs. Fixed #7779 
https://bugzilla.mozilla.org/show_bug.cgi?id=1582768
> Added new UITour target to documentation 

- docs/l10n.rst
Fix typo in localization documentation.
https://github.com/mozilla/bedrock/issues/7787
> Fix typo in localization documentation.

- bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
- Updated links to login to sign in explicitly
- Updated links to "already have an account" to use the default flow, which checks an email address to see if an account exists
Fix #7783
Visit in Firefox logged-out of accounts:
- http://localhost:8000/en-US/firefox/66.0/whatsnew/all/
- I can't figure out the URLs for the dev and beta pages 😅 I think they should be here https://github.com/mozilla/bedrock/pull/7073 but I can't find the strings on those pages.
> Update fxa_link_fragment to use signin not login (#7783)

- bedrock/firefox/templates/firefox/releases/notes.html
- bedrock/releasenotes/views.py
Also avoid adding the "Developer" section if there are no notes, which will only possibly be the case for Fx for iOS.
Fix #7781
1. make run
2. view release notes pages for Firefox and Firefox for iOS
3. iOS notes should not have an MDN link, and others should
The link text for the MDN link is no longer wrapped for l10n, but we do not have translations for Release Notes at all so far, so I do not consider this a blocker.
> Bug 1553566: Do not add MDN release link to Fx iOS notes

- media/css/firefox/all/all.less
This PR changes win64-msi icon from 32 bit windows to 64 bit windows.
https://bugzilla.mozilla.org/show_bug.cgi?id=1566138
> Corrected icon for win64-msi

- bedrock/firefox/templates/firefox/accounts-2019.html
- media/css/firefox/accounts-2019.scss
The accounts page was changed in #7806 to use inline images from Protocol with the `high_res_img()` helper, but that helper rewrites part of the file path so it ends up being a 404, even though it works locally.
Until we can refactor the helper to handle Protocol assets, a quick fix is to use image replacement for these logos (the CSS gets the path right).
> [#7656] Use backgrounds for accounts page logos

- bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
Mozilla is recommending Thimble users move to Glitch, since they're going to 'sunset' Thimble.
I haven't used `trans` tags in Django before, so apologies in advance if I've done it wrong.
N/A
I'm afraid I haven't done any.
> Change Thimble to Glitch

- Makefile
#Description
Add a `-d` argument to the `git clean` flag executed as part of `make clean` to remove untracked directories as well as files. See https://git-scm.com/docs/git-clean#Documentation/git-clean.txt--d
#7866 
1. create a new directory & file
2. `make clean`
3. See that the untracked directory is now removed.
> Clean untracked directories as well as files in 'make clean'; fix #7866

- docs/architecture/decisions/0002-move-ci-cd-pipelines-to-gitlab.md
Our current CI/CD pipelines are implemented in Jenkins. We would like to decommission our Jenkins server by the end of this year. We have implemented CI/CD pipelines using Gitlab in other projects, including [basket](https://github.com/mozmeao/basket/blob/master/.gitlab-ci.yml), [nucleus](https://github.com/mozilla/nucleus/blob/master/.gitlab-ci.yml) and the [snippets-service](https://github.com/mozmeao/snippets-service/blob/master/.gitlab-ci.yml).
#6794
> Add ADR: Move CI/CD Pipelines to Gitlab

- app.json
- bin/sync-all.sh
- heroku.yml
With the decommissioning of Deis Workflow our method of creating a demo instance using a named branch will be going away. This is an attempt to use [Heroku Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps) to replace that. Once this merges I can enable Review Apps for our new `www-demo` Heroku Pipeline and we can try it out. It should create a new deployment for every pull-request and update the PR with a link to it.
Will fix https://github.com/mozmeao/infra/issues/1164
> Add Heroku support for Review apps

- bedrock/firefox/templates/firefox/developer/firstrun.html
- bedrock/firefox/templates/firefox/developer/includes/alt-newsletter.html
- bedrock/firefox/templates/firefox/developer/includes/for-developers.html
- bedrock/firefox/templates/firefox/developer/index.html
- bedrock/firefox/templates/firefox/developer/whatsnew.html
- media/css/firefox/developer/includes/intro.scss
- media/css/firefox/developer/includes/newsletter.scss
Replaces the "Performance" section with a "made for developers" section along with some other copy changes to remove the "quantum" name. Uses the l10n tag `made_for_devs_102019`.
We might get a new graphic at some point but this was a hasty copy update ahead of an expected press story. DevRel is hoping to get this live early on 10 October if possible, but it's not mission-critical and it was a last minute request so we'll do what we can.
https://github.com/firefox-devtools/ux/issues/93
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/developer/
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/70.0a2/whatsnew/
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/70.0a2/firstrun/
> Dev Edition: add “made for devs” section

- bedrock/firefox/templates/firefox/enterprise/index.html
Fixes a displaye issue in IE 11.
#7819
> Fix unclosed </div> on firefox/enterprise (Fixes #7819)

- bedrock/base/templates/includes/protocol/footer/firefox-new.html
Fixes Nightly footer links to point to the expected platform
#7892 
1. Load up the Firefox /new page
2. Scroll to the footer
3. Link to `Nightly` should point to desktop download and `Nightly for Android` should point to Android download page respectively
@alexgibson r?
> Fixes #7892, footer links to nightly points to incorrect platform

- .eslintrc.js
- media/js/base/site.js
The PR for removing 'no-useless-escape' errors has been merged. So I removed rule for it as mentioned in https://github.com/mozilla/bedrock/issues/7747#issuecomment-533000634
#7747
> removed rule for no-useless-escape

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
DE and FR have hard-coded templates for the whatsnew page for Firefox 70. This activates them for prod.
#7677
> [bugfix] Activate DE and FR locales for whatsnew 70

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70.html
- media/js/firefox/whatsnew/whatsnew-70.js
Updates Lockwise CTA links. (Point to firefox/lockwise as uitour fallback.)
[QA Feedback](https://docs.google.com/spreadsheets/d/1Eo4OfeydNmJaWMyTVK_0ODyI4bku1L5rrtXpK_3XC0c/edit#gid=850719639)
#7910
[1579940](https://bugzilla.mozilla.org/show_bug.cgi?id=1579940)
> [bugfix] whatsnew page for Firefox 70 papercuts. (Fixes #7910, bug 1579940)

- bedrock/firefox/templates/firefox/pocket.html
Use pocket favicon on firefox/pocket
#7915
http://localhost:8000/en-US/firefox/pocket/
> Use pocket favicon on firefox/pocket (#7915)

- bedrock/base/templates/macros.html
- media/js/base/fxa-utm-referral-init.js
- media/js/base/fxa-utm-referral.js
- media/static-bundles.json
- tests/unit/spec/base/fxa-utm-referral.js
- Rather than trying to fix #7585 all in one go, I'm splitting this up into separate PRs. This one addresses only the Firefox Monitor button macro.
#7585
> Pass through UTM parameters for Firefox Monitor referrals (#7585)

- bedrock/firefox/templates/firefox/home/index-master.html
iOS and Android store links trigger download events
Fix #7919
> iOS and Android store links trigger download events #7919

- bedrock/firefox/templates/firefox/welcome/page1.html
- media/css/firefox/welcome.scss
Adds a link to a survey behind the switch `lifecycle_page1_survey`
#7911
> [fix #7911] Add survey to lifecycle page 1

- bedrock/base/templatetags/helpers.py
I tried to do more with this but due to the way the site works in dev mode we can't really check for the existance of files since they won't exist in a lot of cases due to bundles and compiled CSS and things only being present on the assets container. Hopefully this will help catch some errors in dev that previously were hard to spot.
> Throw an error in DEBUG mode when a static file path starts with a slash

- media/js/firefox/lockwise/lockwise.js
Fixed IE11 bug described in the issue.
#7947
> Download Firefox button is not shown on Lockwise page in IE11 (Fixes #7947)

- bedrock/base/templates/includes/protocol/navigation/menu-mozilla/firefox.html
- tests/pages/base.py
Update "Firefox Desktop" menu link to link to firefox/new 
#7917
✅  Integrations rests passing here: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/403/pipeline/
> Update "Firefox Desktop" menu link to link to firefox/new #7917

- bedrock/exp/templates/exp/base/base-firefox.html
- bedrock/exp/templates/exp/firefox/accounts-2019.html
- bedrock/exp/templates/exp/firefox/new/base.html
- bedrock/exp/urls.py
- media/css/exp/firefox/accounts-2019.scss
- media/js/exp/firefox/accounts-2019.js
- media/static-bundles.json
- Adds an en-US only version of /firefox/accounts/ at /exp/firefox/accounts/
#7802
> Add /firefox/accounts/ page to CRO sandbox (Fixes #7507)

- bedrock/exp/templates/exp/firefox/accounts-2019.html
- bedrock/firefox/templates/firefox/accounts-2019.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- Updates link on /firefox/accounts/ to point to /firefox/privacy/
- Removes old blog URL logic from view.
#7967
> Update 'Personal Data Promise' link on /firefox/accounts/ page (Fixes #7967)

- bedrock/base/templates/includes/protocol/navigation/menu-firefox/browsers.html
Add Firefox for FireTV to Firefox nav. Direct copy of the text in the Mozilla nav so it should not be a problem for l10n.
n/a and I did get the okay from JRouse.
> Add Firefox for FireTV to Firefox nav

- bedrock/firefox/templates/firefox/privacy/index.html
- bedrock/firefox/templates/firefox/privacy/products.html
- The /firefox/privacy/ pages should use Metropolis for headings.
None
> Firefox privacy hub headings should use Metropolis font

- bedrock/firefox/templates/firefox/privacy/products.html
Updates the number of trackers blocked from 100,000,000 to 10,000,000,000 (two more zeroes).
The number is a variable, not part of the string, so no l10n impact.
#7975 
http://localhost:8000/en-US/firefox/privacy/products/
> [fix #7975] Update trackers blocked

- bedrock/releasenotes/views.py
- bedrock/settings/base.py
An invalid version string in release notes was causing a NoReverseMatch error to be thrown in the Nightly Notes Feed (/firefox/nightly/notes/feed/). This was also being indexed for the sitemap, so it caused the build to fail. This both skips releases with this error in the feed and removes the feed from the sitemap.
Fix #7966
> Catch URL errors in the Firefox Nightly Notes Feed

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/welcome/base.html
- bedrock/firefox/templates/firefox/welcome/page1.html
- bedrock/firefox/templates/firefox/welcome/page2.html
- docs/analytics.rst
- media/css/firefox/welcome.scss
- media/js/base/mozilla-monitor-button.js
- media/js/firefox/welcome-page1-init.js
- media/js/firefox/welcome-page2.js
- media/static-bundles.json
- tests/functional/firefox/test_welcome_page1.py
- tests/functional/firefox/test_welcome_page2.py
- tests/pages/firefox/accounts.py
- tests/pages/firefox/welcome/page1.py
- tests/pages/firefox/welcome/page2.py
Continuation of PR #7954 
⚠️ **Blocking #7834**
Modifies monitor button and pocket button FxA flow begin scripts:
- ensures only one fetch request is made no matter how many ctas.
- every button receives the same `deviceId`, `flowBeginTime`, and `flowId`
- does not require unique ID's for each button. (uses class hook `js-monitor-button`)
_note_: 
- removing `button_id` from docs because this PR makes it so button ID is no longer the way we differentiate different buttons.
#7961
- does this change break previous implementations of the monitor button macro?
- ctas reflect the same `deviceId`, `flowBeginTime`, and `flowId` values?
> Additional ctas on welcome/1 and /2 (Fixes #7961)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
- media/static-bundles.json
Fixes https://bedrock-dev.gcp.moz.works/en-US/firefox/67.0/whatsnew/all/
https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/6521901/
> Fix whatsnew 67 newsletter JS bundle (#7370)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx69.html
`button_id` was removed as an argument for the `monitor_button` macro in #7973
> Remove button_id argument from monitor button macro.

- bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
- bedrock/base/templates/includes/structured-data/software/firefox-android-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-beta-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-browser-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-developer-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-enterprise-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-fire-tv-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-ios-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-linux-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-lite-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-lockwise-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-mac-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-monitor-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-nightly-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-send-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-windows-software.json
Fixes https://github.com/mozilla/bedrock/issues/8002
changed all images includes in the json files of structured data from
`{{ settings.CANONICAL_URL + static('img/mozorg/mozilla-256.jpg') }}`
to
`{{ static('img/mozorg/mozilla-256.jpg') }}`
> Fix urls in structured data

- bedrock/exp/templates/exp/firefox/welcome/base.html
- bedrock/exp/templates/exp/firefox/welcome/page1.html
- bedrock/exp/urls.py
- bedrock/firefox/views.py
- media/css/exp/firefox/welcome.scss
- media/js/exp/firefox/welcome-page1-init.js
- media/static-bundles.json
- tests/functional/test_experiment_pages.py
- Adds an en-US only version of /firefox/welcome/1/ at /exp/firefox/welcome/1/
- Adds headless tests for /exp/ pages.
#7802
Successful test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/373/pipeline
> Add lifecycle page 1 to CRO Sandbox (Fixes #7802)

- tests/functional/firefox/test_lockwise.py
- tests/functional/test_about.py
- tests/pages/firefox/lockwise.py
Adds some base functional tests for the lockwise page so that we have some coverage.
Note: we can't test the Firefox button states here until we update to the newer version of Selenium.
#7899
Successful test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/410/pipeline
> Add functional tests for firefox/lockwise page (Fixes #7899)

- media/js/base/mozilla-monitor-button.js
- media/js/firefox/welcome-page2.js
Value of variable [`flowParams`](https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-monitor-button.js#L62) in monitor button and pocket button fxa fetch requests contained value `undefined` before appending fetch request values.
This was causing the bug of `utm_medium=referralundefined` on button hrefs.
> [bugfix] flowParams in fxa fetch request appending `undefined` to button hrefs.

- bedrock/legal/templates/legal/terms/firefox-lite-reward.html
- bedrock/legal/templates/legal/terms/firefox-lite.html
- bedrock/legal/urls.py
Updates privacy and legal terms pages for Firefox Lite.
#7978
- http://127.0.0.1:8000/en-US/privacy/firefox-lite/
- http://127.0.0.1:8000/en-US/about/legal/terms/firefox-lite/
- http://127.0.0.1:8000/en-US/about/legal/terms/firefox-lite/reward/
> Update Legal Docs for Firefox Lite (Fixes #7978)

- bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx70.html
- bedrock/exp/urls.py
- bedrock/exp/views.py
- media/css/exp/firefox/whatsnew/whatsnew-70.scss
- media/js/exp/firefox/whatsnew/whatsnew-70.js
- media/static-bundles.json
- tests/functional/test_experiment_pages.py
Adds WNP 70 to the CRO sandbox:
http://localhost:8000/en-US/exp/firefox/70.0/whatsnew/all/
#7855
> Add /whatsnew 70 page to CRO app (Fixes #7855)

- bedrock/firefox/templates/firefox/welcome/page2.html
- media/js/base/fxa-utm-referral.js
- tests/unit/spec/base/fxa-utm-referral.js
Pocket button cta no longer overwrites utm parameters.
#8008
- http://localhost:8000/firefox/welcome/2/
pocket button `href` contains values of:
```
&form_type=button
&entrypoint=mozilla.org-firefox-welcome-2
&utm_source=mozilla.org-firefox-welcome-2
&utm_campaign=welcome-2-pocket
&utm_medium=referral
```
- http://localhost:8000/firefox/welcome/2/?utm_campaign=awesomecampaign&utm_medium=referral&utm_source=coolplace&utm_term=thisisaterm
pocket button `href` contains values of:
```
&form_type=button
&entrypoint=mozilla.org-firefox-welcome-2
&utm_source=coolplace
&utm_campaign=awesomecampaign
&utm_term=thisisaterm
&utm_medium=referral
```
> Pass through UTM parameters for Pocket referrals. (Fixes  #8008)

- media/css/firefox/whatsnew/whatsnew-lite.scss
Late request from stakeholder to bring the product image further above the fold.
#7991
> Adjust Firefox Lite product image positioning (#7991)

- bedrock/mozorg/templates/mozorg/about/leadership.html
Adds links to download photos. Zip files reside on assets.mozilla.net
#7839 
> [fix #7839] Add download links to leadership page

- bedrock/base/templates/includes/protocol/footer/firefox.html
Update footer FxA sign up link destination.
See #8044
- Footer on any Firefox page in a non-Firefox browser
> Update footer FxA sign up link destination (#8044)

- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-dec-2015.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2016.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2017.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2018.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2019.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2016.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2017.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2018.html
- bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
- media/css/mozorg/about-transparency.scss
- media/js/mozorg/about-transparency.js
- media/static-bundles.json
Updated Transparency Report templates to use Protocol.
#7530 
http://localhost:8000/about/policy/transparency/
All templates under /about/policy/transparency/ are no longer using Pebbles.
> Port Transparency Report pages to Protocol (Fixes #7530)

- bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx70.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
Update headlines for locale-specific /whatsnew 70 templates.
#8038
**Stay ahead of hackers. Check for data breaches with Firefox Monitor.**
**Sei Hackern einen Schritt voraus. Checke Datenleaks mit Firefox Monitor.**
**Vérifiez si vous avez été victime d’une fuite de données avec Firefox Monitor.**
> Update whatsnew 70 headlines for FR/DE/EN (Fixes #8038)

- bedrock/firefox/templates/firefox/welcome/page1.html
- media/css/firefox/welcome.scss
Updates the title behind the tag `monitor_title_30102019`
Also adjusts the font-size since the new headline is much longer and wrapped awkwardly otherwise.
#8060
> [fix #8060] Update welcome 1 page title

- docs/coding.rst
This PR fixes what appears to be a minor syntax issue in a numbered list in the [Optimizing images](https://bedrock.readthedocs.io/en/latest/coding.html#optimizing-images) section of the bedrock docs.
The list is currently displaying with the `#` characters and no list formatting:
> Fix numbered list syntax

- docker/bin/run_integration_tests.sh
- jenkins/global.yml
- requirements/dev.txt
- Updates selenium and pytest-selenium to latest versions.
- Use 'latest' shortcut for setting browser version on Firefox / Chrome in SauceLabs runs.
#7419
Successful test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/431/pipeline
> Update Selenium to 3.141.0 (Fixes #7419)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
Fixes German and French language hero headline and body typos on whatsnew 70.
#8075
[Copy doc.](https://docs.google.com/spreadsheets/d/1jpLfL5-L3UqtBrEePRcFWJBmxcA0Ktwg9TH9kOLwByg/edit#gid=0)
**ENGLISH**
**hero headline**
**hero body**
---
**GERMAN**
https://bedrock-demo-achurchwell.oregon-b.moz.works/de/firefox/70.0/whatsnew/all/
**hero headline**
**hero body**
---
**FRENCH**
https://bedrock-demo-achurchwell.oregon-b.moz.works/fr/firefox/70.0/whatsnew/all/
**hero headline**
**hero body**
> Fix typos on German and French whatsnew 70 headlines. (Fixes #8075)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
String change due to typo.
#8075
[Copy doc](https://docs.google.com/spreadsheets/d/1jpLfL5-L3UqtBrEePRcFWJBmxcA0Ktwg9TH9kOLwByg/edit#gid=0)
"See what Firefox has blocked for you" CTA on German template is 
"Sieh, was Firefox für dich geblockt hat"
> Update DE protection report CTA on whatsnew 70 (Fixes #8075)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1594001
> Fix typo on /fr/firefox/70.0/whatsnew/ (Fix bug 1594001)

- media/css/exp/firefox/index.scss
- media/css/firefox/home/master.scss
- media/css/firefox/privacy/products.scss
Fixes a Safari layout bug effecting image replaced headlines within a grid layout.
- http://localhost:8000/en-US/firefox/
- http://localhost:8000/en-US/firefox/privacy/products/
#8084
> Fix image-replaced heading Safari bug (Fixes #8084)

- bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-0.html
- bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-2.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- media/css/firefox/whatsnew/whatsnew-70-experiment.scss
Two minor fixes:
- Remove “info” on v2
- Remove `_entrypoint_experiment = None` from v0 parent template
When loading v=0, that `_entrypoint_experiment = None` in the parent template was nullifying the value it should have gotten from the child template. So we need to make sure both the `entrypoint_experiment` and `entrypoint_variation` params are being added to the CTA button on v=0 (the control) but NOT being added on the regular, non-experiment page (with no ?v= param).
> [#8033] WNP70 experiment fixes

- bedrock/exp/templates/exp/firefox/lockwise.de.html
- bedrock/exp/templates/exp/firefox/lockwise.html
- bedrock/firefox/templates/firefox/lockwise/lockwise.html
- Removed GA events on app store badges that are double-counting as Firefox mobile downloads.
#7941
URLs:
- http://localhost:8000/en-US/firefox/lockwise/
- http://localhost:8000/en-US/exp/firefox/lockwise/
- http://localhost:8000/de/exp/firefox/lockwise/
Things to test:
> Stop double counting event on the firefox/lockwise page (Fixes #7941)

- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
Shows the default /whatsnew page for users updating from 70.0 -> 70.0.2.
#8091
> Show default /whatsnew page for 70.0 > 70.0.2 update (Fixes #8091)

- media/js/base/mozilla-monitor-button.js
The new parameters being included with the fetch were missing their `=` resulting in a malformed URL (not causing an error, just those params were being ignored by FxA). My bad.
Several variants use this script:
http://localhost:8000/en-US/firefox/70.0/whatsnew/all/?v=1
http://localhost:8000/en-US/firefox/70.0/whatsnew/all/?v=2
http://localhost:8000/en-US/firefox/70.0/whatsnew/all/?v=5
http://localhost:8000/en-US/firefox/70.0/whatsnew/all/?v=6
http://localhost:8000/en-US/firefox/70.0/whatsnew/all/?v=7
Check the network request in dev tools. 
Before (no `=` on last two params): `metrics-flow?entrypoint=mozilla.org-whatsnew70&form_type=button&utm_source=mozilla.org-whatsnew70&utm_campaign=whatsnew70&utm_content=top-cta&entrypoint_experimentwhatsnew70&entrypoint_variation7`
It should be: …
> [#8033] Fix experiment fetch params

- bedrock/exp/templates/exp/firefox/index.de.html
- bedrock/exp/templates/exp/firefox/index.html
- bedrock/firefox/templates/firefox/home/index-master.html
Removes the locale from the download link on the new `/firefox` page, so that people can get their preffered build even though the page may not be available in their language.
#7982
> Make download link on /firefox locale neutral (Fixes #7982)

- media/css/exp/firefox/accounts-2019.scss
- media/css/firefox/accounts-2019.scss
There was a duplicate logo above headline
Fixes #8118
> Removed duplicate logo on /firefox/accounts

- bedrock/firefox/templates/firefox/whatsnew/index.html
The header background was changed in #8119 but it still uses the black Mozilla logo. This switches to the white one in keeping with brand guidelines.
#8108
> [#8108] Use white logo on legacy whatsnew

- jenkins/default.groovy
- jenkins/test-only.groovy
This will make the notification script include the build number and a link to the build in the message.
Fix #8128
> Change slack notifications from `message` to `stage`

- bedrock/settings/base.py
Returns 'localhost' if a gateway is not found in /proc/net/route.
#8103
> Fix get_default_gateway_linux()

- bedrock/firefox/templates/firefox/privacy/index.html
Fixes the body class so the theme can apply the heading font.
#8135
> [fix #8135] Fx privacy hub, add space to body class

- bedrock/firefox/templates/firefox/mobile-2019.html
- media/css/firefox/mobile-protocol.scss
- Fix nav link alignment.
- Use headings for hero sections.
- Center wordmark alignment on small viewports.
#8137
> Minor UI fixes on /firefox/mobile/ (Fixes #8137)

- bedrock/settings/__init__.py
- bedrock/settings/base.py
- lib/l10n_utils/fluent.py
A long cache timeout is desireable for LANG cache during dev, but a short one is best for Fluent. This allows us to have both.
Fix #8056
> Separate LANG and FTL file caches

- bedrock/base/templates/includes/protocol/footer/firefox.html
- bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
- media/js/base/mozilla-fxa-sign-in-link.js
- media/static-bundles.json
- Moves `mozilla-fxa-sign-in-link.js` into the common JS bundles
#8044
> Fix FxA auth links for non-Firefox browsers in nav and footer (Fixes #8044)

- bedrock/exp/templates/exp/firefox/welcome/base.html
- bedrock/exp/templates/exp/firefox/welcome/page1.html
- bedrock/firefox/templates/firefox/welcome/base.html
- bedrock/firefox/templates/firefox/welcome/page1.html
- bedrock/firefox/templates/firefox/welcome/page2.html
- bedrock/firefox/templates/firefox/welcome/page3.html
- bedrock/firefox/urls.py
- media/css/exp/firefox/welcome.scss
- media/css/firefox/welcome.scss
- media/js/exp/firefox/welcome-page1-init.js
- media/js/firefox/welcome-page1-init.js
- media/js/firefox/welcome-page2-init.js
- media/static-bundles.json
- tests/functional/firefox/test_welcome_page3.py
- tests/pages/firefox/welcome/page3.py
Adds a new welcome page promoting Firefox accounts with a Sync CTA, repurposing content from variant 7 of the WNP70 experiments.
This also makes a few minor changes to the base template and updates the other welcome pages accordingly, including the CRO copy of page 1.
And it consolidates to a shared JS bundle now that we have a single FxA button.
This needs to be in production before **21 November**.
#8152 
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/welcome/3/
> [fix #8152] Add welcome page 3 for Sync

- bedrock/firefox/templates/firefox/pocket.html
- bedrock/firefox/templates/firefox/welcome/page2.html
- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- docs/firefox-accounts.rst
- media/css/firefox/pocket.scss
- media/static-bundles.json
- tests/pages/firefox/pocket.py
- Adds an FxA CTA button to the /firefox/pocket/ page.
- Adds a new dedicated Python helper for creating FxA product buttons.
- Adds unit tests for the helper.
- Updates documentation.
#8059
- http://localhost:8000/en-US/firefox/pocket/
- http://localhost:8000/en-US/firefox/welcome/2/
Things to check:
Integration test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/457/pipeline
> Put Pocket FxA button on /firefox/pocket page (Fixes #8059)

- docker/bin/set_git_env_vars.sh
Fix errors resulting in 404s on some static assets in dev now.
> Use CI_COMMIT_REF_NAME set by gitlab by default for GIT_BRANCH

- l10n/en/mozorg/mission.ftl
Order `mission.ftl`, and add some comments.
I left the IDs alone, though I'm not sure how easy they're to maintain.
I'm still not sure what to do with the second paragraph. The first paragraph is two sentences and one string, the second paragraph is two sentences and two strings. CC @gueroJeff and @peiying2  for input.
We have at least these options:
* adjust the IDs to indicate that they're one paragraph
* and/or put them on one group comment
* or join the two strings into one (needs #8087 , but then is fairly trivial to execute)
#7821
> Order mission.ftl per template, add comments (Fixes #7821)

- bedrock/firefox/templates/firefox/new/trailhead/thanks.html
- media/css/firefox/new/trailhead/thanks.scss
Adds "Download in another language" link to the bottom of `/firefox/download/thanks/` page.
#8116
> Add link to download in another language on /thanks (Fixes #8116)

- media/js/base/mozilla-fxa-form.js
- media/js/base/mozilla-fxa-product-button.js
Refactors `mozilla-fxa-form.js` to check for utm parameters on the url before applying it's own.
#8001
- http://localhost:8000/en-US/firefox/accounts/?utm_campaign=firstrun&utm_medium=referral&utm_source=activity-stream&utm_term=trailhead-join
- http://localhost:8000/en-US/firefox/accounts/
> Pass utm params from upstream referrals on fxa_email_form (Fixes #8001)

- bedrock/foundation/templates/foundation/annualreport/2018/index.html
Fixes typos in the 2018 State of Mozilla template.
#8224
> Fix typos in SOM 2018 (Fixes #8224)

- bedrock/newsletter/templates/newsletter/recovery.html
Remove the page headline after a successful submission on [newsletter/recovery/](https://www.mozilla.org/newsletter/recovery/)
#8217
> Fix success message displayed above page headline on newsletter/recovery/ (Fixes #8217)

- bedrock/base/templates/includes/protocol/footer/firefox.html
- media/css/protocol/components/_footer.scss
- move language switcher and social media links into primary section
- add Mozilla logo to secondary section
Fix #8220
✅ https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/475/pipeline/
> Firefox Footer V2 (#8220)

- bedrock/exp/templates/exp/firefox/index.de.html
- bedrock/exp/templates/exp/firefox/index.html
- bedrock/firefox/templates/firefox/home/index-master.html
- Fixes UTM param encoding for external links on the /firefox page.
#8163
Links should be appear as:
https://monitor.firefox.com/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=firefox-home
Instead of:
https://monitor.firefox.com/?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=firefox-home
> Fix double encoded UTM params on /firefox page (Fixes #8163)

- bedrock/firefox/templates/firefox/campaign/index-trailhead.html
- bedrock/firefox/templates/firefox/new/trailhead/download.html
- media/css/firefox/campaign/download.scss
- media/css/firefox/new/trailhead/download.scss
- Updates `/firefox/new/` and `/firefox/campaign/` with Skyline content, based on the outcome of https://github.com/mozilla/bedrock/issues/7857.
#7851
> Update /new content for Skyline (Fixes #7851)

- bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
http://localhost:8000/en-US/exp/firefox/71.0/whatsnew/all/
#8246
> Whatsnew experiment template should extend /exp/ base template (Fixes #8246)

- bedrock/newsletter/forms.py
- bedrock/newsletter/templates/newsletter/country.html
- bedrock/newsletter/templates/newsletter/country_success.html
- bedrock/newsletter/templates/newsletter/existing.html
Updates newsletter "Country" labels to "Country or region", to encompass places that are distinct regions but not separate countries.
Strings were already added in https://github.com/mozilla-l10n/www.mozilla.org/pull/357
#8223
> [fix #8223] Update newsletter country label

- bedrock/exp/templates/exp/firefox/new/download-nav.html
- bedrock/exp/urls.py
Adds a version of exp/firefox/new with the navigation menu on it. It displays at http://localhost:8000/en-US/exp/firefox/new/nav/
See #8037
http://localhost:8000/en-US/exp/firefox/new/nav/
> Add exp/firefox/new version with nav #8037

- media/css/firefox/mobile-protocol.scss
Replaced 
```
$fx-body: #42425A;
$fx-blue: #0A84FF;
$fx-pink: #FF2889;
$fx-purple: #20123A;
$fx-yellow: #FFE55B;
```
with [Protocol Colors](https://protocol.mozilla.org/fundamentals/color.html) in `mobile-protocol.scss`.
#8170
> Fix `mobile-protocol.scss` (Fixes #8170)

- bedrock/base/templates/base-pebbles.html
- bedrock/base/templates/base-resp.html
- bedrock/firefox/templates/firefox/base/base-pebbles.html
- bedrock/firefox/templates/firefox/base/base-protocol.html
- bedrock/firefox/templates/firefox/base/base-resp.html
- Make the twitter card size into an editable block in the template.
- Edit the Firefox base template to use wider cards (we got wide open graph images for all Firefox products with the last logo update)
n/a
- large cards are configured on firefox pages
- `summary` is still the default on Mozilla pages
> Change Firefox pages to have wide twitter image

- bedrock/newsletter/forms.py
- bedrock/newsletter/templates/newsletter/existing.html
- media/css/newsletter/newsletter.less
Changing UI for the subscriptions page to have checkboxes, also changing the color of blue used
#8186
Checkboxes should be aligned cross browsers, clicking and unclicking boxes should update subscriptions.
> Email subscription page updates [Fixes: #8186]

- bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Re bug 1600707
See #8236
Look at /about/governance/policies/security-group/certs/policy/ and see if things are formatted properly compared to the version on Github.
> Fix incorrect formatting for v2.7 of the security certs policy

- media/css/pebbles/components/_protocol-footer.scss
The social icons in the Firefox footer on Pebbles-based pages were getting absolute positioning from the older/regular footer and needed a few extra overrides. It's a bit of a hack but can eventually go away with the rest of Pebbles.
#8278 
Some Pebbles-based Firefox pages:
http://localhost:8000/firefox/73.0a1/whatsnew/all/
http://localhost:8000/firefox/features/
http://localhost:8000/firefox/features/bookmarks/
> [fix #8278] Broken social links in Fx footer on pebbles pages

- .gitlab-ci.yml
This restores the `git push run-integration-tests` workflow previously implemented with Jenkins & Deis Workflow, but now with Gitlab & a dedicated deployment in oregon-b.
See also: 
- mozmeao/www-config#255 
- mozmeao/infra#1185
The latest push to `run-integration-tests` (this branch) triggered https://gitlab.com/mozmeao/bedrock/pipelines/101844478 which in turn triggered https://gitlab.com/mozmeao/www-config/pipelines/101844766
> Build images and update oregon-b/bedrock-test deployment

- bin/update_config.sh
Integration tests are still running mozorg/bedrock_test:latest images instead of the image built for the job due to a missing `git add` statement.
@alexgibson this should fix the issue you found during the last `run-integration-tests` pipeline.
> git add .gitlab-ci.yml after updating TEST_IMAGE

- bedrock/exp/templates/exp/firefox/new/download-nav.html
Fixes https://github.com/mozilla/bedrock/issues/8037#issuecomment-564104974, hiding the download button in the nav on /new/nav/ in the /exp templates.
#8037
> Hide the download button on nav experiment

- bedrock/settings/base.py
Enable SMS for US, DE, FR
`'sms_countries': config('STD_SMS_COUNTRIES_MOBILE_WELCOME', default='US,DE,FR', parser=ListOf(str)),`
> welcome/4 SMS bugfix.

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx72.html
- bedrock/firefox/tests/test_base.py
- tests/functional/firefox/whatsnew/test_whatsnew_72.py
- tests/pages/firefox/whatsnew/whatsnew_72.py
- Fixes logo image paths for 72 WNP.
- Adds functional test for the page.
http://localhost:8000/en-US/firefox/72.0/whatsnew/all/
#8341
Test run: https://gitlab.com/mozmeao/www-config/pipelines/104577579
> Fix /whatsnew page 72 logos (Fixes #8341)

- l10n/configs/pontoon.toml
- l10n/configs/vendor.toml
- Adds a default configuration rule for Fluent /whatsnew pages, for broad staff + vendor + community locale coverage.
Note: community is already [configured here](https://github.com/mozilla/bedrock/blob/master/l10n/configs/pontoon.toml#L118-L120) with a wildcard rule.
#8326
> Define a localization config for Fluent /whatsnew page (Fixes #8326)

- Dockerfile
- bedrock/settings/base.py
- docs/fluent-conversion.rst
- lib/l10n_utils/management/commands/_fluent.py
- lib/l10n_utils/management/commands/_fluent_activation.py
- lib/l10n_utils/management/commands/_fluent_ftl.py
- lib/l10n_utils/management/commands/_fluent_recipe.py
- lib/l10n_utils/management/commands/_fluent_templater.py
- lib/l10n_utils/management/commands/fluent.py
- lib/l10n_utils/tests/test_migration.py
- requirements/dev.txt
- requirements/migration.txt
- setup.cfg
This uses `fluent.migrate` behind the scenes to convert templates to Fluent. The rough overview of the new flow would be
```bash
./manage.py fluent recipe path/to/template.html
./manage.py fluent ftl path/to/template.html
./manage.py fluent template path/to/template.html
```
with manual edits after the `recipe` step to create good IDs, and after the `ftl` step to create good comments.
#8045 is probably the core of this, but also #7877 
This requires a few branches on the l10n libraries side, but I managed to migrate the `bedrock/firefox/templates/firefox/new/scene1.html` template, with `en` and localized Fluent files.
The docs are not yet where I'd like them to be, but I wanted to put this out there already.
* Activation logic
* Cleanup
> Use recipes for Fluent migration

- bedrock/firefox/redirects.py
- tests/redirects/map_globalconf.py
Redirect /firefox/desktop to /firefox/new instead of /firefox/
#8174
> Redirect /firefox/desktop to /firefox/new

- bedrock/base/templates/base-article.html
- bedrock/legal/templates/legal/docs-base.html
- bedrock/legal/templates/legal/fraud-report.html
- bedrock/legal/templates/legal/index.html
Added Mozilla Theme to the legal docs. Now the headings are in Zilla.
#8355
> Added Mozilla Theme to the legal docs (fix #8355)

- bedrock/firefox/templates/firefox/mobile/index.html
Fixes: https://bedrock-dev.gcp.moz.works/sv-SE/firefox/mobile/
```
ValueError: Missing staticfiles manifest entry for 'img/firefox/mobile/qr-firefox-mozillaonline.png'
```
> Fix missing image reference on /firefox/mobile

- bedrock/firefox/templates/firefox/channel/base.html
- media/css/firefox/channel.scss
Updates the newsletter on the firefox/channel pages to follow style of newsletter on firefox/developer.
#8357
> Newsletter on firefox/channel/ pages should be inside emphasis box. (Fixes #8357)

- bedrock/base/templates/macros.html
- bedrock/exp/templates/exp/firefox/accounts-2019.html
- bedrock/exp/templates/exp/firefox/welcome/page1.html
- bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
- bedrock/firefox/templates/firefox/accounts-2019.html
- bedrock/firefox/templates/firefox/welcome/page1.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx72-de.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx72-en.html
- bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx72-fr.html
- bedrock/firefox/templates/firefox/whatsnew/index-account.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx69.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx71.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx72.html
- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- docs/firefox-accounts.rst
- Adds global `monitor_fxa_button` helper.
- Removes `monitor_button` macro.
- Adds tests for new helper.
- Updates templates to use helper.
URLs:
#8167
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/104635921
> Convert monitor button macro to Python helper (Fixes #8167)

- bedrock/firefox/templates/firefox/mobile/get-app.html
Fixes https://www.mozilla.org/fa/firefox/mobile/get-app/
Also adds the `firefox/mobile-2019` lang file, as the page was using `firefox/send-to` for activation status, which can't be used on its own (the strings for the page were originally taken from /mobile).
```
ValueError: Missing staticfiles manifest entry for 'img/firefox/mobile/qr-firefox-mozillaonline.png'
```
> Fix image reference on /mobile/get-app/ page

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- media/js/base/stub-attribution.js
- tests/unit/spec/base/stub-attribution.js
- Adds additional `experiment` and `variation` params to stub attribution.
#7474
> Handle additional parameters for stub attribution (Fixes #7474)

- media/css/security/components/level.scss
On my computer at least, "MFA 2020-02" is width enough that it overflows to two lines. Increasing the width by one pixel puts it back on one line.
> Increase the width of the level span by one pixel

- media/js/base/mozilla-video-poster.js
- media/js/firefox/facebook-container-video.js
- Converts `mozilla-video-poster.js` library to use native functions over jQuery.
http://127.0.0.1:8000/en-US/firefox/facebookcontainer/
#8370
> Remove jQuery code from Facebook Container page (Fixes #8370)

- bedrock/mozorg/templates/mozorg/about/governance/policies/community-hotline.html
@peiying2 spotted a missing comma in https://github.com/mozilla-l10n/www.mozilla.org/pull/362#discussion_r367712845
> [no bug] Typo fix on CPG community hotline

- bedrock/firefox/tests/test_views.py
- bedrock/settings/base.py
> Increase max length for stub attribution string (Fixes #8399)

- bedrock/firefox/templates/firefox/set-as-default/landing-page.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx73.html
Add new strings to Firefox browser default landing  page and WNP 73 (new strings behind l10n tag).
http://localhost:8000/en-US/firefox/73.0/whatsnew/all/
http://localhost:8000/en-US/firefox/set-as-default/
#8475
> Default browser string changes (Fixes #8475)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- tests/functional/firefox/whatsnew/test_whatsnew_beta_74.py
- tests/pages/firefox/whatsnew/whatsnew_beta_74.py
- Shows the template from `/firefox/70.0/whatsnew/all/` at `/firefox/74.0beta/whatsnew/all/`.
- Also updates the release notes link to point to the version URL for the specific release, as opposed to always the latest version.
http://localhost:8000/en-US/firefox/74.0beta/whatsnew/all/
http://localhost:8000/de/firefox/74.0beta/whatsnew/all/
http://localhost:8000/fr/firefox/74.0beta/whatsnew/all/
#8450
> Show WNP70 template for Firefox Beta 73 update (Fixes #8450)

- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- media/js/base/stub-attribution.js
- tests/unit/spec/base/stub-attribution.js
- Adds a new `ua` parameter to stub attribution.
#8405
Demo: https://www-demo5.allizom.org/en-US/
> Add coarse UA detection to stub attribution (Fixes #8405)

- bedrock/firefox/templates/firefox/enterprise/index.html
- tests/functional/firefox/test_enterprise.py
- tests/pages/firefox/enterprise/landing.py
This replaces/supersedes https://github.com/mozilla/bedrock/pull/8489
⏰ URGENT: these box.com links are now removed and outdated and should be removed from the website ASAP.
- This PR removes the download links/buttons for the packages that were manually created and hosted at box.com.
- It also adds direct links to the various items that Enterprise/ESR folks may want to quickly access (this keeps everything in one useful location).
- Links to deployment guide PDF at assets.mozilla.net
Resolves #8424 
Before:
After:
> Remove enterprise packages

- Dockerfile
- Makefile
The old way suddenly broke in that it no longer properly included pip. This changes to the default recommended way of creating a virtualenv in the Python 3.8 docs.
See https://docs.python.org/3/library/venv.html#creating-virtual-environments
> Fix virtualenv creation in docker

- bedrock/firefox/templates/firefox/enterprise/index.html
The Mac and Windows download links got their URLs crossed. This swaps them the right way around. Replaces #8497 where it was previously reviewed and approved, this is just putting it on a rebased branch to make sure tests pass.
#8496
> [fix #8496] Enterprise page, swap the Mac and Windows 32 links

- bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
- media/css/newsletter/newsletter-opt-out-confirmation.scss
Looks like this was a superfluous JS bundle in the page, which was removed in https://github.com/mozilla/bedrock/pull/8502
> Remove superfluous JS bundle from opt-out confirmation page (Fixes #8527)

- bedrock/settings/base.py
- bedrock/utils/git.py
- lib/l10n_utils/fluent.py
- lib/l10n_utils/management/commands/process_ftl.py
This command does multiple things:
1. Update both the mozmeao/www-l10n repo and the mozilla-l10n/www-l10n one.
2. Copy all of the .ftl files from the mozilla-l10n repo to mozmeao
3. Check if they are valid .ftl files, and if not do not copy them
4. Check all of the successfully copied ones for activation rules
5. Write any newly activated locales to the metadata files
After running `./manage.py process_ftl` your local repo in `git-repos/www-l10n` should be full of any changes which you can then commit and push to the mozmeao/www-l10n repo. This will eventually be run by autmation, but this should help for now.
Re #7705
> Add process_ftl command for updating bedrock ftl git repo

- lib/l10n_utils/management/commands/process_ftl.py
@alexgibson I noticed a problem in the reivew of the PR in that it'd be better to keep the locales sorted.
PR in question: https://github.com/mozmeao/www-l10n/pull/2/
> Sort active locales in fluent metadata automation

- bedrock/mozorg/templates/mozorg/about/manifesto.html
- media/css/mozorg/manifesto.scss
- media/img/mozorg/about/manifesto/cta-arrow.svg
- media/static-bundles.json
- Port /about/manifesto/ page to Protocol.
- Remove L10n tag `manifesto_landing`, as all enabled locales have it set to active.
#8504
> Port manifesto page to Protocol (Fixes #8504)

- media/js/base/mozilla-client.js
- media/js/firefox/whatsnew/account-conditional-ctas.js
- tests/unit/spec/base/mozilla-client.js
- Updates `Client.getFxaDetails()` with new functionality to determine sign-in state.
- Newer clients (FF >= 74) use `fxa` configuration call.
- Older clients (FF < 74) fallback to legacy `sync` configuration call.
- Adds new `Client.getFxaConnections()` function to query services recently used.
#8200
Demo: https://www-demo3.allizom.org/en-US/firefox/accounts/
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/116435502
> Update UITour to take advantage of new FxA capabilities (Fixes #8200)

- bedrock/firefox/templates/firefox/facebookcontainer/index.html
Upcoming campaigns will point people to the FB container addon. Anticipating this, I reached out to learn how attribution can work for FB container addon installs, and [the response](https://mozilla.slack.com/archives/C4C0HCX6F/p1582047889002600) (in Slack, so not open) suggested adding a handful of parameters to referrals. 
Those parameters were missing from links on the /firefox/facebookcontainer/ page. This PR attempts to add them.
> Add params to FB Container URLS per AMO guidance

- bedrock/legal/templates/legal/terms/firefox-private-network.html
- bedrock/privacy/templates/privacy/notices/firefox-private-network.html
Copy was an out-of-date version (oct 18)
#8558
> Update the TOS and PN for FPN (Fixes #8558)

- bedrock/firefox/templates/firefox/compare/chrome.html
- bedrock/firefox/templates/firefox/compare/edge.html
- bedrock/firefox/templates/firefox/compare/ie.html
- bedrock/firefox/templates/firefox/compare/opera.html
- bedrock/firefox/templates/firefox/compare/safari.html
A few grammar and punctuation fixes came up during review of the extracted strings. (See https://github.com/mozilla-l10n/www.mozilla.org/pull/371)
> [#7574] Small copy fixes for browser comparison pages

- bedrock/firefox/templates/firefox/browsers/index.html
- bedrock/firefox/templates/firefox/products/index.html
- media/static-bundles.json
- Fixes account links on `/firefox/products/` and `/firefox/browsers/` pages.
- Removes duplicate `mozilla-fxa-link.js` script from the page's bundle which was encoding URL params twice.
#8586
> Fix broken accounts links on /products and /browsers/ (Fixes #8586)

- requirements/migration.txt
Pick up fix for bug 1615209
#8593
I've used this code to update `mission.ftl` locally.
> Update fluent.migrate to only migrate localized strings (Fix #8593)

- bedrock/base/templates/base-pebbles.html
- bedrock/base/templates/includes/structured-data/breadcrumb/new.json
- bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
- bedrock/base/templates/includes/structured-data/software/firefox-android-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-beta-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-browser-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-developer-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-enterprise-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-fire-tv-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-ios-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-linux-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-lite-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-lockwise-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-mac-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-monitor-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-nightly-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-send-software.json
- bedrock/base/templates/includes/structured-data/software/firefox-windows-software.json
- bedrock/firefox/templates/firefox/browsers/index.html
- bedrock/firefox/templates/firefox/home/index-master.html
- bedrock/firefox/templates/firefox/home/index-quantum.html
- bedrock/firefox/templates/firefox/lockwise/lockwise.html
- bedrock/firefox/templates/firefox/new/trailhead/download.html
- bedrock/firefox/templates/firefox/products/index.html
- bedrock/mozorg/templates/mozorg/home/home-en.html
- bedrock/mozorg/templates/mozorg/home/home.html
- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- bedrock/settings/appstores.py
- bedrock/settings/base.py
- Exposed structured data to more locales.
- Adds helpers to generate structured data IDs, app store links, and shortened locale codes.
- Moves app store links into `appstores.py`.
- Use `url()` helper for generating links.
#8522
Demo: https://www-demo2.allizom.org/en-US/
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/120549500
> Scale Structured data to locales (Fixes #8522)

- bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
- bedrock/firefox/templates/firefox/new/trailhead/thanks.html
- bedrock/firefox/templates/firefox/nightly_whatsnew.html
- bedrock/firefox/templates/firefox/whatsnew/index.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx71.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx73.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx74.html
- media/css/exp/firefox/whatsnew/whatsnew-71.scss
- media/css/firefox/new/trailhead/thanks.scss
- media/css/firefox/whatsnew/includes/_header.scss
- media/css/firefox/whatsnew/whatsnew-70.scss
- media/css/firefox/whatsnew/whatsnew-71.scss
- media/css/firefox/whatsnew/whatsnew-73.scss
- media/css/firefox/whatsnew/whatsnew-74.scss
- media/css/firefox/whatsnew/whatsnew-account.scss
- media/css/firefox/whatsnew/whatsnew-nightly.scss
- media/css/firefox/whatsnew/whatsnew.scss
- media/css/protocol/protocol.scss
Updates notification on /firefox/download/thanks/ to use the right component, as opposed to custom styling.
- http://localhost:8000/en-US/firefox/download/thanks/
- http://localhost:8000/en-US/firefox/whatsnew/all/
- http://localhost:8000/en-US/firefox/60.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/70.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/71.0/whatsnew/all/
- http://localhost:8000/en-US/exp/firefox/71.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/72.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/73.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/73.0a1/whatsnew/all/
#7615
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/122883474
> Update notifications to use notification component (Fixes #7615)

- bedrock/firefox/views.py
Facebook isn't used in China so zh-CN should fall back to more relevant content
#8629 
http://localhost:8000/zh-CN/firefox/74.0/whatsnew/all/
> [fix #8629] fall back to WNP73 content for zh-CN

- bedrock/firefox/templates/firefox/switch.html
- docs/fluent-conversion.rst
- l10n/en/brands.ftl
- l10n/en/firefox/switch-en.ftl
- l10n/en/firefox/switch.ftl
- lib/fluent_migrations/firefox/switch.py
- Updates the existing Fluent migration to use brand name placeholders in the translations.
- Add an example to our Fluent conversion docs.
Disclaimer: I managed to piece this together by browsing through existing migration files for Firefox in [mozilla-central](https://hg.mozilla.org/mozilla-central/file/tip/python/l10n/fluent_migrations/bug_1600528_browser_context.py). I couldn't find much documentation, and was working on a couple of key pointers from Flod. That said, it seems to be working.
#8595
> Use brand terms in firefox/switch Fluent migration (Fixes #8595)

- l10n/configs/pontoon.toml
- l10n/configs/vendor.toml
- Removes existing vendor config paths.
- Adds a wildcard path to cover all .ftl files for Pontoon.
#8648
> Switch Fluent configs over to Pontoon (Fixes #8648)

- bedrock/firefox/templates/firefox/mobile/index.html
- docs/_templates/footer.html
Added the `footer.html` from [Sphinx-RTD theme](https://github.com/readthedocs/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/footer.html) to override button text. 
fix bug #5101
> Display Page titles in the Next and Previous buttons (fixes #5101)

- bedrock/firefox/templates/firefox/releases/system_requirements.html
- media/css/firefox/system-requirements.scss
Adds download call-out CTA to the bottom of /system-requirements.
https://trello.com/c/A6QrAkhX
#8647
**Test Plan:** https://docs.google.com/document/d/1wmLD2vSXd4SYuMsIMCMRgTZj4mRTAmTBOQrvb0c1fSY/edit?usp=sharing
(We have decided to do pre/post analysis for this experiment.)
> Add download call-out to bottom of /system-requirements (#8647)

- media/css/firefox/whatsnew/whatsnew-75.scss
I made a dumb mistake in #8673 and committed a bit of code I should have removed (artifact of local testing).
`.show-signed-in` should always be hidden *except* when the user is signed in. Hanging it from the `.state-fxa-default` class breaks because that class is removed/replaced when FxA is supported (so any modern Firefox) even if signed out.
> [#8564] WNP75, hide signed-in content when signed out

- bedrock/mozorg/tests/test_util.py
- bedrock/mozorg/util.py
- lib/l10n_utils/__init__.py
- lib/l10n_utils/tests/test_dotlang.py
- lib/l10n_utils/tests/test_template.py
This change results in passing every page render through the l10n system, even ones in the SUPPORTED_NONLOCALE list.
Fix #8680
> Fix Fluent error on supported nonlocale pages

- bedrock/base/templates/includes/protocol/footer/firefox.html
- bedrock/base/templates/includes/protocol/footer/mozilla.html
- bedrock/base/templates/includes/protocol/lang-switcher.html
- bedrock/settings/base.py
- l10n/en/footer.ftl
- l10n/en/navigation.ftl
- lib/fluent_migrations/includes/protocol/footer/footer.py
- Migrate footer.lang to footer.ftl
- Update footer templates to use Fluent string IDs.
https://github.com/mozilla/bedrock/issues/8663
- First make sure translations are up to date by running `./manage.py l10n_update`.
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/128782618
> Migrate footer to Fluent (Fixes #8663)

- bedrock/legal/templates/legal/index.html
- bedrock/legal/templates/legal/terms/betterweb.html
- bedrock/legal/urls.py
- bedrock/privacy/templates/privacy/base-protocol.html
- bedrock/privacy/templates/privacy/index.html
- bedrock/privacy/templates/privacy/notices/firefox-betterweb.html
- bedrock/privacy/urls.py
- bedrock/privacy/views.py
Updates legal docs, adds Terms and Privacy pages for Firefox Better Web, and also adds a SUMO link on the main privacy page.
#8691 - Add Better Web terms and privacy pages
#7052 - Add support link to privacy contact section
http://localhost:8000/privacy/
http://localhost:8000/privacy/betterweb/
http://localhost:8000/about/legal/
http://localhost:8000/about/legal/terms/betterweb/
> [fix #8691] Add Better Web terms and privacy pages

- bedrock/legal/templates/legal/impressum.html
Removes mention of Chris Beard and Michael DeAngelo from legal/impressum
(noticed when reviewing a pull request.)
> Remove Chris Beard and Michael DeAngelo from legal/impressum [no bug]

- bedrock/firefox/views.py
- Only show nightly download if `?channel=nightly`
- Only show dev edition download if `?channel=alpha` or `aurora`
#8579
> Only show nightly or dev edition CTA when appropriate channel (Fixes #8579)

- .gitlab-ci.yml
- bedrock/settings/base.py
- bedrock/utils/git.py
- bin/process-ftl.sh
- lib/l10n_utils/management/commands/process_ftl.py
Add a --push argument to the `process_ftl` management command and add a gitlab automation to run this command.
Fix #7705
I ran this locally by running the following command:
```
env FLUENT_REPO=https://github.com/pmac/www-l10n \
docker run --rm -it \
-e FLUENT_REPO \
-e FLUENT_REPO_AUTH \
-v "$PWD/lib:/app/lib:delegated" \
mozorg/bedrock:latest \
python manage.py process_ftl --push
```
If you had a use with access and a personal access token you could add another environment variable `FLUENT_REPO_AUTH` with `<github user>:<github token>` format and it would successfully push as well.
> Add ability to commit and push changes to Fluent repo

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx75.html
- media/css/firefox/whatsnew/whatsnew-75.scss
- media/js/firefox/whatsnew/whatsnew-75.js
- media/static-bundles.json
- tests/functional/firefox/whatsnew/test_whatsnew_75.py
- tests/pages/firefox/whatsnew/whatsnew_75.py
We should only show the Monitor pitch to users signed into FxA with at least one mobile device. All others get the Sync pitch.
https://www-demo3.allizom.org/firefox/75.0/whatsnew/all/
> [#8564] Update WNP75 state logic

- bedrock/base/templates/includes/protocol/footer/firefox.html
- bedrock/base/templates/includes/protocol/navigation/menu-firefox/index.html
- bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
- bedrock/base/templates/includes/protocol/navigation/menu-mozilla/index.html
- bedrock/base/templates/includes/protocol/navigation/nav-cta.html
- bedrock/base/templates/macros.html
- bedrock/exp/templates/exp/firefox/accounts-2019.html
- bedrock/exp/templates/exp/firefox/index.de.html
- bedrock/exp/templates/exp/firefox/index.html
- bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
- bedrock/firefox/templates/firefox/accounts-2019.html
- bedrock/firefox/templates/firefox/browsers/index.html
- bedrock/firefox/templates/firefox/firstrun/firstrun.html
- bedrock/firefox/templates/firefox/home/index-master.html
- bedrock/firefox/templates/firefox/privacy/index.html
- bedrock/firefox/templates/firefox/privacy/products.html
- bedrock/firefox/templates/firefox/products/index.html
- bedrock/firefox/templates/firefox/welcome/page3.html
- bedrock/firefox/templates/firefox/whatsnew/index-account.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx71.html
- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- docs/firefox-accounts.rst
- media/js/base/mozilla-fxa-product-button.js
- media/static-bundles.json
- tests/pages/firefox/accounts.py
- tests/unit/spec/base/mozilla-fxa-product-button.js
- Removes `fxa_cta_link` and `fxa_link_fragment` macros.
- Replaces with `fxa_button` and `fxa_link_fragment` python helpers.
- Adds unit tests 🎉
- Updates documentation.
URLs:
- http://localhost:8000/en-US/firefox/ (navigation and footer links, navigation FxA button, FxA button at bottom of page)
- http://localhost:8000/en-US/firefox/accounts/
- http://localhost:8000/en-US/exp/firefox/accounts/
- http://localhost:8000/de/exp/firefox/
- http://localhost:8000/en-US/exp/firefox/
- http://localhost:8000/en-US/exp/firefox/71.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/browsers/
- http://localhost:8000/en-US/firefox/firstrun/
- http://localhost:8000/en-US/firefox/new/ (legacy template)
- http://localhost:8000/en-US/firefox/privacy/products/
- …
> Convert FxA macro buttons to python helpers (Fixes #8185)

- bedrock/firefox/templates/firefox/installer-help-b.html
- bedrock/firefox/templates/firefox/installer-help.html
- bedrock/firefox/views.py
- media/css/firefox/installer-help-b.scss
- media/js/firefox/installer-help-experiment.js
- media/static-bundles.json
Testing conversion rate of a redesigned firefox/installer-help page.
#8602
**demo:** https://www-demo5.allizom.org/en-US/firefox/installer-help/?v=b
> Experiment: installer-help redesign. (#8602)

- bedrock/firefox/templates/firefox/installer-help-b.html
Adds missing JS bundle to experiment variant template `installer-help-b.html` (#8731)
> Add installer_help_experiment bundle to installer-help-b (bugfix)

- bedrock/base/templates/macros.html
- bedrock/settings/base.py
- l10n/en/fxa_form.ftl
- lib/fluent_migrations/firefox/fxa-form.py
- Migrate FxA form strings from `main.lang` to `fxa_form.ftl`
- Update macro to use Fluent string IDs.
#8657
- Run `./manage.py l10n_update` before testing other languages.
> Port FxA Email form to Fluent (Issue #8657)

- bedrock/mozorg/templates/mozorg/home/home-en.html
Temporarily moving from 2 two 4 cards in the row above the pocket recommendations. This change will check to see if there are 17 cards and change the layout accordingly.
Because of the difference in card sizes between the 2 and 4 card layout the conditional row will not use the card 6 and 7 data.
This means the change here and the change in www-admin are independent of each other. Either change can go first
Fix #8744
- Up on [demo3](https://www-demo3.allizom.org/en-US/) and pulling all 17 cards from www-admin. 
- Other demos have 17 cards of data but not the new homepage file.
- Pushing master to the `dev` branch of www-admin will trigger the state where demo3 has updated homepage code but not updated content cards.
> Display 4 cards in 3rd row of EN homepage if there are 17 cards (#8744)

- bedrock/firefox/templates/firefox/enterprise/index.html
- media/css/firefox/enterprise/landing.scss
- tests/functional/firefox/test_enterprise.py
- tests/pages/firefox/enterprise/landing.py
These were some improvements suggested in code review on https://github.com/mozilla/bedrock/pull/8722 but we punted them at the time so we could get the essential page updates live. Finally following up now.
http://localhost:8000/firefox/enterprise/
> [#8578] Enterprise page - align download menus, update tests

- docs/l10n.rst
- lib/l10n_utils/fluent.py
- lib/l10n_utils/tests/test_fluent.py
This updates the `ftl`, `ftl_lazy`, and `has_messages` functions that are for use in Python code to not require fluent files to be defined if using the default files, to allow passing a single fluent file as a string instead of a list, and to require fluent files to be passed in via the `ftl_files` keyword argument.
> Update Fluent python view utils with better dev UX

- bedrock/mozorg/templates/mozorg/home/includes/macros.html
Update 'meet the firefox family' link to got to firefox home page.
n/a (discussed this with the brand team and it has been okayed)
Visit http://localhost:8000/en-US/ in Firefox and check that the "meet the family" button goes to the Firefox homepage.
> [no bug] update 'meet the firefox family' link to got to firefox home

- bedrock/firefox/templates/firefox/channel/android.html
- bedrock/firefox/templates/firefox/channel/desktop.html
- bedrock/firefox/templates/firefox/enterprise/index.html
- bedrock/firefox/templates/firefox/products/index.html
- l10n/en/download_button.ftl
- lib/fluent_migrations/firefox/includes/download-button.py
- Add missing "Download" string to `download_button.ftl` (migrated from `main.lang`).
- Update templates to use new fluent ID.
#8657
- `./manage.py fluent ftl lib/fluent_migrations/firefox/includes/download-button.py de fr`
> Add Download string to download_button.ftl (#8657)

- bedrock/mozorg/forms.py
- bedrock/newsletter/forms.py
- bedrock/newsletter/templates/newsletter/includes/form-protocol.html
- bedrock/newsletter/templates/newsletter/includes/form.html
- bedrock/newsletter/templates/newsletter/includes/macros.html
- bedrock/newsletter/views.py
- bedrock/settings/base.py
- l10n/en/newsletter_form.ftl
- lib/fluent_migrations/newsletter/includes/newsletter-extra.py
- lib/fluent_migrations/newsletter/includes/newsletter.py
- Migrates newsletter form strings in `main.lang` to `newsletter_form.ftl`.
#8657
Run migrations locally:
```
./manage.py fluent ftl lib/fluent_migrations/newsletter/includes/newsletter.py ach af am an ar ast az azz be bn br bs ca cak crh cy da dsb el en-CA en-GB eo es-AR es-CL es-MX et eu fa ff fi fy-NL ga-IE gd gl gn gu-IN he hi-IN hr hsb hto hy-AM ia is ja ka kab kk km kn ko lij lo lt ltg lv mk ml mr ms my nb-NO ne-NP nn-NO nv oc pa-IN pai pbb pt-PT qvi rm ro si sk sl son sq sr sv-SE sw ta te th tl tr trs uk ur uz vi wo xh zam zh-CN zu
```
```
./manage.py fluent ftl lib/fluent_migrations/newsletter/includes/newsletter-extra.py bg cs de es-ES fr hu id it nl pl pt-BR ru zh-TW
```
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/133548950
> Port newsletter form to Fluent (Issue #8657)

- bedrock/firefox/redirects.py
- tests/redirects/map_globalconf.py
Redirects /mobile to /firefox/mobile
#8749
> Redirect /mobile to /firefox/mobile. (Fixes #8749)

- bedrock/firefox/redirects.py
- tests/redirects/map_globalconf.py
Adds a 302 temporary redirect for all the browser comparison pages
These should all redirect to /firefox
> [no bug] Redirect browser comparison pages

- bedrock/firefox/templates/firefox/features/independent.html
- bedrock/firefox/templates/firefox/features/index.html
Uses the l10n tag `independent_042020` (I'll submit a string update shortly).
#8771 
http://localhost:8000/firefox/features/independent/
> [fix #8771] Update independent features page copy

- bedrock/firefox/templates/firefox/enterprise/index.html
The resources section was removed but I missed the link in the subnav.
#8761
> [fix #8761] Delete resources link from enterprise subnav

- bedrock/releasenotes/management/commands/update_release_notes.py
- bin/cron.py
- bin/run-db-upload.py
We've had a few instances in dev of bedrock not being updated with release notes.
Adds a success message in the run-upload-db.py file, and adding newlines to both skips and successes.
Non-quiet release notes jobs will output the current hashes, and new hash, which should help debugging.
* clock container logs should be a little easier to read
* update_release_notes_job should have an additional log line (container script may not show this, as it has the quiet flag passed).
> Small debugging improvement for release notes update

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx75.html
- media/css/firefox/whatsnew/whatsnew-75.scss
- media/js/firefox/whatsnew/whatsnew-75.js
- tests/functional/firefox/whatsnew/test_whatsnew_75.py
- tests/pages/firefox/whatsnew/whatsnew_75.py
- Adds a third state to /firefox75.0/whatsnew/ for Firefox users who are signed out of Sync.
#8770
> Show regular Sync button to signed out Firefox users on 75 WNP (Fixes #8770)

- lib/l10n_utils/__init__.py
- lib/l10n_utils/tests/test_base.py
If a list of ftl_files that was defined in the view was passed to render() it would have updated the original list in place with the list of default files, and this would have incresed the size of the list every call to render() for that function.
I noticed this while reviewing another l10n related PR.
> Fix potential ftl_files memory leak

- bedrock/base/templates/macros.html
- bedrock/firefox/templates/firefox/mobile/get-app.html
- bedrock/firefox/templates/firefox/mobile/index.html
- bedrock/firefox/templates/firefox/welcome/page4.html
- bedrock/firefox/templates/firefox/welcome/page5.html
- bedrock/firefox/templates/firefox/whatsnew/index-lite.html
- bedrock/firefox/templates/firefox/whatsnew/index-lite.id.html
- bedrock/firefox/templates/firefox/whatsnew/index.html
- bedrock/settings/base.py
- l10n/en/send_to_device.ftl
- lib/fluent_migrations/firefox/send-to-device.py
- Migrates `firefox/sendto.lang` to `send_to_device.ftl`.
#8658
```
./manage.py fluent ftl lib/fluent_migrations/firefox/send-to-device.py ach af am an ar ast az azz be bg bn br bs ca cak crh cs cy da de dsb el en-CA en-GB eo es-AR es-CL es-ES es-MX et eu fa ff fi fr fy-NL ga-IE gd gl gn gu-IN he hi-IN hr hsb hu hy-AM ia id is it ja ka kab kk km kn ko lij lo lt ltg lv mk ml mr ms my nb-NO ne-NP nl nn-NO nv oc pa-IN pl pt-BR pt-PT rm ro ru si sk sl son sq sr sv-SE sw ta te th tl tr uk ur uz vi xh zam zh-CN zh-TW zu
```
> Migrate send-to-device widget to Fluent (Fixes #8658)

- bedrock/exp/templates/exp/firefox/new/download.html
- bedrock/exp/views.py
Add b and c variants of exp/firefox/new page. Both have nav menu but b does not display it. A is control.
#8773
-http://localhost:8000/en-US/exp/firefox/new/?v=a
-http://localhost:8000/en-US/exp/firefox/new/?v=b
-http://localhost:8000/en-US/exp/firefox/new/?v=c
> Add b and c variants of exp/firefox/new page (#8773)

- bedrock/firefox/templates/firefox/channel/base.html
- bedrock/mozorg/templates/mozorg/base.html
- l10n/en/newsletter_form.ftl
- lib/fluent_migrations/newsletter/includes/newsletter.py
- Migrates some global newsletter titles from `main.lang` that I missed in https://github.com/mozilla/bedrock/pull/8748
#8657
```
```
> Migrate global newsletter titles to Fluent (Issue #8657)

- lib/l10n_utils/fluent.py
- lib/l10n_utils/management/commands/active_locales.py
- lib/l10n_utils/tests/test_fluent.py
This will ensure that all functions that use `fluent.get_active_locales` treat all locales as active when `DEV=True`.
> Fluent active locales should be all of them in DEV mode

- bedrock/firefox/templates/firefox/new/trailhead/download-yandex.html
Fixes https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/8015222/
```
ValueError: Missing staticfiles manifest entry for 'js/BUNDLES/firefox_new_scene1_yandex.js'
```
#8801
> Fix missing yandex bundle name (Issue #8801)

- bedrock/firefox/urls.py
- l10n/en/firefox/switch-en.ftl
- l10n/en/firefox/switch.ftl
Adds a new string to `switch.ftl` that was never exposed for L10n prior to the migration from .lang. Exposing this now will prevent the `firefox/switch-en.ftl` file (which was added as a temporary workaround) from being picked up by automation. This will also give us another pre-launch test of the process.
N/A
> Expose new string in firefox/switch.ftl

- Makefile
- bin/run-prod.sh
- docker-compose.yml
- docs/install.rst
This will give us some commands to more easily build and run the prod Docker image locally. It will run using your local version of the Django app, but not the media, which must be built separately.
If you want to run things locally as if they're prod and see changes in templates or Python files you can simply:
```
make pull run-prod
```
That will pull the latest prod image and run it in prod mode locally. If you need to build new static assets (images, CSS, JS, etc.) then you can do:
```
make build-prod run-prod
```
Let me know what you think.
Re #8636
> Make running locally in prod mode easier

- bedrock/firefox/templates/firefox/releases/notes.html
- bedrock/releasenotes/views.py
- media/css/firefox/releasenotes.scss
- media/js/firefox/social-proof-experiment.js
This PR adds a second treatment to the social proof experiment. The second treatment contains a download button but no social proof copy.
I flagged it on in dev (https://github.com/mozmeao/www-config/commit/f30e495c15c8aaa9cace413f91e21765e1bbb5c0#diff-dfacfa39463276824d4b2de8c7a34c6cR37) and tested in Chrome incognito: 
* all 3 variations were assigned by TrafficCop as expected
* all 3 look as expected on wide/narrow screens
* the dataLayer is populated with the expected variation name
* the injected download button works as expected
> Add a 2nd treatment to socialproof experiment

- bedrock/firefox/templates/firefox/messaging-experiment/privacy_by_default.html
- bedrock/firefox/templates/firefox/messaging-experiment/privacy_tools.html
@craigcook 
The tooling callout was meant to go to the protections report. While the privacy by default page was meant to go to the privacy promise page. I had it backwards.
> Exchange CTA buttons

- bedrock/exp/templates/exp/firefox/mobile.html
- bedrock/exp/templates/exp/home/home-de.html
- bedrock/exp/templates/exp/home/home-en.html
- bedrock/exp/templates/exp/home/home-fr.html
- bedrock/exp/urls.py
- bedrock/exp/views.py
- media/css/exp/home/home-2018.scss
- media/css/exp/home/home.scss
- media/css/exp/mobile.scss
- media/js/exp/home.js
- media/js/exp/mobile.js
- media/static-bundles.json
- tests/functional/test_experiment_pages.py
Adds firefox/mobile and the homepage to the exp app for convert tests.
#8795
[Creating exp pages docs.](https://bedrock.readthedocs.io/en/latest/abtest.html#creating-experimental-pages)
> Add exp versions of the homepage and mobile (fixes #8795)

- media/css/mozorg/book.scss
- media/css/mozorg/credits.scss
- media/css/mozorg/namespaces.scss
These pages are all one-offs and have no dependencies on Pebbles:
- http://localhost:8000/book/
- http://localhost:8000/credits/
- http://localhost:8000/keymaster/gatekeeper/there.is.only.xul
N/A
> Remove pebbles import from one-off pages

- bedrock/mozorg/redirects.py
- bedrock/mozorg/templates/mozorg/about/leadership.html
- tests/redirects/map_globalconf.py
Redirects mozilla.org/ekr/ to https://blog.mozilla.org/blog/author/ekrmozilla-com/
https://github.com/mozilla/blogdotmozilladotorg/issues/18
Make sure it works and the test passes.
> Add vanity URL redirect for EKR’s blog

- bedrock/base/templates/base-pebbles.html
- bedrock/base/templates/includes/banners/base.html
- bedrock/firefox/templates/firefox/includes/download-button.html
- bedrock/firefox/tests/test_helpers.py
- media/js/base/mozilla-banner.js
- tests/unit/spec/base/mozilla-banner.js
- Add `data-nosnippet` attributes to conditional messaging inside download buttons.
- Add `data-nosnippet` attribute to page banners.
#8739
Demo: 
- https://www-demo5.allizom.org/en-US/
- https://www-demo5.allizom.org/en-US/firefox/new/
> Exclude unrelated page content from search result snippets (Fixes #8739)

- bedrock/exp/templates/exp/firefox/new/download.html
- bedrock/exp/views.py
Remove nav from /new exp page
See #8773
http://localhost:8000/en-US/exp/firefox/new/
> Remove nav from /new exp page #8773

- bedrock/exp/views.py
Prevents URLs should as http://localhost:8000/ru/exp/ throwing an error
#8882
> Fix /exp/ home page error for some locales (Fixes #8882)

- bedrock/base/templates/includes/canonical-url.html
Remove locale from hreflang x-default
#8513
> Remove locale from hreflang x-default (Fixes #8513)

- media/static-bundles.json
- Fixes broken newsletter signup form on http://localhost:8000/en-US/firefox/channel/desktop/
#8690
> Fix newsletter form submission on /channel page (Fixes #8690)

- bedrock/legal/templates/legal/terms/firefox-screenshotgo.html
- bedrock/legal/urls.py
- bedrock/privacy/templates/privacy/notices/firefox-screenshotgo.html
- bedrock/privacy/urls.py
- bedrock/privacy/views.py
Removes:
- http://localhost:8000/en-US/privacy/firefox-screenshotgo/
- http://localhost:8000/en-US/about/legal/terms/firefox-screenshotgo/
#8619
> Remove screenshotgo pages (fixes #8619)

- bedrock/firefox/templates/firefox/releases/aurora-notes.html
- bedrock/firefox/templates/firefox/releases/beta-notes.html
- bedrock/firefox/templates/firefox/releases/dev-browser-notes.html
- bedrock/firefox/templates/firefox/releases/esr-notes.html
- bedrock/firefox/templates/firefox/releases/nightly-notes.html
- bedrock/firefox/templates/firefox/releases/notes.html
- bedrock/firefox/templates/firefox/releases/release-notes.html
- tests/functional/firefox/test_releasenotes.py
- tests/pages/firefox/releasenotes.py
Adds functional tests for release notes pages.
#7388
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/143244492
> Add functional tests for releasenotes pages (Fixes #7388)

- bedrock/exp/templates/exp/home/home-de.html
- bedrock/exp/templates/exp/home/home-en.html
- bedrock/exp/templates/exp/home/home-fr.html
- bedrock/firefox/templates/firefox/channel/base.html
- bedrock/firefox/templates/firefox/developer/includes/alt-newsletter.html
- bedrock/firefox/templates/firefox/developer/index.html
- bedrock/firefox/templates/firefox/retention/thank-you.html
- bedrock/foundation/templates/foundation/annualreport/2009/base.html
- bedrock/foundation/templates/foundation/annualreport/2010/base.html
- bedrock/foundation/templates/foundation/base.html
- bedrock/legal/templates/legal/index.html
- bedrock/mozorg/templates/mozorg/about-base.html
- bedrock/mozorg/templates/mozorg/about.html
- bedrock/mozorg/templates/mozorg/about/manifesto.html
- bedrock/mozorg/templates/mozorg/home/home-de.html
- bedrock/mozorg/templates/mozorg/home/home-en.html
- bedrock/mozorg/templates/mozorg/home/home-fr.html
- bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
- bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
- bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
- bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
- bedrock/mozorg/templates/mozorg/internet-health/web-literacy.html
- bedrock/mozorg/templates/mozorg/mission.html
- bedrock/mozorg/templates/mozorg/moss/base.html
- bedrock/newsletter/templates/newsletter/includes/form-protocol.html
- bedrock/newsletter/templates/newsletter/includes/form.html
- bedrock/newsletter/templates/newsletter/index.html
- bedrock/newsletter/templatetags/helpers.py
- media/css/protocol/protocol.scss
The new contribute page introduces a secondary title to the newsletter form, and on reviewing that I realize that what we've called a "subtitle" in the form macro isn't really a title. It's a `p` element and is used as more of a description and has the class `mzp-c-newsletter-tagline`, so the element class doesn't even match what we're calling it in the macro. This renames that element as "desc" and adds a new `h4` as "subtitle".
I filed https://github.com/mozilla/protocol/issues/578 to update the component upstream in Protocol but this implements it first in bedrock to unblock the new contribute page. And I made it a separate PR to simplify code review since this ends up touching a bunch of pages.
N/A
Did I miss any forms?
> [no bug] Update newsletter form subtitle and description

- bedrock/exp/templates/exp/firefox/mobile.html
- bedrock/firefox/templates/firefox/mobile/index.html
As mentioned by @alexgibson there were duplicate IDs on the webpages /en-US/firefox/mobile/ and en-US/exp/firefox/mobile/  to avoid future errors related to this bug I added indexes to the IDs, making them unique. The IDs were not declared in any static files.
#8867
> fix bug #8867 added indexes to duplicate IDs

- bedrock/mozorg/templates/mozorg/home/home-fr.html
Fix typo on French homepage.
Fix #8912 
http://localhost:8000/fr/
> Typo on FR homepage (Fix #8912)

- bedrock/mozorg/templatetags/misc.py
- bedrock/mozorg/tests/test_helper_misc.py
- media/js/base/base-page-init.js
- media/js/base/mozilla-fxa-product-button.js
- media/js/base/mozilla-utils.js
- tests/unit/spec/base/mozilla-fxa-product-button.js
- tests/unit/spec/base/mozilla-utils.js
Moves the mozillaonline link switching logic into `mozilla-fxa-product-button.js`, so we have tighter control over how and when FxA links are updated.
By controlling the order of events, this change should prevent metrics flow params being attached to https://accounts.firefox.com.cn/ from flow requests originating at https://accounts.firefox.com/.
#8328
Demo: https://www-demo1.allizom.org/en-US/firefox/60.0/whatsnew/all/
- Setup UITour permission for demo1.
- Open dev tools setting and make sure "Enable browser chrome and add-on debugging toolboxes" is checked.
- Open Firefox's "Browser Console" and set `distribution.id` by pasting `Services.prefs.getDefaultBranch("distribution.").setCharPref("id", "MozillaOnline");`.
- Visit https://www-demo1.allizom.org/en-US/firefox/60.0/whatsnew/all/. …
> Integrate FxA product button JS with China repack logic (Fixes #8328)

- tests/functional/firefox/new/test_platform.py
- tests/pages/firefox/new/platform.py
Adds functional test coverage for `/windows/`, `/mac/`, and `/linux/` download pages.
#8604
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/142725753
> Add platform download page tests (Fixes #8604)

- bedrock/base/templates/product-all-unified-macros.html
- bedrock/firefox/firefox_details.py
- bedrock/firefox/templates/firefox/all-unified.html
- bedrock/firefox/views.py
- l10n/en/firefox/all.ftl
- lib/fluent_migrations/firefox/all-unified.py
- Migrates `firefox/all-unified.lang` to `firefox/all.ftl`.
- Updates template and macros to use new Fluent IDs.
#8511
```
./manage.py fluent ftl lib/fluent_migrations/firefox/all-unified.py ach af am an ar ast az azz be bg bn br bs ca cak crh cs cy da de dsb el en-CA en-GB eo es-AR es-CL es-ES es-MX et eu fa ff fi fr fy-NL ga-IE gd gl gn gu-IN he hi-IN hr hsb hto hu hy-AM ia id is it ja ka kab kk km kn ko lij lo lt ltg lv mk ml mr ms my nb-NO ne-NP nl nn-NO nv oc pa-IN pai pbb pl pt-BR pt-PT qvi rm ro ru si sk sl son sq sr sv-SE sw ta te th tl tr trs uk ur uz vi wo xh zam zh-CN zh-TW zu
```
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/137224011
> Migrate firefox/all to Fluent (Fixes #8511)

- bedrock/firefox/templates/firefox/mobile/index.html
- bedrock/firefox/urls.py
- media/css/firefox/mobile/mobile.scss
- media/js/firefox/mobile/experiment-mobile.js
- media/static-bundles.json
- tests/functional/firefox/test_mobile.py
Adds variant view on firefox/mobile & traffic cop JS for an experiment to test the performance of the send to device widget inside & outside modal.
(See issue for test plan & CRO team card)
#8899
> Add firefox/mobile send-to-device experiment. (fixes #8899)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx77.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/views.py
- media/css/firefox/whatsnew/whatsnew-77.scss
- media/js/firefox/whatsnew/whatsnew-77-zhCN.js
- media/static-bundles.json
YouTube is blocked in China, so we'll show a self-hosted video to zh-CN. Other locales should still get the YouTube embed.
This is behind the switch `firefox-whatsnew77-video-zhCN` so in case we approach exceeding our bandwidth we can quickly turn it off and zh-CN should fall back to the WNP76 template.
The 77 release is **2020-06-02** so we need to get this into production before then. Marking as P1.
http://localhost:8000/zh-CN/firefox/77.0/whatsnew/all/
https://www-demo3.allizom.org/zh-CN/firefox/77.0/whatsnew/all/
> [no bug] WNP77, use self-hosted video for zh-CN

- bedrock/mozorg/templates/mozorg/about/leadership.html
Removed: 'Steering Committee' under Mary Ellen Muckerman and Sean White's names in the Management Teams section. Also reordered accordingly (we list steering committee members first, followed by C-level execs, followed by everyone else).
Removed: 'Chair' under Mitchell's name in the Board of Directors - Moco.
This needs to be live on **Monday, 1 June**
#8951 
http://localhost:8000/about/leadership/
> [fix #8951] Leadership page updates, June 1

- bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
Removes tracking.services.mozilla.com from the list of eligible bug bounty sites, since it no longer exists.
> Remove tracking.services.mozilla.com from eligible sites

- media/css/firefox/browsers-products.scss
- media/css/firefox/enterprise/landing.scss
- media/css/firefox/home/master.scss
- media/css/protocol/components/_custom-menu-list.scss
Takes custom menu-list styles from `/enterprise/` and moves them to a component so they can be shared with `/browsers/` and `/products/`
- http://localhost:8000/en-US/firefox/
- http://localhost:8000/en-US/firefox/enterprise/
- http://localhost:8000/en-US/firefox/browsers/
- http://localhost:8000/en-US/firefox/products/
#8950
> Turn CTA links into buttons on /firefox and /browsers (Fixes #8950)

- media/js/base/uitour-lib.js
Adds `"flow_id", "flow_begin_time", "device_id"` field support
@alexgibson r?
From Firefox 79 we can now also send "flow_id", "flow_begin_time", "device_id" as part of the UI tour.
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1635219
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1635213
Related to https://github.com/mozilla/bedrock/pull/8914
Local testing.
> Rename `extraURLCampaignParams` to `extraURLParams` in FxA UITour

- bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
- bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
- bedrock/base/templates/includes/protocol/navigation/menu-mozilla/developers.html
- bedrock/base/templates/includes/protocol/navigation/menu-mozilla/firefox.html
- switched to smaller .png files for icons
- added `loading=lazy` to icons
- also found a link to the products page that I uncommented
Fix #8981 
The Firefox menu is only on pages under /firefox.
> Lazy load smaller icons in Firefox products nav menu (Fix #8981)

- bedrock/firefox/templates/firefox/switch.html
- bedrock/firefox/urls.py
- l10n/en/firefox/switch.ftl
Removes mention of "autofill" from /firefox/switch/ page as it's something we no longer import.
#8651
> Remove autofill from /switch page (Fixes #8651)

- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- l10n/en/firefox/accounts.ftl
- lib/fluent_migrations/firefox/accounts-2019.py
- Migrates `firefox/accounts-2019.lang` to `firefox/accounts.ftl`
- Renames `firefox/accounts-2019.html` to `firefox/accounts.html`
#8968
```
```
> Migrate /firefox/accounts to Fluent (#8968)

- bedrock/mozorg/redirects.py
- tests/redirects/map_globalconf.py
- Adds redirect for `/dontate` to donate.mozilla.org.
#8949
> Add vanity redirect for donate.mozilla.org (Fixes #8949)

- bedrock/firefox/templates/firefox/home/index-master.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/urls.py
- bedrock/firefox/views.py
- l10n/en/firefox/home.ftl
- lib/fluent_migrations/firefox/home/index-master.py
- Migrates `firefox/home-master.lang` to `firefox/home.ftl`.
#8968
```
```
> Migrate /firefox to Fluent (#8968)

- bedrock/firefox/templates/firefox/browsers/index.html
- bedrock/firefox/urls.py
- l10n/en/brands.ftl
- l10n/en/firefox/browsers.ftl
- lib/fluent_migrations/firefox/browsers/index.py
- Migrates `firefox/browsers.lang` to `firefox/browsers.ftl`.
#8968
```
./manage.py fluent ftl lib/fluent_migrations/firefox/browsers/index.py ach af am an ar ast az azz be bg bn br bs ca cak crh cs cy da de dsb el en-CA en-GB eo es-AR es-CL es-ES es-MX et eu fa ff fi fr fy-NL ga-IE gd gl gn gu-IN he hi-IN hr hsb hto hu hy-AM ia id is it ja ka kab kk km kn ko lij lo lt ltg lv mk ml mr ms my nb-NO ne-NP nl nn-NO nv oc pa-IN pai pbb pl pt-BR pt-PT qvi rm ro ru si sk sl son sq sr sv-SE sw ta te th tl tr trs uk ur uz vi wo xh zam zh-CN zh-TW zu
```
> Migrate firefox/browsers to Fluent (#8968)

- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx77-b.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx77.html
- bedrock/firefox/views.py
- media/css/firefox/welcome.scss
- media/js/firefox/whatsnew/whatsnew-77-exp.js
- media/static-bundles.json
Adds an A/B traffic cop experiment to the whatsnew page for Firefox 77.
[Test plan](https://docs.google.com/document/d/1tAdN48r7BRjosHBXdZTyLl1gwNdkSJC-GNHRBQOHngg/edit?usp=sharing)
_Traffic Distribution Per Group: 2%_
➡️  test plan calls for this experiment to launch friday 6/12
#8683
> Add wnp77 moments template experiment. (#8683)

- bedrock/newsletter/templates/newsletter/includes/form-protocol.html
- bedrock/newsletter/templates/newsletter/includes/form.html
- l10n/en/newsletter_form.ftl
- media/css/firefox/channel.scss
Adds "We will only send you Firefox-related information" string to Firefox related newsletters.
- https://www-demo2.allizom.org/en-US/firefox/channel/desktop/
- https://www-demo2.allizom.org/en-US/newsletter/firefox/
#7460
> Add communication promise string to Firefox newsletters (Fixes #7460)

- media/caldata/calendars.json
Fix Slovak calendar in calendars.json (change end date from 2020 to 2025). ICS file was updated with holidays up to year 2025 in #7170, but calendar.json was not updated. Because of that, webpage with calendar list still says "2009-2020).
Fixes #9029.
> Fix Slovak calendar in calendars.json

- bedrock/privacy/templates/privacy/base-protocol.html
- bedrock/privacy/templates/privacy/notices/firefox-relay.html
- bedrock/privacy/urls.py
- bedrock/privacy/views.py
Adds new privacy notice for Firefox Relay. 
This needs to be live in production on **23 June**
Updates the rest of legal-docs as well.
http://localhost:8000/privacy/firefox-relay/
> Add Firefox Relay legal docs

- bedrock/firefox/urls.py
**Note:** we should only merge this **if** we need to deploy to production **before** we get a go-ahead on the comparison pages. We can also just wait to push prod.
The browser comparison pages are finished, but it was only after they merged that I learned we're still waiting for a final go/no-go from leadership before publishing them, and we won't get word until tomorrow (25 June) at the earliest. 
Since the pages already merged we're effectively blocked from doing a production push until we have permission to relaunch the comparison pages. However, l10n is already in progress so we need to make sure the pages are still available on dev/demo, so I don't want to revert the commit or redirect the URLs. I considered putting the pages behind a switch but I think that would entail routing …
> Only show browser comparison pages in DEV mode

- bedrock/legal/templates/legal/terms/firefox-private-network.html
- bedrock/privacy/templates/privacy/notices/firefox-private-network.html
Remove "(Beta)" from page titles.
#9050 
http://localhost:8000/privacy/firefox-private-network/
http://localhost:8000/about/legal/terms/firefox-private-network/
> [fix #9050] Remove “beta” from FPN terms and privacy policy

- tests/functional/firefox/new/test_download.py
The download page redesign experiment directs 3% of visitors to the new page. There's a slight chance automated functional tests would fail if they get that page and can't find the elements the tests are expecting, thus halting a deployment. Since there's not currently an easy way to exclude functional tests from traffic cop (see #8917) this just adds the `?v=a` param to the URL to make sure tests always get the old page design.
1. Run `tests/functional/firefox/new/test_download.py`
2. Ensure the browser loads `/firefox/new/?v=a` and that tests pass
3. If you want to be extra-sure, you can set the B variant to 100% in the traffic cop config (`/media/js/firefox/new/desktop/exp.js`)
> [#9019] Evade traffic cop in /new functional tests

- bedrock/firefox/redirects.py
- tests/redirects/map_301.py
- tests/redirects/map_globalconf.py
> Redirect /products/firefox/ to /firefox/products/ (Fixes #9008)

- bedrock/firefox/templates/firefox/new/desktop/download.html
Fixes broken iOS app store badge link
http://localhost:8000/en-US/firefox/new/?v=b
#9071
> Fix iOS app store link on /new experiment page (Fixes #9071)

- lib/l10n_utils/fluent.py
- lib/l10n_utils/tests/test_files/l10n/de/mozorg/fluent.ftl
- lib/l10n_utils/tests/test_files/l10n/en/brands.ftl
- lib/l10n_utils/tests/test_files/l10n/en/mozorg/fluent.ftl
- lib/l10n_utils/tests/test_files/l10n/fr/brands.ftl
- lib/l10n_utils/tests/test_files/l10n/fr/mozorg/fluent.ftl
- lib/l10n_utils/tests/test_fluent.py
In Fluent each term you use in a string has to be availalbe in that locale bundle. This is a bit of a hack around that. This change looks for the presence of a term ID in the translated string, and if it sees one it will add the string as a new ID to a new translation context with the en brands.ftl loaded so that it will attempt to use the default english terms.
I'll be adding a new term to a page to test and make sure it doesn't show in the translations and deploy a demo.
> Add a fallback to the en version of a brand term for Fluent strings

- bedrock/firefox/urls.py
This reverts commit 7013fd755fd030313f0af8ae78daf7307996e802 thus publishing the browser comparison pages.
The pages should load normally when `DEV=False`
> Revert "Only show browser comparison pages in DEV mode"

- bedrock/exp/templates/exp/firefox/accounts.html
The new firefox/accounts experiment template is extending the wrong base & is missing the convert JS required to run experiments on it. (ex: `https://cdn-3.convertexperiments.com/`)
> exp/firefox/accounts base bugfix. [no bug]

- bedrock/firefox/templates/firefox/products/index.html
- bedrock/firefox/urls.py
- l10n/en/firefox/products.ftl
- lib/fluent_migrations/firefox/products/index.py
- Migrates `firefox/products.lang` to `firefox/products.ftl`
- Updates template to use new Fluent IDs.
#9001
```
```
> Port firefox/products page to Fluent (Fixes #9001)

- bedrock/firefox/templates/firefox/privacy/base.html
- bedrock/firefox/templates/firefox/privacy/includes/subnav.html
- bedrock/firefox/templates/firefox/privacy/index.html
- bedrock/firefox/templates/firefox/privacy/products.html
- bedrock/firefox/urls.py
- l10n/en/firefox/privacy-hub.ftl
- lib/fluent_migrations/firefox/privacy.py
- Migrates `firefox/privacy-hub.lang` to `firefox/privacy-hub.ftl`
- Updates privacy hub pages to use Fluent IDs:
- http://localhost:8000/en-US/firefox/privacy/
- http://localhost:8000/en-US/firefox/privacy/products/
#9006
```
```
> Migrate firefox/privacy pages to Fluent (Fixes #9006)

- bedrock/base/templates/includes/protocol/footer/firefox.html
- bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
- bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
- bedrock/base/templates/includes/structured-data/software/firefox-lockwise-software.json
- bedrock/exp/templates/exp/firefox/accounts.html
- bedrock/exp/templates/exp/firefox/index.html
- bedrock/firefox/templates/firefox/accounts.html
- bedrock/firefox/templates/firefox/browsers/compare/brave.html
- bedrock/firefox/templates/firefox/browsers/compare/ie.html
- bedrock/firefox/templates/firefox/browsers/compare/safari.html
- bedrock/firefox/templates/firefox/features/safebrowser.html
- bedrock/firefox/templates/firefox/home/index-master.html
- bedrock/firefox/templates/firefox/privacy/products.html
- bedrock/firefox/templates/firefox/products/index.html
- bedrock/firefox/templates/firefox/products/lockwise.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
- bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
- bedrock/firefox/urls.py
- bedrock/foundation/templates/foundation/annualreport/2018/index.html
- l10n/en/firefox/products/lockwise.ftl
- lib/fluent_migrations/firefox/lockwise/lockwise.py
- Migrates `firefox/products/lockwise.lang` to `firefox/products/lockwise.ftl`
- Moves template from `firefox/lockwise/lockwise.html` to `firefox/products/lockwise.html`
- Updates template to use Fluent Ids.
#9016
```
```
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/155643331
> Migrate /firefox/lockwise to Fluent (Fixes #9016)

- bedrock/firefox/templates/firefox/channel/base.html
Removes the stray list item bullet point around the [picto card](https://protocol.mozilla.org/patterns/molecules/picto-card.html) in  [Firefox Channel page](https://www.mozilla.org/en-US/firefox/channel/desktop/).
**Safari:**
**Chrome:**
#8501 
1. `make build`
2. `make run`
3. Visit http://localhost:8000/en-US/firefox/channel/desktop/
4. Bullet point is gone 👋
> fix #8501: (firefox/channel) change picto card base element from 'li' to 'section'

- bedrock/firefox/templates/firefox/welcome/base.html
- bedrock/firefox/templates/firefox/welcome/page1.html
- bedrock/firefox/tests/test_views.py
- bedrock/firefox/views.py
- l10n/en/firefox/welcome/page1.ftl
- lib/fluent_migrations/firefox/welcome/page1.py
- Migrates `firefox/welcome/page1.lang` to `firefox/welcome/page1.ftl`.
http://localhost:8000/en-US/firefox/welcome/1/
https://github.com/mozilla/bedrock/issues/9034
```
```
> Migrate firefox/welcome/1/ to Fluent (Fixes #9034)

- bedrock/firefox/templates/firefox/retention/thank-you.html
Regression from https://github.com/mozilla/bedrock/pull/9027
Issue: https://github.com/mozilla/bedrock/issues/9087
> Fix URL mismatch on /firefox/retention/thank-you/ (Fixes #9087)

- bedrock/firefox/views.py
Adds link to desktop redesign variation.
Fix #9090
http://localhost:8000/en-US/firefox/new/?xv=desktop
> Add link to desktop redesign experience Fix #9090

- bedrock/firefox/templates/firefox/browsers/index.html
- Adds missing link params to copy at the end of the FxA form on /browsers.
http://localhost:8000/en-US/firefox/browsers/
#9073
> Add missing links to FxA form on /browsers (Fixes #9073)

- bedrock/mozorg/templates/mozorg/home/home.html
- media/css/mozorg/home/home.scss
The two column "Impact and Innovations" section can collide with floats in the picto card section below when they're not the same height. This adds a clearfix to the column container to prevent that.
The bug was filed by a localizer working on the Taiwanese version but it likely happens in other locales as well.
https://bugzilla.mozilla.org/show_bug.cgi?id=1640569
http://localhost:8000/zh-TW/
The row of picto cards should line up correctly because the two columns above them are now contained.
> [fix bug #1640569] home page, clear floats in the two column section

- bedrock/firefox/templates/firefox/features/index.html
The compare pages are back online and we can add the link again, so removing the comment: https://github.com/mozilla/bedrock/issues/9103
> Add compare link

- l10n/configs/special-templates.toml
> Exclude id locale from /whatsnew pages in Fluent config (Fixes #9100)

- bedrock/firefox/firefox_details.py
- bedrock/firefox/templates/firefox/all-unified.html
- bedrock/firefox/tests/test_base.py
- bedrock/firefox/tests/test_helpers.py
- l10n/en/firefox/all.ftl
- media/css/pebbles/components/_buttons-download.scss
- media/css/protocol/components/_download-button.scss
- Add Windows ARM64/AArch64 builds to /firefox/all/ and (/firefox/new/ modal).
http://127.0.0.1:8000/en-US/firefox/all/
http://127.0.0.1:8000/en-US/firefox/new/
#8929
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/163494753
> Add Windows ARM64/AArch64 builds to /firefox/all/ (Fixes #8929)

- bedrock/firefox/templates/firefox/welcome/base.html
- bedrock/firefox/templates/firefox/welcome/page2.html
- bedrock/firefox/urls.py
- l10n/en/firefox/welcome/page2.ftl
- lib/fluent_migrations/firefox/welcome/page2.py
- Migrates `firefox/welcome/page2.lang` to `firefox/welcome/page2.ftl`.
http://localhost:8000/en-US/firefox/welcome/2/
#9038
```
```
> Migrate firefox/welcome/2/ to Fluent (Fixes #9034) [skip l10n]

- bedrock/firefox/templates/firefox/welcome/page3.html
- bedrock/firefox/urls.py
- l10n/en/firefox/welcome/page3.ftl
- lib/fluent_migrations/firefox/welcome/page3.py
- Migrates `firefox/welcome/page2.lang` to `firefox/welcome/page2.ftl`.
http://localhost:8000/en-US/firefox/welcome/3/
#9043
```
```
> Migrate firefox/welcome/3 to Fluent (Fixes #9043)

- bedrock/firefox/templates/firefox/welcome/page4.html
- bedrock/firefox/urls.py
- l10n/en/firefox/welcome/page4.ftl
- lib/fluent_migrations/firefox/welcome/page4.py
- Migrates `firefox/welcome/page4.lang` to `firefox/welcome/page4.ftl`.
http://localhost:8000/en-US/firefox/welcome/4/
#9054
```
```
> Migrate firefox/welcome/4/ to Fluent (Fixes #9054) [skip l10n]

- bedrock/firefox/templates/firefox/welcome/page5.html
- bedrock/firefox/urls.py
- l10n/en/firefox/welcome/page5.ftl
- lib/fluent_migrations/firefox/welcome/page5.py
- Migrates `firefox/welcome/page5.lang` to `firefox/welcome/page5.ftl`.
http://localhost:8000/en-US/firefox/welcome/5/
#9069
```
```
> Migrate firefox/welcome/5/ to Fluent (Fixes #9069) [skip l10n]

- bedrock/firefox/templates/firefox/welcome/page6.html
- bedrock/firefox/urls.py
- l10n/en/firefox/welcome/page6.ftl
- lib/fluent_migrations/firefox/welcome/page6.py
- Migrates `firefox/welcome/page6.lang` to `firefox/welcome/page6.ftl`.
http://localhost:8000/en-US/firefox/welcome/6/
#9080
```
```
> Migrate /firefox/welcome/6/ to Fluent (Fixes #9080) [skip l10n]

- bedrock/firefox/templates/firefox/welcome/page8.html
- bedrock/firefox/urls.py
- l10n/en/firefox/welcome/page8.ftl
Note: this is still a new page so there's no existing translations to migrate.
http://127.0.0.1:8000/en-US/firefox/welcome/8/
#8927
> Migrate /firefox/welcome/8/ to Fluent (Fixes #8927)

- bedrock/firefox/templates/firefox/welcome/page7.html
- bedrock/firefox/urls.py
- l10n/en/firefox/welcome/page7.ftl
- lib/fluent_migrations/firefox/welcome/page7.py
- Migrates `firefox/welcome/page7.lang` to `firefox/welcome/page7.ftl`.
http://localhost:8000/en-US/firefox/welcome/7/
#9083
```
```
> Migrate /firefox/welcome/7/ to Fluent (Fixes #9083) [skip l10n]

- bedrock/settings/base.py
Chrome throws the CSP error for failing to have the domain in the `frame-src` directive.
#9112 
Adding `localhost:8080` into the `CSP_FRAME_SRC` list locally fixes the error.
> Update CSP_FRAME_SRC with the domain pointing to object.data URL.
