mozilla/bedrock

jenkins/branches/master.yml, jenkins/branches/prod.yml, jenkins/branches/stage.yml
For https://github.com/mozmeao/infra/issues/981#issuecomment-454633922
=> Remove oregon-b from dev, stage, & prod deployments

bin/deploy.sh
update image in {clock-,}deploy.yaml in bin/deploy.sh
mozmeao/infra#1010
Merge this to master, verify clock-deploy.yaml is updated in the git-sync-operator branch of mozmeao/www-config
=> Update clock deploy image to fix mozmeao/infra#1010

bedrock/redirects/redirects.py, tests/redirects/map_301.py
=> Redirect projects/browsers.html to /new/ (Fixes #6474)

bedrock/firefox/templates/firefox/organizations/organizations.html
we move to a different schedule
=> 12 weeks => at least 12 weeks

bedrock/mozorg/templates/mozorg/about/leadership.html
Bio is live, switch no longer needed. Once this makes it to prod I'll clean up the switch in www-config.
=> [bug 1520905] Remove Higgins switch from leadership page

tests/functional/conftest.py
fix issue seen in https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1482/pipeline
=> Replace get_marker with get_closest_marker for new pytest compat

Makefile
* `make fresh-data` will fetch the latest DB file and update the data from all external sources
* `make shell` will open a bash shell on the running app
* `make djshell` will open the Django shell on the running app
=> Add fresh-data and shell make commands

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/sprint_task.md
- Adds new bug reporting issue template.
- I decided to call the existing template "Sprint task" as opposed to "Feature request", as not all issues are for feature work. Open to other suggestions though?
=> Add bug reporting issue template (Fixes #6804)

bedrock/mozorg/templates/mozorg/home/home-en.html, bedrock/mozorg/views.py
- Updates home page card layout
- Card content has already been updated in the admin 🎉 
#6785
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/
To test locally:
- Make sure your master branch is up to date
- Run `make fresh-data` to pull in the latest from the db.
- New homepage content should be displayed that matches what's on demo.
=> Update home page card layout (en) (Fixes #6785)

bedrock/privacy/templates/privacy/index.html
Add email address and Data Subject Access Requests links in contact section of privacy policy.
#6820
=> Add privacy policy email address (Fixes #6820)

bedrock/firefox/views.py
Remove references to missing templates.
#6833
=> Remove reference to missing template. Fix #6833

bedrock/firefox/templates/firefox/windows-64-bit.html
Update title and description of /windows-64-bit/ so it matches the search intent better
=> Update title and description of /windows-64-bit/

bedrock/firefox/templates/firefox/home.html
Add missing brace to video tag.
=> Add missing brace

bin/slack-notify.sh, contribute.json, docs/pipeline.rst, docs/testing.rst
https://github.com/mozmeao/infra/issues/1043
=> update jenkins urls to use VPN

bedrock/mozorg/templates/mozorg/contact/communities/north-america/canada.html, bedrock/mozorg/templates/mozorg/contact/spaces/toronto.html, bedrock/mozorg/templates/mozorg/contact/spaces/vancouver.html
Remove dead links to mozillacanada.org
Fix mozilla/bedrock#6897
=> Remove mozillacanada.org references

media/css/protocol/components/_navigation.scss
=> [#6887] Hide global FxA button from mobile platforms

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
Updating fxa CTA strings for an l10n bugfix
https://github.com/mozilla-l10n/www.mozilla.org/issues/281
=> Update WNP66 'sign in' strings for l10n

bedrock/firefox/templates/firefox/home/index.de.html, bedrock/firefox/templates/firefox/home/index.fr.html, bedrock/firefox/templates/firefox/home/index.html
=> Fix privacy link on /firefox email form

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
=> Format l10 fxa_link_fragment for WNP66

bedrock/mozorg/templates/mozorg/about/leadership.html
Update Alan Davidson's bio with new copy.
#6968
Is staged correctly for l10n.
=> Update Alan Davidson's bio. (Fixes #6968)

bedrock/firefox/templates/firefox/new/scene1.html
=> Add l10n comment to string on /new (Fixes #6973)

docs/l10n.rst
=> Fix pathname in l10n docs

lib/l10n_utils/gettext.py, lib/l10n_utils/tests/test_files/locale/templates/LC_MESSAGES/messages.pot
=> Fix long template l10n comments being truncated

CODE_OF_CONDUCT.md
=> Update code of conduct (Fixes #6999)

docs/l10n.rst
Adds link to bedrock docs for l10n extraction workflow.
=> Add link to mozilla.org l10n workflow documentation

jenkins/branches/master.yml, jenkins/branches/prod.yml, jenkins/branches/stage.yml
=> Temporarily skip download link tests for stage and prod (#7015)

bedrock/mozorg/templates/mozorg/what-is-a-browser.html
- Marking as a P2, since this is blocking https://github.com/mozilla/bedrock/issues/7059
#7032
=> Punctuation fixes for technology/what-is-a-browser (Fixes #7032)

bedrock/settings/base.py
Re https://github.com/mozmeao/www-admin/pull/18
=> Update content-cards default git branch for dev

media/js/firefox/new/newsletter/experiment.js
=> Adjust pre-donwload experiment percentages (Fixes #7096)

bedrock/mozorg/templates/mozorg/what-is-a-browser.html
- Add l10n comments.
- Remove superfluous lang file declaration.
#7059
=> Localize /technology/what-is-a-browser/ (#7059)

bedrock/mozorg/templates/mozorg/about-2019.html, bedrock/mozorg/templates/mozorg/perf-exp/control.html, bedrock/mozorg/templates/mozorg/perf-exp/variation.html, bedrock/mozorg/tests/test_views.py, bedrock/mozorg/views.py, media/css/mozorg/perf-exp/index.scss, media/js/mozorg/perf-exp/control.js, media/js/mozorg/perf-exp/experiment.js, media/js/mozorg/perf-exp/variation.js, media/static-bundles.json, tests/functional/test_about.py
- Adds an experiment on /about/ that aims to test the effects of hero rendering performance against bounce rate and conversions.
#7118
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/about/
=> Experiment: page hero rendering performance (Fixes #7118)

tests/functional/test_download_l10n.py
Some locales have stopped being built but product-details has not yet been updated. This is a followup to #7199.
=> Bug 1552228: Temporarily skip devedition download tests

bedrock/redirects/redirects.py, tests/redirects/map_301.py
It is mentioned in a file in Firefox.
Fix bug 1551914
=> Add redirect for /unix/customizing.html

bedrock/newsletter/templates/newsletter/existing.html, bedrock/newsletter/templates/newsletter/fxa-error.html, bedrock/newsletter/tests/test_views.py, bedrock/newsletter/urls.py, bedrock/newsletter/views.py, bedrock/settings/base.py, media/css/newsletter/newsletter.less
Proposed changes for the email preferences center for trailhead. Going to look over the strings one more time before calling for extraction for l10n.
Fix #7178
=> Trailhead email pref updates

bedrock/newsletter/templates/newsletter/existing.html, media/css/newsletter/newsletter.less
Just a few small tweaks to make it look less off-brand.
#7225
=> [fix #7225] Style updates for newsletter prefs

bedrock/firefox/templates/firefox/accounts-2019.html, bedrock/firefox/views.py
=> Use French blog post for French accounts page

media/css/firefox/campaign/download.scss
* Remove reference to deleted image
* Remove redundant CSS
=> Fixes for campaign/download.scss

bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
=> Update newsletter ID on /contribute (Fixes #7305)

bedrock/mozorg/templates/mozorg/home/home-fr.html, bedrock/mozorg/tests/test_views.py, bedrock/mozorg/views.py, tests/functional/test_home.py
Add content card based French homepage.
See #7282.
https://bedrock-demo-6.oregon-b.moz.works/fr/
=> Add French homepage template (#7282)

docs/abtest.rst, docs/stub-attribution.rst
Link A/B Testing to experiments section of Stub Attribution
Fix #7332
=> Link A/B Testing to experiments section of Stub Attribution (#7332)

bedrock/firefox/templates/firefox/campaign/index-trailhead.html
Peiying caught this error in https://github.com/mozilla-l10n/www.mozilla.org/pull/303
=> [no bug] Campaign page, lowercase “web”

media/css/firefox/features/adblocker.scss, media/css/mozorg/what-is-a-browser.scss, package.json, yarn.lock
Update protocol to the latest & greatest. 🙂
=> Upgrade protocol to 7.0.1

media/js/mozorg/perf-exp/control.js, media/js/mozorg/perf-exp/experiment.js, media/js/mozorg/perf-exp/variation.js
Run the same experiment from #7118 but for mobile visitors only.
#7118
=> Run hero rendering experiment for mobile users (#7118)

tests/pages/regions/join_firefox_form.py
Fixes https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/stage/91/pipeline/
=> Fix failing functional test for /firefox/accounts/

bedrock/firefox/templates/firefox/features/adblocker.html
There were some copy change requests on the extracted strings in the l10n PR so I am updating this template to match.
l10n PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/321/
=> Update firefox/features/adblocker copy for l10n

docs/install.rst
- Updates legal-docs submodule.
- Adds steps for doing this to the bedrock docs.
#5614
=> Update legal docs (#5614)

README.md
Added link to license file in the README. I haven't contributed to open source before so let me know if I did something wrong. Thanks!
(mozilla#7360)
=> Add relative link to license file (mozilla#7360)

media/js/firefox/all/all-downloads-unified.js, tests/unit/spec/firefox/all/all-downloads-unified.js
- Enables each product on `/firefox/all/` to be preselected via a hash identifier in the page URL.
#7208
Demo links:
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/#product-desktop-release
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/#product-desktop-beta
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/#product-desktop-developer
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/#product-desktop-nightly
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/#product-desktop-esr
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/#product-android-release
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/#product-android-beta
- …
=> Add deep linking to /firefox/all/ (Fixes #7208)

bedrock/base/templates/macros.html, media/css/protocol/base/send-to-device.scss
Protocol based styles for the send to device widget.
These were tested and okay as part of #7006, but those changes are unlikely to make it into production. This bit is useful so I'm pulling it out so others can use it.
n/a
Was tested as part of #7006 so it's probably okay. You can pull that branch down and test there if you want.
=> Protocol based styles for the send to device widget

bedrock/firefox/templates/firefox/switch.html
String update. Not extracted yet so should be okay to re-use the old tag.
See #7608
=> Update string on /switch (#7608)

bedrock/firefox/templates/firefox/developer/index.html, bedrock/firefox/templates/firefox/developer/whatsnew.html
=> Fix dev edition wordmark image paths

bedrock/firefox/templates/firefox/enterprise/index.html
Copy updated to remove "24/7" from our support discription
#7683
=> Copy update for enterprise [Fixes #7683]

media/css/firefox/mobile.scss
Additional icon partly displaying on https://www.mozilla.org/en-US/firefox/mobile/#focus-privacy #6484
=> Additional icon partly displaying on https://www.mozilla.org/en-US/firefox/mobile/#focus-privacy #6484

bedrock/legal/templates/legal/impressum.html
- Updates `/de/about/legal/impressum/` page.
#7630
=> Update the Impressum page (Fixes #7630)

bedrock/legal/redirects.py
=> Updated redirects.py

media/css/mozorg/leadership.scss
Forgot to update the second reference to a deleted image in #7813
=> Leadership - fix reference to missing image

bedrock/privacy/views.py
fixed beautifulSoup Error warning
#7798
=> "No parser was explicitly specified" warning Fixed

media/js/base/core-datalayer-page-id.js, media/js/base/core-datalayer.js, media/js/base/mozilla-client.js, media/js/base/mozilla-cookie-helper.js, media/js/base/mozilla-traffic-cop-funnelcake-geo.js, media/js/base/stub-attribution-macos.js, media/js/firefox/concerts.js, media/js/firefox/tracking-protection-tour.js, media/js/firefox/whatsnew/experiment-whatsnew-68-de.js, media/js/firefox/whatsnew/experiment-whatsnew-68-enCA.js, media/js/firefox/whatsnew/experiment-whatsnew-68-enGB.js, media/js/firefox/whatsnew/experiment-whatsnew-68-enUS.js, media/js/firefox/whatsnew/experiment-whatsnew-68-fr.js
Fix eslint 'no-useless-escape' errors. (#7747) #7752
=> Fix eslint 'no-useless-escape' errors. (#7747) #7752

bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
- Update link
Fix #7883
- click link
=> Update join link (Fix #7883)

bedrock/base/templates/includes/protocol/footer/firefox-new.html, bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html, bedrock/firefox/templates/firefox/accounts-2019.html, bedrock/firefox/templates/firefox/features/safebrowser.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-b.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html, bedrock/mozorg/templates/mozorg/home/includes/structured-data.json
Updates links for lockwise across bedrock
#7628
Make sure links actually work.
=> Lockwise link updates [Fixes #7628]

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
Added a redirect from /enterprise to /firefox/enterprise
#7842
=> Redirect from /enterprise to /firefox/enterprise

bedrock/settings/base.py
No data is flowing to datadog from bedrock instances. This implements the basket setup of statsd which is working. We'll need to set the statsd client in settings to `django_statsd.clients.normal`.
=> Fix statsd for bedrock

bedrock/firefox/templates/firefox/lockwise/lockwise.html
=> Correct url for lockwise og image (#7938)

bedrock/base/templates/macros-protocol.html, bedrock/firefox/templates/firefox/pocket.html, bedrock/mozorg/templates/mozorg/about.html, bedrock/mozorg/templates/mozorg/developer/index.html, bedrock/mozorg/templates/mozorg/home/home-en.html, bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py
=> Update lazy_img and card helpers to not assume the img directory

bedrock/firefox/templates/firefox/unsupported-systems.html, media/css/firefox/unsupported-systems.scss
=> Added Emp Box

bedrock/firefox/templates/firefox/welcome/page1.html, media/css/firefox/welcome.scss
Updates the link text (and the layout).
#7984
=> [fix #7984] Update welcome 1 survey link

bedrock/exp/templates/exp/firefox/lockwise.de.html, bedrock/exp/templates/exp/firefox/lockwise.html, bedrock/exp/urls.py, media/css/exp/firefox/lockwise.scss, media/js/exp/firefox/lockwise.js, media/static-bundles.json
Adds Lockwise page to CRO sandbox, both English and German
#7867
=> [fix #7867] Add Lockwise page to CRO sandbox

bedrock/firefox/templates/firefox/whatsnew/index-lite.id.html, bedrock/settings/base.py, media/css/firefox/whatsnew/whatsnew-lite.scss
- Less padding at the top of the page for desktop viewports.
- Copy fix
- Fix for SMS bug
#7991
#6732
=> WNP updates for Indonesia (Fixes #7991, #6732)

bedrock/foundation/templates/foundation/moco.html, bedrock/mozorg/templates/mozorg/about/leadership.html
- Remove C Beard from MoCo board
- Move B Lisbonne from MoFo to MoCo
http://localhost:8000/en-US/about/leadership/#directors
http://localhost:8000/en-US/foundation/moco/
=> [no bug] Update board membership

bedrock/base/templates/includes/protocol/navigation/menu-mozilla/developers.html
Fixes: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1974/pipeline/
Ref: https://github.com/mozilla/bedrock/commit/f5848b4497d311dea4a0a027f9a511c6d0ebdeda
=> Fix broken nav menu image

media/css/firefox/whatsnew/whatsnew-lite.scss
Fixes: https://github.com/mozilla/bedrock/pull/7992#issuecomment-546095048
=> Fix background position on Firefox Lite /whatsnew page (#7991)

docs/abtest.rst
- Updates docs for using both Convert and Traffic Cop.
#7906
=> Update A/B testing docs for Convert (Fixes #7906)

docker-compose.yml
Temporarily disable locale volume mount
#8051
`make test` on Docker for Mac passes with these changes
=> Disable locale volume mount in test container

media/css/firefox/home/master.scss
Responsive styles bug on product list in bottom /firefox CTA
Fixes #8007
=> Fixed Responsive styles bug on product list

bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx70.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
Add parameters to WNP70 for changed headline
=> Add parameters to WNP70 for changed headline

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
=> Fix bug with wnp params

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
Add new sites to the web bug bounty program.
n/a
n/a
- @april 
- @moz-jvehent 
- @claudijd
=> Updated bug bounty sites

docs/contribute.rst
This PR updates the URLs for the on-demand demo servers for bedrock.
=> Update URLs of the on-demand demo servers

package.json, yarn.lock
=> Update Protocol to 10.0.1

bedrock/security/templates/security/web-bug-bounty.html
Doubled all of the web bug bounty payments and more than quadrupled the critical site RCEs.
N/A
N/A
- @moz-jvehent 
- @april 
- @claudijd
=> Updated web bug bounty payments

media/css/firefox/whatsnew/whatsnew.scss
Default whatsnew page top banner is solid white
Fixes #8108
=> Change default whats new page banner

bedrock/newsletter/templates/newsletter/existing.html, media/css/newsletter/newsletter.less
- Make the form less confusing.
- Fix page layout on small screens.
#8112
=> Make newsletter subscription changes less confusing (Fixes #8112)

bedrock/firefox/templates/firefox/home/index-master.html, tests/functional/firefox/test_home.py, tests/pages/firefox/home.py, tests/pages/regions/menu_list.py
- Test FB Container link only displays in firefox
- Test Menu List opens
- Add Menu List region
Fix #7898 
🏃‍♀ https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/446/pipeline/
=> Add integration tests for new /firefox (#7898)

bedrock/foundation/templates/foundation/trademarks/distribution-policy.html, bedrock/foundation/templates/foundation/trademarks/policy.html, media/css/protocol/basic-article.scss
Fixing errors and typos in the trademark pages
None - reported via email
changes to:
foundation/trademarks/distribution-policy/
foundation/trademarks/policy/
Demo needs to be approved by Daniel Nazer:  https://www-demo3.allizom.org
=> Trademark fixes

bedrock/privacy/redirects.py, tests/redirects/map_globalconf.py
=> Updated Redirects.py 

bedrock/legal/templates/legal/terms/firefox-private-network.html, bedrock/privacy/templates/privacy/notices/firefox-private-network.html, media/css/legal/legal.scss
Replaces https://github.com/mozilla/bedrock-private/pull/81
mozilla/bedrock#7850
https://bugzilla.mozilla.org/show_bug.cgi?id=1575696
=> Update FPN privacy notice and terms of service. (Fixes #7850)

bedrock/firefox/templates/firefox/developer/includes/for-developers.html
=> Fix broken css engine link

media/css/newsletter/newsletter-opt-out-confirmation.scss
=> Fix Social link

bin/run-prod.sh, wsgi/app.py
Instead of importing newrelic in the wsgi file.
Fix #7372
=> Use newrelic-admin in run-prod.sh

bedrock/firefox/templates/firefox/nightly_whatsnew.html
Minor updates to the what's new page
Issue #8252 
* The IRC paragraph should be removed
* The sentence "Every 6 to 8 weeks…" should now be "Every 4 to 5 weeks…"
=> Issue #8252: Update text on Nightly What's New page

bedrock/security/templates/security/bug-bounty.html
Per Michael Feldman, add Crimea to sanctioned countries.
=> Update sanction countries

docs/architecture/decisions/0004-use-fluent-for-localization.md
=> Add ADR for Fluent L10n system

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx72.html, bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py
Create whatsnew-72 page
Link to page on demo: https://www-demo-whats-new-72-yeyfvjkm.herokuapp.com/en-US/firefox/72.0/whatsnew/all/
#8331
=> create whatsnew-72 [Fixes: #8331]

bedrock/styleguide/templates/styleguide/index.html, media/css/styleguide/styleguide.scss
Ports /styleguide/ from Pebbles to Protocol.
=> [no bug] Port style guide to Protocol.

docs/pipeline.rst
Follow up from #8222 where the Jenkins pipeline files were removed.
=> Remove Jenkins pipeline docs

bedrock/mozorg/templates/mozorg/contact/spaces/berlin.html, bedrock/mozorg/templates/mozorg/contact/spaces/mountain-view.html, bedrock/mozorg/templates/mozorg/contact/spaces/portland.html, bedrock/mozorg/templates/mozorg/contact/spaces/san-francisco.html, bedrock/mozorg/templates/mozorg/contact/spaces/taipei.html, bedrock/mozorg/templates/mozorg/contact/spaces/toronto.html, bedrock/mozorg/templates/mozorg/contact/spaces/vancouver.html
added listings filtered by location
Fixes #8121
=> Linked back to careers listings on /contact/spaces/

docs/l10n.rst
=> Document Fluent file configuration (Fixes #8335)

root_files/.well-known/matrix/server
=> Add .well-known/matrix/server URL

bedrock/settings/base.py, root_files/.well-known/matrix/client
Like #8411 added the server file.
Fix #8414
=> Add .well-known/matrix/client

media/css/mozorg/technology.scss, media/js/mozorg/technology.js, media/static-bundles.json
Removes old .less based modal styles.
N/A
=> Use Protocol modal on /technology/

media/js/base/stub-attribution.js, tests/unit/spec/base/stub-attribution.js
See: https://github.com/mozilla/bedrock/pull/8483#discussion_r375642035
=> Remove Opera from stub attribution UA detection (#8405)

bedrock/firefox/templates/firefox/browsers/index.html, bedrock/firefox/templates/firefox/products/index.html
Markup bugfix per feedback in l10n repo - https://github.com/mozilla-l10n/www.mozilla.org/pull/366#pullrequestreview-354791031
=> l10n bugfix on firefox/products & firefox/browsers. [no bug]

bedrock/privacy/templates/privacy/base-protocol.html
=> Add metadata for description

lib/l10n_utils/management/commands/process_ftl.py
=> Include the TOML configs when updating the Fluent repo

bedrock/firefox/redirects.py, tests/redirects/map_globalconf.py
=> Redirect /firefox/xr/ to SUMO article

bedrock/firefox/templates/firefox/switch.html, bedrock/firefox/urls.py, docs/fluent-conversion.rst, l10n/configs/pontoon.toml, l10n/configs/vendor.toml, l10n/en/firefox/switch-en.ftl, l10n/en/firefox/switch.ftl, lib/fluent_migrations/firefox/switch.py, lib/l10n_utils/management/commands/_fluent.py, lib/l10n_utils/management/commands/_fluent_activation.py, lib/l10n_utils/management/commands/_fluent_recipe.py, requirements/migration.txt
Migrate /firefox/switch/ to Fluent
#8595
Tested the `en-US` page as well as `de` and `bn`.
Migration to mozmeao/www-l10n is going to be a separate PR onto that repo.
=> Migration and switch

requirements/migration.txt
Fixes https://github.com/mozilla/bedrock/issues/8607
=> Update compare-locales to 7.6.0 (Fixes #8607)

bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
Fixes https://github.com/mozilla/bedrock/issues/8621
=> Add missing url in enterprise > offer

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
=> Add redirect for /builders

.github/ISSUE_TEMPLATE/experiment.md
Add experiment template to issue templates.
=> Add experiment GitHub template.

bedrock/firefox/templates/firefox/mobile/index.html
=> Added empty alt attributes to images

bedrock/firefox/templates/firefox/welcome/page6.html, bedrock/firefox/urls.py, media/css/firefox/welcome.scss
Add moments page 6
#8569
http://localhost:8000/en-US/firefox/welcome/6/
=> Moments 6 [fixes 8569]

bedrock/base/templates/includes/protocol/footer/firefox.html, bedrock/base/templates/includes/protocol/footer/mozilla.html
Fixes https://github.com/mozilla/bedrock/issues/8707
=> Fix moco and mofo footer links (Fixes #8707)

bedrock/mozorg/templates/mozorg/about/leadership.html
This needs to be live on or before April 7 (Tuesday).
- Update Dana’s title
- Add Dana and MEM to steering committee
- Update order
#8735
=> [fix #8735] Leadership updates

bedrock/mozorg/templates/mozorg/about/leadership.html
Updates Mitchell's bio and title
#8758
=> Mitchell bio update [Fixes: #8758]

bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.html
https://github.com/mozilla/bedrock/issues/8736
=> Fix broken link to adjust

bedrock/mozorg/templates/mozorg/about/leadership.html
#8792 
Needs to be live Monday, 20 April
=> [fix #8792] Update Mitchell’s bio on leadership page

lib/fluent_migrations/includes/protocol/navigation/navigation.py
=> Remove duplicate Fluent ID from navigation.ftl

bedrock/settings/base.py
=> Add metrics.convertexperiments.com to CSP_CONNECT_SRC (Issue #8773)

docs/fluent-conversion.rst, docs/l10n.rst
=> Update Fluent documentation for automation processes (Fixes #8826)

bin/run-tests.sh
Fixes https://github.com/mozilla/bedrock/issues/8846
=> Lint .ftl files using moz-l10n-lint (Fixes #8846)

bedrock/base/templates/includes/protocol/footer/firefox.html, bedrock/base/templates/includes/protocol/navigation/menu-firefox/browsers.html, bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html, bedrock/firefox/templates/firefox/home/index-master.html
Translation status for the browsers and products pages is high enough to add them to the nav outside of en-US now.
Fix #8298
Check links in global nav in non-en.
=> Link to browsers and products pages for all locales #8298

docs/l10n.rst
@pmac r? not urgent, just a small addition to the docs.
=> Add Fluent documentation on using brand names

.gitlab-ci.yml
Merge https://github.com/mozmeao/www-config/pull/264 first
=> Switch to new Gitlab runners

.gitlab-ci.yml
This reverts commit 88aeafd4d87c5a5c1a2a0731c571bf4de2c54695.
=> Revert "Switch to new Gitlab runners"

media/css/exp/home/home-2018.scss, media/css/mozorg/home/home-2018.scss
Fixes https://gitlab.com/mozmeao/www-config/-/jobs/537668386
=> Fix navigation visibility in IE when home banner is off

.gitlab-ci.yml, bin/upload-staticfiles.sh
- This reverts commit 82e6ffd283fed928afacb11075312effb3174b5b.
- Also remove --profile from s3 sync.
----
#
=> Switch to new Gitlab runners, take two.

bedrock/firefox/templates/firefox/welcome/page7.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx74.html
- http://localhost:8000/fr/firefox/welcome/7/
- http://localhost:8000/fr/firefox/74.0/whatsnew/all/
#8746
=> Fix typos in French hard-coded /welcome /whatsnew pages (Fixes #8746)

tests/functional/firefox/test_facebook_container.py, tests/pages/firefox/facebook_container.py
Add functional tests for Facebook Container page
#8588
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/142794966
=> Add functional tests for Facebook Container page (Fixes #8588)

tests/functional/firefox/test_campaign.py, tests/pages/firefox/campaign.py
Add functional test for firefox/campaign/ page
#8631
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/142740830
=> Add functional test for firefox/campaign/ page (Fixes #8631)

bedrock/firefox/templates/firefox/welcome/page8.html, bedrock/firefox/urls.py, media/css/firefox/welcome.scss, media/js/firefox/welcome/welcome8.js, media/static-bundles.json
Adds welcome page 8
https://github.com/mozilla/bedrock/issues/8839
=> welcome 8 [Fixes: #8839]

bedrock/mozorg/templates/mozorg/about/leadership.html
=> [no bug] Leadership, correction to Seligman’s bio

bedrock/base/middleware.py, bedrock/settings/base.py, tests/redirects/test_urls.py
=> Remove the x-robots-tag header from responses

tests/functional/firefox/test_firstrun.py, tests/pages/firefox/firstrun.py
Add functional test for legacy /firstrun page
#8890
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/143623610
=> Add functional test for legacy /firstrun page (Fixes #8890)

tests/functional/test_manifesto.py, tests/pages/manifesto.py
Add functional test for Manifesto page
#8589
https://gitlab.com/mozmeao/www-config/pipelines/144712537
=> Add functional test for Manifesto page (Fixes #8589)

bedrock/mozorg/templates/mozorg/about/leadership.html
Hi folks! 👋 
I believe there's a minor grammar issue in Adam's leadership bio. Please let me know if you'd like me to make any changes to my pull-request.
=> Improve grammar in leadership bio

bedrock/mozorg/redirects.py, tests/redirects/map_globalconf.py
=> Update /builders redirect to include UTM params

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2019.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2019.html, bedrock/mozorg/urls.py
URL: http://localhost:8000/en-US/about/policy/transparency/jul-dec-2019/
https://github.com/mozilla/bedrock/issues/8870
=> Add H2 2019 Transparency Report (Fixes #8870)

bedrock/base/templates/cron-health-check.html, bedrock/base/views.py
* Add the FLuent repo to the stats
* Only show the most recently update repo for a repo name
Fix #8940
=> Update the /healthz-cron page

bedrock/base/templates/includes/protocol/footer/firefox.html, l10n/en/footer.ftl
Add link to Firefox Support in Firefox footer
Fix #8935
=> Add link to Firefox Support in Firefox footer #8935

bedrock/releasenotes/models.py, requirements/base.txt
Also upgrade bleach to 0.5.1
Fix #8957
=> Sanitize release notes markdown using bleach

bedrock/mozorg/templates/mozorg/about/manifesto.html
Fixes 404 link on /manifesto page
#8991
=> Update link to resource (Fixes #8991)

.github/CONTRIBUTING.md, README.md
=> Update CONTRIBUTING.md with good-first-bug links (Fixes #8992)

bedrock/firefox/templates/firefox/welcome/page6.html
Fixes: https://github.com/mozilla/bedrock/issues/8875
=> Added firefox logo to welcome page 6 modal

docs/index.rst
=> updated index.rst

bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/firefox/templates/firefox/new/trailhead/download.html, bedrock/firefox/tests/test_views.py, bedrock/firefox/views.py, media/js/firefox/new/desktop/exp.js, media/static-bundles.json
Traffic cop for /new redesign experiment. 
[Experiment plan.](https://docs.google.com/document/d/1d8i1pjejFPmiz60odkwdZjWPgiEgCE8Q1gt9Ifyg3jU/edit#heading=h.i4bqf6o9zs3g) (Link available to employees only.)
https://github.com/mozilla/bedrock/issues/9019
=> Traffic cop for /new redesign experiment

docs/fluent-conversion.rst, lib/l10n_utils/management/commands/_fluent_recipe.py
Fix #8612
I ran the following command to test:
```bash
./manage.py fluent recipe bedrock/firefox/templates/firefox/nightly_whatsnew.html
```
=> Add brand term detection and replacement to fluent recipe migration script

bedrock/settings/appstores.py
Full context: https://docs.google.com/document/d/1lG6q7C94xk3ihJKQWTuMeN_lLXpKtg-oC43pj0CwZkw/edit
https://bugzilla.mozilla.org/show_bug.cgi?id=1649400
=> Bug 1649400 - Change nightly like to point to org.mozilla.fenix

lib/l10n_utils/fluent.py
It was caching the `FluentLocalization` object, but that caused issues in multithreaded environments (like the development server) due to simultaneous attempts at iteration. This change caches loading the Fluent resources which is the expensive work of parsing the files and bundling the results into lists of resources.
Fix #8705
This is a tough one to test since it was a race condition, but I was able to force it to happen locally and now I can't. Perhaps this is one that we should attempt to test locally but only really know if it worked after it merges and the issue stays gone for a long time. I know the issue is the cache as I was able to also reliably fix it by disabling the cache.
=> Improve Fluent translation cache

bedrock/mozorg/templates/mozorg/about/leadership.html
As per email, needs to be live Today (Thurs 9th July).
N/A
=> Update /leadership page

bedrock/mozorg/templates/mozorg/home/home-en.html, media/css/mozorg/home/home-en.scss, tests/functional/test_home.py, tests/pages/home.py
Fixes https://github.com/mozilla/bedrock/issues/9153
=> Update home page functional tests (Fixes #9153)

tests/functional/firefox/browsers/compare/test_browsers.py, tests/functional/firefox/browsers/compare/test_index.py, tests/pages/firefox/browsers/compare.py
Adds base functional tests for comparison index and browser pages.
#8584
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/163411824
=> Add browser comparison page tests (Fixes #8584)

bedrock/firefox/templates/firefox/new/trailhead/thanks-a.html, bedrock/firefox/tests/test_views.py, bedrock/firefox/views.py, media/css/firefox/new/trailhead/exp-thanks.scss, media/static-bundles.json
Custom designed /thanks page to be linked to in a convert experiment.
[Airtable card](https://airtable.com/tblO5zD4uNk7ISyG0/viwIUJsHKDrOFl90B/rec7dWsJPvKgsF1QQ)
**Demo:** https://www-demo5.allizom.org/en-US/firefox/download/thanks/?v=a
=> Switch from chrome /thanks variation. [no bug]

tests/functional/firefox/whatsnew/test_whatsnew.py, tests/functional/firefox/whatsnew/test_whatsnew_id.py, tests/pages/firefox/whatsnew/whatsnew.py, tests/pages/firefox/whatsnew/whatsnew_africa.py, tests/pages/firefox/whatsnew/whatsnew_id.py, tests/pages/firefox/whatsnew/whatsnew_india.py
=> Update Firefox Lite functional tests (Fixes #9119)

bedrock/firefox/templates/firefox/welcome/page8.html
Fixes #9207
r? @craigcook @alexgibson
=> update DE typo

bedrock/firefox/templates/firefox/new/desktop/download.html, l10n/en/brands.ftl, l10n/en/firefox/new/desktop.ftl
Review fixes for /new ftl file
https://github.com/mozilla-l10n/www-l10n/pull/83
No tokens appear on the page.
=> Review fixes for /new ftl file

l10n/en/firefox/new/desktop.ftl
Review fixes for /new ftl file
https://github.com/mozilla-l10n/www-l10n/pull/84
=> Reivew fixes for l10n on /new

bedrock/firefox/templates/firefox/messaging-experiment/control.html
Fixed mixed languages in the mobile promo page
#9147
=> Fixed mixed languages in mobile promo page

bedrock/mozorg/templates/mozorg/about/leadership.html
#9244 
http://localhost:8000/about/leadership/#katharina-borchert
=> Leadership page, update Katherina’s bio [fix #9244]

bedrock/firefox/templates/firefox/mobile/index.html, l10n/en/firefox/mobile.ftl
=> Fix 9215: Remove hyperlink and copy from /mobile.

bedrock/firefox/firefox_details.py, bedrock/firefox/tests/test_firefox_details.py, bedrock/releasenotes/tests/test_base.py
Updated the link to Firexfox nightly
https://github.com/mozilla/bedrock/issues/9225
=> Updated the link to Firexfox nightly

bedrock/mozorg/templates/mozorg/about/leadership.html, media/css/mozorg/leadership.scss
Updates Lindsey Shepard's bio, add a bio for Leslie Gray, narrows the page, and changes to an auto-fit grid instead of floats and clears.
#9306 
#9307
http://localhost:8000/about/leadership/
=> Leadership bio updates and bug fixes [fix #9306]

media/js/privacy/privacy-protocol.js
Open the cookies portion of the website by javascript if it is visited via the cookies link. 
#8354 
Tested on local enviroment in different languages by clicking on "cookies" in the footer.
=> Open cookies portion via cookies link (Fixes #8354)

bedrock/firefox/templates/firefox/channel/desktop.html, l10n/en/firefox/channel.ftl
https://bugzilla.mozilla.org/show_bug.cgi?id=1614106
Closes #9271
=> Explore options for featuring previous Nightly builds on www.mozilla.org 

bedrock/security/templates/security/bug-bounty.html, bedrock/security/templates/security/client-bug-bounty.html
See https://github.com/mozilla/bedrock-private/pull/87 for approvals
=> Add the exploit mitigation bounty

l10n/en-US/firefox/whatsnew/whatsnew-fx81.ftl, l10n/en/firefox/whatsnew/whatsnew-fx81.ftl, tests/functional/firefox/whatsnew/test_whatsnew_81.py
More neutral English for easier l10n, and we'll treat the quirky colloquialisms as an American translation.
Also fixes a failing test.
=> String fixes for WNP81 [#9344]

Dockerfile, bedrock/base/geo.py, bedrock/base/tests/test_geo.py, bedrock/base/tests/test_views.py, bedrock/base/views.py, bedrock/newsletter/views.py, bedrock/settings/base.py, requirements/prod.txt
=> Use Maxmind DB for getting request country codes

bedrock/firefox/templates/firefox/welcome/page4.html, l10n/en/firefox/welcome/page4.ftl, media/css/firefox/welcome.scss
Revised strings on Welcome/4 page. 
#9394 
Local URL: http://localhost:8000/en-US/firefox/welcome/4/
=> Fixed #9394 - Revised FTL Strings for Welcome/4 Page

bedrock/mozorg/templates/mozorg/about/leadership.html
Copy updates to leadership title/bios
#9414 
Confirm copy from Leadership page.
=> Fixed #9414 - Updated title/bios for Dana, Dave and Leslie

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx76.html, tests/functional/firefox/whatsnew/test_whatsnew_76.py, tests/pages/firefox/whatsnew/whatsnew_76.py
Fixes: https://gitlab.com/mozmeao/www-config/-/pipelines/191738102/failures
=> Fix functional tests on 76 WNP (#9316)

bedrock/firefox/firefox_details.py
Fixes: https://gitlab.com/mozmeao/www-config/-/jobs/751098290
Looks like this info changed in product details
=> Update firefox/all Android tests

bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
Minor copy update to de landing page for september campaign.
#9361
=> Update sept landing page de copy (#9361)

docs/architecture/decisions/0005-use-a-single-docker-image-for-all-deployments.md
Re https://github.com/mozmeao/infra/issues/1306
=> Add an ADR for using a single docker image for all deployments

bedrock/firefox/templates/firefox/campaign/unfck/index.de.html, media/css/firefox/unfck.de.scss
A couple of minor copy amends for German
#9361
=> Copy updates for German sept landing page (#9361)

bedrock/firefox/templates/firefox/campaign/unfck/index.html
=> Add blog post URLs

bedrock/firefox/templates/firefox/campaign/unfck/index.html
Copy tweaks to campaign landing page.
#9334
http://localhost:8000/en-US/firefox/unfck/
=> Copy tweaks (#9334)

bin/run-db-clock.sh
These weren't happening and it was causing dev to have prod data in
certain situations.
Re #9488
=> Run db download and migrations in clock pod

bedrock/mozorg/templates/mozorg/home/home-de.html
- Update hero copy
- Remove redundant `_()` lang helper calls.
#9510
=> Update Hero copy for /de/ home page (Fixes #9510)

bedrock/firefox/templates/firefox/campaign/unfck/index.html
Copy tweak requested in Slack
n/a
=> [no bug] Copy tweak

.circleci/config.yml
=> Upgrade CircleCI Docker engine version

media/js/mozorg/about-leadership.js
=> Fix JS error on /about/leadership/ page (Fixes #9478)

bedrock/firefox/templates/firefox/campaign/unfck/index.html
Update social share text
#9334
=> Upate social share text

bedrock/mozorg/templates/mozorg/home/home-fr.html
http://localhost:8000/fr/
#9556
=> Update hero CTA on French home page (Fixes #9556)

media/css/firefox/enterprise/landing.scss
@glogiotatidis r? this should help with the test failure
=> Remove smooth scrolling from /enterprise landing page (Fixes #9563)

bin/run-integration-tests.sh
Adds Browser Stack as a driver option when setting desired capabilities
=> Add BrowserStack as a functional test driver option

bedrock/firefox/templates/firefox/faq.html, l10n/en/firefox/faq.ftl
Copy updates for firefox/faq per Raphael and [Peiying's feedback.](https://github.com/mozilla-l10n/www-l10n/pull/123)
=> Copy updates for firefox/faq

docs/pipeline.rst
=> Update pipeline testing docs (Fixes #9580)

bedrock/firefox/templates/firefox/home/index-master.html
Fixes https://github.com/mozilla/bedrock/issues/9604
=> Fix internal link with utm

bedrock/firefox/templates/firefox/campaign/unfck/index.html
Add a second link in the Pocket section of EN UTI page.
No bug.
=> Add link to explain Pocket [no bug]

bedrock/firefox/templates/firefox/releases/notes.html
Fixes https://github.com/mozilla/bedrock/issues/9610
=> Add link in footer to /more

lib/l10n_utils/management/commands/open_ftl_pr.py
Automation currently always opens a new PR for FTL file updates. This
checks for an open PR and updates the branch instead of creating a new
PR everytime, since the new PR will contain changes from the other open
one.
=> Fix #9602: Update FTL automation to update the PR if one is open

bedrock/firefox/redirects.py, bedrock/firefox/templates/firefox/sync.html, bedrock/firefox/urls.py, l10n/en/firefox/sync.ftl, media/css/firefox/sync.scss, media/static-bundles.json, tests/redirects/map_globalconf.py, tests/redirects/test_urls.py
Adds firefox/sync
#9490
#9519
#9516
[Copy](https://docs.google.com/document/d/1LE3SwAOvSajQ_3TC_lt87tj2Fxokxhe55BFiCngVuBA/edit)
[Design](https://github.com/mozilla/bedrock/issues/9518#issuecomment-706292804)
=> Add firefox/sync (#9490, Fixes #9519, #9516)

bedrock/firefox/templates/firefox/browsers/quantum.html, l10n/en/firefox/browsers/chromebook.ftl, l10n/en/firefox/browsers/quantum.ftl, l10n/en/firefox/sync.ftl
Changes requested in https://github.com/mozilla-l10n/www-l10n/pull/125
Relating to work in #9490
=> l10n updates [#9490]

bedrock/base/templates/base-protocol.html
=> Remove set_hsts.gif from the site

bedrock/base/tests/test_waffle_config.py, bedrock/base/waffle_config.py, bedrock/firefox/tests/test_views.py, bedrock/firefox/views.py
=> Set up experiment redirects for /firefox/new/

media/js/base/sentry-init.js
=> Add GA and Convert domains to Sentry JS allowURLs list

.gitlab-ci.yml
Requires https://github.com/mozmeao/www-config/pull/324
Fix #9598
=> Fix run-integration-tests branch test runs

bedrock/firefox/templates/firefox/campaign/unfck/index.html, media/css/firefox/unfck.scss
- update copy to be less electoin focused behind a switch
- remove old switches
n/a
=>  Copy updates for UTI landing page [no bug] 

bedrock/firefox/templates/firefox/all-unified.html, media/css/firefox/all/all-unified.scss
- change download info to a table
- right align button
See #8938
[Design specs](https://github.com/mozilla/bedrock/issues/8938#issuecomment-700214409)
[Link to localhost](http://localhost:8000/en-US/firefox/all/)
=> Display updates to /all (#8938)

bedrock/firefox/templates/firefox/faq.html
Fixes https://github.com/mozilla/bedrock/issues/9639
=> /faq include structured data on en-US only

l10n/en/firefox/browsers/quantum.ftl, l10n/en/firefox/more.ftl
Addresses feedback in www-l10n review.
https://github.com/mozilla-l10n/www-l10n/pull/127
=> [no bug] l10n updates

bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
=> Update Instagram link on /de/firefox/unfck/ (Fixes #9671)

l10n/en/firefox/sync.ftl
Change requests from l10n for firefox/sync
=> [no bug] firefox/sync l10n fix

bedrock/firefox/templates/firefox/new/protocol/download_mac.html
Fixes https://github.com/mozilla/bedrock/issues/9701
=> Title fix on /mac/

bedrock/firefox/templates/firefox/features/safebrowser.html
Remove Focus from safe-browser
Fix #9705 
http://localhost:8000/en-US/firefox/features/safebrowser/
=> Remove Focus from safe-browser (Fix #9705)

l10n/en/firefox/privacy/book.ftl
Updates bedrock's copy of `firefox/privacy/book.ftl` to reflect the copy changes that were implemented in the www-l10n repo.
=> l10n copy changes for book.ftl [no bug]

docs/coding.rst
Add documentation of getting files onto assets.mozilla.net
=> Document usage of large file assets

bedrock/firefox/templates/firefox/new/protocol/base.html, bedrock/firefox/templates/firefox/new/protocol/base_download.html, bedrock/firefox/templates/firefox/new/protocol/download_linux.html, bedrock/firefox/templates/firefox/new/protocol/download_mac.html, bedrock/firefox/templates/firefox/new/protocol/download_windows.html, bedrock/firefox/urls.py, l10n/en/firefox/new/platform.ftl, lib/fluent_migrations/firefox/new/protocol/download.py
- http://localhost:8000/en-US/firefox/windows/
- http://localhost:8000/en-US/firefox/mac/
- http://localhost:8000/en-US/firefox/linux/
#9677
```
```
=> Migrate /firefox platform download pages to Fluent (Fixes #9677)

.gitlab-ci.yml
=> Changing update config to point at new folder

bedrock/foundation/urls.py
Fixes https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/10197450/events/
https://github.com/mozilla/bedrock/issues/9756
=> Fix annual report redirect URL (Fixes #9756)

l10n/en/brands.ftl
Ref: https://github.com/mozilla-l10n/www-l10n/pull/150#discussion_r537638256
=> Add Netscape to brands.ftl

bedrock/firefox/templates/firefox/browsers/best-browser.html, bedrock/firefox/urls.py, l10n/en/firefox/browsers/best-browser.ftl, lib/fluent_migrations/firefox/browsers/best-browser.py
http://localhost:8000/en-US/firefox/browsers/best-browser/
#9692
```
```
=> Migrate /firefox/browsers/best-browser/ to Fluent (Fixes #9692)

bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html, bedrock/firefox/urls.py, l10n/en/firefox/browsers/history/what-is-a-browser.ftl, lib/fluent_migrations/firefox/browsers/what-is-a-browser.py
http://localhost:8000/en-US/firefox/browsers/what-is-a-browser/
#9694
```
```
=> Migrate /firefox/browsers/what-is-a-browser/ to Fluent (Fixes #9694)

bedrock/base/templates/includes/banners/fundraiser.html, bedrock/mozorg/templates/mozorg/home/home-de.html, bedrock/mozorg/templates/mozorg/home/home-en.html, bedrock/mozorg/templates/mozorg/home/home-fr.html, bedrock/mozorg/templates/mozorg/home/home.html, bedrock/mozorg/views.py, bedrock/settings/base.py, l10n/en/banners/fundraising.ftl
Adds a MoFo fundraising banner to the home page (maybe more), to run from 21 December to 4 January.
#9765 
https://www-demo-pr-9772.herokuapp.com
=> Add EOY2020 fundraising banner [fix #9765]

bedrock/firefox/templates/firefox/privacy/passwords.html, l10n/configs/pontoon.toml, l10n/en/firefox/privacy/passwords.ftl
Fixes: https://github.com/mozilla/bedrock/issues/9795
=> Add pontoon config for privacy/passwords.ftl (Fixes #9795)

media/js/base/protocol/protocol-sub-navigation.js
Fixes sub navigation collapse / expand on iOS devices
#9821
=> Fix sub navigation on iOS devices (Fixes #9821)

bedrock/firefox/templates/firefox/developer/includes/highlights.html, bedrock/firefox/templates/firefox/features/private-browsing.html, l10n/en/firefox/features/private-browsing.ftl
A couple of minor string fixes for recent Fluent pages.
None
=> Misc Fluent string fixes

test_infra/test_cdn.py
to run tests `make test-cdn TEST_DOMAIN=www.allizom.org`
=> Add a test for query string respect for the CDN

bedrock/firefox/templates/firefox/channel/desktop.html
=> Update Firefox Beta feedback link (Fixes #9834)

docs/abtest.rst
Add docs for viewing traffic cop experiments in GA
n/a
n/a
=> Add docs for viewing traffic cop experiments in GA

tests/functional/firefox/browsers/compare/test_browsers.py, tests/functional/firefox/features/test_features.py, tests/functional/firefox/test_releasenotes.py, tests/pages/firefox/browsers/best_browser.py, tests/pages/firefox/browsers/browser_history.py, tests/pages/firefox/browsers/compare.py, tests/pages/firefox/browsers/incognito_browser.py, tests/pages/firefox/browsers/what_is_a_browser.py, tests/pages/firefox/browsers/windows_64_bit.py, tests/pages/firefox/features/adblocker.py, tests/pages/firefox/features/feature.py, tests/pages/firefox/features/landing.py, tests/pages/firefox/releasenotes.py
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/242101362
=> Fix functional tests for sticky promo

bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py, bedrock/settings/base.py
=> Update donate metadata

media/js/firefox/all/all-downloads-unified.js, tests/unit/spec/firefox/all/all-downloads-unified.js
- Fixes error thrown on firefox/all page when `BOUNCER_URL` is set to staging.
- Throw more useful error messages when bad download links are found.
#9851
=> Support staging Bouncer URLs on firefox/all (Fixes #9851)

bedrock/mozorg/templates/mozorg/home/home-en.html
=> Copy update (Fix #9766)

media/css/protocol/components/send-to-device.scss
Update S2D thank you message to match notification styles
See #9864 
Submit the form on http://localhost:8000/en-US/firefox/mobile/ with the testing email address success@example.com
=> Update S2D thank you message to match notification styles (#9864)

bedrock/legal_docs/models.py, bedrock/legal_docs/tests/test_base.py, bedrock/legal_docs/views.py, bedrock/privacy/views.py
See https://github.com/mozilla/legal-docs/issues/1501
=> Support the updated legal-docs repo layout

bedrock/legal_docs/models.py, bedrock/legal_docs/tests/test_base.py
=> Fix endless redirect when legal-doc uses en locale

bedrock/mozorg/templates/mozorg/about/leadership.html
Update's Roxi Wen's bio.
#9906 
https://bugzilla.mozilla.org/show_bug.cgi?id=1690911
http://localhost:8000/en-US/about/leadership/#roxi-wen
=> Leadership page, update Roxi’s bio [fix #9906]

l10n/en/firefox/browsers/compare/shared.ftl
=> resolved #9899

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2020.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2020.html, bedrock/mozorg/urls.py
http://localhost:8000/en-US/about/policy/transparency/jul-dec-2020/
#9918
- https://www-demo2.allizom.org/en-US/about/policy/transparency/
- https://www-demo2.allizom.org/en-US/about/policy/transparency/jul-dec-2020/
- https://www-demo2.allizom.org/en-US/about/policy/transparency/jan-jun-2020/
=> Add transparancy report for jul-dec 2020 (Fixes #9918)

bedrock/mozorg/templates/mozorg/home/home-de.html, bedrock/mozorg/templates/mozorg/home/home-en.html, bedrock/mozorg/templates/mozorg/home/home-fr.html, bedrock/mozorg/templates/mozorg/home/home.html, bedrock/mozorg/templates/mozorg/moss/base.html, bedrock/mozorg/views.py, l10n/configs/pontoon.toml, l10n/en/mozorg/home.ftl, lib/fluent_migrations/mozorg/home/home.py
=> Migrate Mozilla home page to Fluent (Fixes #9911)

bedrock/mozorg/templates/mozorg/about/governance/policies/regressions.html
http://localhost:8000//en-US/about/governance/policies/regressions/
#9947
=> Update Performance Regression Policy (Fixes #9947)

tests/unit/spec/base/core-datalayer.js, tests/unit/spec/base/fxa-utm-referral.js, tests/unit/spec/base/mozilla-fxa.js, tests/unit/spec/base/mozilla-lazy-load.js, tests/unit/spec/base/send-to-device.js, tests/unit/spec/base/stub-attribution-macos.js, tests/unit/spec/base/stub-attribution.js
Remove jQuery syntax from JS unit tests
N/A
=> Remove jQuery from JS unit tests

tests/functional/test_contact.py
Fixes: https://gitlab.com/mozmeao/www-config/-/jobs/1055123099
=> Update /contact/ spaces functional test

bedrock/newsletter/templates/newsletter/index.html, l10n/en/mozorg/newsletters.ftl
http://localhost:8000/en-US/newsletter/
#9935
=> Update /newsletter page copy (Fixes #9935)

bedrock/products/templates/products/vpn/platforms/desktop.html, bedrock/products/templates/products/vpn/platforms/includes/subnav-desktop.html, bedrock/products/templates/products/vpn/platforms/includes/subnav-mobile.html, bedrock/products/templates/products/vpn/platforms/ios.html, bedrock/products/templates/products/vpn/platforms/linux.html, bedrock/products/templates/products/vpn/platforms/mac.html, bedrock/products/templates/products/vpn/platforms/mobile.html, bedrock/products/templates/products/vpn/platforms/windows.html, bedrock/products/urls.py, l10n/en/brands.ftl, l10n/en/products/vpn/platforms/ios.ftl, l10n/en/products/vpn/platforms/linux.ftl, l10n/en/products/vpn/platforms/mac.ftl, l10n/en/products/vpn/platforms/mobile.ftl, l10n/en/products/vpn/platforms/shared.ftl, l10n/en/products/vpn/platforms/windows.ftl, media/css/products/vpn/platforms/common.scss, media/static-bundles.json
Create the following 6 pages: 
Other tasks: 
Notes: 
- The Android VPN platform page will be added in a later PR. 
- #10011
- #10010
- #10009
- ~#10008~ Blocked on copy right now 
- #10007 
- #10006
Test the following URLs (including subnav, pricing links) 
- https://www-demo-pr-10013.herokuapp.com/en-US/products/vpn/desktop/linux/
- https://www-demo-pr-10013.herokuapp.com/en-US/products/vpn/desktop/mac/
- https://www-demo-pr-10013.herokuapp.com/en-US/products/vpn/desktop/windows/
- https://www-demo-pr-10013.herokuapp.com/en-US/products/vpn/mobile/
- ~https://www-demo-pr-10013.herokuapp.com/en-US/products/vpn/mobile/android/~
- https://www-demo-pr-10013.herokuapp.com/en-US/products/vpn/mobile/ios/
=> Build VPN platform pages 

bedrock/products/templates/products/vpn/platforms/android.html, bedrock/products/templates/products/vpn/platforms/includes/subnav-mobile.html, bedrock/products/urls.py, l10n/en/products/vpn/platforms/android.ftl
Add Android page to VPN platform pages
#10008 
http://localhost:8000/en-US/products/vpn/mobile/android/
=> Fix #10008 - Add Android VPN platform page

bin/update_config.sh
Keep the image of bedrock up to date
=> Canary configs to be updated

bedrock/products/templates/products/vpn/platforms/android.html, l10n/en/products/vpn/platforms/android.ftl
Fixed the following: 
- Removed double spaces
- Replace hard coded number with variable 
#10044 
- http://localhost:8000/en-US/products/vpn/mobile/android/
=> Fix #10044 - VPN Android platform page FTL updates

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
This adds hugs production endpoints to the web bug bounty.
=> Add hubs to bug bounty

bedrock/mozorg/templates/mozorg/home/home-en.html, bedrock/mozorg/views.py
Homepage layout updates to support March content.
Fix #10074
Might need to view it on the demo to see the new cards in the new layout.
=> March EN homepage

bedrock/products/tests/test_views.py, bedrock/products/views.py
@craigcook r? (small followup fix for https://github.com/mozilla/bedrock/issues/10069)
=> Remove vpn experiment logic from view (#10069)

media/js/base/core-datalayer.js, tests/unit/spec/base/core-datalayer.js
Make sure we're conforming to new standards defined in `Mozilla.Client.getFxaDetails()`.
#9929
=> Fix FxA GA bug for Sync device counts (Fixes #9929)

l10n/configs/pontoon.toml
Per the request from Tajik's community manager Victor (victor.ibragimov@gmail.com), they would like to start localizing the site.
The Tajik community would like to start localizing the site.
This is the first time since the migration such request has come to us. If this is not the correct process to initiate the request, let me know if I need to file a bug or an issue for it.
=> Add Tajik (tg) to the locale list

bedrock/mozorg/templates/mozorg/about/forums/forums.html
Last weekend we decommissioned our legacy forums (mailman+usenet) and so this page needs to be updated.  Text was reviewed by mhoye as well, not sure of the process for approving this change any further.
(likewise, I've tested this in a local docker environment, but I am not a bedrock dev so please let me know if this is incomplete or breaks something elsewhere)
=> Updated forums page

bedrock/firefox/templates/firefox/privacy/book.html
Add anchor links to all `h2` and `h3` elements on the Little Book of Privacy page. 
~Blocking merge until Liz approves~ Liz approved! 
#10079
The following links should jump down the page to their respective sections: 
- https://www-demo-pr-10138.herokuapp.com/firefox/privacy/book/#risks
- https://www-demo-pr-10138.herokuapp.com/firefox/privacy/book/#data-breaches
- https://www-demo-pr-10138.herokuapp.com/firefox/privacy/book/#web-never-forgets
- https://www-demo-pr-10138.herokuapp.com/firefox/privacy/book/#trackers-everywhere
- https://www-demo-pr-10138.herokuapp.com/firefox/privacy/book/#trolls
- https://www-demo-pr-10138.herokuapp.com/firefox/privacy/book/#fake-news
- https://www-demo-pr-10138.herokuapp.com/firefox/privacy/book/#control
- …
=> Add anchor links to Little Book of Privacy

bedrock/products/templates/products/vpn/landing.html, l10n/en/products/vpn/landing.ftl
http://localhost:8000/en-US/products/vpn/#faq-compatibility
#10128
=> Update VPN system requirements (Fixes #10128)

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Fix bug 1703063
Folloup to #10098
=> Fix the ordered list in section 2.1 of the CA Certs Policy page

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1703063
http://localhost:8000/en-US/about/governance/policies/security-group/certs/policy/
=> Add section 8 to CA policy table of contents [bug #1703063]

media/js/base/send-to-device.js, tests/unit/spec/base/send-to-device.js
Ports send-to-device to vanilla JS
#7673
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/301467419
=> Remove jquery from send-to-device.js (Fixes #7673)

media/js/products/vpn/download-first-experiment.js
This shouldn't effect anything, but was pointed out by Sarah on the VPN team. I could not resist updating it because I'm OCD.
#10209
=> Update VPN download-first exp cookie ID

bedrock/settings/base.py
=> Update VPN staging plan IDs (Fixes #10260)

media/js/firefox/welcome/welcome10-experiment.js, tests/pages/firefox/welcome/page10.py
Fixing the test I broke (just need to update the class in the button locator). Also excludes automation from traffic cop.
`py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/firefox/welcome/test_welcome_page10.py`
=> Fix functional tests for welcome 10 [#10257]

bedrock/products/tests/test_helper_misc.py, bedrock/settings/base.py
Fixes https://github.com/mozilla/bedrock/issues/10300
=> Update CHF currency formatting (Fixes #10300)

media/js/base/mozilla-fxa-product-button.js, tests/unit/spec/base/mozilla-fxa-product-button.js
Fixes JS error on WNP 90
https://github.com/mozilla/bedrock/issues/10316
http://localhost:8000/en-US/firefox/90.0/whatsnew/all/?v=2
=> Fix uncaught promise thrown by FxAProductButton.init() (Fixes #10316)

media/css/protocol/components/_navigation.scss
The new nav hasn't made it into Protocol yet, so updating here to reference the issue I filed.
https://github.com/mozilla/protocol/issues/700
=> Update nav scroll offset (protocol/issues/700)

bedrock/mozorg/templates/mozorg/home/includes/mr1-promo-gary.html, bedrock/mozorg/templates/mozorg/home/includes/mr1-promo-lalo.html, media/css/mozorg/home/home-mr1-promo.scss
Adds links for Gary and Lalo. The other two are forthcoming in a the next few weeks.
#10352 
You'll probably have to reload the page several times to get both promos (it's random)
=> Link to blog interviews from home promos [#10352]

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2021.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html, bedrock/mozorg/urls.py, media/css/mozorg/about-transparency.scss
Jan-Jun 2021 TR report
#10365
http://localhost:8000/en-US/about/policy/transparency/jan-jun-2021/
=> 2021 H1 Transparency report (Fixes #10365)

l10n/en/products/vpn/more/when-to-use-a-vpn.ftl
Oops.
https://github.com/mozilla-l10n/www-l10n/issues/216
=> Fix dev URL in VPN page Fluent file

bedrock/firefox/templates/firefox/nightly/firstrun.html
Fixes: https://gitlab.com/mozmeao/www-config/-/jobs/1487954047
=> Fix Nightly /firstrun page test selectors

docs/coding.rst
In the subsection of "Developing on Bedrock" added section name Working with Protocol .
#10371
=> Added a new subsection Working with Protocol

bedrock/contentful/api.py, bedrock/contentful/templates/includes/contentful/cta.html
=> Add support for VPN CTA for Contentful Hero components

tests/functional/firefox/browsers/mobile/test_android.py, tests/functional/firefox/browsers/mobile/test_ios.py
Fixes https://gitlab.com/mozmeao/www-config/-/jobs/1592553975
N/A
N/A
=> Temporarily skip tests that require localized pages not yet in production

bedrock/firefox/templates/firefox/browsers/mobile/compare.html, l10n/en/firefox/browsers/mobile/android.ftl, l10n/en/firefox/browsers/mobile/compare.ftl, l10n/en/firefox/browsers/mobile/focus.ftl, l10n/en/firefox/browsers/mobile/index.ftl
A few small fixes for the mobile pages.
https://github.com/mozilla-l10n/www-l10n/pull/229
=> String fixes for mobile pages [mozilla-l10n/www-l10n #229]

l10n/en/products/vpn/shared.ftl
Addresses https://github.com/mozilla-l10n/www-l10n/pull/231#pullrequestreview-764434471
=> Remove outdated VPN country strings (#10498)

docs/contribute.rst, docs/fluent-conversion.rst, docs/install.rst, docs/l10n.rst, docs/pipeline.rst, docs/redirects.rst, docs/testing.rst
Fixed all the clipboard code snippets 
#10453
=> Fix clipboard issue (fixes #10453)

docs/coding.rst
Fix code formatting blocks added in https://github.com/mozilla/bedrock/pull/10478
N/A
=> Minor docs syntax fixes

bedrock/security/templates/security/bug-bounty/faq.html, bedrock/security/templates/security/client-bug-bounty.html
=> Be explicit about EOL products

.pre-commit-config.yaml, docs/install.rst, setup.cfg
See https://pre-commit.com/ for details
You can try it by checking out this branch, installing pre-commit using instructions on their site (I used brew for Mac), and then running `pre-commit install`. You can try running it against all of the files by running `pre-commit run --all-files`.
=> Add pre-commit hooks configuration and docs

media/js/base/stub-attribution.js
Fixes https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/13516420/?environment=production&referrer=alert_email
=> Use indexOf over includes for better older browser compat (#10524)

bedrock/products/templates/products/vpn/more/what-is-a-vpn.html, l10n/en/products/vpn/more/what-is-a-vpn.ftl
I misinterpreted some of the previous updates and missed a whole chunk of one string.
#10484 
http://localhost:8000/products/vpn/more/what-is-a-vpn/
=> Copy fix for "what is a vpn" page [#10484]

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
As per https://groups.google.com/g/mozilla.governance/c/7M6MlaNZXH0
=> Exempt employees from requiring vouching for commit level 1

l10n/configs/pontoon.toml
=> Add home MR2 promo to Pontoon config

l10n/configs/pontoon.toml, l10n/configs/vendor.toml
- Remove de, fr from Pontoon locale list
- Add de, fr to Vendor supported locale list
=> Move de, fr to vendor supported locale

media/js/base/sentry.es6.js
Fixes https://github.com/mozilla/bedrock/issues/10683
=> Ignore noisy non-actionable JS errors (Fixes #10683)

bedrock/security/templates/security/client-bug-bounty.html
@dveditz @deian LMK if this looks good to you.
=> Add wasmbox to the Exploit Mitigation Bounty explicitly.

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
This updates the FQDN for our JIRA instance.
=> Update JIRA FQDN

bedrock/mozorg/templates/mozorg/about/leadership.html
Adding the Steering Committee note under Imo's title.
Requested via Slack, but I can file an issue if we really want to follow procedure.
http://localhost:8000/about/leadership/#imo-udom
=> Leadership page, add Imo Udom to steering committee [no bug]

bedrock/base/templates/cron-health-check.html, bedrock/base/views.py
Fix issue with this page due to removed l10n info.
=> Remove .lang files info from healthz-cron page

bedrock/contentful/api.py, bedrock/contentful/templatetags/helpers.py, bedrock/contentful/tests/test_contentful_api.py, bedrock/contentful/tests/test_templatetags_helpers.py, setup.cfg
Backfilling more tests for the contentful integration. These are having to be written based on viewable code paths, so aren't going to cover every edge case, but they're a building block.
More to come soon - hopefully just one PR's worth.
Contributes to #10639
Unit tests passing and coverage going (slightly) up is enough,  I think.
=>  Improve Contentful-related test coverage - part 2 of n

docs/coding.rst
Micro documentation update to help remind new team members (eg: me) about the risk of certain DB migrations and how to avoid them
=> Update docs with a reminder about writing safer migrations

.github/dependabot.yml
Just testing for now. I've added a commented out section for front-end if we're interested.
=> Add dependabot.yml for backend dependencies

bedrock/externalpages/templates/externalpages/pocket/add.html, bedrock/externalpages/templates/externalpages/pocket/includes/platform-footer.html, bedrock/externalpages/templates/externalpages/pocket/includes/platform-nav.html, media/css/externalpages/pocket/components/add.scss, media/css/externalpages/pocket/includes/_platform-footer.scss, media/css/externalpages/pocket/includes/_platform-nav.scss
Removing BEM classes from Pocket pages that have them
#10876
http://localhost:8000/en-US/external/pocket/add/
http://localhost:8000/en-US/external/pocket/android/
=> Remove BEM classes in Pocket pages

bedrock/firefox/templates/firefox/nightly/firstrun.es-AR.html, bedrock/firefox/templates/firefox/nightly/firstrun.es-ES.html
Updates content on the Nightly firstrun page for es-AR and es-ES
#10894 
http://localhost:8000/es-AR/firefox/nightly/firstrun/
https://www-demo-pr-11037.herokuapp.com/es-AR/firefox/nightly/firstrun/
http://localhost:8000/es-ES/firefox/nightly/firstrun/
https://www-demo-pr-11037.herokuapp.com/es-ES/firefox/nightly/firstrun/
=> Update Nightly firstrun page for es-AR and es-ES [fix #10894]

bedrock/base/geo.py, bedrock/base/middleware.py, bedrock/base/tests/test_urlresolvers.py, bedrock/base/urlresolvers.py, bedrock/newsletter/views.py, bedrock/products/views.py, bedrock/redirects/util.py, lib/l10n_utils/__init__.py
Introduced in Django 2.2:
https://docs.djangoproject.com/en/2.2/releases/2.2/#requests-and-responses
=> Switch to simpler request header access

bedrock/careers/urls.py, bedrock/exp/urls.py, bedrock/firefox/urls.py, bedrock/legal/urls.py, bedrock/mozorg/tests/urls.py, bedrock/mozorg/urls.py, bedrock/mozorg/util.py, bedrock/newsletter/urls.py, bedrock/press/urls.py, bedrock/privacy/urls.py, bedrock/redirects/util.py, bedrock/security/urls.py, bedrock/urls.py
Introduced in Django 2.0:
https://docs.djangoproject.com/en/2.0/releases/2.0/#simplified-url-routing-syntax
=> Use simplified URL routing syntax

bedrock/careers/templates/careers/position.html
Port to bedrock of
https://github.com/mozmeao/lumbergh/commit/e68e2c310e7ed9be54b5f431cedfb25d33127d97
=> Update Careers Applicant Privacy Notice link

bedrock/externalpages/templates/externalpages/pocket/pocket-and-firefox.html, bedrock/externalpages/templates/externalpages/pocket/save-to-pocket.html, bedrock/externalpages/urls.py, media/css/externalpages/pocket/components/pocket-features.scss
Coded the [save-to-pocket](https://getpocket.com/en/save-to-pocket) page onto Bedrock.
https://github.com/mozilla/bedrock/issues/10211
http://localhost:8000/en-US/external/pocket/save-to-pocket/
=> Migrate save-to-pocket page

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-de.html
=> Fix typo in WNP 96 DE (Issue #11059)

tests/unit/spec/base/dnt-helper.js, tests/unit/spec/base/mozilla-client.js
Front-end code seems to check out OK 👍 
#9575
=> Add JS unit tests with Firefox v100 UA string (Issue #9575)

bedrock/firefox/templates/firefox/whatsnew/includes/fx96-en/qr.html, media/css/firefox/whatsnew/whatsnew-96-en-mobile.scss
Requested via slack to reduce the size of the QR code.
#11070 
http://localhost:8000/en-US/firefox/96.0/whatsnew/?v=2
=> Shrink QR code on EN WNP96 [#11070]

bedrock/security/templates/security/web-bug-bounty.html
Add SSRF to the list of payouts for web bug bounty
=> Add SSRF to the list of payouts for web bug bounty

bin/cron.py, bin/db_s3_utils.py, bin/move_hashed_staticfiles.py, bin/open-compare.py, bin/run-db-download.py, bin/run-db-upload.py
=> Update `bin/` scripts to explicitly use Python 3

media/js/careers/listings/filters.es6.js, tests/unit/spec/careers/filters.js
Fixing of Remote job filtering like now when we'll select Remote US, the Remote will also be included and for all the specific Remote location.
#11112
https://user-images.githubusercontent.com/73520373/149544200-48637a42-63c2-4b92-8338-57f1e0218d24.mp4
=> Fixed 'Remote' job filtering

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
Some minor improvements on the access policy doc
=> Some minor improvements on the access policy doc

docs/install.rst
Quick fix to documentation - the instructions did work, but only while the shell session persisted. This fix makes it persistent/re-triggered each new session
=> Update docs re pyenv-virtualenv setup

l10n/en/firefox/enterprise.ftl
=> Fix variable names in enterprise.ftl

docs/index.rst, docs/sitemap.rst
I've added a light intro to how the sitemap generation works (I think...) as a signpost to our future selves.
No ticket
* pull the branch
* `make docs` to spin up the Docker-powered livedocs
* Take a look at http://0.0.0.0:8100/sitemap.html
Feedback/improvements are 1000% welcome!
=> Add initial summary of how sitemap generation works

docs/sitemap.rst
=> Sitemaps documentation: clarify that it's data flowing around, not rendered sitemaps

bedrock/security/templates/security/known-vulnerabilities.html, bedrock/sitemaps/utils.py
Issue: https://github.com/mozilla/bedrock/issues/9659
=> Link to Mozilla VPN advisories

bedrock/security/templates/security/bug-bounty/hall-of-fame.html, bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
2016-2021 comes to $1.9m and I don't have any data pre 2016.  @dveditz Does $2m sound good or do you want to try to find some more data to pump it higher?
=> Update the bug bounty amount

bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-ios-qr.html, bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-ios-sms.html, bedrock/firefox/templates/firefox/browsers/mobile/ios.html, bedrock/firefox/urls.py, media/js/firefox/browsers/firefox-ios-sms-experiment.js, media/static-bundles.json
This sets up the templates and the traffic cop experiment, but the SMS form isn't actually working yet.
Also I think we're supposed to get a new QR code. I'll follow up on that.
=> Set up SMS experiment

media/js/base/sentry.es6.js, package-lock.json, package.json
Bump Sentry JS
N/A
https://www-demo-pr-11343.herokuapp.com/en-US/
=> Update Sentry JS

bin/run-integration-tests.sh, docs/testing.rst, requirements/dev.in, requirements/dev.txt, tests/pages/firefox/ios_testflight.py, tests/pages/regions/newsletter.py
Updates functional test suite to use Selenium v4.
#10591
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/499226561
=> Update to Selenium 4 (Fixes #10591)

bedrock/settings/base.py, media/css/products/vpn/components/affiliate.scss
This endpoint isn't live yet but this is the final URL. Nothing really to test yet as it's behind a switch.
#11212
http://localhost:8000/en-US/products/vpn/?cjevent=09d8676b716a11ec831e01500a18050e
=> Update CJMS endpoint for prod (Issue #11212)

.github/CONTRIBUTING.md, .gitlab-ci.yml, README.md, bedrock/base/views.py, bedrock/settings/base.py, bedrock/sitemaps/management/commands/fetch_sitemaps.py, bedrock/sitemaps/management/commands/update_sitemaps_data.py, bedrock/utils/git.py, bedrock/utils/tests/test_git.py, bin/deploy.sh, bin/open-compare.py, bin/open-ftl-pr.sh, bin/tag-release.sh, bin/update-locales.sh, bin/update_config.sh, bin/upload-staticfiles.sh, docker/bin/push2dockerhub.sh, docs/coding.rst, docs/contribute.rst, docs/download-buttons.rst, docs/funnelcake.rst, docs/install.rst, docs/l10n.rst, docs/pipeline.rst, docs/testing.rst, lib/l10n_utils/management/commands/_ftl_repo_base.py, lib/l10n_utils/management/commands/l10n_update.py, lib/l10n_utils/management/commands/open_ftl_pr.py, setup.cfg
=> Update references to bedrock git default branch to main

docs/vpn-affiliate-attribution.rst
Micro docs update to factor in https://github.com/mozilla/bedrock/issues/11454
N/A
=> Update VPN affiliate docs with addition of OK button

docs/abtest.rst, docs/analytics.rst, docs/banners.rst, docs/browser-support.rst, docs/coding.rst, docs/contentful.rst, docs/download-buttons.rst, docs/firefox-accounts.rst, docs/install.rst, docs/l10n.rst, docs/redirects.rst, docs/send-to-device.rst, docs/vpn-affiliate-attribution.rst
=> Add `:abbr:` tags for common abbreviations

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
This reverts commit 0164bc579045a9c6735d814ae953bd95afd42d32, backtracking the gunicorn upgrade
=> Revert "Bump gunicorn (#11520)"

media/js/products/vpn/affiliate-attribution.es6.js, tests/unit/spec/products/vpn/affiliate-attribution.js
Right now if a visitor already has an affiliate marketing cookie set, but that corresponding ID no longer exists in the CJMS database, we end up throwing an `Unknown aicID` error and the cookie banner is not shown. This scenario is possible if someone has gone on to purchase a subscription via an affiliate link (at which point the ID is archived in the CJMS database), but then that visitor goes on to revisit the landing page later (before the cookie has expired).
This change makes it so we perform another `POST` if the existing `PUT` fails with a 404, rather than throwing an error like we do currently. Or in otherwords, we treat it like a new flow entry and override the existing affiliate cookie.
#11506
URL: http://localhost:8000/en-US/products/vpn/?cjevent=4a39c2b8bccc11ec806c00a40a18050c …
=> Initiate new CJMS POST when issued with a 404 for unknown aic id (Fixes #11506)

docs/contentful.rst
=> Update Contentful documentation around the developer experience within Bedrock

.github/PULL_REQUEST_TEMPLATE.md
The testing list is more useful as a checklist that people can tick off?
=> Update PR template to use checklist

bedrock/mozorg/templates/mozorg/home/includes/fx100-promo-eu.html, bedrock/mozorg/templates/mozorg/home/includes/fx100-promo.html, media/css/mozorg/home/home-fx100-promo.scss
- Adds a couple of line breaks to the DE/FR versions requested by the EU team.
- Adds GA data attributes and utm params to promo links for all versions.
#11539
=> Updates to FF100 home page promo (#11539)

bin/update_config.sh
See https://github.com/mozmeao/www-config/pull/453
=> Add pocket-deploy.yaml to the files updated during deployment

bedrock/security/templates/security/known-vulnerabilities.html, bedrock/sitemaps/utils.py
Link to Firefox for iOS advisories
=> Link to Firefox for iOS advisories

media/js/glean/init.es6.js
This should match the application ID name used here https://dictionary.telemetry.mozilla.org/apps/bedrock?itemType=app_ids&page=1
=> Update Glean application ID to 'bedrock' (Issue #10746)

docs/analytics.rst
Tiny follow up to https://github.com/mozilla/bedrock/pull/11692
=> Update glean debug tag name in analytics docs (Issue #10746)

docs/browser-support.rst
Moves IE11 to degraded support.
#11709
=> Update browser support docs (Fixes #11709)

l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
wifi -> Wi-Fi (https://github.com/mozilla-l10n/www-l10n/pull/294#discussion_r892883305)
=> Another string fix for MDNPlus Dev WNP [#11633]

l10n-pocket/en/pocket/add.ftl, l10n-pocket/en/pocket/firefox/new-tab.ftl
Two small fixups from https://github.com/mozilla-l10n/pocket-www-l10n/pull/6#pullrequestreview-1002048382
=> Minor amends following L10N feedback

media/static-bundles.json
My changes in #11780 got overwritten in a rebase and I missed it before I pushed. This fixes it.
=> FIx Android experiment JS bundle [#11119]

bedrock/base/templates/includes/protocol/navigation/nav-cta.html, bedrock/firefox/templates/firefox/new/basic/base_download.html, bedrock/firefox/templates/firefox/new/desktop/download.html, bedrock/products/templates/products/vpn/includes/pricing-variable.html, media/js/firefox/new/desktop/join-modal.js, media/js/glean/elements.es6.js
Reverts https://github.com/mozilla/bedrock/pull/11783
=> Remove Glean click delay test (Fixes #11770)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx102-en.html
Teeny copy tweak, articles -> stories (less repetitive). Requested by Mary via Slack.
http://localhost:8000/en-US/firefox/102.0/whatsnew/
=> WNP 102 EN copy change [#11797]

tests/unit/spec/base/site.js
=> Update isARM() tests (Issue #8440)

l10n/en/mozorg/about/this-site.ftl
As requested by Peiying in https://github.com/mozilla-l10n/www-l10n/pull/300
=> L10n fix for about/this-site.ftl

bedrock/mozorg/templates/mozorg/about/leadership.html
We got Mike's bio.
http://localhost:8000/about/leadership/#mike-madeiros
=> Leadership: add Madeiros bio

bedrock/stories/templates/stories/articles/art-of-engagement.html, media/css/stories/stories-article.scss, media/css/stories/stories-landing.scss, media/css/stories/stories-shared.scss
* Fix missing image.
* Add focus styles to story button.
* Add hover/focus styles to related stories.
* Fix nav z-index. 
#11634 
http://localhost:8000/stories/
=> Product blog bug fixes [#11634]

bedrock/stories/templates/stories/articles/art-of-engagement.html, media/css/stories/stories-landing.scss
Small tweaks post-launch for Product Blog
The changes should be reflected in these pages:
- http://localhost:8000/stories
- http://localhost:8000/stories/art-of-engagement
=> content and style fixes post-launch

bedrock/stories/templates/stories/articles/art-of-engagement.html, bedrock/stories/templates/stories/articles/build-together.html
We weren't provided with the updated article, so these changes are mostly focused on content and fixing incorrectly spelled names
=> Article tweaks and typo fixes

bedrock/mozorg/templates/mozorg/about/index.html, bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
Updated a old URL which was erroring out in Sentry
=> Fix old URL in mozorg/about/

docs/contribute.rst, docs/l10n.rst
* Update documentation for demo servers to explain how to get always-on behaviour enabled
* L10N integration docs fixups
=> Documentation addition

bedrock/firefox/templates/firefox/family/includes/agreement.html, media/css/firefox/family/components/_agreement.scss, tests/functional/firefox/family/test_family.py, tests/pages/firefox/family/landing.py
Added the link to the PDF asset and updated interaction styles for the "Download PDF" button
=> update download PDF link with asset and add interaction styles

bedrock/firefox/templates/firefox/family/includes/hero.html, media/css/firefox/family/_utils.scss, media/css/firefox/family/components/_hero.scss
Added responsive layout for the hero section, and added a minimum width (500px) to the tech talk lock-up before the elements stack
https://localhost:8000/firefox/families
=> Responsive layout for Hero section

bedrock/firefox/templates/firefox/family/includes/modules/privacy.html, media/css/firefox/family/components/modules/_privacy.scss
Finish responsive styling for privacy section
Added responsive layout for privacy section using CSS Grid
#12004 
Demo server URL: http://localhost:8000/en-US/firefox/family/#privacy
=> Privacy fx family

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx105-en.html
Just wee copy tweaks. The Figma file I was working from was outdated.
http://localhost:8000/en-US/firefox/105.0/whatsnew/
=> Copy updates for EN WNP 105 [#12130]

bedrock/mozorg/templates/mozorg/home/home-contentful.html
Used the wrong switch statement in `home-contentful.html` - this PR fixes that
=> fix incorrect switch statement

l10n/en/products/vpn/shared.ftl
I think (?) this should fix the linting error in https://github.com/mozilla-l10n/www-l10n/pull/309
=> Fix linting error in products/vpn/shared.ftl

l10n/en/brands.ftl, l10n/en/products/vpn/shared.ftl
Addresses: https://github.com/mozilla-l10n/www-l10n/pull/309#discussion_r989408154
=> Use brand name for Relay Premium on /products/vpn/

l10n/configs/pontoon.toml
Fixes #12238 
Per the community manager's request, adding locale to Pontoon.
(filing on behalf of @peiying2, since the PR was never opened apparently)
=> Add locale "skr" to Pontoon TOML configuration

bedrock/mozorg/templates/mozorg/moss/index.html
Made some more minor update to the MOSS sub-site (added a link and tweaked some text)
Added one link and some plain text
If relevant:
=> added a link to the MOSS evaluation and tweaked header language

bedrock/firefox/templates/firefox/welcome/page14.html, bedrock/firefox/urls.py, l10n/configs/pontoon.toml, l10n/en/firefox/welcome/page14.ftl, media/css/firefox/welcome14.scss, media/js/firefox/welcome/welcome14.js, media/static-bundles.json
Add VPN moments page - October (Fixes #12233)
This page uses the same layout and shares fluent strings with the moments page-10
#12233 
Demo server URL: http://localhost:8000/firefox/welcome/14/
=> Add VPN Moments page - October

l10n/en/firefox/welcome/page14.ftl
Small PR to fix linting issue in a fluent file
=> remove extra line to pass l10n lint tests

bedrock/firefox/templates/firefox/welcome/page14.html, l10n/en/firefox/welcome/page14.ftl
Copy has been updated for the newest VPN moment page, will be using the old string as a fallback
=> Update copy for VPN Moments page - October

media/css/firefox/family/components/_pro-tip.scss, media/js/firefox/family/animate-pop-in.es6.js
Animation was requested by designers in #12111 - as you scroll by the pro-tip animations, they will animate from each side of the screen.
http://localhost:8000/firefox/family
https://user-images.githubusercontent.com/30009669/196262520-cf1d31ce-2b6b-43b6-bb17-9683d4a81c29.mov
=> f3: Add parental protip animation

bedrock/security/templates/security/client-bug-bounty.html
We no longer provide the databases
=> Update codeql database note

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
Just refreshing a bit the content
cc @globau
=> Refresh the commit access policy DOC 

bedrock/products/templates/products/vpn/resource-center/includes/vpn-article-card.html
Fixes https://www-dev.allizom.org/en-US/products/vpn/resource-center/
Test failure: https://gitlab.com/mozmeao/www-config/-/pipelines/690087636/failures
#12300
http://localhost:8000/en-US/products/vpn/resource-center/
=> Fix card macro in VPN resource centre (Issue #12300)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx107-de.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx107-fr.html, bedrock/firefox/tests/test_base.py, bedrock/firefox/views.py, media/css/firefox/whatsnew/whatsnew-107-eu.scss, media/static-bundles.json
Adds WNP107 templates for DE and FR
https://github.com/mozilla/bedrock/issues/12230
⚠️ waiting on Firefox Mobile Adjust links
~🟢 Adjust links available!~ whoops, wrong product
=> Add WNP for EU (fixes #12230)

bedrock/mozorg/tests/test_views.py
Fixes https://app.circleci.com/pipelines/github/mozilla/bedrock/11109/workflows/1cf9ae6e-75f4-4dc6-8672-ed4ad3196278/jobs/49076
=> Fix fundraising banner currency tests

bedrock/firefox/templates/firefox/browsers/mobile/focus.html
Fixes an error in the macro call in focus.html
=> Add missing comma to macro call

bedrock/press/views.py
Change e-mail destination of speaker request form.
=> Fix #12404: Update speaker request email

bedrock/legal/templates/legal/impressum.html
Updates as requested by legal.
https://github.com/mozilla/bedrock/issues/12452
http://localhost:8000/de/about/legal/impressum/
=> Update impressum page (Fixes #12452)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-curation-de.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-feature-de.html
http://localhost:8000/de/firefox/108.0/whatsnew/
=> Fix /de/ Pocket collections link in WNP 108

bedrock/firefox/templates/firefox/browsers/mobile/focus.html, l10n/en/firefox/browsers/mobile/focus.ftl
Updates copy to Firefox Focus page based on comments in the doc linked in [the issue](#12499).
Also updates a couple of additional strings that weren't called out in the doc but seem also relevant.
#12499
=> Updates to Firefox Focus page (Fixes #12499)

bedrock/mozorg/templates/mozorg/about/leadership/boards.html, media/css/mozorg/leadership.scss
Add board member roles.
A second pair of eyes to make sure I got this matrix correct would be good: https://docs.google.com/document/d/15E4naLf27zwTwqI5aTpUL2jxBD3ohbm0_2PzifwyoW0/edit?usp=sharing
https://github.com/mozilla/bedrock/issues/12498
http://localhost:8000/en-US/about/leadership/boards-of-directors/
=> Board member updates (Fixes #12498)

docker-compose.yml, docs/install.rst, package-lock.json, package.json, webpack.config.js
Switches to `webpack-dev-server` for local development.
https://github.com/mozilla/bedrock/issues/12496
Local install
- `npm start`
Docker install
- `make build`
- `make run`
=> Use webpack-dev-server for local development

docs/firefox-stub-attribution.rst
Updates stub attribution docs to list the values we capture, along with the related cookie IDs and download parameter values.
N/A
=> Update stub attribution documentation

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
I just manually made the HTML changes based on the [diff in the PR for the policy](https://github.com/mozilla/pkipolicy/pull/265/files) (linked from the bug).
=> Fix bug 1814309: Update CA policy to 2.8.1

bedrock/foundation/templates/foundation/annualreport/2009/a-competitive-world.html, bedrock/foundation/templates/foundation/annualreport/2011.html, bedrock/foundation/templates/foundation/annualreport/2019/index.html, bedrock/foundation/templates/foundation/annualreport/2020/index.html, bedrock/foundation/templates/foundation/feed-icon-guidelines/index.html, bedrock/foundation/templates/foundation/licensing/website-content.html
Add width to images in to improve rendering speed.
n/a
http://localhost:8000/en-US/foundation/annualreport/2009/a-competitive-world/
http://localhost:8000/en-US/foundation/annualreport/2011/
http://localhost:8000/en-US/foundation/annualreport/2019/
http://localhost:8000/en-US/foundation/annualreport/2020/
(the dots are in the modal, you do not need to check all of the modals, just spot check)
=> Add width to images in /foundation

bin/compile-requirements.sh, docs/abtest.rst, requirements/dev.in, requirements/dev.txt, requirements/docs.in, requirements/docs.txt, requirements/prod.in, requirements/prod.txt
* Resolves https://github.com/mozilla/bedrock/pull/12725
* Security bump 
* Resolves https://github.com/mozilla/bedrock/pull/12702
* You can check QR code generation still works at http://localhost:8000/de/firefox/107.0.0/whatsnew/
* Resolves https://github.com/mozilla/bedrock/pull/12656
* If you make the docs, you can confirm that the fluent highlighting etc still work there
* Resolves https://github.com/mozilla/bedrock/pull/12701
* Resolves https://github.com/mozilla/bedrock/pull/12682
Integration tests pass https://gitlab.com/mozmeao/bedrock/-/pipelines/775960097
=> Dependency bumps, incl security bump + fluent deps

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
Django security update:
https://www.djangoproject.com/weblog/2023/feb/14/security-releases/
=> Bump for new Django release

bedrock/security/templates/security/client-bug-bounty.html
I am not a native speaker but I believe this is a typo?
https://www.merriam-webster.com/dictionary/eligible
Flagging @dveditz for review :)
N/A
N/A
If relevant:
None
=> typo fix: elligible or eligible

contentful_migrations/package-lock.json
=> Fix @sideway/formula contains Regular Expression Denial of Service (ReDoS) Vulnerability

bedrock/mozorg/templates/mozorg/about/leadership/index.html
Removing Mitchell's mastodon link for now until we get confirmation that she wants it added.
=> Leadership: remove Mitchell’s mastodon link [#12814]

bedrock/mozorg/templatetags/misc.py, bedrock/mozorg/tests/test_helper_misc.py
This started with adding bleach tests for potential future changes.
=> Increase templatetag testing to 100%

bedrock/mozorg/templates/mozorg/about/leadership/index.html
Requested via Slack to update the composition of Shep's household.
http://localhost:8000/en-US/about/leadership/#lindsey-shepard
=> Leadership page: updates to the Shep household [#12827]

bedrock/security/templates/security/bug-bounty.html
=> Add a note saying to email us for bounty questions

media/js/pocket/analytics.es6.js
Fixes a data issue with snowplow for pocket pages.
There's not much to review here, but we worked with the pocket team to figure out what was missing
N/A
http://localhost:8000/en/
=> Fix Snowplow app ID

l10n/en/firefox/accounts.ftl
Added an explanatory comment to one string, tweaked the URL reference on another.
https://github.com/mozilla-l10n/www-l10n/pull/319
=> String fixes (comments) for Fx Accounts page

bedrock/mozorg/tests/test_views.py, bedrock/mozorg/views.py
Innovations team asked for the subject line to change on emails based on which email they are sent to
Updated the test_view.py, so those should still pass.
=> Update mieco email subject

bedrock/security/templates/security/client-bug-bounty.html
=> Correct a footnote in security page

bedrock/legal/templates/legal/terms/builders-challenge.html
Prize values were doubled for the Builders Challenge, the T&C are changed to reflect that.
n/a
=> Update prize values for builders challenge

bedrock/legal/templates/legal/terms/builders-challenge.html
=> Revert "Update prize values for builders challenge"

bedrock/products/templates/products/vpn/download.html, l10n/en/products/vpn/download.ftl
Oops, needed a new string ID. I didn't realize that string had already been sent to localizers.
https://github.com/mozilla-l10n/www-l10n/pull/326#pullrequestreview-1402250323
=> String fix for string fix for VPN download page [fix #13041]

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
* https://docs.djangoproject.com/en/4.2/releases/3.2.19/
* https://github.com/mozilla/bedrock/security/dependabot/61 ("sqlparse contains a regular expression that is vulnerable to Regular Expression Denial of Service")
=> Security bumps: Django and sqlparse

l10n/en/products/vpn/platform-post-download.ftl
Fixes https://github.com/mozilla-l10n/www-l10n/pull/327/files#r1190207043
=> L10n comment fix in l10n/en/products/vpn/platform-post-download.ftl

l10n/en/products/vpn/platform-post-download.ftl
Fixes https://github.com/mozilla-l10n/www-l10n/issues/329
=> Use Firefox Account brand name in platform-post-download.ftl

bedrock/products/templates/products/vpn/includes/download-faq.html, l10n/en/firefox/faq.ftl, l10n/en/products/vpn/platform-post-download.ftl
Addresses comments in https://github.com/mozilla-l10n/www-l10n/pull/328
=> Fluent string fixes

bedrock/mozorg/templates/mozorg/diversity/2021/moco-data.html
This changeset (explain what) in order to (why).
(Outline the main things changed, and if there are particular parts that need extra scrutiny.)
If relevant:
=> Solved issue #13188

Makefile, docs/Makefile, docs/contribute.rst, requirements/dev.txt, requirements/docs.in, requirements/docs.txt, requirements/prod.in, requirements/prod.txt
Plus one small documentation fix while testing the docs dependencies
Plus, plus, moving a make command for docs dependencies to the docs-specific makefile - more logical and more usable
=> Minor dependency bump

l10n/en/products/vpn/platform-post-download.ftl
Fixes https://github.com/mozilla-l10n/www-l10n/issues/331
=> Remove outdated string with error

bedrock/firefox/templates/firefox/flashback/index.html
Finished my testing, removing the experiment code.
This reverts commit 9fa3e9ac229b95c78b1872f643720b72febe4af6.
[Companion PR removing the switch](https://github.com/mozmeao/www-config/pull/520)
=> Revert "Add Convert experiment block to /firefox/flashback (#13230)"

tests/unit/spec/base/datalayer-begincheckout.js
This file name was missed when I was changing the name of everything else from add_to_cart to begin_checkout
=> Update test filename to reflect contents

bedrock/security/templates/security/client-bug-bounty.html
=> Correct a few references to the max payout, which we had changed.

bedrock/base/templates/base-protocol.html
Script is now 404 and no longer needed
=> Remove pontoon.js script (Fixes #13273)

bedrock/products/templates/products/relay/includes/subnav.html, l10n/en/products/relay/shared.ftl
Add FAQ page to Relay subnav
(Outline the main things changed, and if there are particular parts that need extra scrutiny.)
#12876 
http://localhost:8000/en-US/products/relay/
=> Add FAQ page to Relay subnav

bedrock/security/templates/security/bug-bounty/faq.html
Remove references to FPN and Lockwise since they are being sunsetted
=> remove references to FPN and Lockwise

bedrock/settings/base.py
Add Stripe IDs for DEV in US
- add stripe plan IDs for DEV server in US
- remove placeholders for other DEV IDs, this is all we have
#12876
=> Add Stripe IDs for DEV in US

bedrock/mozorg/templates/mozorg/about/leadership/boards.html, bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
Updates to MoFo leadership and board.
#13330 
http://localhost:8000/en-US/about/leadership/mozilla-foundation/
http://localhost:8000/en-US/about/leadership/boards-of-directors/
=> Leadership updates [fix #13330]

bedrock/firefox/templates/firefox/includes/download-button.html
=> Fix ESR alias in download link (Issue #13317)

l10n/en/firefox/nightly/whatsnew.ftl
Addresses: https://github.com/mozilla-l10n/www-l10n/pull/339#issuecomment-1625661767
=> Don't use third-party brand name variables in nightly/whatsnew.ftl

package-lock.json, package.json
Test run https://github.com/mozilla/bedrock/actions/runs/5552765019
=> Bump webpack and related dependencies to latest versions

bedrock/foundation/templates/foundation/annualreport/2021/article/innovation.html, bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
Updates title for J. Bob Alotta
Fixes #13451
=> Update J. Bob Alotta's title

bedrock/products/templates/products/relay/faq.html, bedrock/products/templates/products/relay/includes/bundle.html, bedrock/products/templates/products/relay/includes/features.html, bedrock/products/templates/products/relay/includes/matrix.html, bedrock/products/templates/products/relay/landing.html, bedrock/products/templates/products/relay/premium.html, bedrock/products/templates/products/relay/pricing.html, bedrock/products/templatetags/misc.py, bedrock/settings/base.py, l10n/en/products/relay/bundle.ftl, l10n/en/products/relay/faq.ftl, l10n/en/products/relay/features.ftl, l10n/en/products/relay/matrix.ftl
https://github.com/mozilla-l10n/www-l10n/pull/343#pullrequestreview-1548350918
=> Fluent string fixes for Relay migration

bedrock/products/templates/products/relay/faq.html, bedrock/products/templates/products/relay/includes/matrix.html, bedrock/products/templates/products/relay/includes/waitlist-base.html, bedrock/products/templates/products/relay/landing.html, bedrock/products/templates/products/relay/waitlist/bundle.html, bedrock/products/templates/products/relay/waitlist/phone.html, bedrock/products/templates/products/relay/waitlist/premium.html, bedrock/products/views.py, bedrock/settings/base.py, l10n/en/products/relay/faq.ftl, l10n/en/products/relay/landing.ftl, l10n/en/products/relay/matrix.ftl, l10n/en/products/relay/waitlist.ftl
https://github.com/mozilla-l10n/www-l10n/pull/343#pullrequestreview-1549193385
=> Relay l10n review changes

tests/unit/karma.conf.js, tests/unit/spec/newsletter/form-utils.js
Fixes https://github.com/mozilla/bedrock/actions/runs/5712478016/job/15476031756
=> Fix intermittent test failure in form-utils.js

bedrock/privacy/templates/privacy/index.html
#13466 
http://localhost:8000/privacy/
=> Update access request link on privacy page [fix #13466]

bedrock/security/templates/security/client-bug-bounty.html
Update Client Bug Bounty.  @dveditz has reviewed already
=> Split UXSS out into its own category for payout.

l10n/configs/pontoon.toml
Adds references to new string paths for Relay landing to l10n.toml for recognition by Pontoon.
=> Add new relay paths to l10n toml

l10n/en/mozorg/home-new.ftl
Some guidance for localizers, requested in https://github.com/mozilla-l10n/www-l10n/pull/345#discussion_r1296426538
=> Adding some l10n comments to home page strings

bedrock/foundation/templates/foundation/moco.html, bedrock/mozorg/templates/mozorg/diversity/2021/racial-justice.html
Fixes https://github.com/mozilla/bedrock/issues/13589
=> Fix 500 error on pages due to leadership page redsign (Fixes #13589)

bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
Received an edit to Suba's bio from @enavajas
=> Update bio for Suba

media/css/pocket/style.scss
Didn't import themes into the head of pocket-mode, fix updates styles on different pages
=> Fix protocol issue in pocket mode

bedrock/firefox/templates/firefox/features/fast.html, l10n/en/firefox/features/fast-2023.ftl, l10n/en/firefox/features/password-manager-2023.ftl, l10n/en/firefox/features/private-browsing-2023.ftl, l10n/en/firefox/features/shared.ftl, l10n/en/firefox/features/sync-2023.ftl
A few string updates from comments on https://github.com/mozilla-l10n/www-l10n/pull/347
https://github.com/mozilla-l10n/www-l10n/pull/347
=> String fixes for Firefox feature pages

l10n/en/products/monitor/landing.ftl
Addresses comments in https://github.com/mozilla-l10n/www-l10n/pull/348
=> String fixes for products/monitor/landing.ftl

bedrock/firefox/templates/firefox/features/customize.html, l10n/en/firefox/features/customize-2023.ftl
There was a malformed string throwing errors.
https://github.com/mozilla-l10n/www-l10n/issues/349
http://locahost:8000/firefox/features/customize/
=> String fixes for /firefox/features/customize

docs/l10n.rst
Expand l10n docs with recent freedback from the l10n team.
- how to do HTML attributes
- how to do variables
- more info on brand names
n/a
In your venv: `make livedocs`
=> Improve l10n docs

bedrock/firefox/templates/firefox/accounts.html, bedrock/firefox/templates/firefox/browsers/compare/safari.html, bedrock/firefox/templates/firefox/features/sync.html, bedrock/security/templates/security/third-party-injection-policy.html, l10n/en/firefox/browsers.ftl, l10n/en/firefox/browsers/compare/safari.ftl, l10n/en/firefox/features/password-manager-2023.ftl, l10n/en/firefox/features/sync-2023.ftl, l10n/en/firefox/privacy-hub.ftl, l10n/en/firefox/products.ftl, l10n/en/sub_navigation.ftl
Received feedback from the L10N team regarding the Fluent files we merged regarding the Mozilla accounts update coming up: https://github.com/mozilla-l10n/www-l10n/pull/350
No major string changes, just tiny fix-ups.
I also included tiny string changes (English only, no localization) to the following page:
- http://localhost:8000/en-US/security/third-party-software-injection/
=> Fix Fluent files for Moz accounts update

l10n/configs/pontoon.toml
Fixes https://github.com/mozilla-l10n/www-l10n/issues/352
=> Fix pontoon.toml path for try-picture-in-picture.ftl

tests/pages/products/vpn/landing.py
Fixes https://github.com/mozilla/bedrock/actions/runs/6413748924/job/17413109627
=> Update VPN nav test selector to fix failure

l10n/en/firefox/privacy/passwords.ftl
Addresses https://github.com/mozilla-l10n/www-l10n/pull/355#discussion_r1350541009
=> Fluent string fixes to firefox/privacy/passwords.ftl

docs/l10n.rst, l10n/en/banners/fundraising.ftl, l10n/en/brands.ftl, l10n/en/firefox/browsers.ftl, l10n/en/firefox/browsers/compare/chrome.ftl, l10n/en/firefox/browsers/mobile/focus.ftl, l10n/en/firefox/developer.ftl, l10n/en/firefox/facebook_container.ftl, l10n/en/firefox/new/desktop.ftl, l10n/en/firefox/new/download.ftl, l10n/en/firefox/nightly/whatsnew.ftl, l10n/en/firefox/privacy/passwords.ftl, l10n/en/footer.ftl, l10n/en/mozorg/mission.ftl, l10n/en/mozorg/newsletters.ftl, l10n/en/navigation.ftl, l10n/en/privacy/faq.ftl, l10n/en/products/monitor/shared.ftl, l10n/en/products/vpn/landing.ftl, l10n/en/products/vpn/shared.ftl
Update l10n docs with guidance on obsolete strings.
- Update docs
- Find and replace Outdated -> Obsolete
n/a
In your venv `make livedocs`
=> Update l10n docs with guidance on obsolete strings

bedrock/firefox/templates/firefox/challenge-the-default/landing.html, media/css/firefox/challenge-the-default/_hero.scss
Move CTD CTA on mobile viewports - Fixes #13779
#13779
localhost:8000/de/firefox
=> Move CTD CTA (Fixes #13779)

package-lock.json, package.json
Will tackle the front-end linters in a separate PR
N/A
- `npm start`
=> Bump webpack, babel, sass to latest versions

bedrock/settings/base.py
=> Remove newsletter-strings.json from sitemap.xml (Fixes #13777)

bedrock/firefox/templates/firefox/welcome/page16.html
Referral ID for Moments 16 was incorrect, this PR updates it
#13799
http://localhost:8000/firefox/welcome/16
=> Update referral id for moments 16

bedrock/firefox/templates/firefox/welcome/page16.html
=> Revert "Update referral id for moments 16"

bedrock/firefox/templates/firefox/welcome/page16.html
Change title for VPN Moment 16
n/a
http://localhost:8000/firefox/welcome/16
=> Title update for Vpn Moment 16

bedrock/contentful/management/commands/update_contentful.py
Example output:
```
...
Checking pagePageResourceCenter:nl:55qRE7t9g7lR64HY49kjFk-> Localised? False 
These fields were missing localised content: {'.info.seo.description'}
...
```
=> Improve logging output of Contentful sync to spot what fields might be missing

bedrock/base/management/commands/update_www_config.py, bedrock/careers/migrations/0002_position_internal_job_id.py, bedrock/contentcards/management/commands/update_content_cards.py, bedrock/contentful/management/commands/update_contentful.py, bedrock/externalfiles/management/commands/update_externalfiles.py, bedrock/legal_docs/management/commands/update_legal_docs.py, bedrock/mozorg/management/commands/update_product_details_files.py, bedrock/mozorg/management/commands/update_webvision_docs.py, bedrock/newsletter/management/commands/update_newsletter_data.py, bedrock/pocketfeed/management/commands/update_pocketfeed.py, bedrock/releasenotes/management/commands/update_release_notes.py, bedrock/sitemaps/management/commands/fetch_sitemaps.py, bedrock/sitemaps/management/commands/update_sitemaps_data.py, bedrock/wordpress/management/commands/update_wordpress.py, lib/l10n_utils/management/commands/l10n_update.py, lib/l10n_utils/management/commands/lint_ftl.py
Ruff found some tuples that aren't actually intended to be tuples
=> Fix tupled non-tuples

bedrock/newsletter/templates/newsletter/online-harassment.html, bedrock/newsletter/urls.py, media/css/newsletter/newsletter-online-harassment.scss, media/static-bundles.json
This is a thank you page that will be linked from the online harassment form on formstack [here](https://mozilla.formstack.com/forms/online_harassment)
n/a
http://localhost:8000/en-US/newsletter/security-and-privacy/online-harassment/
=> Add PXI Form thank you page

bedrock/products/templates/products/vpn/download.html, bedrock/products/templates/products/vpn/landing.html, l10n/en/products/vpn/landing.ftl
Update Mozilla VPN Macos version requirements
N/A
https://mozilla-hub.atlassian.net/browse/VPN-5829
Not sure?
=> Update MozVPN MacOS version requirements

bedrock/products/templates/products/vpn/landing.html, l10n/en/products/vpn/landing.ftl
Addresses https://github.com/mozilla-l10n/www-l10n/pull/363#discussion_r1387365841
N/A
http://localhost:8000/en-GB/products/vpn/
=> VPN landing page string FTL fix

bedrock/newsletter/templates/newsletter/online-harassment.html
Updates copy / makes the email form a little less confusing.
#13874
http://localhost:8000/en-US/newsletter/security-and-privacy/online-harassment/
=> Update PXI form thank you page (Fixes #13874)

bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
#13889 
http://localhost:8000/about/leadership/
=> Leadership: update Mitchell’s bio and Oscar’s title [fix #13889]

gcp/bedrock-demos/cloudrun/mozorg-demo.env.yaml
This reverts commit 08cc575e7b301d860eadb36c6355b5357c3f10da.
=> Revert "Set BOUNCER_URL for demos to be the dev bouncer, for all demos (#13981)"

bedrock/mozorg/templates/mozorg/about/leadership/includes/boards.html
Adds a bio for Amy Keating to the leadership page.
#14001 
http://localhost:8000/about/leadership/#amy-keating
=> Leadership: Add bio for Amy Keating [fix #14001]

bedrock/firefox/templates/firefox/welcome/page17/page17-a.html, bedrock/firefox/templates/firefox/welcome/page17/page17-b.html, bedrock/firefox/templates/firefox/welcome/page17/page17-c.html, media/css/firefox/welcome17.scss
Updates and adds translations for Moments 17
Translation updates: https://drive.google.com/drive/folders/1pAT1vwkqLgKqTu-hdmt1UvOIH1u04a20?usp=drive_link
n/a
For en-US, de, and fr:
http://localhost:8000/firefox/welcome/17a/
http://localhost:8000/firefox/welcome/17b/
http://localhost:8000/firefox/welcome/17c/
=> Update and add translations for Moments 17

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-na.html, media/css/firefox/whatsnew/whatsnew-122-na.scss
Adds a disclaimer to the NA WNP for Firefox 122 to further clarify the basis for comparison.
http://localhost:8000/en-US/firefox/122.0/whatsnew/
=> Add disclaimer to NA WNP 122 [#14058]

bedrock/mozorg/templates/mozorg/mpl/2.0/faq.html, media/css/mozorg/license-faq.scss, media/static-bundles.json
Some updates came in for the Public License FAQ page.
[Copy doc](https://docs.google.com/document/d/1P2w5KGg-DAc54zP-BW1l0EqqKM50jSXXd1Ez9JXAzvo/edit)
https://github.com/mozilla/bedrock/issues/14137
http://localhost:8000/en-US/MPL/2.0/FAQ/
=> Updated public license FAQ [fixes #14137]

bedrock/firefox/templates/firefox/accounts.html, bedrock/firefox/templates/firefox/home/index-master.html, bedrock/firefox/templates/firefox/privacy/products.html, bedrock/firefox/templates/firefox/products/index.html, bedrock/mozorg/templates/mozorg/home/home-new.html, bedrock/newsletter/templates/newsletter/updated.html, l10n/en/mozorg/home-new.ftl, media/css/mozorg/home/home-new.scss
Updates Monitor copy for brand update - has separate copy for en-US vs rest of world.
🚨 DO NOT MERGE TILL February 6th! 🚨 
[Link](https://docs.google.com/document/d/1KPdepCn4bNKwP3BLgihg82DfGrI8BsMfe2JEnclpZiw/edit) to copy changes
Note: I made all changes on the document except for those to the firefox moments pages
#14047
http://localhost:8000/en-US/?v=2
http://localhost:8000/en-US/firefox/accounts/
http://localhost:8000/en-US/firefox/privacy/products/
http://localhost:8000/en-US/firefox/products/
http://localhost:8000/en-US/newsletter/updated/
=> Update Monitor copy [Feb 6th]

bedrock/mozorg/templates/mozorg/home/home-new.html
=> Fix typo on home page (Fixes #14184)

bedrock/mozorg/templates/mozorg/about/leadership/includes/boards.html, bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
=> Leadership page updates

bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.fr.html
Minor copy edit in the FAQ section.
#14169 
http://localhost:8000/fr/firefox/challenge-the-default/
=> Copy update on French CTD page [fix #14169]

bedrock/firefox/templates/firefox/features/translate.html, bedrock/firefox/templates/firefox/nightly/whatsnew.html, l10n/en/firefox/features/translate.ftl, l10n/en/firefox/nightly/whatsnew.ftl
Updates and fixes requested in https://github.com/mozilla-l10n/www-l10n/pull/379
=> String fixes for Translation page

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-static.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-video.html, media/css/firefox/whatsnew/whatsnew-124-na.scss
A few small copy updates and tweaks were requested for the Monitor Plus 124 WNP
#14296
- http://localhost:8000/en-US/firefox/124.0/whatsnew/?v=1
- http://localhost:8000/en-US/firefox/124.0/whatsnew/?v=2
=> WNP 124 NA updates for Monitor Plus (Issue #14296)

tests/unit/spec/base/datalayer-begincheckout.js, tests/unit/spec/base/datalayer-productdownload.js, tests/unit/spec/products/vpn/invite.js
This should hopefully help fix the following test failure that sometimes occurs: https://github.com/mozilla/bedrock/actions/runs/8278198659/job/22650052456 🤞 
#14319
`npm test`
=> Fix intermittent JS test failure (Fixes #14319)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-pdf.html
Updates PDF link to escape CDN cache
http://localhost:8000/en-US/firefox/124.0/whatsnew/
=> Update WNP 124 PDF link

docs/attribution/0001-analytics.rst
Updates dashboard links for Glean data in Looker
N/A
=> Update Glean dashboard links

package-lock.json, package.json, webpack.config.js
Bumps webpack and related front-end dependencies
N/A
- `npm start`
Successful test run: https://github.com/mozilla/bedrock/actions/runs/8520662891
=> Bump webpack and related dependencies

docs/architecture/decisions/0012-wagtail-for-cms.md
This is mostly to test whether the ReadTheDocs webhook is 100% happy again
=> Add a positive consequence to the Wagtail ADR

docs/l10n.rst
Trivial wording fix to verify RTD webhooks
Close #14464
=> docs: Update l10n obsolete removal wording

l10n/en/banners/consent-banner.ftl
Addresses https://github.com/mozilla-l10n/www-l10n/pull/395#discussion_r1576573560
=> Use mdash in consent-banner.ftl

l10n/en/privacy/cookie-settings.ftl
Revises a string for easier translation (has been approved by legal)
https://github.com/mozilla/bedrock/issues/14505
=> Revise legal text in en/privacy/cookie-settings.ftl (Fixes #14505)

.github/PULL_REQUEST_TEMPLATE.md
Adds a simple disclosure checkbox to the bedrock pull request template, asking code contributors to indicate if they used AI tools to author any of the code in their PR.
=> Add AI disclosure to PR template

bedrock/products/templates/products/landing.html, l10n/en/firefox/products.ftl
Addresses comments in https://github.com/mozilla-l10n/www-l10n/pull/397
=> L10n fixes for products.ftl

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html, bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2023.html, bedrock/mozorg/urls.py
Added the new transparency report for July–December 2023
fixes https://github.com/mozilla/bedrock/issues/14508
=> H2 2023 Transparency Report

bedrock/security/templates/security/web-bug-bounty.html
Follow up PR for https://github.com/mozilla/bedrock/pull/14536 to fix the links on https://www-dev.allizom.org/en-US/security/web-bug-bounty/
=> fix remaining hackerone program link

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-eu.html
Fixes a typo reported in Slack
N/A
http://localhost:8000/es-ES/firefox/126.0/whatsnew/
=> Fix typo in es-ES WNP 126

l10n/en/firefox/features/private-browsing-2023.ftl
See https://github.com/mozilla/bedrock/pull/14580#pullrequestreview-2063679429
=> Clarify that older string is obsolete

bedrock/privacy/templates/privacy/faq.html, l10n/en/privacy/faq.ftl
Updated copy based on [this copy doc](https://docs.google.com/document/d/1cVfzhYC4US7yzkn2pxoPhUYwSf5B1Qeo2HhffGgquTY/edit#heading=h.j5d4kikac80n)
Fixes https://github.com/mozilla/bedrock/issues/14652
http://localhost:8000/en-US/privacy/faq/
=> Update copy in `/privacy/faq` page

bedrock/cms/tests/test_models.py, bedrock/cms/tests/test_rendering.py, bedrock/settings/base.py, bedrock/urls/mozorg_mode.py
This is to help us test performance issues
=> Add in setting to control whether or not Wagtail's page-serving logic is enabled

bedrock/settings/base.py
The previous commit removed greenlet
=> Remove greenlet import

package-lock.json, package.json, requirements/dev.txt, requirements/prod.in, requirements/prod.txt
No major changes for this one that effect us, just a bump to the latest version.
N/A
- `make preflight`
- `npm start`
=> Bump Glean.js to v5.0.2

.github/workflows/pull_request_tests.yml
Updates python CI test runner version to JS runner version for consistency.
Since #14683 the matching version note is not true anymore. Let's try ubuntu-latest too…
🚫🐞
=> Update GHA python job to ubuntu-latest

Makefile
Need to bootstrap the postgres DB first
=> Don't run worker queue node for now

.github/workflows/playwright.yml, tests/playwright/specs/footer.spec.js, tests/playwright/specs/navigation.spec.js, tests/playwright/specs/products/firefox/firefox-home.spec.js, tests/playwright/specs/products/firefox/firefox-new.spec.js, tests/playwright/specs/products/vpn/vpn-download.spec.js
Adds GitHub action to run tests once per day against dev.
#14701
=> Run Playwright tests once per day against dev (Fixes #14701)

.github/workflows/playwright.yml
Should hopefully fix https://github.com/mozilla/bedrock/actions/runs/9585021893/job/26429986098
=> Specify correct directory in playwright.yml

bedrock/settings/__init__.py, bedrock/settings/base.py
This might increase CPU load but also may reduce possible memory leaks
=> Explore LocMemCache to reduce complexity

bedrock/settings/__init__.py, bedrock/settings/base.py
This reverts commit 195d09b65609ce51a9b6dac0d0550cca5093a92a.
=> Revert "Explore LocMemCache to reduce complexity"

bedrock/settings/base.py
Starting out with CONN_MAX_AGE of ~600~ 0, to match the default. We can then tune from there
=> Add configurability for DB connection params;

.github/workflows/integration_tests.yml
Should hopefully fix: https://github.com/mozilla/bedrock/actions/runs/9779024892/attempts/1 🤞
=> Notify failure if Playwright tests fail in CI (Fixes #14785)

.github/workflows/integration_tests.yml
Foiled by YAML again. Hopefully fixes https://github.com/mozilla/bedrock/actions/runs/9780825120
=> Fix quotes in integration_tests.yml

.github/workflows/integration_tests.yml
Fixes https://github.com/mozilla/bedrock/actions/runs/9791704959
=> Always run Playwright tests even if Selenium fails

tests/playwright/specs/products/firefox/firefox-home.spec.js, tests/playwright/specs/products/firefox/firefox-new.spec.js
Should hopefully fix https://github.com/mozilla/bedrock/actions/runs/9863305875
=> Fix Playwright test failure on /firefox/new/

bedrock/settings/__init__.py
- Move `frame-ancestors 'none'` to report-only
- Add `frame-ancestors 'self'` to CMS admin for page previews
- Remove `script-src unsafe-inline` from report-only for testing
- Clean up CSP overrides
- Add `img-src blob:` to RO overrides also
=> Various content security policy fixes

bedrock/firefox/templates/firefox/welcome/page14.html
Fixes https://github.com/mozilla/bedrock/actions/runs/10076497234/job/27856998373
=> Fix firefox/welcome/14/ images (#14857)

.github/dependabot.yml
Attempts to fix https://github.com/mozilla/bedrock/pull/14834/checks?check_run_id=28146270934
=> Fix dependabot.yaml

requirements/dev.txt, requirements/prod.in, requirements/prod.txt
See https://www.djangoproject.com/weblog/2024/aug/06/security-releases/
=> Bump Django to latest secure 4.2.x version

bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
This PR updates leadership bio for Mark Surman.
https://github.com/mozilla/bedrock/issues/14994
=> update leadership bio  [fix #14994]

bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
https://github.com/mozilla/bedrock/issues/14994#issuecomment-2311012154
http://localhost:8000/about/leadership/#mark-surman
=> Leadership page, update Surman’s bio [#14994]

tests/functional/firefox/test_all.py
Fix failing integration test on /all
- removed a superfulous slash
n/a
=> Fix failing integration test on /all

docs/cms.rst
=> Add docs about not enabling page-tree syncing between locales

media/css/m24/base.scss, media/css/m24/vars/animation.scss, media/css/m24/vars/color.scss, media/css/m24/vars/spacing.scss, media/css/m24/vars/text.scss
CSS custom properties extracted from the Figma files, and then abstracted to a Sass variable.
- color
- spacing
- text
#14826
=> Add variables for refresh

bedrock/newsletter/forms.py, tests/functional/newsletter/test_newsletter_embed.py, tests/functional/test_about.py, tests/playwright/specs/home.spec.js
https://github.com/mozilla/bedrock/actions/runs/10809040577
=> Fix home/about page test failures

tests/functional/newsletter/test_newsletter_embed.py, tests/pages/newsletter/knowledge_is_power.py
This should hopefully fix: https://github.com/mozilla/bedrock/actions/runs/10816999113
=> Remove KiP newsletter tests

bedrock/base/templates/includes/protocol/footer/footer-newsletter.html, bedrock/base/templates/includes/protocol/footer/footer-refresh.html, bedrock/mozorg/templates/mozorg/about/index-m24.html, bedrock/mozorg/templates/mozorg/home/home-m24.html, l10n/en/footer-refresh.ftl, media/css/m24/components/footer-refresh.scss
Tweaks for MVP footer.
- changed to using the Sass variables which reference CSS variables, instead of the Sass variables which reference Sass variables (I know this is confusing, I'm confused and I wrote it)
- increased specificity on some link state style declarations
- focus style tweaks
- added spacing between list items
- moved pixelated border into footer include
- removed underline from donate button (brought up during community feedback)
- added newsletter sign up form to MVP homepage
- add dividing line between newsletter signup and footer links
#14830
=> Tweaks for MVP footer

media/js/mozorg/home/fundraising-nav-cta.es6.js
To hit this error locally you need following environment variables set:
```
SWITCH_M24_HOME=off
SWITCH_FUNDRAISING_BANNER_JULY2024=off
```
#15126
- http://localhost:8000/en-US/?v=1
- http://localhost:8000/en-US/?v=2
=> Fix JS error thrown by nav CTA experiment (Fixes #15126)

media/css/m24/components/footer-newsletter.scss, media/css/m24/components/footer-refresh.scss
Please just review the form a11y improvements. There's some tweaking to be done on mobile/tablet sizes still but those are outside the scope of this PR.
- separated newsletter styles from footer ones
- aligned newsletter form and footer links
- input and selects now have visible focus states
- input and select contrast is improved
- selects have down arrow as affordance for selecting a value
- removed border radius to match Figma
- more spacing around links in the footer on mobile sizes
#15129
#14830
The newsletter should appear at the bottom of the homepage.
=> Refresh: #a11y improvements to footer newsletter #15129

bedrock/base/templates/macros-m24.html, bedrock/mozorg/templates/mozorg/about/includes/m24/amplify.html, bedrock/mozorg/templates/mozorg/home/includes/m24/ai-grid.html, bedrock/mozorg/templates/mozorg/home/includes/m24/resources-grid.html, media/css/m24/grid.scss
Changes grid tiles to behave card-like with block links.
=> Refresh: make grid tiles block links

l10n/en/navigation_refresh.ftl
Addresses comments in https://github.com/mozilla-l10n/www-l10n/pull/431
=> Use sentence case for navigation headings and titles

bedrock/settings/__init__.py
Updates our CSP settings so that we send reports to Sentry for both the enforced and report-only policies. We want to know if the enforced policy ever gets triggered so we can fix as soon as possible.
Add something like this to your local `.env` file:
```
CSP_REPORT_URI=http://localhost:8000/_csp
```
and verify the headers for `Content-Security-Policy` contain a `report-uri`.
=> Also send reports for the enforced CSP

bedrock/foundation/templates/foundation/trademarks/list.html
Just commenting them out for now, pending more information and timing of the brand launch.
#15091 
http://localhost:8000/en-US/foundation/trademarks/list/
=> Remove new brand assets from trademarks list [#15091]

bedrock/firefox/templates/firefox/features/translate.html, bedrock/firefox/views.py
New supported language released.
Resolves #15209
/en-US/firefox/features/translate/
/nl/firefox/features/translate/
=> Add Swedish to translate feature list

l10n/en/products/vpn/pricing-2023.ftl
Adds new Fluent strings for upcoming VPN expansion copy
https://github.com/mozilla/bedrock/issues/15262
=> Add Fluent strings for VPN wave vii expansion (issue #15262)

bedrock/base/tests/test_middleware.py, bedrock/settings/__init__.py
Update to add `CSP_RO_REPORT_URI` for separate reporting endpoints for enforced vs report-only CSP headers.
=> Add CSP_RO_REPORT_URI logic

bedrock/firefox/templates/firefox/challenge-the-default/includes/wednesday.html
Missed this one in https://github.com/mozilla/bedrock/pull/15255
https://github.com/mozilla/bedrock/issues/15137
http://localhost:8000/de/firefox/challenge-the-default/
=> Prevent aria-hidden button receiving focus (#15137)

bedrock/products/templates/products/vpn/features.html, bedrock/products/views.py
Missed this in https://github.com/mozilla/bedrock/pull/15325
https://github.com/mozilla/bedrock/issues/15262
http://localhost:8000/en-US/products/vpn/features/
=> Conditionally show  guarantee copy on vpn/features page (#15262)

bedrock/settings/base.py
Updates list of languages the VPN client is translated in.
#15326
=> Update VPN supported landuages (Fixes #15326)

media/css/m24/components/navigation-refresh.scss
Update m24 nav background color and border style.
https://github.com/mozilla/bedrock/issues/15310
=> update navigation style (fix #15310)

l10n/en/firefox/welcome/page23.ftl
Fixes a missing word in a string.
https://github.com/mozilla-l10n/www-l10n/pull/444#discussion_r1811106526
http://localhost:8000/firefox/welcome/23/
=> String fix for welcome 23 [#15162]

bedrock/mozorg/templates/mozorg/about/includes/m24/community.html, bedrock/mozorg/templates/mozorg/about/includes/m24/idea.html, bedrock/mozorg/templates/mozorg/about/includes/m24/impact.html, bedrock/mozorg/templates/mozorg/about/includes/m24/leadership.html, bedrock/mozorg/templates/mozorg/about/index-m24.html, media/css/m24/showcase.scss
This PR updates about page DEI and community sections to match the design updates.
https://github.com/mozilla/bedrock/issues/15301
- Turn on switch M24_WEBSITE_REFRESH
=> update about page DEI and community sections (fix #15301)

bedrock/mozorg/context_processors.py, bedrock/settings/base.py
During the pocketfeed removal I noticed some other settings that were old and unused.
=> Remove unused settings

.pre-commit-config.yaml, media/js/firefox/welcome/welcome19-to-24.js, package-lock.json, package.json
Bumps front-end linter dependencies and updates pre-commit hook
N/A
- `npm run lint`
=> Update front-end linters

bedrock/base/templates/macros-m24.html, bedrock/mozorg/templates/mozorg/about/includes/m24/amplify.html, bedrock/mozorg/templates/mozorg/about/includes/m24/careers.html, bedrock/mozorg/templates/mozorg/about/includes/m24/hero.html, bedrock/mozorg/templates/mozorg/home/includes/m24/ai-grid.html, bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html, bedrock/mozorg/templates/mozorg/home/includes/m24/products.html, bedrock/mozorg/templates/mozorg/home/includes/m24/resources-grid.html, media/css/m24/base.scss, media/css/m24/careers.scss, media/css/m24/gallery.scss, media/css/m24/hero.scss, media/css/m24/intro.scss, media/css/m24/launchpad.scss
Rename components to match designs
Quick find/replace to update some component names.
Fix #15429
=> Rename components to match designs (#15429)

bedrock/security/templates/security/bug-bounty/faq.html
=> Update the FAQ entry on bug bounty non-default configurations.

media/css/m24/components/footer-refresh.scss
Fixes https://github.com/mozilla-sre-deploy/deploy-bedrock/actions/runs/11723676265/job/32655859085
=> Remove unused mastodon image reference from footer

bedrock/mozorg/templates/mozorg/home/includes/m24/donate.html, media/css/m24/donate.scss, media/img/m24/todo-21-9.svg
This PR updates the M24 homepage donate section styles to match the latest design changes.
https://github.com/mozilla/bedrock/issues/15480
=> homepage donate section style update (fix #15480)

media/css/m24/base.scss, media/css/m24/components/pencil-banner.scss, media/css/m24/flag.scss, media/css/m24/launchpad.scss, media/css/m24/showcase.scss
We identified these as changes to make in a meeting designed to get parity between the design and site.
- they're just tweaks
n/a
=> Refresh: Tweaks from design review session

bedrock/sitemaps/templates/sitemap.xml
This is some more cleanup I missed from the last PR #15224
=> Ref #15224: Remove the lastmod line from the sitemap template

bedrock/mozorg/templates/mozorg/about/includes/m24/amplify.html, bedrock/mozorg/templates/mozorg/about/includes/m24/careers.html, bedrock/mozorg/templates/mozorg/about/includes/m24/community.html, bedrock/mozorg/templates/mozorg/about/includes/m24/intro.html, bedrock/mozorg/templates/mozorg/about/includes/m24/manifesto.html, bedrock/mozorg/templates/mozorg/about/index-m24.html, bedrock/mozorg/views.py, l10n/en/mozorg/about-m24.ftl, media/css/m24/feature.scss
Convert homepage strings to ftl identifiers.
#15299
=> Refresh: About page strings (Fix #15299)

l10n/configs/pontoon.toml, l10n/en/mozorg/about-m24.ftl, l10n/en/navigation_refresh.ftl
Open about-m24.ftl for translation and change Rise25 to brand name.
=> Refresh: About page l10n fixes

bedrock/mozorg/templates/mozorg/home/includes/m24/donate.html, media/css/m24/donate.scss
Donation block tweak source order and spacing.
This doesn't match the Figma because a new spacing variable has been introduced to the system. For desktop I tried to match the spacing in the showcase component for consistency with the spacing currently on the site.
We don't have a final image for this.
=> Refresh: Donation block tweak source order and spacing

bedrock/mozorg/templates/mozorg/about/includes/m24/community.html, bedrock/mozorg/templates/mozorg/about/includes/m24/manifesto.html, bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html, bedrock/mozorg/templates/mozorg/home/includes/m24/issues-gallery.html, media/css/m24/components/footer-refresh.scss, media/css/m24/components/navigation-refresh.scss, media/css/m24/root.scss, media/css/m24/theme.scss, media/css/m24/transition.scss, media/css/m24/vars/_color.scss
Update color palette
- made footer off-black
- update colours to match most recent brand color palette
- tweak some colors to better match Figma
#14826 
Everything should look the same as before except the footer should be ever so slightly less black.
=> Refresh: Update color palette

bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html, l10n/en/mozorg/home-m24.ftl
=> Fix bad copy/paste

bedrock/mozorg/templates/mozorg/home/includes/m24/ai-gallery.html, bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html, bedrock/mozorg/templates/mozorg/home/includes/m24/showcase.html, l10n/en/mozorg/home-m24.ftl
Updated tag type and link for Llamafile. Swapped first two topics in media springboard
Fix #15688 
Fix #15681
=> Minor fixes (Fix #15688 Fix #15681)

media/css/m24/components/navigation-refresh.scss
This PR updates the nav menu underline to support large fonts.
- update font setting to range from very small to very large
https://github.com/mozilla/bedrock/issues/15635
http://localhost:8000/en-US
=> Updater nav menu underline to support large fonts (fix #15635)

bedrock/foundation/templates/foundation/annualreport/2024/article/2-5-ryan-sipes.html
Update article title
Fix #15746
http://localhost:8000/en-US/foundation/annualreport/2024/article/success-through-two-way-conversations-with-our-community/
=> SOM: Page title update (Fix #15746)

bedrock/mozorg/templates/mozorg/home/includes/m24/showcase-som.html
=> SoM: Lazy load showcase image

bedrock/foundation/templates/foundation/annualreport/2024/article/2-3-jane-silber.html
=> Fix http -> https for link

bedrock/foundation/templates/foundation/annualreport/2024/article/0-1-mark-surman.html
=> Fix link: http->https

bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html
Add analytics to springboard links
#15416 
View source and look for `data-link-text`.
=> Add analytics to springboard links

bedrock/foundation/templates/foundation/annualreport/2024/article/4-1-ayah-bdeir.html, bedrock/foundation/templates/foundation/annualreport/2024/includes/macros.html
Update's Ayah's official title
#15748
- http://localhost:8000/en-US/foundation/annualreport/2024/
- http://localhost:8000/en-US/foundation/annualreport/2024/article/shaping-ai-we-can-trust-mozillas-portfolio-at-work/
=> Update job title on SoM 20204 page (Fixes #15748)

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx134-ca.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx134-gb.html, bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx134-us.html
Last-minute revisions for English, as well as a few little code fixes I initially overlooked.
#15750 
http://localhost:8000/en-US/firefox/134.0/whatsnew/
http://localhost:8000/en-US/firefox/134.0/whatsnew/?v=1
http://localhost:8000/en-US/firefox/134.0/whatsnew/?v=2
http://localhost:8000/en-CA/firefox/134.0/whatsnew/
http://localhost:8000/en-CA/firefox/134.0/whatsnew/?v=1
http://localhost:8000/en-CA/firefox/134.0/whatsnew/?v=2
http://localhost:8000/en-GB/firefox/134.0/whatsnew/
http://localhost:8000/en-GB/firefox/134.0/whatsnew/?v=1
http://localhost:8000/en-GB/firefox/134.0/whatsnew/?v=2
=> Copy updates for WNP134 [#15750]

.github/workflows/build-and-push.yml
=> update the prod image tag

.github/workflows/build-and-push.yml
=> typo in the name of the intergration tests branch

bedrock/firefox/templates/firefox/share.html
Update copy on Firefox share page
#15861 
http://localhost:8000/en-US/firefox/share/
http://localhost:8000/en-CA/firefox/share/
=> Update copy on Firefox share page

bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
changes made in the below file
bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
closes #15890
=> [Refresh] Added utm_params to Thunderbird link in nav

bedrock/firefox/redirects.py, bedrock/firefox/tests/test_redirects.py
- **Refactor mobile_app redirect function**
- **Add SMI campaign options to mobile redirector**
=> Fix #15951: Add SMI campaign options to mobile redirector

bedrock/mozorg/templates/mozorg/home/includes/m24/ai-gallery.html, l10n/en/mozorg/home-m24.ftl
This PR updates l10n strings with versions.
Copy on Gallery section on About Us page should remain the same.
Original issue (with copy): https://github.com/mozilla/bedrock/issues/15933
www-l10n feedback: https://github.com/mozilla-l10n/www-l10n/pull/474#pullrequestreview-2596977571
http://localhost:8000/en-CA/about/
=> update l10n strings with versions

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
This commit was missed out of the prod push
=> Hotfix to root store policy

bedrock/mozorg/templates/mozorg/about/policy/transparency/2024.html
#16039
http://localhost:8000/en-US/about/policy/transparency/2024/
=> Copy update to /about/policy/transparency/2024/ (Fixes #16039)

bedrock/privacy/templates/privacy/includes/privacy-basics.html
Per conversation with legal, these are the correct links.
=> Correct links in Firefox PN for managing privacy settings

media/css/firefox/welcome.scss, media/css/legal/terms-firefox-2025.scss, media/css/mozorg/rise25/rise25.scss, media/css/privacy/privacy-firefox-2025.scss, media/css/products/vpn/landing-refresh.scss
Formatting updates for Privacy Notice & Terms of Use
These were left out of the initial formatting changes because of time constraints:
- Restore smooth scrolling on select pages 
- I made this global and it broke some tests so we're back to doing it ad-hoc
- This should revert the removals in #16009 
- This should also add it to the PN and ToU
#15982
http://localhost:8000/en-US/privacy/firefox/#notice
http://localhost:8000/fr/privacy/firefox/#notice
http://localhost:8000/en-US/about/legal/terms/firefox/
http://localhost:8000/fr/about/legal/terms/firefox/
=> Formatting updates for PN and ToU #15982

bedrock/legal/templates/legal/terms/firefox-2025.html, bedrock/privacy/templates/privacy/notices/firefox-2025.html, media/css/legal/terms-firefox-2025.scss, media/css/privacy/privacy-firefox-2025.scss, media/css/protocol/components/legal-toc.scss, media/js/base/legal-toc.es6.js, media/static-bundles.json
Add sticky toc to PN and TOU #15982
- Make table of contents sticky when there's enough height
- Indicate current section in TOC
#15982
http://localhost:8000/en-US/privacy/firefox/#notice
http://localhost:8000/fr/privacy/firefox/#notice
http://localhost:8000/en-US/about/legal/terms/firefox/
http://localhost:8000/fr/about/legal/terms/firefox/
=> Add sticky toc to PN and TOU #15982

.adr-dir
Now nested on level deeper.
#13288
=> Update .adr-dir link

package-lock.json
=> (chore) Security: Bump babel and eslint's plugin-kit

bedrock/products/models.py, bedrock/settings/base.py
Add MonitorArticlePage to allow list
n/a
Can you add a Monitor Article page under a Monitor Article Index Page with `DEV=False`
=> Add MonitorArticlePage to allow list

bedrock/firefox/templates/firefox/all/base.html
#16104
http://localhost:8000/firefox/all/
=> Add add nofollow to pages under /all (Fixes #16104)

.github/l10n/check_toml_configs.py, .github/workflows/build-and-push.yml, .github/workflows/pull_request_tests.yml, .pre-commit-config.yaml, l10n/en/firefox/welcome/page20-21.ftl, l10n/en/firefox/welcome/page22.ftl, l10n/en/firefox/welcome/page24.ftl, media/css/m24/components/navigation-refresh.scss, media/css/m24/launchpad.scss, media/css/protocol/components/_navigation-ie.scss, tests/pages/__init__.py
Add pyupgrade and django-upgrade to pre-commit hooks, then run full pre-commit on all files, which caught some missed files.
=> Update pre-commit and fix errors

bedrock/settings/__init__.py
Using Python sets allows for de-duplication and, imo, simpler logic for merging or manipulating the values.
The django-csp project, when it notices the CSP values are sets, will convert to a list using `sorted` so we have stable sorting, which is good for caching. Previously the pattern of `list(set(...))` for de-duplication may not have been a good practice and could have produced unstable headers.
=> Move CSP settings to be sets instead of lists

media/css/privacy/privacy-firefox-simple.scss
Linearize tables for in product view of privacy notice.
I just copied the working production code from one file to another. There are probably some maintainability improvements to be made with these sets of files but now's not a good time for that.
Fix #16235
http://localhost:8000/en-US/privacy/firefox/?v=product#lawful-bases
=> Linearize ToS tables on product variant (Fix #16235)

bedrock/settings/base.py
Correctly categorize Indian locales
#16253 
View `/locales/` to verify the correct categorization.
=> Correctly categorize Indian locales

bedrock/settings/__init__.py
This refactors the CSP settings a bit to consolidate patterns, layer on better security practices, and bring some of the report-only policies into the enforced policy.
I tried to break this down into logical commits as much as possible to help show the rationale, but happy to connect for a walk-through if needed.
#11943 
#14896
#15555
I did some local driving and fixed issues that were found.
=> Refactor CSP settings

l10n/en/firefox/browsers/mobile/android.ftl, l10n/en/firefox/browsers/mobile/ios.ftl
Other occurrences use the correct casing
Using the same v2 string as the update is still waiting in l10n review.
https://github.com/mozilla-l10n/www-l10n/pull/511#pullrequestreview-2998920872
=> Fix Internet (… case in fluent string)

docs/docs/attribution/0001-analytics.md, docs/docs/mozilla-accounts.md, l10n/en/firefox/more/misinformation.ftl, l10n/en/mozorg/home-new.ftl, media/css/mozorg/home/home-new.scss, media/js/base/datalayer-productdownload.es6.js, tests/unit/spec/base/datalayer-productdownload.js, tests/unit/spec/base/fxa-attribution.js
This PR is a follow-up of the [Pocket removal PR](https://github.com/mozilla/bedrock/pull/16365). 
Details of changes: https://github.com/mozilla/bedrock/pull/16365#pullrequestreview-2998627350
https://github.com/mozilla/bedrock/issues/16358
=> pocket removal clean up (fix #16358)

bedrock/products/templates/products/monitor/cms/article.html
=> Add missing closing tag

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx143-row.html
WNP en-CA/GB copy updates
- remove S2S feature
- update section title & subtitle
n/a (Slack)
http://localhost:8000/en-CA/firefox/143.0/whatsnew/
=> WNP en-CA/GB copy updates

bedrock/security/management/commands/update_security_advisories.py
Avoids this
```
(bedrock) [steve] ~/Code/bedrock $ ./manage.py update_security_advisories                             [hotfix-secadvisory-parsing]
/Users/steve/.pyenv/versions/bedrock/lib/python3.12/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
INFO 2025-09-16 07:14:10,472 logging METRICS|2025-09-16 07:14:10|gauge|cache.size|10|#cache:fluent
Updating repository.
................................................................................................................................................................................. …
```
=> (fix) Allow security advisories to not have a 'description' key in the source data

bedrock/foundation/templates/foundation/moco.html
=> chore: Update Board of Directors list

bedrock/base/templates/includes/protocol/footer/footer-refresh.html, l10n/en/footer-refresh.ftl
Do not fallback.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/WT-296)
┆Priority: P2
┆Sprint: Backlog
=> Remove old tagline.
