mozilla/bedrock

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html

This is an update of the eligible web properties for new product initiatives
Verify that formatting rendered properly for the new sites added.
@moz-jvehent @bhourigan @april

Add new product FQDNs to Web Bounty Eligible sites

---

package.json

Removes a warning in the console when installing dependencies.
https://github.com/mozilla/bedrock/issues/9067

Remove bin entry for browser-sync in package.json (Fixes #/9067)

---

bedrock/legal/templates/legal/terms/mozilla-vpn.html
bedrock/legal/urls.py
bedrock/privacy/templates/privacy/base-protocol.html
bedrock/privacy/templates/privacy/notices/mozilla-vpn.html
bedrock/privacy/urls.py
bedrock/privacy/views.py

Adds TOS and privacy policy pages for Mozilla VPN.
This needs to be live in production on **14 July, 2020**
#9138 
http://localhost:8000/about/legal/terms/mozilla-vpn/
http://localhost:8000/privacy/mozilla-vpn/
https://www-demo-pr-9140.herokuapp.com/about/legal/terms/mozilla-vpn/
https://www-demo-pr-9140.herokuapp.com/privacy/mozilla-vpn/

[fix #9138] Add terms and privacy notice for Mozilla VPN

---

Dockerfile
bedrock/settings/base.py
requirements/base.txt

The default list of latency buckets contains 17 entries. My proposal is just 8.
https://github.com/korfuri/django-prometheus/blob/5ca09db237dc2c60c5eb397b95e2b610c3557042/django_prometheus/middleware.py#L8-L26

Reduce the number of latency buckets for Prometheus

---

media/css/protocol/components/_navigation.scss
media/js/base/protocol/init-navigation.js

- Adds a subtle bounce animation to the navigation CTA button (both download and FxA) shortly after page load.
#9009

Animate global nav button (Fixes #9009)

---

bedrock/mozorg/templates/mozorg/home/home-de.html
bedrock/mozorg/templates/mozorg/home/home-en.html
bedrock/mozorg/templates/mozorg/home/home-fr.html
bedrock/mozorg/views.py
media/css/mozorg/home/home-en.scss
media/static-bundles.json

Update homepage layout:
https://github.com/mozilla/bedrock/issues/9135
New cards merged to www-admin in https://github.com/mozmeao/www-admin/pull/76. They are in a different directory so the live page will work until this update is published and then the old folder can be removed.
I could not see them locally so you may need to test on the heroku deployment.
Make sure I didn't break DE or FR.

EN homepage redesign

---

bedrock/firefox/templates/firefox/new/desktop/download.html

Add anchor to non-profit section of desktop version of /new
No bug.
http://localhost:8000/en-US/firefox/new/?xv=desktop#non-profit

[no bug] Add anchor to non-profit section of desktop version of /new

---

docs/firefox-accounts.rst
docs/uitour.rst
media/js/base/fxa-utm-referral.js
media/js/base/mozilla-fxa-form.js
media/js/base/mozilla-fxa-link.js
media/js/base/mozilla-fxa-product-button.js
media/js/base/uitour-lib.js
media/static-bundles.json
tests/unit/spec/base/mozilla-fxa-form.js
tests/unit/spec/base/mozilla-fxa-link.js
tests/unit/spec/base/mozilla-fxa-product-button.js

Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1635219
@rfk @alexgibson this is a draft of the changes we could make to route all the FxA links and forms using the UITour. Alex, see the chart below, we are working on moving the login to OAuth and to be able to generate OAuth urls we would need to "Create the FxA url" in Desktop.
TODO

Use the UITour for the FxA flow

---

media/css/pebbles/components/_buttons-download.scss
media/css/protocol/components/_download-button.scss

- Enabled download buttons for Windows ARM46 / AArch64 devices.
#9117

Enable download buttons for Windows ARM64 builds. (Fixes #9117)

---

tests/functional/newsletter/test_newsletter_embed.py

The newsletter form was removed from feature pages in https://github.com/mozilla/bedrock/pull/9105 but I failed to notice there were newsletter tests for those pages. This removes those redundant functional tests.

Remove newsletter tests for feature pages

---

.circleci/config.yml
.eslintignore
.eslintrc.js
.stylelintignore
Dockerfile
Makefile
docs/testing.rst
gulpfile.js
package.json
yarn.lock

Begins to reduce our dependency on Gulp by moving JS tests and JS/CSS/JSON linting from Gulp to NPM scripts.
- Adds NPM scripts for linting and testing front-end assets.
- Removes `gulp-eslint`, `gulp-stylelint`, and `gulp-jsonlint` plugins.
- Updates `eslint` to version 7.
- Uses ESLint plugin to lint JSON files.
- Updates docker images to use Node v12.
#8479
Make sure to update dependencies by running `yarn` and `make build` first.
- Running `npm run test` should lint front end assets before running JS unit tests.
- Running `make lint` should lint both front-end and back-end code.
Successful test run: https://gitlab.com/mozmeao/www-config/pipelines/149677839

Move front-end linting and tests to NPM scripts (Fixes #8479)

---

media/js/firefox/welcome/welcome8-traffic-cop.js
media/js/firefox/welcome/welcome8.js

r? @alexgibson @craigcook 
For the High Velocity Testing moments page, we have re-calculated the percentage for traffic cop to be 2.5% per branch, totalling 10%. 
I would like to separate data collection on the main CTA leading to the protections report, and the link in the body which also leads to the protections report, so edited the `eLabel` for that particular link to separate it from the button.

Add correct branch percentages, add custom params for protections link

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

- Restrict new Firefox Lite /whatsnew page to 79.0 and above.
#9119
Firefox Lite template:
- http://localhost:8000/id/firefox/79.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/79.0/whatsnew/africa/
- http://localhost:8000/en-US/firefox/79.0/whatsnew/india/
Standard /whatsnew templates:
- http://localhost:8000/id/firefox/78.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/78.0/whatsnew/africa/
- http://localhost:8000/en-US/firefox/78.0/whatsnew/india/

Only show Firefox Lite WNP to 79.0 and above (#9119)

---

bedrock/firefox/templates/firefox/enterprise/index.html
bedrock/firefox/urls.py
l10n/en/firefox/enterprise.ftl
lib/fluent_migrations/firefox/enterprise/index.py

- Migrates `firefox/enterprise/index.lang` to `firefox/enterprise.ftl`
Note: the entperpise/signup page was never localized, so remains hard-coded.
#9149
```
```

Migrate firefox/enterprise to Fluent (Fixes #9149)

---

bedrock/firefox/redirects.py

Redirect links from Firebird comparison page to Firefox
#9113
http://localhost:8000/products/firebird/
http://localhost:8000/products/firebird/compare/

add firebird redirect [fixes 9113]

---

bedrock/firefox/templates/firefox/facebookcontainer/index.html
bedrock/firefox/urls.py
l10n/en/firefox/facebook_container.ftl
lib/fluent_migrations/firefox/facebookcontainer/index.py

- Migrates `firefox/facebookcontainer/index.lang` to `firefox/facebook_container.ftl`
#9152
```
```

Migrate Facebook Container page to Fluent (Fixes #9152)

---

media/css/firefox/browsers-products.scss

I made a small change that will fix this issue, by utilizing z-index to make sure the image is underneath the form container at all times, so the image cannot ever make the form unusable by being in front of it.
#9110 
http://localhost:8000/ar/firefox/browsers/

 RTL styling issues on /firefox/browsers/ page

---

l10n/en/firefox/features/shared.ftl

L10n PR: https://github.com/mozilla-l10n/www-l10n/pull/82
https://github.com/mozilla/bedrock/issues/9187

Use brand name in missing shared /features string (#9187) [skip l10n]

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
tests/functional/firefox/whatsnew/test_whatsnew_africa.py
tests/functional/firefox/whatsnew/test_whatsnew_id.py
tests/functional/firefox/whatsnew/test_whatsnew_india.py

Puts updated Firefox Lite /whatsnew page behind a switch.
http://localhost:8000/en-US/firefox/79.0/whatsnew/africa/
http://localhost:8000/en-US/firefox/79.0/whatsnew/india/
http://localhost:8000/id/firefox/79.0/whatsnew/all/
#9189

Add switch to Firefox Lite /whatnsew page (Fixes #9189)

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit.html

Per https://groups.google.com/forum/#!topic/mozilla.dev.platform/c57FBhCsHI0, we're trying to get commit access bugs to follow a standard template. The new link supports that.

Update bug filing link for commit access.

---

bedrock/mozorg/templates/mozorg/book.html

Adds the latest passage to the Book of Mozilla.
#9222 
http://localhost:8000/book/

[fix #9222] Update Book of Mozilla

---

bedrock/firefox/templates/firefox/welcome/page8.html

Template was hiding it from zh-TW but that should be zh-CN
#9235 
http://localhost:8000/zh-CN/firefox/welcome/8/

[fix #9235] Remove FB Container from zh-CN on /welcome/8/

---

media/js/firefox/welcome/welcome8-traffic-cop.js
media/js/firefox/welcome/welcome8.js

r? @craigcook 
It seems we are not getting an expected amoung of "link click" events, and the event may not be firing because the page navigates away to the protection report before the event is being added to the data layer. This makes the event fire before the navigation. 
note, this is a bug in all places where protection report is being opened, and will need to be updated in those places in the future.

Make GA event fire before opening the protection report

---

bedrock/firefox/templates/firefox/welcome/page8.html

links below the fold and the main CTA (when JS is not enabled) are lacking data-cta-text params - this fixes that.
Luckily we did included UTM params and so have a decent record of click throughs on below-the-fold links.
r? @craigcook 
~This may not need to be merged, but adding it awaiting on the teams decision.~ 
Team has decided this is good to go. please take note of the timestamp when this is pushed to production

add data-cta-text params

---

tests/functional/test_l10n.py

Temporarily moving the test to /firefox while we sort out what's up with the language switcher on the redesigned /new page.
No bug because it's possible merging https://github.com/mozilla-l10n/www-l10n/pull/83 will solve the problem.
Passed locally.

Test language switcher on /firefox instead

---

bedrock/firefox/templates/firefox/new/desktop/download.html
media/js/firefox/new/desktop/join-modal.js

The modal was triggering on every download button in the page, including the button that's already within the modal.
https://github.com/mozilla/bedrock/issues/9256

Fix modal download button on /new (Fixes #9256)

---

media/js/firefox/new/desktop/download.js
media/js/firefox/privacy/messaging-experiment.js
media/js/firefox/privacy/products.js
media/js/firefox/whatsnew/whatsnew-76.js
media/js/firefox/whatsnew/whatsnew-79.js

We've been launching about:protections before the dataLayer.push, so most of the time the dataLayer never updates and we've failed to count those clicks. This just reorders events so dataLater.push fires first.
#9237 
http://localhost:8000/firefox/78.0/whatsnew/
http://localhost:8000/firefox/79.0/whatsnew/
http://localhost:8000/firefox/privacy/products/
http://localhost:8000/firefox/new/?v=b
http://localhost:8000/firefox/privacy-tools/

[fix #9237] Fix tracking on protection report clicks

---

bedrock/settings/base.py
media/js/base/mozilla-pixel.js
tests/unit/spec/base/mozilla-pixel.js

- Adds random number param to cache bust doubleclick request on /download/thanks/.
- Replaces jQuery code with vanilla JS.
- Adds test for cache bust param.
#9128
Test using a browser with DNT disabled:

Cache-bust doubleclick pixel on /download/thanks (Fixes #9128)

---

bedrock/firefox/templates/firefox/mobile/get-app.html
bedrock/firefox/templates/firefox/mobile/index.html
bedrock/firefox/urls.py
l10n/en/firefox/mobile.ftl
lib/fluent_migrations/firefox/mobile/index.py

- Migrates `firefox/mobile-2019.lang` to `firefox/mobile.ftl`.
- Updates the following templates to use Fluent IDs:
- http://localhost:8000/en-US/firefox/mobile/
- http://localhost:8000/en-US/firefox/mobile/get-app/
#9161
```
```

Migrate firefox/mobile to Fluent (Fixes #9161)

---

bedrock/firefox/views.py
docs/l10n.rst
lib/l10n_utils/__init__.py
lib/l10n_utils/fluent.py
lib/l10n_utils/tests/test_base.py
lib/l10n_utils/tests/test_fluent.py

Fix #9251
I tested locally by setting `DEV=False` and `SWITCH_NEW_REDESIGN=on`. With the current code you would see the new page but not the lang switcher, and with these changes you should see the full list.

Allow specification of multiple FTL files for locale activation

---

bedrock/firefox/templates/firefox/welcome/page7.html

Both CTA links to addons.mozilla.org should have identical UTM parameters.
This needs to be in prod **before 6 August 2020** because a campaign starting that day will be sending traffic to this page.
#9261 
http://localhost:8000/firefox/welcome/7/

Welcome page 7, match UTM params on CTA links [fix #9261]

---

media/js/base/mozilla-pixel.js
tests/unit/spec/base/mozilla-pixel.js

I made a small error in the random number generation in https://github.com/mozilla/bedrock/pull/9131. This follows Google's guideline more closely, as per: https://support.google.com/dcm/answer/2837746?hl=en
#9128

Tweak random number generation for doubleclick pixel (#9128)

---

bedrock/firefox/views.py
docs/l10n.rst
lib/l10n_utils/__init__.py
lib/l10n_utils/tests/test_base.py

Follup to #9262. This changes the `ftl_activations` parameter to `activation_files` and allows devs to include template filenames in the list so that .lang activations will be included.
Re #9251
I tested by commenting out the template file name in the `activation_files` parameter on the `NewView` class and looking at the list of locales in the source of the `/firefox/new/` page. Then I uncommented the line and looked at the list and saw that it was significantly longer.

Allow views to specify multiple ftl or template files for lang activation list

---

media/css/firefox/mobile/mobile.scss

Fixed the bug by adding backgound-size attribute for c-wordmark class in the mobile.scss.
#8293 
I have tested the change in local envirioment on the following pages:
localhost:8000/ar/firefox/mobile/
localhost:8000/he/firefox/mobile/
localhost:8000/fa/firefox/mobile/
(Following to check if the change doesn't have negative effects on non RTL)
localhost:8000/de/firefox/mobile/
localhost:8000/en-us/firefox/mobile/

Fix #8293 truncated logo on \mobile for RTL languages

---

bedrock/firefox/templates/firefox/new/desktop/thanks.html

- Fixes "Get help with your installation." link for macOS users.
- Also fixed the GA data attribute for help links.
http://localhost:8000/en-US/firefox/download/thanks/
#9272

Fix macOS installer help link on /thanks (Fixes #9272)

---

bedrock/legal_docs/views.py
bedrock/settings/base.py

It was set to an hour for dev and prod. In the new system 10min on prod and 1min on dev is good and helps get changes out faster for the legal team.

Adjust Legal Docs Cache Timeout

---

bedrock/mozorg/templates/mozorg/about/leadership.html

Justin O'Kelly has asked for an update to the copy we added on Tuesday.
<quote>
In 2020 Katharina was named one of the 100 Most Creative People by Fast Company, an award which recognizes her leadership on Common Voice in helping to diversify AI speech through machine learning.
becomes
In 2020 Katharina was named one of the Most Creative People by Fast Company. The award recognizes her leadership on Common Voice and helping to collect and diversify open speech data, to build and train voice-enabled applications.
</quote>

Next update to Katherina's bio

---

bedrock/firefox/templates/firefox/mobile/index.html

There is a CSS rule to hide the main CTA button (which opens the send-to-device widget) on mobile platforms, but the store badges were in the same container so were also being hidden.
#9289 
http://localhost:8000/firefox/mobile/
https://www-demo-pr-9292.herokuapp.com/firefox/mobile/
Test on both Android and iOS (either using a real device, browserstack, or just fake it by changing the root class to `android` or `ios` with dev tools). Also check both the main hero at the top of the page and the secondary one at the bottom.

firefox/mobile page, show app store badges on mobile platforms [fix #9289]

---

bedrock/legal_docs/management/commands/update_legal_docs.py

Only update the repo state if there are no errors: this means that we'll get a DMS notification if there are errors, while still updating the docs that did not error. Also ping DMS when there are not updates so that the DMS will work properly.

Fix legal docs Dead Mans Snitch configuration

---

bedrock/legal/templates/legal/terms/firefox-relay.html
bedrock/legal/urls.py

http://localhost:8000/en-US/about/legal/terms/firefox-relay/
https://github.com/mozilla/bedrock/issues/9240

Add Firefox Relay terms of service (Fixes #9240)

---

bedrock/legal/templates/legal/fraud-report.html
media/css/legal/legal.scss
media/css/protocol/protocol.scss

I moved both the Success and Error notifications to render at the top instead of bottom, and made the h2 'Fraud Report' no longer render upon successful form submission since it would then have nothing under it.
#9177
For Success notification, visit: http://localhost:8000/en-US/about/legal/fraud-report/?submitted=True
For Error notification, visit: http://localhost:8000/en-US/about/legal/fraud-report/
And enter in an invalid url before submitting

Adjust /fraud-report/ notification location

---

bedrock/firefox/templates/firefox/whatsnew/index-account.html
l10n/en/firefox/whatsnew/whatsnew-account.ftl
media/css/firefox/whatsnew/whatsnew-account.scss
media/js/firefox/whatsnew/whatsnew-account.js
media/static-bundles.json
tests/functional/firefox/whatsnew/test_whatsnew_60.py
tests/pages/firefox/whatsnew/whatsnew_60.py

Adds a signed-in state to the evergreen fallback WNP, shown to locales that haven't translated the current version's custom page or to any users updating to an older version that doesn't have an active custom page.
If the user is not signed into sync, we display a pitch to create an account (or sign in).
If the user is signed into sync, we display the send-to-device widget to promote Firefox mobile.
This adds a few new strings to `/firefox/whatsnew/whatsnew-account.ftl`
#9245 
http://localhost:8000/firefox/60.0/whatsnew/all/
http://localhost:8000/firefox/60.0/whatsnew/all/?signed-in=true
https://www-demo-pr-9276.herokuapp.com/firefox/60.0/whatsnew/all/
https://www-demo-pr-9276.herokuapp.com/firefox/60.0/whatsnew/all/?signed-in=true

Add signed in state to evergreen WNP [fix #9245]

---

bedrock/firefox/templates/firefox/whatsnew/includes/header.html
bedrock/firefox/templates/firefox/whatsnew/index-account.html
bedrock/firefox/templates/firefox/whatsnew/index.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx79.html
bedrock/firefox/views.py
l10n/en/firefox/whatsnew/whatsnew-s2d.ftl
lib/fluent_migrations/firefox/whatsnew/index.py
media/css/firefox/whatsnew/whatsnew.scss

- Migrates default /whatsnew page (S2D widget) to Fluent
- Use shared header for Fluent /whatsnew pages
http://localhost:8000/en-US/firefox/whatsnew/all/
#9194
```
```

Migrate default /whatsnew page to Fluent (Fixes #9194)

---

media/js/base/mozilla-lazy-load.js
media/js/base/mozilla-smoothscroll.js
tests/unit/spec/base/mozilla-smoothscroll.js

For mozilla-lazy-load.js:
1. Only one occurrence of $, which was replaced with querySelectorAll
For mozilla-smoothscroll.js:
1. Removed a unit test spec which expected jQuery functions to be called
2. Modified a unit test spec to not refer to window.jQuery
https://github.com/mozilla/bedrock/issues/8381
I've run the units tests via `karma start karma.conf.js`

Removed jQuery from mozilla-lazy-load.js & mozilla-smoothscroll.js (Fixes #8381)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx80.html
l10n/en-US/firefox/whatsnew/whatsnew-fx80.ftl

The new Firefox for Android is releasing to most locales on the 25th (the same date as Firefox 80 for desktop) but it's being delayed in en-US and en-CA until the 27th. WNP80 promotes the new Android browser, but we shouldn't show that promo to en-US and en-CA until it's actually available in those locales.
This puts the Android blurb behind the switch `firefox-whatsnew80-daylight-en-us` only for en-US and en-CA; all other locales will be able to see it by default.
This also fixes a typo, but avoids altering the original string by treating en-US as a locale (I've already submitted the same via Pontoon for en-CA and en-GB).
We need to get this to production on **Monday the 24th** ahead of the Fx80 release.
#9319 
http://localhost:8000/en-US/firefox/80.0/whatsnew/

WNP80, hide Android promo with switch for en-US/CA [fix #9319]

---

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html

This is an update of the eligible web properties to remove qsurvey from the web bounty
Verify that formatting rendered properly for the new sites added.
@april @g-k

remove qsurvey from bounty

---

bedrock/mozorg/templates/mozorg/moss/index.html

Just adding a section on the main page of the MOSS sub-site to let folks know that our application is currently closed as a result of MoCo restructuring. Thanks!

adding 2020 funding update section to index page

---

bedrock/exp/templates/exp/firefox/new/download.html
bedrock/firefox/templates/firefox/new/desktop/download.html

Change the mobile banner product heading from an h1 to h2.
#9330

Only one h1 on /firefox/new/ (Fixes #9330)

---

bedrock/base/templates/includes/banners/daylight/daylight-launch.html
l10n/en/banners/firefox-daylight-launch.ftl

Updates the Daylight banner headline, keeping the old one as a fallback.
#9351

Update Daylight banner title [fix #9351]

---

bedrock/firefox/templates/firefox/channel/desktop.html

Fix page title on http://localhost:8000/en-US/firefox/channel/desktop/
https://github.com/mozilla/bedrock/issues/9352

Fix channel page title (Fixes #9352)

---

bedrock/firefox/templates/firefox/facebookcontainer/index.html
l10n/en/firefox/facebook_container.ftl
media/css/firefox/facebook-container.scss
media/js/firefox/facebook-container-video.js
media/static-bundles.json

- Change mobile CTA from Firefox Focus to Firefox for mobile.
- Fix video positioning CSS.
#9349
https://github.com/mozilla/bedrock/issues/9347

Update Facebook Container page (Fixes #9349)

---

bedrock/base/templates/includes/protocol/footer/firefox.html
bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
bedrock/exp/templates/exp/firefox/accounts.html
bedrock/exp/templates/exp/firefox/index.html
bedrock/firefox/templates/firefox/accounts.html
bedrock/firefox/templates/firefox/home/index-master.html
bedrock/firefox/templates/firefox/privacy/products.html
bedrock/firefox/templates/firefox/products/index.html
bedrock/firefox/templates/firefox/welcome/page3.html
media/css/exp/firefox/accounts.scss
media/css/firefox/accounts-2019.scss

Removes promotional references/links to Firefox Send, hiding them temporarily behind the switch `firefox-send-active`. Send is hidden by default when the switch is OFF, so we can quickly switch it ON and unhide Send when/if Send becomes available again (and we'd follow that up with some cleanup to remove the switch and make it permanent again).
#9316 
Note that the switch hides Send when it's OFF and switches are treated as ON in dev mode. You'll need to test locally in prod mode to verify it's hidden.
Send should be removed from:
Main nav
Footer
http://localhost:8000/firefox/
http://localhost:8000/exp/firefox/
http://localhost:8000/firefox/products/
http://localhost:8000/firefox/accounts/
http://localhost:8000/exp/firefox/accounts/
http://localhost:8000/firefox/privacy/products/ …

Hide Firefox Send [fix #9316]

---

bedrock/firefox/templates/firefox/campaign/unfck/index.html

- Makes hard-coded copy in landing page macro translatable.
- Make UTMs optional for internal links (defaults to external).
#9361

Make share copy in campaign page macro translatable

---

l10n/configs/special-templates.toml

Reverses https://github.com/mozilla/bedrock/commit/11d53e942095d44e6b7f02dfbe860cfd459ee2d3#diff-f0fc96ed40fd13113a924f2fb3d2e712
#9323

Make WNP localizable in Pontoon for the Indonesian community (Fixes #9315)

---

bedrock/firefox/forms.py
bedrock/firefox/templates/firefox/campaign/unfck/emails/unfck.txt
bedrock/firefox/templates/firefox/campaign/unfck/index.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/urls.py
bedrock/firefox/views.py
media/css/firefox/unfck.scss

- Adds form view & tests for the september landing page (heavily borrowed from the /press/ section).
- Moves logic for making page appear only on Dev from `urls.py` to a switch in `views.py` (needed for the unit tests).
#9334

Add form functionality to sept landing page (#9334)

---

bedrock/mozorg/templates/mozorg/contact/contact-base.html

This PR updates the parent Contract page template to remote the Spaces JS bundle. (As it's not used/needed on this page) 
https://github.com/mozilla/bedrock/issues/9322
Test the following URLs: 
- `/contact`
- `/contact/spaces/`

Fixed #9322 - Removed Spaces JS bundle from root contact template

---

bedrock/mozorg/templates/mozorg/contact/contact-base.html
bedrock/mozorg/templates/mozorg/contact/contact-landing.html

- Only exclude contact JS bundle from the /contact landing page
http://localhost:8000/en-US/contact/
http://localhost:8000/en-US/contact/spaces/
#9380
#9322

Exclude contact JS bundle from landing page only (Fixes #9380)

---

bedrock/firefox/templates/firefox/campaign/unfck/index.html

A couple of small enhancement requests from the EU team:
- Lazy load gifs
- Make cta links on steps 1-4/5 open in a new tab.
#9361

Lazy load gifs on september campaign page (#9361)

---

bedrock/firefox/templates/firefox/new/desktop/thanks.html
bedrock/firefox/templates/firefox/new/protocol/base.html
bedrock/firefox/templates/firefox/new/trailhead/thanks.html

This adds the attribute `data-test-fxa-template="firefox-download-thanks"` to the /download/thanks/ template root element, which FxA tests can use to verify the page loads.
There's likely another way to verify a page in a test, but they've been using a CSS selector to look for an element already and this may be easier than completely rewriting their tests. Once this lands they can update their tests to look for the selector `html[data-test-fxa-template="firefox-download-thanks"]`
#9389

Add a test attribute to thanks page [fix #9389]

---

bin/db_s3_utils.py
bin/run-db-download.py
bin/run-db-upload.py

This is a thing that was missed in #8900. The DB data info file is now created in a subsdirectory of the project, and was being uploaded to the same subdirectory of the s3 bucket, even though it needs to be in the root of the bucket.

Fix db data upload path issue

---

media/js/libs/mozilla-traffic-cop.js

Updates bedrock's Traffic Cop lib to the latest version from https://github.com/mozilla/trafficcop
#9209

Update traffic-cop lib (Fixes #9209)

---

bedrock/exp/templates/exp/firefox/new/download.html
bedrock/firefox/templates/firefox/new/desktop/download.html
l10n/en/firefox/new/desktop.ftl

Adds "by default" to "Blocks third-party tracking cookies" table row and removes Chrome's check.
#9359

Update comparison table on /new (Fixes #9359)

---

bedrock/mozorg/templates/mozorg/contribute/contribute-2020.html
bedrock/mozorg/tests/test_views.py
bedrock/mozorg/urls.py
bedrock/mozorg/views.py
l10n/en/mozorg/contribute.ftl

- Adds `mozorg/contribute.ftl`
- Converts `/contribute/` page to use Fluent IDs.
- Updates view tests.
#9151

Expose /contribute for L10n (Fixes #9151)

---

package.json
yarn.lock

Upgrade `mozilla-protocol/core` page from `12.0.1` to `12.1.0`
Note that this new version did not require any migration/compatibility changes. 
- https://github.com/mozilla/bedrock/issues/9357
- https://github.com/mozilla/protocol/pull/636
- https://www.npmjs.com/package/@mozilla-protocol/core/v/12.1.0

Fixed #9357 - Updated mozilla-protocol/core package

---

l10n/en/firefox/browsers/compare/safari.ftl

Adding a comma to the string that was updated in #9416 
https://github.com/mozilla-l10n/www-l10n/pull/108#discussion_r491034377

String fix for Safari comparison page

---

media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

- Add stub attribution data to `data-direct-link` attributes for legacy IE browsers.
- Update tests.
#9350
Demo: https://www-demo3.allizom.org/en-US/
1. Using IE 8/9 on Windows, navigate to the demo URL above.
2. Open IE developer tools, try to inspect the DOM of the download button in the nav.
3. Find a download link and inspect the attributes.
4. Verify `attribution_code` and `attribution_sig` params have been appended to the URL (see screenshot below).
5. Click download, and verify you still get the expected FF installer.

Make stub attribution work for legacy IE browsers (Fixes #9350)

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2020.html
bedrock/mozorg/urls.py

Create new page for the H1 2020 Transparency Report  and update nav/links on root Transparency page.
#9335 
- 2020 Report: https://www-demo-pr-9422.herokuapp.com/en-US/about/policy/transparency/jan-jun-2020/
- Transparency root page: https://www-demo-pr-9422.herokuapp.com/en-US/about/policy/transparency/

H1 2020 Transparency Report

---

bedrock/privacy/templates/privacy/notices/thunderbird.html

Removes Google Analytics from Thunderbird privacy notice.
http://localhost:8000/en-US/privacy/thunderbird/
https://github.com/mozilla/bedrock/issues/9426

Exclude GA on /privacy/thunderbird/ (Fixes #9426)

---

media/js/firefox/facebook-container-video.js

Fixes a (harmless) JS error when viewing the German page (since that locale uses a youtube iframe instead of a native `<video>` element).
- http://localhost:8000/de/firefox/facebookcontainer/
- http://localhost:8000/en-US/firefox/facebookcontainer/
#9437

Fix JS error on FB Container page (Fixes #9437)

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2020.html

Updated values in the H1 2020 Transparency Report
#9448
Check `/about/policy/transparency/jan-jun-2020.html` page to make sure there are no instances of `TK`

H1 2020 Transparency Report updates

---

bedrock/firefox/templates/firefox/features/adblocker.html
bedrock/firefox/urls.py
l10n/en/brands.ftl
l10n/en/firefox/features/adblocker.ftl
lib/fluent_migrations/firefox/features/adblocker.py

http://localhost:8000/en-US/firefox/features/adblocker/
#9146
```
```

Migrate features/adblocker page to Fluent (#9146) [skip l10n]

---

bedrock/firefox/templates/firefox/campaign/unfck/index.html
media/js/firefox/campaign/unfck.js

Three small changes to unfuck landing page. Move the share link to the bottom, add the JS for the Facebok share, and point to a different landing page for the movie.
#9334 
http://localhost:8000/en-US/firefox/unfck/

Move share links, update movie url (#9334)

---

bedrock/base/templates/base-protocol.html

As per https://docs.sentry.io/platforms/javascript/troubleshooting/supported-browsers/
#8444

Exclude Sentry JS from IE < 10 (#8444)

---

bedrock/firefox/templates/firefox/nightly/whatsnew.html
media/js/firefox/whatsnew/whatsnew.js
media/static-bundles.json

Fixes JS error on the following pages:
- http://localhost:8000/en-US/firefox/whatsnew/all/
- http://localhost:8000/en-US/firefox/70.0a1/whatsnew/all/
#9455

Fix JS error on /whatsnew pages (Fixes #9455)

---

bedrock/base/templates/includes/banners/daylight/daylight-promo.html
bedrock/firefox/templates/firefox/browsers/index.html
bedrock/firefox/templates/firefox/home/index-master.html
bedrock/firefox/templates/firefox/mobile/index.html
bedrock/firefox/templates/firefox/products/index.html
bedrock/mozorg/templates/mozorg/home/home-de.html
bedrock/mozorg/templates/mozorg/home/home-en.html
bedrock/mozorg/templates/mozorg/home/home-fr.html
bedrock/mozorg/templates/mozorg/home/home.html
bedrock/settings/base.py
l10n/en/banners/firefox-daylight-promo.ftl
media/css/base/banners/daylight-promo.scss
media/js/mozorg/home/daylight-promo-banner-init.js
media/static-bundles.json

Adds a new minimal banner promoting the new Firefox for Android and iOS. This will replace the previous banner but I ended up building it as a separate banner so we can get this into production ahead of time and control them both with separate switches. We don't intend to make the switch until Oct 8 (pending release of Fx 29 for iOS). Doing this weird double-banner/separate-switch treatment gives us more control on the timing. We'll turn the old one off at the same time as we turn the new one on, then we can delete the old one in a follow-up PR.
#9412 
http://localhost:8000/firefox/
http://localhost:8000/firefox/products/
http://localhost:8000/firefox/mobile/
http://localhost:8000/firefox/browsers/
The banner is hidden if the strings aren't translated so you won't …

Update daylight promo banner [fix #9412]

---

tests/pages/firefox/whatsnew/whatsnew_60.py

This updates the selector used to locate the FxA button on the evergreen whatsnew page. A class changed in #9404 which broke a test. My bad.
This failing test is currently blocking a production deployment for the big campaign that starts tomorrow.
Run `tests/functional/firefox/whatsnew/test_whatsnew_60.py`

Fix test for whatsnew 60 [#9218]

---

bedrock/firefox/templates/firefox/browsers/compare/brave.html
bedrock/firefox/templates/firefox/browsers/compare/chrome.html
bedrock/firefox/templates/firefox/browsers/compare/edge.html
bedrock/firefox/templates/firefox/browsers/compare/ie.html
bedrock/firefox/templates/firefox/browsers/compare/index.html
bedrock/firefox/templates/firefox/browsers/compare/opera.html
bedrock/firefox/templates/firefox/browsers/compare/safari.html
l10n/en/firefox/browsers/compare/shared.ftl

Updates the disclaimer intro to clarify that comparisons were made with default settings.
#9481 
http://localhost:8000/firefox/browsers/compare/ (and subpages)

Update browser comparison version disclaimer [fix #9481]

---

bedrock/exp/templates/exp/firefox/campaign/unfck/index.html
bedrock/exp/urls.py

Add exp variant of EN unfck page.
#9334 
http://localhost:8000/en-US/exp/firefox/unfck/

Add exp variant of EN unfck page

---

bedrock/mozorg/forms.py
bedrock/newsletter/forms.py
bedrock/newsletter/templates/newsletter/base.html
bedrock/newsletter/templates/newsletter/confirm.html
bedrock/newsletter/templates/newsletter/developer.html
bedrock/newsletter/templates/newsletter/existing.html
bedrock/newsletter/templates/newsletter/firefox.html
bedrock/newsletter/templates/newsletter/fxa-error.html
bedrock/newsletter/templates/newsletter/index.html
bedrock/newsletter/templates/newsletter/mozilla.html
bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
bedrock/newsletter/templates/newsletter/recovery.html
bedrock/newsletter/templates/newsletter/updated.html
bedrock/newsletter/tests/test_footer_form.py
bedrock/newsletter/tests/test_views.py
bedrock/newsletter/urls.py
bedrock/newsletter/views.py
l10n/configs/pontoon.toml
l10n/en/brands.ftl
l10n/en/mozorg/newsletters.ftl
l10n/en/newsletter/opt-out-confirmation.ftl
l10n/en/newsletter_form.ftl
lib/fluent_migrations/newsletter/index.py
lib/fluent_migrations/newsletter/opt-out-confirmation.py

- Migrates `/newsletter/` app from .lang to Fluent
#8659
#9401
- http://localhost:8000/en-US/newsletter/
- http://localhost:8000/en-US/newsletter/existing/*TOKEN*/
- http://localhost:8000/en-US/newsletter/confirm/*TOKEN*/
- http://localhost:8000/en-US/newsletter/country/*TOKEN*/
- http://localhost:8000/en-US/newsletter/updated/
- http://localhost:8000/en-US/newsletter/recovery/
- http://localhost:8000/en-US/newsletter/mozilla/
- http://localhost:8000/en-US/newsletter/firefox/
- http://localhost:8000/en-US/newsletter/developer/
- http://localhost:8000/en-US/newsletter/fxa-error/
- http://localhost:8000/en-US/newsletter/opt-out-confirmation/
- http://localhost:8000/en-US/newsletter/country/success/

Migrate newsletter preference center to Fluent (Fixes #9401)

---

bedrock/base/templates/includes/protocol/footer/firefox.html

The class is not needed for this element. This should fix bug 9327
This fixes an issue where some links in the footer receive additional styles when a FxA form is on the page
This class appears to be unnecessary for the footer (the only scss files that referenced this class were for the FxA signup). If this is true, a new unique class is not needed, and removing from the footer should suffice. 
fixes bug #9327

remove fxa-signin class from footer list items

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

Adds a redirect for /openletter to a blog post (currently password protected) at foundation.mozilla.org.
**This needs to be live early on Monday, 19 October.**
#9560 
http://localhost:8000/openletter
Should redirect to `https://foundation.mozilla.org/blog/mozilla-urges-facebook-and-twitter-halt-dangerous-recommendations/?utm_source=mozilla.org&utm_content=shortlink`

Add vanity redirect for openletter [fix #9560]

---

bedrock/mozorg/templates/mozorg/home/home-en.html

Revise Pocket hero title text and copy on the EN homepage. 
#9558
Local: http://localhost:8000/en-US/
Live Demo: https://www-demo-pr-9559.herokuapp.com

Fix #9558 - Revise Pocket hero text on the EN homepage

---

bin/run-integration-tests.sh
tests/functional/conftest.py

This should hopefully fix an issue we're seeing in BrowserStack where IE browsers sometimes don't enter form input text correctly.
https://www.browserstack.com/docs/automate/selenium/using-sendkeys-on-remote-IE11

Add sendKeys capability for BrowserStack sessions

---

bedrock/mozorg/templates/mozorg/home/home.html

Fix Daylight banner on rest-of-world home page (Fixes #9582)

---

bedrock/firefox/redirects.py
bedrock/firefox/templates/firefox/faq.html
bedrock/firefox/templates/firefox/includes/structured-data-firefox-faq.html
bedrock/firefox/urls.py
l10n/en/brands.ftl
l10n/en/firefox/browsers/quantum.ftl
l10n/en/firefox/faq.ftl
media/css/firefox/faq.scss
media/static-bundles.json
tests/redirects/map_globalconf.py

Adds firefox/faq SEO page.
Includes redirect for [new firefox/browsers/quantum page](#9502).
#9490
#9491
#9498
[Final copy](https://docs.google.com/document/d/1LAdUXUovciI1N4xNN1lNGmWv-6kdXVunvM7arrGyK-E/edit?ts=5f74df55)
[Design](https://github.com/mozilla/bedrock/issues/9497#issuecomment-707772063)

Add firefox/faq (#9490, Fixes #9491, #9498)

---

tests/functional/conftest.py

@glogiotatidis r?
This is just to help me test something in browserstack. It should not effect any tests that we're running in the default pipeline.

Only set browserstack capabilities for IE 11

---

bin/run-integration-tests.sh

@glogiotatidis r?
This splits out the browserstack config into some separate variables for setting capabilities. Using just for testing right now.
Based on: https://www.browserstack.com/docs/automate/selenium/select-browsers-and-devices#browserstack-specific-capabilities-desktop

Update browserstack capabilities config

---

media/js/base/mozilla-utils.js
media/js/ie/mozilla-utils-ie.js
tests/unit/spec/base/mozilla-utils.js
tests/unit/spec/ie/mozilla-utils-ie.js

- Fixes GA bug where old IE browsers are not setting download event label correctly.
- Add 'Unsupported' fallback label for other platforms.
#9535
Demo: https://www-demo2.allizom.org/en-US/

Improve GA download reporting for legacy / unknown browsers (Fixes #9535)

---

package.json
yarn.lock

Upgrade `mozilla-protocol/core` page from `12.1.0` to `12.1.1`
Note that this new version did not require any migration/compatibility changes. 
- https://github.com/mozilla/bedrock/issues/9608
- https://github.com/mozilla/protocol/issues/638
- https://github.com/mozilla/protocol/releases/tag/v12.1.1

Fix #9608 - Update mozilla-protocol/core package to v12.1.1

---

media/js/firefox/new/common/thanks-init.js

Ensure a download still happens if prior code encounters an unexpected error introduced in the /thanks page.
#9615

Fix error on /download/thanks/ if 'try again' link is not well formatted (Fixes #9615)

---

bedrock/firefox/templates/firefox/browsers/quantum.html
l10n/en/firefox/browsers/quantum.ftl

Updates firefox/quantum fluent strings to have a standardized prefix per https://bedrock.readthedocs.io/en/latest/l10n.html#ftl-string-ids

update ftl IDs for firefox/quantum [no bug]

---

media/js/base/send-to-device.js

Fixes `this.inSupportedCountry is not a function` JS error when geo-location check times out.
#9617

Send-to-device JS form error when geo lookup times out (Fixes #9617)

---

media/js/base/sentry-init.js

This should hopefully help cut down on a lot of the noise created by external scripts / extensions.
#8444
I pushed an undefined function error to the home page on demo: https://www-demo1.allizom.org/en-US/
Error in Sentry: https://sentry.prod.mozaws.net/operations/bedrock-demos/issues/9190127/

Filter Sentry JS errors to /media/ scripts (#8444) 

---

media/css/firefox/releasenotes.scss

Adds scroll-margin-top to release notes' list items to avoid sticky header from overlaying an item when using fragments (e.g. https://www.mozilla.org/en-US/firefox/83.0a1/releasenotes/#note-788467). This probably shouldn't have a hard-coded value, but I didn't manage to understand which SASS variables to use.

[WIP] Add scroll margin to release note items

---

.eslintignore
media/js/firefox/browsers/chromebook.js
media/js/firefox/campaign/unfck.js
media/js/firefox/whatsnew/whatsnew-account.js
package.json
tests/unit/spec/firefox/new/common/thanks.js

- Fixes ESLint parsing depth (NPM stripts require quotes around Node globs).
- Fixes a few linting errors that have been missed as a result of this bug.
#9626

Fix ESLint parsing depth (Fixes #9626)

---

bedrock/firefox/templates/firefox/browsers/compare/brave.html
bedrock/firefox/templates/firefox/browsers/compare/chrome.html
bedrock/firefox/templates/firefox/browsers/compare/edge.html
bedrock/firefox/templates/firefox/browsers/compare/ie.html
bedrock/firefox/templates/firefox/browsers/compare/opera.html
bedrock/firefox/templates/firefox/browsers/compare/safari.html
media/css/firefox/compare/compare-details.scss

- add download button to hero; hide if Firefox
- switch to simplified download button for secondary download cta
Fix #9640
In Fx and not-fx:
- http://localhost:8000/en-US/firefox/browsers/compare/brave/
- http://localhost:8000/en-US/firefox/browsers/compare/chrome/
- http://localhost:8000/en-US/firefox/browsers/compare/edge/
- http://localhost:8000/en-US/firefox/browsers/compare/ie/
- http://localhost:8000/en-US/firefox/browsers/compare/opera/
- http://localhost:8000/en-US/firefox/browsers/compare/safari/

Add download button to compare pages non-Firefox (Fix #9640)

---

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html

Jira is becoming a core engineering facility for Mozilla, thus we'd like to include JIRA in the web bug bounty program eligibility list.

Add JIRA to eligible websites

---

bin/build-release-image.sh

Raphael discovered that the sitemap was behind. I found that this is because the `prod-latest` and git-tag-based docker tags weren't being pushed to Docker Hub. This is because we moved to promoting images instead of building fresh for stage and prod. Because of this the docker hub push was being skipped for stage and prod. This change ensures that the tagging and pushing happens regardless.

Fix docker image tagging

---

bedrock/base/templates/404.html
media/js/base/error-pages.js

Prevent JS error on 404 pages where locales still display older messaging.
#9642
Locales that don't satisfy [this conditional statement](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/404.html#L20) currently receive an error.

Fix JS error on 404 pages (#9642)

---

bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py

Allowing the responses to be cached means that the query params in the
redirect responses are also cached and therefore we need a unique
response per visitor in order to ensure that we are giving them the
right experiment and stub attribution.

Set never-cache headers for experiment responses for /firefox/new/

---

bedrock/firefox/redirects.py
tests/redirects/map_globalconf.py

firefox/features/sync redirects to firefox/sync
#9490

update sync redirect (#9490)

---

bedrock/firefox/templates/firefox/firstrun/firstrun.html
bedrock/firefox/views.py
l10n/en/firefox/firstrun.ftl
lib/fluent_migrations/firefox/firstrun/firstrun.py

http://localhost:8000/en-US/firefox/firstrun/
#9193
```
```

Migrate /firefox/firstrun/ page to Fluent (Fixes #9193)

---

bedrock/firefox/templates/firefox/developer/firstrun.html
bedrock/firefox/templates/firefox/developer/whatsnew.html
bedrock/firefox/templates/firefox/nightly/whatsnew.html
bedrock/firefox/templates/firefox/nightly_firstrun.html
bedrock/firefox/templates/firefox/welcome/base.html
bedrock/firefox/templates/firefox/whatsnew/base.html
bedrock/privacy/templates/privacy/notices/firefox.html
media/js/base/stub-attribution.js

- Removes Stub Attribution script from in-product pages such as /whatsnew, /welcome, and /privacy/firefox/ (those users are already on Firefox, and if they should go on to download attribution should still happen on the download page)
- Adds a check for `window._SearchParams` in stub attribution script to fail more gracefully when network errors happen.
#9620

Remove Stub Attribution script from in-product Firefox pages (#9620)

---

bedrock/base/templates/base-protocol.html
bedrock/settings/base.py

Will apply to firefox.com and all subdmains.
Re bug 1666072
Fix #9695

Add image from firefox.com to set proper HSTS settings

---

bedrock/firefox/templates/firefox/features/includes/features-content.html
bedrock/firefox/templates/firefox/features/index.html
bedrock/firefox/templates/firefox/features/private-browsing.html

Update two links on features pages which reference sync to point to new sync page.
Fix  #9704 
http://localhost:8000/en-US/firefox/features/
http://localhost:8000/en-US/firefox/features/fast/

Update links to point to sync page (Fix#9704)

---

bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
bedrock/firefox/urls.py
l10n/en/firefox/browsers/windows-64-bit.ftl
l10n/en/firefox/windows-64-bit.ftl
lib/fluent_migrations/firefox/browsers/windows-64-bit.py

L10n PR: https://github.com/mozilla-l10n/www-l10n/pull/134
One possible sticking point is that the .lang file is in the root of /firefox but I'm trying to move the corresponding Fluent file into /firefox/browsers (to match the URL). Not sure if that will cause problems, maybe better to leave it in the /firefox folder?
Edit: ^^ that was indeed problematic, I've moved it back into the /firefox folder.
Edit 2: After moving it back to the /firefox folder to make it easier to run the migration, I then moved all the files to /firefox/browsers manually when committing to www-l10n.
#9691 
http://localhost:8000/firefox/browsers/windows-64-bit/

Migrate firefox/browsers/windows-64-bit to Fluent [fix #9691] [skip l10n]

---

l10n/en/firefox/browsers/windows-64-bit.ftl

Missed some brand names in the migration.
www-l10n PR: https://github.com/mozilla-l10n/www-l10n/pull/137
https://github.com/mozilla/bedrock/pull/9709#discussion_r527040196

Fix brand names in firefox/browsers/windows-64-bit.ftl [skip l10n]

---

l10n/configs/pontoon.toml

Configure firefox/privacy/book to be exposed for DE, FR, and EN localization only.
[Context from Peiying:](https://github.com/mozilla-l10n/www-l10n/pull/127#pullrequestreview-529626438)
> Given the length of this page, we are discussing with Justin on how to keep a content heavy page like this one to the target markets and offer an alternative, a shorter version to smaller communities. This page is best left for the l10n vendor to do.
The EU team already has translations available for DE and FR once this is available in Pontoon.
**www-l10n ref:** https://github.com/mozilla-l10n/www-l10n/pull/139

Configure firefox/privacy/book.ftl for de, fr, and en only. [no bug]

---

bin/run-prod.sh
requirements/base.txt
wsgi/config.py

@duallain I think this works. My mistake before in 89a6b9c8bd9df8272371a5dd5114da7129c8434c was that I added the env var in the Docker image which meant it tried to use it all the time and some of the management commands and the dev server didn't play nice with it. I tested locally by running `make run-prod` and looking at `/prometheus/metrics/` as well as getting a shell on the running container `docker-compose exec release-local bash` and looking at the `/tmp/prometheus_metrics` dir.

Enable multiprocess mode for prometheus metrics gathering

---

bedrock/base/templates/includes/protocol/footer/footer.html
bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/tests/test_helper_misc.py
bedrock/settings/base.py

- use Twitter helper for Firefox twitter link in footer
- add and use Instagram helper for Firefox Instagram link in footer
Fix #9699

Use helpers for footer social media links (Fix #9699)

---

bedrock/firefox/redirects.py
bedrock/firefox/templates/firefox/nightly/firstrun.cs.html
bedrock/firefox/templates/firefox/nightly/firstrun.de.html
bedrock/firefox/templates/firefox/nightly/firstrun.es-AR.html
bedrock/firefox/templates/firefox/nightly/firstrun.es-ES.html
bedrock/firefox/templates/firefox/nightly/firstrun.fr.html
bedrock/firefox/templates/firefox/nightly/firstrun.html
bedrock/firefox/templates/firefox/nightly/firstrun.it.html
bedrock/firefox/templates/firefox/nightly/firstrun.ru.html
bedrock/firefox/urls.py
l10n/en/firefox/nightly/firstrun.ftl
lib/fluent_migrations/firefox/nightly_firstrun.py
media/css/firefox/firstrun/nightly.scss
media/static-bundles.json

http://localhost:8000/en-US/firefox/nightly/firstrun/
#9684
```
```

Migrate firefox/nightly/firstrun to Fluent (Fixes #9684) [skip l10n]

---

docs/l10n.rst
l10n/configs/pontoon.toml

See discussion in https://github.com/mozilla-l10n/www-l10n/pull/146
@pmac r? It seems like these config files don't quite work the way we originally thought, and we can't use broad wild cards like the way we have been if we need to expose certain files only to a subset of locales. 
This fix is a little verbose, but (from what I can tell) it's the only real option we have that doesn't involve re-architecting all the L10n files into different directories (which feels like a somewhat large change to make suddenly).
Thoughts?

Add more explicit path definitions to pontoon Fluent config

---

bedrock/base/templates/includes/sticky-promo.html

- Fix GA attribution.
- Declare explicit logo sizes.
https://github.com/mozilla/bedrock/issues/9721
https://github.com/mozilla/bedrock/issues/9728

Sticky promo fixes (#9721, #9728)

---

bedrock/firefox/templates/firefox/browsers/browser-history.html
bedrock/firefox/urls.py
l10n/en/firefox/browsers/history/browser-history.ftl
lib/fluent_migrations/firefox/browsers/browser-history.py

http://localhost:8000/en-US/firefox/browsers/browser-history/
#9693
```
```

Migrate /firefox/browsers/browser-history/ to Fluent (Fixes #9693) [skip l10n]

---

media/css/firefox/includes/_sticky-promo.scss

Sticky Promo box was just being visually hidden, rather than not displayed, once dismissed.
#9786 
Go to [http://localhost:8000/en-US/firefox/](http://localhost:8000/en-US/firefox/) and dismiss the box. It should no longer visible and should not intefer with selecting the language from the footer.

Fix #9786 - Add CSS qualification to visible sticky promo box

---

bedrock/firefox/urls.py

Update URL for block-fingerprinting
#9761
http://localhost:8000/en-US/firefox/features/block-fingerprinting

Update URL for block-fingerprinting #9761

---

bedrock/base/templates/includes/banners/mobile/native-android-exp.html
bedrock/firefox/templates/firefox/home/exp/v-1.html
bedrock/firefox/templates/firefox/home/exp/v-2.html
bedrock/firefox/templates/firefox/home/exp/v-3.html
bedrock/firefox/templates/firefox/home/exp/v-4.html
bedrock/firefox/templates/firefox/home/exp/v-5.html
bedrock/firefox/templates/firefox/home/exp/v-6.html
bedrock/firefox/templates/firefox/home/index-master.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
media/css/base/banners/native-android-exp.scss
media/js/firefox/home/android-experiment.js
media/js/firefox/home/android-native-banner-init.js
media/static-bundles.json

Adds multi-variant Traffic Cop experiment for testing native app banners for Android on the /firefox page.
- http://localhost:8000/en-US/firefox/?v=1 (control)
- http://localhost:8000/en-US/firefox/?v=2 (mozilla banner)
- http://localhost:8000/en-US/firefox/?v=3 (native no star rating)
- http://localhost:8000/en-US/firefox/?v=4 (native star rating)
- http://localhost:8000/en-US/firefox/?v=5 (native dark star rating)
- http://localhost:8000/en-US/firefox/?v=6 (native dark no stars)
#9434

Android native styled banners A/B test on /firefox. (#9434)

---

media/css/mozorg/home/home-en.scss

Fix "Firefox products are designed to protect your privacy" title font on home page.
#9803

Fix Metropolis font for Firefox banner on home page (Fixes #9803)

---

bedrock/firefox/templates/firefox/developer/firstrun.html
bedrock/firefox/templates/firefox/developer/includes/alt-newsletter.html
bedrock/firefox/templates/firefox/developer/includes/engage.html
bedrock/firefox/templates/firefox/developer/includes/features.html
bedrock/firefox/templates/firefox/developer/includes/for-developers.html
bedrock/firefox/templates/firefox/developer/includes/highlights.html
bedrock/firefox/templates/firefox/developer/includes/intro-features.html
bedrock/firefox/templates/firefox/developer/includes/nightly.html
bedrock/firefox/templates/firefox/developer/includes/performance.html
bedrock/firefox/templates/firefox/developer/index.html
bedrock/firefox/templates/firefox/developer/whatsnew.html
bedrock/firefox/urls.py
bedrock/firefox/views.py
l10n/en/firefox/developer.ftl
lib/fluent_migrations/firefox/developer/index.py

- http://localhost:8000/en-US/firefox/developer/
- http://localhost:8000/en-US/firefox/83.0a2/whatsnew/all/
- http://localhost:8000/en-US/firefox/83.0a2/firstrun/
#9191
```
```

Migrate firefox/developer pages to Fluent (Fixes #9191) [skip l10n]

---

bedrock/firefox/templates/firefox/channel/desktop.html

Fixes: https://github.com/mozilla/bedrock/issues/9836

Force full installer for Firefox Beta on Windows (Fixes #9836)

---

bedrock/security/templates/security/client-bug-bounty.html

Just fixing a typo I randomly found.. CCing @tomrittervg 
The client bounty page has a typo (extra letter)
None. Is this needed for simple changes?
N/A

Fix typo (originsd -> origins)

---

bedrock/mozorg/templates/mozorg/about/history.html
bedrock/mozorg/urls.py
l10n/en/mozorg/about/history.ftl
lib/fluent_migrations/mozorg/about/history.py

http://localhost:8000/about/history/
#9805
```
```

Migrate about/history page to Fluent (Fixes #9805) [skip l10n]

---

bedrock/firefox/templates/firefox/browsers/browser-history.html
bedrock/firefox/templates/firefox/browsers/incognito-browser.html
bedrock/firefox/templates/firefox/browsers/update-browser.html
bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
media/css/firefox/browsers/browser-history.scss
media/css/firefox/browsers/incognito-browser.scss
media/css/firefox/browsers/update-browser.scss
media/css/firefox/browsers/what-is-a-browser.scss
tests/functional/firefox/browsers/test_browser_history.py
tests/functional/firefox/browsers/test_incognito_browser.py
tests/functional/firefox/browsers/test_update_browser.py
tests/functional/firefox/browsers/test_what_is_a_browser.py
tests/pages/firefox/browsers/browser_history.py
tests/pages/firefox/browsers/incognito_browser.py
tests/pages/firefox/browsers/update_browser.py
tests/pages/firefox/browsers/what_is_a_browser.py

Adds primary/secondary download buttons to several SEO pages:
- http://localhost:8000/en-US/firefox/browsers/update-your-browser/
- http://localhost:8000/en-US/firefox/browsers/what-is-a-browser/
- http://localhost:8000/en-US/firefox/browsers/incognito-browser/
- http://localhost:8000/en-US/firefox/browsers/browser-history/
#9712
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/237141339

Add primary/secondary download buttons to SEO pages (Fixes #9712)

---

bedrock/firefox/templates/firefox/features/password-manager.html
bedrock/firefox/templates/firefox/privacy/book.html
l10n/en/firefox/features/password-manager.ftl
l10n/en/firefox/privacy/book.ftl

- Updates pages that used outdated terminology.
- Changes to `pontoon.toml` and `brands.ftl` relate to what's in master in the L10n repo (see https://github.com/mozilla/bedrock/pull/9827 and https://github.com/mozilla/bedrock/pull/9829)
URLs:
- http://localhost:8000/en-US/firefox/features/password-manager/
- http://localhost:8000/en-US/firefox/privacy/book/
#9738

Replace 'master password' terminology with 'primary password' (Fixes #9738)

---

bedrock/security/templates/security/web-bug-bounty.html

Specifically exclude *.ngrok.io and "development-only" domains from the Domain Takeover bounty.

Mention and exclude ngrok from domain takeover bounties

---

media/css/firefox/whatsnew/whatsnew-account.scss
media/css/firefox/whatsnew/whatsnew-mobile-de.scss
media/css/firefox/whatsnew/whatsnew.scss

Using dark theme colors, the "Your download link was sent" is not currently readable.
- http://localhost:8000/de/firefox/85.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/60.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/whatsnew/all/
None

Fix send-to-device success header color

---

bedrock/firefox/templates/firefox/welcome/page7.html

Looks like these were copied from welcome/6 but not needed on welcome 7 in the end.
No bug.
http://localhost:8000/en-US/firefox/welcome/7/

Remove unused variables on welcome/7 (no bug)

---

bedrock/base/templates/macros.html
bedrock/base/templatetags/helpers.py
bedrock/base/tests/test_helpers.py
bedrock/firefox/forms.py
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx80.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx81.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/settings/base.py
docs/send-to-device.rst
l10n/en/firefox/whatsnew/whatsnew-fx80.ftl
l10n/en/firefox/whatsnew/whatsnew-fx81.ftl
l10n/en/send_to_device.ftl
media/css/protocol/components/send-to-device.scss
media/js/base/send-to-device.js
tests/redirects/map_globalconf.py
tests/unit/spec/base/send-to-device.js

Remove SMS feature for send to device 
- rename form field from  `phone-or-email` to `s2d-email` (unique name makes it easier to trace the path through the code)
- remove `legal_note_sms` and `input_label_alt` from macro
- remove sms error and thank you messages and form labeling
- remove geolocation check from helpers and javascript
- remove sms from message sets (keep message sets because not all countries get email option)
- remove sms tests
- convert one test from sms to email
- update docs to remove sms references
- remove sms strings from ftl files
- update JS and CSS to remove sms behaviour and styles
- update JS tests
See #9864 
Testing values: success@example.com, failure@example.com, invalid@email.
Should still fallback to QR codes for languages without translated emails (eg. …

Remove SMS feature for send to device (#9864)

---

bedrock/firefox/views.py

New redesign is here to stay, we can remove the switch
(no bug)

Remove new-redesign switch (no bug)

---

bedrock/firefox/redirects.py
bedrock/firefox/templates/firefox/mobile/index.html
tests/redirects/map_globalconf.py

Over time the content of the pages at /sync and /accounts have changed. This PR updates some redirects and content links to point to the more appropriate of the two locations.
Fix #9860
http://localhost:8000/en-US/firefox/mobile/

Update links to sync and accounts (Fix #9860)

---

bedrock/base/templates/404.html
bedrock/base/templates/500.html
bedrock/base/views.py
l10n/en/404.ftl
l10n/en/500.ftl
lib/fluent_migrations/404.py
lib/fluent_migrations/500.py

- http://localhost:8000/en-US/404/
- http://localhost:8000/en-US/500/
#9807
```
```

Migrate error pages to Fluent (Fixes #9807) [skip l10n]

---

.circleci/config.yml

Adding our dockerhub creds to pull images, so we can avoid getting rate limited.
The build failed when I put bad creds into the env variables, and passed when good creds were added.
Checked that the username/password wasn't echo'd in the logs, and that seems to be true for both jobs.

Adding dockerhub creds to circleci builds

---

bedrock/privacy/templates/privacy/base-protocol.html
bedrock/privacy/templates/privacy/faq.html
bedrock/privacy/templates/privacy/index.html
bedrock/privacy/templates/privacy/principles.html
bedrock/privacy/urls.py
bedrock/privacy/views.py
docs/fluent-conversion.rst
l10n/configs/pontoon.toml
l10n/en/brands.ftl
l10n/en/privacy/faq.ftl
l10n/en/privacy/index.ftl
l10n/en/privacy/principles.ftl
lib/fluent_migrations/privacy/faq.py
lib/fluent_migrations/privacy/index.py
lib/fluent_migrations/privacy/principles.py

Updates the contact section of the privacy pages _(completed by @craigcook)_  and migrates the pages to Fluent in the process. 
- Privacy (/privacy/)
- Privacy FAQs (/privacy/faq)
- Privacy Principles (/privacy/principles/)
- #9388 
- #9809
- http://localhost:8000/privacy/
- http://localhost:8000/privacy/principles/
- http://localhost:8000/privacy/faq/

Migrate /privacy pages to Fluent

---

bedrock/legal/templates/legal/docs-base.html
bedrock/legal/templates/legal/eula.html
bedrock/legal/templates/legal/eula/firefox-2-eula.html
bedrock/legal/templates/legal/eula/firefox-3-eula.html
bedrock/legal/templates/legal/eula/thunderbird-1.5-eula.html
bedrock/legal/templates/legal/eula/thunderbird-2-eula.html
bedrock/legal/templates/legal/fraud-report.html
bedrock/legal/templates/legal/index.html
bedrock/legal/templates/legal/report-infringement.html
bedrock/legal/templates/legal/terms/acceptable-use.html
bedrock/legal/templates/legal/terms/betterweb.html
bedrock/legal/templates/legal/terms/firefox-lite-reward.html
bedrock/legal/templates/legal/terms/firefox-lite.html
bedrock/legal/templates/legal/terms/firefox-private-network.html
bedrock/legal/templates/legal/terms/firefox-reality.html
bedrock/legal/templates/legal/terms/firefox-relay.html
bedrock/legal/templates/legal/terms/firefox.html
bedrock/legal/templates/legal/terms/mozilla-vpn.html
bedrock/legal/templates/legal/terms/mozilla.html
bedrock/legal/templates/legal/terms/services.html
bedrock/legal/templates/legal/terms/thunderbird.html
bedrock/legal/templates/legal/terms/vpn.html
bedrock/legal/urls.py
bedrock/legal_docs/views.py
l10n/configs/pontoon.toml
l10n/en/mozorg/about/legal.ftl
lib/fluent_migrations/legal/index.py

http://localhost:8000/en-US/about/legal/
#9808
```
```

Migrate /legal pages to Fluent (Fixes #9808)

---

bedrock/legal_docs/views.py

Adds reference to `privacy/index` Fluent file to the legal doc view so all privacy pages can get those strings in the sidebar.
http://localhost:8000/privacy/firefox/

Fix common strings on privacy policies

---

bedrock/firefox/templates/firefox/new/protocol/base_download.html
bedrock/firefox/templates/firefox/new/trailhead/base.html
bedrock/firefox/templates/firefox/new/trailhead/download-yandex.html
bedrock/firefox/templates/firefox/new/trailhead/download.html
media/css/firefox/new/trailhead/download.scss

- remove background images from platform and Yandex pages
#9266
http://localhost:8000/en-US/firefox/mac/
http://localhost:8000/ru/firefox/new/?geo=ru
http://localhost:8000/ru/firefox/new/
http://localhost:8000/eu/firefox/new/ (you will have to switch your environment to `DEBUG=False` to view this page using the fallback, or you can edit the view)

Update design on /new varients (#9266)

---

media/css/firefox/sticky-promo.scss
media/css/protocol/components/_footer.scss
media/js/firefox/sticky-promo.js
tests/functional/firefox/browsers/compare/test_browsers.py
tests/functional/firefox/browsers/test_best_browser.py
tests/functional/firefox/browsers/test_browser_history.py
tests/functional/firefox/browsers/test_incognito_browser.py
tests/functional/firefox/browsers/test_what_is_a_browser.py
tests/functional/firefox/browsers/test_windows_64_bit.py
tests/functional/firefox/features/test_adblocker.py
tests/functional/firefox/features/test_features.py
tests/functional/firefox/features/test_landing.py
tests/functional/firefox/new/test_sticky_promo.py
tests/functional/firefox/test_home.py
tests/functional/firefox/test_releasenotes.py
tests/pages/firefox/browsers/best_browser.py
tests/pages/firefox/browsers/browser_history.py
tests/pages/firefox/browsers/compare.py
tests/pages/firefox/browsers/incognito_browser.py
tests/pages/firefox/browsers/what_is_a_browser.py
tests/pages/firefox/browsers/windows_64_bit.py
tests/pages/firefox/features/adblocker.py
tests/pages/firefox/features/feature.py
tests/pages/firefox/features/landing.py
tests/pages/firefox/home.py
tests/pages/firefox/new/sticky_promo.py
tests/pages/firefox/releasenotes.py

This PR adds two revisions to the UX of the [sticky download promo](https://protocol.mozilla.org/patterns/molecules/sticky-promo.html):
1. When the footer is in the viewport, the promo box is hidden. 
2. The promo box is not displayed until a user scrolls on the page. 
TODO: 
#9717
*Be sure to delete any `localhost` cookeis you may have*
1. Go to http://localhost:8000/en-US/firefox/new/
2. Scroll down the page some. 
3. Expected: Promo should appear
4. Scroll down to where the footer is in view. 
5. Expected: Promo should dissapear 
6. Scrioll back up to where the footer is no longer in view
7. Expected: Promo should reappear 
Notes: 
- I couldn't find a page that had the promo that was so short that the footer was already in view. It is assumed that the promo would not be displayed. 
- …

Revise UX/Behavior of Sticky Download Promo 

---

bedrock/mozorg/templatetags/qrcode.py

Writing to the `DATA_PATH` in our deployments doesn't work as that is mounted as a RO volume to the host node.

Move QR Code cache to /tmp

---

bedrock/firefox/templates/firefox/retention/thank-you.html
bedrock/firefox/urls.py
l10n/configs/pontoon.toml
l10n/en/brands.ftl
l10n/en/firefox/retention/thank-you.ftl
lib/fluent_migrations/firefox/retention/thank-you.py

http://127.0.0.1:8000/en-US/firefox/retention/thank-you/
#9811
```
```

Migrate /firefox/retention/thank-you/ to Fluent (Fixes #9811)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-mobile-qrcode-de.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
media/css/firefox/whatsnew/whatsnew-mobile-qrcode-de.scss
media/js/firefox/whatsnew/up-to-date.js
media/static-bundles.json
tests/functional/firefox/whatsnew/test_whatsnew_86.py
tests/pages/firefox/whatsnew/whatsnew_86.py

- http://localhost:8000/de/firefox/86.0/whatsnew/all/ (Firefox Mobile promo with QRCode)
- http://localhost:8000/fr/firefox/86.0/whatsnew/all/ (Template from WNP81 with Send to Device)
#9926
Demo
- https://www-demo2.allizom.org/de/firefox/86.0/whatsnew/all/
- https://www-demo2.allizom.org/fr/firefox/86.0/whatsnew/all/

WNP 86 for /de/ and /fr/ (Fixes #9926)

---

bedrock/mozorg/templatetags/qrcode.py
bedrock/mozorg/tests/test_helper_qrcode.py
bedrock/settings/__init__.py

Some deployments (e.g. Demos) don't have writable file systems.
Also it seems to be frowned upon to write to the FS in Docker in
general. This should work as well or better.

Move QR Code generator cache from file system to memory

---

bedrock/firefox/templates/firefox/nightly/firstrun.cs.html
bedrock/firefox/templates/firefox/nightly/firstrun.de.html
bedrock/firefox/templates/firefox/nightly/firstrun.es-AR.html
bedrock/firefox/templates/firefox/nightly/firstrun.es-ES.html
bedrock/firefox/templates/firefox/nightly/firstrun.fr.html
bedrock/firefox/templates/firefox/nightly/firstrun.it.html
bedrock/firefox/templates/firefox/nightly/firstrun.ru.html

This change updates the obsolete text and links on the German Firefox nightly Firstrun page. Additionally, it fixes the visibility of all headings in the German page and other custom locales.
This fixes #9930, related to https://bugzilla.mozilla.org/show_bug.cgi?id=1692600
Run the server locally and visit http://localhost:8000/de/firefox/nightly/firstrun/. The links should be up-to-date and the heading "Erfahren Sie mehr über die lokale Mozilla-Community" should be visible. Additionally, the headings for the other locales `cs`, `es-AR`, `es-ES`, `fr`, `it`, `ru` should now be visible too.

Update obsolete links on German Firefox nightly Firstrun page, fix heading visibility (fixes #9930)

---

media/js/base/fxa-utm-referral-init.js
media/js/base/fxa-utm-referral.js
tests/unit/spec/base/fxa-utm-referral.js
tests/unit/spec/ie/mozilla-utils-ie.js

- http://localhost:8000/en-US/firefox/accounts/?entrypoint_experiment=test&entrypoint_variation=test
- http://localhost:8000/en-US/firefox/accounts/?utm_source=test&utm_campaign=test&entrypoint_experiment=test&entrypoint_variation=test
#9922

Pass through experiment and variation parameters to FxA links (Issue #9922)

---

bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

- Passes Google Analytics visit ID to stub attribution for Windows visitors.
#9830
Demo: https://www-demo3.allizom.org/

Pass GA visit ID to stub attribution (Fixes #9830)

---

bedrock/base/templates/includes/sticky-promo.html
bedrock/firefox/templates/firefox/faq.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx79.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx82.html
bedrock/foundation/templates/foundation/annualreport/2019/index.html
l10n/en/firefox/faq.ftl

Changes internal links from `vpn.mozilla.org` to `/products/vpn/`. This is to begin funnelling some traffic to the new VPN landing page.
**Note:** I'm deliberately leaving out WNP 84 and 85 for now, since those currently attribute ~80% of total traffic to vpn.mozilla.org. We can update these WNPs to point to /products/vpn/ when we're ready to retire the old landing page.
#9942
- http://localhost:8000/en-US/firefox/79.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/82.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/
- http://localhost:8000/en-US/firefox/faq/
- http://localhost:8000/en-US/foundation/annualreport/2019/

Update internal links to point to /products/vpn/ (#9942)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx84.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx85.html

- http://localhost:8000/en-US/firefox/84.0/whatsnew/all/
- http://localhost:8000/en-US/firefox/85.0/whatsnew/all/
#9942

Update vpn.mozilla.org links on /whatsnew to point to /products/vpn/ (Fixes #9942)

---

bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
bedrock/settings/base.py
docs/firefox-accounts.rst

- Add env variable for setting VPN product links to point to staging.
- Add documentation for VPN link helpers.
#9952

Add support for staging instances to VPN product buttons (Fixes #9952)

---

bedrock/base/templates/macros-protocol.html
bedrock/firefox/templates/firefox/products/lockwise.html
media/css/firefox/lockwise/lockwise.scss

Swaps custom subheading for Protocol supported tagline.
Fix #9977
Only place with a tagline:
https://www-demo-pr-9978.herokuapp.com/en-US/firefox/lockwise/
Other hero components to make sure I didn't break anything:
https://www-demo-pr-9978.herokuapp.com/en-US/firefox/features/
https://www-demo-pr-9978.herokuapp.com/en-US/firefox/privacy/

Swap subheading for tagline in Hero (Fix #9977)

---

media/js/base/fxa-utm-referral.js
media/js/base/mozilla-fxa-product-button.js

A small update to https://github.com/mozilla/bedrock/issues/9952 to ensure FxA metric and utm params are added to VPN links when set to staging.
http://localhost:8000/en-US/products/vpn/?utm_source=test&utm_campaign=test
#9952
Set the following in your `.env` file to test locally:
```
FXA_ENDPOINT=https://stable.dev.lcip.org/
VPN_ENDPOINT=https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/
```

Add VPN staging domain to allowedList for FxA metrics (#9952)

---

bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py

I noticed the extra redirect when inspecting network traffic.

fix: remove trailing slash from vpn urls to save a redirect

---

bedrock/security/templates/security/web-bug-bounty.html

Add an exception for S3 buckets and logging domains for subdomain takeovers to the web bug bounty policy 
We've received a number of bugs for takeovers of S3 buckets found in infra repos with limited security impact.
I'd like to consider an S3 bucket takeover as a security bug only when reporters can demonstrate additional security impact such as:
* use as a plausible phishing domain e.g. from an alias to the bucket content
* bucket content used on a public site, CDN, or internal service (so XSS or CSS/HTML injection risk; adding malicious binaries or updates for public consumption or that an internal service will use)
* receives confidential info or PII with a sample e.g. here's an API key or logs
Bugs filed before this change plus some grace period of a week or two would be handled …

clarify domain takeovers for S3 buckets

---

media/MPL/2.0/index.txt

The [HTML version](https://www.mozilla.org/en-US/MPL/2.0/) of the license points to the HTTPS URL:
https://github.com/mozilla/bedrock/blob/564f4fcbb62755a9aea3e78138d2616361a77e56/bedrock/mozorg/templates/mozorg/mpl/2.0/index.html#L135
but the [plaintext version](https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt) is still using the legacy HTTP URL.
No bug
1. Go to <https://www.mozilla.org/en-US/MPL/>.
2. Click on the *plain text* link in the second paragraph.
3. Search for `https:`.

Fix URL scheme to match HTML page.

---

bedrock/firefox/redirects.py
tests/redirects/map_globalconf.py

Update http://mozilla.org/firefox/central redirect to /firefox, instead of SUMO page. 
#10004
1. Go to http://localhost:8000/en-US/firefox/central
2. Should redirect to http://localhost:8000/en-US/firefox/

Fix #1004 - Update /firefox/central redirect

---

bedrock/privacy/templates/privacy/notices/mozilla-vpn.html

http://localhost:8000/en-US/privacy/mozilla-vpn/
#10025

Add Mozilla VPN logo to privacy notice page (Fixes #10025)

---

bedrock/products/templates/products/vpn/platforms/android.html
bedrock/products/templates/products/vpn/platforms/desktop.html
bedrock/products/templates/products/vpn/platforms/ios.html
bedrock/products/templates/products/vpn/platforms/linux.html
bedrock/products/templates/products/vpn/platforms/mac.html
bedrock/products/templates/products/vpn/platforms/mobile.html
bedrock/products/templates/products/vpn/platforms/windows.html

Updated server count for VPN platform pages
#10033
Confirm the instance of `750` on these pages:
- http://localhost:8000/en-US/products/vpn/desktop/    
- http://localhost:8000/en-US/products/vpn/desktop/linux/
- http://localhost:8000/en-US/products/vpn/desktop/mac/
- http://localhost:8000/en-US/products/vpn/desktop/windows/
- http://localhost:8000/en-US/products/vpn/mobile/
- http://localhost:8000/en-US/products/vpn/mobile/android/
- http://localhost:8000/en-US/products/vpn/mobile/ios/

Fix #10033 - Update VPN server count to 750

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx87-de.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx87-fr.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

- http://localhost:8000/de/firefox/88.0/whatsnew/all/
- http://localhost:8000/fr/firefox/88.0/whatsnew/all/
#10049

Show VPN waitlist signup for WNP 88 (DE/FR) (Fixes #10049)

---

l10n/configs/pontoon.toml
l10n/configs/vendor.toml

- Switch Malay (ms) to vendor supported locale
- Remove it from Pontoon
- Add to vendor supported list.
Ref: https://github.com/mozilla-l10n/www-l10n/pull/176
**DO NOT** merge once approved. Needs to be coordinated with  Smartling/L10n team

Migrate `ms` from Pontoon to Smartling

---

bedrock/products/templates/products/vpn/landing.html
bedrock/products/views.py
l10n/en/products/vpn/landing.ftl
media/css/products/vpn/landing.scss

http://localhost:8000/en-US/products/vpn/?vpn-sub-not-found=true
#10002

Add error message for VPN sign-ins without a subscription (Fixes #10002)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx87-de.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx87-fr.html
media/js/base/fxa-utm-referral.js
media/js/base/mozilla-fxa-product-button.js
tests/unit/spec/base/fxa-utm-referral.js

- http://localhost:8000/de/firefox/87.0/whatsnew/all/
- http://localhost:8000/fr/firefox/87.0/whatsnew/all/
- http://localhost:8000/de/firefox/88.0/whatsnew/all/
- http://localhost:8000/fr/firefox/88.0/whatsnew/all/
#10053
1. On each /whatsnew page, click the "Learn more about Mozilla VPN" link at the bottom of the page.
2. Once on the VPN landing page, verify that the URL includes a `source` param specific to the /whatsnew page where the click occured e.g. http://localhost:8000/de/products/vpn/?source=whatsnew88
3. Verify that the VPN subscription links in the landing page have been updated with related utm and entrypoint params e.g.
- `entrypoint=www.mozilla.org-whatsnew`
- `utm_source=www.mozilla.org-whatsnew`
- `utm_campaign=whatsnew88`

Pass attribution from /whatsnew pages to the VPN landing page (Fixes #10053)

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html

'Mozilla Commit Access Policy' describes a mechanism by which a user can go from L2 to L3 with one vouch.  It lists this in the middle of the doc rather than near the L3 section.  This led to multiple people missing the policy exception and a dev being idled for that time.
N/A, though technically inspired by bug 1697933.
None, I moved a line.  Test / change / wordsmith as you see fit.  If you think it should fold into the 'Requirements' line above it, that's totally cool too.

Move the L3 single-voucher requirement under L3

---

bedrock/mozorg/templates/mozorg/home/home.html

#10077 
http://localhost:8000/id/ scroll down to the newsletter form, make sure the button is translated

Home page, fix newsletter button string ID [fix #10077]

---

bedrock/products/templates/products/vpn/includes/pricing-fixed.html

http://localhost:8000/en-US/products/vpn/?geo=de
#10070

Hide price for VPN if not available (Fixes #10070)

---

bedrock/firefox/templates/firefox/mobile/index.html
bedrock/firefox/templates/firefox/new/desktop/download.html
l10n/en/sub_navigation.ftl

Update all instances of "Addons" across the site with "Add-ons" 
#10047
- http://localhost:8000/en-US/firefox/new/
- http://localhost:8000/en-US/firefox/mobile/
_Note - Both instances are in the subnavigation._

Fix #10047 - Update strings to correct spelling of 'Add-ons'

---

bedrock/products/templates/products/vpn/platforms/desktop.html
l10n/en/products/vpn/platforms/desktop.ftl

The word "servers" was missing from the end of the sentence, after the number.
#10082 
http://localhost:8000/products/vpn/desktop/ about halfway down the page under "Connect to servers all over the world"

Fix string on VPN desktop page [fix #10082]

---

l10n/en/products/vpn/platforms/mobile.ftl
l10n/en/products/vpn/shared.ftl

Replaces straight apostrophes with curly ones (en-* only, don't need to change string IDs)
#10086 
http://localhost:8000/products/vpn/mobile/

Curly apostrophes on VPN pages [fix #10086]

---

bedrock/firefox/templates/firefox/releases/notes.html

Firefox for Android Beta release notes are not updating on the website anymore. Hide the menu link while we investigate.
Bug #1701489
See #10064

Hide release notes for Firefox for Android Beta (Bug #1701489)

---

bedrock/foundation/templates/foundation/trademarks/distribution-policy.html
bedrock/foundation/templates/foundation/trademarks/policy.html
bedrock/legal/templates/legal/fraud-report.html
bedrock/legal/tests/test_forms.py
bedrock/legal/urls.py
bedrock/mozorg/redirects.py
bedrock/mozorg/templates/mozorg/mpl/license-policy.html

#9984 
Confirm copy edits on the following pages: 
- https://www-demo-pr-10102.herokuapp.com/en-US/foundation/trademarks/distribution-policy/ 
- https://www-demo-pr-10102.herokuapp.com/en-US/MPL/license-policy/
- https://www-demo-pr-10102.herokuapp.com/en-US/about/legal/defend-mozilla-trademarks/
Redirects: 
- The old Fraud Report page should redirect to the new URL: 
https://www-demo-pr-10102.herokuapp.com/en-US/about/legal/fraud-report/ -> https://www-demo-pr-10102.herokuapp.com/en-US/about/legal/defend-mozilla-trademarks/

Fix #9984 - Policy Page Updates

---

bedrock/products/templates/products/vpn/platforms/android.html
bedrock/products/templates/products/vpn/platforms/desktop.html
bedrock/products/templates/products/vpn/platforms/ios.html
bedrock/products/templates/products/vpn/platforms/linux.html
bedrock/products/templates/products/vpn/platforms/mac.html
bedrock/products/templates/products/vpn/platforms/mobile.html
bedrock/products/templates/products/vpn/platforms/windows.html

http://localhost:8000/en-US/products/vpn/desktop/
#10107

VPN platform pages should use shared variables (Fixes #10107)

---

bedrock/products/templates/products/vpn/includes/subnav.html
bedrock/products/templates/products/vpn/landing.html
l10n/en/products/vpn/landing.ftl
l10n/en/products/vpn/shared.ftl
media/js/products/vpn/landing.js

- Add sub navigation to VPN landing page.
- Link to VPN platform pages from within FAQ content.
#10106

Add sub-nav to VPN landing page (Fixes #10106)

---

bedrock/security/templates/security/web-bug-bounty.html

Adds an exception to domain takeovers, requiring a proof of concept, where previously this was not required.

Add exception for domain takeovers to include a proof of concept

---

bedrock/base/geo.py

When `DEV == True` we used to always return the default country.
Now we return the country from the CloudFlare header whenever it's
present, and the default country only if it's not and it's in DEV mode.

Fix #10139: Allow Geo to work via CF header in dev

---

media/css/products/vpn/common.scss
media/css/products/vpn/components/block.scss
media/css/products/vpn/components/hero.scss

Some CSS fixes to better cater for longer strings (such as German) on small viewports. This is mostly just making copy a little smaller on mobile screen sizes. Large viewports should be uneffected.
- Reduce hero font size on small screens.
- Reduce block component padding & font-size on small screens.
- Reduce feature list font size / spacing on small screens.
I've tried to ensure things are still readable (i.e. not truncated or cut off screen) down to 320px in German.
- http://localhost:8000/de/products/vpn/
- http://localhost:8000/fr/products/vpn/
#10130

L10n fixes for VPN landing page on mobile (Fixes #10130)

---

media/js/base/protocol/protocol-sub-navigation.js

Fix sub navigation when viewport is exactly 768px wide (Fixes #10123)

---

media/css/legal/legal.scss

The word "Servicebedingungen" is so long here that reducing the default font size on small screens isn't really a viable option, so this is the best I can come up with.
http://localhost:8000/de/about/legal/terms/mozilla-vpn/
#10141

Fix heading overflow on German VPN legal page (Fixes #10141)

---

media/css/firefox/whatsnew/whatsnew-88-en.scss

The en-US whatsnew page for Fx88 doesn't support dark mode, but the included styles from `_header.scss` still swap the wordmark. This fix overrides that styling.
#10150 
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/
Set your OS to dark mode and ensure the wordmark is still readable.

Fix WNP88 Firefox wordmark in dark mode [fix #10150]

---

media/js/base/mozilla-utils.js
tests/unit/spec/base/mozilla-utils.js

Changes the `Mozilla.Utils.maybeSwitchToChinaRepackImages()` function so it will only look for matching selectors if the distribution ID is specifically `mozillaonline`.
Should fix errors such as: https://sentry.prod.mozaws.net/operations/bedrock-prod/?query=is%3Aunresolved+SyntaxError%3A+%27img%5Bdata&sort=freq
#10157

Only try and swap out images for China Repack builds (Fixes #10157)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx88-en.html

Updates the source param to include the variant.
#10160 
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/ (no variant)
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/?v=1
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/?v=2
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/?v=3
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/?v=4
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/?v=5

WNP88, add variant to source param [fix #10160]

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx88-en.html

The old "using now" <-> "now using" switcheroo.
http://localhost:8000/en-US/firefox/88.0/whatsnew/all/

Fix typo on WNP88 :facepalm: [no bug]

---

bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py

Removes `vpn-new-subscription-url-format` switch (new URLs went live in prod yesterday).
#10126

Remove switch for new VPN subscription URLs (#10126)

---

bedrock/base/templates/includes/banners/vpn/vpn-promo.html
bedrock/firefox/templates/firefox/browsers/index.html
bedrock/firefox/templates/firefox/home/index-master.html
bedrock/firefox/templates/firefox/privacy/products.html
bedrock/firefox/templates/firefox/products/index.html
bedrock/mozorg/templates/mozorg/home/home-de.html
bedrock/mozorg/templates/mozorg/home/home-en.html
bedrock/mozorg/templates/mozorg/home/home-fr.html
bedrock/mozorg/templates/mozorg/home/home.html
media/css/base/banners/vpn-promo.scss
media/js/base/banners/vpn-promo-banner-init.js
media/static-bundles.json

Adds Mozilla VPN banner to the following pages:
- http://localhost:8000/de/
- http://localhost:8000/de/firefox/
- http://localhost:8000/de/firefox/privacy/products/
- http://localhost:8000/de/firefox/browsers/
- http://localhost:8000/de/firefox/products/
- http://localhost:8000/fr/
- http://localhost:8000/fr/firefox/
- http://localhost:8000/fr/firefox/privacy/products/
- http://localhost:8000/fr/firefox/browsers/
- http://localhost:8000/fr/firefox/products/
#10178

Add VPN site banner for DE/FR (Fixes #10178)

---

bedrock/base/templates/includes/protocol/footer/footer.html
media/js/privacy/privacy-firefox.js
media/js/privacy/privacy-protocol.js

- Enabled link targeting on privacy notice pages.
- Fixes broken cookies link in website footer.
#10186

Enable target-linking on privacy notice pages (Fixes #10186)

---

media/js/base/mozilla-cookie-helper.js

This PR will let the cookie-helper lib set the samesite explicitly. Boolean value 'true' and 'false' will be evaluated to 'strict' and 'none' respectively. Also user can set the value of samesite by specifying numbers ( for ex- 1 will be 'strict' and -1 will be 'none' .Besides strings like 'strict', 'lax', 'none' will also work (case-insensitive).  The default value is 'lax'
#8670

Update cookie-helper: add samesite [fixes #8670]

---

media/js/base/core-datalayer.js
tests/unit/spec/base/core-datalayer.js

Fixes an error where some logged-in FF clients can return `undefined` when querying `browserServices.sync`.
#10118
- I added a unit test for this that should cover things.

Fix JS error e.browserServices.sync is undefined (Fixes #10118)

---

docs/install.rst

The file ``.gitmodules`` was left empty after PR #9213, and ``git clone --recursive`` is no longer needed.

Remove .gitmodules

---

bedrock/firefox/templates/firefox/developer/whatsnew.html
bedrock/firefox/views.py
l10n/en/firefox/developer.ftl

It fixes issue #10063. It works same as the bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1700518 suggests. 
#10063
go to http://127.0.0.1:8000/en-US/firefox/88.0a2/whatsnew/all/?oldversion=87.0 . Remove the oldversion attribute from the link and compare the change in the heading.

Differentiate headings for installations stuff [ fixes #10063]

---

bedrock/settings/base.py
bin/run-db-update.sh

We are not using it for now, and a 404 means that data updating fails.
Re #10222

Stop pulling data from wordpress blogs

---

media/js/base/send-to-device.js

Fixes https://sentry.prod.mozaws.net/operations/bedrock-prod/?query=is%3Aunresolved+this.widget+is+null
This error occurs because some locales don't have a send-to-device widget in the template, and the JS expects it to be there.
#7673

Fix send-to-device JS error if there's no form in the template (#7673)

---

bedrock/products/templates/products/vpn/includes/footer-download-exp.html
bedrock/products/templates/products/vpn/includes/pricing-fixed.html
bedrock/products/templates/products/vpn/includes/pricing-variable.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/templates/products/vpn/variants/download-a.html
bedrock/products/templates/products/vpn/variants/download-b.html
bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
bedrock/products/tests/test_views.py
bedrock/products/views.py
media/css/products/vpn/common.scss
media/js/base/fxa-utm-referral.js
media/js/base/mozilla-fxa-product-button.js
media/js/products/vpn/download-first-experiment.js
media/js/products/vpn/download-first-geo-callback.js
media/js/products/vpn/geo.js
media/static-bundles.json
tests/unit/spec/base/fxa-utm-referral.js
tests/unit/spec/base/mozilla-fxa-product-button.js

Adds a "download first" experiment to the VPN landing page with two variations:
- a) Control
- b) "Get Mozilla VPN" buttons link directly to a client download page (`/vpn/download`). The pricing/subscription section of the page still links to regular FxA auth flow (`/vpn/subscribe`). 
Experiment targets Windows and macOS only.
To understand the full user flow, you can view the [figma file here](https://www.figma.com/file/Rvu8RsVhTksMs48b5pRlup/Mozilla-VPN---Download-Experiment-Flowchart?node-id=0%3A1).
#10209
**Demo URLs:**
- https://www-demo1.allizom.org/en-US/products/vpn/?entrypoint_experiment=vpn-landing-page-download-first&entrypoint_variation=a (control)
- https://www-demo1.allizom.org/en-US/products/vpn/?entrypoint_experiment=vpn-landing-page-download-first&entrypoint_variation=b …

VPN download-first experiment (Fixes #10209)

---

bedrock/mozorg/templates/mozorg/about/leadership.html

We were asked to change the ordering to strictly alphabetical (previously we listed steering committee members first, then everyone else). Also adding Mark Surman to the MoFo board.
http://localhost:8000/about/leadership/

Leadership ordering, add Surman to MoFo board [no bug]

---

bedrock/mozorg/templates/mozorg/home/home.html
tests/functional/test_home.py
tests/pages/home.py

I wrote tests assuming the MR1 promo would be everywhere, then neglected to update them when it was removed from DE and FR.
Run `tests/functional/test_home.py`

Fix/update home page tests [#10167]

---

bedrock/products/templates/products/vpn/includes/footer-download-exp.html
bedrock/products/templates/products/vpn/variants/download-b.html

Adds default analytics params to variation b of download experiment.
http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-landing-page-download-first&entrypoint_variation=b
#10247
Setup: make sure to set `FXA_ENDPOINT=https://stable.dev.lcip.org/` in your `.env`.
"Get Mozilla VPN" links that point to `vpn/download` should now also contain:

Add analytics params to VPN download experiment links (Fixes #10247)

---

bedrock/press/templates/press/speaker-request.html
media/js/base/base-page-init.js
media/js/base/core-datalayer-init.js
media/js/base/mozilla-utils.js
media/js/firefox/whatsnew/whatsnew.js
media/js/press/speaker-request.js
media/js/privacy/privacy-firefox.js

- Updates DOM Ready and window load events to use vanilla JS in `base-page-init.js`.
- Updates a few other misc files that had stray references to jQuery.
#7523
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/303962734

Remove jQuery from base-page-init.js and other misc files (Fixes #7523)

---

l10n/configs/pontoon.toml

`sco` is for Scots, which is localized for Firefox and ready for Beta. There are links in the product that take users to mozilla.org.

Add locale `sco` per community request

---

bedrock/products/templates/products/vpn/includes/pricing-fixed.html
bedrock/products/templates/products/vpn/includes/pricing-variable.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
bedrock/products/views.py
bedrock/settings/base.py
media/css/products/vpn/common.scss
media/css/products/vpn/components/block.scss
media/js/products/vpn/geo.js
tests/functional/products/vpn/test_landing.py

- Enables variable pricing for VPN in wave 1 countries.
- Feature toggled via `SWITCH_VPN_VARIABLE_PRICING_WAVE_1=on`
#10199
Variable pricing should be shown in US$ for wave 1 countries (clicking "Get Mozilla VPN" should scroll to pricing section):
Variable pricing should be shown in Euros for wave 2 countries (clicking "Get Mozilla VPN" should scroll to pricing section):
Waitlist should be displayed for countries where VPN is not yet available:

Enable VPN variable pricing for wave 1 countries (Fixes #10199)

---

media/css/mozorg/home/home.scss

The billboard has a negative top margin to create the "pop-out" effect on the dino image, but that was causing content overlap at smaller screen sizes. This compensates for that by adding some generous margin on the container.
#10273 

Fix legacy home page billboard spacing [fix #10273]

---

bedrock/settings/base.py

I think this is all we need to do to enable `sco` in prod for whatever pages are activated. 
cc @peiying2

Enable sco locale in production

---

bedrock/security/templates/security/web-bug-bounty.html

This removes the lowest tier of bug bounty rewards for subdomain takeovers and restricts payments to only eligible properties and properties which are hanging off *.mozilla.org, *.mozilla.com, *.mozilla.net, or *.firefox.com.

Remove Low subdomain wildcard

---

bedrock/firefox/templates/firefox/releases/notes.html

- Do not display the Developer section for dot releases on the Release channel
- Keep displaying it on other release notes (major release, beta, nightly, esr)
- Display the Developer section for a dot release if one of the fixes included has a note tagged with `Developer` in nucleus
Issue #10287
These release notes should have a Developer section:
- https://www.mozilla.org/en-US/firefox/89.0/releasenotes/ 
- https://www.mozilla.org/en-US/firefox/beta/notes/
- https://www.mozilla.org/en-US/firefox/nightly/notes/
- https://www.mozilla.org/en-US/firefox/78.10.0/releasenotes/
Most dot releases shouldn't have a developer section:
- https://www.mozilla.org/en-US/firefox/85.0.2/releasenotes/
Only dot releases with a note which has the Developer tag should have a Developer section;
- …

Issue #10287: Do not show Developer section in release notes for dot releases

---

l10n/configs/pontoon.toml
l10n/en/firefox/whatsnew/whatsnew-fx90.ftl

Exposes `whatsnew-fx90.ftl` in Pontoon for locales "de", "fr", "it", "nl", and "es-ES".
The EU team want to get this in ahead of https://github.com/mozilla/bedrock/pull/10295 to give the community as much time as possible to translate.
#10270

Expose Fluent strings for WNP 90 (Issue #10270)

---

bedrock/products/templates/products/vpn/includes/templates.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
bedrock/products/views.py
bedrock/settings/base.py
l10n/en/products/vpn/shared.ftl
media/css/products/vpn/components/block.scss
media/js/products/vpn/geo.js
tests/unit/spec/vpn/geo.js

Enables VPN availability in new EU countries (behind a feature switch)
#10280
Note: this will go through a week of testing by the product QA team prior to launch on www-dev, but I tried to provide some (hopefully) easy to follow steps for reviewing the changes here:
To test this PR please set the following in your `.env` file:
```
SWITCH_VPN_VARIABLE_PRICING_WAVE_1=off
SWITCH_VPN_VARIABLE_PRICING_EU_EXPANSION=on
```
**New countries:**
Page should display variable pricing in Euros:
Page should display variable pricing in Swis Francs:
**Not available:**

Enable new EU countries on VPN landing page (Fixes #10280)

---

bedrock/products/templates/products/vpn/landing.html

Adds introductory offer to the top of the VPN landing page for wave 1 countries (EN locales only).
localhost:8000/en-US/products/vpn/?geo=us
#10286

Add pricing offer to VPN hero for wave 1 countries (en only) (Fixes #10286)

---

bedrock/newsletter/forms.py
bedrock/newsletter/tests/test_forms.py

For the newsletter/existing/<token>/ form (email preferences) it would
select the first country in the list if the country from the user data
was an invalid selection in the list. e.g. if the data said "Spain"
instead of "ES". This change makes the form default to the best country
based on the locale of the page.

Fall back to locale-based country if user data country is invalid

---

bedrock/base/templates/base-protocol.html
media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

- Removes old jQuery calls from stub-attribution script.
- Prevent the script from running on IE6/7 via conditional comment.
- Add custom success / timeout callbacks that might be useful for https://github.com/mozilla/bedrock/issues/10207
- Update tests.
#7524
To test this use **Chrome on a Windows VM**:
1. Open https://www-demo2.allizom.org/en-US/?utm_source=test&utm_campaign=test
2. Click "Download Firefox" in the navigation on the top right.
3. Hold down the shift key and click the "Try downloading again" link to open the download URL in a new tab.
4. Copy the download URL using command + C
5. Open https://www.base64decode.org/
6. Paste the download link in the text field, and then remove everything except the value of the `attribution_code` param (this is the only bit we need to …

Remove jQuery as a dependency from stub-attribution.js (Fixes #7524)

---

bedrock/products/views.py

@pmac r?
I noticed that with `extend()` the country lists we're growing exponentially on each page refresh. I don't quite understand why exactly (my guess is something to do with the setting file acting differently?). Good thing is this is still behind a feature switch.
This PR seems to fix the issue?

Avoid using extend for VPN country lists (#10280)

---

bedrock/firefox/templates/firefox/browsers/compare/edge.html
bedrock/firefox/templates/firefox/browsers/compare/index.html

Per the new Edge, autoplay blocking, an in-browser screenshot, and support for macOS and Linux have all been introduced. Sources:
https://www.microsoftedgeinsider.com/en-us/download?platform=linux-deb
https://techcommunity.microsoft.com/t5/articles/introducing-web-capture-for-microsoft-edge/td-p/1721318
https://www.microsoft.com/en-us/edge
https://www.onmsft.com/how-to/how-to-block-auto-playing-media-in-the-new-microsoft-edge
https://answers.microsoft.com/en-us/microsoftedge/forum/all/how-to-prevent-video-autoplay-in-chromium-edge/7b0bf188-1915-4b61-b186-103fbc6ba556

Update Edge information for the browser comparison page

---

bedrock/products/templates/products/vpn/includes/pricing-variable.html
media/css/products/vpn/components/block.scss

- Update variable pricing section on VPN landing page to recommend 12-month plan vs 6-month (current).
#10302

Change recommended VPN plan to 12-months (Fixes #10302)

---

bedrock/firefox/templates/firefox/new/desktop/thanks-amo-exp.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
media/js/firefox/new/common/thanks-amo-exp.js
media/static-bundles.json

Adds an experiment template for the AMO team at the following URL:
http://localhost:8000/en-US/firefox/download/thanks/?xv=amo
This will help the AMO team understand the impact on installs if they link directly to `/download/thanks/` instead of `/firefox/new/` from AMO pages. The template contains some custom stub attribution logic that will delay the Firefox download (!) if someone lands on the page directly and does not already have a stub attribution cookie.
Obviously this is something we've been cautious about doing be default, but in the confines of an experiment we met and agreed the risk was low enough to test.
~**Note:** this PR relies on some logic added in https://github.com/mozilla/bedrock/pull/10216, so **please review that PR first**.~
#10207
This is up on demo2 for testing: …

AMO attribution experiment template (Fixes #10207)

---

media/js/base/core-datalayer-init.js
media/js/base/core-datalayer.js
media/static-bundles.json
tests/unit/spec/base/core-datalayer.js

For URLs that contain `experiment` and `variation` parameters, both of which match validation specific to AMO experiments, add a `dataLayer.push()` event to register then experiment as a custom dimension in GA.
http://localhost:8000/en-US/?experiment=20210708_amo_experiment_name&variation=variation_1_name
#10175
1.) Open the above URL.
2.) Open web console
3.) In the console enter `window.dataLayer` and hit enter.
4.) Verify that the array contains an abject with `{ "data-ex-name": "20210708_amo_experiment_name", "data-ex-variant": "variation_1_name" }`

Add GA custom dimension for AMO experiments (Fixes #10175)

---

bedrock/products/templates/products/vpn/landing.html
media/css/products/vpn/components/block.scss

Moves VPN pricing component from bottom of page to up underneath the "One tap to privacy" section.
#10321

Move VPN pricing component position (Fixes #10321)

---

bedrock/firefox/templates/firefox/home/index-master.html

We want to replace Lockwise logo link with Mozilla VPN logo link in bottom section above footer on /firefox.
https://github.com/mozilla/bedrock/issues/10299
Scroll down to section above footer. You should see the correct logos (no lockwise, white VPN logo instead)
If you inspect VPN logo, text should be "Mozilla VPN"
If you click VPN logo, you should go to VPN product page: http://localhost:8000/en-US/products/vpn/

Replace lockwise logo with vpn on /firefox (Fixes #10299)

---

media/js/firefox/sticky-promo.js

Sticky elements can be troublesome for people who prefer reduced motion. This adds a matchMedia check and doesn't trigger the sticky promo if it matches `prefers-reduced-motion: reduce`.
#10324 
http://localhost:8000/firefox/
http://localhost:8000/firefox/browsers/
On a Mac, open System Preferences > Accessibility > Display and check "Reduce motion"
The sticky promo should **not** appear when reduced motion is preferred, and should only appear when there's no preference.
The preference can also be emulated via devtools in [Chrome](https://umaar.com/dev-tips/211-media-query-simulation/) and [Edge](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/accessibility/reduced-motion-simulation) but it's a bit hard to get to (alas, not in Firefox devtools yet).

Don’t show sticky promo for reduced motion [fix #10324]

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

Created a redirect that enables a user to add `/vpn` at the end of the mozorg URL to redirect them directly to `/products/vpn`
Issue #10335  
Ran `py.test -r a tests/redirects` and all tests have passed.

Issue #10335: Add simplified VPN redirect

---

bedrock/mozorg/templates/mozorg/contribute.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1714434
https://github.com/mozilla/bedrock/issues/10244

Replace the MDN link by Firefox's docs

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx90-eu.html
l10n/en/firefox/whatsnew/whatsnew-fx90.ftl

Small string update for WNP 90 (VPN)
http://localhost:8000/de/firefox/90.0/whatsnew/all/
#10342
This new string won't show up in the page until it's been translated, but it's a small enough change it should hopefully be easy enough to review and trust that it's good.

Update number of available servers on VPN /whatsnew page 90 (Fixes #10342)

---

media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

- If `utm_content` contains valid RTAMO data, and `referrer` is **not** AMO, then drop attribution data.
#10337
Validate that no attribution cookie is created when hitting a RTAMO link directly (i.e. the referrer is not AMO):
1. On a Windows device using Chrome, open a new Incognito Window and visit https://www-demo2.allizom.org/en-US/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=rta%3Acm9uaW4td2FsbGV0QGF4aWVpbmZpbml0eS5jb20
2. Open Developer Tools and select the Application tab.
3. In the Storage panel on the left, open the Cookie menu and select www-demo2.
4. Validate that there are no `moz-stub-attribution-code` and `moz-stub-attribution-sig` cookies created.

Limit RTAMO attribution to AMO referrals (Fixes #10337)

---

bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
bedrock/settings/base.py
docs/firefox-accounts.rst
media/js/base/fxa-utm-referral.js
media/js/base/mozilla-fxa-product-button.js

- Update VPN subscription links to point to FxA (behind a switch).
- Update FxA referral docs to reflect changes.
#10333

Update VPN subscription links to point to FxA (Fixes #10333)

---

bedrock/firefox/templates/firefox/channel/base.html
bedrock/firefox/templates/firefox/nightly/firstrun.html
bedrock/firefox/templates/firefox/privacy/index.html
bedrock/mozorg/templates/mozorg/moss/index.html
media/css/firefox/channel.scss
media/css/firefox/firstrun/nightly.scss
media/css/firefox/privacy/promise.scss
media/css/mozorg/moss.scss

This PR mainly addressed replacing the old Picto Card component with the new Picto component in Protocol.
#10341 
http://localhost:8000/en-US/firefox/channel/desktop/
http://localhost:8000/en-US/firefox/nightly/firstrun/
http://localhost:8000/en-US/firefox/privacy/
http://localhost:8000/en-US/moss

Issue #10341 Remove deprecated Picto Card components

---

bedrock/base/templates/base-protocol.html
media/static-bundles.json

Splits up `common.js` into three separate bundles with more distinct responsibilities:
- `lib.js` (libraries, utilities, polyfills).
- `ui.js` (global components etc).
- `data.js` (analytics and referrals).
Happy to bikeshed the naming if others have ideas or suggestions.
#9321
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/350097824

Break up common.js bundle (Fixes #9321)

---

bedrock/firefox/templates/firefox/browsers/index.html
bedrock/firefox/templates/firefox/products/index.html
media/css/firefox/browsers-products.scss

When we updated the Browsers page in https://github.com/mozilla/bedrock/commit/346aace714ff65b0410d256ec875e896b47f6b83 I failed to notice that the Products page uses the same style sheet, so some styling was broken. This updates the Products page and makes a few other minor tweaks.
This is currently broken in production (pushed only yesterday) so we should try to fix this ASAP.
http://localhost:8000/firefox/products/

Use Split on Firefox Products page, fix layout [#10341]

---

media/css/protocol/components/_download-button.scss

- Serve Windows 64bit Firefox Beta installer on /channel page for matching user agents.
#10194
Local: http://localhost:8000/en-US/firefox/channel/desktop/
Demo: https://www-demo1.allizom.org/en-US/firefox/channel/desktop/

Use UA detection to serve 64bit builds Firefox Beta on Windows (Fixes #10194)

---

bedrock/exp/views.py

There's no traffic going to this experimental page, but I noticided the MR1 promo strings weren't showing up correctly.
N/A
http://localhost:8000/en-US/exp/

Add promo ftl file to /exp/ home page

---

bedrock/firefox/templates/firefox/products/lockwise.html
bedrock/firefox/templates/firefox/switch.html
bedrock/mozorg/templates/mozorg/home/home-en.html
media/css/firefox/lockwise/lockwise.scss
media/css/firefox/switch.scss
media/css/mozorg/home/home-en.scss

Replacing the soon-to-be deprecated [Hero](https://protocol.mozilla.org/patterns/organisms/hero.html) components in some pages with the new [Split](https://protocol.mozilla.org/patterns/organisms/split.html) component.
#10341 
http://localhost:8000/firefox/lockwise/
http://localhost:8000/firefox/switch/

Update Hero components with Split

---

bedrock/mozorg/templates/mozorg/home/home-en.html

Fixes test failure in https://gitlab.com/mozmeao/www-config/-/jobs/1549619134
See https://github.com/mozilla/bedrock/pull/10384/files#r699390512 for context.
N/A
MR1 promo should default to being visible on http://localhost:8000/en-US/

Fix home page promo switch logic

---

bedrock/base/templates/macros-protocol.html
bedrock/firefox/templates/firefox/developer/includes/for-developers.html
bedrock/firefox/templates/firefox/developer/includes/performance.html

Restores (and renames) `id` param in the split macro that was lost in a different merge.
Adds a `base_el` param while I'm in here anyway, which defaults to `section` so doesn't actually change anycurrent uses of this macro but gives us future opportunities.
The id param was only used in two places.
http://localhost:8000/en-US/firefox/91.0a2/whatsnew/all/

Fix split call on dev edition pages [no bug]

---

bedrock/firefox/templates/firefox/pocket.html
bedrock/firefox/templates/firefox/privacy/book.html
bedrock/foundation/templates/foundation/annualreport/2019/index.html

I got cocky and renamed a parameter in a macro without thoroughly searching for every place that macro was called with the old parameter. This, I think, catches them all.
http://localhost:8000/firefox/pocket/
http://localhost:8000/firefox/privacy/book/
http://localhost:8000/foundation/annualreport/2019/

Update id param in Split macro calls [no bug]

---

bedrock/products/templates/products/vpn/includes/pricing-variable.html
l10n/en/products/vpn/shared.ftl

Fixes: https://github.com/mozilla-l10n/www-l10n/issues/225

Turn shared VPN string in multiple contexts into separate strings

---

media/js/base/mozilla-fxa-product-button.js
tests/unit/spec/base/mozilla-fxa-product-button.js

Add `utm_medium` param when making FxA metrics-flow requests.
https://github.com/mozilla/bedrock/issues/10418
1. Load http://localhost:8000/en-US/products/vpn/?utm_campaign=sem-comp-tla-copy-1&utm_medium=cpc&utm_source=google
2. Open dev tools and the network inspector panel.
3. Reload the page, and look for the FxA metrics flow request.
4. Verify the request contains h`ttps://stable.dev.lcip.org/metrics-flow?form_type=button&entrypoint=www.mozilla.org-vpn-product-page&utm_source=google&utm_campaign=sem-comp-tla-copy-1&utm_medium=cpc`

FxA metrics calls should pass through utm_medium (Fixes #10418)

---

docs/conf.py
requirements/docs.txt

Add copy button to code snippets in bedrock docs
Docker: in root folder, run `make docs`
Local: in docs folder, run `make html`
You should see a small clipboard icon when you hover over a code section. If you click, you should be able to copy the code (minus the prompt) to your terminal.

Add sphinx-copybutton for docs

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-fr.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

Fixes /whatsnew page display logic for `WhatsNewFranceView`
#10422
- http://localhost:8000/fr/firefox/94.0a1/whatsnew/france/ should display Nightly /whatsnew page
- http://localhost:8000/fr/firefox/92.0/whatsnew/france/ should displaye VPN page for release channel.

Nightly /whatsnew page show incorrect content to users in France (Fixes #10422)

---

docker-compose.yml

These changes will allow the build to succeed on machines with non-intel processor architectures. This is so far mostly an issue for Mac computers with the M1 chip (ARM64 arch).
See https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

Add platform to images in docker-compose

---

bedrock/mozorg/urls.py
bedrock/mozorg/views.py

In #10429 we want to set the CDN to include the user's country
in the cache key. This creates a URL we can use on dev to test
our CDN settings changes to make sure it's working as expected.
URL: /cdn-geo-test/

Add a page to test CDN geo

---

Dockerfile
bedrock/base/context_processors.py
bedrock/base/geo.py
bedrock/base/templates/cron-health-check.html
bedrock/base/tests/test_context_processors.py
bedrock/base/tests/test_geo.py
bedrock/base/tests/test_views.py
bedrock/base/views.py
bedrock/newsletter/views.py
bedrock/settings/base.py
docs/coding.rst
requirements/prod.txt

Allows for a query param to override the country (e.g. `?geo=de`).
Also removes the old Maxmind stuff since we're unlikely to use that again, and add a GeoTemplateView class to make it easy to switch template based on request country. Adds docs for all of this as well.

Fix #10434: Add country_code to the context for all pages

---

bedrock/base/templatetags/helpers.py

We saw [this error in Sentry](https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/13026476/?query=is%3Aunresolved) when Contentful failed to upload an image. This will cause a warning to be output to the logs, but not break the whole page when an image can't be found by the static assets system.
This is more than just a contentful issue, and we should ensure that outputting a log warning is enough, but I believe we can all agree that a broken image on a page is superior to a broken page.

Output warning on missing image not issue 500 error

---

Makefile
docker-compose.yml
docs/Makefile
docs/coding.rst
docs/contentful.rst
docs/index.rst
docs/install.rst
docs/javascript-libs.rst

Followup from #10437:
- Fix docs formating errors and warnings from Sphinx
- Change the `make docs` command to start an auto-build-reload server using Docker:
* `make docs` does this using Docker
* `make livedocs` does this locally
* `make build-docs` just builds the docs using Docker

More docs improvements

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-fr.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

- Adds a new switch name for France WNP that can be toggle on/off independently of English WNP.
- Adds a prior VPN WNP template as a fallback for France.
#10450

Use a separate switch name for French VPN WNP 92 (Issue #10450)

---

bedrock/contentful/templates/includes/contentful/all.html

Contentful cards had misnamed youtube attribute so the style and functionality for cards with youtube links was missing. This fixes that typo.
https://github.com/mozilla/bedrock/issues/10442
Running locally, ensure you have the latest DB data: `bin/run-db-download.py --force`
~.env file must have Contentful homepage switch on: `SWITCH_CONTENTFUL_HOMEPAGE_EN=on`~ (all switches are on by default as long as you are in dev mode)
The large card (new look for Firefox) should behave like the one in production:https://www.mozilla.org/en-US/
- has play icon by video tag
- has play icon over thumbnail
- opens modal
- has learn more link to new page

Fix youtube_id on contentful cards (Fixes #10442)

---

docs/install.rst

Added a Documentation section under "Installing Bedrock > Make it run".
#10452

Added Documentation section under Make it Run (fixes #10452)

---

bedrock/mozorg/templates/mozorg/about/manifesto.html

Add linkable targets to the principles on the Manifesto page - added an id to each individual principle and move the id #principles to the header for the principles section so it is viewable when navigating from a different page.
#10408 
localhost:8000en-US/about/manifesto/#principles

Add linkable targets to the principles on the Manifesto page

---

bedrock/base/templates/includes/protocol/navigation/nav-cta.html
bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
docs/firefox-accounts.rst
media/css/protocol/components/_navigation-ie.scss
media/css/protocol/components/_navigation.scss
media/js/base/fxa-utm-referral.js
media/js/base/mozilla-cookie-helper.js
tests/pages/base.py
tests/unit/spec/base/fxa-utm-referral.js

- Adds a new VPN product referral link helper.
- Implements helper in navigation CTA button for VPN.
#10409
To test use a Firefox browser with DNT disabled:
1.) Open http://localhost:8000/en-US/
2.) Click on the "Get Mozilla VPN" CTA button in the main navigation.
3.) Once on http://localhost:8000/en-US/products/vpn/#pricing, verify that each subscription link contains:
- `utm_source=www.mozilla.org`
- `utm_medium=referral`
- `utm_campaign=navigation`
Demo link: https://www-demo1.allizom.org/en-US/

Implement attribution flow for VPN subscription referrals (Fixes #10409)

---

bedrock/mozorg/templates/mozorg/contentful-homepage.html

Fixes https://sentry.prod.mozaws.net/operations/bedrock-demos/issues/13118973/
```
Missing staticfiles manifest entry for 'js/daylight-promo-banner.js'
```
#10460

Contentful homepage 500 error missing staticfiles entry (Fixes #10460)

---

bedrock/products/templates/products/vpn/variations/cta-b.html
media/js/products/vpn/cta-change-experiment.js

An extra add-on to the VPN CTA variation ticket. This ticket is to reflect Dan's comment in https://github.com/mozilla/bedrock/pull/10436#issuecomment-918392872. It is to make sure the end user understands that the top CTA for the VPN page reflects that the $4.99/month plan is, in fact, a 12-month plan.
Changes include:
- adding an asterisks to the end of the button text
- including "*For a 12 month plan." to the copy below the button.
- setting up test to not trigger when the URL contains "utm_medium=cpc"
Extension of this PR: #10436
Original issue: #10404 
http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-landing-page-cta-change&entrypoint_variation=b

Update VPN variation to include months

---

l10n/en/firefox/browsers/mobile/focus.ftl
l10n/en/firefox/facebook_container.ftl

Fixes some minor errors in Fluent files; a misspelled brand ID and a missmatched dev URL.
#10474 
#10475

Fluent fixes [fix #10474, #10475]

---

bedrock/base/views.py
media/js/base/fxa-utm-referral.js

We had two 404/redirect links in the code comments. This updates those links to directly reach the information source required.
https://github.com/mozilla/bedrock/issues/10458
The new links should take you to expected pages.

Update comment links for external docs (Fixes #10458)

---

bedrock/firefox/templates/firefox/browsers/mobile/compare.html
bedrock/firefox/templates/firefox/browsers/mobile/ios.html
l10n/en/firefox/browsers/mobile/compare.ftl
l10n/en/firefox/browsers/mobile/ios.ftl
l10n/en/firefox/facebook_container.ftl

Fixes a string on the iOS page, one on the compare page, and deletes an obsolete string (see https://github.com/mozilla-l10n/www-l10n/pull/230#issuecomment-922107952)
#10477 
#10482 
https://github.com/mozilla-l10n/www-l10n/pull/230

More string fixes for mobile pages [fix #10477]

---

bedrock/legal/templates/legal/impressum.html

Address and director updates to hardcoded page only available for `de` locale
https://github.com/mozilla/bedrock/issues/10483
http://localhost:8000/de/about/legal/impressum/

Update Impressum page (Fixes #10483)

---

bedrock/contentful/templates/includes/contentful/all.html

Assume that 4-card layout should always use the `mzp-c-card-extra-small` component class.
https://github.com/mozilla/bedrock/issues/10444

Contentful: Card components font size is too big (Fixes #10444)

---

bedrock/settings/base.py

To accomplish this we simply move the middleware closer to the front
of the list of MIDDLEWARE so that it is not skipped for redirects.

Ensure x-backend-server header appears in all responses

---

bedrock/mozorg/templates/mozorg/contentful-homepage.html
media/css/mozorg/home/home-contentful-en.scss
media/css/mozorg/home/includes/_home-base-en.scss
media/static-bundles.json

Removes duplicate front-end assets from Contentful home page:
- `protocol/css/components/split.scss`
- `protocol/css/templates/card-layout.scss`
- `js/base/mozilla-lazy-load.js`
#10470

Remove duplicate CSS/JS bundles from Contentful home page (Fixes #10470)

---

bedrock/firefox/templates/firefox/browsers/mobile/android.html

Had the same string twice on the page. The dangers of copy-paste. 🤦 
#10510 
http://localhost:8000/firefox/browsers/mobile/android/

Fix string ID on Android page [fix #10510]

---

bedrock/products/templates/products/vpn/includes/templates.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/views.py
bedrock/settings/base.py
l10n/en/products/vpn/shared.ftl
media/js/products/vpn/geo.js
tests/unit/spec/vpn/geo.js

- Add 2 new countries to the VPN country list, behind the switch `SWITCH_VPN_LAUNCH_WAVE_IV`.
- Add new plan IDs for English/Euros.
- Update country list strings for landing page copy.
#10498
When `SWITCH_VPN_LAUNCH_WAVE_IV=on`:
When `SWITCH_VPN_LAUNCH_WAVE_IV=off`

VPN Wave IV country expansion (Fixes #10498)

---

l10n/en/products/vpn/shared.ftl

Added hyphens on the buttons for the 12-month and 6-month plans on the VPN page.
#10441 

Add hyphens to VPN plans buttons

---

bedrock/base/templates/404.html
bedrock/base/templates/500.html
bedrock/base/templates/base-error.html
bedrock/base/views.py
l10n/en/500.ftl
media/css/base/page-not-found.scss

What started as a quick fix for the logo sizing turned into a more significant refactor of the error page templates, just to simplify the markup and CSS a bit and adjust some spacing. Sorry.
#10357 
http://localhost:8000/404/
http://localhost:8000/500/

Fix error page header logos, refactor templates [fix #10357]

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-vpn-en.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-vpn-fr.html
bedrock/products/templates/products/vpn/includes/pricing-variable.html
l10n/en/products/vpn/shared.ftl

Had to create new Fluent strings (added `-v2`) and undo changes from previous PR: https://github.com/mozilla/bedrock/pull/10503. 
Updated the variable throughout some pages and created a fallback.
#10503 
http://localhost:8000/en-US/firefox/92.0/whatsnew/en/
http://localhost:8000/fr/firefox/92.0/whatsnew/france/ (since it's a translated page, the hyphens won't show up for now. I'm not sure how the French do it with hyphens, but code has been updated on this page in case the French do hyphens in this context as well)

Added new VPN fluent variables for hyphens

---

bedrock/mozorg/templates/mozorg/contentful-homepage.html

The newsletter section on the Contentful home page is now inside `mzp-l-content` container and correctly aligned after fixing this issue.
#10521
Here is the screenshot of my changes

Aligned the Newsletter section on Contentful home page

---

bedrock/firefox/templates/firefox/browsers/mobile/focus.html
l10n/en/firefox/browsers/mobile/focus.ftl

Updated some strings in the new [Firefox Focus](https://www.mozilla.org/en-US/firefox/browsers/mobile/focus/) page. Will also update the logo in another ticket down the line after some Protocol updates. 
#10506 
http://localhost:8000/en-US/firefox/browsers/mobile/focus/

Update Firefox Focus page strings

---

.eslintrc.js
media/js/base/mozilla-convert.js
media/js/base/sentry.es6.js
media/js/firefox/whatsnew/whatsnew-88-en.js
media/js/foundation/annual-report-2019.es6.js

Updates bedrock ESLint rules for both ES5 and ES2017+ JS files.
Feel free to make other suggestions? https://eslint.org/docs/rules/
#10527
- `npm run lint`

Update ESLint rules for bedrock (Fixes #10527)

---

.eslintrc.js
media/js/base/sentry.es6.js

This got accidentally removed when I updated to the latest version.
#10527
`npm run lint`

Reinstate ESLint default rule set (#10527)

---

media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

Handles double-encoded attribution data when validating RTAMO referrals.
https://github.com/mozilla/bedrock/issues/10524

Check for double-encoded RTAMO attribution data (Fixes #10524)

---

bedrock/products/templates/products/vpn/landing.html
l10n/en/products/vpn/landing.ftl

Updates supported devices copy for windows in page FAQ.
https://github.com/mozilla/bedrock/issues/10633
http://localhost:8000/en-US/products/vpn/#faq-compatibility

Update VPN landing paging to reflect support for Windows 11 (Fixes #10633)

---

l10n/en/firefox/browsers/mobile/android.ftl
l10n/en/firefox/new/desktop.ftl

Some strings were recently added that ended up not being used in the templates. Removing them so localizers won't need to bother.
https://github.com/mozilla-l10n/www-l10n/pull/243#discussion_r738815199
https://github.com/mozilla/bedrock/pull/10644#discussion_r739763136
http://localhost:8000/firefox/new/
http://localhost:8000/firefox/browsers/mobile/android/

Remove unused strings on download and Android pages

---

media/js/products/vpn/landing.js

This was accidentally removed in https://github.com/mozilla/bedrock/pull/10608/ when `geo.js` was deleted.
https://github.com/mozilla/bedrock/issues/10663
It looks like https://stable.dev.lcip.org/ is currently down right now, which makes it a little hard to test locally. But hopefully this is a simple enough fix that the code can be reviewed with enough confidence to validate later once this merges?

Attach FxA flow params to VPN subscription links (Fixes #10663)

---

bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/templates/mozorg/home/includes/mr2-promo-eu.html
bedrock/mozorg/templates/mozorg/home/includes/mr2-promo.html
media/css/mozorg/home/home-mr2-promo.scss

While looking at the Contentful preview I realized some of my styling for the MR2 promo was applying some padding to other instances of the Split component. This updates the promo styles to be more specific to just the promo so they won't mess with any other Splits on the same page.
http://localhost:8000/fr/

Make MR2 home promo styles more specific [#10620]

---

bedrock/contentful/templates/includes/contentful/cta.html

We need a Relay option in bedrock to match Contentful CTA buttons. ~We also want to change the Download Firefox CTA link to: /firefox/browsers~
[UPDATE](https://github.com/mozilla/bedrock/issues/10662#issuecomment-957970219): we want a new option to "Explore Firefox" which leads to /firefox/browers, "Download Firefox" action will not change
UPDATE 2 (see comments below): We are removing the analytics for location as that value is waiting on a Contentful content model update
https://github.com/mozilla/bedrock/issues/10661
https://github.com/mozilla/bedrock/issues/10662
~set `.env` to use:
`CONTENTFUL_ENVIRONMENT=maureen-2021-11-02`~
All changes were made in Master env, so you do not need to specify a CONTENTFUL_ENVIRONMENT to test (as long as you have your CONTENTFUL_KEY) …

Fix Contentful CTAs (fixes #10661, #10662)

---

bedrock/mozorg/templates/mozorg/contentful-homepage.html

While in the neighbourhood I spotted we had two tags closing `<main>` on the contentful-powered homepage
Deleting the first of the two
No ticket
* Pull this branch and visit the contentful-powered `en` homepage - confirm visually OK
* View source and paste it into validator.w3.org and confirm no warning of "Stray end tag `main`" (which you can see on https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2F)

Remove duplicated </main> tag

---

media/css/contentful/firefox/c-logo.scss
media/css/contentful/general.scss
media/css/contentful/mozilla/c-logo.scss
media/css/mozorg/home/home-contentful-en.scss

Add relay product class to Contentful logo styles. `firefox/c-logo` is already imported into Contentful pages, so we do not need to individually import brand wordmarks.
**Note**: we should probably discuss why this logo partial is always imported: https://github.com/mozilla/bedrock/blob/master/bedrock/contentful/templates/includes/contentful/css.html#L14
No issue, follow up for https://github.com/mozilla/bedrock/issues/10661
You'll need to update npm dependencies to access the latest Protocol version (with Relay assets).
Check http://localhost:8000/en-US/contentful-preview/01i30zNjYwlPkmcAoc1hy0/ has Relay logo in the Hero component.

Add Relay wordmark to Contentful home CSS

---

bedrock/products/templates/products/vpn/includes/macros.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
bedrock/products/views.py
docs/firefox-accounts.rst
l10n/en/products/vpn/landing.ftl
media/css/products/vpn/landing.scss

- Update "Already a subscriber?" link in VPN page nav to point to https://vpn.mozilla.org/vpn/download/
- Remove superfluous "vpn-sub-not-found" notification.
#10535

Update VPN Already a subscriber? link url (Fixes #10535)

---

bedrock/newsletter/templates/newsletter/forms/simple_radio_select.html
bedrock/newsletter/templates/newsletter/forms/tabular_radio_select.html

This changeset stops the newsletter preferences form at /newsletter/existing/<hash>/ from showing a reference to MPL2.0, which was leaking from a template partial being used to render the form.
Two templates have been updated, one of which was clearly leaking. The other was updated for consistency and belt-and-braces safety
The key issue was that the template had a Jinja2-style comment, which was not being skipped because the standard Django form renderer was being used.
Switching to a jinja2 renderer did not work, so instead the fix has been to swap the comment style to be Django Template Language style AND also add a magic string so that the pre-commit hook does not think that the templates in question lack the licence text.
BEFORE
AFTER
Fixes #10690  
* Go to …

10690: Fix leak of MPL comment into newsletter management form

---

media/css/externalpages/pocket/components/_about.scss
media/css/externalpages/pocket/components/_nav.scss

Had an issue where the text elements on the about page were not able to be highlighted, which presented an a11y issue [Related slack thread](https://mozilla.slack.com/archives/C02F3V74CJV/p1635793459023300) and [w3 doc](https://www.w3.org/dpub/IG/wiki/Accessibility_When_Users_Select_and_Highlight_Text)
Also converted remaining `em` units to `px` in the styles for the global navigation
#10211
external/pocket/about

Fix text a11y on /about and convert em to px

---

bedrock/firefox/templates/firefox/home/index-master.html
l10n/en/firefox/home.ftl

Adding Firefox Relay logo to the products page:
- Under 'Family of Products' section
- Bottom products section 
#10698 

Add Relay logo to Products page

---

bedrock/settings/base.py
docs/firefox-accounts.rst
media/js/base/fxa-utm-referral.js
media/js/base/mozilla-fxa-link.js
media/js/base/mozilla-fxa-product-button.js

- Update FxA links to point to https://accounts.stage.mozaws.net/ when `Dev=True`.
- Remove references to deprecated https://stable.dev.lcip.org/ and https://latest.dev.lcip.org/ domains.
Note: this does not yet fix the CORS error mentioned in the issue. We'll need some help from the FxA team with this part, but that doesn't need to hold up changing the links.
#10670
1. Using a **non-Firefox browser**, open http://localhost:8000/en-US/firefox/ (with `Dev=True` in your `.env` file).
2. Scroll to the bottom of the page and click the "Join Firefox" button.
3. Verify that the link navigates to https://accounts.stage.mozaws.net/

Update links to point to FxA staging when Dev=True (#10670)

---

bedrock/firefox/templates/firefox/welcome/page10.html
bedrock/firefox/urls.py
l10n/configs/pontoon.toml
l10n/en/firefox/welcome/page10.ftl

Exposes string for welcome/10 in Pontoon for locales `es-ES`, `it`, `nl`.
#10708
http://localhost:8000/en-US/firefox/welcome/10/

Enable firefox/welcome/10 for L10n (Fixes #10708)

---

bedrock/firefox/templates/firefox/privacy/passwords.html
l10n/en/firefox/privacy/passwords.ftl

This PR updates the twofactorauth.org references to [https://2fa.directory](https://2fa.directory) in firefox/privacy/safe-passwords/
#10137
Docker/ local machine

Update 2FA references

---

media/js/firefox/features/picture-in-picture.js
media/js/firefox/features/tips/tips-youtube.js
media/js/mozorg/home/youtube.js

There's not really much we can do if people block YouTube, or their script / API fails. This PR will supress frequent errors like https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/10909431/
In some cases I've tried to redirect people to youtube.com, where there's a chance they might have more luck.
#10202
- http://localhost:8000/en-US/firefox/features/tips/
- http://localhost:8000/en-US/firefox/features/picture-in-picture/
- http://localhost:8000/en-US/

Supress JS errors thrown when YouTube is blocked (Fixes #10202)

---

bedrock/products/templates/products/vpn/includes/macros.html
bedrock/products/templates/products/vpn/includes/pricing-variable.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/templates/products/vpn/more/base-article.html
bedrock/products/templates/products/vpn/platforms/android.html
bedrock/products/templates/products/vpn/platforms/desktop.html
bedrock/products/templates/products/vpn/platforms/ios.html
bedrock/products/templates/products/vpn/platforms/linux.html
bedrock/products/templates/products/vpn/platforms/mac.html
bedrock/products/templates/products/vpn/platforms/mobile.html
bedrock/products/templates/products/vpn/platforms/windows.html
l10n/en/products/vpn/landing.ftl
media/css/products/vpn/common.scss
media/css/products/vpn/landing.scss

- Updates VPN 30-day money back guarantee copy, across all VPN web pages that mention it.
- Updates FAQ copy to highlight that this is only available through subscriptions on the website.
#10696
- http://localhost:8000/en-US/products/vpn/more/what-is-a-vpn/
- http://localhost:8000/en-US/products/vpn/more/what-is-an-ip-address/
- http://localhost:8000/en-US/products/vpn/more/when-to-use-a-vpn/
- http://localhost:8000/en-US/products/vpn/more/vpn-or-proxy/
- http://localhost:8000/en-US/products/vpn/mobile/
- http://localhost:8000/en-US/products/vpn/desktop/
- http://localhost:8000/en-US/products/vpn/desktop/mac/
- http://localhost:8000/en-US/products/vpn/desktop/windows/
- http://localhost:8000/en-US/products/vpn/desktop/linux/
- …

Update VPN guarantee copy (Fixes #10696)

---

l10n/en/firefox/new/desktop.ftl

Small comment to communicate which strings will only be used in a variant view. In this case it's for https://www-dev.allizom.org/en-US/firefox/new/?v=fx94

Added comment to string used on /new variant

---

bedrock/firefox/templates/firefox/new/desktop/download.html
bedrock/firefox/urls.py
bedrock/firefox/views.py
l10n/en/firefox/new/desktop.ftl

- Fixes bug where English copy is shown on non-English pages.
#10724

Check translation status when showing MR2 copy on /new (Fixes #10724|

---

bedrock/base/templates/base-protocol.html
bedrock/settings/base.py

In some situations/environments we want to separate out backend and frontend sentry alerts, to make spotting relevant issues easier.
This changeset adds support for a frontend-specific DSN, which will default to be the same DSN as the existing one, which wil remain in use for the backend.
We can add the FE DSN config to specific environments only (eg Production) and leave all other envs using the same DSN for both FE and BE.
**This changeset will also need a config/secrets change, but it can be released beforehand as it's non-breaking** That change is PRed here https://github.com/mozmeao/www-config/pull/409
#10593  
1. Check out the branch
2. Load http://localhost:8080 and view source. Search for `data-sentry-dsn` and you will have no matches
3. In your `.env` set a `SENTRY_DSN` value …

10593: Add support for an optional frontend-specific Sentry DSN

---

bedrock/contentful/api.py
bedrock/firefox/templates/firefox/browsers/mobile/android.html
bedrock/firefox/templates/firefox/browsers/mobile/focus.html
bedrock/firefox/templates/firefox/browsers/mobile/ios.html
bedrock/firefox/templates/firefox/features/index.html
bedrock/firefox/templates/firefox/mobile/index.html
bedrock/firefox/templates/firefox/privacy/book.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
package-lock.json
package.json

Updates to the latest Protocol, which includes the new breadcrumb component and renames previous "alt" theme variables/classes to "secondary"
Run `npm install` or `make build` locally to get latest dependencies.
Make sure I didn't miss any instances of the old names.
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/406631275

Update to Protocol 16.0.0

---

bedrock/firefox/templates/firefox/privacy/passwords.html

I can't see any reason why this page needs this bundle.
https://github.com/mozilla/bedrock/issues/10717
http://localhost:8000/en-US/firefox/privacy/safe-passwords/

Remove unrelated JS bundle from safe-passwords page (Fixes #10717)

---

media/js/base/mozilla-client.js
tests/unit/karma.conf.js
tests/unit/spec/base/mozilla-client.js

Fixes JS error when Firefox user agents do not contain a version number (e.g. modified through an extension)
#10582
Hopefully the additional unit test should provide enough coverage / confidence.

Fix error thrown by isFirefoxUpToDate when no version number is found (Fixes #10582)

---

media/js/base/fxa-utm-referral.js
tests/unit/karma.conf.js
tests/unit/spec/base/fxa-utm-referral.js

Removes DNT check from VPN same-site link attribution check (legal team have given this the OK).
#10701
1. Using Firefox (with DNT enabled), open http://localhost:8000/en-US/
2. Click the "Get Mozilla VPN" link in the top right navigation.
3. Verify that the subscription links in the pricing section conatin `utm_campaign=navigation`

Remove DNT check from VPN link referral attribution (Fixes #10701)

---

bedrock/privacy/templates/privacy/index.html
l10n/en/privacy/index.ftl

removed outdated link from Privacy page Index portion and added a new link.
#10722

fixed outdated link with a new link in privacy

---

bedrock/base/templates/includes/protocol/footer/footer.html
bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
bedrock/mozorg/templates/mozorg/contact/contact-landing.html
bedrock/mozorg/templates/mozorg/contribute.html
bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/tests/test_helper_misc.py
bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
bedrock/settings/base.py

The German / French Twitter social accounts have been re-branded / renamed using Mozilla instead of Firefox. This PR updates the footer links, as well as a few other places.
https://bugzilla.mozilla.org/show_bug.cgi?id=1740912
Scroll to the footer on the following pages:

Update Twitter social links for DE/FR (fix bug 1740912)

---

bedrock/contentful/api.py

Removes magic paragraph formatting.
#10768

Remove unnecessary class being added to paragraphs (Fixes #10768)

---

bedrock/contentful/constants.py
bedrock/contentful/management/commands/update_contentful.py
bedrock/contentful/tests/test_commands.py

This changeset adds support for mirroring the removal of a page in Contentful in Bedrock's sqlite database.
The main behavioural changes are:
* The "archive", "unpublish" and "delete" events now trigger an API poll, whereas before they did not
* The "create" event of a page no longer counts as a 'go signal' for an API poll (and probably shouldn't have been in the first instance)
* We continue to ask the API for all the pages it knows of (for the relevant environment + API key combination), so we get a list of page IDs which we attempt to sync. After that attempt, we then query sqlite and look for any ContentfulEntry records we hold that were NOT in the list of IDs we just tried to sync -- and we delete those entries. This approach means that even if a sync for a particular page fails, we …

10711: Update Contentful sync to delete absent pages from sqlite

---

media/js/firefox/privacy/products.js

This PR removes unused PictoCard code from Firefox Privacy Products JS code:
Fixes: #10731 
All tests passed.

Remove old PictoCard code from Firefox Privacy Products JS

---

bedrock/base/templates/cron-health-check.html

With the removal of the country-code.json endpoint in #10719 we need
another easy way to see from which country bedrock thinks the request is
coming. It's available in the html tag on every page, but this makes it
even easier and more human readable.

Add request country code to healthz-cron page

---

bedrock/products/tests/test_views.py
bedrock/products/urls.py
bedrock/products/views.py

While we're not yet using/revealing any categories in the VRC, we have code that provides a list of them for filtering. This code was not avoiding duplicates, so this changeset remedies that, via TDD.
There were different ways to approach this, but the separate tracking set of 'seen' categories seemed the simplest.
This changeset also renames a view to match the template it renders (`detail -> article`)
Resolves #10744 
Not straightfoward to test at the mo, because the categories are not revealed in the template, but reviewing the tests should be enough

Avoid duplicates when generating list of VRC categories based on available data

---

lib/l10n_utils/dotlang.py
lib/l10n_utils/templatetags/helpers.py

This adds back the call to `Markup` to flag the text string as safe to be rendered as HTML.
Fixes #10780 
Ensure that `/about/forums/` links in the text work as expected.

Fix #10780: Add back `Markup` to `gettext` no-op

---

bedrock/products/templates/products/vpn/resource-center/landing.html

Fixes missing spacing around "Start protecting your identity today" section.
https://github.com/mozilla/bedrock/issues/10777
http://localhost:8000/en-US/products/vpn/resource-center/

Fix spacing issue on VRC landing page (Fixes #10777)

---

bedrock/contentful/api.py
bedrock/contentful/tests/test_contentful_api.py

Backfilling tests for Contentful content processing - part 1 of n
These have all been written purely based on the code present, not the incoming data. As such, some will require expansion, especially the tests for _only_child, I feel.
#10639 
Checking that CodeCov shows an uptick in coverage and that all the free-floating helper funcs in bedrock.contentful.api have 100% coverage

10639: Backfilling tests for Contentful content processing - part 1 of n

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

This will help when we need to change these redirects to point to
/careers/ in the future.

Change redirects to careers.m.o to temporary

---

bedrock/exp/views.py

The /exp home page wasn't referencing the `mozorg/home-mr2-promo` Fluent file and hence was display string IDs instead of the correct text.
n/a
http://localhost:8000/en-US/exp/
The button in the top promo should read "Get the new Firefox" and not show the string ID.

Update Fluent file for exp home page [no bug]

---

bedrock/contentful/api.py

Use image description fields for `<img>` alt text instead of title fields.
#10787
Note: if you already have these pages in the DB locally, you may need to run `./manage.py update_contentful --force` to see the changes.
http://localhost:8000/en-US/products/vpn/resource-center/what-is-an-ip-address/

Use image description for alt text in Contentful (Fixes #10787)

---

media/css/products/vpn/resource-center.scss

#10769
http://localhost:8000/en-US/contentful-preview/1dQAhsz5Xnr6IrGwvhnFZp/

Add default bottom margin to VRC images served in Contewntful articles (Fixes #10769)

---

bedrock/contentful/constants.py
bedrock/sitemaps/tests/test_utils.py
bedrock/sitemaps/utils.py

This changeset adds support for showing the VPN-specific resource center pages authored in Contentful in the sitemap, plus the index/landing page for the VPN Resource Center iff there are any articles available in the DB
TBC how one sees the results of the sitemap - that hasn't been manually checked yet
Resolves #10778 (assuming it needs no extra work/wiring)
```
make shell
./manage.py update_contentful --force  # to ensure you have VRC pages in your local DB
./manage.py update_sitemaps  # to regen the sitemap-powering JSON file
```
then inspect `root_files/sitemaps.json` to confirm the VRC pages are in there - they should be towards the very end of the file

10778: Add support for VRC pages to sitemap

---

.circleci/config.yml
Dockerfile
package-lock.json

Updates bedrock to Node.js v16 (LTS), which comes bundled with NPM v8.
#10803
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/413730939

Update bedrock to NodeJS to v16 (Fixes #10803)

---

bedrock/products/templates/products/vpn/invite.html
l10n/en/products/vpn/landing.ftl

Updates platform interest string to include Windows 11.
#10819
http://localhost:8000/en-US/products/vpn/invite/

Update Windows platform string on VPN waitlist page (Fixes #10819)

---

docs/coding.rst

- Adds a section to the start of the "developing on bedrock" for how to add new dependencies.
- Fixed up some minor title-level warnings when building the docs.
#10831
Run `make livedocs` and then open:
http://127.0.0.1:8100/coding.html

Add docs for how to install new Python dependencies (Fixes #10831)

---

bedrock/base/templates/includes/banners/fundraiser.html

I missed these params in https://github.com/mozilla/bedrock/issues/10700 so bumping the year here.
#10700

Update utm_campaign for 2021 fundraising banner (Issue #10700)

---

Dockerfile
bedrock/settings/base.py
bin/run-db-update.sh

This changeset updates the bin/run-db-update.sh script to be more resilient to errors and ping a new Dead Man's Snitch IFF we have successful completion of all update tasks.
Specifically:
* Changed script mode to allow continue execution even if one of the management 
commands has a non-zero exit value
* Sets a sentinel to true if we encounter a problem during one of those 
management commands
* If the sentinel is false AND we have a specific, new, DMS url 
configured, ping it to confirm the update script went without problem. 
NOT pinging it will trigger an alert within MEAO circles once the snitch is active
Note that the new DMS snitch URL will come from the environment, but is 
not loaded in as a Django setting. Three new env-specific ones have been set up via …

Refactor DB update script to be more resilient and also ping a new DMS

---

bedrock/base/management/commands/update_www_config.py
bedrock/contentcards/management/commands/update_content_cards.py
bedrock/contentful/management/commands/update_contentful.py
bedrock/externalfiles/management/commands/update_externalfiles.py
bedrock/legal_docs/management/commands/update_legal_docs.py
bedrock/mozorg/management/commands/update_product_details_files.py
bedrock/newsletter/management/commands/update_newsletter_data.py
bedrock/pocketfeed/management/commands/update_pocketfeed.py
bedrock/releasenotes/management/commands/update_release_notes.py
bedrock/security/management/commands/update_security_advisories.py
bedrock/sitemaps/management/commands/update_sitemaps_data.py
bedrock/utils/management/cron_command.py
bedrock/utils/management/decorators.py
bedrock/utils/tests/test_decorators.py
bedrock/wordpress/management/commands/update_wordpress.py

This is part of [a broader epic](https://github.com/mozilla/bedrock/issues/10627) about making the DB update script a bit more resilient and its results more visible
This changeset adds a way for us to have management commmands raise exceptions upon failure, but still capture that info in Sentry, in a fairly unobstrusive way, via a class decorator
Resolves #10813 
* Add the SENTRY_DSN from Dev to your .env and restart your local stack
* In one of the relevant management commands (eg `update_contentful`) raise an Exception high in the _handle() command
* Confirm the exception is shown in your console AND also gets sent to sentry - eg https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/15307834/?referrer=alert_email

Make update commands alert to sentry on exceptions

---

media/css/firefox/welcome11.scss

Updated footer link styles for dark mode.
#10836 
https://bugzilla.mozilla.org/show_bug.cgi?id=1743408
http://localhost:8000/firefox/welcome/11/

Fix welcome page footer links in dark mode [fix #10836]

---

l10n/configs/vendor.toml

I don't think there's anything actually using this file, but that's what I use to parse strings in Transvision (which, at the moment, it's missing all these locales).
The file doesn't make a lot of sense in its current form, as it lists locales but doesn't apply to any resource.
CC @peiying2

Add paths to vendor.toml

---

media/css/base/banners/pocket.scss

Noticed on https://www-dev.allizom.org/en-CA/
If you visit the CTA button link and return, the text is white and cannot be seen. (or use dev tools to set visited state)
This PR adds `a:visited` to the pocket banner link text styling
Open dev tools and target the Pocket banner CTA. Set state to visited. You should still see link text
.

Fix pocket banner link:visited style [no bug]

---

bedrock/base/templates/includes/banners/pocket.html

Fix en utm campaign param to 'best-of-us'
https://github.com/mozilla/bedrock/pull/10846#discussion_r760454176
CTA should have appropriate utm campaign value

Fix pocket utm campaign [no bug]

---

.stylelintrc
bedrock/externalpages/urls.py
media/css/externalpages/pocket/components/_about.scss
media/css/externalpages/pocket/components/_add.scss
media/css/externalpages/pocket/components/_footer.scss
media/css/externalpages/pocket/components/_nav.scss
media/css/externalpages/pocket/components/_platform-footer.scss
media/css/externalpages/pocket/components/_platform-nav.scss
media/css/externalpages/pocket/components/_platforms.scss
media/css/externalpages/pocket/style.scss
media/css/externalpages/pocket/utils/_fonts.scss
media/css/externalpages/pocket/utils/_tokens.scss
media/css/externalpages/pocket/utils/_variables.scss

There's still more work to do here until this matches conventions we use in the rest of bedrock (e.g. removing BEM selector syntax), but this is the minimal set of changes needed to start linting these files.
#10841
- http://localhost:8000/en-US/external/pocket/about/
- http://localhost:8000/en-US/external/pocket/add/
- http://localhost:8000/en-US/external/pocket/android/
- http://localhost:8000/en-US/external/pocket/ios/
- http://localhost:8000/en-US/external/pocket/chrome/
- http://localhost:8000/en-US/external/pocket/safari/
- http://localhost:8000/en-US/external/pocket/opera/
- http://localhost:8000/en-US/external/pocket/edge/

Lint external Pocket .scss files (Fixes #10841)

---

bedrock/firefox/templates/firefox/new/basic/thanks_direct.html
bedrock/firefox/templates/firefox/new/desktop/thanks_direct.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
media/js/firefox/new/common/thanks-direct.js
media/static-bundles.json

Adds special `?s=direct` URL parameter to `/firefox/download/thanks/` for cross-site attribution of direct downloads.
#10520
Note: needs testing on a Windows device / VM:
1. Open a new private tab and load https://www-demo1.allizom.org/firefox/download/thanks/?s=direct
2. Wait for the download to begin.
3. Verify that the download was initiated with both `attribution_code` and `attribution_sig` query parameters in the URL (you can hover over the "Try downloading again" link to easily copy/view the URL).
Example: https://download.mozilla.org/?product=firefox-stub&os=win&lang=en-US&attribution_code=c291cmNlPShub3Qgc2V0KSZtZWRpdW09KGRpcmVjdCkmY2FtcGFpZ249KG5vdCBzZXQpJmNvbnRlbnQ9KG5vdCBzZXQpJmV4cGVyaW1lbnQ9KG5vdCBzZXQpJnZhcmlhdGlvbj0obm90IHNldCkmdWE9Y2hyb21lJnZpc2l0X2lkPTEwNzg5NjA0MzAuMTYzNzY2 …

Create cross-site Firefox download attribution page (Fixes #10520)

---

bedrock/base/templates/includes/banners/pocket.html

We want to include the language in Pocket Collections URL so users end up on the correctly translated page
https://github.com/mozilla/bedrock/issues/10853
Click Pocket Banner Best Of button
Should go to Pocket's DE collections page
https://getpocket.com/de/collections?utm_source=mozilla.org&utm_campaign=best-of-de
http://localhost:8000/en
Click Pocket Banner Best Of button
Should go to Pocket's EN collections page
https://getpocket.com/collections?utm_source=mozilla.org&utm_campaign=best-of-us

Fix pocket collections url (fixes #10853)

---

docs/download-buttons.rst

Now that #10520 is in prod here's some docs for how sites should use it.
#10520
- Run `make livedocs` and check http://127.0.0.1:8100/download-buttons.html

Add docs for external site Firefox download links (#10520)

---

bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
media/js/base/mozilla-fxa-product-button.js
tests/unit/spec/base/mozilla-fxa-product-button.js

Adds `service=guardian-vpn` param to VPN auth URLs to make querying easier for data science teams.
#10811

Add service=guardian-vpn param to VPN metrics-flow and FxA links (Fixes #10811)

---

media/css/contentful/mozilla/c-hero.scss

Center wordmarks for Contentful homepage hero components. A stop-gap fix until we resolve the underlying Protocol issue: https://github.com/mozilla/protocol/issues/718
The Hero component has [mobile centering for logos only](https://github.com/mozilla/protocol/blob/main/src/assets/sass/protocol/components/_hero.scss#L22). We added the wordmark for Contentful Hero but since the Protocol component is deprecated, we won't be updating Hero in Protocol. It's a Mozilla only fix because we should not be using the Contentful Hero component on new pages.
https://github.com/mozilla/bedrock/issues/10666
At mobile view size, Hero wordmarks in the Featured Mozilla Products section should be centered.
Above that view size, the wordmarks should be left-aligned or …

Center wordmarks on mobile (fixes #10666)

---

bedrock/contentful/api.py
bedrock/contentful/tests/test_contentful_api.py

Update ContentfulPage.get_info_data() and its helpers, while broadening test coverage
To make things easier to test, I refactored a lot of get_info_data() into smaller methods, which also made things a bit easier to read and will be easier to update in the future
#10639
* test should pass
* do a manual local sync

10639: improve Contentful coverage - part 3

---

l10n/configs/pontoon.toml

Adds page13.ftl to pontoon.toml for es-ES, it, and nl. Other locales are covered by Smartling.
https://github.com/mozilla-l10n/www-l10n/issues/263

Add welcome/page13.ftl to Pontoon config [#10801]

---

Dockerfile

Before, bpython would complain it couldn't write to /home/webdev/.pythonhist because it and the parent dir did not exist. 
Adding both with the appropriate permissions seems the smallest change to make the history work, and reduce the noise in the shell, but if we don't like this, I can dig into adding a config file in bedrock and mounting that in the container
No ticket
Pull, `make build`, then `make shell`, then `./manage.py shell` and write some Python, confirming that the up-arrow history now works and doesn't pepper the terminal with `Error occurred while writing to file /home/webdev/.pythonhist (No such file or directory)`

Allow bpython (used by ./manage.py) to write its history file

---

l10n/configs/vendor.toml

I was naive when copying from `pontoon.toml`, and didn't realize this would analyze only the files in the root, and ignore subfolders.

vendor.toml: parse also subfolders

---

bedrock/products/templates/products/vpn/platforms/linux.html
bedrock/products/templates/products/vpn/platforms/mac.html

A few strings had undefined variables.
#10883 
Check body copy under "Protect 5 devices with one subscription" on both the Mac and Linux pages. These were the only ones I could find.
http://localhost:8000/products/vpn/desktop/mac/
http://localhost:8000/products/vpn/desktop/linux/

Fix VPN devices variables [fix #10883]

---

bedrock/newsletter/templates/newsletter/recovery.html

Fixed hyperlink rendering in error message of recovery page. Closes #10691
Fixed the hyperlink rendering error in the error message produced on submitting an email id that does not occur in the newsletter system.
https://github.com/mozilla/bedrock/issues/10691
Enter an email id that does not occur in the newsletter system.  [localhost:8080/en-US/newsletter/recovery](http://localhost:8080/en-US/newsletter/recovery/)

Fixed hyperlink rendering in error message of recovery page. Closes #10691

---

bedrock/foundation/templates/foundation/annualreport/2020/index.html

There was a typo on the leadership cards -- fixed `Steeting Committee` to be `Steering Committee`
http://localhost:8000/en-US/foundation/annualreport/2020/

Fix SOM2020 typo

---

Dockerfile

This changeset enables us to run `manage.py dbshell` in the app container for the devapp (but not production)
No ticket
```
you@host:$ make shell
webdev@df9f9ff07135:/app$ ./manage.py dbshell
sqlite> select count(*) from releasenotes_productrelease;
```

Add sqlite3 to devapp image, so we can run manage.py dbshell in local development

---

bedrock/base/templates/includes/banners/vpn-promo.html
bedrock/base/templates/includes/protocol/navigation/nav-cta.html
bedrock/firefox/templates/firefox/home/index-master.html
bedrock/mozorg/templates/mozorg/home/home-contentful.html
bedrock/mozorg/templates/mozorg/home/home-de.html
bedrock/mozorg/templates/mozorg/home/home-fr.html
bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
media/css/base/banners/vpn-promo.scss
media/js/base/banners/vpn-promo-banner-init.js
media/static-bundles.json

Adds a top-of-page banner to the home page and main /firefox page, in English, French, and German.
#11026 
In your .env file set:
```
SWITCH_FUNDRAISING_BANNER_EOY2021=False
SWITCH_POCKET_BANNER=False
SWITCH_VPN_PROMO_BANNER=True
```
http://localhost:8000/en-US/ (also en-GB and en-CA)
http://localhost:8000/en-US/firefox/ (also en-GB and en-CA)
http://localhost:8000/de/firefox/
http://localhost:8000/fr/
http://localhost:8000/fr/firefox/

Add VPN promo banner [fix #11026]

---

media/css/externalpages/pocket/includes/_nav.scss

For some reason `active` links were being set as `display: none`. I'm guessing the original intent was to remove some pseudo class styling?
#11030
http://localhost:8000/en-US/external/pocket/about/

Fix navigation links on /pocket/about/ (Fixes #11030)

---

media/css/firefox/new/desktop/download.scss

Fixes button color contrast issue on /firefox/new/ page.
https://github.com/mozilla/bedrock/issues/9866
1. Test in a **Firefox** browser that's **not** signed into a Firefox Account.
2. Open http://localhost:8000/en-US/firefox/new/
3. Click "Download Firefox" and wait for the modal to open.

Fix hover state on join modal for firefox/new (Fixes #9866)

---

bedrock/firefox/urls.py
bedrock/mozorg/urls.py

Started seeing functional test failures after https://github.com/mozilla/bedrock/pull/11047
https://gitlab.com/mozmeao/www-config/-/pipelines/431529045
Platform pages 404 with a trailing slash before the ?automation=true param:
http://localhost:8000/en-US/firefox/windows/?automation=true is 404
http://localhost:8000/en-US/firefox/windows?automation=true is fine 
Urls using the new `path` helper should have trailing slashes 
no bug
Functional tests should pass and
http://localhost:8000/en-US/firefox/windows/?automation=true should be working
Successful test run:
https://gitlab.com/mozmeao/www-config/-/pipelines/431817259

Fix trailing slash for platform urls [no bug]

---

media/js/base/fxa-utm-referral.js
tests/unit/spec/base/fxa-utm-referral.js

Prevents malformed utm parameter values throwing an error when parsing attribution data.
https://github.com/mozilla/bedrock/issues/10897
Test URL: http://localhost:8000/en-US/products/vpn/?utm_source=test&utm_campaign=test&utm_contant=uns_footer%

Fix JS error parsing malformed utm values (Fixes #10897)

---

bedrock/externalpages/templates/externalpages/pocket/base.html
bedrock/externalpages/templates/externalpages/pocket/includes/footer.html
bedrock/externalpages/templates/externalpages/pocket/privacy.html
bedrock/externalpages/urls.py
bedrock/settings/base.py
media/css/externalpages/pocket/components/privacy.scss
media/css/externalpages/pocket/includes/_footer.scss
media/static-bundles.json

Coded the /privacy page and also added the scripts for the cookie helper that getpocket.com uses
#10762
http://localhost:8000/external/pocket/privacy

Code /privacy and add cookies scripts (Fixes #10762)

---

bedrock/settings/base.py

Nano-sized papercut, tidied up while in the neighbourhood. #DeadCodeRemoval
Resolves #10872
* All tests pass

Remove session-related settings and remind developers that Bedrock is stateless

---

bedrock/newsletter/tests/test_views.py
bedrock/newsletter/views.py

Apply ``BASKET_API_KEY`` to the basket update ``kwargs`` after checking if any of the settings from the newsletter preference page changed. This prevents detecting that the page always has changes, and avoids sending a needless update to Basket when unsubscribing from all newsletters.
https://github.com/mozilla/bedrock/issues/10205
Unit testing only. I added ``BASKET_API_KEY`` to all ``TestExistingNewsletterView``, which required some test changes and caused ``test_remove_all`` to fail, replicating the issue from basket-dev.  The second commit changes the view logic, and the test now passes again.

Do not send basket update when nothing changed on newsletter preference page

---

bedrock/contentful/management/commands/update_contentful.py
bedrock/contentful/tests/test_commands.py
bedrock/settings/base.py

This doesn't affect prod behaviour, but we have had to swap from checking 'is this dev' to 'is this NOT prod', 
rather than introduce a new settings.STAGING variable
~NB BLOCKED by PR 280 in the infra repo, which needs to be merged first to avoid errors on staging~
Resolves #10886
Tricky to test - let's DM about it

10886: Update Contentful sync to allow non-Prod environments to treat saved/draft content as worth syncing.

---

requirements/base.txt

See release notes https://docs.djangoproject.com/en/dev/releases/2.2.26/
We do use `dictsort`, which is one of the three things amended in this release, so the testing steps below cover the two places where we do, to confirm there's no regression.
Integration tests have been run and [passed](https://gitlab.com/mozmeao/www-config/-/pipelines/441040365)
No ticket
* Set `DEV=False` in your local build.  
* `make run` 
* Visit the homepage and view source. 
* View the list of canonical links in the head. Compare these to the ones in live site. They match.
* View the list of locales in the language picker. Compare these to the ones in live site. They match.

Bump Django to 2.2.26

---

docs/coding.rst

In order to make working with Bedrock easier for contributors and team members alike, we decided to add more information in the Bedrock documentation about how to work with Protocol and custom macros that the team created. This provides more clarity on how we make coding in Bedrock work really great in a modular fashion.
https://github.com/mozilla/bedrock/issues/10647
checkout into this branch and run `make livedocs` on a local install, or `make docs` if you're using docker.
http://127.0.0.1:8100/coding.html#working-with-protocol

Add Protocol and Macro paths to Bedrock documentation

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-en-qr.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-en-s2d.html

We've generated custom Adjust links for the app store badges instead of using the standard global link. This updates WNP96 to use the new URLs.
#11070 
http://localhost:8000/en-US/firefox/96.0/whatsnew/?v=1
http://localhost:8000/en-US/firefox/96.0/whatsnew/?v=2
[Google Doc with the custom links](https://docs.google.com/document/d/1rw_bsL_S7CYHXStoRxivxMzWZ35YQzve0PvGSHGfzMA/edit). The bit to look for in each URL is the 7-digit code right after app.adjust.com.
v1, Android = `b4dabjm`
v1, Apple = `fokjl4u`
v2, Android = `8abpl22`
v2, Apple = `5jpoe35`

Update Adjust links on EN WNP96 [#11070]

---

bedrock/firefox/templates/firefox/whatsnew/includes/fx96-en/s2d.html

Minor tweak to the device widget to save space. Removed the extra line of copy and used it for the form label.
#11070 
http://localhost:8000/en-US/firefox/96.0/whatsnew/

Update EN WNP96 send-to-device form [#11070]

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2021.html

Minor update to H1 2021 transparency report due to a data error.
#11095
http://localhost:8000/en-US/about/policy/transparency/jan-jun-2021/

Transparency report amendment h1 2021 (Fixes #11095)

---

media/css/protocol/protocol-mozilla.scss

Changed Error-message colour on newsletter error as per accessibility standards.
#11016

Fixed Error-message colour on newsletter error

---

bin/cron.py

This was suggested by @duallain following a minor problem where a scheduled sync
task stalled/failed during an infrastructure outage and just hung. Adding a
timeout should avoid this happening again.
~Nine minutes is a gut-feel for a reasonable time, allowing for long-running syncs, but maybe we can go with less - 4 mins?~
Resolves #11038
Tricky to test - suggestions welcome!

Add a timeout to cron tasks, to avoid a long-running blockage

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

Fixes two semi-related issues for /whatsnew pages related to Firefox 100.
#9575

Fix /whatsnew URL version number logic for Firefox 100 (Issue #9575)

---

bedrock/releasenotes/tests/test_views.py
bedrock/releasenotes/views.py

System requirement pages for Android releases exist from 46.0 and upward. This changeset makes sure that it the relevant check works for FF100 and above
#9575
Unit tests passing should be enough - not sure how to trigger this directly, without actual release notes for 100 yet, but I think the scope of the change is tested well enough

Update android-sys-req helper for FF100+

---

bedrock/utils/tests/test_decorators.py

A clash between test auto-discovery (find something beginning with "Test") and a dummy/utility class created for testing the relevant decorator was causing pytest to raise warning.
Renaming the dummy classes solves the issue. Note that no tests were being skipped - the dummy classes being skipped were not actual test cases, so we didn't have a gap.
Resolves #11103 
Run `pytest bedrock/utils -vv` and see that the relevant tests mentioned in the diff are still run, while the warnings are now gone. (There are 13 tests in total in `bedrock/utils`)

Deal with warning during test collection of bedrock/utils 

---

requirements/base.txt

No point upgrading a redundant dependency.
It's not imported here and looks like it was related to a vendored version of DRF
No ticket
CI passing should be enough. The integration tests were happy too https://gitlab.com/mozmeao/bedrock/-/pipelines/447514918

Drop django-filter from project - no longer required

---

tests/unit/spec/base/core-datalayer-page-id.js
tests/unit/spec/base/core-datalayer.js
tests/unit/spec/base/dnt-helper.js
tests/unit/spec/base/experiment-utils.js
tests/unit/spec/base/fxa-utm-referral.js
tests/unit/spec/base/mozilla-banner.js
tests/unit/spec/base/mozilla-convert.js
tests/unit/spec/base/mozilla-fxa-form.js
tests/unit/spec/base/mozilla-fxa-link.js
tests/unit/spec/base/mozilla-fxa.js
tests/unit/spec/base/search-params.js
tests/unit/spec/base/send-to-device.js
tests/unit/spec/base/site.js
tests/unit/spec/firefox/all/all-downloads-unified.js
tests/unit/spec/firefox/new/common/thanks.js

We have a broken link in JS unit test comments. Needs update to current Jasmine docs.
NO BUG
http://pivotal.github.io/jasmine/ is broken and is replaced everywhere with https://jasmine.github.io/

Update jasmine docs link [NO BUG]

---

bedrock/firefox/tests/test_firefox_details.py
bedrock/releasenotes/tests/test_models.py
bedrock/releasenotes/tests/test_views.py
bedrock/releasenotes/views.py

This changeset expands test coverage for code that deals with specific version numbers, and confirms it handles three-digit version numbers without problem.
Contributes to #9575
Reviewing the tests and ensuring CI is green should be enough here

9575: Expand backend FF100 coverage

---

bedrock/externalpages/templates/externalpages/pocket/base.html

This script doesn't seem (?) to be used by any Pocket pages currently, so this PR removes the 404 request for now. We can always figure out the best way to include it when there's a requirement for it in the future.

Remove unused cookie helper 404 script (#11123)

---

bedrock/settings/base.py

`DisallowedHost` will still return a 400, but we won't get Sentry being filled with them
#11106
Local test-drive and CI passing should be enough. Integration tests have been pre-run https://gitlab.com/mozmeao/bedrock/-/pipelines/449752340

11106: Disable logging of DisallowedHost to reduce log noise

---

requirements/dev.txt

This changeset reverts only the pytest-selenium and selenium dependency upgrades from 6ce73dfac to reverse a regression. Updating Selenium will involve some code changes too, which we can do later.
This should bring `master` back to health
No ticket
CI passing is good. Integration tests have been pre-run at https://gitlab.com/mozmeao/www-config/-/pipelines/452352630 -- note that all the core/automatic ones are green, but some of the optional ones may not be, but don't need to be green

Downgrade pytest-selenium and selenium to avoid regression in integration tests

---

bedrock/externalpages/templates/externalpages/pocket/base.html
bedrock/externalpages/templates/externalpages/pocket/includes/nav.html
media/css/externalpages/pocket/includes/_mobile-nav.scss
media/js/externalpages/pocket/base.js
media/js/externalpages/pocket/mobile-nav-init.es6.js
media/js/externalpages/pocket/mobile-nav.es6.js
media/static-bundles.json
tests/functional/externalpages/pocket/__init__.py
tests/functional/externalpages/pocket/test_navigation.py
tests/pages/externalpages/pocket/__init__.py
tests/pages/externalpages/pocket/about.py
tests/pages/externalpages/pocket/base.py
tests/unit/karma.conf.js
tests/unit/spec/externalpages/pocket/mobile-nav.es6.js

Introduce Functional and JS Unit tests for new Pocket mobile navigation
Functional:
- open and close menu  
- accessible names are available on open and close buttons
Unit:
- accessible focus management
https://github.com/mozilla/bedrock/issues/11029
Run functional test locally: `py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/externalpages/pocket`
`py.test --base-url http://localhost:8000 --driver Chrome --html tests/functional/results.html tests/functional/externalpages/pocket`
successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/449648084
successful test run 2 (after removing timeout): https://gitlab.com/mozmeao/www-config/-/pipelines/451416342
Unit tests should pass in PR CI

Add tests to pocket mobile navigation (fixes #11029)

---

.pre-commit-config.yaml
bedrock/externalpages/templates/externalpages/pocket/base.html
bedrock/settings/base.py
media/js/externalpages/pocket/snowplow.es6.js
media/static-bundles.json

Part of Pocket to Bedrock Pocket migration: we need to preserve the [Snowplow Analytics script](https://github.com/mozmeao/pocket-marketing-pages/blob/master/content/marketing-assets/js/snowplow.js)
https://github.com/mozilla/bedrock/issues/11171
NOTE:
You'll get CORS errors similar to the ones from [pocket repo](https://github.com/mozmeao/pocket-marketing-pages) if you run master locally
This is fine once in production on [getpocket.com](https://getpocket.com/en/)
http://localhost:8000/en-US/external/pocket/about/
Should load the "se" dev script on localhost.
In Storage > Cookies, there should be a long lasting ID cookie to persist across sessions and a short session cookie.

Add snowplow to pocket (fixes #11171)

---

lib/l10n_utils/__init__.py
lib/l10n_utils/tests/test_base.py

Fix [bug 1752823](https://bugzilla.mozilla.org/show_bug.cgi?id=1752823).
As seen in [Sentry](https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/17149595/?query=is%3Aunresolved).

Use default language if none match accept-language

---

bedrock/wordpress/api.py

Quick fix for occasional blow-up https://sentry.prod.mozaws.net/operations/bedrock-demos/issues/17944644/?referrer=alert_email
Noticket
Eyeballing is enough here, and we can see it recover on Dev

Quick fix to handle WP posts having no tags data returned

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html

Update module owners in the Access Policy page.
See https://wiki.mozilla.org/Modules/All for the current owners

Update module owners in the Access Policy page

---

bedrock/mozorg/redirects.py
bedrock/redirects/util.py
tests/redirects/map_globalconf.py

Include default query params if none are incoming with the request, otherwise forward the ones from the request.
Fix #11204

Add redirects for /turningred and /truecolors

---

docs/install.rst

rST doesn't seem to like links nested in bold. 
I rearranged the copy a bit to adjust the syntax. 
Does the instruction still make sense?

Fix docs syntax [no bug]

---

bedrock/mozorg/templates/mozorg/credits.html
media/css/mozorg/credits.scss

Removed non-functional stylesheet URL from credits page and added those rules to credits.scss
#11197

fixing of non-functional stylesheet URL from credits page

---

bedrock/products/templates/products/vpn/includes/macros.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/tests/test_helper_misc.py
bedrock/products/views.py
bedrock/settings/base.py
l10n/en/products/vpn/shared.ftl

Adds 2 new supported countries to the VPN landing page behind `SWITCH_VPN_WAVE_V`
#11213
`SWITCH_VPN_WAVE_V=on`
`SWITCH_VPN_WAVE_V=off`

Add new supported countries to VPN landing page (Fixes #11213)

---

docs/newsletters.rst

We have a line on [Bedrock's newsletter docs](https://bedrock.readthedocs.io/en/latest/newsletters.html#configuration) to see Basket for more information. This adds a link to the Basket docs homepage to find that information.
no bug
Does this link make sense? Should it go directly to the Newsletter API docs or the github repo instead?

Add basket docs link [no bug]

---

tests/functional/test_cdn.py

We're not paying for the extra backwards compatability on the cdns,
so it makes sense to skip this test for dev/stage

Skipping the compatibility test for not-prod

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

Our friends in Canada and the UK might spell it this way if they hear
about the campaign. Let's support them.

Add redirect support for /truecolours

---

bedrock/mozorg/templates/mozorg/namespaces.html

Because we're now linking off to a Wikipedia page (thanks to https://github.com/mozilla/bedrock/pull/11242), calling it 'documentation' didn't seem appropriate.
No ticket
Go to http://localhost:8080/keymaster/gatekeeper/there.is.only.xul locally and confirm the page is not broken

Minor fix to the label element when showing the XUL namespace page

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2021.html
bedrock/mozorg/urls.py

Adds report for July-December 2021.
#11214
http://localhost:8000/en-US/about/policy/transparency/jul-dec-2021/

Add Transparency Report for H2 2021 (Fixes #11214)

---

docs/testing.rst
tests/functional/firefox/new/test_download.py
tests/functional/firefox/test_installer_help.py
tests/functional/test_home.py

Since https://github.com/mozmeao/www-config/pull/429 we're no longer running functional tests using IE9 against deployed code, since this old browser is now a bit too much of a challenge to run the SSL certs we use in our deployment environments.
Instead, we have a new set of CDN tests that were added in https://github.com/mozilla/bedrock/pull/11129, which will at least make sure the site is accessible in old browsers such as legacy IE.
This PR removes references to the now obsolete `sanity` marker in functional browser tests.

Remove obsolete sanity markers from functional tests

---

bedrock/careers/templates/careers/home.html

We were linking the 2019 diversity and inclusion link instead of the more recent, 2020 version. Fixed that ~
http://localhost:8000/en-US/careers/ and scroll down to the `Diversity and Inclusion at Mozilla` section and `Learn more` has the updated link

Update diversity link in careers page

---

bedrock/firefox/templates/firefox/whatsnew/includes/fx98-mobile-de/qr.html
bedrock/firefox/templates/firefox/whatsnew/includes/fx98-mobile-fr/qr.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-de.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-fr.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
media/css/firefox/whatsnew/whatsnew-98-mobile-eu.scss
media/static-bundles.json
tests/functional/firefox/whatsnew/test_whatsnew_98.py
tests/pages/firefox/whatsnew/whatsnew_98.py

Adds a WNP for Firefox 98 in German and French.
#11211
- http://localhost:8000/de/firefox/98.0/whatsnew/
- http://localhost:8000/fr/firefox/98.0/whatsnew/

WNP 98 for DE/FR (Fixes #11211)

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py

Fixes `ftl_file_is_active` check preventing translated locales from displaying the correct template.
#11262
1. Make sure to update locales locally first by running `bin/bootstrap.sh`.
2. Set `Dev=False` in your `.env`.

Fix active locale logic for displaying VPN NWP 98 (Fixes #11262)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-de.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-fr.html

There's little to be gained by forcing desktop users to go through adjust.com links and some privacy extensions prevent opening them, so let's link directly to the app stores instead.
- http://localhost:8000/de/firefox/98.0/whatsnew/
- http://localhost:8000/fr/firefox/98.0/whatsnew/
Note: the QR-Code in each page still retains opening an adjust.com URL.
#11211

Remove adjust.com links from WNP 98 badges (issue #11211)

---

bedrock/firefox/templates/firefox/mobile/get-app.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/urls.py
bedrock/settings/base.py

Add variation context to get-app template to set the `message_set` param for `send_to_device`
This message should correspond to basket ID `download-firefox-mobile-reco-exp` in bedrock settings
We also need new adjust links on the `?v=mfm` variation
Google Play Store: https://app.adjust.com/y68hlxi?campaign=firefox-desktop&adgroup=about-prefs&creative=mfm-fxvt-default-global-email-site-and&fallback=http%3A%2F%2Fmozilla.org%2Ffirefox%2Fmobile%2F
App Store: https://app.adjust.com/y68hlxi?campaign=firefox-desktop&adgroup=about-prefs&creative=mfm-fxvt-default-global-email-site-ios&fallback=http%3A%2F%2Fmozilla.org%2Ffirefox%2Fmobile%2F 
https://github.com/mozilla/bedrock/issues/11206
should have regular message_set: `fx-mobile-download-desktop` …

Add variation for get-app email basket id (fixes #11206)

---

bedrock/settings/base.py

See:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#directives
- https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-SECURE_REFERRER_POLICY
Re https://bugzilla.mozilla.org/show_bug.cgi?id=1697793

Set strict-origin-when-cross-origin as default Referrer Policy

---

bedrock/firefox/templates/firefox/developer/firstrun.html
bedrock/firefox/templates/firefox/developer/whatsnew.html

Fixing of Styling and link issues on Firefox Developer firstrun and Dev Edition whatsnew page.
#11281

fixed Styling and link issues on Firefox Developer page

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-turningred-en.html
media/css/firefox/whatsnew/whatsnew-98-turningred-en.scss

1. Changes the secondary headline to "Oh and here are a few ways Firefox can relate with Turning Red:" to make it a bit less literal.
2. Adds the line "A mystical connection with red pandas (firefoxes)" at the top of the list. It was always supposed to be there but got omitted from the mockup at some point.
3. The hero image has a little "OMG!" cloud which creates some extra whitespace on the left, pushing the red swatch off-center. This just shifts the image a bit left to compensate and look more visually balanced. I didn't really measure anything, just eyeballed it, and 50px felt about right.
#11208 
http://localhost:8000/en-US/firefox/98.0/whatsnew/?geo=us

WNP98 Turning Red: update copy, center image

---

bedrock/firefox/templates/firefox/developer/includes/for-developers.html
bedrock/firefox/templates/firefox/developer/includes/intro-features.html
bedrock/firefox/templates/firefox/developer/includes/performance.html
l10n/en/firefox/developer.ftl

Updates last picto text and anchor on Developer Whatsnew and Firstrun pages. Near term fix. Long term fix should involve how (if?) we keep these pages updated.
https://github.com/mozilla/bedrock/issues/11281
http://localhost:8000/en-US/firefox/98.0a2/firstrun/
http://localhost:8000/en-US/firefox/98.0a2/whatsnew/
last picto should read "Built for Developers" in EN and fallback to "Next gen CSS Engine" in untranslated languages (all except EN at the moment)

Update last intro feature on dev

---

bedrock/base/templates/includes/banners/mozilla-connect.html
bedrock/mozorg/templates/mozorg/contribute.html
bedrock/mozorg/urls.py
l10n/en/banners/mozilla-connect.ftl
l10n/en/brands.ftl
media/css/base/banners/mozilla-connect.scss
media/css/mozorg/contribute.scss
media/js/base/banners/mozilla-connect-banner-init.js
media/static-bundles.json

Adds a Mozilla Connect banner on the contribute page with link to https://connect.mozilla.org/
Banner is behind switch. Should be live **March 15**.
switch PR: https://github.com/mozmeao/www-config/pull/437
analytics link: https://connect.mozilla.org?utm_source=contribute-website&utm_medium=banner&utm_campaign=connect-campaign&utm_content=15032022
https://github.com/mozilla/bedrock/issues/11233
http://localhost:8000/en-US/contribute/
`SWITCH_MOZILLA_CONNECT_BANNER=on` (default in DEV mode) shows banner
`SWITCH_MOZILLA_CONNECT_BANNER=off` does not show banner

Add contribute banner (fixes #11233)

---

package-lock.json
package.json

We want to use latest karma and browser-sync dev dependencies
No bug
JS unit tests should pass on PR. (`npm run test` locally)
Locally, page should automatically refresh with changes to .html, .scss, and .js files

chore: bump karma and browser-sync [no bug]

---

bedrock/base/templates/includes/banners/mozilla-connect.html
bedrock/mozorg/urls.py
l10n/en/banners/mozilla-connect.ftl
l10n/en/brands.ftl

Mozilla Connect site is not translated and we decided it's best to [leave the banner English only](https://github.com/mozilla/bedrock/issues/11233#issuecomment-1069299483) across locales.
No leftover FTL connections.
http://localhost:8000/en-US/contribute/ - hardcoded English content is correct

Remove translation file for Mozilla Connect banner

---

bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html

As we now have an official [Localization module](https://groups.google.com/a/mozilla.org/g/governance/c/sl8l7pcvR44/m/pGpvQOJOBAAJ), we can drop individual names (currently commented out), and point to owner/peers.

Commit access: Update named vouchers for l10n

---

bedrock/legal/templates/legal/index.html
bedrock/legal/templates/legal/terms/mdn-plus.html
bedrock/legal/urls.py
bedrock/privacy/templates/privacy/base-protocol.html
bedrock/privacy/templates/privacy/notices/mdn-plus.html
bedrock/privacy/urls.py
bedrock/privacy/views.py
l10n/en/brands.ftl
l10n/en/mozorg/about/legal.ftl
l10n/en/privacy/index.ftl

Adds MDN Plus privacy and terms of service to appropriate pages.
⚠️ DO NOT MERGE until March 23. We can wait until that date or put the changes behind a switch.
✅ This has sign-off from stakeholders.
https://github.com/mozilla/bedrock/issues/11184
https://www-demo4.allizom.org/en-US/privacy (link listed in side
navigation)
https://www-demo4.allizom.org/en-US/privacy/mdn-plus
https://www-demo4.allizom.org/en-US/about/legal/ (link listed under Terms heading)
https://www-demo4.allizom.org/en-US/about/legal/terms/mdn-plus

[March 23] Add MDN Plus legal pages (fixes #11184)

---

bedrock/mozorg/templates/mozorg/diversity/2021/beyond-products.html

Remove trailing spaces after some URLs in hrefs on a D&I page
We can't add them to the link checker if they have trailing spaces
No ticket
* Manually checking the links work when running the page -- though eyeballing is probably fine for a few space removals

Remove trailing spaces after some URLs in hrefs on a D&I page

---

bedrock/products/templates/products/vpn/resource-center/base-article.html

We missed a protocol-split import in VPN Resource Center articles. Added here.
should have proper split styling
http://localhost:8000/en-US/products/vpn/resource-center/5-reasons-you-should-use-a-vpn/

Add protocol-split bundle to vpn article

---

app.json
bedrock/settings/base.py

This changeset updates the config for the Heroku Review apps to use SaaS Sentry, under the bedrock-demos DSN.
It also updates the django-csp connect-src list to allow `sentry.io`
(The values in Heroku's web-based config have also been updated to the new bedrock-demos DSN)
No ticket
Might need y'all to push up a branch for review (eg this one) and see? Not pushed a review app here before, so would welcome a pointer about how it's done here.

Update Sentry-related values in Bedrock

---

bedrock/firefox/templates/firefox/facebookcontainer/index.html
bedrock/firefox/templates/firefox/installer-help.html
bedrock/firefox/templates/firefox/new/desktop/download.html
bedrock/firefox/templates/firefox/privacy/base.html
bedrock/mozorg/templates/mozorg/diversity/2021/index.html
bedrock/mozorg/templates/mozorg/moss/base.html
media/css/firefox/facebook-container.scss
media/css/firefox/installer-help.scss
media/css/firefox/new/desktop/download.scss
media/css/firefox/privacy/products.scss
media/css/mozorg/diversity/2021/diversity-2021.scss
media/css/mozorg/moss.scss

This PR will primarily work on converting the `card` & `card-layout` (they are coupled here) component. I also converted some other components because they resided in the same file, and thought it be best to kill two birds (or, however many birds in this case) with one stone (or, rather, a PR).
#11032 
http://localhost:8000/en-US/firefox/facebookcontainer/
http://localhost:8000/en-US/firefox/installer-help/
http://localhost:8000/en-US/firefox/privacy/products/ (just removed the `card` + `card-layout` imports from `firefox/privacy/products.scss` as it's not being used for the page)
http://localhost:8000/en-US/moss/
http://localhost:8000/en-US/diversity/2021/ (all pages in the diversity nav)
http://localhost:8000/en-US/moss/ …

Updating `card` Protocol component to CSS bundle

---

bedrock/firefox/templates/firefox/browsers/best-browser.html
bedrock/firefox/templates/firefox/browsers/browser-history.html
bedrock/firefox/templates/firefox/browsers/incognito-browser.html
bedrock/firefox/templates/firefox/browsers/update-browser.html
bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
bedrock/firefox/templates/firefox/campaign/unfck/index.html
bedrock/firefox/templates/firefox/channel/base.html
bedrock/firefox/templates/firefox/features/adblocker.html
bedrock/firefox/templates/firefox/features/safebrowser.html
bedrock/firefox/templates/firefox/new/desktop/thanks.html
bedrock/firefox/templates/firefox/releases/notes.html
bedrock/firefox/templates/firefox/releases/system_requirements.html
bedrock/mozorg/templates/mozorg/about/manifesto.html
bedrock/mozorg/templates/mozorg/home/home-contentful.html
media/css/firefox/browsers/best-browser.scss
media/css/firefox/browsers/browser-history.scss
media/css/firefox/browsers/incognito-browser.scss
media/css/firefox/browsers/update-browser.scss
media/css/firefox/browsers/windows-64-bit.scss
media/css/firefox/channel.scss
media/css/firefox/features/safebrowser.scss
media/css/firefox/new/basic/thanks.scss
media/css/firefox/releasenotes.scss
media/css/firefox/system-requirements.scss
media/css/firefox/unfck.scss
media/css/mozorg/home/home-contentful.scss
media/css/mozorg/manifesto.scss

Converting `call-out` CSS imports to CSS bundles
#11032 
http://localhost:8000/en-US/firefox/channel/desktop/
http://localhost:8000/en-US/firefox/97.0/releasenotes/
http://localhost:8000/en-US/firefox/97.0.1/system-requirements/
http://localhost:8000/en-US/firefox/unfck/
http://localhost:8000/en-US/firefox/browsers/best-browser/
http://localhost:8000/en-US/firefox/browsers/browser-history/
http://localhost:8000/en-US/firefox/browsers/incognito-browser/
http://localhost:8000/en-US/firefox/browsers/update-your-browser/
http://localhost:8000/en-US/firefox/browsers/windows-64-bit/
http://localhost:8000/en-US/firefox/features/adblocker/
http://localhost:8000/en-US/firefox/features/safebrowser/
`/firefox/new/desltop/thanks.html` (i can't find the URL for this page) …

Updating `call-out` Protocol component to CSS bundle

---

bedrock/firefox/templates/firefox/developer/index.html
media/css/firefox/developer/includes/engage.scss

I didn't do it in this PR https://github.com/mozilla/bedrock/pull/11355 so doing it here
#11032 

Add `picto` bundle to `firefox/developer` page

---

bedrock/exp/templates/exp/opt-out.html
bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
bedrock/privacy/templates/privacy/email.de.html
bedrock/privacy/templates/privacy/email.fr.html
bedrock/privacy/templates/privacy/email.html
bedrock/products/templates/products/vpn/more/base-article.html
media/css/exp/opt-out.scss
media/css/firefox/browsers/what-is-a-browser.scss
media/css/mozorg/about-transparency.scss
media/css/privacy/privacy-email.scss
media/css/products/vpn/article.scss
media/static-bundles.json

Converting `article` CSS imports to CSS bundles
#11032 
http://localhost:8000/en-US/exp/opt-out/
http://localhost:8000/en-US/firefox/browsers/what-is-a-browser/
http://localhost:8000/en-US/about/policy/transparency/ (removed the `article` CSS import from its respective CSS file (`about-transparency.scss`) since the page doesn't use it.
http://localhost:8000/en-US/privacy/email/
http://localhost:8000/fr/privacy/email/
http://localhost:8000/de/privacy/email/
http://localhost:8000/en-US/products/vpn/more/do-i-need-a-vpn/ 
http://localhost:8000/en-US/products/vpn/more/what-is-a-vpn/
http://localhost:8000/en-US/products/vpn/more/what-is-an-ip-address/
http://localhost:8000/en-US/products/vpn/more/when-to-use-a-vpn/
http://localhost:8000/en-US/products/vpn/more/vpn-or-proxy/

converting articles

---

bedrock/exp/templates/exp/opt-out.html

Fixes 500 error for mnissing CSS file
#11367
http://localhost:8000/en-US/exp/opt-out/

Remove unused CSS bundle reference (Fixes #11367)

---

bedrock/firefox/templates/firefox/developer/index.html
bedrock/firefox/templates/firefox/retention/thank-you.html
bedrock/firefox/templates/firefox/testflight.html
bedrock/legal/templates/legal/fraud-report.html
bedrock/legal/templates/legal/index.html
bedrock/newsletter/templates/newsletter/base.html
bedrock/newsletter/templates/newsletter/developer.html
bedrock/newsletter/templates/newsletter/firefox.html
bedrock/newsletter/templates/newsletter/mozilla.html
media/css/firefox/retention/thank-you.scss
media/css/firefox/testflight.scss
media/css/legal/legal.scss
media/css/newsletter/newsletter-developer.scss
media/css/newsletter/newsletter-firefox.scss
media/css/newsletter/newsletter-mozilla.scss
media/css/newsletter/newsletter.scss

Converting `newsletter-form` CSS imports to CSS bundles
#11032 
http://localhost:8000/en-US/firefox/ios/testflight/
http://localhost:8000/en-US/firefox/retention/thank-you/
http://localhost:8000/en-US/about/legal/
http://localhost:8000/en-US/newsletter/developer/
http://localhost:8000/en-US/newsletter/firefox/
http://localhost:8000/en-US/newsletter/mozilla/
http://localhost:8000/en-US/newsletter/ (I'm not sure if this is the only file associated with the changes in `newsleter/newsletter.scss`, but it's the one I could directly find.
http://localhost:8000/en-US/firefox/ios/testflight/
http://localhost:8000/en-US/about/legal/defend-mozilla-trademarks/

Converting `newsletter-form` into CSS bundle

---

bedrock/firefox/templates/firefox/accounts.html
bedrock/firefox/templates/firefox/browsers/index.html
bedrock/firefox/templates/firefox/firstrun/firstrun.html
bedrock/firefox/templates/firefox/new/basic/thanks.html
bedrock/firefox/templates/firefox/new/desktop/download.html
bedrock/firefox/templates/firefox/nightly/whatsnew.html
bedrock/firefox/templates/firefox/privacy/products.html
bedrock/firefox/templates/firefox/products/index.html
bedrock/firefox/templates/firefox/unsupported-systems.html
bedrock/newsletter/templates/newsletter/base.html
bedrock/press/templates/press/speaker-request.html
media/css/firefox/accounts-2019.scss
media/css/firefox/browsers-products.scss
media/css/firefox/firstrun/firstrun.scss
media/css/firefox/new/desktop/download.scss
media/css/firefox/new/desktop/thanks.scss
media/css/firefox/privacy/products.scss
media/css/firefox/unsupported-systems.scss
media/css/firefox/whatsnew/whatsnew-nightly.scss
media/css/newsletter/newsletter.scss
media/css/press/press.scss

Converting the `emphasis-box` Protocol component from CSS imports to CSS bundles
#11032 
http://localhost:8000/en-US/firefox/accounts/
http://localhost:8000/en-US/firefox/products/
http://localhost:8000/en-US/firefox/browsers/
http://localhost:8000/en-US/firefox/unsupported-systems/
http://localhost:8000/en-US/firefox/firstrun/
http://localhost:8000/en-US/firefox/privacy/products/
http://localhost:8000/en-US/firefox/100.0a1/whatsnew/
http://localhost:8000/en-US/newsletter/ (I'm not sure if this is the only file associated with the changes in `newsletter/newsletter.scss`, but it's the one I could directly find.)
http://localhost:8000/en-US/press/speakerrequest/
http://localhost:8000/en-US/newsletter/ (I'm not sure if this is the only file associated …

Convert `emphasis-box` into CSS bundle

---

media/js/base/mozilla-cookie-helper.js
tests/unit/karma.conf.js
tests/unit/spec/base/core-datalayer-page-id.js
tests/unit/spec/base/fxa-utm.js
tests/unit/spec/base/mozilla-banner.js
tests/unit/spec/base/mozilla-cookie-helper.js
tests/unit/spec/base/stub-attribution.js
tests/unit/spec/firefox/all/all-downloads-unified.js

Added tests for the Mozilla.Cookies helpers: `getItem, setItem, hasItem, removeItem and keys`
Fixes #11338
run `npm run test` and it will run the test suite

Added test suite for Mozilla.Cookies

---

bedrock/settings/base.py

Setting a null handler in the Django logging config didn't seem to be working (either at all, or at least for certain cases of DisallowedHost, for non-obvious reasons). This is the approach taken by the Relay team, where it works.
https://github.com/mozmeao/infra/issues/1374
Replicating some of the bad requests with `curl` is tricky, because it rejects them (because they are invalid!) but we should soon see a decrease in DisallowedHost results in Sentry anyway

Switch to ignoring DisallowedHost at the Sentry level

---

bedrock/newsletter/forms.py
bedrock/newsletter/templates/newsletter/includes/form.html
bedrock/newsletter/templatetags/helpers.py
bedrock/newsletter/tests/test_forms.py
bedrock/newsletter/tests/test_views.py
bedrock/newsletter/views.py
docs/newsletters.rst
media/js/newsletter/form-protocol.es6.js

This updates the form submission to accept newsletters as a list value and convert to CSV for Basket call.
https://github.com/mozilla/bedrock/issues/11270

Update `NewsletterFooterForm` to use `MultipleChoiceField`

---

media/js/base/banners/mozilla-banner.js
media/js/base/fxa-utm.es6.js
media/js/base/mozilla-cookie-helper.js
media/js/base/stub-attribution.js
media/js/firefox/sticky-promo.js
media/js/libs/mozilla-traffic-cop.js
tests/unit/spec/base/fxa-utm.js
tests/unit/spec/base/stub-attribution.js

Updated the calls to Mozilla.Cookies.SetItem inside bedrock to include the sameSite=lax (if none was set previously) attribute to fix the warnings we were getting previously.
#11058
These are the javascript files that are effected (from what I can tell) - you should no longer get a warning about SameSite being added to cookies that are set inside of bedrock
Mozilla Banner & fxa-utm.js: http://localhost:8000/
Mozilla.Cookies.enabled: http://localhost:8000/ (think this is run on launch of any page? could be wrong!)
Traffic Cop: http://localhost:8000/en-US/firefox/welcome/8/
Sticky promo: http://localhost:8000/en-US/firefox/browsers/compare/brave/

Add samesite attr to Cookies.SetItem calls within 1st party JS

---

.pre-commit-config.yaml
.stylelintrc
package-lock.json
package.json

Updated `value-keyword-case` to allow camelCasing for keywords that come from SVG, specifically, `currentColor`. See https://github.com/stylelint/stylelint/issues/5863 for discussion.
#11340
`npm run lint-css`

Update Stylelint (Fixes #11340)

---

bedrock/privacy/templates/privacy/base-protocol.html

Moves sidebar to the bottom of the page for mobile users when trying to view privacy notices.
#10628
http://localhost:8000/en-US/privacy/

Render sidebar at the end of /privacy pages for mobile (Fixes #10628)

---

bedrock/contentful/api.py
bedrock/contentful/templates/includes/contentful/all.html
bedrock/contentful/tests/test_contentful_api.py

This isn't a perfect solution but seems sane (?) and certainly better than what we have now. Assumes that if the first Contentful entry on a page is either a Hero or Split component, then set `loading="eager"`, else set `loading="lazy"`.
https://github.com/mozilla/bedrock/issues/10669

Lazy load Contentful images on home page (Fixes #10669)

---

bedrock/mozorg/templates/mozorg/home/home-contentful.html

Add the Firefox Account product name to the CTA
#10706

Make home page footer CTA more obvious about which product it relates to (Fixes #10706)

---

docs/testing.rst
tests/functional/conftest.py

This should hopefully help with flakey test clicks in IE, such as https://gitlab.com/mozmeao/www-config/-/jobs/2289800872
N/A
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/509413100 (I re-ran this a bunch of times)

Set nativeEvents to false for IE SauceLabs tests

---

media/css/l10n/zh-CN/intl.css

We found that there is a small miss of zh-CN intl.css here: https://github.com/mozilla/bedrock/commit/0f59dc09485c86d8eeb9bb8678d1c38198b2a551#diff-7ac7b33cf917c31888237b97fdcbf3a5392495e091acbfc6635c83e8da56784dL20-R36
So just wanna fix it, thx

Fix zh-CN bold fonts

---

bedrock/security/templates/security/base.html
bedrock/security/templates/security/third-party-injection-policy.html
bedrock/security/urls.py

Adds new policy to the `/security/` section.
#11276
http://localhost:8000/en-US/security/third-party-software-injection/

Add Third-Party Software Injection Policy (Fixes #11276)

---

bedrock/mozorg/templates/mozorg/about/governance/governance.html

Update discussion forum link to non-archived mailing list
https://bugzilla.mozilla.org/show_bug.cgi?id=1743147
http://localhost:8000/en-US/about/governance/
Discussion forum link goes to https://groups.google.com/a/mozilla.org/g/governance

Update governance discussion forum link (fixes #10866)

---

bin/open-compare.py

The https://www.mozilla.org/revision.txt seems to be empty, but using "prod" seems to work just as well to compare the prod and master branches.

Add `rev` fallback to "prod"

---

bedrock/products/templates/products/vpn/includes/cookie-notification.html
l10n/en/products/vpn/shared.ftl
media/css/products/vpn/components/affiliate.scss
media/js/products/vpn/affiliate-init.es6.js

- Adds additional 'OK' button to dismiss the affiliate banner.
- Updates GA events for banner interaction.
#11454
http://localhost:8000/en-US/products/vpn/?cjevent=09d8676b716a11ec831e01500a18050e

Add 'OK' button to VPN affiliate banner (Fixes #11454)

---

media/css/firefox/welcome11.scss
media/css/firefox/welcome12.scss
media/css/firefox/welcome13.scss
media/css/firefox/whatsnew/includes/_dark-mode.scss
media/css/firefox/whatsnew/includes/_footer.scss
media/css/firefox/whatsnew/whatsnew-99-en.scss

Fix regression from https://github.com/mozilla/bedrock/pull/11300
Updates remaining ".c-footer" selectors
Nests footer styles for firefox pages in ".mzp-c-footer.mzp-t-light" to override new light theme class
Removes redundant styles
https://github.com/mozilla/bedrock/issues/11465
http://localhost:8000/en-US/firefox/99.0/whatsnew/
http://localhost:8000/en-US/firefox/welcome/11/
http://localhost:8000/en-US/firefox/welcome/12/
http://localhost:8000/en-US/firefox/welcome/13/

Fix remaining selectors for new footer styles (fixes #11465)

---

bedrock/firefox/templates/firefox/testflight.html
bedrock/newsletter/templates/newsletter/includes/form.html
bedrock/products/templates/products/vpn/invite.html

Hides visible newsletter checkboxes for single newsletters
#11469
- http://localhost:8000/en-US/products/vpn/invite/
- http://localhost:8000/en-US/firefox/ios/testflight/

Hide checkboxes on single newsletters (Fixes #11469)

---

media/js/firefox/new/common/thanks-direct.js

Adds referrer check for AMO to /thanks/ attribution page.
#11467
Please test on a Windows VM / browser:

Add AMO referrer check for /thanks/?s=direct page (Fixes #11467)

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Upgrade Django to 3.2.13 following security release announcement
No ticket
* CI passing should be enough  - the diff for 3.2.12 to 3.2.13 seems _almost_ entirely focused on the security issue and the change to the template reloading seems safe - https://github.com/django/django/compare/3.2.12...3.2.13

Upgrade Django to 3.2.13 following security release announcement

---

bedrock/settings/base.py

See https://github.com/mozilla/legal-docs/issues/1735
`main` branch is already available in the legal-docs repository

Switch legal-docs branch from master to main for DEV

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Note: We need to watch this as it deploys to prod and be prepared to roll-back if there are issues with scaling.

Update gunicorn dependency

---

docs/coding.rst

We updated how we import some Protocol components by creating some CSS bundles for them. The original ticket explaining it is here: https://github.com/mozilla/bedrock/issues/11032
https://github.com/mozilla/bedrock/issues/11382
`make livedocs` and go to http://127.0.0.1:8100/coding.html#working-with-protocol-design-system
`make docs` and go to http://127.0.0.1:8100/coding.html#working-with-protocol-design-system

Document CSS bundles updates

---

docs/coding.rst

It seems that some sub-subsection titles were broken and couldn't be seen anymore from [my previous PR](https://github.com/mozilla/bedrock/pull/11526) because I had to update their underlines.
Here is a good explanation as to what underlines represent different subsections for reStructured text: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections
Updated the underlines from `<<<<` to `^^^^`
`make livedocs` and go to http://127.0.0.1:8100/coding.html#working-with-protocol-design-system
`make docs` and go to http://127.0.0.1:8100/coding.html#working-with-protocol-design-system

Updated subsection underline for visibility

---

bedrock/security/templates/security/bug-bounty.html
bedrock/security/templates/security/bug-bounty/web-eligible-sites.html

- modify bug bounty program policy to exclude harmful testing on services
- request testing on bedrock staging instead of production

modify program policy to exclude harmful testing on services

---

bedrock/firefox/templates/firefox/mobile/get-app.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/urls.py
bedrock/settings/base.py

Sets up three new variations of the get-app page. The URLs will get direct traffic, no traffic cop needed.
#11547 
http://localhost:8000/firefox/mobile/get-app/?v=eco-a
http://localhost:8000/firefox/mobile/get-app/?v=eco-b
http://localhost:8000/firefox/mobile/get-app/?v=eco-c
Each variant should hide the app store buttons and set its corresponding message-set in the form (view source and look for the hidden `message-set` field).

Add get-app page experiment variations [fix #11547]

---

bedrock/firefox/templates/firefox/features/tips/tips.html
bedrock/firefox/templates/firefox/more.html
bedrock/firefox/templates/firefox/more/misinformation.html
bedrock/firefox/templates/firefox/pocket.html
bedrock/firefox/templates/firefox/privacy/index.html
bedrock/firefox/templates/firefox/privacy/passwords.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
media/css/firefox/privacy/common.scss
media/css/protocol/components/split.scss

Some of the `nospace` split components at the top of firefox pages have a gap on mobile sizes. These changes remove that gap.
update (21/4/22): there are more instances of pages with this gap, so this PR will widen scope to address those. A [discussion issue ](https://github.com/mozilla/protocol/issues/779)has been created in Protocol to decide how to handle these cases in future
https://github.com/mozilla/bedrock/issues/11457
fix checks
http://localhost:8000/en-US/firefox/more/
http://localhost:8000/en-US/firefox/privacy/safe-passwords/
(updated 21/4/22)
http://localhost:8000/en-US/firefox/features/tips/
http://localhost:8000/en-US/firefox/pocket/
http://localhost:8000/en-US/firefox/more/misinformation/
http://localhost:8000/en-US/about/policy/lean-data/ (and sub-pages)
no regression …

Remove gap space on firefox pages (fixes #11457)

---

bedrock/base/templates/macros.html
bedrock/base/tests/test_macros.py
bedrock/firefox/templates/firefox/browsers/chromebook.html
bedrock/firefox/templates/firefox/browsers/compare/includes/subnav.html
bedrock/firefox/templates/firefox/browsers/mobile/android.html
bedrock/firefox/templates/firefox/browsers/mobile/compare.html
bedrock/firefox/templates/firefox/browsers/mobile/focus.html
bedrock/firefox/templates/firefox/browsers/mobile/includes/sub-nav.html
bedrock/firefox/templates/firefox/browsers/mobile/index.html
bedrock/firefox/templates/firefox/browsers/mobile/ios.html
bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
bedrock/firefox/templates/firefox/channel/base.html
bedrock/firefox/templates/firefox/includes/desktop-platform-sub-nav.html
bedrock/firefox/templates/firefox/new/basic/base_download.html
bedrock/firefox/templates/firefox/privacy/base.html
bedrock/firefox/templates/firefox/privacy/book.html
bedrock/firefox/templates/firefox/privacy/includes/sub-nav.html
bedrock/firefox/templates/firefox/releases/notes.html
bedrock/mozorg/templates/mozorg/diversity/2021/index.html
bedrock/products/templates/products/vpn/includes/subnav-more.html
bedrock/products/templates/products/vpn/platforms/includes/subnav-desktop.html
bedrock/products/templates/products/vpn/platforms/includes/subnav-mobile.html
media/css/protocol/components/_sub-navigation.scss

Adds sub_nav macro for standard HTML structure and dynamic `aria-current=page` attribute. This applies to our most consistent sub navigations.
Removes commented out Android Beta link in Release Notes sub nav: https://github.com/mozilla/bedrock/issues/10064
https://github.com/mozilla/bedrock/issues/10038
Check subnavs have expected text and links for the following
Test locally `py.test bedrock/base/tests/test_macros.py`

Add sub_nav macro and current page styling (fixes #10038)

---

bedrock/careers/views.py
bedrock/exp/views.py
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
bedrock/legal_docs/views.py
bedrock/mozorg/tests/test_views.py
bedrock/mozorg/util.py
bedrock/mozorg/views.py
bedrock/products/views.py
bedrock/releasenotes/views.py
bedrock/security/views.py
bedrock/sitemaps/tests/test_views.py
bedrock/sitemaps/views.py
bedrock/utils/views.py
bedrock/wordpress/views.py
docs/coding.rst
lib/l10n_utils/__init__.py
lib/l10n_utils/tests/test_base.py

This updates the `page` URL helper to wrap the view using the `require_safe` decorator, and also limits the HTTP methods on the `L10nTemplateView` to `GET` or `HEAD`. All other views explicitly get decorated with `@require_safe`.
#11536 
`curl -i -X POST localhost:8000/en-US/` and various pages return `HTTP/1.1 405 Method Not Allowed`

Ensure GET views are protected

---

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html

Removes extraneous hashes from the heading for section 5.3.1 (some artifact of the markdown conversion that I missed).
And tools.ietf.org now forwards to datatracker.ietf.org, so this updates the remaining links to avoid the extra redirect.
http://localhost:8000/about/governance/policies/security-group/certs/policy/

CA policy fixes [bug #1766461]

---

media/css/mozorg/home/home-fx100-promo.scss

Designers have asked for some small changes to the firefox 100 promo - decreased font-size on medium and above viewports and updated the size of the Firefox 100 logo to match the line height of the title.
Demo server URL: https://localhost:8000/en-US

small edits to fx100 promo from design

---

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html

Some asterisks got stripped in the conversion from markdown.
http://localhost:8000/about/governance/policies/security-group/certs/policy/#611-end-entity-tls-certificate-crlrevocation-reasons

Add asterisks in root store policy [bug #1766461]

---

bedrock/mozorg/templates/mozorg/home/home-de.html
bedrock/mozorg/templates/mozorg/home/home-fr.html
bedrock/mozorg/templates/mozorg/home/includes/fx100-promo-eu.html
bedrock/mozorg/templates/mozorg/home/includes/fx100-promo.html

Created promo for firefox 100 for FR and DE locales - also updated the CTA to link to `firefox/new` for EN as well
Demo server URL: https://localhost8000/fr and https://localhost8000/de
Just load your local server to the homepage and the fx100 promo should be viewable in both FR and DE locales.

fx100 promo for FR and DE

---

docs/coding.rst

Adds a link to country code table in the docs.

Add link to ISO country code table in docs (Fixes #11568)

---

l10n/en/firefox/privacy/book.ftl

I missed one in my checks, because the code didn't deal very well with HTML strings (and plenty of double quotes).

Fix straight double quotes in Fluent string (privacy/book)

---

bedrock/careers/management/commands/sync_greenhouse.py
bedrock/contentful/tests/test_templatetags_helpers.py
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

This changeset updates `boto` and `bleach`, as nudged by Dependabot. 
Hat-tip to @robhudson for nice tests that caught/matched a breaking change in Bleach - see https://bleach.readthedocs.io/en/latest/clean.html#sanitizing-css

Dependency bumps to boto and bleach

---

bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
bedrock/settings/base.py

- Adds a list of countries in `settings` where we can't sell or advertise Mozilla VPN.
- Updates our `/whatsnew` logic to reference this list before deciding to promote VPN.
Make sure I got the [list of countries](https://docs.google.com/presentation/d/1_TCE85CSXw_A5grv12fAclknXOUe3NYsiaBj4Pelk3Q/edit?usp=sharing) and their [respective codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) correct?
Note: `UA` is left out intentionally after discussion with legal.
#11572
If relevant:

Add additional countries to VPN exclusion list for /whatsnew (Fixes #11572)

---

bedrock/firefox/templates/firefox/new/desktop/download.html
bedrock/firefox/views.py
media/js/base/experiment-utils.es6.js

Prevent showing the _"You already have Firefox..."_ interstitial modal if we know the visitor is having trouble updating their Firefox.
#11071
Test using Firefox (signed out of a Firefox Account):

Don't show Firefox download interstitial in manual update flow (#11071)

---

bedrock/firefox/templates/firefox/new/desktop/download.html

Edge is now available on Windows, macOS and Linux.
#11593

Update OS availability when comparing Firefox and Edge (Fixes #11593)

---

bedrock/pocket/templates/pocket/android.html
bedrock/pocket/templates/pocket/chrome.html
bedrock/pocket/templates/pocket/edge.html
bedrock/pocket/templates/pocket/ios.html
bedrock/pocket/templates/pocket/opera.html
bedrock/pocket/templates/pocket/safari.html
bedrock/pocket/templates/pocket/welcome.html
bedrock/pocket/urls.py
l10n-pocket/en/brands.ftl
l10n-pocket/en/pocket/platforms.ftl

Created Fluent file for Pocket's platform pages and placed their strings in the respective file.
Fluent file found in `l10n-pocket/en/pocket/platforms.ftl`
https://github.com/mozilla/bedrock/issues/11519

Adding Fluent file for Pocket Platforms pages

---

.gitlab-ci.yml
Dockerfile
bedrock/settings/__init__.py
bedrock/settings/base.py
bin/open-ftl-pr.sh
lib/l10n_utils/fluent.py
lib/l10n_utils/management/commands/_ftl_repo_base.py
lib/l10n_utils/management/commands/l10n_update.py
lib/l10n_utils/management/commands/open_ftl_pr.py

This changeset is the first/main pass to support a Pocket-specific `mozilla-l10n` / Fluent workflow. The relevant new repo for translations exists at https://github.com/mozilla-l10n/pocket-www-l10n.
When `SITE_MODE=Pocket` updated defaults for almost all `FLUENT_*` settings are set - e.g. pointing at a Pocket-specific repo for translations, etc.
For Pocket mode, we don't need an intermediary mozmeao/* repo to hold the translations while we calculate activation metadata via a CI task (which does happen for Mozorg). Why? All locales in Pocket should be 100% ready to go, because they are translated by a vendor, whereas Mozorg has community translation contributions as well, which aren't always exhaustive.
As a result,  we are in Pocket mode, both `FLUENT_REPO` and `FLUENT_L10N_TEAM_REPO` …

Lay in Pocket l10n workflow support

---

bedrock/firefox/templates/firefox/new/basic/thanks.html
bedrock/firefox/templates/firefox/new/desktop/thanks.html
bedrock/firefox/templatetags/helpers.py
bedrock/firefox/tests/test_helpers.py
bedrock/mozorg/tests/test_views.py
media/css/firefox/new/basic/thanks.scss
media/css/firefox/new/desktop/thanks.scss
media/js/firefox/new/common/thanks.js
tests/unit/spec/base/site.js
tests/unit/spec/firefox/new/common/thanks.js

Serve the full Firefox installer to users on Windows 7 when hitting `/firefox/download/thanks/`.
This is only a temporary measure whilst they fix an issue with the stub installer, so I tried to make the change as low effort as possible so we can roll out a fix quickly. I've added tests for the new condition, but some manual testing on a Windows 7 VM (e.g. using Browser Stack) would be helpful to verify that the change works as expected.
#11606
If relevant:
Test using a Windows 7 VM (I used browserstack.com for dev):
URLs:
- http://localhost:8000/en-US/firefox/new/
- http://localhost:8000/en-US/firefox/download/thanks/
- http://localhost:8000/en-US/firefox/download/thanks/?xv=basic
- http://localhost:8000/en-US/firefox/download/thanks/?s=direct
- …

Serve full Firefox installer for users on Windows 7 (Fixes #11606)

---

.stylelintrc
media/css/pocket/components/add.scss
media/css/pocket/components/new-tab-learn-more.scss
media/css/pocket/components/platforms.scss
media/css/pocket/components/pocket-features.scss

- Reinstate `declaration-no-important` rule for Stylelint.
- Fix existing errors in Pocket pages.
#11594

Add no-important rule to Stylelint (Fixes #11594)

---

bedrock/pocket/templates/pocket/404.html
bedrock/pocket/templates/pocket/500.html
bedrock/pocket/views.py
bedrock/urls/pocket_mode.py

This changeset fixes 500s we're seeing for Pocket-Dev when spiders/bots/whatever hit URLs that would normally 404. It does this by quickly adding minimal 404 and 500 templates (pinched from @maureenlholland's WIP branch for proper error pages)
Without this changeset, Pocket-Dev tries to render the default Mozorg 404 page, which tries to reverse `mozorg.home`, fails hard and then tries to render the 500 page, which tries to reverse `mozorg.home` and fails harder.
The templates added are super low-fi, but will do the job of reducing Sentry noise for now. As @pmac mentioned, we may not need them in production, but they are useful for now.
Snaps to @maureenlholland, whose branch I stole most of this 😄 
Resolves #11611
- set DEBUG=False in your …

11611 fix pocket mode 500s

---

bedrock/pocket/templates/pocket/contact-info.html
bedrock/pocket/urls.py
l10n-pocket/en/brands.ftl
l10n-pocket/en/pocket/contact-info.ftl

Use Fluent with Pocket contact-info page
https://github.com/mozilla/bedrock/issues/11598
http://localhost:8000/en-US/contact-info/

Add ftl file for pocket contact-info (fixes #11598)

---

bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html

The TOC was omitted (it doesn't appear in the markdown, we have to add it manually). I also updated the steps in the comment so hopefully I don't forget again next time. 🤦 
http://localhost:8000/en-US/about/governance/policies/security-group/certs/policy/

Add table of contents to CA policy [bug #1766461]

---

docs/install.rst

Just added `Local run` in the Pocket section of the documentation for clarity on which command to run based on how you're running bedrock
- local: `make livedocs`
- docker: `make docs`
- http://127.0.0.1:8100/install.html#pocket-mode

Add "Local run" for Pocket start command

---

bedrock/firefox/templates/firefox/new/basic/thanks.html

Adds missing CSS bundle to fix page headline styling.
#11608
http://localhost:8000/en-US/firefox/download/thanks/?xv=basic

Add missing protocol-call-out bundle to /thanks/ page (Fixes #11608)

---

bedrock/base/templates/macros-protocol.html

Fixes a rendering bug on the home page by making `link_url` and `link_cta` optional macro params.
https://github.com/mozilla/bedrock/issues/11569

Update billboard macro to make link optional (Fixes #11569)

---

bedrock/pocket/templates/pocket/includes/pocket-premium.html
bedrock/pocket/templates/pocket/save-to-pocket.html
bedrock/pocket/urls.py
l10n-pocket/en/pocket/banners/pocket-premium.ftl
l10n-pocket/en/pocket/save-to-pocket.ftl

Convert save-to-pocket to use FTL strings (fixes #11623)
- run in pocket mode
- navigate to https://localhost:8000/save-to-pocket and compare to [dev server](https://dev.tekcopteg.com/en/save-to-pocket/)

Convert save-to-pocket to use FTL strings (fixes #11623)

---

bedrock/firefox/templates/firefox/new/desktop/download.html
l10n/en/firefox/new/desktop.ftl

Replaces outdated Lockwise copy on `/firefox/new/`.
#10795

Replace Lockwise copy shown when trying to re-download Firefox (Fixes #10795)

---

media/css/protocol/common-old-ie.scss
media/css/protocol/protocol-firefox.scss
media/css/protocol/protocol-mozilla.scss

This changeset adds a CSS selector for the hidden attribute in order to provide backwards compatibility for old browsers like IE10. Old browsers were not registering the hidden attribute to hide elements.
- `./media/css/protocol/common-old-ie.scss` seemed like a better place for this change, however, it didn't seem to be loading on every page.
- I attempted to push up a demo branch to one of the on-demand demos for manual testing in IE, however, was denied permissions. This might be user error here and will ask about this on the mozilla.org chat. https://bedrock.readthedocs.io/en/latest/contribute.html#server-architecture
https://github.com/mozilla/bedrock/issues/11476

fix bug 11476 - Adds css selector for hidden attribute

---

bedrock/firefox/templates/firefox/nightly/whatsnew.html
media/css/firefox/whatsnew/whatsnew-nightly.scss

I've created new CSS style for the a:visited element (was #e7dfff font color from Protocol class and that was our problem).
https://github.com/mozilla/bedrock/issues/11563
I think this will do the trick.

Link hover contrast issue on Nightly /whatsnew page

---

bin/compile-requirements.sh
requirements/dev.txt
requirements/docs.txt
requirements/prod.in
requirements/prod.txt

This changeset updates Twilio, Sentry SDK and Boto, following nudges from dependabot.
It also updates the pinned versions of pip and pip-tools in `bin/compile-requirements.sh`
Resolves #11636
Resolves #11635
Resolves #11585

2022-05-16's dependency bumps

---

bedrock/firefox/templates/firefox/nightly/whatsnew.html
l10n/en/firefox/nightly/whatsnew.ftl
media/js/firefox/whatsnew/nightly.js
media/static-bundles.json

Updates Nightly /whatsnew page to link to `about:preferences#experimental` via UITour.
#11487
http://localhost:8000/en-US/firefox/102.0a1/whatsnew/
Make sure you have UITour enabled for local dev: https://bedrock.readthedocs.io/en/latest/uitour.html#local-development

Link to about:preferences in Nightly /whatsnew page (Fixes #11487)

---

media/css/firefox/whatsnew/whatsnew-nightly.scss

Quick bug fix to add a bg colour to the Nightly /whatsnew page for rubber and scrolling.
#10251
http://localhost:8000/en-US/firefox/101.0a1/whatsnew/

Set bg color on Nightly /whatsnew page for rubber band scrolling (Fixes #10251)

---

bin/run-tests.sh

Lints Pocket .ftl files for duplicate strings, syntax errors etc.
#11660

Lint Pocket Fluent files (Fixes #11660)

---

bedrock/pocket/templates/pocket/404.html
bedrock/pocket/templates/pocket/500.html
bedrock/pocket/templates/pocket/includes/platform-footer.html
bedrock/pocket/views.py
l10n-pocket/en/pocket/404.ftl
l10n-pocket/en/pocket/500.ftl
media/css/pocket/components/error-page.scss
media/css/pocket/includes/_platform-footer.scss
media/static-bundles.json

Adds Pocket 500/404 translations and styling. The pages should be cleanly styled and easy to read, showing appropriate template depending on the error (500 = server error, 404 = page not found).
Note: the 404 is using existing Pocket copy but not the existing styles: https://getpocket.com/en/asg
⚠️ we might never see the 404 in production, but it doesn't hurt to have a backup
https://github.com/mozilla/bedrock/issues/11542
http://localhost:8000/en/404/
http://localhost:8000/en/500/

Add pocket 404 and 500 pages (fixes #11542)

---

media/js/products/vpn/affiliate-attribution.es6.js
tests/unit/spec/products/vpn/affiliate-attribution.js

Small edge case fix to avoid throwing an un-handled error when certain conditions are met:
1. Visitor has an existing affiliate marketing cookie set.
2. The ID for that cookie has since expired in the CJMS database.
3. Visitor returns to the page with no `cjevent` query parameter set. 
#11506
If relevant:
The included tests should already cover this, but manual testing is not so easy as you need a cookie with an ID that's not in the database. The easiest way I could mock this was to manually create a cookie in the console using:
```javascript
Mozilla.Cookies.setItem(
'moz-vpn-affiliate',
'some-unique-to-you-test-value',
new Date(Date.now() * 1000).toUTCString(),
'/',
null,
false,
'lax'
);
```
Then reload the page and you should be able to verify …

Remove affiliate marketing cookie if aic id is unknown and there's no cjevent param (Fixes #11506)

---

bedrock/products/templates/products/vpn/more/ip-address.html

Fixes missing link `href` passed to Fluent string.
#11676
http://localhost:8000/en-US/products/vpn/more/what-is-an-ip-address/

Fix missing link href on VPN SEO page (Fixes #11676)

---

bedrock/pocket/templates/pocket/firefox/new-tab-learn-more.html
bedrock/pocket/urls.py
l10n-pocket/en/pocket/firefox/new-tab.ftl
l10n-pocket/en/pocket/new-tab.ftl
media/css/pocket/components/new-tab-learn-more.scss

Add Fluent strings to the new_tab_learn_more page
#11519 
- Local: run `npm run in-pocket-mode`
- Docker: `make run-pocket` and `make run-pocket prod`

Fluent-size firefox/new_tab_learn_more

---

bin/compile-requirements.sh
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Manually force upgrade of pyjwt (a subdep of Pygithub and fluent-runtime. Even though neither top-level dep specifies a hard version of pyjwt to use, pip-tools was coming back with 2.3.0, not the security-patched 2.4.0, so this subdep was promoted to top-level dep, at least for now

Dependency bump: pyjwt 

---

tests/conftest.py

This will make the Frankfurt integration tests happy again, where there is
not yet a prod deployment to test against
```
$ pytest -m pocket_mode
...
ERROR tests/functional/pocket/test_navigation.py::test_mobile_menu - django.core.exceptions.ImproperlyConfigured: No BASE_P...
ERROR tests/functional/pocket/test_navigation.py::test_accessible_mobile_menu_open_name - django.core.exceptions.Improperly...
ERROR tests/functional/pocket/test_navigation.py::test_accessible_mobile_menu_close_name - django.core.exceptions.Improperl..
```
```
$ pytest -m pocket_mode
...
SKIPPED [3] tests/conftest.py:34: No BASE_POCKET_URL detected in env vars
```

Make Pocket-mode integration tests automatically skip if no BASE_POCKET_URL exists

---

bedrock/landing/templates/landing/base-landing.html
media/js/landing/landing-shared.js

Fixed typo for `handleWordmarkClick` function in  the `landing-shared.js` file
- http://localhost:8080/en-US/landing/firefox/fx100

Fix typo in SEM landing pages function

---

bedrock/products/templates/products/vpn/landing.html

Adds Glean JS bundle to /products/vpn/ landing page.
#10746

Add Glean to /products/vpn/ landing page (Issue #10746)

---

bedrock/firefox/templates/firefox/developer/whatsnew-mdnplus.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
l10n/configs/pontoon.toml
l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
media/css/firefox/developer/whatsnew-mdnplus.scss
media/static-bundles.json

A whatsnew page for Firefox Dev Edition to promote MDN Plus. It's controlled by the switch `firefox-developer-whatsnew-mdnplus` and isn't specific to any version as we'll probably run it for more than one release cycle (or could turn it off for a few releases and back on again later).
#11633 
http://localhost:8000/firefox/102.0a2/whatsnew/

Add WNP for Dev Edition promoting MDN Plus [fix #11633]

---

bedrock/pocket/templates/pocket/add.html
bedrock/pocket/templates/pocket/jobs.html

Removes `rel` and `target` attributes for the help.getpocket domain as it is Mozilla controlled. Also small syntax fix on quotations in an href.
https://github.com/mozilla/bedrock/issues/11666
In code, there should be no more _blank links for help.getpocket domain

Remove blank target on pocket support links, fix typo, (fixes #11666)

---

.github/workflows/demo_deploy.yml

This will re-enable demo deployments on pushes to the demo branches (e.g. `demo/5`). You can see a [successful test run](https://github.com/mozilla/bedrock/runs/6730752746).

Add Heroku demo deployment GitHub Action

---

bedrock/settings/base.py
media/js/base/sentry.es6.js
package-lock.json
package.json
webpack.config.js

This PR updates our Sentry JS SDK bundle to v7.0.
This is a major version bump with some breaking changes:
- Sentry 7.0 allows us to "opt in" to use only the [default integrations](https://docs.sentry.io/platforms/javascript/configuration/integrations/default/) that we find most useful. The benefit here is that we can end up with a smaller JS bundle by using only what we need/want. There are some useful [tree shaking docs](https://docs.sentry.io/platforms/javascript/configuration/tree-shaking/) here which I used as reference.
- The 7.0 NPM package is now published directly as ES modules, allowing for a smaller footprint. As discussed on Slack yesterday, we're going to decide against transpiling the Sentry code for older browsers, as doing so loses many of the optimisations we would …

Update to Sentry v7.0.0 (Fixes #10473)

---

bedrock/base/templates/includes/sticky-promo.html

Since it's not good practice to have UTM parameters in same-site link, we've decided to remove it in the sticky promo
https://github.com/mozilla/bedrock/issues/11725

Removed UTM param from same-site link

---

bedrock/firefox/templates/firefox/home/index-master.html
bedrock/firefox/templates/firefox/new/basic/base.html
bedrock/firefox/templates/firefox/new/desktop/base.html

Adds glean bundle to core Firefox pages.
#10746
Glean page pings on:

Add Glean to core /firefox pages (Issue #10746)

---

l10n/en/firefox/new/download.ftl

Two variables in [`firefox/new/download.ftl`](https://github.com/mozilla/bedrock/blob/main/l10n/en/firefox/new/download.ftl) didn't have spaces. I added the spaces for best practices and consistency.
https://github.com/mozilla/bedrock/issues/11740

Add spaces in L10N strings

---

bedrock/settings/__init__.py
l10n-pocket/configs/vendor.toml

This changeset gets the locales all lined up to be correct based on what's _currently_ configured at the vendor end for the Pocket L10N pipeline.
It's not the entire solution, though: the vendor side is using "es-ES", but getpocket.com currently uses /es/ in its URLs, which means we will need to bridge that gap. That work is written up in #https://github.com/mozilla/bedrock/issues/11738
At least, with the current config in this changeset, Bedrock in Pocket Mode WILL handle the locale differences (redirecting from `/es/add` to `/es-ES/add`, for example), but will do so with a HTTP 302 Temporary Redirect - and that has an SEO impact. (Ideally any redirect due to a locale code being different must be a 301.)
Testing this is tricky until we have translations flowing, which in turn need this …

Update Pocket locale/L10N config based on latest info about translations from Vendor

---

bedrock/newsletter/templates/newsletter/includes/form.html
bedrock/newsletter/templates/newsletter/index.html

When used older browser or browser where JS is disabled, subscribe to newsletter shows a blank screen.
Added no script tag so that optional message will be shown if javascript is disabled.
#10327 
1.  start bedrock server and go to bottom for subscribing to newsletter
2. disable browser javascript
3. enter email (`success@example.com`)
4.  subscribe

10327 java script disabled on browser fix

---

bedrock/products/templates/products/vpn/includes/macros.html
bedrock/products/templates/products/vpn/landing.html
bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
docs/firefox-accounts.rst

Removes `vpn_download_link` helper and points all VPN download page links to the new bedrock page.
#11748

Stop sending people to the legacy VPN download page (Fixes #11748)

---

bedrock/settings/__init__.py

...because for now Pocket Mode is loading from the same S3 bucket as Mozorg, which is CNAMEd to a mozilla.org domain

Update CSP rules for Pocket mode - needs to allow mozilla.org

---

bedrock/pocket/templates/pocket/home.html
l10n-pocket/en/pocket/home.ftl
media/css/pocket/components/about.scss
media/css/pocket/components/add.scss
media/css/pocket/components/home.scss
media/css/pocket/components/platforms.scss
media/css/pocket/includes/_nav.scss

Adds 10 year badge to bedrock pocket home to match live site: https://getpocket.com/en/
Also removes any unused $image-path vars and updates to use $pocket-image-path namespacing to avoid protocol conflicts
https://github.com/mozilla/bedrock/issues/11730
related pocket pr: https://github.com/mozmeao/pocket-marketing-pages/pull/53
Run in pocket mode
http://localhost:8000/en/
You should see pocket logo and "10 Years of Pocket" above the H1 in the hero section.
To test no errors after variable updates:
http://localhost:8000/en/about/
http://localhost:8000/en/add/
http://localhost:8000/en/ios/
Top Navigation

Add pocket home 10 year badge (fixes #11730)

---

bedrock/mozorg/templates/mozorg/home/home.html

Empowering Women Online link was redirecting to blank page
Changed the link in [this path](https://github.com/mozilla/bedrock/blob/487ecbad3381507bbac5b9244f409853c9473fa1/bedrock/mozorg/templates/mozorg/home/home.html#L84)
#11703 
1. Open https://www.mozilla.org/es-ES/
2. Click the link [Empoderando a las mujeres en línea](https://learning.mozilla.org/blog/new-partnership-with-un-women-to-teach-key-digital-skills-to-women/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage)

11703 changed broken link to working link

---

bedrock/settings/__init__.py
l10n-pocket/configs/smartling-config.json

The locale codes from our translation vendor don't quite align with the simpler locales used in Pocket's URLs. It looks like  we can address that via translation config, which is what we do here.
Note how `PROD_LANGUAGES` for Pocket references the shorter locale code - this is because when they translations emerge from the L10N pipeline, they should (🤞) land in directories like `es` not `es-ES`, etc. 
If this works, even though the locale pattern will be slightly different from Mozorg (where we always use the full `locale-REGION` pattern), we will be providing _exactly_ the same URLs in locale terms as getpocket.com currently does, which saves us UX and SEO pain.
Resolves #11738 
* Not much to manually test until we get L10N data flowing in.

Support mapping of locales at vendor level for Pocket

---

bedrock/foundation/templates/foundation/base.html

The strategy 2016-2016 was inaccessible and outdated.
removal of the item from list
#11460 
1. go to link  /en-US/foundation/trademarks/list/
2. verify the 2016-2018 link is absent.

removed outdated doc from foundation list

---

bedrock/settings/__init__.py

I don't feel great about adding a wild card for all GA sub domains, but I'm not sure if there's a better way seeing as there seem to be several regions?
#11768

Add region1.google-analytics.com to CSP list (Fixes #11768)

---

docs/abtest.rst
media/js/firefox/browsers/firefox-ios-sms-experiment.js
media/js/firefox/welcome/welcome8-traffic-cop.js
media/js/firefox/whatsnew/whatsnew-101-en-experiment.js
media/js/firefox/whatsnew/whatsnew-99-en-experiment.js
package-lock.json
package.json

Updates TrafficCop to v2.0.0, so it no longer needs to dangle off a `Mozilla` global variable.
https://github.com/mozilla/bedrock/issues/11775
The following URLs should all trigger traffic cop experiment redirects (make sure you don't have DNT set):

Update @mozmeao/trafficcop to v2.0.0 (Fixes #11775)

---

bedrock/firefox/templates/firefox/set-as-default/landing.html
bedrock/firefox/urls.py
l10n/en/firefox/set-as-default/landing.ftl
media/js/firefox/set-as-default/landing.js
media/static-bundles.json

- Added new copy to the Firefox set-as-default page
- Added Traffic cop for a split test with three variations. The experiment is behind a switch, otherwise it will default to the copy for variation 1.
The switch on www/config in this PR: https://github.com/mozmeao/www-config/pull/466
Fixes #11772 and #11773 
Demo server URL: https://localhost:8000/firefox/set-as-default

Code variations for set to default page (fixes #11772)

---

bedrock/contentful/api.py
bedrock/contentful/templates/includes/contentful/all.html
media/css/contentful/mozilla/c-split.scss
media/css/mozorg/home/home-contentful.scss

This PR updated the code in bedrock to update the split component to be used on the contentful homepage instead of hero
https://github.com/mozilla/bedrock/issues/10445
The following screenshots are from the local preview viewing the EN-US homepage - both are using the updated split component:
Pull down this branch, and then start a local server - load a contentful preview of the sandbox environment and you should be able to see both the hero components and split components to compare. Once this PR merges, we can remove the old Hero components from the contentful homepage.

update the contentful API to use Split

---

bedrock/base/templates/includes/protocol/navigation/nav-cta.html
bedrock/firefox/templates/firefox/new/basic/base_download.html
bedrock/firefox/templates/firefox/new/basic/download_windows.html
bedrock/firefox/templates/firefox/new/desktop/download.html
bedrock/products/templates/products/vpn/includes/pricing-variable.html
media/js/firefox/new/desktop/join-modal.js
media/js/glean/elements.es6.js

This builds on https://github.com/mozilla/bedrock/pull/11771 by adding the click delay to a few more CTAs (temporarily). This should only be needed for a couple of weeks and then I think we can turn Glean off for now.
#11770

Add Glean click delay for a few more CTAs (Fixes #11770)

---

codecov.yml

Pinched from https://docs.codecov.com/docs/common-recipe-list#only-comment-on-coverage-changes
Resolves #11786

Make Codecov refrain from commenting on a PR if coverage has not changed

---

bedrock/base/templates/includes/protocol/navigation/nav-cta.html
bedrock/firefox/templates/firefox/new/basic/base_download.html
bedrock/firefox/templates/firefox/new/desktop/download.html
bedrock/products/templates/products/vpn/includes/pricing-variable.html
media/js/firefox/new/desktop/join-modal.js
media/js/glean/elements.es6.js

I ended this test too early, as some delayed data coming through on Friday made me wrongly assume it didn't have an effect. Sorry for the noise here, but I think this warrants some more time to run.
This reverts commit 8fc042425b2cbc676db8a03694736cd6fb853039.
#11770

Revert "Remove Glean click delay test (Fixes #11770) (#11785)"

---

.github/workflows/glean-probe-scraper.yml

This should hopefully prevent the action running on forks of bedrock.
#11803

Only run Glean probe-scraper GitHub action on mozilla/bedrock (Fixes #11803)

---

bedrock/newsletter/forms.py
bedrock/newsletter/templates/newsletter/includes/form.html
l10n/en/newsletter_form.ftl
media/css/firefox/developer/includes/newsletter.scss

Adds localised field labels for country and language to newsletter forms.
#11829
- http://localhost:8000/en-US/
- http://localhost:8000/en-US/newsletter/
- http://localhost:8000/en-US/newsletter/mozilla/
- http://localhost:8000/en-US/newsletter/firefox/
- http://localhost:8000/en-US/newsletter/developer/
- http://localhost:8000/en-US/newsletter/knowledge-is-power/
- http://localhost:8000/en-US/contribute/

Add country and language newsletter field labels (Fixes #11829)

---

docs/coding.rst

Added a sub-section in our documentation to list the front-end dependencies we currently have in place for Bedrock.
I listed it as a sub-section under `Managing Dependencies`. I thought this would be a good spot for it? Let me know if you think otherwise.
#11795 
- If using Docker, run `make docs`
- If using locally, run `make livedocs`
- Go to http://127.0.0.1:8100/coding.html#front-end-dependencies

Add front-end dependencies section in documentation (fixes #11795)

---

bedrock/base/templatetags/helpers.py
bedrock/contentcards/models.py
bedrock/contentcards/tests/test_models.py
bedrock/contentful/templatetags/helpers.py
bedrock/contentful/tests/test_templatetags_helpers.py
bedrock/firefox/templatetags/helpers.py
bedrock/firefox/tests/test_base.py
bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/templatetags/qrcode.py
bedrock/mozorg/tests/test_helper_misc.py
bedrock/newsletter/templatetags/helpers.py
bedrock/newsletter/views.py
bedrock/pocketfeed/models.py
bedrock/products/templatetags/misc.py
bedrock/settings/base.py
bedrock/wordpress/models.py
bin/compile-requirements.sh
lib/l10n_utils/templatetags/fluent.py
lib/l10n_utils/templatetags/helpers.py
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

All three need upgrading at the same time because jinja 3.1+ removes deprecated
code which we were leaning on in Bedrock and django-jinja markdown - either
a convenience import of `Markup` or a change in decorators
Fixes #[11561](https://github.com/mozilla/bedrock/pull/11561) - which couldn't be automatically merged without this legwork.
If relevant:
This will need a decent local test drive around, I think

Upgrade jinja2, django-jinja and django-jinja-markdown

---

bedrock/firefox/templates/firefox/retention/thank-you.html

/es-ES/firefox/retention/thank-you/ and other locales were 500ing because of
> Reverse for 'firefox.set-as-default.landing' not found. 'firefox.set-as-default.landing' is not a valid view function or pattern name.
Turns out that view name changed to firefox.set-as-default in https://github.com/mozilla/bedrock/pull/11774. This changeset updates the only reference in bedrock to the old URL name.
Resolves #11846
To test this work, ensure `DEBUG=False` in your `.env`, then visit 
- http://localhost:8080/en-US/firefox/retention/thank-you/
- http://localhost:8080/es-ES/firefox/retention/thank-you/
which will no longer 500

Fix up URL name for Set As Default page, to stop retention page from 500ing

---

bedrock/base/templates/includes/protocol/navigation/nav-cta.html
bedrock/firefox/templates/firefox/new/basic/base_download.html
bedrock/firefox/templates/firefox/new/desktop/download.html
bedrock/products/templates/products/vpn/includes/pricing-variable.html
media/js/firefox/new/desktop/join-modal.js
media/js/glean/elements.es6.js

Glean is now turned off in production. We may enable it again in the future to test some changes, however I think this delay code can safely be retired permanently.
#11770

Remove Glean delay ping code (#11770)

---

bedrock/base/templates/includes/banners/vpn-coupon-variations/vpn-coupon-promo-1.html

Talked to Hanns on the EU team re: https://github.com/mozilla/bedrock/issues/11826#issuecomment-1178726858
He agreed that the first two items should be fixed.
#11826
http://localhost:8000/de/products/vpn/?entrypoint_experiment=vpn-coupon-promo-banner&entrypoint_variation=1

Fix typos in /de/ VPN promo banner (Issue #11826)

---

bedrock/products/templates/products/vpn/landing.html

We have a Traffic Cop experiment running on the VPN landing page. I  initially set it up to have variation 2 on the default landing page (with no experiment parameters). I misunderstood, so fixing that up here to remove the banner form a no-parameter page.
Original PR: https://github.com/mozilla/bedrock/pull/11828
You should see no banner in the following pages:
- http://localhost:8000/de/products/vpn/
- http://localhost:8000/fr/products/vpn/

Remove variation #2 from default VPN page

---

bedrock/base/templates/base-protocol.html
media/css/protocol/components/_download-button.scss
media/js/base/site.js
media/js/firefox/new/common/thanks.js
tests/unit/spec/base/site.js
tests/unit/spec/firefox/new/common/thanks.js

On Oct 25th, Chrome is freezing UA string info that relates to platform version, CPU type, and CPU architecture. These "high entropy" values will then only be available via the Client Hints API in Chromium browsers. This PR adds code to use the new Client Hints API, falling back to regular UA string checks for non-supporting browsers.
This change will help to ensure we carry on detecting things like 32/64 bit for Firefox Linux downloads, as well as info we rely on in a few other places (see below for details). 
- Removes redundant `x86` CPU architecture class.
- Updates `site.js` to favour using Client Hints when detecting:
- CPU size (32/64 bit).
- CPU type (x86, ARM).
#8440
Demo: https://www-demo1.allizom.org/
This PR should work without any config changes in the latest Chrome, however …

Use Client Hints to get high entropy platform info (Fixes #8440)

---

bedrock/products/templates/products/vpn/landing.html

Excludes countries where VPN isn't currently available from the promo banner experiment.
#11907 
For thoroughness you can also check both banner variations, in the French and German localized versions, and try a few other non-VPN countries (Denmark, Argentina, Saudi Arabia, Namibia, etc... go wild!).

Exclude non-VPN countries from banner experiment [fix #11907]

---

bedrock/security/templates/security/web-bug-bounty.html

This changeset adds a reference in the web bug bounty page to the general program eligibility requirements in order to make the web bug bounty page a single page that we can point researchers to where they won't miss the general program details.
The client bug bounty page has this but our web bug bounty page was missing it.
If relevant:

Add a reference in the web bug bounty program to the eligibility requirements

---

package-lock.json
package.json

Bug fixes: https://github.com/mozmeao/trafficcop/releases/tag/v2.0.1
#11884

Bump @mozmeao/trafficcop to v2.0.1 (Fixes #11884)

---

docs/architecture/decisions/0008-move-demos-to-gcp.md
docs/contribute.rst
newrelic.ini

This changeset updates the Bedrock docs with how to use the new Demo-server infrastructure. 
Currently, the new approach is not active for Mozorg demos, only Pocket demos, but we will arrange a switch over v soon, in a way that doesn't impact everyone's workflows. At that point, we can merge these docs, but pre-reading them now is useful, particularly if they raise questions.
We also add an Architecture Decision Record to capture the move from Heroku demo servers to GCP demo servers.

Update docs for new demo servers

---

package-lock.json
package.json

Release notes: https://github.com/getsentry/sentry-javascript/releases (nothing notable for us here just some bug fixes)
N/A
Set `SENTRY_FRONTEND_DSN=https://c1f94ae1b8c54ed0adcf223328157caf@o1069899.ingest.sentry.io/6260211` in your `.env` if you would like to test this locally.

Bump @sentry/browser to v7.6.0

---

docs/contentful.rst

Update Contentful docs to reflect Compose usage.
- Add Compose section
- Update Page description
- Change ♟️ Component name to "Embed"* (tested in `sandbox-compose-migration`, this is not done in `master` environment yet, would not change API ID, purely a Contentful UI-facing change)
- Update Roles/Permissions section
- Add Troubleshooting section
- Add Legacy section and move Connect component into it
- Fix formatting
*Embed in Contentful UI
https://github.com/mozilla/bedrock/issues/11815
http://127.0.0.1:8100/contentful.html

Update Contentful docs (fixes #11815)

---

bedrock/contentful/api.py
bedrock/contentful/templates/includes/contentful/all.html
media/css/contentful/firefox/c-split.scss
media/css/contentful/mozilla/c-split.scss

We're making changes to the Contentful content model and prioritizing Split over Hero components
This reverts unnecessary fields additions from https://github.com/mozilla/bedrock/pull/11712/files#diff-77ac837e3992065e29560e9150f097cdea55bf59219a4d22ef08cb00f1427f5fR771
And adds a workaround MDN Plus wordmark to split css (copied over from https://github.com/mozilla/bedrock/commit/bdf695fb79e80d79d57680fefe1d8f41762ef67a)
See https://github.com/mozilla/bedrock/issues/11822#issuecomment-1168752708 for issue and how to test
DO NOT MERGE until Contentful changes are reviewed and approved and Contentful master environment is updated
**edit:** these changes are OK to merge before the contentful master environment change, they won't break anything, but until that environment is changed, they …

Update contentful split api and css

---

bedrock/contentful/tests/test_contentful_api.py

Forgot to remove related tests from https://github.com/mozilla/bedrock/pull/11825/files
No bug
CI should pass
`py.test bedrock/contentful/tests/test_contentful_api.py` locally should pass

Remove outdated contentful split tests and mock data

---

bedrock/base/templates/404-locale.html
bedrock/careers/tests/test_views.py
bedrock/firefox/tests/test_views.py
bedrock/mozorg/context_processors.py
bedrock/newsletter/tests/test_views.py
bedrock/products/tests/test_views.py
bedrock/urls/mozorg_mode.py
l10n/en/404-locale.ftl
lib/l10n_utils/__init__.py
lib/l10n_utils/tests/test_base.py
lib/l10n_utils/tests/test_files/templates/404-locale.html
media/css/mozorg/locales.scss
tests/functional/conftest.py
tests/functional/test_experiment_pages.py
tests/functional/test_generated_pages.py
tests/redirects/base.py
tests/redirects/map_globalconf.py

This changes the default of unsupported locales from redirect to `/en-US/` to a 404 with a locale selection page.
The redirect to best locale logic depends on the `Accept-language` header. If yours is set to an English locale it will be hard to trigger the 404 locale selection page. So this is what I have done:
1. Set your preferred language in your browser settings to remove English and pick an uncommonly supported locale. I chose `ast` since it was near the top.
2. Navigate to localhost:8000 or localhost:8000/firefox/new/
You can also use `curl` to test responses with and without an accept language header like so:
1. `curl -IL localhost:8000/ -H "Accept-language: ast"`
2. `curl -IL localhost:8000/`

Return 404 page if locale is unavailable or no header sent 

---

bedrock/firefox/templates/firefox/new/basic/thanks.html
bedrock/firefox/templates/firefox/new/desktop/thanks.html
l10n/en/firefox/new/desktop.ftl
l10n/en/firefox/new/download.ftl
media/css/firefox/new/basic/thanks.scss
media/css/firefox/new/desktop/thanks.scss

- Adds a message to `/thanks/` notifying that Firefox will be pinned to the Windows taskbar on installation.
- Content is behind the switch `SWITCH_FIREFOX_103_TASKBAR_MESSAGE`.
#11759
Test on a Windows device / VM:

Notify users about pinning Firefox in Windows (Fixes #11759)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx103-en-rally.html

Requested via Slack to point the link to https://members.rally.mozilla.org (which redirects to a signup page if you're signed out, and they're working on updating that page with more info before the release).
http://localhost:8000/en-US/firefox/103.0/whatsnew/?v=2

Updated CTA link on Rally WNP103 [#11940]

---

l10n-pocket/en/pocket/about.ftl

CC @peiying2 
Spotted while adding more checks to my linter, mostly because locales didn't copy over this error.

about:ftl: Remove extra double quote from anchor

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx103-en-rally.html

Updates the meta description since the default is a bit inaccurate.
http://localhost:8000/en-US/firefox/103.0/whatsnew/?v=2

Update meta description on WNP 103 Rally page [#11940]

---

l10n-pocket/en/pocket/contact-info.ftl
l10n-pocket/en/pocket/legal.ftl

This replaces a couple of hard-coded brand names in Pocket strings. Found them while working on https://github.com/mozilla-l10n/pocket-www-l10n/pull/9

Fix hard-coded brand names in Pocket strings

---

bedrock/firefox/templates/firefox/browsers/mobile/index.html

The compare link of browser compare was wrong.
#11975 
See how Firefox for desktop stacks up to seven other browsers. compare button 
- http://localhost:8080/en-US/firefox/browsers/mobile/

fix wrong browser compare link

---

bedrock/mozorg/redirects.py
tests/redirects/map_globalconf.py

Adds redirect requested by legal
#11991

Create vanity redirect for transparency policy (Fixes #11991)

---

bedrock/products/templates/products/vpn/download.html
bedrock/products/templates/products/vpn/landing.html
l10n/en/products/vpn/landing.ftl

Bumps minimum supported iOS version to 13.0
#11980
- http://localhost:8000/en-US/products/vpn/#faq-compatibility
- http://localhost:8000/en-US/products/vpn/download/

Update supported iOS version on VPN pages (Fixes #11980)

---

bedrock/base/templates/macros-protocol.html
docs/coding.rst

- Updates Protocol macro docs to match what we have in code.
- Adds missing `l10n_image` param to the `card` macro.
Note: I haven't touched `feature_card`, which is being removed in https://github.com/mozilla/bedrock/pull/12018
#12019
``make livedocs``

Update Protocol macro docs (Fixes #12019)

---

bedrock/firefox/templates/firefox/mobile/index.html
bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
media/css/firefox/mobile/mobile.scss
tests/functional/firefox/browsers/mobile/test_landing.py
tests/pages/firefox/browsers/mobile_landing.py

- Fixes Firefox mobile page
- Adds integration tests
#12025
- http://localhost:8000/en-US/firefox/browsers/mobile/?xv=legacy
- http://localhost:8000/en-US/firefox/browsers/mobile/

Fix broken Firefox mobile page (Fixes #12025)

---

media/js/products/vpn/affiliate-attribution.es6.js
media/js/products/vpn/affiliate-init.es6.js
tests/unit/spec/products/vpn/affiliate-attribution.js

This fixes an edge case we ran into in #11998. If flow params are undefined then we should throw an error instead of passing over a bad value to the CJMS.
#11998
Prerequisites:
1. Use a browser with DNT disabled.
2. Make sure you have `Persist logs` checked in the dev tools web console so that you can see logs across page redirects.
Testing:
1. Open http://localhost:8000/en-US/products/vpn/?cjevent=123456789
2. You should be redirected to a traffic cop experiment with `entrypoint_experiment=vpn-coupon-promo-banner` in the URL.
3. Open the web console.
4. You should see an error saying `Error: FxA flow params are undefined.`
5. You should not see a 500 error posting data to `https://stage.cjms.nonprod.cloudops.mozgcp.net/` (which is what you get on the `main` branch).

Stop making CJMS calls if FxA flow params are undefined (Fixes #11998)

---

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
bedrock/security/templates/security/web-bug-bounty.html

This changeset explicitly defines the scope for Pocket in the web bug bounty.

changes to Pocket scope

---

bedrock/mozorg/templates/mozorg/about/leadership/index.html

Removes an extraneous dot.
http://localhost:8000/en-US/about/leadership/#kristen-trubey

Leadership page, delete extra period [no bug]

---

Makefile
requirements/dev.txt
requirements/docs.in
requirements/docs.txt
requirements/prod.in
requirements/prod.txt

This changeset updates dependencies for main Bedrock and also for the docs site.
* Most of it is pretty standard. I've checked `Sphinx` builds the docs ok and it does.
* Note that the `urllib3` upgrade clashes for the docs install - Sphinx wants and gets a lower version than sentry-sdk asks for, but docs generation doesn't need sentry-sdk anyway. We should look to build out a separate docs image that doesn't also need the dev deps, but it's not a big deal as-is.
Resolves #12033 Bump boto3 from 1.24.36 to 1.24.51 in /requirements
Resolves #12032 Bump sentry-sdk from 1.8.0 to 1.9.4 in /requirements
Resolves #12031 Bump twilio from 7.12.0 to 7.12.1 in /requirements
Resolves #12008 Bump phonenumberslite from 8.12.52 to 8.12.53 in /requirements
Resolves #11989 Bump sphinx from 4.5.0 to 5.1.1 …

2022-08-15 Dependency bumps

---

docs/l10n.rst

This will be useful if/when we add another mode to Bedrock for a different website.
It was requested by @peiying2 but is useful to all of us.
- pull this branch
- `make docs`
- go to http://0.0.0.0:8100/l10n.html#new-l10n-integrations

Add documentation about how to add a new L10N integration

---

package-lock.json

Updates NPM dependencies to fix https://github.com/mozilla/bedrock/security/dependabot/26
It seems that `webpack-terser-plugin` does not pin `terser` to a specific version number, so we should update bedrock's local dependencies to fix the warning, as opposed to wait for a fix downstream (see https://github.com/webpack-contrib/terser-webpack-plugin/issues/506).
I did this locally by running `rm -rf node_modules package-lock.json && npm install` in the root directory.
https://github.com/mozilla/bedrock/security/dependabot/26

Update transive dependencies in package-lock.json

---

.eslintrc.js
bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
bedrock/newsletter/templates/newsletter/recovery.html
bedrock/newsletter/tests/test_views.py
bedrock/newsletter/views.py
media/css/newsletter/newsletter-opt-out-confirmation.scss
media/css/newsletter/newsletter-recovery.scss
media/js/newsletter/form-utils.es6.js
media/js/newsletter/recovery-init.es6.js
media/js/newsletter/recovery.es6.js
media/static-bundles.json
tests/functional/newsletter/test_newsletter_recovery.py
tests/pages/newsletter/recovery.py
tests/unit/karma.conf.js
tests/unit/spec/base/fxa-form.js
tests/unit/spec/base/fxa-link.js
tests/unit/spec/base/mozilla-banner.js
tests/unit/spec/base/mozilla-pixel.js
tests/unit/spec/base/send-to-device.js
tests/unit/spec/base/site.js
tests/unit/spec/base/stub-attribution.js
tests/unit/spec/newsletter/form-utils.js
tests/unit/spec/newsletter/recovery.js

Migrates the newsletter recovery form from Python to JS, which now posts directly to Basket.
Did I miss any edge cases that were in the back-end code?
#11963
- http://localhost:8000/en-US/newsletter/recovery/
- http://localhost:8000/en-US/newsletter/opt-out-confirmation/

Newsletter recovery page should post directly to basket (Fixes #11963)

---

bedrock/firefox/templates/firefox/browsers/mobile/get-ios.html

Updated link in the `get-ios` page to be the correct universal Adjust link
https://github.com/mozilla/bedrock/issues/12055

Update get-ios Adjust link

---

bedrock/firefox/templates/firefox/family/includes/modules/public-wifi.html
media/css/firefox/family/components/modules/_public-wifi.scss

Cleans up and finalizes responsive styling for public wifi section
[scroll-snap-align](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-align) is a newer property meant to enhance scrolling experience by allowing a "snap" to a particular alignment after the user stops scrolling, will be ignored and regular scroll behaviour used for browsers without support
Because this is built from the feature branch, it only shows changes from the existing files. Best to review the entire html & css files for public-wifi.
figma: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families
On large screens and above, on browsers that support grid
- Yellow card in first column and white cards in second column
Below large screen
- Yellow …

Style public wifi section

---

bedrock/privacy/templates/privacy/data-preferences.html
bedrock/privacy/urls.py
docs/analytics.rst
l10n/en/brands.ftl
l10n/en/privacy/data-preferences.ftl
media/js/privacy/data-preferences-cookie.es6.js
media/js/privacy/data-preferences-init.es6.js
media/static-bundles.json
tests/unit/karma.conf.js
tests/unit/spec/privacy/data-preferences-cookie.js

- Updates Glean opt-out page so that it will work for other `*.mozilla.org` websites.
- Opens up page for L10n.
- Adds `disabled` properties to opt-out buttons to improve UX a little.
- Improves test coverage.
#12056
Demo: https://www-demo5.allizom.org/en-US/privacy/websites/data-preferences/
http://localhost:8000/en-US/privacy/websites/data-preferences/

Make data privacy prefs page work across '.mozilla.org' domains (Fixes #12056)

---

media/js/privacy/data-preferences-cookie.es6.js
tests/unit/spec/privacy/data-preferences-cookie.js

Fixes an issue whereby trying to opt back in to data collection fails, if the previous cookie specified `www.mozilla.org` as the domain and not `.mozilla.org`.
#12056
This is not so easy to test manually as it relies on behaviour that only takes effect in production, but I added a JS test that should hopefully give enough confidence that the change works.
I'll test this manually on stage / prod also as we deploy.
http://localhost:8000/en-US/privacy/websites/data-preferences/

Also clear preference cookies that specify www.mozilla.org sub domain (issue #12056)

---

media/css/firefox/family/components/modules/_mental-health.scss

Add responsive styling for Mental Health section
figma: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families
http://localhost:8000/en-US/firefox/family/#mental-health

Add responsive styling for Mental Health section

---

bedrock/firefox/templates/firefox/family/index.html
media/css/firefox/family/_utils.scss
media/css/firefox/family/components/_subnav.scss
media/css/firefox/family/components/_typography.scss
media/css/firefox/family/components/modules/_bullying.scss
media/css/firefox/family/components/modules/_passwords.scss
media/css/firefox/family/components/modules/_privacy.scss
media/css/firefox/family/styles.scss
media/js/firefox/family/subnav.js
media/static-bundles.json

Style fixes for subnav and sections
- copy/pasted subnav and added a t-firefox-family container class
- changed subnav collapse/expand breakpoint to 950 and reset float/display styles below that
- added black border bottom to sections that needed it
- changed scope for typography styles to fix subnav vertical alignment
figma: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families
http://localhost:8000/firefox/family/
privacy, bullying, and password sections should have underline
nav should be properly center aligned and collapse at 950px

Fix subnav, add dividers

---

bedrock/firefox/templates/firefox/developer/whatsnew-mdnplus.html
media/css/firefox/developer/whatsnew-mdnplus.scss
media/js/firefox/developer/whatsnew-mdnplus.js
media/static-bundles.json

The Dev Edition WNP promoting MDN Plus features an animated graphic in the header which is fairly processor-intensive. Since the page opens automatically upon updating, this can sometimes happen in the background or in an inactive tab taxing CPU without a user being aware of what's causing it.
This updates the animation to only trigger when the page is visible, and when it is visible the animation automatically stops after five minutes (note that switching away from the tab and back will reset that timer because it restarts the animation).
#11793 
http://locahost:8000/firefox/105.0a2/whatsnew/

Dev WNP, only animate mandala when visible [#11793]

---

bedrock/firefox/templates/firefox/family/includes/dad-jokes-banner.html
media/css/firefox/family/_utils.scss
media/css/firefox/family/components/_agreement.scss
media/css/firefox/family/components/_dad-jokes-banner.scss
media/js/firefox/family/banner-init.es6.js
media/js/firefox/family/banner.es6.js
media/static-bundles.json

Adds styling and functionality to dad jokes banner
- Updates copy
- Does not show banner if js is disabled
figma: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families?node-id=100%3A1597
**with JS**
on scroll, banner fades in 
on banner click, banner fades out
**without JS**
no banner
Design feedback: keep banner extending full width of page at all screen sizes, slow down fade in (original transition 500ms, increased to 1000ms)

Style dad jokes and add banner functionality

---

bedrock/firefox/templates/firefox/family/includes/modules/passwords.html
media/css/firefox/family/components/_blurb.scss
media/css/firefox/family/components/modules/_passwords.scss

Finishes responsive styling for Passwords section
figma: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families?node-id=971%3A2714
This builds on styling from feature branch. Please review entire css and html files for passwords module.
http://localhost:8000/en-US/firefox/family/#passwords
design feedback
- On mobile, email in password section breaks to next line
- On mobile: Shadow behind log-in box looks incorrect on mobile (separates)

Style passwords section

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-de-coupon.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-de.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-en-coupon.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-en.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-fr-coupon.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-fr.html

Updates WNP 104 templates to use `vpn_product_referral_link()` for the main CTA.
#12088
Test with `SWITCH_FIREFOX_104_WHATSNEW_VPN_COUPON_EN` and `SWITCH_FIREFOX_104_WHATSNEW_VPN_COUPON_FRDE` both `on` and `off`:

Fix WNP 104 referrals for VPN (Fixes #12088)

---

bedrock/firefox/templates/firefox/family/includes/download-firefox.html
bedrock/firefox/templates/firefox/family/includes/modules/passwords.html
bedrock/firefox/templates/firefox/family/includes/modules/privacy.html
bedrock/firefox/templates/firefox/family/includes/modules/private-mode.html
bedrock/firefox/templates/firefox/family/includes/subnav.html
bedrock/firefox/templates/firefox/family/index.html
media/css/firefox/family/components/_download-firefox.scss
media/js/firefox/family/banner.es6.js
media/js/firefox/family/fx-is-default.js
media/static-bundles.json

Adds F3 analytics and updates `mozilla.com` to `example.com` in passwords section
No issue, follow up from[ feature PR](https://github.com/mozilla/bedrock/pull/12086)
- all external links have utm params, all subnav links have gtm data
- email in passwords section is now using `example.com`
- CTA conditionals work in download section (tests are coming in the [fast-follow issue](https://github.com/mozilla/bedrock/issues/12091))
- if not on Firefox, download Firefox CTA
- if on Firefox but not default, default Firefox CTA
- if on Firefox and default, mobile Firefox CTA

F3 landing page fixes

---

bedrock/newsletter/templates/newsletter/country_success.html
bedrock/newsletter/templates/newsletter/fxa-error.html

I discovered a couple of rogue URLs that I missed in #11963. This PR updates / fixes those URLs to extend `newsletter/base` rather than `newsletter/recovery`, since they have no form and only display simple messages.
#11963
- http://localhost:8000/en-US/newsletter/fxa-error/
- http://localhost:8000/en-US/newsletter/country/success/

Fix newsletter country success / fxa error URLs (Issue #11963)

---

media/css/firefox/family/styles.scss
tests/functional/firefox/family/test_family.py
tests/pages/firefox/family/landing.py

This avoids confusion with the primary goal of the page: to get users to download firefox or make it their default
slack request from Mary O'Regan
In Firefox, no nav CTA
In non-Firefox, "Download Firefox" CTA
local testing
`py.test --base-url http://localhost:8000 --driver Chrome tests/functional/firefox/family`
`py.test --base-url http://localhost:8000 --driver Firefox tests/functional/firefox/family`

Hide nav CTA on /firefox/family for Firefox users

---

bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
l10n/en/navigation_v2.ftl

Removed the link, and deleted its string in respective `.ftl` file.
https://github.com/mozilla/bedrock/issues/12103

Remove "More Mozilla Innovation" link from main nav

---

bedrock/firefox/redirects.py
tests/redirects/map_globalconf.py

Added the needed redirect. Also ran the test to make sure its well tested
#12107

Added `/firefox/families` redirect for F3

---

media/css/firefox/family/components/_download-firefox.scss

Downsizes the heart and pulls in the words on either side for spacing to more closely match figma
figma: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families?node-id=1799%3A8474
Download section is below Public Wifi: http://localhost:8000/en-US/firefox/family/#public-wifi

F3 design feedback: fix heart sizing and spacing

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2022.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
bedrock/mozorg/urls.py
bedrock/privacy/templates/privacy/notices/ad-targeting-guidelines.html
bedrock/privacy/urls.py
bedrock/privacy/views.py

Adds H1 2022 transparency report, and a new privacy notice detailing Mozilla's policy on targeted advertising.
This needs to go live on **Tuesday Sept 13th**, so labelling as a P1.
#12057
Note: you may need to update legal docs locally to render the new ad-targeting-guidelines notice.
- http://localhost:8000/en-US/about/policy/transparency/
- http://localhost:8000/en-US/about/policy/transparency/jan-jun-2022/
- http://localhost:8000/en-US/privacy/ad-targeting-guidelines/

Add transparency report H1 2022 (Fixes #12057)

---

media/css/firefox/family/components/_agreement.scss

Updates agreement CTA font size to match download section CTA font size, moves agreement cta centering to start mobile-first
http://localhost:8000/en-US/firefox/family/#agreement

Update agreement cta sizing and mobile alignment

---

media/css/firefox/family/components/_news-ticker.scss

Fix from design feedback
ticker is available below hero when there is no reduced motion preference
font size 16px
increases at medium breakpoint to 18px

Reduce ticker font size on mobile

---

media/css/firefox/family/_utils.scss

Matches figma offset more closely
affects both card and browser component shadows
note: this will create merge conflict with https://github.com/mozilla/bedrock/pull/12125
desktop shadow should be larger to match figma: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families?node-id=1799%3A8474
mobile shadow should be reduced
[http://localhost:8000/en-US/firefox/family](http://localhost:8000/en-US/firefox/family)

Fix shadow offset sizing

---

media/css/firefox/family/components/_browser.scss
media/css/firefox/family/components/modules/_mental-health.scss

Adjust grid rows to better show doomscroll text
Update dimensions of doomscroll container to match figma
http://localhost:8000/en-US/firefox/family/#mental-health

Reduce bottom spacing on browser container content

---

bedrock/firefox/templates/firefox/mobile/get-app.html
bedrock/firefox/tests/test_helpers.py
bedrock/firefox/urls.py
bedrock/settings/base.py

Removes outdated send-to-device experiment variations
https://github.com/mozilla/bedrock/issues/12159
http://localhost:8000/en-US/firefox/mobile/get-app/

Remove /mobile/get-app/ experiment variations (Fixes #12159)

---

bedrock/privacy/templates/privacy/notices/base-notice.html

Fix Monitor Terms & Privacy title 
#12129 
Demo server URL: http://localhost:8000//en-US/privacy/firefox-monitor/

Fix Monitor Terms & Privacy title (Fixes #12129)

---

bedrock/firefox/templates/firefox/family/includes/download-firefox.html
media/css/firefox/family/components/_download-firefox.scss

Break line after heart on mobile only in download firefox section
download section is under public wifi
http://localhost:8000/en-US/firefox/family/#public-wifi

Break download heading on mobile

---

media/css/firefox/family/components/_news-ticker.scss

Updates ticker to only show motion to users on modern enough browser that motion pref is supported (https://github.com/mozilla/bedrock/pull/12086#discussion_r962023816)
With reduced motion preference or on [old browser](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#browser_compatibility), ticker doesn't show
With no pref, ticker does show

Move ticker into no-pref motion query

---

bedrock/firefox/templates/firefox/family/includes/modules/private-mode.html

Original statement was too broad as some data can still be collected by websites in private mode
https://github.com/mozilla/bedrock/issues/12150
http://localhost:8000/en-US/firefox/family/#private-mode
updates copy to say "private browsing can make it harder for advertisers to track your kid"

Update copy for private mode

---

bedrock/base/templates/macros.html

Simply fixed the erroneous for attribute on the Your Firefox Account form on [privacy/products/](https://www.mozilla.org/en-GB/about/this-site/).
This was causing an a11y issue on the page.
N/A
If relevant:

Fix label for the Your Firefox Account form on privacy/products

---

.circleci/config.yml

As of 5 Oct, our CI pipeline started seeing test errors unrelated to code changes in _any_ particular PR. These failures were not replicable locally (bare metal MacOS, or via Docker) and were not replicable via a SSH session to CircleCI, despite using the same images that had just failed.
My theory is that there is something about how Bedrock interacts with the 3.9.14 version of Python in the Circle container that causes the very odd failures (eg Mocks not returning the expected values). We will continue to explore this, but this changeset downpins us to using an earlier cut of Circle's Python 3.9 image, which we know works. The vulnerabilities fixed in 3.9.14 seem to pose a low risk, given that we are not building production images here, and the actual Bedrock Docker images are using …

Specify a downpinned version of the CircleCI image to avoid CI failures

---

bedrock/pocket/templates/pocket/base.html
bedrock/pocket/templates/pocket/home.html
l10n-pocket/en/pocket/home.ftl

Small fixups noted while QAing Pocket on Bedrock

Pocket mode fixups

---

media/js/pocket/google-analytics.js
media/static-bundles.json

Adds ga to pocket base template (ga script taken from [existing pocket-marketing-pages script](https://github.com/mozmeao/pocket-marketing-pages/blob/master/content/_includes/scripts.njk))
Inspect head element. Analytics script should appear near bottom.

Add pocket google analytics

---

bedrock/firefox/templates/firefox/testflight.html
bedrock/newsletter/templates/newsletter/includes/form.html
bedrock/products/templates/products/vpn/invite.html
media/js/newsletter/newsletter.es6.js
tests/unit/spec/newsletter/newsletter.js
tests/unit/spec/products/vpn/invite.js

We're seeing a small amount of errors in Sentry due to newsletter submissions posting the old `fmt` parameter instead of the new `format` one, which was changed as part of https://github.com/mozilla/bedrock/issues/11944.
This PR updates the form HTML to use `name="format"` as well, should someone try to submit the form with JS disabled.
#11944
I pushed this up on demo for easier testing: https://www-demo5.allizom.org/en-US/

Rename 'fmt' to 'format' in newsletter template (Issue #11944)

---

bedrock/pocket/templates/pocket/android.html
bedrock/pocket/templates/pocket/ios.html
bedrock/pocket/templates/pocket/platform-pages.html
bedrock/pocket/templates/pocket/welcome.html
l10n-pocket/en/pocket/platforms.ftl
media/css/pocket/components/platforms.scss

This changeset adds in a link to the Pocket bookmarklet for browsers, which slipped through the net in the main port.
Template amended, new CSS rule added  - tested locally. Hyperlink has rollover state with underline
(Compare with https://getpocket.com/en/chrome/)
`npm run in-pocket-mode` to start things up right
Confirm bookmarklet link appears below CTA button for
* http://localhost:8080/en/chrome/
* http://localhost:8080/en/safari/
* http://localhost:8080/en/edge/
* http://localhost:8080/en/opera/
... and ultimately links to a sensible destination page (`/add` )
And does NOT appear for
* http://localhost:8080/fr/chrome/
* http://localhost:8080/es/safari/
* http://localhost:8080/it/edge/
* http://localhost:8080/pt-BR/opera/
because it hasn't been localised just yet
And does not appear …

Add Bookmarklet link to Pocket browser pages (only)

---

bedrock/firefox/templates/firefox/welcome/page14.html
tests/functional/firefox/welcome/test_welcome_page14.py
tests/pages/firefox/welcome/page14.py

Fixes 500 error on https://www-dev.allizom.org/en-US/firefox/welcome/14/
https://sentry.io/organizations/mozilla/issues/3671860684/?alert_rule_id=10555963&alert_timestamp=1665774510814&alert_type=email&environment=production&project=6260211&referrer=alert_email
http://localhost:8000/en-US/firefox/welcome/14/
```
py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/firefox/welcome/test_welcome_page14.py
```

Fix 500 error on /firefox/welcome/14/

---

bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
l10n/en/navigation_v2.ftl

Added a link in the "Who we are" section of global navigation
#12101 
Demo server URL: https://localhost:8000 
- Link should navigate to mozilla.org/stories

Add link for Stories to global nav (Fixes #12101)

---

bedrock/pocket/templates/pocket/contact-info.html

Nano-sized fix. Noticed the link to press from /contact-info was wrong. Swapping in a link that works, with Pocket's blessing.

Update link to Pocket's press page

---

bedrock/firefox/templates/firefox/releases/nightly-feed.xml

Whitespace before the XML declaration isn't allowed. Feed readers using a strict XML parser won't load the feed.
Current state: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Fnightly%2Fnotes%2Ffeed%2F
- Use the W3C's feed validator: https://validator.w3.org/feed/

Fix Firefox Nightly Atom feed to start with XML declaration

---

tests/functional/test_contact.py

Fixes functional test for contact pages since the Portland office was deleted.
`py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/test_contact.py`

Fix contact functional test

---

bedrock/pocket/templates/pocket/includes/mobile-nav.html
bedrock/pocket/templates/pocket/includes/nav.html
bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
l10n-pocket/en/nav.ftl
tests/functional/pocket/test_navigation.py
tests/pages/pocket/base.py

This changeset is designed to match in-app wording change for main Pocket, where My List will be rephrased as Saves.
The switchover is scheduled for 31 October, but we need to get a new string ("Saves") translated before then, so getting the changes in to main now, behind a switch, lets us move ahead now and test what we can.
The wording and URL change is overseen by a switch, which has NOT yet been added to `www-config`.
`SWITCH_POCKET_RENAME_MY_LIST_TO_SAVES`
A follow-up task is required to clean this up after go-live. It would have been possible to do this without switches (add the new fluent string now, get it translated in Smartling, then swap it in), but switches give us extra latitude.
NOT IN THIS PR: there's also an image change needed for the homepage, to replace the mocked-up …

Pocket: update /my-list and "My List" to /saves and "Saves"

---

bedrock/legal/urls.py
bedrock/privacy/views.py

Updates Hubs legal docs sources to point to new markdown files.
**Do not merge until Oct 25**
#12260
Run `./manage.py update_legal_docs`
- http://localhost:8000/en-US/privacy/hubs/
- http://localhost:8000/en-US/about/legal/terms/hubs/

[Oct 25] Update Hubs privacy/legal notices (Fixes #12260)

---

bedrock/products/tests/test_helper_misc.py
bedrock/settings/base.py

The VPN product team need to update the price IDs for the VPN / Relay bundle as below.
#11781

Update VPN & Relay bundle IDs (Issue #11781)

---

bedrock/pocket/templates/pocket/contact-info.html
bedrock/pocket/templates/pocket/get-inspired.html
bedrock/pocket/templates/pocket/jobs.html
bedrock/pocket/templates/pocket/pocket-and-firefox.html
bedrock/pocket/templates/pocket/privacy.html
bedrock/pocket/templates/pocket/save-to-pocket.html
bedrock/pocket/templates/pocket/tos.html

Pages that import the nav need a corresponding nav JS block
NO BUG
live pages are missing mobile nav JS bundle: https://getpocket.com/en/contact-info/
local pages should be working as expected `npm run in-pocket-mode`
http://localhost:8000/en/contact-info/
http://localhost:8000/en/get-inspired/
http://localhost:8000/en/jobs/
http://localhost:8000/en/pocket-and-firefox/
http://localhost:8000/en/privacy/
http://localhost:8000/en/save-to-pocket/
http://localhost:8000/en/tos/

Pocket: fix mobile nav JS

---

Dockerfile

Tune docker file to cache better, speeding up local rebuilds
When we added in Glean support to our app image, some instructions with rarely-changing results were added lower down the Dockerfile than ideal. So we're moving them up to allow more layers to be re-used
Resolves #11887
Demo server URL: https://www-demo3.allizom.org/

Improve cacheing of layers in Dockerfile re Glean setup

---

bedrock/base/templates/404-locale.html
bedrock/firefox/tests/test_views.py
bedrock/mozorg/context_processors.py
bedrock/newsletter/tests/test_views.py
bedrock/urls/mozorg_mode.py
lib/l10n_utils/__init__.py
lib/l10n_utils/tests/test_base.py
lib/l10n_utils/tests/test_files/templates/404-locale.html
media/css/mozorg/locales.scss
tests/functional/conftest.py
tests/functional/test_experiment_pages.py
tests/functional/test_generated_pages.py
tests/redirects/base.py

Return locale selection page at root URL if no header sent
Test home page with various accept-language headers and lack of header.
#11538

Return locale selection page at root URL if no header sent

---

media/css/products/vpn/components/block.scss

Removes empty space at the end of Relay wordmark.
https://github.com/mozilla/bedrock/issues/12317
Note: you may need to update local translations to see the issue
- http://localhost:8000/de/products/vpn/?geo=us

Fix Firefox Relay wordmark alignment for l10n (Fixes #12317)

---

bedrock/base/templates/macros-protocol.html
bedrock/mozorg/templates/mozorg/about/index.html
bedrock/mozorg/templates/mozorg/home/home-de.html
bedrock/mozorg/templates/mozorg/home/home-fr.html
bedrock/mozorg/templates/mozorg/home/home.html
docs/coding.rst

Removed the image macro for the protocol Billboard macro to simplify the logic that exists inside the Billboard macro. The change will require that an `image` argument is passed using one of the existing python image helpers instead of the `image` macro.
#12190 
To test this works:
Check the following pages that the billboard element matches what is on production

Remove image macro from billboard macro

---

bedrock/products/templates/products/vpn/resource-center/landing.html
tests/functional/products/vpn/test_resource_center.py
tests/pages/products/vpn/resource_center.py

This will help keep an eye on the Contentful-powered VRC listing page post-rollout. 
However it's not foolproof because if the page breaks due to bad data, that might be triggered many minutes/hours after the tests are run.
If relevant:

Add light smoke/integration test for the VRC landing page to confirm it's OK

---

media/css/pocket/components/about.scss

Updated the line height for pocket/{locale}/about to fix a visual bug in the heading when the letter j is used
This is more of a band-aid, but not sure how to deal with this as it could pop up in others areas. Do we change line-height for all heading elements that use that font family?
#12265 
start server in pocket mode (you may have to run `manage.py l10n_update` to update the strings)

Pocket mode: improve line spacing of headers

---

docs/install.rst

👋 This is just a small documentation fix, so hopefully should be quick. GitHub no longer supports the `git://` protocol for cloning, this will fail. Instead, use the HTTPS protocol. See the [GitHub blog post](https://github.blog/2021-09-01-improving-git-protocol-security-github/) for more information.

Use https: protocol instead of deprecated git: protocol

---

lib/l10n_utils/__init__.py
lib/l10n_utils/tests/test_base.py

This avoids showing users the "choose locale" page even for unsupported locales, defaulting back to our previous behavior of redirecting to `en-US` pages.
#12328

Update strict redirect to consider accept-language header

---

bedrock/pocket/templates/pocket/includes/footer.html
media/css/pocket/components/new-tab-learn-more.scss

Fixes broken style on the new tab learn more page and updates the year in the footer
http://localhost:8000/en/firefox/new_tab_learn_more/

Fix broken styles in /new-tab-learn-more

---

bedrock/firefox/templates/firefox/new/desktop/download.html

Acronyms aren’t pluralized with “s” in French.
https://bugzilla.mozilla.org/show_bug.cgi?id=1799474
http://localhost:8000/fr/firefox/new/

Fix French string on /new page [bug #1799474]

---

bedrock/base/templates/macros-protocol.html
bedrock/contentful/templates/includes/contentful/all.html
bedrock/firefox/templates/firefox/features/tips/tips.html
bedrock/firefox/templates/firefox/more.html
bedrock/firefox/templates/firefox/pocket.html
bedrock/foundation/templates/foundation/annualreport/2020/index.html
bedrock/mozorg/templates/mozorg/about/index.html
bedrock/mozorg/templates/mozorg/diversity/2021/beyond-products.html
bedrock/mozorg/templates/mozorg/diversity/2021/index.html
bedrock/mozorg/templates/mozorg/diversity/2021/what-we-build.html
bedrock/mozorg/templates/mozorg/diversity/2021/who-we-are.html
bedrock/mozorg/templates/mozorg/moss/index.html
bedrock/newsletter/templates/newsletter/updated.html
docs/coding.rst

This PR removes the `image` macro from the protocol card macro and replaces it with a single `image` argument where we can pass an image using one of the image helpers
#12300 
The following pages had the call to card updated:
To test this works:

Remove image from card macro (Fixes #12300)

---

bedrock/firefox/templates/firefox/whatsnew/includes/fx107/vpn-shopping.svg
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx107-en.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
media/css/firefox/whatsnew/whatsnew-107-en.scss
media/js/firefox/whatsnew/whatsnew-107-en.js
media/static-bundles.json

Adds the English what's new page for Firefox 107 (I'm not sure if the EU team wants a different page shown in the UK, but I'm assuming for now this one is for all Englishes and not just US and CA). @maureenlholland is working on the EU pages.
#12229 
http://localhost:8000/en-US/firefox/107.0/whatsnew/

Add English WNP for Firefox 107 [fix #12229]

---

media/css/pocket/components/about.scss

Fixes overlap on awkward breakpoint
https://github.com/mozilla/bedrock/issues/12371
https://getpocket.com/en/about/ around 570px wide

Fix Pocket about illustration overlap (fixes #12371)

---

bedrock/base/templates/includes/banners/fundraiser.html
media/css/base/banners/fundraiser.scss

Changes the form action so it submits to the campaign page on donate.mozilla.org rather than the front page. 
Also makes some small style tweaks because in languages where the submit button label is more than one word it tends to wrap and look wonky, and/or causes some overflow issues.
#12373 
Make sure the form submits to `https://donate.mozilla.org/help-mozilla-fight-for-a-better-internet-this-holiday-season/` and that the form on the other end still reflects the right selections.

Fix fundraising banner destination

---

bedrock/careers/feeds.py

This pre-sorts the list so `groupby` can find the groupings of the jobs by `internal_job_id`.

Fix #12398: Fix grouping of jobs in RSS feed

---

bedrock/contentful/models.py
bedrock/sitemaps/tests/test_utils.py
bedrock/sitemaps/utils.py

This changeset stops ContentfulEntry records with incomplete localisation status from appearing in the sitemap
If they do, they create URLs with a slug of `.../unknown/`, which then 404s so can't be spidered by the sitemap generator

Fix sitemap generation due to incompletely localised Contentful objects appearing

---

bedrock/newsletter/templates/newsletter/country.html
tests/unit/spec/newsletter/country.js

Small follow up bug fix for https://github.com/mozilla/bedrock/pull/12421
The page is `en-US` only and has no FTL file associated with it, so the error string should be hard-coded.
#12376
You need a newsletter token in order to view / test this page locally, which you can [get here](https://www.mozilla.org/en-US/newsletter/recovery/). Once you have a token you can view the page at:
`http://localhost:8000/en-US/newsletter/country/{TOKEN}/`

Fix error string on newsletter/country/ page (Issue #12376)

---

bedrock/mozorg/templates/mozorg/home/includes/pocket-best-2022-promo.html

We were previously given the incorrect link for German best of pocket collection. This updated URL should fix things

Fix Best of Pocket link for German (Issue #12406)

---

bedrock/mozorg/templates/mozorg/about/leadership/index.html

Fixes https://gitlab.com/mozmeao/www-config/-/jobs/3395498449
The reason for the failure was Eric's surname was misspelt in the `data-id` attribute, so it was not matching up to `id`.
The test failure report gave the clue:

Fix intermittent test failure on /leadership page

---

Makefile
docs/install.rst

This changeset adds `make preflight` as a new Makefile command so it just takes one command to bring a local install up to latest state.
* installs latest Python deps
* installs latestJS deps
* gets latest DB and l10n files

Add 'make preflight' command to make it easier to keep local installs ready for work

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Resolves #12418 Bump phonenumberslite from 8.13.0 to 8.13.1 in /requirements 
Resolves #12417 Bump boto3 from 1.26.3 to 1.26.17 in /requirements 
Resolves #12413 Bump sentry-sdk from 1.10.1 to 1.11.1 in /requirements 
Resolves #12396 Bump twilio from 7.15.1 to 7.15.3 in /requirements 
Resolves #12364 Bump pygithub from 1.55 to 1.57 in /requirements 
Resolves #12362 Bump apscheduler from 3.9.1 to 3.9.1.post1 in /requirements

Dependency updates

---

media/css/mozorg/contribute.scss

Sets overflow-wrap to break words that would otherwise overflow container.
https://github.com/mozilla/bedrock/issues/12343

Contribute card fix overflow (fixes #12343)

---

bedrock/security/templates/security/bug-bounty/web-eligible-sites.html

add instruction to use staging instance when testing crash-stats.

add instruction to use staging instance when testing crash-stats

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

This changeset upgrades Bedrock to Markdown 3.4, which had breaking changes in it that required patching the mdx_outline library (which we've forked). 
We're still using our fork of mdx_outline, so have just made it work with 3.4.x as a potentially breaking change, rather than also support <3.4
Resolves #11936 (dependabot PR)
If relevant:

Update Markdown to 3.4.1, using related change/bump to mdx_outline

---

bedrock/careers/management/commands/sync_greenhouse.py
bedrock/careers/tests/test_commands.py

The Greenhouse API started sending `metadata: null` for a job, rather than the expected `metadata: []`. This works around this so it can accept either and still complete the import.

Make greenhouse metadata checking more resilient

---

media/js/newsletter/unsubscribed.es6.js
tests/unit/spec/newsletter/unsubscribed.js

Small bug fix for https://github.com/mozilla/bedrock/pull/12448
Prevents the form trying to POST to basket if the token is invalid / empty.
This scenario shouldn't normally happen, unless someone manually / accidentally alters the URL.
#12377
You need a newsletter token in order to view / test this page locally, which you can [get here](https://www.mozilla.org/en-US/newsletter/recovery/). Once you have a token you can view the page at:
`http://localhost:8000/en-US/newsletter/updated/?unsub=1&token={TOKEN}`

Newsletter /updated page should not POST when token is empty (Issue #12377)

---

bedrock/products/views.py
tests/functional/products/vpn/test_landing.py
tests/pages/products/vpn/landing.py

Removes the VPN / Relay bundle feature switch (now that it has launched), and adds functional tests to make sure the button shows in the right countries.
#12424
```
py.test --base-url http://localhost:8000 --driver Firefox --html tests/functional/results.html tests/functional/products/vpn/test_landing.py
```

Add functional tests for VPN / Relay bundle offer (Fixes #12424)

---

requirements/dev.txt
requirements/docs.in
requirements/docs.txt
requirements/prod.in
requirements/prod.txt

Bumps dependencies, incl a security fixup due to a SSL Certificate Authority being revoked - [source](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ)
#12454 Bump certifi from 2021.10.8 to 2022.12.7 in /requirements - security 
#12446 Bump twilio from 7.15.3 to 7.15.4 in /requirements \
#12445 Bump boto3 from 1.26.17 to 1.26.22 in /requirements

Dependency updates, incl security bump

---

bedrock/mozorg/templates/mozorg/about/history.html
l10n/en/mozorg/about/history.ftl

The situation is that the History of Mozilla Project (https://www.mozilla.org/en-US/about/history/) links to a page that currently shows access denied (an air Mozilla link). 
The missing link is Code Rush by David Winton, which according to Wikipedia, is licensed under a CC 3.0 US License: https://en.wikipedia.org/wiki/Code_Rush 
There is an youtube version which is active and provided by The Documentary Network: https://www.youtube.com/watch?v=4Q7FTjhvZ7Y which is the one I have used in the patch. 
Keep in mind that I am not familiar with Fluent.

Link on The History of Mozilla goes to an access denied webpage

---

bedrock/firefox/templates/firefox/whatsnew/includes/header.html
l10n/en/firefox/whatsnew/whatsnew.ftl

Updates a string on the WNP that's shown when someone's Firefox browser is out of date to include a SUMO help link.
#12444
You may need to use an out of date Firefox confirm the fix looks as expected, but I've also included a screenshot below.
http://localhost:8000/en-US/firefox/whatsnew/

Add SUMO link to /whatsnew page update notification (Fixes #12444)

---

bedrock/base/templates/404-locale.html

Sets `page_title` and `page_desc` to match the English [home page](https://www.mozilla.org/en-US/) when the `404-locale.html` template is served at the site root.
#12468
To test this locally, first remove all languages from your browser settings:

Update meta data on home page when 'Choose your own language' is displayed (Fixes #12468)

---

bedrock/firefox/templates/firefox/privacy/index.html
l10n/en/firefox/privacy-hub.ftl

Removes an outdated link from the firefox/privacy page.
#12469
http://localhost:8000/en-US/firefox/privacy/

Remove outdated Wiki link from firefox/privacy page (Fixes #12469)

---

package-lock.json
package.json

Bumps `@sentry/browser` to latest version.
N/A
Set `SENTRY_FRONTEND_DSN=https://c3ab8514873549d5b3785ebc7fb83c80@o1069899.ingest.sentry.io/6260331` in your `.env` if you would like to test this locally.

Bump @sentry/browser to v7.25.0

---

docs/contentful.rst

Updates docs to explain some extra steps needed if you want to preview a new sandbox content type
no bug
in `/docs` locally, run `make livehtml` and check
http://127.0.0.1:8100/contentful.html#how-to-preview-your-changes-on-localhost

Update contentful preview docs

---

bedrock/base/templates/404-locale.html

Removes duplicate "Mozilla" in page title
https://github.com/mozilla/bedrock/issues/12488
To test this locally, first remove all languages from your browser settings:

Remove duplicate Mozilla from home page title (Fixes #12488)

---

media/js/careers/listings/filters.es6.js
tests/unit/spec/careers/filters.js

The trailing commas in the listings template were accidentally removed in https://github.com/mozilla/bedrock/commit/3ed13e3fb87c572e2d5ffe814eda192c5c336624#diff-6008798ac860c68d377519dacb7c71d769dd9b7a04bd10aed6f17b69b08033ce
This PR removes the reliance on them in the template, by updating the logic in the page's JS instead.
#12490

Fix careers listings filtering (Fixes #12490)

---

bedrock/pocket/templates/pocket/add.html
bedrock/pocket/templates/pocket/base-platform.html
bedrock/pocket/templates/pocket/firefox/new-tab-learn-more.html
bedrock/pocket/templates/pocket/get-inspired.html
bedrock/pocket/templates/pocket/home.html
bedrock/pocket/templates/pocket/pocket-and-firefox.html
bedrock/pocket/templates/pocket/save-to-pocket.html

Updates split macro image syntax for pocket pages.
Apologies for the diff - the changes are actually much smaller, but I did some white space / indentation fixes whilst I was here.
#12331
Run  `npm run in-pocket-mode`

Remove image macro use from split macro (pocket) (Issue #12331)

---

bedrock/careers/templates/careers/includes/testimonials.html

Removed a typo in the testimonials section:
`Mozilla is a special place that is truly cares about the people who work here…` 
👇🏽 to 
`Mozilla is a special place that truly cares about the people who work here… `

Fix typo in Careers testimonials section

---

bedrock/firefox/templates/firefox/browsers/index.html
l10n/en/firefox/browsers.ftl

Updates page title and description as per copy in the issue linked below.
https://github.com/mozilla/bedrock/issues/12486

Update firefox/browsers page title and desc (Fixes #12486)

---

webpack.config.js

This is a small test to see if specifying the IPv4 address of the Python server fixes #12508 for me 🤞 
#12508 
`npm start`

Force client proxy server to use IPv4 (Issue #12508)

---

bedrock/mozorg/forms.py
bedrock/mozorg/templates/mozorg/emails/meico-email.txt
bedrock/mozorg/tests/test_views.py
bedrock/mozorg/urls.py
bedrock/mozorg/views.py
bedrock/press/tests/test_base.py

Add a view to process email requests from MEICO forms.

Add email processing view for meico form

---

bedrock/mozorg/templates/mozorg/santa-locator.html
media/css/mozorg/santa-locator.scss

- Changes till to 'til
- Converts tabs to spaces (tabs got pasted from whatever StackOverflow post I copied)

Grammar and linting fixes for Santa Locator page

---

.gitignore
.vscode/extensions.json

Adds a list of recommended VSCode extensions for bedrock development.
#12515
VS Code prompts a user to install the recommended extensions when a workspace is opened for the first time. The user can also review the list with the `Extensions: Show Recommended Extensions` command.

Add recommended extensions for VSCode (Fixes #12515)

---

bedrock/base/templates/macros-protocol.html
bedrock/careers/templates/careers/diversity.html
bedrock/careers/templates/careers/includes/footer.html
bedrock/firefox/templates/firefox/browsers/mobile/android.html
bedrock/firefox/templates/firefox/privacy/book.html
bedrock/mozorg/templates/mozorg/home/includes/mr2-promo-eu.html
docs/coding.rst

Instead of passing lots of parameters through multiple macros in order to construct an image, `split()` now just takes a single `image` parameter. This can be a `resp_img()`, a `picture()`, a simple `<img>`, an inline SVG, or anything calling the template wants.
#12331

Simplify split() macro image handling (Fixes #12331)

---

bedrock/releasenotes/models.py
bedrock/releasenotes/tests/test_models.py

**Not critical, so marking as Do Not Merge until after the code freeze**
This changeset:
1) Fixes a bug in our bleaching of release notes
2) adds support for transforming `~~` into `<del>`
Please check the logic of the change made to `render_markdown` (the first commit in this PR) in case I'm overlooking something and introducing a subtle regression
Resolves https://github.com/mozilla/nucleus/issues/665
Testing is hard because it requires getting in releasenotes data that has `~~` in the markdown. I can a database file with that directly if you want it, with installation instructions
Assuming you've got it
should see ~~test test test~~ in the middle of that message, as per the screenshot above

Support <del></del> in Release Notes markup

---

contentful_migrations/package-lock.json
contentful_migrations/package.json

Minor bumps to contentful-migrations framework, incl remedying security vuln based on dependabot ping
Also moves to node 16, so the lockfileVersion is moved to v2
Tested locally as much as possible without new schemae to change, and appears to be OK

Update contentful-migrations lib and fix vulnerable jsonwebtoken dep

---

docs/abtest.rst
docs/coding.rst
docs/contentful.rst
docs/install.rst
docs/testing.rst

This changeset fixes up broken links in the Bedrock documentation. 
* `cd path/to/bedrock/docs`
* `make linkcheck` - there WILL still be some 404s flagged as broken links, but these are either links to dummy URLs or to private git repos, so they are fine as they are
* `make livehtml` - and confirm the console has nothing to grumble about when starting the Sphinx server

Fix up broken links in documentation

---

bedrock/firefox/templates/firefox/channel/android.html
bedrock/firefox/templates/firefox/new/desktop/base.html
l10n/en/firefox/new/desktop.ftl

Change in title and description at path /en-US/firefox/new/ 
Title and Description for download page at /firefox/new.
Removed release notes link from Android beta on page https://www.mozilla.org/en-US/firefox/channel/android/#beta.
https://github.com/mozilla/bedrock/issues/12370
https://github.com/mozilla/bedrock/issues/12487

Bug Fix for 12370 and 12487

---

bedrock/settings/base.py

Add `skr` to the localized languages.
Note: This may require a `python manage.py update_product_details_files` locally for testing to pull down the latest `product_details`.
- Check the `locales` page includes this locale.
- Check this locale is included in the list of locales at the bottom of the page.

Fix #12553: Enable skr locale

---

bedrock/releasenotes/models.py

Image embedding in Release Notes pages is broken due to a regression. This changeset fixes it by reverting an unnecessary change.
b29693789 was an attempt to improve sanitisation of HTML from markdown, but doing so inadvertently over-escaped some of the HTML tags that were produced by rendering markdown (eg img) because they were not in the allowlist.
Revisiting this, I think it's OK to revert to only sanitising the raw markdown's HTML elements, because any rendered HTML from the markdown is only going to be adding safe HTML tags, based on the spec.
Resolves #12558
Before
```
<li id="note-789315">
<p>Processes used for background tabs now use efficiency mode on Windows 11 to limit resource use.&lt;br /&gt;
&lt;img alt="Efficiency mode on Windows 11" …
```

Only bleach the HTML in the raw markdown content, not the rendered HTML

---

media/css/firefox/whatsnew/includes/_dark-mode.scss

Updated the icon to be white in the WNP dark mode footer.
#12569 

Fix Mastodon icon to be white in WNP's dark mode

---

bedrock/newsletter/templates/newsletter/updated.html
l10n/en/mozorg/newsletters.ftl
media/js/newsletter/form-utils.es6.js
tests/unit/spec/newsletter/form-utils.js
tests/unit/spec/newsletter/unsubscribed.js

Enforces a 500 char maximum field length on the `<textarea>` field on `newsletter/updated` page.
#12539
You need a newsletter token in order to view / test this page locally, which you can [get here](https://www.mozilla.org/en-US/newsletter/recovery/). Once you have a token you can view the page at:
`http://localhost:8000/en-US/newsletter/updated/?unsub=1&token={TOKEN}`

Set maximum field length on newsletter/updated form field (Fixes #12539)

---

bedrock/base/templates/macros-protocol.html
bedrock/careers/templates/careers/benefits.html
bedrock/careers/templates/careers/home.html
bedrock/careers/templates/careers/teams.html
bedrock/contentful/templates/includes/contentful/all.html
bedrock/firefox/templates/firefox/browsers/quantum.html
bedrock/firefox/templates/firefox/channel/base.html
bedrock/firefox/templates/firefox/developer/includes/engage.html
bedrock/firefox/templates/firefox/enterprise/index.html
bedrock/firefox/templates/firefox/features/includes/features-content.html
bedrock/firefox/templates/firefox/features/index.html
bedrock/firefox/templates/firefox/features/picture-in-picture.html
bedrock/firefox/templates/firefox/more/misinformation.html
bedrock/firefox/templates/firefox/new/basic/base_platform.html
bedrock/firefox/templates/firefox/nightly/firstrun.html
bedrock/firefox/templates/firefox/privacy/book.html
bedrock/firefox/templates/firefox/privacy/index.html
bedrock/firefox/templates/firefox/privacy/products.html
bedrock/firefox/templates/firefox/set-as-default/landing.html
bedrock/firefox/templates/firefox/sync.html
bedrock/mozorg/templates/mozorg/home/home.html
bedrock/mozorg/templates/mozorg/moss/index.html
bedrock/pocket/templates/pocket/home.html
bedrock/products/templates/products/vpn/download.html
docs/coding.rst

Simplifies `picto()` macro image handling, so we now pass a single `image` param (as opposed to passing multiple parameters through multiple macros to decide which type of image to render).
#12513
`npm start`

Simplify picto macro image handling (Fixes #12513)

---

media/js/newsletter/management.es6.js

Removes the check for `resp.statusText === 'OK'` as this is returned as an empty string in production (only) in Chrome / Safari. We still check for a successful status code, which should hopefully be enough.
#12595
This is only reproducible on demo.
https://www.mozilla.org/en-US/newsletter/recovery/
`https://www-demo5.allizom.org/en-GB/newsletter/existing/YOUR_TOKEN_HERE/`

Fix newsletter management error in chrome/safari (Fixes #12595)

---

bedrock/products/templatetags/misc.py
bedrock/products/tests/test_helper_misc.py
l10n/en/products/vpn/shared.ftl

In US and Canada where tax is typically not included in the price shown to consumers, show "+ tax" after monthly / total VPN subscription prices.
#12589

Show price + tax for VPN in US and Canada (Fixes #12589)

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Resolves #12601 Bump boto3 from 1.26.45 to 1.26.50 in /requirements 
Resolves #12599 Bump twilio from 7.16.0 to 7.16.1 in /requirements 
Resolves #12598 Bump sentry-sdk from 1.12.1 to 1.13.0 in /requirements 
Resolves #12579 Bump phonenumberslite from 8.13.3 to 8.13.4 in /requirements 
Resolves #12597 Bump requests from 2.28.1 to 2.28.2 in /requirements

2023-01-16 Dependency bumps

---

bedrock/firefox/urls.py
tests/redirects/test_urls.py

Fix 500 when trying to access releasenotes for Android and iOS using the same URL structure as for FF desktop
If a user goes to https://www.mozilla.org/en-US/firefox/releasenotes/ they get redirected to the latest release notes URL for Firefox - eg currently https://www.mozilla.org/en-US/firefox/108.0.1/releasenotes/
However, prior to this changeset, that behaviour didn't exist for mobile FF's release notes - eg the following two links triggered a 500
* https://www.mozilla.org/en-US/firefox/android/releasenotes/
* https://www.mozilla.org/en-US/firefox/ios/releasenotes/
This changeset updates that, so that the URLs for mobile Firefox now redirect to the latest releasenotes for the relevant mobile platform
Resolves #12536 
If relevant:
* `npm …

Fix 500ing releasenotes shortcut page for FF mobile

---

bedrock/firefox/views.py

English whatsnew pages for Firefox 109 promote VPN, which we don't advertise in certain countries. Countries on that list should see the standard WNP page instead.
http://localhost:8000/en-US/firefox/109.0/whatsnew/?geo=us should show the VPN promo
http://localhost:8000/en-US/firefox/109.0/whatsnew/?geo=cn should show the default page

Add EN whatsnew 109 templates to the VPN excluded list [#12541, #12583]

---

media/css/firefox/family/components/_dad-jokes-banner.scss

The `Accept all dad jokes` banner's button didn't have a pointed cursor on hover, so I changed that to include it, just to enhance it's clicking feature.

Add cursor declaration for F3 page banner

---

bedrock/settings/__init__.py

Add region1 to Pocket CSP to allow GA4 to connect and load
https://github.com/mozilla/bedrock/issues/12608

Add region1 to Pocket CSP (fixes #12608)

---

bedrock/settings/__init__.py

Fixes placement of region1 in Pocket CSP (currently under **script**, should be **connect**)
Follow up for https://github.com/mozilla/bedrock/pull/12611
https://dev.tekcopteg.com/en/ shows region1 connect error in console
local does not show error
http://localhost:8000/en/

Move region1 to correct Pocket CSP setting

---

bedrock/careers/templates/careers/diversity.html
bedrock/careers/templates/careers/home.html
media/css/careers/components/hero-video.scss

Remove background video on careers to decrease distraction for users.
(Outline the main things changed, and if there are particular parts that need extra scrutiny.)
See #12619 
http://localhost:8000/en-US/careers/diversity/

Remove background video on careers (#12619)

---

bedrock/careers/templates/careers/position.html

Previously the "Apply Now" button URL for jobs with only a single location was set to go to the cover job URL, not the posting with the job location.
The team also wanted to make the apply button consistent with jobs with multiple locations to make it clearer which location they were clicking through to view. So this simplifies the template logic.

Update job posting page for single location jobs

---

bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/tests/test_helper_misc.py

Updates `resp_img()` helper to support absolute image URLs.
#12625
I added tests but please give this a try locally as well.

Update resp_img() helper to support absolute URLs (Fixes #12625)

---

bedrock/mozorg/templatetags/misc.py

Fixes: https://github.com/mozilla/bedrock/issues/12633
Regression was due to a some copy pasta, which didn't show up locally since there `static()` resolves to a relative path, whereas when deployed image URLs are absolute.
Demo: https://www-demo1.allizom.org/en-US/products/vpn/

Fix picture helper (Fixes #12633)

---

media/css/firefox/family/components/_pro-tip.scss

Add overflow-y: hidden to parental tips to prevent horizontal scroll
Fix #12586

Prevent overflow on parent tips (Fix #12586)

---

Makefile
bedrock/careers/management/commands/sync_greenhouse.py
bedrock/contentful/templatetags/helpers.py
bedrock/contentful/tests/test_templatetags_helpers.py
bedrock/mozorg/templatetags/misc.py
bedrock/releasenotes/models.py
bedrock/wordpress/models.py
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

UPDATE: also now includes:
* [Bump Django to 3.2.17 following security release](https://github.com/mozilla/bedrock/pull/12662/commits/bfe43f6f99106797caa2e2a6decdc8dfd75e2e94)
* Dependency bumps: 2022-01-30
* Resolves https://github.com/mozilla/bedrock/pull/12657 Bump twilio from 7.16.1 to 7.16.2 in /requirements
* Resolves https://github.com/mozilla/bedrock/pull/12654 Bump markupsafe from 2.0.1 to 2.1.2 in /requirements
* Resolves https://github.com/mozilla/bedrock/pull/12653 Bump boto3 from 1.26.50 to 1.26.59 in /requirements
* Resolves https://github.com/mozilla/bedrock/pull/12652 Bump phonenumberslite from 8.13.4 to 8.13.5 in /requirements
* Resolves https://github.com/mozilla/bedrock/pull/12650 Bump sentry-sdk from 1.13.0 to 1.14.0 in /requirements
* Resolves …

2022 01 30  dependency updates

---

bedrock/products/forms.py
bedrock/products/templates/products/vpn/invite.html
l10n/en/products/vpn/landing.ftl
media/js/products/vpn/invite.es6.js
tests/unit/spec/products/vpn/invite.js

Removes the "What platforms are you interested in?" question from the VPN wait-list form.
#12590
http://localhost:8000/en-US/products/vpn/invite/

Remove platform fields from VPN waitlist form (Fixes #12590)

---

bedrock/pocket/templates/pocket/home.html

Added UTM params to the pocket homepage banner that already went live today
- `npm run in-pocket-mode`
- open http://localhost:8000/de

Add utm params to de pocket banner

---

bedrock/base/geo.py
bedrock/base/tests/test_context_processors.py
bedrock/base/tests/test_geo.py
bedrock/mozorg/templates/mozorg/robots.txt
bedrock/mozorg/tests/test_views.py
bedrock/mozorg/views.py
bedrock/settings/base.py

@bkochendorfer has fixed the CDN for us so that it will send the proper Host header for the original behavior to work. We'd like the original behavior back for two reasons:
1. When you access the prod website from the origin domain the robots.txt currently allows crawling because it's the prod infra, but the old way would disallow crawling except at the real prod domain. Blocking crawling of all non-prod domains is best.
2. Some of our integration tests rely on using the `?geo=XX` param for testing against the origin domains, but we don't allow that param to work in prod for security reasons. Allowing the tests to pass on prod infra and non-prod domains is preferable. 
This reverts commit 320e674b6d81a4bbab9c410f28cd4d19ad04154f.

Revert "Fix #12667: Change to using a setting to determine if in prod"

---

media/css/firefox/family/components/_hero.scss

Adds gap between text and logo on larger screens in Family page Hero CTA
https://github.com/mozilla/bedrock/issues/12691
issue
fix
horizontal space creates gap between text and logo

Family: fix horizontal spacing in hero CTA (fixes #12691)

---

media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

Updates the stub-attribution script to allow attribution data to be added to bouncer staging links e.g. https://bouncer-bouncer.stage.mozaws.net/?product=firefox-latest-ssl&os=win&lang=en-US
#12631
1. On a Windows machine, navigate to https://www-demo5.allizom.org/en-US/ and click download
2. Verify the download URL contains `attribution_code` and `attribution_sig` params

Allow stub attribution data to be added to bouncer staging links (Fixes #12631)

---

bedrock/newsletter/templates/newsletter/confirm.html
bedrock/newsletter/templates/newsletter/country.html
bedrock/newsletter/templates/newsletter/management.html
bedrock/newsletter/templates/newsletter/updated.html
bedrock/newsletter/tests/test_views.py
bedrock/newsletter/urls.py
bedrock/newsletter/views.py
docs/newsletters.rst
media/css/newsletter/newsletter-confirm.scss
media/js/base/send-to-device.es6.js
media/js/newsletter/country.es6.js
media/js/newsletter/form-utils.es6.js
media/js/newsletter/management.es6.js
media/js/newsletter/newsletter.es6.js
media/js/newsletter/recovery.es6.js
media/js/newsletter/unsubscribed.es6.js
media/js/products/vpn/invite.es6.js
media/static-bundles.json
tests/unit/spec/newsletter/country.js
tests/unit/spec/newsletter/form-utils.js
tests/unit/spec/newsletter/management.js
tests/unit/spec/newsletter/unsubscribed.js

Removes UUID tokens from basket newsletter URLs. Pages that rely on such URLs will now remove the tokens from the URL path on page load (via the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState)). Tokens are also now stored in a cookie for the front end code to reference instead.
Why make this change? Whilst the token URLs allow people to easily update their newsletter preferences without requiring a frustrating login process, it is possible for users to accidentally leak their own token by sharing the URL. Clicking links to external sites from our pages can also leak the token via `document.referrer` in site analytics. This PR hopefully makes it much harder for users to accidentally share their token.
Given the above is quite a large change, it needs to …

Remove token from newsletter URLs (Fixes #12389)

---

bedrock/contentful/templates/includes/contentful/all.html

Add empty alt attribute for homepage Contentful images so HTML validation passes.
This is not ideal. Ideal is actual descriptive image text! But this is an incremental improvement.

Add empty alt attribute for homepage contentful images

---

bedrock/newsletter/templates/newsletter/management.html
bedrock/newsletter/views.py
l10n/en/mozorg/newsletters.ftl

Updates error message string to link to recovery form when newsletter token has expired.
https://github.com/mozilla/bedrock/issues/12685

Expired token error message should link to recovery form (Fixes ##12685)

---

Dockerfile
docker/gitconfig

Including makring the l10n git repos as "safe".

Fix #12705: Add system git config

---

package-lock.json
package.json

Bumps `@sentry/browser` to latest version
N/A
Set `SENTRY_FRONTEND_DSN=https://c3ab8514873549d5b3785ebc7fb83c80@o1069899.ingest.sentry.io/6260331` in your `.env` if you would like to test that Sentry initializes locally. You'll also need a browser with DNT disabled.

Bump @sentry/browser to v7.31.0

---

bedrock/base/templates/includes/sticky-promo.html

Lazy load images in the sticky promo to improve page load experience.
n/a
Sticky promo appears on http://localhost:8000/en-US/firefox/ Watch the Dev Tools network panel to see that the images are loaded late.

Lazy load images in the sticky promo

---

bedrock/privacy/templates/privacy/base-protocol.html
bedrock/privacy/templates/privacy/notices/base-notice-headings.html
media/css/privacy/privacy-protocol.scss

Tweak the beautiful soup parsing to move the footnote on the Firefox privacy page into the footnote section.
- only add footer element to page if it will not be empty
- extract the full footer section from the body of the privacy notice
- add a visual separator between the footer and other sections  
Fix #12713
See screenshot in #12713 
Check here is a proper footer on:
- http://localhost:8000/en-US/privacy/firefox/
Check I did not break other privacy notices using the same template:
http://localhost:8000/en-US/privacy/firefox-reality/
http://localhost:8000/en-US/privacy/subscription-services/
http://localhost:8000/en-US/privacy/mdn-plus/
http://localhost:8000/en-US/privacy/firefox-reality/
http://localhost:8000/en-US/privacy/hubs/

Move footnote under heading (Fix #12713)

---

bedrock/firefox/templates/firefox/browsers/browser-history.html
bedrock/firefox/templates/firefox/browsers/incognito-browser.html
bedrock/firefox/templates/firefox/browsers/mobile/compare.html
bedrock/firefox/templates/firefox/browsers/mobile/index.html
bedrock/firefox/templates/firefox/browsers/update-browser.html
bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
bedrock/firefox/templates/firefox/developer/includes/features.html
bedrock/firefox/templates/firefox/developer/includes/highlights.html
bedrock/firefox/templates/firefox/developer/includes/intro-features.html
bedrock/firefox/templates/firefox/family/includes/download-firefox.html
bedrock/firefox/templates/firefox/features/bookmarks.html
bedrock/firefox/templates/firefox/features/fast.html
bedrock/firefox/templates/firefox/features/includes/pip-video.html
bedrock/firefox/templates/firefox/features/memory.html
bedrock/firefox/templates/firefox/features/password-manager.html
bedrock/firefox/templates/firefox/features/private-browsing.html
bedrock/firefox/templates/firefox/features/safebrowser.html
bedrock/firefox/templates/firefox/features/translate.html
bedrock/firefox/templates/firefox/firstrun/firstrun.html
bedrock/firefox/templates/firefox/mobile/get-app.html
bedrock/firefox/templates/firefox/mobile/includes/s2d-hero.html
bedrock/firefox/templates/firefox/mobile/index.html
bedrock/firefox/templates/firefox/privacy/book.html
bedrock/firefox/templates/firefox/releases/release-notes.html

Add width to images in to improve rendering speed.
n/a
http://localhost:8000/en-US/firefox/browsers/browser-history/
http://localhost:8000/en-US/firefox/browsers/incognito-browser/
http://localhost:8000/en-US/firefox/browsers/mobile/
http://localhost:8000/en-US/firefox/browsers/mobile/compare/
http://localhost:8000/en-US/firefox/browsers/update-your-browser/
http://localhost:8000/en-US/firefox/features/bookmarks/
http://localhost:8000/en-US/firefox/features/fast/
http://localhost:8000/en-US/firefox/features/memory/
http://localhost:8000/en-US/firefox/features/password-manager/
http://localhost:8000/en-US/firefox/features/safebrowser/
http://localhost:8000/en-US/firefox/features/translate/ …

Add width to images in /firefox

---

media/js/base/fxa-utm.es6.js
tests/unit/spec/base/fxa-utm.js

Passes through organic search referrals (via `document.referrer`) to VPN (and FxA) subscription links.
Also removes support for the old (and unused `?source`) param, which was replaced with the `vpn_product_referral_link()` helper some time ago.
#12706
I found this addon useful for manual testing: https://addons.mozilla.org/en-US/firefox/addon/referer-modifier/
With it you can override the referrer to any value you choose:

Pass search referrals through to VPN subscription link utms (Fixes #12706)

---

bedrock/firefox/templates/firefox/channel/android.html
bedrock/firefox/templates/firefox/channel/desktop.html
bedrock/firefox/templates/firefox/channel/ios.html

Adds the class `mzp-is-anchor-link` to sections on the Firefox channel pages so when we link directly to a section it gets some scroll offset to accommodate the sticky navbar.
#12751 
http://localhost:8000/firefox/channel/desktop/#beta
http://localhost:8000/firefox/channel/android/#beta

Add scroll offset to anchors on channel pages [fix #12751]

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx111-eu.html
bedrock/firefox/views.py
l10n/configs/pontoon.toml
l10n/en/firefox/whatsnew/whatsnew-111-pdf.ftl
media/css/firefox/whatsnew/whatsnew-111-eu.scss
media/static-bundles.json

This is just a stub page in order to get strings ready for l10n ahead of the release of Firefox 111 on March 14. Localized PDFs are forthcoming and we'll eventually need to update the CTA to link to the correct PDF for each locale. We may end up doing something different with the title as well. It could be an image for each language (hence the separate string for alt), but I'm hoping to keep it live text (hence the string with the line break for layout).
The page should only be visible in dev mode so we can merge it ahead of time.
#12720 
http://localhost:8000/es-ES/firefox/111.0/whatsnew/

Stub out WNP 111 page for EU locales [#12720]

---

bedrock/legal/templates/legal/terms/peopleofdeutschland.de.html
bedrock/legal/templates/legal/terms/peopleofdeutschland.html
bedrock/legal/urls.py

Adds legal pages for Pocket raffle
#12699
- http://localhost:8000/en-US/about/legal/terms/peopleofdeutschland/
- http://localhost:8000/de/about/legal/terms/peopleofdeutschland/

Add T&C legal page for Pocket PoD raffle (Fixes #12699)

---

media/css/protocol/common-old-ie.scss
media/css/protocol/protocol-firefox.scss
media/css/protocol/protocol-mozilla.scss
media/js/careers/testimonials-modal.es6.js
media/js/foundation/annual-report-modal.es6.js
package-lock.json
package.json

Change log https://github.com/mozilla/protocol/blob/main/CHANGELOG.md
- Removes redundant `[hidden]` selectors which are now in protocol's base style sheets
- Removes modal focus workarounds which have since been fixes 
#12759
Demo: https://www-demo3.allizom.org/en-US/
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/779927308

Update protocol/core to v16.1.0 (Fixes #12759)

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2022.html
bedrock/mozorg/urls.py

Adds Transparency Report page for H2 2022. The EU MAU numbers have a hard legal deadline, so this needs to go live tomorrow (Friday 17th Feb).
#12748
http://localhost:8000/en-US/about/policy/transparency/jul-dec-2022/

Add Transparency Report H2 2022 (Fixes #12748)

---

bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2022.html

Somehow I accidentally left in a duplicate table, which needs removing

Remove duplicate table from Transparency Report

---

bedrock/settings/__init__.py
media/js/pocket/analytics.es6.js

Updated the Pocket Marketing pages to use v3 of Snowplow analytics 
#12727 
- Run tests locally with `npm run test` to ensure the unit tests pass
- http://localhost:8000 and see that snowplow has been loaded

Migrate snowplow to v3 for pocket marketing pages

---

media/static-bundles.json

Removes duplicate bundle that was accidentally added in https://github.com/mozilla/bedrock/pull/12767
N/A

Remove duplicate JS bundle from static-bundles.json

---

bedrock/pocket/templates/pocket/includes/footer-platform.html
media/css/pocket/includes/_platform-footer.scss

Ensures all pocket marketing pages have a "Cookie preferences" link, as per: https://help.getpocket.com/article/1163-pocket-website-cookies-faq
The footer here could really use a larger CSS refactor to make it more scalable for adding new links. I had to tweak a few things to make it play nice. But then I started down the path of why we even have two footers and not just one, so for now I think this is the quickest fix.
#12678
http://localhost:8000/en/

Add missing cookie preferences link to pocket platform footer (Fixes #12678)

---

bedrock/pocket/templates/pocket/includes/mobile-nav.html
bedrock/pocket/templates/pocket/includes/nav.html
bedrock/security/templates/security/bug-bounty/web-eligible-sites.html

We created a switch to have a wording change ready for Oct. 31, 2022. We no longer have need for this logic.
https://github.com/mozilla/bedrock/issues/12284
If relevant:
POCKET MODE
MOZORG MODE

Remove pocket saves switch (fixes #12284)

---

lib/l10n_utils/templatetags/fluent.py
lib/l10n_utils/tests/test_templatetags.py

This changeset adds a layer of protection against unexpected markup being introduced via Fluent strings as part of the localisation process.
We now use `bleach` to sanitise each Fluent string's content before declaring it as safe for Django to render without further escaping (which we do via `Markup`).
The sanitisation only allows a specific, small, set of HTML tags and attributes to be allowed through; everything else will be escaped.
We've drawn our initial set of allowed tags and attributes from the current en-US fluent templates in the repo, following the logic that: a) we trust these because we added them; and b) if someone tries to add in malevolent markup via a Fluent string in a particular locale, we _should_ be sanitising that because the translation should use the same tags and …

Support sanitisation of Fluent strings before rendering

---

bedrock/newsletter/templates/newsletter/management.html

Fix HTML leaking into the prefs page
This appears to be a subtle regression via https://github.com/mozilla/bedrock/pull/12730 where we introduced sanitisation of strings sourced by `ftl()` using the `bleach` library. UPDATE: I think it's actually `html5lib`, used by `bleach` that is doing the "fixing" of the markup.
I've tried to keep the fix as light as possible, retaining calls to `|escape`.
Resolves #12789 
Before/Broken
After/Fixed

Fix leakage of HTML for JS errors into the main newsletter prefs page

---

bedrock/newsletter/templates/newsletter/management.html
media/js/newsletter/management.es6.js
tests/unit/spec/newsletter/management.js

This is a potentially more robust fix for #12789 that moves the error strings from data attributes to regular HTML that's in the DOM. This should hopefully avoid the need for any tricky escaping.
#12789

Fix data string escape leakage by moving error strings to the DOM (Fixes #12789)

---

bedrock/firefox/tests/test_helpers.py
tests/pages/firefox/all.py
tests/pages/firefox/new/thank_you.py

This changeset should fix CI on Dev, by making sure tests seek the download bouncer domain that is configured for the relevant enviroment (Dev, Test, Stage, Prod). Only Dev points to the Staging bouncer.
* JS tests pass (tested locally)
* Integration tests were run with `BOUNCER_URL` forced/hard-coded to the Staging bouncer url. All passed.
* Local commit hard-coding it: 
`* 618fab990 (HEAD -> hotfix-failing-dev-ci-tests, mozilla/run-integration-tests) DISCARD ME LATER: TEMPORARILY FORCE BEDROCK TO USE THE STAGING BOUNCER JUST TO RUN INTEGRATION TESTS (29 minutes ago)`
* CI passing for that commit: https://gitlab.com/mozmeao/www-config/-/pipelines/786774127
* You can see that 618fab990 is not a commit in this PR, because it's been dropped from the branch
No ticket.
Demo server URL: (or …

Make browser tests use whatever is set as BOUNCER_URL when checking for a download URL

---

bedrock/base/templates/includes/banners/fundraiser.html
bedrock/base/templates/includes/protocol/footer/footer.html
bedrock/foundation/templates/foundation/annualreport/2009/broadening-our-scope.html
bedrock/foundation/templates/foundation/annualreport/2021/index.html
bedrock/foundation/templates/foundation/openwebfund/more.html
bedrock/mozorg/templates/mozorg/contact/contact-landing.html
bedrock/mozorg/templates/mozorg/contribute.html
bedrock/mozorg/templates/mozorg/home/home-contentful.html
bedrock/mozorg/templatetags/misc.py
bedrock/mozorg/tests/test_helper_misc.py
bedrock/settings/base.py

- Adds `c_id` param to all donation links for Sales Force attribution.
- Alse hard codes `utm_campaign=moco` to all donation links.
#12796

Add Sales Force param to donation links (Fixes #12796)

---

bin/compile-requirements.sh
requirements/dev.txt
requirements/docs.in
requirements/docs.txt
requirements/prod.in
requirements/prod.txt

#12810  Bump boto3 from 1.26.74 to 1.26.79 in /requirements
#12808  Bump whitenoise from 6.3.0 to 6.4.0 in /requirements
#12807  Bump twilio from 7.16.3 to 7.16.4 in /requirements
#12805  Bump django-cors-headers from 3.13.0 to 3.14.0 in /requirements
#12799  Bump markdown-it-py from 2.0.1 to 2.2.0 in /requirements

2023-02-27 Dependency bumps

---

tests/functional/test_contact.py

The most recently added Mozilla spaces (on the [contact page](https://www.mozilla.org/en-US/contact/spaces/)) are not tested by test_spaces_menus ([test_contact.py ](https://github.com/mozilla/bedrock/blob/main/tests/functional/test_contact.py)) as the input hasn't been updated with Paris and Beijing.
The spaces input has been updated with Paris and Beijing.
N/A
N/A
N/A

Update input for test_spaces_menu

---

media/js/pocket/mobile-nav-init.es6.js
media/js/pocket/mobile-nav.es6.js
tests/functional/pocket/test_navigation.py
tests/pages/pocket/base.py
tests/unit/spec/pocket/mobile-nav.js

Simplifies mobile nav logic by removing the transitionend event and toggle class function.
Updated test to check for button display on desktop size
Removed transitionend event listener (no obvious effect on styling, unnecessary for functional or testing, might have been left over from a previous approach)
https://github.com/mozilla/bedrock/issues/12677
Note: I wasn't able to recreate the scroll issue locally

Fix pocket intermittent scrolling issue (fixes #12677)

---

bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
docs/firefox-stub-attribution.rst
media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

- Adds a new `session_id` parameter to stub attribution that contains the GA session ID.
- Renames `visit_id` to `client_id` as to be more technically correct / less confusing.
This change has already been tested end-to-end by QA against demo3, so code-level review should be all that's really required here. If you would like to manually test things still, there are testing steps below for the bedrock side of things.
#12355
1. On a Windows machine, open https://www-demo3.allizom.org/en-US/
2. Inspect cookies using dev tools and look for a cookie called `moz-stub-attribution-code`. The value should be a base64 string.
3. [Decode](https://www.base64decode.net/) the cookie value and verify it has both a `client_id` and `session_id` parameter.

Add GA session_id to stub attribution data (Fixes #12355)

---

tests/pages/pocket/base.py

Fixes: https://gitlab.com/mozmeao/www-config/-/jobs/3896135830
N/A
Note: failure only happens in Chrome, so you'll need [chrome driver](https://chromedriver.chromium.org/home) installed to test locally
`BASE_POCKET_URL=http://localhost:8000 py.test -m pocket_mode --driver Chrome --html tests/functional/results.html tests/functional/pocket/test_navigation.py`

Fix intermittent test failure for pocket/test_navigation.py

---

setup.cfg
tests/functional/firefox/family/test_family.py
tests/functional/pocket/test_navigation.py

Spotted a few tests that were missing the `nondestructive` pytest mark and are still OK to be run against prod.
This PR also updates `sensitive_url` so we can distinguish the [new infra](https://prod.bedrock.prod.webservices.mozgcp.net/en-US/) in tests that might be considered sensitive should we need/want to (I don't think we currently have any though).

Mark Pocket and Family pages tests as non-destructive

---

.github/workflows/pull_request_tests.yml

This should hopefully stabilise CI tests running on the main `mozilla` origin, but it may not work for forks of this repo.
Example of the failure we're trying to avoid https://github.com/mozilla/bedrock/actions/runs/4404509648/jobs/7714206696

Try supplying a CodeCov token to sidestep issues where the build can't be found via GHA's API

---

bedrock/mozorg/templates/mozorg/about/governance/policies/policies.html
bedrock/mozorg/templates/mozorg/about/governance/policies/social-content-policies.html
bedrock/mozorg/urls.py
media/css/mozorg/social-content-policies.scss
media/static-bundles.json

Adds content policy page for mozilla.social
#12865
http://localhost:8000/en-US/about/governance/policies/social-content-policies/

Add content poilicy page for mozilla.social (Fixes #12865)

---

bedrock/firefox/templates/firefox/browsers/mobile/focus.html

Changes `res_img()` calls to use explicit parameter names
#12871
http://localhost:8000/en-US/firefox/browsers/mobile/focus/

Fix res_img parameters on Firefox Focus page (Fixes #12871)

---

bedrock/mozorg/templates/mozorg/about/governance/policies/social-content-policies.html

Fixes a typo in the mailto: part of an email address (`mozilla.co` instead of `mozilla.com`)
Spotted with www-site-checker
Resolves https://github.com/mozmeao/www-site-checker/issues/172
Before
After

Fix typo in mailto address for DMCA contact

---

.github/workflows/pull_request_tests.yml

This should stop things like https://github.com/reemhamz/bedrock/actions/runs/4527910198/jobs/7974199028 I am hoping, but there's commentary around in other issues that suggests it might not be a silver bullet.

Stop CodeCov failing CI if it errors out

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx112-eu-privacy.de.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx112-eu-privacy.fr.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx112-eu-privacy.uk.html
bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx112-eu-translate.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
media/css/firefox/whatsnew/whatsnew-112-eu-privacy.scss
media/css/firefox/whatsnew/whatsnew-112-eu-translate.scss
media/js/firefox/whatsnew/whatsnew-112-eu-privacy.js
media/static-bundles.json
tests/functional/firefox/whatsnew/test_whatsnew_112.py
tests/pages/firefox/whatsnew/whatsnew_112.py

Adds WNP 112 for EU.
#12905
Note: you'll need [UITour](https://bedrock.readthedocs.io/en/latest/uitour.html#local-development) set up for local dev for the conditional CTAs to work.
"Set Firefox as default" CTA, or Protection Report CTA if Firefox is already default.
Firefox Translate add-on CTA:

WNP 112 EU (Fixes #12905)

---

bedrock/legal/urls.py

Not urgent, but makes things consistent.

Add trailing slash to builders challenge t&c URL

---

bedrock/legal/templates/legal/terms/builders-challenge.html

I forgot to add the word `phone` in the last point (point 15)

Add missing word to Builders Challenge T&C

---

docs/contentful.rst

Updates Contentful docs with latest info
- outlines use of Contentful Apps
- adds naming for a Compose Page's rich text field
- adds instructions for creating new Compose Page
- adds notes on limitations
- fixes list semantics at end of l10n Smartling section
no bug
Local: from docs folder, run `make livedocs`

Update Contentful docs [no bug]

---

.github/workflows/integration_tests.yml

We switch to using if: always() for each step to keep the GHA going when some steps fail, rather than continue-on-error, because that approach falsely marks the overall test suite as green/passed even if it has some failures.

Amend GHA to fail if integration tests fail, but try all permutations

---

bedrock/pocket/templates/pocket/add.html
l10n-pocket/en/pocket/add.ftl
media/css/pocket/components/add.scss

Updates to better match the prod /add page
https://github.com/mozilla/bedrock/issues/12494
Run in pocket mode
top headline should go across section
app integration section
- should have typo fixed
- sets 2 icons per row on larger screens, as we only have 4 working links

Fixes for pocket add page (fixes #12494)

---

bedrock/pocket/templates/pocket/license-ios.html
bedrock/pocket/templates/pocket/privacy.html
bedrock/pocket/templates/pocket/tos.html
bedrock/pocket/urls.py
media/css/pocket/components/legal-pages.scss
media/static-bundles.json

Hard-coded in the list of licenses for all packages used for Pocket's iOS app.
The copy can be found here: https://docs.google.com/document/d/16trRWFNBsQrfusdISL4BXchSkkOCWVOQp_X6tOtCFtw/edit
**No L10N needed**
#12910 
📝 Make sure to run `npm run in-pocket-mode` or `make run-pocket`

Set up Pocket iOS license page

---

bedrock/mozorg/views.py
bin/run-db-update.sh

This changeset removes syncing the PocketArticle model during the DB update (it's no longer getting data back), and also stops trying to load in PocketArticle records on the Mozorg homepage, because we no longer show them so it's redundant.
A ticket has been made to complete the cleanup: https://github.com/mozilla/bedrock/issues/12986
Resolves #12985 

Disable PocketArticles feed sync

---

bedrock/newsletter/templates/newsletter/knowledge-is-power.html
bedrock/newsletter/urls.py

Adds Knowledge is power newsletter variation page with variation `rise25`
#12988 
standard page: http://localhost/newsletter/knowledge-is-power/
variant page: http://localhost/newsletter/knowledge-is-power/?v=rise25

Knowledge is power newsletter variation page

---

bedrock/mozorg/templates/mozorg/rise25/includes/rise25-social-share.html
bedrock/mozorg/templates/mozorg/rise25/rise25.html
media/css/mozorg/rise25.scss
media/js/mozorg/rise25.js

Fixes a couple of small issues on the rise 25 page (mostly around the video section, but I noticed a couple of other small validation errors as well in the process):
- Tweaks main heading sizing/spacing on smaller viewports for slightly better readability.
- Updates video hero placeholder to use an `<a href="#">`, since `<div>` is not a valid child element of `<button>`.
- Renames `role="external noopener noreferrer"` to `rel="external noopener noreferrer"`.
- Removes invalid `title` attributes from inline `<svg>` elements.
Note: the hero video still needs a hover/focus state of some sorts, but I didn't try and tackle that here as it may require some further design input?
N/A
http://localhost:8000/en-US/rise25/

Rise 25 minor fixes

---

bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json
bedrock/newsletter/templates/newsletter/security-privacy-news.html
bedrock/newsletter/urls.py
l10n/en/mozorg/newsletters.ftl
media/css/newsletter/newsletter-firefox.scss
media/css/newsletter/newsletter-knowledge-is-power.scss
media/css/newsletter/newsletter-security-privacy-news.scss
media/static-bundles.json
tests/functional/newsletter/test_newsletter_embed.py
tests/pages/newsletter/security_privacy_news.py
tests/unit/spec/newsletter/data.js

Adds a standalone subscription page for the Security & Privacy News newsletter.
Primary stakeholders are Tina Rattliff and Mike Altman so check with them for any changes/approvals.
There is an email planned for some time during the week of 17-21 April that will refer to this page so it needs to be live before that email can be sent (and we need to let Tina know the URL).
#12983 
http://localhost:8000/newsletter/security-and-privacy/

Add Security & Privacy newsletter subscription page [fix #12983]

---

bedrock/products/templates/products/vpn/download.html
l10n/en/products/vpn/download.ftl
media/css/products/vpn/download.scss

I forgot to add the CTA for older VPN downloads on the new VPN download page in #12980 
https://github.com/mozilla/bedrock/issues/11875

Add Old VPN Versions CTA to Downloads page

---

l10n/en/products/vpn/download.ftl

Updated the string from `Download previous versions` to `Download previous versions for Windows and Mac`. VPN Eng team requested the update. It's connected to https://github.com/mozilla/bedrock/issues/11875

Updated string for VPN Download CTA

---

media/js/base/site.js
tests/unit/spec/base/site.js

Updates bedrock's UA detection to flag macOS 10.11 (El Capitan) and below as unsupported, as per https://www.mozilla.org/en-US/firefox/112.0.1/system-requirements/
Does my feeble regex look OK?
#13013
This is the message people should see on El Capitan when clicking download and viewing the `/thanks/` page:
This is on demo 3 for easier review: https://www-demo3.allizom.org/firefox/new/

Flag macOS 10.11 as unsupported when downloading Firefox (Fixes #13013)

---

bedrock/firefox/templates/firefox/features/translate.html
l10n/en/firefox/features/translate.ftl

Adds the Firefox Translations addon to the Translate feature page. 
#12771
http://localhost:8000/firefox/features/translate/

Add Firefox Translations addon to /features/translate [fix #12771]

---

l10n/en/firefox/features/translate.ftl

Fixes https://github.com/mozilla/bedrock/issues/13044

Fix typo in firefox/features/translate page (Fixes #13044)

---

.pre-commit-config.yaml
.stylelintrc
package-lock.json
package.json

First step in resolving https://github.com/mozilla/bedrock/security/dependabot/63
https://stylelint.io/migration-guide/to-15/
N/A

Update stylelint to v15.6.0

---

bedrock/firefox/tests/test_views.py
bedrock/firefox/views.py
docs/firefox-stub-attribution.rst
media/js/base/stub-attribution.js
tests/unit/spec/base/stub-attribution.js

Adds a new `dlsource` field to stub attribution, with a value of `mozorg`.
This is requested by the Firefox team so that we can distinguish downloads that come from mozorg, and downloads that come from https://archive.mozilla.org/ (which will use`dlsource=mozillaci`).
This has already been approved by Firefox QA on demo1, but I included instructions below for some additional manual testing.
#12836
1. On a Windows machine, open https://www-demo1.allizom.org/en-US/
2. Inspect cookies using dev tools and look for a cookie called `moz-stub-attribution-code`. The value should be a base64 string.
3. [Decode](https://www.base64decode.net/) the cookie value and verify it has both a `dlsource` parameter it's value is `mozorg`

Add new dlsource field to stub attribution (Fixes #12836)

---

bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx113-eu.html
bedrock/firefox/tests/test_base.py
bedrock/firefox/views.py
media/css/firefox/whatsnew/whatsnew-113-eu.scss
media/js/firefox/whatsnew/whatsnew-113-eu.js
media/static-bundles.json
tests/functional/firefox/whatsnew/test_whatsnew_113.py
tests/pages/firefox/whatsnew/whatsnew_113.py

- Repurposes https://www.mozilla.org/en-US/firefox/welcome/10/ strings for WNP 113.
- Adds a new hard-coded string to WNP for coupon code.
#12961
- GB: https://www-demo3.allizom.org/en-GB/firefox/113.0/whatsnew/
- FR: https://www-demo3.allizom.org/fr/firefox/113.0/whatsnew/
- DE: https://www-demo3.allizom.org/de/firefox/113.0/whatsnew/
- IT: https://www-demo3.allizom.org/it/firefox/113.0/whatsnew/
- ES: https://www-demo3.allizom.org/es-ES/firefox/113.0/whatsnew/
- NL: https://www-demo3.allizom.org/nl/firefox/113.0/whatsnew/
- SV: https://www-demo3.allizom.org/sv-SE/firefox/113.0/whatsnew/
- FI: https://www-demo3.allizom.org/fi/firefox/113.0/whatsnew/

Add WNP 113 for EU (Fixes #12961)

---

bedrock/firefox/views.py

Replaces https://github.com/mozilla/bedrock/pull/13062
#12961
When `Dev=False` in your `.env`:

Activate en-GB locale for WNP 113 (Issue #12961)

---

README.md

Token change to run through the full infra pipelines

Remove CircleCI badge, because we don't use it any more

---

bedrock/products/redirects.py
tests/redirects/map_globalconf.py

The way the regex was before this change, a request to the URL with a
trailing slash was a 404, but with this change both with and without
will redirect.

Fix VPN what-is-a-vpn redirect to include a trailing slash

---

.github/workflows/send_mozorg_fluent_strings_to_l10n_org.yml
.github/workflows/send_pocket_fluent_strings_to_l10n_org.yml
.gitlab-ci.yml

Moves the call to the ftl-PR shell scripts out of the Gitlab config and into GH Actions
Resolves #13051

Move Fluent-PR-opening CI tasks from GL to GHA

---

bedrock/base/templates/base-protocol.html
bedrock/base/templates/includes/protocol/footer/footer.html
bedrock/mozorg/templates/mozorg/about/leadership/index.html

Also add the old account to the header so that the old account will remain verified as it was our official account for a time.
Also update the link to the account for Steve Teixeira as he has also migrated his account.
The [docs for verified links](https://docs.joinmastodon.org/user/profile/#verification) suggest that both of these should work fine.

Update Mastodon social footer link to mozilla.social

---

bedrock/firefox/views.py

I inadvertently added back the Fluent file check for the page, which breaks for en-GB. We don't actually need that check after all (all locales are already active). See https://github.com/mozilla/bedrock/pull/13063/files#diff-4fec82465cd60d028a383c064b7ea42028d1ae3ce15a98ee0dbdf4330578d385L595
With `DEV=False` http://localhost:8000/en-GB/firefox/113.0/whatsnew/ should display the VPN page, not the default.

Fix view for EU WNP 113
